- osu.Framework/Configuration/ConfigManager.cs
this was missing to if you would use Set it would use the generic Bindable instead of BindableBool
> Add missing Set for bool type in ConfigManager

- osu.Framework/Graphics/Containers/BoundsBypassContainer.cs
- osu.Framework/Graphics/Containers/ProcessingContainer.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/UserInputManager.cs
- osu.Framework/osu.Framework.csproj
- Input should be fed in to the draw tree even when "outside" the `BasicGameHost` (else the cursor stops at the edge.
- If a drawable handles `OnMouseDown`, it should be the only drawable allowed to handle `OnClick`.
- `OnMouseUp` events should be sent to the same input queue that `OnMouseDown` was sent to, regardless of if the mouse moved.
> Mousedown handling improvements

- osu.Framework/Graphics/Sprites/SpriteCircular.cs
This is untested and should get its own testcase, but I am confident it should work. Will make one this weekend if nobody else does it before.
> Fix circular sprite hover radius not working with inhomogeneous scaling.

- osu.Framework/Graphics/UserInterface/TextBox.cs
pressing right when you selection ends at the end of the text clears the selection now
same with pressing left at the beginning of the text
ctrl+selection fixes:
ctrl+move selected text without holding shift doesn't move in weird ways anymore
> fixed different text box behavior with selections.

- osu.Framework/OS/GLControl.cs
version.Split(' ')[0] throws ArgumentException if you are connected via RDP.
Here are my GL.GetString(StringName.Version) results for different cases:
MSI GX680 via RDP: OpenGL ES 3.0 (ANGLE 2.1.0.0d79a9db3d42)
MSI GX680 without RDP: 4.5.0 NVIDIA 365.10
Surface Pro 2 without RDP: 4.3.0 - Build 20.19.15.4501
I did not try it on Linux, but on Windows it looks ok :)
> Fix ArgumentException in GLControl.Initialize (RDP).

- osu.Framework/Graphics/Shaders/ShaderPart.cs
compileLog isn't used in release mode
This also removes a `GetShaderInfoLog` call for every shader unit in release mode, which should save a tiny bit of memory/reduce allocations + one less GPU call
> Fixed unused variable warning in release mode

- osu.Framework.VisualTests/Tests/TestCaseCheckBoxes.cs
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/Graphics/UserInterface/BasicCheckBox.cs
- osu.Framework/Graphics/UserInterface/CheckBox.cs
- osu.Framework/osu.Framework.csproj
The feature that kickstarted the movement of ```Padding``` to ```Container``` and helped Peppy and me discover ```FlowContainer```s were applying their ```Spacing``` to the edges when they shouldn't.
A Simple abstract container with two ```CheckBoxState```s, ```CheckBoxState.Unchecked``` and ```CheckBoxState.Checked```, has two overridable methods ```OnChecked()``` and ```OnUnchecked()```
Provides one Subclass: ```BasicCheckBox```, this brings a basic UI featuring a White/Cyan Box based on state, and one clickable label with properties to alter that label's text and padding
> Adds CheckBoxes and a TestCase

- osu.Framework/Graphics/Drawable_TransformationHelpers.cs
Before this, inmediate transformations with delay (e.g. `drawable.Delay(duration); drawable.FadeOut();`) wouldn't be applied.
> Fix unapplied transforms with no delay and duration = 0

- osu.Framework.Desktop.Tests/Benchmark/BenchmarkTests.cs
- osu.Framework.Desktop.Tests/Platform/HeadlessGameHostTest.cs
- osu.Framework.Desktop/Platform/DesktopGameHost.cs
Looks to have been running in parallel with the BenchmarkTest in some cases, which caused a port bind conflict.
> Fix IPC test case failing at random

- osu.Framework.VisualTests/Tests/TestCaseAutosize.cs
- osu.Framework.VisualTests/Tests/TestCaseMasking.cs
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/GameModes/Testing/TestCase.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable_TransformationHelpers.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/Transformations/TransformScale.cs
- osu.Framework/Graphics/Transformations/TransformSize.cs
- osu.Framework/Graphics/UserInterface/Button.cs
- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
- osu.Framework/osu.Framework.csproj
Not sure if this is faster or slower compared to just drawing additional quads with increased size underneath. In my (rudimentary) performance testing this didn't seem to affect FPS at all, but I suspect I was not fill-rate limited.
> Add border feature to masking containers.

- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
In the future we have to do wrapping at a shader level since we use atlases.
> Remove texture wrapping at a texture level.

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/InputManager.cs
Gives minor (~5-10%) speedup in our tests, but has big potential cost savings in the future e.g. on the options scrollbar.
> Don't check for input on masked-away drawables.

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable_Interaction.cs
- osu.Framework/Input/Handlers/ICursorInputHandler.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseState.cs
This code may become a bit nicer if we expose the input clock within drawables. More specifically, the member variables https://github.com/ppy/osu-framework/commit/cd565e125ec0095a83d54bb7eb892c4209359606#diff-35bbcf584966891fe1dcd0f8f38d5f80R138 will then not be needed.
> Better scrolling

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Input/InputManager.cs
Currently, `Container<T>` cannot cast to anything but `IContainer<T>`.
FlowContainer<Box> container = new FlowContainer<Box>();
IContainer<Box> iBox = container as IContainer<Box>; // iBox ok
IContainer<Drawable> iDrawable = container as IContainer<Drawable>; // iDrawable = null
As a consecuence, many scenarios are not possible. For instance:
void DoStuff(Drawable drawable)
{
IContainer<Drawable> container = drawable as IContainer<Drawable>;
if (container != null)
foreach (Drawable child in container.Children)
DoChildStuff(child);
}
DoStuff(new FlowContainer<Drawable>()); // will iterate over children
DoStuff(new FlowContainer<Box>()); // will NOT iterate over children
This is important, as this is actually what happens when queuing mouse events; for `Container<T>` where `T` is not …
> Covariance/contravariance for Containers [proposal]

- osu.Framework.VisualTests/Tests/TestCaseColourGradient.cs
- osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs
- osu.Framework/Graphics/Colour/ColourInfo.cs
- osu.Framework/Graphics/Colour/SRGBColour.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/ContainerDrawNode.cs
- osu.Framework/Graphics/DrawInfo.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Drawable_TransformationHelpers.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/Transformations/TransformColour.cs
- osu.Framework/Graphics/UserInterface/Button.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- osu.Framework/MathUtils/Interpolation.cs
- osu.Framework/osu.Framework.csproj
Not 100% sure if this makes things simpler or more complicated for the end user.
> Encapsulate away linear and sRGB conversions from Drawable and Container.

- osu.Framework.VisualTests/Tests/TestCaseAutosize.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
This moves the Margin property over to Drawables. Conceptually, this simplifies the following: The DrawRectangle (and the ScreenSpaceDrawingQuad) of containers now corresponds to only their visible region and not the entire region including the margin.
Also, this PR adds additional tests for nested margins with scale applied, and for margins applied directly to drawables.
> Make Margin a property of Drawable instead of Container.

- osu.Framework/BaseGame.cs
Reasoning: They currently trigger font atlas loads (framework) which could delay game loading.
in the future we may want to avoid loading these elements until they are first used or similar.
> Move debug tools to background loading.

- osu.Framework/Audio/Track/AudioTrackBass.cs
Fix for [Game freezes after finishing theme song](https://github.com/ppy/osu/issues/162) issue.
> Game freezes after finishing theme song

- osu.Framework/Input/InputManager.cs
TransformState needs to be aware if the current state frame it is handling has keyboard/mouse states or not.
> Don't add previous states to CurrentState until after TransformState is run.

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
Note that due to the nature of FlowContainer, the elements animate from (0,0), which looks wrong.
> Fix log overlay not displaying properly.

- osu.Framework/Graphics/Sprites/SpriteText.cs
For https://github.com/ppy/osu/pull/202 , it's just so the Shadows can be darker to match the designs, I chose to expose it rather than simply make all shadows darker because customisation is king, but feel free to ask for that. or to close this (in which case I'll adjust my other PR to use current shadows)
> Exposes SpriteText's shadow colour as a property.

- osu.Framework/Graphics/Containers/Container.cs
This is for scenario that `Add` is doing something to the item. Example: `KeyCounterCollection`.
Reason for modifying `Children` is that it's already virtual, so acceptable for calling virtual method.
> Make Container.Children calling Add instead of AddInternal.

- osu.Framework.Desktop/Platform/HeadlessGameHost.cs
- osu.Framework/Platform/BasicGameHost.cs
- osu.Framework/Threading/GameThread.cs
Uses an EventWaitHandle to block threads waiting for other threads to finish initializing.  On game shutdown uses Thread.Join() to wait for threads in the process of terminating.
> Eliminate busy wait loops for game thread synchronization

- osu.Framework/Graphics/Drawable_TransformationHelpers.cs
Discovered this while cleaning/fixing up https://github.com/ppy/osu/pull/202
For example:
A Parent Container of dimensions 1000x1000
A Child Drawable of Relative Position 0.5fx0.5f
So Child's position is 500x500
If you the tell Child to MoveToX(0.9f), the expected outcome is for it to be at 900x500, the actual outcome is different, the Transforms all work with a "start value", for the relative transitions to work, the start value here should be 0.5f, but is instead 500 (0.5f *Parent.ChildSize.X), this has the effect of applying the Parent.ChildSize.X at every step of the transformation (because it's pre-multiplied), which essentially leads to the drawable disappearing at the beginning of the transform and reappearing at the end.
This has now changed how Drawables react to position …
> Position Transforms now correctly handle RelativePositionAxes, always use Position instead of DrawPosition

- osu.Framework/IO/File/FileSafety.cs
- osu.Framework/Platform/BasicStorage.cs
If the gameName given contains invalid path or file name characters, the Logger will have issues later.
This should strip out invalid characters before that happens.
For example, ":theori" crashes the Logger.
> Add sanity check to dissalow invalid file paths

- osu.Framework/GameModes/GameMode.cs
Was pretty ugly having to call DisplayAsRoot everr time (and a testcase missed out on it soooo).
> Remove DisplayAsRoot (handled automatically now).

- osu.Framework.Desktop/Platform/DesktopStorage.cs
- osu.Framework/Extensions/GeneralExtensions.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Platform/BasicGameHost.cs
- osu.Framework/Platform/BasicStorage.cs
Until now, exceptions have been thrown out and ignored when inside Task.Run blocks, which can regularly leave the framework in an unrecoverable state (to the point you can't close the window).
This resolves that by throwing the exceptions. Note this doesn't yet gracefully handle exceptions, it just ensures the application crashes.
> Exception handling (and a bit of log tidying)

- osu.Framework.Desktop/Platform/DesktopGameWindow.cs
- osu.Framework.Desktop/Platform/Windows/WindowsGameWindow.cs
- osu.Framework.Desktop/osu.Framework.Desktop.csproj
- osu.Framework/BaseGame.cs
- osu.Framework/Platform/BasicGameWindow.cs
- osu.Framework/osu.Framework.csproj
Uses .NET Framework internals to implement Drag&Drop events
for the WindowsGameWindow. The events themselves are defined on
BasicGameWindow so that other platforms can use the same event
infrastructure later on by manually creating the necessary EventArgs.
Further, OnDroppedFile has been changed to OnDroppedFiles and receives
a string[] instead of a single string. This is to keep symmetry between
OnDroppedFiles and OnDragEnterFiles.
Should be noted that the changes for WindowsGameWindow.cs are worth reviewing. The usage of .NET Framework internals there may cause breakage when those internals change (which, unlike the public .NET Framework API, is something that can happen).
Arguably, it's very unlikely that it will ever break, and if it does, all that happens is that drag&drop on windows …
> Implement Drag&Drop for Windows

- osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Drawable_Interaction.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/osu.Framework.csproj
- Makes focus requesting a non-explicit call.
- Makes it possible for focus requests to be made by multiple drawables; the highest in keyboard priority is chosen.
- Adds the ability to trigger a recalculation of what should have focus (by forcefully unfocusing oneself and letting nature take its course).
> Focus improvements

- osu.Framework/Graphics/Colour/SRGBColour.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Drawing one triangle by drawing two smaller triangles! 💯 
Still better than back when we draw triangles by drawing a quad (which was also two triangles) with a triangle-shaped texture.
> Make EdgeSmoothness work on non-bottom sides of triangles.

- osu.Framework/Audio/AudioManager.cs
Previously we considered disabled audio devices as available (although
playback was blocked). This commit treats them as if they don't exist.
> Only consider enabled audio devices

- osu.Framework.VisualTests/Tests/TestCaseAutosize.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Drawable_Interaction.cs
- osu.Framework/Input/InputManager.cs
This PR contains two major performance optimizations:
- We avoided the need of an expensive cast operation in input queue construction
- We cache DrawSize to avoid expensive recursive walks up the scene graph with over-all O(n²) complexity
(pair programmed with @default0 )
> Refactor and improve performance

- SampleGame/SampleGame.csproj
- osu.Framework.Desktop.Tests/osu.Framework.Desktop.Tests.csproj
- osu.Framework.Desktop/osu.Framework.Desktop.csproj
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/osu.Framework.csproj
With `TreatWarningsAsErrors` set to true, even warnings would prevent successful compilation.
> Prevent warnings as errors

- osu.Framework/GameModes/GameMode.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
A series of changes which bring the performance of draw vis from "grinding to a halt in the main menu when visualizing a bunch of triangles" to "can zoom out fully inside song select with 120 fps".
Also makes behavior slightly nicer by fixing input regressions related to overlay container changes, and making the root visualised drawable interactive.
> Make drawvis great again

- osu.Framework/BaseGame.cs
- osu.Framework/Platform/BasicGameHost.cs
I broke default window titles by assuming the title was empty when not specified (was actually "OpenTK Game Window").
> Add better fallback window title support.

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/DrawInfo.cs
This commit adds masked-away checks for non-flattened containers
and prevents updates to children of containers masked-away in the
previous frame.
> Improve performance of masked away containers

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
Adds remarks about relative size axes and relative position axes
not affecting auto sizing.
> Extend doc of AutoSizeAxes and BypassAutoSizeAxes

- osu.Framework.Desktop/Platform/DesktopGameWindow.cs
If the argument is left at 0 it will use the specified resolution using the first refresh rate OpenTK sees. Even though windows reports a refresh rate as available it might not necessarily work (in my case 25Hz does not work). By using the currently set refresh rate we (almost) know for sure that the refresh rate will work.
> Explicitly set refresh rate when going into fullscreen

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/ProxyDrawable.cs
- osu.Framework/Platform/GameHost.cs
Mostly makes access more restricted. internal Drawable<->Container
composability overrides have been made sealed. Drawable.Hovering
has gotten a public getter and documentation.
> Improve access modifiers

- osu.Framework/Graphics/Containers/Container.cs
This was a case of not invalidating correctly. There is future
potential for optimization by separating Colour invalidations
frorm visibility invalidations, but there is no measurable difference
to be found for now.
> Fix auto size not updating when children change visibility

- osu.Framework/Graphics/UserInterface/PasswordTextBox.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
Prohibit copying or separating by actual content.
Using `AllowClipboardExport` for the flag. Create a new flag for separating if needed.
> "Security" enhancements for PasswordTextBox

- osu.Framework.VisualTests/Tests/TestCaseAutosize.cs
- osu.Framework.VisualTests/Tests/TestCaseCheckBoxes.cs
- osu.Framework.VisualTests/Tests/TestCaseFlow.cs
- osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs
- osu.Framework.VisualTests/Tests/TestCaseTextBox.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/Performance/PerformanceOverlay.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/UserInterface/BasicCheckBox.cs
- osu.Framework/Graphics/UserInterface/DropDownMenu.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- osu.Framework/Screens/Testing/TestBrowser.cs
- osu.Framework/Screens/Testing/TestCase.cs
FillDirection now only controls horizontal, vertical and full,
whereas left-to-right and bottom-to-top are controlled by the
Anchors of children. Centre anchors will now correctly fill starting
from the centre of the flow.
> Make fill direction be determined partially by child Anchors

- osu-framework.sln.DotSettings
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
This commit makes autosize behave correctly when using custom
anchor positions. Custom anchor positions now have to be supplied
in relative coordinates for the sake of auto sizing logic being
possible in the first place.
This commit also does a little bit of refactoring and doc cleanup.
> Generalize autosize to arbitrary anchors

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseState.cs
Supersedes #397.
Fixes handling of non-main mouse buttons. Also changes click handling to only be on LeftButton for now.
> Simplify mouse button handling.

- osu.Framework/Graphics/UserInterface/Tab/TabControl.cs
Alternatively, TabControl can be made to only accept Enum Types.
> Get correct String representation for Enum

- osu.Framework/Graphics/Textures/TextureStore.cs
Locking now only occurs when two sources request the same texture.
> Fix TextureStore blocking globally when loading textures

- osu.Framework/Graphics/Containers/Container.cs
AutoSizeAxes was not being checked before ensuring autoSize is valid.
It's never in a valid state on non-autosize drawables.
> Fix performance degredation with many non-autosized masked drawables.

- osu.Framework/Graphics/Shaders/ShaderManager.cs
We can add this back in a friendlier way if/when needed. At the moment it triggers false-positive warnings when configuration is set to Release mode.
> Remove compile-time conditional in ShaderManager

- osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Input/InputManager.cs
Until now we've been pushing 1,000 states per second even when nothing has changed in those states. This adds equality checks and thus reduces the overhead of input queue building quite substantially.
> Don't queue new input states when nothing changed

- osu.Framework.VisualTests/Tests/TestCaseOnlineTextures.cs
- osu.Framework/Graphics/Containers/AsyncLoadContainer.cs
- osu.Framework/Graphics/Containers/DelayedLoadContainer.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/osu.Framework.csproj
New container types to help with common async scenarios.
- `AsyncLoadContainer` can be used in place of manual `LoadAsync` calls to write more elegant code.
- `DelayedLoadContainer` can be used to add a delay to content to avoid prematurely loading children when they haven't been on screen for long enough (ie. online resources or otherwise expensive texture fetches).
> Delayed load container

- osu.Framework/Platform/GameHost.cs
Black screens were caused by bootstrapSceneGraph causing a TextureAtlas texture load before the GL initialisation was complete, meaning we could not determine the MaxTextureSize.
Removing the asynchronous load unexpectedly improves startup time quite considerably.
> Improve startup time and fix occasional black-screen failures

- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Transforms/TransformColour.cs
This was spurred by two main issues;
1) `UpdateTransformsOfType()` had to be explicitly called whenever a new transform helper was created in derived classes. E.g. `BufferedContainer.BlurTo`.
2) Transforms lacked the ability to transform colours, through something like `TransformColourTo`.
Both of these are resolved in 2 steps:
1) Adding a generic `TransformTo()` method that replaces the `Transform*To()` methods.
2) Making UpdateTransformsOfType() implicit with the new `TransformTo()`.
Furthermore, this fixes a few transform helpers that were previously not using the `Transform*To()` methods and were not fully implementing it (or were implemented very hackishly).
The ideal end result is that the Transforms list really shouldn't be changed from the outside - it could lead to potentially …
> Better transform helpers

- osu.Framework/Graphics/Drawable.cs
Consider the case where we want to have an interface that provides a property and a transformation for that property. This interface could be attached onto any object and doesn't need to be a part of the base classes (Drawable/Container).
An example of such an interface implementation is:
```
public interface IAccented : IDrawable
{
Color4 AccentColour { get; set; }
}
public static class AccentedExtensions
{
public static void FadeAccent<TDrawable>(this TDrawable drawable, Color4 newColour, double duration = 0, EasingTypes easing = EasingTypes.None)
where TDrawable : Drawable, IAccented
{
drawable.TransformTo(drawable.AccentColour, newColour, duration, easing, new TransformAccent());
}
}
```
I would've liked to implement a TransformObjectTo() method or something like that, which would …
> Make TransformTo public and constrain T by struct.

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
Ignoring these will prevent getting mouse movement events with unexpected results.
For example, https://imgur.com/XEQvcvf (see Delta)
I can't compile it with latest osu, as it gives errors, but on osu's version this check has fixed ppy/osu#429.
> Ignore all mouse events when main window is minimized

- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/IDrawable.cs
We now pass in a delegate to retrieve the current value, as we want to do a complete update of transforms before querying it. This has the added advantage of simplifying the startValue code, as we no longer need to factor in changes from other transforms.
> Fix transforms not being applied correct when drawable is not present.

- osu.Framework.Desktop/osu.Framework.Desktop.csproj
- osu.Framework.Testing/osu.Framework.Testing.csproj
- osu.Framework/osu.Framework.csproj
Fixes ppy/osu#636 until Mono 5.0 is out, where we may or may not want to switch to C#7.
> Explicitly set language version to C# 6.0 for now.

- .vscode/launch.json
- .vscode/tasks.json
Because MSBuild doesn't check PDBs at compile time, a rebuild is necessary to recompile to portable versions of them.
> Clr vscode debugging

- osu.Framework/Threading/Scheduler.cs
The findAll() method on line 60 was creating a new list every time the method was run, causing the game to GC frequently during gameplay.  This changes the loop to iterate over the list directly, removing the offending allocations.
> Decrease memory traffic in the thread scheduler

- osu.Framework.Desktop/Platform/Linux/LinuxClipboard.cs
- osu.Framework.Desktop/Platform/Linux/LinuxGameHost.cs
- osu.Framework.Desktop/osu.Framework.Desktop.csproj
At least half of it.
This allows reading from clipboard, which I really missed when I tried logging in. (I use a password manager)
You still can't copy anything, though. The obvious code is there as a comment, but it causes issues.
If you enable that line and copy something, then try to paste in a different app, that other app will freeze until osu is closed.
I believe this is due to the weird way the clipboard is handled in X.
It will probably require using X libraries directly to be able to write to the clipboard, as well, but for the time being, at least you can paste.
> Add Linux clipboard support

- osu.Framework.VisualTests/Tests/TestCaseRigidBody.cs
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/Primitives/RectangleF.cs
- osu.Framework/Physics/RigidBodies/ContainerBody.cs
- osu.Framework/Physics/RigidBodies/DrawableBody.cs
- osu.Framework/Physics/RigidBody.cs
- osu.Framework/Physics/RigidBodySimulation.cs
- osu.Framework/osu.Framework.csproj
[Video](https://streamable.com/7qrhz)
This commit introduces RigidBodySimulation, which allows performing
rigid body simulation on the children of a given container. For now,
the simulation is limited to impulse responses and does not support
resting contact well. Additionally, only centre origin, absolute
positioned children are permitted. Performance optimizations are
also an area of future work.
For now I'll leave the implementation at this. It is complete enough to be integrated into the game as a prototype if it becomes desired. At that point further features and optimizations can be added.
> Add rudimentary support for rigid body simulation

- osu.Framework/Game.cs
Allows derived games to set the current mode of the statistics display programatically.
> Expose frame statistics mode.

- osu.Framework.Testing/TestCase.cs
- osu.Framework/Configuration/FrameSync.cs
- osu.Framework/Configuration/FrameworkConfigManager.cs
- osu.Framework/Graphics/Performance/PerformanceOverlay.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/GameWindow.cs
If the state was set before CreateDisplays was called, their would be initialised with the wrong initial state.
> Fix state not propagating to FrameStatisticDisplays

- osu.Framework/Threading/GameThread.cs
30hz has always felt too low. We are at the point where running all threads at 60hz has quite a low overhead, and the boost in smoothness is definitely worth it in my opinion.
Keep in mind this is still just a sane default, and consumers of the framework can set their own update rates if deemed necessary.
> Increase inactive thread update rates

- osu-framework.sln.DotSettings
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/Shaders/ShaderManager.cs
- osu.Framework/Graphics/Sprites/Sprite.cs
- osu.Framework/Graphics/UserInterface/CircularProgress.cs
Enum.ToString() is quite an expensive operation, and was being called twice per drawable loaded.
> Improve performance of hot path in ShaderManager

- osu.Framework/IO/Network/JsonWebRequest.cs
This was causing the whole game to crash when a bad response is returned by the server.
> Avoid hard-crashing when web response gives non-json content

- osu.Framework/Timing/FramedClock.cs
Allows for very specific clock pausing, even when the clock is a custom clock in a drawable (where ProcessFrame is being automatically called).
> Allow blocking of processing of frames in a FramedClock

- osu.Framework/Game.cs
Fixes mouse cursor not correctly travelling outside the window bounds.
> Add missing AlwaysReceiveInput

- osu.Framework.VisualTests/Tests/TestCaseHollowEdgeEffect.cs
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/Graphics/Containers/ContainerDrawNode.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
#726 
Looks a little ugly though
> Ability to render EdgeEffects only outside the draw rectangle

- osu.Framework/Graphics/Containers/ScrollContainer.cs
Fixes:
- Disallow clicking through the scrollbar (In the osu! project you could click through the scrollbar in the song selection)
- Clicking on the scrollbar while it scrolls causes it to stop scrolling
> Scrollbar fixes

- osu.Framework/Graphics/Containers/TabbableContainer.cs
Happens when a textbox isn't part of a tabbable container.
> Fix a crash when pressing tab on a textbox

- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/InputManager.cs
Previously, TriggerOnFocus was incorrectly called twice when
a drawable obtained focus via mouse click.
> Fix double-call of TriggerOnFocus on mouse click

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
> Fix mouse handling on linux

- osu.Framework.Testing/TestBrowser.cs
- osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs
- osu.Framework.VisualTests/Tests/TestCaseTabControl.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
Adds margin and uses additive blending.
> Scrollbar visual improvements

- osu.Framework.VisualTests/Tests/TestCaseSearchContainer.cs
- osu.Framework/Graphics/Containers/IFilterable.cs
- osu.Framework/Graphics/Containers/IHasFilterTerms.cs
- osu.Framework/Graphics/Containers/SearchContainer.cs
- osu.Framework/osu.Framework.csproj
Sometimes we want drawables to expose terms but not handle matching themselves (one of their parents may be the one reacting to a filter).
Closes #699
> Add IHasFilterTerms interface and improve naming

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
Need people to test this and see how it performs on different operating systems. Also whether it is more or less RAW than previous.
- Need macOS users to test if this fixes cursor input not working for some devices.
- Need windows users to test whether this has acceleration or not.
- Need linux users to test how this works in general.
As I'm currently running windows in a virtualised device, I haven't tested native behaviour yet myself. OpenTK docs suggest using the events gives raw input response, but from my testing so far this doesn't seem correct.
> Handle Mouse events rather than polling

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Fixes some seriously bad performance while selecting a target and traversing up the the hierarchy in drawvis.
> Check whether the cursor is contained before recursing in findTargetIn

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
There are many cases in which it is desired to expose a generic `Container.Add(T)`, but have the ability to add children from inside the container that are not of type `T`. Since `InternalChildren` and `AddInternal` are protected functions, it seems fair to allow `AddInternal = new Drawable[]` in this sort of use case.
An example of such a use case is as follows:
```
public class MyContainer : Container<MyType>
{
protected override Container<MyType> Content => content;
private Container<MyType> content;
public MyContainer()
{
// This line would previously fail due to AddInternal(MyType drawable)
AddInternal(content = new Container<Mytype>());
}
}
```
> Make InternalChildren an IEnumerable<Drawable>

- osu.Framework/Graphics/UserInterface/TextBox.cs
When a user hits Enter to commit the contents of a TextBox, this used
to trigger a loss of focus for the TextBox, and then OnFocusLost used
to invoke the OnCommit-Handler on the condition that the enter key
is held. Now, hitting the enter key directly invokes OnCommit if the
TextBox is currently focused and only removes focus from the
TextBox if the ReleaseFocusOnCommit flag is set.
> Do not lose focus when commiting in TextBox

- osu.Framework.VisualTests/Tests/TestCaseCoordinateSpaces.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Primitives/RectangleF.cs
This is a requisite for TimingChanges. Imagine a timing change which has start time = 5000, and a hitobject that is to be positioned inside that container with start time = 7500. Since the hit object will become relatively positioned to the container, the hitobject has to be offset backwards by the timing change start time.
This gets problematic because there is no really easy way to do this while supporting moving hit objects around in the editor.
So this allows defining the relative coordinate space as a range with a `RectangleF`. The above scenario could be achieved by:
```
new TimingPointContainer
{
RelativeCoordinateSpace = new RectangleF(0, TimingPoint.StartTime, 0, N),
Children = new[]
{
new HitObjectContainer { Y = HitObject.StartTime }
}
}
```
Where N, in the TimingChange branch, …
> More relative coordinate space

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKEventMouseState.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseState.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKPollMouseState.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework.Desktop/osu.Framework.Desktop.csproj
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseState.cs
There are scenarios where we don't want the LastState to be set on a newly arriving MouseState. This covers those cases, and fixes some bugs along the way.
- InputManager now only assigns the `LastState` when both the last and current MouseState are of the same type (ie. coming from the same InputHandler source).
- Fixed multiple bugs with window focus and delta computations.
> Fix various cases of mouse delta values being incorrect

- osu.Framework/Graphics/Containers/ContainerDrawNode.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
Makes hollow inner edge effect smooth. Also documents an old hack better, and adds a new one to make this even work.
> Make the inside edge of hollow edge effects smooth

- osu.Framework.Testing/GridTestCase.cs
- osu.Framework.Testing/TestBrowser.cs
- osu.Framework.Testing/osu.Framework.Testing.csproj
- osu.Framework.VisualTests/Tests/TestCaseColourGradient.cs
- osu.Framework.VisualTests/Tests/TestCaseDrawablePath.cs
- osu.Framework.VisualTests/Tests/TestCaseFillModes.cs
- osu.Framework.VisualTests/Tests/TestCaseFlow.cs
- osu.Framework.VisualTests/Tests/TestCaseHollowEdgeEffect.cs
- osu.Framework.VisualTests/Tests/TestCaseInputResampler.cs
- osu.Framework.VisualTests/Tests/TestCasePadding.cs
- osu.Framework.VisualTests/Tests/TestCaseSmoothedEdges.cs
This pull request adds an abstract `GridTestCase` helper class, which tests can derive from to facilitate easy display of multiple configurations of the tested component in a grid.
Also makes `TestCaseInputResampler` significantly more understandable and comprehensive.
> Generalize several tests to GridTestCase and improve TestCaseInputResampler

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
We weren't identifying inactive "placeholder" states as different classes, resulting in incorrect handling of them.
> Correctly handle focus changes when RawMouseHandler is active

- appveyor.yml
There are many instances we accidentally merge pull requests with outstanding warnings, as the fact warnings exists is not made obvious. This forces all `inspectcode` warnings to an error level.
> Treat inspectcode warnings as errors (CI)

- osu.Framework/Graphics/Containers/ScrollContainer.cs
The internal size the ScrollContainer used to make decisions about
the scroll range, scrollbar size, etc. was outdated by one frame
because it was updated before its children.
> Fix ScrollContainer lagging behind by one frame

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
Does what it says: Schedules a call to run the next time
UpdateAfterChildren() gets called.
> Add ScheduleAfterChildren()-API to Containers

- osu.Framework/Graphics/Containers/ScrollContainer.cs
Useful if you want to control the bouncing animation that happens when
a user scrolls up or down quickly.
My own use-case was preventing users from scrolling below/above the scroll limits too much, changing clamp_extension to lower values accomplished that while keeping the scrolling animation smooth.
> Make ScrollContainer.clamp_extension configurable

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
Scheduling should never be done from a parent. There's basically no reason to do this.
> Make Drawable.Schedule methods protected

- osu.Framework/Game.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Lines/Path.cs
This change stops propagating down layout / autosize invalidations if `DrawSize` hasn't been changed and the child does not have `RelativeSizeAxes`. Results in huge speedups in certain cases such as `TestCaseSpriteText` where I observe up to 5x.
> Rework invalidation rules to avoid unnecessary computations

- osu.Framework/Input/CustomInputManager.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/PassThroughInputManager.cs
- osu.Framework/Input/UserInputManager.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/osu.Framework.csproj
- Makes InputHandler list a property, and removes the ability to add/remove by default.
- Moves initialisation on InputHandlers to GameHost.
- Adds a method to reset to a sane default by completely disposing and recreating handlers.
- Fixes UserInputManager not getting InputHandler changes (new added or existing removed) from its underlying GameHost.
> Make InputManager abstract

- osu.Framework.VisualTests/Tests/TestCaseEffects.cs
- osu.Framework.VisualTests/Tests/TestCaseHollowEdgeEffect.cs
- osu.Framework.VisualTests/Tests/TestCaseMasking.cs
- osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/ContainerDrawNode.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Effects/BlurEffect.cs
- osu.Framework/Graphics/Effects/EdgeEffect.cs
- osu.Framework/Graphics/Effects/EffectExtensions.cs
- osu.Framework/Graphics/Effects/IEffect.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectAlpha.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectColour.cs
- osu.Framework/MathUtils/Blur.cs
- osu.Framework/osu.Framework.csproj
An initial draft and a few useful/encouraging examples for an API to allow application of effects to drawables.
The basic idea is to have an Effect object that when applied to a drawable, returns a new drawable (fe a container containing the target drawable) that displays the original drawable with the effect.
This design was chosen after some discussion with @Tom94.
His idea was originally to simply have Containers that wrap drawables, to make the resulting draw graph more obvious. However, this prevents easy re-use of effects (since the Containers have to ensure that only one drawable is contained by them) for no particular gain other than being able to use the initialization syntax when creating a big draw graph.
To allow having a markup-esque structure with effects, the example of …
> Add simplified API for applying visual effects to drawables

- osu.Framework.VisualTests/Tests/TestCaseTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TabItem.cs
A much better flow than having tabs always set themselves as active. Didn't allow enough flexibility.
> Make Active bindable in TabItem, managed by TabControl

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
The OnSizingChanged() method is a callback method that can be used by
subclasses to react to changes of the RelativeSizeAxes and AutoSizeAxes
properties that Drawable and Container expose, respectively.
> Add Drawable.OnSizingChanged

- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectAlpha.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectColour.cs
Really not sure why `TransformEdgeEffectAlpha` and `TransformEdgeEffectColour` casts the drawable to a `Container`, which won't allow transforming other container EdgeEffects such as `Container<Box>`.
> Use IContainer instead of Container in EdgeEffect transforms

- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/IDrawable.cs
- osu.Framework/Graphics/Transforms/ITransform.cs
- osu.Framework/Graphics/Transforms/Transform.cs
- osu.Framework/Graphics/Transforms/TransformAlpha.cs
- osu.Framework/Graphics/Transforms/TransformColour.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectAlpha.cs
- osu.Framework/Graphics/Transforms/TransformEdgeEffectColour.cs
- osu.Framework/Graphics/Transforms/TransformFloat.cs
- osu.Framework/Graphics/Transforms/TransformPositionX.cs
- osu.Framework/Graphics/Transforms/TransformPositionY.cs
- osu.Framework/Graphics/Transforms/TransformRotation.cs
- osu.Framework/Graphics/Transforms/TransformSize.cs
- osu.Framework/Graphics/Transforms/TransformVector.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
- osu.Framework/osu.Framework.csproj
To use it for example in `AdjustableAudioComponent` in the future.
> Split the drawable's transformation logic into its own class for reuse purposes

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKEventMouseState.cs
- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework.Desktop/osu.Framework.Desktop.csproj
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/InputManager.cs
Reverts a chance which caused the mouse wheel to act weird when the mouse enters the window (and raw input is disabled).
Adds a special case for `PositionMouseDown` which covers the scenario which the reverted fix was implemented to fix.
> Fix mouse wheel state retention regression

- osu.Framework/Game.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Shapes/Triangle.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Input/UserInputManager.cs
The idea for this came when discussing with @default0 about how you can accidentally get weird side-effects by using `AlwaysReceiveInput` in combination with existing classes that handle certain input events.
Turns out, we don't need it and can simply handle input correctly for _all_ visible drawables _all the time_. In fact, this fix sometimes _avoids_ unnecessary input events from firing, while making the code substantially nicer.
> Remove the need for AlwaysReceiveInput

- osu.Framework.Testing/GridTestCase.cs
- osu.Framework.Testing/TestCase.cs
- osu.Framework.Testing/TestRunner.cs
- osu.Framework.VisualTests/Tests/TestCaseDropdownBox.cs
- osu.Framework.VisualTests/Tests/TestCaseFlow.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/IContainer.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/UserInterface/ContextMenu.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- osu.Framework/Lists/LazyList.cs
- osu.Framework/osu.Framework.csproj
Allows for convenient access of children by index and to get other
information such as the number of children in a container.
> Change Children to a IReadOnlyList

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
This fixes a bug with the draw visualiser and improves on the property display.
The bug that was fixed can be reproduced as follows:
-Locate a dropdown
-Select the dropdown
-Go up the hierarchy until you can see the menu subtree toggling as you toggle the dropdown
-Open the dropdown menu
-Double-click a drawable in the subtree of the menu
-Hit "up one parent"
Basically whats happening is that the draw visualiser doesnt properly deal with the case that the drawable currently selected as the root node gets removed by user code.
The other improvement revolves around the property display: Write-only properties are now excluded (ChildrenEnumerable, fe) and if an exception occurs during evaluation, the type of exception that occured is written out instead of just the message "<Cannot …
> DrawVis improvements

- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Shapes/Triangle.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
- osu.Framework/Input/InputManager.cs
- Makes `InputManager.HoveredDrawables` a `IReadOnlyList`
- Adds an overridable `Drawable.ReceiveMouseInputAt` method to decouple input from `Contains`
- Avoids a significant heap allocation every frame from `lastHoveredDrawables`
- Documents `hoveredDrawables` et al. a bit better
More details in individual commit messages.
> Various small improvements to mouse input

- osu.Framework/Caching/Cached.cs
- osu.Framework/Graphics/Colour/SRGBColour.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/UserInterface/ContextMenu.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
I believe Cached was overengineered. While dumbing down the Cached interface, this PR imho makes the code simpler to understand. Further, this reduces nesting quite a bit and doesn't rely on the JIT inlining delegates, which appears to give around 10% performance.
We can get another 10-20% performance in invalidation-heavy scenarios by removing the `FrameStatistics.Increment` calls from `Cached`. We should probably do this on release builds at some point in the future.
> Simplify caching of properties

- osu.Framework.VisualTests/Tests/TestCaseContextMenu.cs
- osu.Framework.VisualTests/Tests/TestCaseTooltip.cs
- osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Primitives/RectangleF.cs
- osu.Framework/Graphics/Primitives/RectangleI.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/osu.Framework.csproj
This changes the TooltipContainer API to be more reasonable:
Instead of adding the ability for its siblings and parents to have tooltips, the TooltipContainer now enables tooltips for all its children.
> Make TooltipContainer and ContextMenuContainer only consider children

- osu.Framework.VisualTests/Tests/TestCaseTooltip.cs
- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/ITooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/IDrawable.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/osu.Framework.csproj
Adds an IHasCustomTooltip interface that allows Drawables to use different types of tooltips without the need to create a new TooltipContainer and nest the Drawables inside them.
The Drawable API has been changed slightly as well: Hovering has been renamed to IsHovered, and the IsHovered method has been removed and inlined. A new IsDragged property has been added to go along with IsHovered.
TooltipContainer itself now also offers two more extension points for subclasses: RefreshTooltip() and ShallHideTooltip(), where RefreshTooltip() is used to customize the update scheme of the tooltips (if live updates are undesired, for example) and ShallHideTooltip() controls when visible tooltips should be hidden.
> Add ability to use custom tooltips per drawable

- osu.Framework/Graphics/Sprites/Sprite.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/Textures/TextureAtlas.cs
- osu.Framework/Graphics/Textures/TextureWhitePixel.cs
- osu.Framework/osu.Framework.csproj
You really never want to manually dispose the builtin white pixel
texture as it breaks builtin features like Box and edge effects.
> Disallow disposal of TextureWhitePixel

- osu.Framework.Testing/TestBrowser.cs
- osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs
- osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
Should be moved to osu! project as legacy/non-standard behaviour. See #897.
> Remove all framework usage of RelativeMouseDrag

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/MarginPadding.cs
I double-checked the code, and it seems like the old reasons for
forbidding negative values no longer exist. Still use with caution,
since children can easily be made to poke out of their parents,
causing potentially counterintuitive optimization patterns.
> Allow negative margin and padding again

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Threading/GameThread.cs
- osu.Framework/Threading/Scheduler.cs
This fixes drifting schedule times for frame-based clocks and also ensures animations which rely on Schedule work with faster and slower playback.
> Base Scheduler on IClock instead of Stopwatch

- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Input/InputManager.cs
- Dragged IHasTooltip Drawables now immediately show a tooltip
which overrides the tooltip of any potentially other hovered
IHasTooltip Drawable.
- The mouse no longer has to stay perfectly still for a tooltip
to appear, but staying within a small region is enough. This is
paramount for making tooltips work with tablet input as the cursor
is always moving slightly.
> Significantly more tablet and drag friendly TooltipContainer

- osu.Framework/Audio/Track/Track.cs
- osu.Framework/Audio/Track/TrackBass.cs
Was implemented without much consideration. Not used anywhere, so let's remove for now. "Resolves" #908.
> Remove Track's OnLoaded

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Drawable.cs
We may be able to get rid of the `game` member altogether by scheduling to the `CompositeDrawable`'s own `Scheduler`. @peppy did you ever consider this and decide against it for some reason I am missing?
> Move LoadComponentAsync to CompositeDrawable and prevent wrong usage

- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/osu.Framework.csproj
This PR passes down IReadOnlyDependencyContainer such that children can not cache dependencies into their parent's dependency container.
> Prevent dependency pollution up the scene graph

- osu.Framework.VisualTests/Tests/TestCaseCircularProgress.cs
- osu.Framework.VisualTests/Tests/TestCaseColourGradient.cs
- osu.Framework.VisualTests/Tests/TestCaseEffects.cs
- osu.Framework/Graphics/Colour/ColourInfo.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Effects/BlurEffect.cs
- osu.Framework/Graphics/Effects/EdgeEffect.cs
- osu.Framework/Graphics/Effects/GlowEffect.cs
- osu.Framework/Graphics/Effects/OutlineEffect.cs
- osu.Framework/Graphics/Lines/PathDrawNode.cs
- osu.Framework/Graphics/TransformSequenceExtensions.cs
- osu.Framework/Graphics/TransformableExtensions.cs
- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- osu.Framework/MathUtils/Interpolation.cs
- osu.Framework/osu.Framework.csproj
This PR adds the following functionality to `BufferedContainer`:
- Effects can now be drawn in front of the original (only relevant if `DrawOriginal` is true).
- Effects can now have a custom blending mode (useful for additive glow).
Further, `BlurEffect` has been made more versatile and a new `GlowEffect` has been added. It looks like this on text (in contrast to `OutlineEffect`):
> Add GlowEffect which allows making any Drawable glow

- osu.Framework.Desktop/Platform/DesktopGameHost.cs
- osu.Framework.Desktop/Platform/DesktopStorage.cs
- osu.Framework.Desktop/Platform/Linux/LinuxStorage.cs
- osu.Framework.Desktop/Platform/Windows/WindowsStorage.cs
- osu.Framework/Logging/Logger.cs
- osu.Framework/Platform/Storage.cs
- `BasePath` is only located once, saving on computations.
- `GetUsablePathFor` is used everywhere to find the combined path for a user input.
- Added the ability to get a new storage for a subdirectory of an existing one (`GetStorageForDirectory`).
- Added documentation.
- Make `Logger` use `Storage` and remove the hacky path setting in `DesktopStorage`.
- Add `GetDirectories` method.
> Storage improvements

- osu.Framework.Testing/Drawables/TestCaseButton.cs
- osu.Framework.Testing/DynamicClassCompiler.cs
- osu.Framework.Testing/TestBrowser.cs
- osu.Framework.Testing/TestBrowserConfig.cs
- osu.Framework.Testing/TestBrowserTestRunner.cs
- osu.Framework.Testing/osu.Framework.Testing.csproj
- osu.Framework.Testing/packages.config
- osu.Framework.VisualTestBrowser/AutomatedVisualTestGame.cs
- osu.Framework.VisualTestBrowser/VisualTestGame.cs
- osu.Framework.VisualTestBrowser/osu.Framework.VisualTestBrowser.csproj
- osu.Framework.VisualTestBrowser/packages.config
This is done to avoid referencing VisualTestBrowser from framework consumers.
> Move common TestBrowser components to Testing

- osu.Framework.Desktop.Tests/Platform/HeadlessGameHostTest.cs
- osu.Framework/Graphics/Drawable.cs
RelativeChildSize caused issues with fillmodes because they used relativeToAbsoluteFactor without taking into account the final absolute size in each dimension, thus yielded incorrect conversions. For example:
```
Assume square 50x50 parent, RelativeChildSize = Vector2(1)
Size = Vector2(1)
FillMode.Fit
---
Conversion = ComponentMin(relativeToAbsoluteFactor) = Min(50, 50) = Vector2(50)
FinalSize = Size * conversion = Vector2(1) * Vector2(50) = Vector2(50)
```
vs
```
Assume square 50x50 parent, RelativeChildSize = Vector2(2, 1)
Size = Vector2(2, 1)
FillMode.Fit
---
Conversion = ComponentMin(relativeToAbsoluteFactor) = Min(25, 50) = Vector2(25)
FinalSize = Size * Conversion = Vector2(2, 1) * Vector2(25, 25) = Vector2(50, 25)  // Even though Size == RelativeChildSize
```
So now we first …
> Apply FillModes after computing the absolute size to account for RelativeChildSize

- osu.Framework/Platform/GameHost.cs
In some cases OpenTK provides the framework with an invalid refresh rate (e.g. 0 Hz). In such cases the frame limiter was previously broken; it did nothing. This commit instead defaults the frame limiter to using a refresh rate of 60 Hz (and multiples thereof) as it is most likely the user has a 60 Hz display. If the user has a higher refresh rate, then the 8x or unlimited frame limiters should still provide sufficient functionality for good use.
> Default frame limiter to a refresh rate of 60 Hz

- osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
- osu.Framework/Graphics/Containers/TabbableContainer.cs
- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
Previous DI logic was causing issues where PassThroughInputManagers were present in the tree, due to fetching an InputManager too global.
While we may modify DI to better support this scenario, this is a better solution for the time being.
> Add method to search upwards for first parent InputManager

- osu.Framework/Graphics/Drawable.cs
- osu.Framework/MathUtils/Precision.cs
Apparently my last changes to precision caused asserts to be fired in ScrollContainer. So I'm reverting them for now but also added an IsPresent check because we'll experience undesired pixel visibility with effectively 0 scale on medium-sized sprites.
> Revert Precision changes but add scale check to IsPresent.

- osu.Framework/Input/Bindings/KeyBindingInputManager.cs
This change is to allow elements to query whether a specific action is pressed, without needing to explicitly implement `IKeyBindingHandler<T>`.
> Expose PressedActions for querying currently actuated actions

- osu.Framework/Platform/GameHost.cs
Previously we were relying on the finalizer for disposal, which is too slow for things like nUnit
> Dispose draw tree on GameHost.Dispose

- osu.Framework/Input/Bindings/KeyBindingInputManager.cs
This seems like a better default and solves a lot of issues that were coming up (like global bindings overriding local scrolling in ScrollContainers).
> Reverse handling order of KeyBindings (handle raw events first)

- osu.Framework/Input/InputManager.cs
Previously would call PropagateKeyDown twice, causing incorrect execution in overridden usages which referenced their own queue.
> Fix InputManager execution order when a focused drawable is present

- osu.Framework/Platform/GameHost.cs
e.g. osu! uses a RatioAdjust container which scales relative to the Root size, and this may result in bad/irrecoverable states.
This should fix the "black screen" issue we've been experiencing erratically.
> Enforce Root is at least 1px size for any children that scale relative to its size

- osu.Framework/Graphics/Textures/TextureAtlas.cs
- osu.Framework/Input/Handlers/InputHandler.cs
Locking on 'this' is unsafe when the class is not private: an object can be locked on in any part of the program after creating its instance.
> Do not use 'this' object for locking

- osu.Framework.Testing/TestCase.cs
- osu.Framework.Testing/TestCaseTestRunner.cs
Allows NUnit tests to add steps to the test case and generate a scene graph. An example of such a use case is TestCaseNestedMenus.
> Make NUnit tests run a HeadlessGameHost instance

- SampleGame/SampleGame.csproj
- osu.Framework.Desktop.Tests/Visual/TestCaseNestedMenus.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
`DrawableMenuItem`s now expose a `State`. Changes to this property from within a derived `DrawableMenuItem` will propagate these changes to the menu containing the `DrawableMenuItem`.
Furthermore, the `DrawableMenuItem`'s `State` is updated appropriately when the `State` of the menu containing it changes.
Test case TBD, in next PR, because I'm not implementing it without https://github.com/ppy/osu-framework/pull/1019 .
> Make DrawableMenuItems IStateful

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Basically making it be useful again.
> Fix dodgy hover handling in DrawVisualiser

- osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs
This fixes a bug where OpenTK is returning negative data when the mouse crosses a screen center (width or height div 2) on Windows 10 under certain circumstances.
Whenever my mouse passes over `screen_width.x/2` or `screen_width.y/2` in a negative direction (towards zero) the mouse coordinate in that direction will become negative of what it should be for one single event. Reproducible in Parallels 13, but I've heard from other users not using a VM that can reproduce the same issue.
> Ignore negative mouse coordinates when polling

- osu.Framework/Graphics/Containers/CircularContainer.cs
Wasn't being updated often enough (when being sized based on an autosize parent).
> Fix CircularContainer not always being circular

- osu.Framework/Graphics/Drawable.cs
This happens when a drawable is asynchronously loaded, but is added to its parent before it is done loading.
> Report when drawable loading is blocked.

- osu.Framework/Audio/Track/TrackBass.cs
Added a check in TrackBass to prevent amplitudes being updated to crazy values if the track is paused.
Related to: https://github.com/ppy/osu/pull/1243
Possibly also a fix for: https://github.com/ppy/osu/issues/1284
> Bass.ChannelGetLevelLeft/Right returns negative values if paused

- osu.Framework/Platform/DesktopStorage.cs
- osu.Framework/Platform/Storage.cs
Fixes database initialisation potentially not having a containing folder ready for it.
> Allow GetUsablePathFor to create directories when they don't exist

- osu.Framework/osu.Framework.csproj
Mono lib resolver requires this includes, it was deleted while merging Desktop and pure Framework.
> Add missing includes of .config files to .csproj

- osu.Framework/IO/Network/JsonWebRequest.cs
We were getting html error responses from the API when http response code errors were expected
> Use the correct Accept type for json requests

- .vscode/launch.json
- osu.Framework/Graphics/UserInterface/Dropdown.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
This was ugly and couldn't be overridden easily when this sizing functionality is not desired (e.g. EditorMenuBar).
Also fixes:
* Framework Dropdowns not using their DropdownMenuItems.
* VSCode launch config.
(Both of these are minor changes ¯\_(ツ)_/¯
> Fix weird auto/relative sizing in Menu

- osu.Framework/Audio/Track/TrackBass.cs
Previously seeks triggered by a drag operation could lag behind.
> Limit the rate at which seeks are performed at bass' end

- osu.Framework/Platform/GameHost.cs
I've tested this over 2000 startups and haven't been able to replicate the blackscreen bug once.
Does two things:
1. Moves GLWrapper calls to just before the draw nodes are drawn.
2. Changes the GLWrapper.Reset call to not reference DrawSize.
I believe #2 is what actually provides the fix, but #1 also makes sense otherwise the screen could be cleared too early if updates are running behind draws.
> Fix occasional blackscreens on startup

- osu.Framework/Graphics/Containers/CircularContainer.cs
Previously a stale value of DrawSize may have been used, causing unexpected results.
> Ensure base invalidation happens before DrawSize is consumed

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Conside the case where a Container has an autosize content with a drawable inside it. The drawable won't be considered for autosize until after the first UpdateSubTree without this change, as UpdateChildrenLife's (when called in load()) checkChildLife will return early.
Therefore, querying DrawSize in LoadComplete() will fail without this change, where it is expected to work.
> Allow children to be loaded in containers which are still in a Loading state

- osu.Framework.Tests/VisualTestGame.cs
- osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
- osu.Framework/osu.Framework.csproj
Introduces `DrawSizePreservingFillContainer` as a generalization of `RatioAdjust` from https://github.com/ppy/osu . Once this is merged in, https://github.com/ppy/osu/pull/1359 removes `RatioAdjust` and replaces it with this.
Further, this PR uses `DrawSizePreservingFillContainer` within `VisualTestGame` to make the tests usable on HiDPI screens.
> Draw size preserving fill container

- osu.Framework/Audio/Track/Waveform.cs
Removes the empty parameter ctor and exposes an optional default.
> Allow waveform to handle null data

- osu.Framework/Audio/Track/Waveform.cs
BASS returns errors if we try to load as much data as long songs have in one go. Tested with para para and unforgiving.
> Fix waveform incorrectly loading long songs

- SampleGame/SampleGame.csproj
Having these produce warnings under certain compile environments.
> Remove references to CodeAnalysisRulesets

- osu.Framework/Graphics/Audio/WaveformGraph.cs
In some cases, Waveforms are shared between multiple WaveformGraphs. This logic was causing the waveform data to be disposed while references were still held.
> Don't dispose underlying Waveform in WaveformGraph

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
This reverts commit 3717de89726ad643b321627da911f55394a74d34.
Let's not do this like this. Causes lots of problems game-wide.
> Revert loading children while the parent is in a loading state

- osu-framework.sln.DotSettings
- osu.Framework/Host.cs
- osu.Framework/Input/GameWindowTextInput.cs
- osu.Framework/Platform/DesktopGameHost.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/HeadlessGameHost.cs
- osu.Framework/Platform/Linux/LinuxGameHost.cs
- osu.Framework/Platform/MacOS/MacOSClipboard.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
- osu.Framework/Platform/MacOS/MacOSStorage.cs
- osu.Framework/Platform/MacOS/Native/Class.cs
- osu.Framework/Platform/MacOS/Native/Cocoa.cs
- osu.Framework/Platform/MacOS/Native/NSArray.cs
- osu.Framework/Platform/MacOS/Native/NSDictionary.cs
- osu.Framework/Platform/MacOS/Native/NSPasteboard.cs
- osu.Framework/Platform/MacOS/Native/Selector.cs
- osu.Framework/Platform/Windows/WindowsGameHost.cs
- osu.Framework/osu.Framework.csproj
* Added macOS framework classes (host, window, etc.)
* Added native classes (combination of interop and reflection on the OpenTK classes)
* Added a workaround for an OpenTK bug where modifier keys (command, control, etc.) do not receive their own keydown/keyup events on macOS
* Added a workaround for an OpenTK bug where printable keys fire a keypress event on macOS even if a modifier key is held (this is not the case on Windows).  Note that the workaround does not drop the actual event.
* Added an implementation of macOS clipboard using the general pasteboard
This includes some of the initial changes of #945 but not the actual drag+drop functionality.  I will make a separate PR for that later based on this branch.
OpenTK issue: https://github.com/opentk/opentk/issues/669
> Improved macOS target

- osu.Framework/Logging/Logger.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/TestCase.cs
- osu.Framework/Threading/Scheduler.cs
This also enabled faster-than-realtime testcase runs, which seems to have been overlooked at the framework level. Shaves a minute off CI runs.
> Fix isolation of individual TestCase runs

- osu.Framework/Testing/TestBrowser.cs
Was causing exceptions under a mono host.
> Don't attempt to get locations of dynamic assemblies

- osu.Framework/Graphics/Animations/TextureAnimation.cs
Given that Sprite.Texture accepts a null value, I want to allow TextureAnimation to accept nulls. This is also consistent with TextureAnimation.updateTextureHolderSize(), which checks if the texture is null.
> Fix TextureAnimation nullref on null texture

- osu.Framework/Configuration/ConfigManager.cs
When initialising bindables in `ConfigManager`, they should have their `Default` set to the initial value so that the game can tell whether they have been modified.
> Ensure config bindables have Default set to their initial value

- osu.Framework/Platform/DesktopGameWindow.cs
- osu.Framework/Platform/Windows/WindowsGameWindow.cs
Remove Windows specific drag and drop code from framework. File drop handling currently provided by OpenTK(see `NativeWindow.cs` -> `FileDrop` event) in platform agnostic manner.
> Remove platfrom dependent drag and drop

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/IO/Network/FileWebRequest.cs
- osu.Framework/IO/Network/JsonWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
- osu.Framework/IO/Stores/OnlineStore.cs
- osu.Framework/osu.Framework.csproj
- osu.Framework/packages.config
Optional:
Found [this](https://github.com/dotnet/corefx/issues/11885#issuecomment-248915149) comment during my quest to fix the WebRequest issue on .NET Core. Furthermore [this](https://github.com/dotnet/corefx/issues/7037) thread basically states that:
1. Anything to do with WebRequest is deprecated.
2. `HttpClient` handles the proxy stuff much better.
As far as I can see, `HttpClient` is the only way forward for .NET Core compatibility.
This branch serves two main purposes:
1. Making `WebRequest` use `HttpClient` for requests.
2. Utilising async/await methods to make the code neater.
The following is _not_ implemented:
1. Certificate validation. This needs to be re-implemented at an osu.Game level - it cannot enforce `*ppy.sh` certificates.
2. IPv4 fallback. I don't know if this is …
> Make WebRequest use HttpClient and proper async/await

- osu.Framework/IO/Network/WebRequest.cs
- osu.Framework/Logging/Logger.cs
This was a thing left over from osu-stable where we wanted to log web requests between startups to debug the updater.
Not required for now.
> Always clear logs on startup for the time being

- osu.Framework/Graphics/Drawable.cs
Very noticeable on mono runtime, where the ThreadPool's size starts out a magnitude lower than .NET
> Fix ThreadPool filling up from Drawable LoadAsync calls

- osu.Framework/Graphics/Containers/CircularContainer.cs
Could be potentially caching an incorrect value.
Fixes https://github.com/ppy/osu/issues/1416
> Fix CircularContainer using DrawSize too early

- osu.Framework/Configuration/Bindable.cs
It should only be used to trigger the local events, not any other Bindable's events. While this is not a serious issue as the ForEach would be essentially a no-op (the values are synchronised at point of binding), this change makes it more clear what is going on.
> Stop TriggerChange from propagating out to bound bindables

- osu.Framework/Graphics/Containers/VisibilityContainer.cs
Until now, setting the state on VisibilityContainer before LoadComplete would result in the container being displayed in the set state (without transition).
This allows the consumer to be in control of whether the PopIn animation is played on first display or not.
Fixes https://github.com/ppy/osu/issues/1419.
> Allow VisibilityContainer to always animate at LoadComplete

- osu.Framework/Platform/DesktopStorage.cs
- osu.Framework/Platform/Storage.cs
- osu.Framework/osu.Framework.csproj
- osu.Framework/packages.config
Gonna say that for my own sanity, this is a prerequisite to https://github.com/ppy/osu-framework/pull/1106.
1. We are no longer using SQLite.Net, and as of the latest discussions, we're moving all database-related code to the osu! project. We can figure this out later, but this is how it is right now.
2. The SQLite targets are also targeted by osu.Game and osu.Desktop.
> Remove unused SQLite.Net library

- osu.Framework/Graphics/TransformableExtensions.cs
> Fix MoveToOffset's offset not being applied when an existing move transformation is present.

- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
As noted in #1138, apps will hard crash if running on macOS with the SDL backend.  This change will prevent the crash, but special handling for modifier keys will no longer be initialised.
It's possible that the reflection workarounds may be unnecessary with SDL anyway.  Need more info from @Zylviij regarding this.
> Catch any exceptions thrown by macOS reflection during initialisation

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
> Add method to transform a Transformable to a point in time

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Previously it would iterate over every container and perform a FirstOrDefault on it to figure out whether a VisualisedDrawable existed/should be updated. With many drawables, this was super expensive, tending towards O(n^2) in worst case, plus other O(n) loops over visualised drawables.
I noticed this as a hot line when profiling:
This changes makes DrawVisualiser instead respond to additions/removal from AliveInternalChildren, and caches the VisualisedDrawables, removing the need for expiry/reconstruction and more O(n) searching.
Along with this, these changes also seem to fix the flickering present due to the expiries inside VisualisedDrawable, such as in the case of TestCaseBlending.
> Improve performance of DrawVisualiser

- osu.Framework/Graphics/Containers/TabbableContainer.cs
What it sounds like. If you had a hierarchy like this:
```
Container
|-> CompositeDrawable
|-> TextBox (TabbableContentContainer set to Container)
|-> CompositeDrawable
|-> TextBox (TabbableContentContainer set to Container)
```
Then tabbing between the TextBoxes would not work, because they are both children of a CompositeDrawable. This is fixed by checking through all children of all CompositeDrawables, instead of only of Containers when figuring out which control to transfer focus to when tabbing.
> Fix TabbableContainer ignoring children of CompositeDrawables

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
- osu.Framework/Logging/Logger.cs
- osu.Framework/Platform/GameHost.cs
All methods of the Logger class are now thread-safe. Logging can be
constrained by Log-Level. All public static methods, relevant enums
and auxiliary classes are fully documented. The osu-specific
Tournament LoggingTarget has been removed, instead the Logger now
allows using arbitrary strings as names for loggers, so long as they
do not conflict with any already existing LoggingTarget enum-names.
If they do, logging with these names is equivalent to providing the
conflicting LoggingTarget.
WaitForCompletion has been changed to Flush, and no longer stops
all logging after it is called once.
One notable caveat with Flush:
```CSharp
// Correctly flush and cease logging:
Logger.Enabled = false;
Logger.Flush();
// Incorrectly flush, might still have some stray log messages after flushing in …
```
> Refactor and extend Logger

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Improves debug performance by over 10% in scenarios drawables are removed regularly.
> Remove insanely expensive string format operation

- osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
Adds a line about the need for HandleInput to be set to true in the xml docs of TooltipContainer, IHasTooltip and IHasCustomTooltip.
> Add note about HandleInput to Tooltip docs

- osu.Framework/Graphics/Drawable.cs
This is useful in scenarios where the clock time is read from somewhere else and updated within a derived UpdateSubTree, such as replay playback. In such scenarios, we don't want to call ProcessFrame() on the clock twice as doing so would affect FPS count and AverageFrameTime.
> Expose a way to stop clock updates

- osu.Framework/MathUtils/Interpolation.cs
Improved the easing functions by repeating less code, and by optimizing the algorithms.
The `ApplyEasing` method now only accepts one parameter next to `easing` type: `time`.
`time ` is the precalculated `time / duration`, it should be normalized in the 0 - 1 range. The return value of `ApplyEasing` is the amount to `Lerp` the `start` and `end` values with.
By removing these parameters a lot of useless value copies can be avoided.
Some of the algorithm changes were based on:
https://joshondesign.com/2013/03/01/improvedEasingEquations
https://gist.github.com/gre/1650294
> Easing improvements

- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/InputState.cs
Seems like a better place to leave this. Derived InputStates shouls also create distinct states for what they add to the base implementation.
Also contains a fix for derived implementations types being lost in distinct state creation (uses Clone instead of new InputState). This caused a regression in osu!.
> Move distinct state creation to InputeState

- osu.Framework/Configuration/FrameworkConfigManager.cs
I think most users would want this to be off as a default behaviour.
> Don't show log overlay by default

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
Should resolve https://github.com/ppy/osu/issues/1539, along with any other usages which rely on try-catch around `Perform()` or `await PerformAsync()`.
This is a regression from original WebRequest behaviour.
WebRequests also only fire `Finished` on non-erroneous completion. A new event `Failed` exists to handle failures now.
> Propagate WebRequest exceptions outwards from Perform methods

- osu.Framework.Tests/Visual/TestCaseAnimation.cs
- osu.Framework.Tests/Visual/TestCaseContainerState.cs
- osu.Framework.Tests/Visual/TestCaseDynamicDepth.cs
- osu.Framework.Tests/Visual/TestCaseEffects.cs
- osu.Framework.Tests/Visual/TestCaseSizing.cs
- osu.Framework.Tests/Visual/TestCaseTextFlow.cs
the `using NUnit.Framework` directives at the beginning of those TestCase files made them originally use the wrong Description attribute. They are now all fully qualified so the attributes work.
Framework change that originally introduced this problem: #1186
> Fixed Description attributes in Framework Tests

- osu.Framework/Audio/Track/TrackVirtual.cs
Not sure how this wasn't an issue until now...
> Fix calling Reset on a TrackVirtual starting the track unexpectedly

- osu.Framework/Audio/Sample/Sample.cs
- osu.Framework/Audio/Sample/SampleBass.cs
- osu.Framework/Audio/Sample/SampleManager.cs
8 was way too high for most use-cases. Also makes this configurable at a SampleManager level if this default is not appropriate for certain use-cases. Can be expanded to per-Get when necessary.
> Reduce default sample concurrency to two

- osu.Framework/Graphics/DrawInfo.cs
- osu.Framework/Graphics/Drawable.cs
Saw #1153 and tried to reduce CPU usage of the function. In my (isolated) tests with a huge load of tested floats, this resulted in around 12-15% performance increase and in in-game tests (granted I'm not too used to performance profiling, but the numbers should still be correct) CPU time for checkComponentValid was actually reduced by 15-20%.
Explanation for why I did what I did:
The old implementation checks for `float.IsNaN(value) || float.IsInfinity(value)`. So for this to be true, the `value` has to be `float.NaN`, `float.PositiveInfinity` or `float.NegativeInfinity`.
Looking into the specifications, if the exponent of a float value is 255 (its max value), the float has to be any one of these three values ([source](https://en.wikipedia.org/wiki/Single-precision_floating-point_format#E …
> Changed the float validation inside DrawInfo.ApplyTransform for performance gain

- LangVer.props
- SampleGame/SampleGame.csproj
- osu-framework.sln.DotSettings
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework.props
- osu.Framework/Allocation/TimedExpiryCache.cs
- osu.Framework/Graphics/Shaders/Shader.cs
- osu.Framework/osu.Framework.csproj
Have converted most new resharper suggestions to hints, except `JoinNullCheckWithUsage` which results in weird code in some scenarios. This would transform code in the following way:
```
if (x == null) throw new ArgumentNullException(nameof(x));
this.x = x;
```
->
```
this.x = x ?? throw new ArgumentNullException(nameof(x));
```
We can re-enable these as we see fit in further PRs (especially the out variable one I think).
> Migrate to C# 7

- osu.Framework/RuntimeInfo.cs
- osu.Framework/osu.Framework.csproj
- osu.Framework/packages.config
✓ Cross platform (.NET Core compatible)
✓ No uname issues with debugging
✓ No more relying on magic constants defined by mono (6 is a recent addition for osx)
> Add a better method to retrieve platform-specific information

- osu.Framework.Tests/Visual/TestCaseDrawSizePreservingFillContainer.cs
- osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
Fixes ppy/osu#1512
First commit is an addition to `TestCaseDrawSizePreservingFillContainer` where you can manually override the `DrawSizePreservingFillContainer`'s `Parent.Size` to 1x1, after which you can re-adjust it via the sliders again. What you should see is that the content of the `DrawSizePreservingFillContainer` stays black (in the old version), and with the draw visualiser you can see that the `DrawSizePreservingFillContainer`'s Scale is very small which leads to it's `IsPresent` field being false, which in turn leads to it not getting any more `Update()` calls which then again leads to it (and its children) not displaying ever again.
I (well, Tom94 had the good idea, mine was more a hackaround) fix this in the second commit by overriding …
> Fixes the reoccurring "blackscreen on minimize" bug

- osu.Framework/Testing/TestCase.cs
Also only replace if the class name starts with TestCase, to avoid cases like OsuTestCase being potentially mangled.
> Use replace instead of magic substring when assigning a TestCase's name

- osu.Framework/Screens/Screen.cs
The Screens OnKeyDown-Method was overridden to automatically exit the
screen on hitting escape. This is hardly always wanted or necessary and
being unaware of this feature can trivially cause bugs. This
functionality is best left to be implemented by the user via their
own Screen subclasses.
Please note that the osu project itself will need to make compensatory changes if it relies on this behaviour. I assume it currently does so for things like the options or similar.
> Remove Screen.OnKeyDown override

- osu.Framework.Tests/Visual/TestCaseSearchContainer.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Testing/Drawables/TestCaseButton.cs
- osu.Framework/Testing/TestBrowser.cs
> Make test cases searchable in TestBrowser

- osu.Framework/Audio/AudioCollectionManager.cs
- osu.Framework/Audio/AudioComponent.cs
- osu.Framework/Audio/Sample/SampleChannel.cs
Tracks have more manual lifetime management and should not be removed from their parent until disposed.
> Fix tracks no longer getting processed when they complete playback

- osu.Framework/Audio/Track/Track.cs
Related to ppy/osu-framework/pull/1227 (and ppy/osu/pull/1649)
I removed the `HasReachedEnd` property as it would get redundant.
> Remove no longer needed HasReachedEnd property

- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
Does what it says in the title. Previously setting a TextFlowContainer to AutoSize on X would crash as soon as it internally added a NewLineContainer due to the NewLineContainer being implemented via relative-sizing on the X axis, creating an exception in the FlowContainers internal validation.
This somewhat hackily allows subclasses of FillFlowContainer more control over the layout the FillFlowContainer creates, which TextFlowContainer can use to sidestep the whole issue.
Unsure if this is the right way forward, but it was a simple thing to do and gets the job done without getting in the way of anything else, not that I can think of, at least.
Please destroy.
> Allow TextFlowContainer to AutoSize on the X axis

- .vscode/tasks.json
Since last request, `/p:Configuration=Release` to `-c:Release`, fixed stupid spelling mistake.
> Netstandard tasks.json

- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/FrameworkActionContainer.cs
- osu.Framework/Input/MouseState.cs
- osu.Framework/Input/PlatformActionContainer.cs
- osu.Framework/Input/UserInputManager.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/osu.Framework.csproj
It turns out the overhead and complexity is a lot lower this way.
This resolves the inability to nest `KeyBinding` handlers inside each other and better handles cross-`Container` and cross-`InputManager` scenarios.
This removes the workaround in `TextBox` which involved every `TextBox` having their own `InputManager`.
> Make KeyBindingInputManagers into Containers

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/Container.cs
The implementation of ChangeInternalChildDepth via AddInternal and
RemoveInternal would influence the ChildID, causing z-ordering to be
incorrect if the Depth was changed to a non-unique value inside the
CompositeDrawable.
Specifically, the following code will have bad z-ordering without this patch:
```C#
container.Add(drawable1);
container.Add(drawable2);
container.ChangeInternalChildDepth(drawable1, 10f);
container.ChangeInternalChildDepth(drawable1, 0f);
```
Despite ``drawable1`` being added first and having the same ``Depth``-Value as ``drawable2``, ``drawable1`` will be drawn on top of ``drawable2``.
This patch remedies this situation and ensures that ``drawable1`` after this code will be drawn behind ``drawable2`` as would be expected.
> Prevent ChildID from being changed by ChangeInternalChildDepth

- .vscode/tasks.json
Follows what's already in ppy/netstandard, however uses msbuild instead of dotnet, since dotnet doesn't support targetting net461 on mono.
> Update tasks.json format

- osu.Framework.Tests/Visual/TestCaseDropdownBox.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
This ensures that opened dropdowns are drawn on top of anything else inside their container, but only for the duration of them being opened.
This renders things like [ReverseChildIDFillFlowContainer](https://github.com/ppy/osu/blob/349dbfe263495b3479f8a13331446aafcc8a3b38/osu.Game/Graphics/Containers/ReverseChildIDFillFlowContainer.cs) unnecessary insofar ``FillFlowContainer``s with dropdowns in them are concerned.
Depends on #1239
> Dropdown depth

- osu.Framework.Tests/Visual/TestCaseDropdownBox.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
As discussed, this breaks in quite a few current use cases.
> Revert dropdown depth changes

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Testing/TestBrowser.cs
Previously the wrong clock and dependncies were used – the TestBrowser's rather than their load target, which contains a custom clock implementation.
> Use DelayedLoadWrapped instead of LoadComponentAsync for loading TestCases

- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Allocation/RecursiveLoadException.cs
- osu.Framework/Extensions/ExceptionExtensions/ExceptionExtensions.cs
- osu.Framework/Extensions/ExtensionMethods.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/osu.Framework.csproj
Because [this](https://ci.appveyor.com/project/peppy/osu/build/master-5904) is unreadable.
From:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Try find me!
at osu.Game.Rulesets.UI.Playfield.load () [0x00001] in /Users/smoogipoo/Repos/Temp/temp-osu/osu.Game/Rulesets/UI/Playfield.cs:64 
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
--- End of …
```
> Simplify BackgroundDependencyLoader exceptions

- osu.Framework/Host.cs
- osu.Framework/Input/GameWindowTextInput.cs
- osu.Framework/Platform/Architecture.cs
- osu.Framework/RuntimeInfo.cs
Also replaced the multiple bool values by an enum.
I left the `IsUnix` property in even though it's not used currently (or should `Host.cs` be changed so that the `LinuxGameHost` is used as a fallback if `IsUnix` is true? Atm it's exactly the same as checking for `OS == Linux`).
This closes #1224 .
> Check for multiple OS platform matches and throw an exception.

- osu.Framework/IO/Network/WebRequest.cs
This was causing countless unnecessary ObjectDisposedExceptions which impacts performance.
> Avoid unnecessarily aborting WebRequests if they are already completed or aborted

- osu.Framework/Logging/Logger.cs
Also avoids constructing strings when unnecessary.
> Fix Logger still outputting to screen even when OutputToListeners is disabled

- osu.Framework/Configuration/BindableBool.cs
- osu.Framework/Configuration/BindableNumber.cs
Avoid misleading scenarios like:
> Throw exceptions when implicitly casing Bindables to their counterparts

- osu.Framework/Localisation/LocalisationEngine.cs
This is regularly used from a BackgrounDependencyLoader context, which can cause weird threading issues due to lack of locking on WeakList<>
> Local all WeakList access in LocalisationEngine

- osu.Framework/Graphics/Sprites/SpriteText.cs
In cases where a derived class overrided `Content` this would cause failures. As changing TextSize is a relatively rare thing, there's no reason for this "optimisation" anyways.
> Don't access Children when changing TextSize

- osu.Framework.Tests/Visual/TestCaseAnimation.cs
- osu.Framework.Tests/Visual/TestCaseBlending.cs
- osu.Framework.Tests/Visual/TestCaseBufferedContainer.cs
- osu.Framework.Tests/Visual/TestCaseCheckboxes.cs
- osu.Framework.Tests/Visual/TestCaseCircularContainer.cs
- osu.Framework.Tests/Visual/TestCaseCircularProgress.cs
- osu.Framework.Tests/Visual/TestCaseContextMenu.cs
- osu.Framework.Tests/Visual/TestCaseDelayedLoad.cs
- osu.Framework.Tests/Visual/TestCaseDrawSizePreservingFillContainer.cs
- osu.Framework.Tests/Visual/TestCaseDropdownBox.cs
- osu.Framework.Tests/Visual/TestCaseEffects.cs
- osu.Framework.Tests/Visual/TestCaseFillFlowContainer.cs
- osu.Framework.Tests/Visual/TestCaseLocalisation.cs
- osu.Framework.Tests/Visual/TestCaseMasking.cs
- osu.Framework.Tests/Visual/TestCaseNestedHover.cs
- osu.Framework.Tests/Visual/TestCaseNestedMenus.cs
- osu.Framework.Tests/Visual/TestCasePropertyBoundaries.cs
- osu.Framework.Tests/Visual/TestCaseRigidBody.cs
- osu.Framework.Tests/Visual/TestCaseScreen.cs
- osu.Framework.Tests/Visual/TestCaseScrollableFlow.cs
- osu.Framework.Tests/Visual/TestCaseSearchContainer.cs
- osu.Framework.Tests/Visual/TestCaseSizing.cs
- osu.Framework.Tests/Visual/TestCaseSpriteText.cs
- osu.Framework.Tests/Visual/TestCaseTabControl.cs
- osu.Framework.Tests/Visual/TestCaseTextBox.cs
- osu.Framework.Tests/Visual/TestCaseTextFlow.cs
- osu.Framework.Tests/Visual/TestCaseTooltip.cs
- osu.Framework.Tests/Visual/TestCaseTriangles.cs
- osu.Framework/Testing/TestBrowser.cs
Don't show assemblies with no tests.
> Clean up the TestBrowser assembly dropdown

- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Input/IHandleGlobalInput.cs
- osu.Framework/Input/PlatformActionContainer.cs
- osu.Framework/osu.Framework.csproj
Global handlers can now continue to receive input even when it is being blocked by OverlayContainers.
Helps in fixing https://github.com/ppy/osu/issues/1668 and https://github.com/ppy/osu/issues/1615.
> Improve key blocking behaviour of OverlayContainer

- osu.Framework/Screens/Screen.cs
The reason is that push function work with async.
So, That can be wrong work. Because Exit function can be called before async push function done.
I inserted function escape code when this scene exited.
> returning Push function when screen hasExited.

- osu.Framework/Allocation/RecursiveLoadException.cs
From:
`osu.Framework.Allocation.RecursiveLoadException : Exception of type 'osu.Framework.Allocation.RecursiveLoadException' was thrown.`
To:
`osu.Framework.Allocation.RecursiveLoadException : The type initializer for 'osu.Game.Database.OsuDbContext' threw an exception.`
> Return the original message from RecursiveLoadExceptions

- osu.Framework/osu.Framework.csproj
Same thing as in https://github.com/ppy/osu/pull/1673.
It gets included and marked as a change every time you run tests on VS which is pretty annoying.
> Add NUnit Itemgroup to csproj

- osu.Framework/Graphics/Drawable.cs
Was causing a memory leak in TestBrowser.
> Immediately unbind all bindings to OnLoadComplete after load is complete

- osu.Framework/Input/Bindings/InputKey.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
- osu.Framework/Testing/TestBrowser.cs
- osu.Framework/Testing/TestBrowserTestRunner.cs
- Ctrl-F to search (and hit enter to load first match)
- Ctrl-H to hide test listing
- Ctrl-R to re-run current test
> Add keyboard controls to TestBrowser

- osu.Framework/Logging/Logger.cs
- osu.Framework/Testing/TestCase.cs
This allows discerning between description and raw exception outputs when displaying to the end user.
Does not affect underlying logging to file.
> Log exception content as Important rather than error

- osu.Framework.Tests/Visual/TestCaseTabControl.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
This adds a separate order value that gets tracked alongside each child added to a ``FlowContainer`` effectively ensuring that the z-ordering of children has no influence over their position in a layout produced by a ``FlowContainer``.
This change required fixing up ``TabControl`` which relied on the old behaviour and adjusted z-ordering of children in order to change their positions in a layout.
While reworking ``TabControl`` I also noticed that the ``Items`` property returned the list of values not in the displayed order, but in reversed display order, which I changed, since it conflicted with what the documentation said about the ``Items`` property.
> Explicit flow order

- osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
This allows for a "pass-through" style for tooltips, where something can be on top of something else, but the tooltip is still retrieved from the bottom item.
I thought it was better to use an extra property rather than ignoring `null` tooltips in case it is intentional for a tooltip to be set to `null`.
> Add the ability to ignore a tooltip and get the below tooltip

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
For when you want to compute values using the alive states of children, but `Update` is too early (called before `UpdateChildrenLife`) and `UpdateAfterChildren` is too late (called after childrens' `UpdateSubTree`)
> Expose a new method that is invoked after UpdateChildrenLife

- osu.Framework/Graphics/Containers/OverlayContainer.cs
Alternative to ppy/osu#1866
Basically doing as the keyboard stuff does. I didn't change the default value of BlockPassThroughMouse because that goes down a very deep way.
> Allow global mouse bindings to work with OverlayContainers

- osu.Framework/Graphics/Containers/GridContainer.cs
There are three scenarios where this is desired:
1. Fully async-loading a grid structure.
* `GridContainer` will currently load itself, but because its children aren't added until the `layoutContent` which is called during `Update`, its children won't be loaded until the first `Update`, at which point they'll load synchronously.
2. If an object is added to a GridContainer and that object constructs a child inside its load() method, an outsider cannot indirectly reference that child expecting it to be constructed.
* E.g.
```
GridContainer
-> Contains a playfield
load()
-> playfield.Add(myHitObject) // Will fail because the hitobject list is constructed in playfield's load, which hasn't been called yet due to its wrapping GridContainer
```
> Fix GridContainer not performing layout/loading children before Update

- osu.Framework/Graphics/Containers/GridContainer.cs
This is a pretty useless computation to be done at this point in time for a few reasons:
1. It is wrong in terms of getting correct sizing since we don't have a parent at this point.
2. The cell layout is invalidated upon LoadComplete (and hence re-computed in Update) anyway.
> Don't layout cells in GridContainer's BDL

- osu.Framework.Tests/Visual/TestCaseBindableNumbers.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Configuration/BindableDouble.cs
- osu.Framework/Configuration/BindableFloat.cs
- osu.Framework/Configuration/BindableInt.cs
- osu.Framework/Configuration/BindableLong.cs
- osu.Framework/Configuration/BindableNumber.cs
- osu.Framework/Graphics/UserInterface/BasicSliderBar.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
- osu.Framework/Testing/Drawables/Steps/StepSlider.cs
- osu.Framework/Testing/TestCase.cs
* Fixes Precision not working for BindableInt/BindableLong.
* Cleans up/consolidates a lot of code that was shared between all numeric BindableNumber implementations.
* Adds testcase.
> Fix precision not working for BindableInt/BindableLong

- osu.Framework/Graphics/Cursor/TooltipContainer.cs
This fixes tooltips not working inside `OverlayContainer`.
> Add IHandleGlobalInput to TooltipContainer

- osu.Framework.Tests/Visual/TestCaseDelayedLoad.cs
- osu.Framework.Tests/Visual/TestCaseTooltip.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Containers/VisibilityContainer.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/Visualisation/LogOverlay.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/PassThroughInputManager.cs
- osu.Framework/Screens/Screen.cs
At the moment both keyboard and mouse input queues are built using `CanReceiveInput`(which depends on `HandleInput` property).
Since `HandleInput` does not distinguish keyboard and mouse events this causes one small problem. Keyboard queue can contain drawables which handles only mouse events and mouse queue can contain drawables which handles only keyboard events which is not correct.
I guess that not having unnecessary drawables in input queues is good in terms of performance.
On the other hand, I did increase the number of properties. :(
I hope this is acceptable since we do not override `HandleInput` often.
All overrides in osu! solution:
[osu! game](https://github.com/UselessToucan/osu/tree/RefactorInputQueues) branch which I can PR if required.
> Store handleability of input separate for keyboard and mouse

- osu.Framework/Graphics/Cursor/CursorContainer.cs
Doesn't seem to have any effects (testcase, visualtests, and gameplay). There's no reason why this should be an overlaycontainer imo, since it never requires input to not be passed to children.
> Make CursorContainer not an OverlayContainer

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
In a case where AutoSizeDuration is changed from non-zero to zero at runtime, it si possible a previous transform is still running when a subsequent autosize is performed. The previous transform would overwrite the new size and provide an incorrect final size.
> Fix AutoSizeDuration not being cleared correctly in some cases

- osu.Framework/IO/Stores/DllResourceStore.cs
Note that everything _but the last_ string here has its hyphens replaced by underscores. This is intentional because only the directory paths in the manifest replace the hyphens. The actual file names don't.
> Fix DllResourceStore not being able to handle hyphens in file path

- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Platform/GameHost.cs
Alternative to https://github.com/ppy/osu-framework/pull/1336 . Since we can't seem to come to an agreement as to which type we should cache. One of these has to happen, and I believe this is the cleaner of the solutions.
With these changes:
* `Cache` - Always caches the most derived type.
* `CacheAs<T>` - Allows caching as a base type (e.g. `Storage`).
* There is no more overwrite parameter - we've previously discussed that this isn't useful anymore since we have local dependencies.
* `Cache` no longer returns the object back.
> Allow BDL caching by specific type

- osu.Framework.Tests/Bindables/BindableBoolTest.cs
- osu.Framework.Tests/Bindables/BindableDoubleTest.cs
- osu.Framework.Tests/Bindables/BindableEnumTest.cs
- osu.Framework.Tests/Bindables/BindableFloatTest.cs
- osu.Framework.Tests/Bindables/BindableIntTest.cs
- osu.Framework.Tests/Bindables/BindableLongTest.cs
- osu.Framework.Tests/Bindables/BindableStringTest.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableBool.cs
- osu.Framework/Configuration/BindableDouble.cs
- osu.Framework/Configuration/BindableFloat.cs
- osu.Framework/Configuration/BindableInt.cs
- osu.Framework/Configuration/BindableLong.cs
- osu.Framework/Configuration/BindableNumber.cs
* Removes custom `Parse` methods from derivers of `BindableNumber`.
* This is handled by the base `Bindable<T>.Parse`.
* Only "big" difference is that value-in-range checks are missing, which I don't think are a critical component anyway.
* Adds testcases.
> Bindable parsing fixes

- osu.Framework/Configuration/ConfigManager.cs
This behaviour wasn't even correct as `default(U)` would not match the expected type for cases like `BindableDouble`.
> Stop ConfigManager from setting a default when calling GetOriginalBindable

- osu.Framework.Tests/Visual/TestCaseCircularContainer.cs
Failing under some environments
> Use AlmostEquals for CircularContainer test cases

- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/FrameworkActionContainer.cs
Alternative to ppy/osu#1974. Fixes Alt+Enter from not working in `GameplayMenuOverlay` and `SongSelect`.
> Fix FrameworkActionContainer input ordering

- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Platform/GameHost.cs
@Tom94 Thoughts?
Basically, we cannot compute `IsMaskedAway` as soon as it is used due to it requiring that autosize calculations have taken place. It is dangerous for autosize computations to occur through a call to `IsMaskedAway` since it's possible that `UpdateSubTree` hasn't been called on the relevant drawables, and lifetimes/other stuff has possibly not been updated by that point.
To be able to use this in `RulesetInputManager`, we cannot have the computation occur in `GenerateDrawNodeSubtree`, as that constructs/modifies `DrawNode`s. Due to this, I chose to have the computation occur as a post-`UpdateSubTree` method, with the following usage in `RulesetInputManager`:
> Fix up recent IsMaskedAway regressions

- osu.Framework.Tests/Visual/TestCaseIsMaskedAway.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/ProxyDrawable.cs
- osu.Framework/Platform/GameHost.cs
We were using the incorrect masking bounds for the drawable. This is causing taiko hitobjects to get masked away when they're moved to an upper (non-masking) layer, intended to avoid the hitobjects getting masked away.
Also adds a whole slew of automated testcases for IsMaskedAway.
> Fix wrong IsMaskedAway value when proxies are involved

- osu.Framework/Testing/TestBrowser.cs
Resolves ppy/osu#1781.
Alternative to #1319, fixes the underlying cause - OnLoadComplete is called from a child which is currently being updated, and this will trigger GetContainingInputManager to be null since the child now has a null parent.
> Fix tests being removed from TestBrowser while they're being updated

- SampleGame.iOS/SampleGame.iOS.csproj
- osu-framework.iOS.sln
- osu-framework.sln
- osu.Framework/osu.Framework.csproj
* Splits out iOS build into a separate sln.
* Still requires `nuget restore` to be run from terminal prior to loading in vs for mac... This is potentially an issue we can report to MS.
> Attempting to improve the iOS load/build process

- osu.Framework/Configuration/ConfigManager.cs
Closes ppy/osu-framework#1387.
> Debounce config saves

- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
Now displays internal/protected properties (e.g. IsMaskedAway).
> Fix PropertyDisplay ignoring protected and internal properties

- osu.Framework.Tests/Visual/TestCaseTextBox.cs
- osu.Framework/Graphics/Containers/TabbableContainer.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Input/PlatformActionContainer.cs
* Fixes TextBoxes blocking all key input.
* Not entirely sure why this was here, if any case comes up where this breaks we'll analyse it/comment it appropriately.
* Removes unnecessary returns which are already handled in `OnAction`.
* Fixes `PlatformActions` not being handled before keys.
* Fixes not being able to Cmd+Left/Cmd+Right in the search box in SongSelect.
* Fixes readonly textboxes being able to be tabbed to. Browsers do the same thing.
> Various improvements to textbox input

- osu.Framework/Testing/TestBrowser.cs
Closes #1347 .
I kept the behaviour the same, where it deletes the dynamically compiled tests (and the dropdown entry for the dynamic assembly) when switching back to a "statically" compiled test.
> Fix dynamically compiled test cases disappearing from old assembly

- osu.Framework/Platform/GameHost.cs
Under certain conditions, the audio thread is getting stuck during exit due to an underlying bass call. This should hopefully resolve that issue.
On top of this, we *do* always want to have a failsafe timeout for all threads to the game itself eventually gives up and leaves thread cleanup to the OS.
> Add a timeout for thread exiting

- osu.Framework.Tests/IO/TestWebRequest.cs
The service we use for testing live-wire communications (httpbin) can occasionally fail to respond as we expect.
This allows tests to retry after an initial failure, rather than report false positive failures.
> Allow web request tests to re-run on failure

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
It seems like retry logic was already running and tests failed regardless, so retrying alone likely isn't going to help the scenario.
> Revert retry test case changes

- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Audio/Sample/SampleManager.cs
- osu.Framework/Audio/Track/TrackManager.cs
- osu.Framework/Graphics/Textures/TextureStore.cs
As we begin to query optional sources, such as user-provided content, it's more frequent that queries may be null or empty. In these cases it seems like handling and returning null is better than throwing exceptions.
Note that nulls are already returned in cases like `TextureStore`; this just allows the query to be null without throwing an exception.
> Allow resource managers to accept and return null

- osu.Framework/Graphics/Drawable.cs
Until now, it has not been possible to run some "final" code after all `BackgroundDependencyLoader` methods have been run. This fixes that shortcoming.
> Add a LoadAsyncComplete method

- osu.Framework/Allocation/ObjectStack.cs
In cases where the ObjectStack has a large `maxAmountObjects` (say 100), the HashSet operations can become a huge bottleneck. There's really no point in tracking them.
> Don't track all used objects

- osu.Framework/Platform/GameHost.cs
Want to make sure cases like this do not go unnoticed.
> Add logging when threads fail to join in time

- osu.Framework/Testing/TestBrowserConfig.cs
Not sure how anyone was using visualtests. It would just crash on a fresh install.
> Fix VisualTests crashing on first startup due to incorrect configuration

- osu.Framework/Graphics/Containers/ScrollContainer.cs
They are too expensive to use. We either need to stop using them or make alternative arrangements.
Same changes need to be made on the osu!-side if we decide not to change the way zero-duration transform helpers handle themselves (for instance `ParallaxContainer`).
> Reduce dependence on zero-duration transforms

- osu.Framework/Graphics/Transforms/Transform.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
Not only were they applying, but they were running their OnComplete actions every frame forever. Huge performance losses.
Regressed with implementation of rewind support.
> Fix transforms on RemoveCompletedTransforms drawables applying forever

- osu.Framework/Testing/DynamicClassCompiler.cs
- osu.Framework/Testing/TestBrowser.cs
Handles any exceptions thrown in the loaded TestCase's Update or UpdateSubTree.
Closes #1284.
> Catch exceptions thrown during dynamic compilation runtime

- osu.Framework/Platform/DesktopGameWindow.cs
First time contributing to an open source project, wanted to start small.
fixes ppy/osu#1388 
My reproduction of the bug: https://streamable.com/4wn3l (also tested on my laptop, same result)
When switching to fullscreen mode, the BitsPerPixel were being set to 0, which is an invalid value. When OpenTK detects 0bpp it uses a default value instead, resulting in the 256 colors mode (8bpp) mentioned in the issue above.
> Set display colour depth to correct value when switching to fullscreen

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
There was a scenario where log entries could recursively trigger more log entries as they were not loading asynchronously (triggering a log mentioning they weren't loading asynchronously).
> Load log entries asynchoronously

- osu.Framework.Tests/Visual/TestCaseCachedBufferedContainer.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Adds extensive testing of caching.
> Avoid updates / generating draw nodes for valid BufferedContainers

- osu.Framework.Tests/Visual/TestCaseTabControl.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
This adds a separate order value that gets tracked alongside each child added to a FlowContainer effectively ensuring that the z-ordering of children has no influence over their position in a layout produced by a FlowContainer.
This change required fixing up TabControl which relied on the old behaviour and adjusted z-ordering of children in order to change their positions in a layout.
While reworking TabControl I also noticed that the Items property returned the list of values not in the displayed order, but in reversed display order, which I changed, since it conflicted with what the documentation said about the Items property.
Recreates #1261 due to demand in #1303
> Recreate changes for explicit flow order from #1261

- osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs
- osu.Framework.Tests/Visual/TestCaseTransformSequence.cs
- osu.Framework/Graphics/Transforms/Transform.cs
- osu.Framework/Graphics/Transforms/TransformSequence.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
- Fixes jumping forward to the middle of active transforms
- Fixes rewinding in general.
- Fixes rewinding over infinite loops.
- Adds visually understandable tests. Asserts can/should be added in the future.
> Overhaul transform logic to fix many failing rewind/seek cases

- osu.Framework/Graphics/Containers/TextFlowContainer.cs
Sometimes we just want to add a custom `SpriteText` type to a `TextFlow`.
Example usage:
```csharp
infoTextLeft.NewLine();
infoTextLeft.AddText("Last seen ", lightText);
infoTextLeft.AddText(new DrawableDate(user.LastVisit), boldItalic);
infoTextLeft.NewParagraph();
```
> Add method to add arbitrary drawables to TextFlowContainers

- osu.Framework/IO/Network/WebRequest.cs
Previously misleading "request successful" could be followed by a response process failure, resulting in overall failure.
> Add logging of failed response processing to network log

- osu.Framework/Graphics/Drawable.cs
This should not be used by framework consumers.
> Make ChildID internal

- osu.Framework/Platform/DesktopGameWindow.cs
- osu.Framework/Platform/GameWindow.cs
- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
- osu.Framework/Platform/Windows/WindowsGameWindow.cs
Reintroduces the changes and fixes the windows bug from #1420 .
This should probably still be tested on all other platforms.
Edit: Closes #1102 (again).
> Reintroduce & fix gamewindow refactor

- osu.Framework/Graphics/Component.cs
- osu.Framework/osu.Framework.csproj
This is paving the way to allow for non-drawable components to exist in the hierarchy.
Fully fleshing this out is on the short-term roadmap, but for the time being I would like this class to exist so we can at very least mark non-drawable items as we add them, so they can instantly take advantage of future changes.
> Add a base component class

- osu.Framework/Configuration/ConfigManager.cs
By incrementing the save ID we can potentially avoid unnecessary background saves.
> Avoid background saves after actual saves occur

- osu.Framework/Audio/Track/Track.cs
- osu.Framework/Audio/Track/TrackVirtual.cs
And also disallow negative length values for `Length`.
> Fix being able to seek TrackVirtual to negative time values

- osu.Framework/Timing/StopwatchClock.cs
```
StopwatchClock.Seek(50); <- CurrentTime = 50
StopwatchClock.Seek(100); <- CurrentTime = 50
StopwatchClock.Seek(200); <- CurrentTime = 150
```
versus
```
trackBass.Seek(50); <- CurrentTime = 50
trackBass.Seek(100); <- CurrentTime = 100
trackBass.Seek(200); <- CurrentTime = 200
```
This brings the clocks in-line with one another, so that now:
```
StopwatchClock.Seek(50); <- CurrentTime = 50
StopwatchClock.Seek(100); <- CurrentTime = 100
StopwatchClock.Seek(200); <- CurrentTime = 200
```
> Fix seekOffset being considered when seeking

- osu.Framework/Graphics/Containers/ContainerExtensions.cs
- osu.Framework/Graphics/Effects/BlurEffect.cs
- osu.Framework/Graphics/Effects/EdgeEffect.cs
- osu.Framework/osu.Framework.csproj
Adds and exposes a wrap method that removes duplicate code that was shared between `EdgeEffect` and `BlurEffect`.
This also fixes #1167.
> Add wrap method to remove duplicate code in effects

- osu.Framework/Platform/GameHost.cs
TaskCompletionSource is way too slow.
Also operations were being done on the draw thread which didn't need to be.
We may want to go down the path of making schedulers return Tasks to allow awaiting on them. UselessToucan had such an implementation in an earlier iteration if we decide to do this.
> Fix performance of TakeScrenshotAsync

- osu.Framework/Graphics/Audio/WaveformGraph.cs
- osu.Framework/Graphics/Batches/VertexBatch.cs
- osu.Framework/Graphics/Containers/CompositeDrawNode.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Closes ppy/osu#2274 .
Alternative to ppy/osu#2274, in a way that adds the same change for `CompositeDrawable` and `WaveformGraph`, and any future `DrawNode`s we may implement.
Also removes `CustomVertexAction` because it's never used and it's probably never going to be used.
> Add a cached delegate for VertexBatch.Add()

- osu.Framework/Graphics/UserInterface/TextBox.cs
Closes ppy/osu#2234.
Closes ppy/osu#2237.
> TextBox should only handle keyboard input when focused

- osu.Framework/Configuration/FrameworkConfigManager.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Statistics/BackgroundStackTraceCollector.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
This comes with quite a large overhead and as such should not be enabled by default.
> Expose the ability to disable background performance profiling

- osu.Framework/Testing/DynamicClassCompiler.cs
The FSW would get disposed and never trigger onchange events.
> Fix dynamic compilation not detecting changes on .NET Core

- osu.Framework/Input/FrameworkActionContainer.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Testing/DynamicClassCompiler.cs
IntelliSense does not show them in completion list, but no error reported. Should be their bug.
Quite minor, and may be merged together with other improvements.
> Use Linq.Append and Prepend.

- osu.Framework/Properties/AssemblyInfo.cs
- osu.Framework/Testing/DynamicClassCompiler.cs
- osu.Framework/Testing/TestBrowser.cs
The old method was using one global namespace across all projects, incorrectly giving `osu.Game` access to `osu.Framework` internals.
> Explicitly define the dynamic compilation namespace to avoid crosstalk

- osu.Framework.Tests/Visual/FrameworkTestCase.cs
Should not be instantiated on its own. Was showing up in TestBrowser for no reason.
> Make FrameworkTestCase abstract

- osu.Framework/Graphics/Drawable.cs
Reduces anywhere from 1.5-2.5K IsMaskedAway calculations, depending on the screen. Results in about 35-45 update fps boost (270/280 - 310/320) in gameplay (mania), about 30fps in SongSelect.
This would've previously been computed during drawnode creation only if we were present anyway (basically just before the `IsMaskedAway` check in `addFromComposite`).
> Significantly reduce number of IsMaskedAway calculations

- osu.Framework.Tests/Visual/FrameworkTestCase.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/TestCase.cs
- osu.Framework/Testing/TestCaseTestRunner.cs
Aligns headless nUnit testing to how we expect tests to behave in VisualTests.
> Make sure each TestCase runs all tests under one GameHost

- osu.Framework/Testing/TestCase.cs
- osu.Framework/Testing/TestCaseTestRunner.cs
Seems to fix remaining issues.
> Ensure host is in a running state before running tests further

- osu.Framework/Testing/DynamicClassCompiler.cs
Some file systems / editors don't change files, but delete and create them. This should cover those cases.
> Fix dynamic compilation not working for some users

- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
https://www.khronos.org/opengl/wiki/Primitive#Quads states that Quads are legacy api and shouldn't be used
Also reduces memory consumption from 4\*N to 2\*N+2 where N is the vertex size
> Replace PrimitiveType.Quads with PrimitiveType.TriangleStrip in CircularProgressDrawNode

- osu.Framework/Graphics/TransformSequenceExtensions.cs
- osu.Framework/Graphics/TransformableExtensions.cs
- osu.Framework/Graphics/Transforms/TransformBindable.cs
- osu.Framework/Graphics/Transforms/TransformCustom.cs
- osu.Framework/MathUtils/Interpolation.cs
Adds:
* `ITransformable.TransformBindableTo()`
* `TransformSequence.TransformBindableTo()`
Simplifies cases such as:
* https://github.com/ppy/osu-framework/pull/1538/files#diff-2af10bd70f4a7f83f67a8ab2d0444b90R16
* https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs#L111
> Add a way to transform bindables

- osu.Framework.Tests/Bindables/BindableBindingTest.cs
- osu.Framework/Configuration/Bindable.cs
Resolves [#2460](https://github.com/ppy/osu/issues/2460) and every other future similar implementation's issues with resetting values.
This is not really tested, but it should (hopefully) not break anything.
> Change order of lines to properly raise events

- osu.Framework.Tests/Visual/TestCaseSpriteTextPresence.cs
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
When a `SpriteText`'s text becomes `string.Empty`, it will become `!IsPresent`, and will:
1. Not clear its children
2. Not alert parents of this presence change.
This fixes both of those.
> Fix SpriteText size not being computer when set to empty

- osu.Framework/Graphics/UserInterface/CircularProgress.cs
https://github.com/ppy/osu/pull/2430#issuecomment-383315446
> Add CircularProgress.FillTo method

- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
Fixes ppy/osu#2268
At this point I've spent about 1.5 days trying to nail down the exact frame-by-frame issue, to no avail, so I'm going to PR this as it is a sane change.
The issue that sparked this is https://github.com/ppy/osu/issues/2268 and similar issues happening in BreakOverlay:
It seems that the issue is a mix of invalidation + frame timings + values of `AddChildDrawNodes` / `RequiresChildrenUpdate`, causing what I imagine: the `BufferedContainerDrawNode` receives an updated `ScreenSpaceDrawRectangle` which it uses for the ortho projection, but the child of the `BufferedContainerDrawNode` doesn't get updated.
Went through and sanity checked most of `BufferedContainer` - making it use the common "shared data" paradigm that's used for other drawnodes, adjusting draw/child update …
> Clean up BufferedContainer and fix alignment issues

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
The issue that sparked this: https://github.com/ppy/osu/pull/2496
**Explanation**:
`DrawableMedal` binds to `medalContainer.OnLoadComplete`, to set the position of some text contained within that container (i.e. `unlocked.Position = new Vector2(0f, medalContainer.DrawSize.Y / 2 + 10);`).
This is expecting two things:
1. The children of `medalContainer` are loaded.
2. The children of `medalContainer` is alive.
(1) Is fulfilled by `LoadComplete` being called from `UpdateSubTree`, which occurs post-all-children-being-loaded.
(2) Is where the issue occurs. `CompositeDrawable.load()` called `UpdateChildrenLife`, but it would get blocked by load state check in `checkChildLife`: https://github.com/ppy/osu-framework/compare/master...smoogipoo:async-child-life?expand=1#diff-2f079688019880634dc52499 …
> Make children life update in BDL-load

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
In the case of, e.g.:
```
container1 = Container
AutoSizeAxes = Axes.Both
Children =
{{ other children }}
container2 = Container
AutoSizeAxes = Axes.Both // Want to maintain a size
BypassAutoSizeAxes = Axes.Both // But we don't want the parent to size to us
```
If the size of `container2` was changed, it will propagate a `DrawSize` invalidation to `container1` which will cause `container1` to recompute its autosize.
When `container1` recomputes its autosize, it finds that `container2` has `BypassAutoSizeAxes`, so skips it.
This extra computation is unnecessary.
> Fix autosize invalidations occurring with BypassAutoSIzeAxes

- osu.Framework.Tests/Visual/TestCaseTooltip.cs
- osu.Framework/Graphics/Cursor/IHasAppearDelay.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
Avoids the requirement of adding a `null` `AppearDelay` to every usage of `IHasTooltip`
> Move custom AppearDelay into its own interface

- osu.Framework/Testing/TestBrowser.cs
Previously, the label text was touching the checkbox. This minor change adds padding between the label and the checkbox to improve aesthetics.
Before:
After:
> Added padding to the checkbox for running all steps.

- osu.Framework/Configuration/IBindable.cs
- osu.Framework/Configuration/ICanBeDisabled.cs
- osu.Framework/Configuration/IHasDefaultValue.cs
- osu.Framework/Configuration/IHasDescription.cs
- osu.Framework/Configuration/IUnbindable.cs
Previously, `IBindable` didn't have `Description`, and `IBindable<T>` didn't have `IsDefault`, `Disabled` or `DisabledChanged`.
This splits those properties out into interfaces common to both interfaces.
I didn't want to make `IBindable<T> : IBindable` as it would break the restrictions described [in the original implementation](https://github.com/ppy/osu-framework/pull/1517).
> Make IBindable and IBindable<T> share some common interfaces

- osu.Framework.Tests/Visual/TestCaseMouseStates.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/FrameworkActionContainer.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework/Input/IJoystickState.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/JoystickState.cs
- osu.Framework/Input/MouseState.cs
- osu.Framework/Input/PassThroughInputManager.cs
- osu.Framework/Testing/Input/ManualInputManager.cs
This started as a fix for ppy/osu#2158, but ended up as quite a serious improvement to testing and readability of input handling (with a focus on mouse).
The eventual goal is to remove delta values from `MouseState` and only provide them in `MouseEventArgs`, but as this is a breaking change I decided to first fix the majority of issues without this reorganisation to begin with.
- Removes `LastState` from `MouseHandler` and `JoystickHandler` in favour of private fields storing previous values.
- Refactors `createDistinctStates` to use similar logic for each device. Should be quite a bit easier to follow now.
- Removes `IRequireHighFrequencyMousePosition` from `InputManager` as it was deemed unneeded.
- Adds unit/visual tests for mouse states, including nested inside a …
> Fix mouse input state inconsistencies and add unit tests

- osu.Framework/Input/InputManager.cs
For cases where a custom InputState is being used, there was a chance it was getting lost during distinct state creation. This ensures at the end of creating distinct states we still return the new (original) state.
> Always yield the new state when creating distinct states

- Directory.Build.props
- SampleGame/SampleGame.csproj
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/osu.Framework.csproj
*I'm working on my own project these days, and found some noticeable things.*
The special name `Directory.Build.props` will be automatically imported by latest MSBuild.
Common property file should use relative path from itself.
The service guid is for unit test, so it's sure to keep it only in test project. (If ci is happy for this)
Should latest language version be introduced? C# releases minor versions rapidly now, and third-party tools may not understand it, especially for non-Visual Studio users.
But C# 7.x has improved some performance (span and readonly struct), making minor version update worth while.
Roslyn team is interested in enforcing code style at build time. Should I introduce rules in editor config now?
> Improvement to project files using Directory.Build.props

- osu.Framework.Tests/Visual/TestCaseTransformSequence.cs
- osu.Framework/Graphics/Transforms/ITransformable.cs
- osu.Framework/Graphics/Transforms/TransformSequence.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
Supersedes https://github.com/ppy/osu-framework/pull/1578
Fixes #1520.
- Fixes regressed loop with finite iteration counts due to missing reset of `Applied` and `AppliedToEnd` of cloned `Transforms`
- Fixes infinite loops containing `Transforms` that initially were instantaneously applied
> Fix broken TransformSequence.Loop

- osu.Framework/Platform/Windows/WindowsClipboard.cs
> Fix WindowsClipboard.SetText being broken

- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework.Tests/Visual/TestCaseMouseStates.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseState.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseState.cs
- osu.Framework/Input/PassThroughInputManager.cs
- osu.Framework/Testing/Input/ManualInputManager.cs
Refactored `int Wheel;` to `Vector2 Scroll;`. This lays the groundwork for eventually having smooth scrolling when devices support it (e.g. some trackpads, such as on MacBooks).
> Generalize scrolling from an integer to a Vector2

- osu.Framework/Graphics/Cursor/TooltipContainer.cs
This avoids the 1-frame delay that new tooltips usually have before
displaying the correct contents.
To elaborate a bit: If you have a setup in which there is only one TTC which uses only one tooltip, that tooltip gets toggled with Hide() and Show().
But when Show() is called because the tooltip is needed for a new tooltip-target, the tooltip is not immediately refreshed. Since the tooltip is being reused (because there is only one tooltip) there is a single frame in which it still displays the old and incorrect contents (and if it auto-sizes, has the old and incorrect size), which in some situations can cause a noticeable flicker when the tooltip gets displayed.
All this patch does is immediately call RefreshTooltip() to circumvent this issue.
> Immediately update new tooltips

- osu.Framework/Testing/DynamicClassCompiler.cs
Fixes #1575 
Only works when you compile the framework yourself
> Add parse options for dynamic compilation

- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseState.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework/Input/IMouseState.cs
- osu.Framework/Input/MouseState.cs
- osu.Framework/osu.Framework.csproj
- Adds support for precise scrolling on macOS trackpads. Verified to work correctly with non-precise input (tested with linear _and_ accelerated modes via SteerMouse)
- Allows scrolling through horizontal `ScrollContainer`s by scrolling horizontally.
- Fixes https://github.com/ppy/osu-framework/issues/1177
Resolves #1177 🎉 🎈
> Add support for precise and horizontal scrolling

- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/IBindable.cs
- osu.Framework/Configuration/ICanBeDisabled.cs
previous:
```csharp
bindable.ValueChanged += val => { // do stuff };
bindable.TriggerChange();
```
or
```csharp
bindable.ValueChanged += method;
method(bindable);
```
now:
```csharp
bindable.BindValueChanged(val => { // do stuff }, true);
bindable.BindValueChanged(method, true);
```
> Add ability to bind to ValueChanged and run bound method once automatically

- osu.Framework/Platform/GameHost.cs
Previously it would misleadingly show as "work" making is hard to discern which thread was bottlenecking.
> Mark time spent waiting for update thread as sleep time

- osu.Framework/osu.Framework.csproj
Replacing CoreCompat.System.Drawing with System.Drawing.Common. This helps resolving issues with native libraries on some Linux distributions. (Arch Linux for instance does not provide libpcre.so.3 which the CoreCompat.System.Drawing runtime apparently needs)
Natives for CoreCompat.System.Drawing are also only available for x86 (if I'm not mistaken).
> Switch from CoreCompare.System.Drawing to System.Drawing

- osu.Framework/Input/PassThroughInputManager.cs
Turns out that without this any `PassThroughInputMnager` is in an incorrect state until the mouse moves once.
Resolves ppy/osu#2754.
> Add HighFrequency interface back to PassThroughInputManager

- osu.Framework/Audio/Track/Waveform.cs
- osu.Framework/Graphics/Audio/WaveformGraph.cs
Possible thread race condition causing a nullref of the cancellation token (cross-thread access to private field)
> Fix failing async logic in WaveformGraph

- osu.Framework/Graphics/Containers/ScrollContainer.cs
This prevents most jittery behavior when "letting go" of a scroll flick and running the game at low frame rates.
> Apply a small degree of smoothing to precise scroll

- osu.Framework/Allocation/BufferStack.cs
Extracted from #1481. Makes user aware when a `BufferStack` is possibly not doing what they think it is.
> Add logging when a BufferStack exceeds its allocation allowance

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Statistics/FrameStatistics.cs
- osu.Framework/Threading/UpdateThread.cs
This also standardises the logic to assign colours, so we don't need to manually decide on them.
> Add input queue rebuild statistics to overlay

- osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
- osu.Framework.Tests/NonVisual/TestDecoupleableClock.cs
- osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs
Resolves #1633
Fixes #1634
Blocked awaiting osu!-side testing.
---
Fixes the state of decoupled clocks (used commonly for increasing precision beyond the audio driver's capabilities) lagging behind one frame.
> Fix state inconsistencies of DecoupleableInterpolatingFramedClock

- osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
These log events were too noisy and unimportant.
Closes ppy/osu#2864.
> Reduce log level for "Joystick Connected" messages

- osu.Framework.Tests/Visual/TestCaseMouseStates.cs
- osu.Framework/Input/InputManager.cs
- Resolves ppy/osu#2862.
TestCaseMouseStates is modified to add tests for this behavior.
---
The recent rework of InputManager overlooked drag-clicking logic for the case where the object being "dragged" didn't handle the drag. The objects expect to receive click events in this case, as per the previous functionality.
> Fix clicks not occurring if drag events weren't handled

- osu.Framework/Testing/DynamicClassCompiler.cs
- Resolves ppy/osu#2656
---
JetBrains [suggest](https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html#embedding-declarations-of-code-annotations-in-your-source-code) that you can embed annotations in code by using the JetBrains.Annotations namespace. This leads to issues where our code may try to reference internal types from other assemblies instead of JetBrains'.
EF Core does this, as discovered in [this comment](https://github.com/ppy/osu/issues/2656#issuecomment-397685950), leading to osu!-side issues, however this is potentially not limited to EF Core. As such, I'm applying a universal fix at a framework level.
> Embed JetBrains' annotations assembly during dynamic compilation

- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
ScrollDelta should be only read at OnScroll.
- Resolves ppy/osu#2872
Also, test cases of KeyBidings are added.
> Fix KeyBindingContainer incorrectly reading ScrollDelta

- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Platform/Linux/LinuxGameHost.cs
- osu.Framework/Platform/Linux/Native/Library.cs
Because libbass_fx does not specify libbass as a dependency, we need  to load libbass globally so that libbass_fx knows where to look for it. This patch also adds a way to load libraries with some of the flags of dlopen.
- Closes https://github.com/ppy/osu/issues/2852
---
Fix beatmaps not playing on linux.
> Add library loading and load libbass.so globally on linux

- osu.Framework.Tests/Visual/TestCaseCircularContainerSizing.cs
- osu.Framework/Graphics/Containers/CircularContainer.cs
- Closes ppy/osu#2578
PRing while testing in osu!.
This is a temporary fix, while ppy/osu-framework#1665 is a thing.
I removed the `Cached` here because we are guaranteed to have `DrawSize` validated here (`UpdateSubTreeMasking` has run), and thus this is not an expensive computation.
---
Fixes random squares appearing instead of circles for 1 frame in various areas.
> Compute CircularContainer's corner radius as late as possible

- osu.Framework/Graphics/UserInterface/TextBox.cs
Required for osu! to provide alternative exit sequences for textboxes.
---
> Expose the ability to kill focus of a textbox

- osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
This removes the only handling of the escape key outside of common UI controls (menus/textboxes). I feel this should be up to the developer to decide and implement locally.
In osu!, we allow key binding the "back" key and do not want the escape default to be handled in this way, which is why this change is being made.
---
Allows for applications to decide how they close focused overlays.
> Remove escape handling logic from FocusedOverlayContainer

- osu.Framework/Graphics/UserInterface/TextBox.cs
Add any details pertaining to developers above the break.
- Closes ppy/osu#2447
---
Fixes keys not always being blocked by text boxes, leading to unexpected UI actions.
> Decouple TextBox blocking behaviour from underlying text consumption

- osu.Framework.Tests/Visual/TestCaseInputQueueChange.cs
- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework.Tests/Visual/TestCaseMouseStates.cs
- osu.Framework.Tests/Visual/TestCaseNestedMenus.cs
- osu.Framework/Testing/Input/ManualInputManager.cs
- osu.Framework/Testing/ManualInputManagerTestCase.cs
- Cleanup ManualInputManager
- Add support for joystick button, precise scrolling and arbitrary `IInput`.
- ManualInputManagerTestCase
- Automatically initialize input state for each test case setup. This prevents a test fail when manually test using the test browser.
- Use this for existing tests.
- I noticed that osu.Game has ManualInputManagerTestCase after coded. This framework's version cannot replace that because the osu.Game version is an OsuTestCase and this is completely independent to that for now.
> Cleanup ManualInputManager and make a common base class for test cases which use ManualInputManager

- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework/Input/Bindings/IMouseWheelBindingHandler.cs
- osu.Framework/Input/Bindings/IScrollBindingHandler.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
Required for a solution of ppy/osu#2881.
Mouse wheel actions are actions which is bind to mouse wheel. The amount of scroll and whether it is a precise scrolling is informed. In this way we can bind opposite direction of wheel easily for example.
When this type of action is fired then it first searches for `IMouseWheelBindingHandler` and then searchs for usual IKeyBindingHandler.
Also, I made KeyCombination.FromInputState to receive scroll delta if any and essentially rewrote #1648 with a simpler solution.
> Make mouse wheel bind actions know amount of scroll

- osu.Framework/Platform/DesktopGameWindow.cs
- osu.Framework/Platform/GameWindow.cs
This will make it easier for consumers to implement DisplayDevice-related logic. Note that the main logic for this will be implemented in another PR (multi-monitor handling), this is just for compatibility (so that Toucan can update his PRs ASAP)
- breaks #1652 and ppy/osu#2715
---
Adds a method in preparation for fullscreen multi-monitor support.
> Add abstract GameWindow.GetCurrentDisplay() method

- osu.Framework/Platform/GameHost.cs
`UpdateFrame` is certainly called after the first `ProcessEvents` https://github.com/ppy/opentk/blob/21754ca665f1b6595c2ef0a02bd4e8ee6fe8dc99/src/OpenTK/GameWindow.cs#L368-L374.
- Closes #578
---
Fixes game not always being active on startup, even when window is.
> Delay first setActive call until event handlers are set up

- osu.Framework.Tests/Visual/TestCaseInputManager.cs
We can't have 0-size containers anchored to the sides of the screen (or a parenting container). This was causing the flow container to move between `IsMaskedAway = true` and `IsMaskedAway = false` while resizing the window.
---
> Fix flashing in test case

- osu.Framework/Logging/Logger.cs
- osu.Framework/Platform/GameHost.cs
Fixes logs not having a version if not explicitly specified by the game.
> Populate Logger's version with assembly version information by default

- osu.Framework/Platform/GameWindow.cs
These are already initialised in GLWrapper, which is where they should be since GLWrapper is the class through which we pass, e.g. scissor and depth test from other classes.
---
> Remove duplicate OpenGL initialisation

- osu.Framework.Tests/Visual/TestCaseInputManager.cs
- osu.Framework.Tests/Visual/TestCasePassThroughInputManager.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/ButtonInput.cs
- osu.Framework/Input/ButtonStates.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/JoystickButtonInput.cs
- osu.Framework/Input/KeyboardKeyInput.cs
- osu.Framework/Input/MouseButtonInput.cs
- osu.Framework/Input/PassThroughInputManager.cs
When `UseParentInput` is true, a `PassThroughInputManager` syncs its keyboard and joystick state to parent `InputManager`'s state.
For mouse buttons, only input that reached event handlers (`OnMouseDown` and `OnMouseUp`) are applied. Click initiated at outside of the `PassThroughInputManager` and blocked inputs are not synced. However, always sync `MouseUp` to maintain an invariant (for a mouse button) `this.pressed <= parent.pressed`. This is because a mouse inputs are positional and this behavior is matching to regular `Drawable`s.
- Closes #1672 
- When `KeyBindingContainer` handles `OnKeyDown` before `KeyBindings` are set there was a null reference. I fixed this. However, the new `KeyBindingContainer` doesn't fire actions that is bind to keys pressed while the new …
> Make PassThroughInputManager sync with parent input state

- osu.Framework/Input/MouseButtonEventManager.cs
- Intersection was done backwards in a few placing, causing incorrect ordering.
- MouseUp now always invokes on all drawables in the mouse down queue, regardless of `IsAlive`/`IsPresent` states.
---
> Fix incorrect intersection logic

- osu.Framework/Game.cs
- osu.Framework/Graphics/Drawable.cs
I don't think this is something we should be allowing. In the case a derived class needs to override something accessed directly in the thing it is overriding, the base should probably be modified to be aware of this. Or there should be more abstraction between components.
In standard DI this is not allowed; it's only possible here due to the order of calling.
> Don't inject local dependencies on self

- osu.Framework/Graphics/Visualisation/TitleBar.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
- osu.Framework/Graphics/Visualisation/TreeContainerStatus.cs
It was manually checking positional conditions in `OnDragStart`, at which point the mouse may be outside the draggable region (but should still be considered a drag).
---
> Fix draw visualiser title bar ignoring drags in some cases

- osu.Framework.Tests/Visual/TestCaseFocus.cs
- osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
- osu.Framework/Input/InputManager.cs
- Closes ppy/osu#2989.
`AcceptsFocus` was still true even when overlay was hidden. this means that any overlay with a fade animation would keep focus when it shouldn't.
---
> Fix focus overlay focus

- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- Fixes empty tooltips from being `Show`n when actually unnecessary.
- Closes ppy/osu#3003 (also supersedes and closes ppy/osu#3016).
TooltipContainer needs some serious reafactoring (see `Update` / `UpdateAfterChildren` mess), but I'm leaving this for another day.
---
> Fix empty tooltips being shown incorrectly

- appveyor.yml
Due to multiple http failures recently, this is better to have turned on as a fallback.
---
> Turn cache back on for chocolatey packages

- osu.Framework/Graphics/UserInterface/TextBox.cs
- Removed per-character gradient. This looked bad if many characters were typed quickly. To ensure characters don't appear in front of the caret, they fade using double the duration.
- Read existing character colour rather than forcing white. Allows consumers to change character colour, where it was previously not possible.
- No longer applies fades when the source of a text change was programmatic (ie. via `Textbox.Text`). Closes #1711.
> Fix multiple issues surrounding textbox per-character fades

- osu.Framework/IO/Stores/GlyphStore.cs
Fixes an issue where requesting fonts be precached was making a reference to the `Font` property, which attempted to wait on its own task.
We do not currently precache fonts by default, so this has gone unnoticed since its inception.
Not really sure how to unit test this one, since loading fonts is part of the visual test bootstrap.
---
> Fixes font precache freezing

- osu.Framework.Tests/Visual/TestCaseIsMaskedAway.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/ContainerExtensions.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/IO/File/FileSafety.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseState.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework/Input/UserInputManager.cs
- osu.Framework/Platform/GameWindow.cs
- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
With .NET core 2.1+ this is as efficient as the ugly code we've been using. Skipping usage with invalidation logic since there's many cases we care about *any* of combined flags values matching (making it easy to get the usage pattern wrong).
---
> Use Enum.HasFlag

- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
Small helper method to simplify cases like:
```
CreateChildDependencies:
existing = dependencies.Get<T>();
if (existing != null)
existing = ...
```
Which now becomes:
```
CreateChildDependencies:
if (!dependencies.TryGet<T>(out existing))
existing = ...
```
---
> Add TryGet<T>() extension to dependency containers

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Holding ctrl will expand. Holding shift will pause. Allows for viewing expanded statistics without pausing data collection (useful in many cases).
> Allow frame statistics to expand without pausing

- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
- osu.Framework/Platform/MacOS/Native/Cocoa.cs
Fixes an issue where the macOS cursor would reappear on focus switch.
Delay is required to ensure the cursor rects are invalidated while the window has the focus, otherwise the cursor will not disappear until the user moves the mouse.
Resolves #1703
> Fix macOS cursor reappearing on focus lost

- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Input/PlatformActionContainer.cs
Refactors the `SimultaneousBindingMode.NoneExact` into a separate enum, and provides support for only performing exact matches on modifier keys.
Allows `PlatformAction`s to be correctly recognised even if there are additional keypresses, as long as the required modifier keys match exactly.
Resolves #1702
> Allow KeyCombinations to handle exact matches only on modifier keys

- osu.Framework.Tests/Visual/TestCaseJoystick.cs
- osu.Framework/Input/Bindings/InputKey.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
- osu.Framework/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs
- osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
- osu.Framework/Input/InputManager.cs
- Made `InputManager` to not ignore inputs from disabled input handlers.
When an input handler is disabled, this disable produces release input of buttons and these input should be handled.
- Also fixed JoystickButton.FirstButton was not correctly used.
- Required for the correct function of ppy/osu#3022.
> Fix joystick input not working when first disabled then enabled

- appveyor.yml
Via peppy/CodeFileSanity#4, CFS is now being published to the appveyor nuget source as a dotnet CLI tool.
> Use .NET Core CodeFileSanity

- osu.Framework.Tests/Visual/TestCaseTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
Adds the ability to remove all items from a `TabControl`.
Will be used in a future PR to dynamically replace the contents of the `SectionsContainer` used in the `UserProfileOverlay`.
> TabControl.RemoveAllItems

- osu.Framework.Tests/Visual/TestCaseFullscreen.cs
- osu.Framework/Platform/DesktopGameWindow.cs
- osu.Framework/osu.Framework.csproj
`changeResolution` now takes a `display` parameter that specifies the display of which the resolution should be changed. 
Other than that, the window now tracks the last display that went into fullscreen: If you move the window to another monitor while being fullscreen (Win-Shift-Arrow Key on Windows), it should still restore resolution for the monitor that originally went fullscreen (since its resolution is still changed).
I also removed `Position = Vector2.Zero` in the borderless logic, because it's A) unnecessary (at least on Windows, needs testing) and B) always moves the borderless window to the same place, which is usually the first monitor.
---
Adds multi-monitor support for custom fullscreen resolutions.
> Add multi-monitor support for custom fullscreen resolutions

- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
Just a small QOL improvement, removes the parentheses showing up when autocompleting BDL in some IDEs (Rider).
From: https://streamable.com/q325w
To: https://streamable.com/hmptm
> Add default constructor for BackgroundDependencyLoader

- osu.Framework/Graphics/UserInterface/SliderBar.cs
Caused null ref exceptions in implementations using custom `UpdateValue` logic.
> Fix SliderBar binding to events too early

- osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Platform/GameHost.cs
Disallows the case of something like:
```
class Base:
[Cached]
object myObject
class Sub : Base:
[Cached]
object myObject2
```
Because it's hard to determine exactly which object a resolver will receive with the way dependency container currently works.
Exception output changes e.g.:
```
Unhandled Exception: osu.Framework.Allocation.DependencyInjectionException: Exception of type 'osu.Framework.Allocation.DependencyInjectionException' was thrown.
at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_1.<CreateActivator>b__4(Object target, DependencyContainer dc) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs:line 62
at osu.Framework.Allocation.DependencyActivator.<>c__DisplayClass8_0.<activate>b__0(InjectD …
```
> Disallow doubly-caching objects as dependencies

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
Should hopefully fix web requests hogging `ThreadPool` threads during IO.
> Move WebRequest to using pure async logic

- osu.Framework/Testing/Drawables/Steps/StepButton.cs
From:
```
[runtime:important] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> osu.Framework.Allocation.DependencyInjectionException: Exception of type 'osu.Framework.Allocation.DependencyInjectionException' was thrown.
at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_1.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs:line 73
at osu.Framework.Allocation.DependencyActivator.<>c__DisplayClass8_0.<activate>b__0(InjectDependencyDelegate a) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Allocation/DependencyActivator.cs:line 73
at …
```
> Fix incorrect DI error being reported by StepButton failures

- osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
- osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
- osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
- osu.Framework/Allocation/CachedAttribute.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
- osu.Framework/Allocation/ResolvedAttribute.cs
- osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
- osu.Framework/Testing/Dependencies/CachedNullableProvider.cs
- osu.Framework/Testing/Dependencies/CachedStructProvider.cs
```diff
+ internal void CacheValue<T>(T instance)
+ internal void CacheValueAs<T>(T instance)
```
```diff
+ internal static T GetValue<T>(this IReadOnlyDependencyContainer container)
```
Functionality is also provided through `[Cached]`, with the same soft limitation that only framework types can define this on structs. If another assembly tries to use `[Cached]` on structs, an `ArgumentException` will be thrown (as it already was).
Replaces the eventual implementation in https://github.com/peppy/osu-framework/tree/cancellation-drawables .
> Allow framework types to cache structs as dependencies

- osu.Framework/Platform/GameHost.cs
- osu.Framework/Threading/GameThread.cs
It looks like:
1. Assertion exceptions cannot be left unhandled. They seem to be handled by the parenting process if this is the case - crashing the test runner.
2. Assertions shouldn't be thrown on non-main threads. Related to (1) because they don't crash the main nunit thread.
Instead, this change handles assertion exceptions and then forwards them to the correct thread (InputThread).
From:
To:
> Fix assertions breaking rider/cli outputs

- osu.Framework/Graphics/Shaders/ShaderManager.cs
Using tuples still has an overhead, but it's much more tame than performing string operations. A further improvement would see adding a double-level cache lookup or hashing the FS/VS portions without requiring a tuple, but this reduces overheads by well over 50% as is.
> Reduce overhead of shader lookup caused by string concatenation

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
When the frame time display is not visible, collections are still being infinitely cycled though the queue. This stops that from happening (there's no point in storing these frames when they are not being used).
> Reduce allocations by ConcurrentQueue when collecting perf data

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
- osu.Framework/Timing/FramedClock.cs
- osu.Framework/Timing/ThrottledFrameClock.cs
When doing performance testing, it is very hard to objectively use FPS as a gauge for whether you've made improvements due to rule of demising returns.
This exposes the frame times for each thread along with the thread's current target refresh rate. Note that these times do *not* include time spent sleeping, so they should be useful across all frame limiter modes.
> Display frame times in addition to FPS

- osu.Framework/Input/InputManager.cs
Reduces memory allocation greatly. Further gains are still to be had in locations like `CursorEffectContainer.findTargetChildren`
> Remove usage of linq to handle unhovering

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
Cancellation token only needs to be cached in `CompositeDrawable`.
> Reduce cancellation token overhead

- osu.Framework.Tests/Visual/TestCaseSizing.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
There are multiple cases where this would break. One such case is that `BypassAutosizeAxes` is changed to `Axes.Both` post-construction, which wouldn't cause an invalidation due to this.
Similar things could happen when adding/removing drawables, changing scale, etc... The code was super wrong.
I've left the parameter in for now to preserve the API.
Have also tested mania and it _seems_ to be okay, which is what https://github.com/ppy/osu/pull/2564 / https://github.com/ppy/osu-framework/pull/1554 was addressing.
> Remove completely incorrect BypassAutoSize optimisation

- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
`SpriteText` currently has a pretty huge overhead. Due to the longer display format now, this actually eats in to frame time considerably.
This aims to reduce that so we can continue comparing performance using the minimal frame time display.
> Limit rate of frame time display updates to reduce overhead

- osu.Framework.Tests/Visual/TestCaseFillModes.cs
- osu.Framework.Tests/Visual/TestCaseFitInsideFlow.cs
- osu.Framework/Testing/TestCase.cs
Also fixes a `TestCase` which abused this (and never worked correctly as a result).
> Disallow TestCases to add/remove from InternalChildren

- osu.Framework/Testing/TestBrowser.cs
Until now only `[Test]` methods would appear. This adds support for `[TestCase(args)]` cases too.
> Add support for TestCase execution in visual tests

- osu.Framework/Testing/TestCase.cs
It was previous the case that exceptions on the input thread may not correctly fail a test, as they were only encountered in `OneTimeTearDown` (too late).
Cannot add a test case for this, but has been tested locally.
> Fix nunit not correctly catching input thread exceptions

- osu.Framework.Tests/Visual/TestCaseLayoutDurations.cs
- osu.Framework.Tests/Visual/TestCaseLayoutIdempotence.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
Don't apply layout transform when there is a same transformation already.
- Fixes #1804 (no.2 issue only. no.1 issue is a separate issue).
---
> Fix non-zero AutoSizeDuration causing a potentially incorrect transformation

- osu-framework.sln.DotSettings
- osu.Framework.Tests/Bindables/BindableBindingTest.cs
- osu.Framework/Graphics/Drawable.cs
We have too many places where we're doing stuff like
```
override Dispose()
myBindable.UnbindAll()
```
This is starting to become problematic, with cases like visual settings needing to unbind 5 of them. This does it automatically inside `Drawable.dispose()`.
> Auto-unbind all bindables in drawables when disposed

- osu.Framework/Testing/TestBrowser.cs
Triggers the `ClearInternal()` exception, not sure why we were clearing in the first place - code is 2+ years old.
> Fix TestBrowser crashing when changing testcases

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
Also fixes a Padding invalidation issue.
I found the issue by random test quick check #1800  and I made the changes so the test passes.
`BypassAutoSizeAxes` is a bit awkward due to its asymmetry between getter and setter.
---
> Fix layout invalidation issues related to BypassAutoSizeAxes

- osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
- osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
- osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Platform/GameHost.cs
We removed this because the `CancellationToken` could've been set multiple times when this code was entirely in `Drawable`. But we've since moved away from that.
> Fix LoadAsync ContinueWith not being cancelled

- osu.Framework.Tests/Visual/TestCaseFocus.cs
- osu.Framework/Input/InputManager.cs
It was pointed out that `.Append` doesn't modify the collection and has no effect (wrong code).
This PR fixes this. `KeyDown` event is now correctly prioritized for a focused drawable. For other events such as `KeyUp`, there was a separate code to do this but there was a bug which called `OnKeyUp` two times for an event for a focused drawable.
---
> Correctly prioritize focused drawable for input propagation

- osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
- osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
- osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
- osu.Framework/Allocation/DependencyActivator.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
- osu.Framework/Allocation/ResolvedAttribute.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/IO/Stores/CachedResourceStore.cs
- osu.Framework/Platform/GameHost.cs
I think the description for this will be subject of a long blog post. A general summary of findings are in #1828.
There are likely some exception handling methods left behind which can now be removed or simplified. There are also some test cases which need to be tidied that still contain BDL async methods (while not harmful should probably be reverted).
> Restore pre-async BDL/activator logic

- osu.Framework.Tests/Visual/TestCaseSizing.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/Drawable.cs
Fixes https://github.com/ppy/osu-framework/pull/1816
`Parent` already performs an `Invalidate()` upon being set, but wouldn't do anything because `Drawable`s aren't usually not loaded by that point.
> Fix parent setter's invalidation never occurring

- osu.Framework/Graphics/Drawable.cs
Apparently the root inputmanager requires invalidations to compute its size. Whoo'da thunk it?
I considered this fix previously, still fixes the original issue (parent invalidations weren't happening).
> Don't block all invalidation when parent is null

- osu.Framework.Tests/Visual/TestCaseEffects.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
Prereqs:
~- [ ] https://github.com/ppy/osu-framework/pull/1836~
In cases where we used fullscreen dims (e.g. osu! focused overlays), spritetext would recompute layout due to the way colour invalidations worked.
> Don't recompute spritetext layout on colour invalidation

- osu.Framework/Input/MouseButtonEventManager.cs
While this wasn't a leak as such, it does mean that whatever was in the positionalInputQueue at last MouseDown was retained for longer than necessary.
> Reduce memory retention by MouseButtonEventManager

- osu.Framework/Game.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/Textures/TextureAtlas.cs
- osu.Framework/Graphics/Textures/TextureLoader.cs
- osu.Framework/Graphics/Textures/TextureStore.cs
- osu.Framework/IO/Stores/FontStore.cs
Reduces overall object count, as `TextureStore`s now cache the Texture objects rather than TextureGLs.
> Have atlases return GL textures, not Textures

- osu.Framework.Tests/Visual/TestCaseProxyDrawables.cs
- osu.Framework/Graphics/Drawable.cs
We were placing a huge stress on the GC previously, with tens of thousands of drawables being finalised. There's no reason not to dispose eargerly.
Note that most of these were SpriteText characters, which will likely be fixed in the near future, but still a worthwhile optimisation.
> Dispose drawables aggressively

- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
For mipmap level selection to work the sampling must happen
consistently through the shader, so sample the texture first
and then use it where necessary.
- closes ppy/osu#3118
- closes (potentially) ppy/osu#3215
> Fix texture sampling issue on Intel/Linux

- osu.Framework/Graphics/Sprites/SpriteText.cs
Might as well do this to ease up on the update thread, if the textures aren't already in the cache.
> Precache character textures during SpriteText's BDL load

- osu.Framework/Graphics/Sprites/SpriteText.cs
Unsure if padding should be ignored on zero-width or not.
> Fix SpriteTexts with only spaces not getting a width

- osu.Framework/Graphics/Audio/WaveformGraph.cs
- osu.Framework/Graphics/Colour/ColourInfo.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/DrawColourInfo.cs
- osu.Framework/Graphics/DrawInfo.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Lines/PathDrawNode.cs
- osu.Framework/Graphics/Shapes/Triangle.cs
- osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
- Creates a new invalidation value (`Invalidation.Presence`).
- `Scale`, `Alpha`, and `AlwaysPresent` trigger this, if the IsPresent state changes.
- Propagates upwards only.
- `Invalidation.Colour` propagates downwards only.
- Flow containers/other components that would handle colour invalidations for presence, now handle `Invalidation.Presence` instead.
Accepting suggestions for what to call `DrawColourInfo`...
I go up from 30 -> 55 FPS on the following stresstest:
```
public class TestCaseScratch : TestCase
{
[BackgroundDependencyLoader]
private void load()
{
var topContainer = new Container { Size = new Vector2(10) };
var currentContainer = topContainer;
for (int i = 0; i < 50; i++)
{
var newContainer = new Container { RelativeSizeAxes = Axes.Both };
for (int j = 0; j < 200; j++) …
```
> Separate out colour and presence invalidations

- osu.Framework.Tests/Visual/TestCaseRefCountTexture.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/Sprites/Sprite.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/Textures/TextureWithRefCount.cs
With the previous implementation, it was possible that the following scenario occurred, causing double dereferencing:
- A Sprite with a Texture is ready for finalizing
- The texture gets finalized first, calling Dispose(false).
- The sprite then gets finalized, calling Texture.Dispose(true).
> Move reference count exception from Dispose

- osu.Framework/Graphics/Drawable.cs
We use the scheduler as a guard against running operations after disposal (ie. web request callbacks) and always assume it is non-null (even after disposal). This breaks that assumption.
> Don't set scheduler to null on disposal

- osu-framework.sln.DotSettings
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Lists/SortedList.cs
```
Method |     Mean |     Error |    StdDev |    Gen 0 | Allocated |
------------------- |---------:|----------:|----------:|---------:|----------:|
NoCustomEnumerator | 67.27 ms | 0.3430 ms | 0.3209 ms | 125.0000 |  400000 B |
CustomEnumerator | 11.46 ms | 0.0927 ms | 0.0774 ms |        - |       0 B |
```
```
[MemoryDiagnoser]
public class Bench
{
private SortedList<int> sortedList = new SortedList<int>();
private SortedListCustomEnumerator<int> sortedListCustomEnumerator = new SortedListCustomEnumerator<int>();
[GlobalSetup]
public void Setup()
{
for (int i = 0; i < 1000; i++)
{
sortedList.Add(i);
sortedListCustomEnumerator.Add(i);
}
}
[Benchmark]
public void NoCustomEnumerator()
{
int finalValue = 0;
for (int i = 0; i < 10000; i++)
{
foreach (var val in sortedList)
finalValue += …
```
> Implement a custom SortedList enumerator to reduce allocations

- osu.Framework/Allocation/ValueInvokeOnDisposal.cs
- osu.Framework/Graphics/Batches/VertexBatch.cs
- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/Shaders/UniformMapping.cs
1. `BufferedContainerDrawNode` now spends most of its time binding render buffers, which can be improved further, but is a larger change.
2. Edge effect draw time has been almost halved - probably also a decent representation for masking in general.
> Reduce allocations/performance overhead of draw nodes

- osu.Framework/Graphics/Batches/VertexBatch.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
Eventually bottlenecks draw thread performance over long executions with many BufferedContainers being constructed.
> Fix references to VBOs causing disposal to never occur

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Screens/Screen.cs
Without this, long blocks can occur on the update thread when a large draw hierarchy is disposed. I believe this is better than relying on the finalizer still.
Fixes performance regression from #1849.
> Run aggressive disposal of drawables asynchronously

- osu.Framework/Threading/Scheduler.cs
Used in osu! to make drawables present only when they have pending scheduled events.
> Expose whether a scheduler has pending events

- osu.Framework/Graphics/Textures/LargeTextureStore.cs
Until we decide on the correct path forward for mipmapping, I believe this is a better default for LargeTextureStores. It will result in lower quality texture display when scaled below 1.0, but avoid large stutters due to CPU-based mipmap generation occurring on the draw thread.
> Disable mipmap generation for LargeTextureStore

- osu.Framework/Graphics/Containers/CompositeDrawNode.cs
As determined previously, iterating by index in hot paths can be beneficial in terms of performance with minimal overhead. Just squeezing out as much as we can.
> Iterate by index in CompositeDrawNode for increased performance

- osu.Framework.Tests/Visual/TestCaseTextures.cs
- osu.Framework/Graphics/Audio/WaveformGraph.cs
- osu.Framework/Graphics/Lines/PathDrawNode.cs
- osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/Textures/TextureStore.cs
- osu.Framework/Graphics/Textures/TextureWithRefCount.cs
- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
With these changes, `DrawNode` implementations must check `Texture?.Available == true` rather than `Texture?.TextureGL?.IsDisposed != false`.
Because `TextureWithRefCount` throws an exception when accessing `TextureGL`.
> Fix disposal checks throwing exceptions in drawnodes

- osu.Framework/Graphics/Containers/Container.cs
Was about to iterate over a container in `Update()` then I realized this would be problematic:
```
Method |     Mean |    Error |   StdDev |    Gen 0 | Allocated |
-------------   |---------:|---------:|---------:|---------:|----------:|
NoEnumerator   | 326.4 us | 4.631 us | 4.106 us | 101.5625 |  312.5 KB |
WithEnumerator | 177.8 us | 3.483 us | 4.146 us |        0 |       0 B |
```
There is a duplication of the enumerator with `SortedList<T>`, BUT baking it into `Container<T>` yields a ~25% (220us -> 170us) performance improvement, over extracting it out into a common generic struct.
Along with this, we should iterate over a container rather than its `Children`. E.g. `SectionsContainer.UpdateAfterChildren()` iterates over `Children`, which is an interface and will box the enumerator.
> Reduce allocations when iterating over children of a container

- osu.Framework.Tests/Visual/TestCaseMouseStates.cs
- osu.Framework/Input/MouseButtonEventManager.cs
Double click event should fire on second mouse down, not mouse up.
- Fix #1827
---
Fix double click drag not working.
> Fix double click behavior regression

- osu.Framework/Graphics/Drawable.cs
`TriggerOnXXX` is now removed by #1713 but triggering a left click is most used and most useful to have an own method. Will be used for osu! framework update PR.
---
> Add Drawable.Click method

- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
These are wrong on retina displays, and as far as I can see there's no way to get the "dpi" from DisplayResolution...
> Don't return any resolutions for macOS

- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
Due to a quirk in how reflection retrieval of members happens, inherited public members are included but inherited _private_ members are not.
> Retrieve all inherited members for property display

- osu.Framework.Tests/Visual/TestCaseConcurrentLoad.cs
- osu.Framework.Tests/Visual/TestCaseDelayedLoad.cs
- osu.Framework.Tests/Visual/TestCaseDelayedUnload.cs
- osu.Framework.Tests/Visual/TestCaseFocus.cs
- osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
- osu.Framework.Tests/Visual/TestCasePathInput.cs
- osu.Framework.Tests/Visual/TestCaseTooltip.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Containers/VisibilityContainer.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/LogOverlay.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseButtonEventManager.cs
- osu.Framework/Input/PassThroughInputManager.cs
- osu.Framework/Screens/Screen.cs
- osu.Framework/Statistics/FrameStatistics.cs
- osu.Framework/Threading/UpdateThread.cs
There are couple of naming pairs such as `handleKeyboardInput`/`handleMouseInput` or `BuildKeyboardInputQueue`/`BuildMouseInputQueue`.
This is bad because "Keyboard" means not only keyboard but anything except mouse.
I propose to rename this things.
---
> Rename Keyboard/Mouse to NonPositional/Positional

- osu.Framework.Tests/Visual/TestCaseMasking.cs
- osu.Framework/Graphics/Containers/CompositeDrawNode.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/Shaders/GlobalProperty.cs
- osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
The hollow region should not be offset, but was before. Here is a comparison of before and after.
- Closes #1936
---
Fixes incorrect behavior of hollow edge effects with an offset. The following images show before and after:
> Fix incorrect behavior of hollow offset edge effects

- osu.Framework/Input/Events/UIEvent.cs
- osu.Framework/Input/States/KeyboardState.cs
I moved modifier key getters from `KeyboardState` to `UIEvent` on #1922 but during osu side update of that PR I found there are couple of uses of modifier keys getters without access of `UIEvent`. This PR restores modifier key getters to avoid code duplication (checking both left and right key).
---
> Restore modifier key getters of KeyboardState

- osu.Framework/IO/File/FileSafety.cs
- Required for ppy/osu#3558
---
This change fixes `FileSafety.PathStandardise(string)`, which would not change Window path separators on Unix machines.
> Fix FileSafety.PathStandardise only working on Windows

- osu.Framework.Tests/Visual/TestCaseDrawablePath.cs
- osu.Framework.Tests/Visual/TestCaseInputResampler.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/Lines/SmoothPath.cs
- osu.Framework/Graphics/Lines/TexturedPath.cs
* `Path` no longer exposes its `Texture` publicly.
* Migration: Use `TexturedPath`.
* `SmoothPath` adds the AA capabilities of `SliderBody`
* `Path` exists by itself to either provide non-aa'd paths, or have subclasses provide the texture.
> Implement SmoothPath which provides antialiasing capabilities

- osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
- osu.Framework/Allocation/ResolvedAttribute.cs
Currently if a bindable is `[Resolved]`, it'll copy the original bindable, which is unsafe and against the expected flow of bindables.
With this, the `[Resolved]` bindable becomes a bound copy of the original.
> Add special case for resolving bindables

- osu.Framework.Tests/Bindables/BindableDoubleTest.cs
- osu.Framework/Configuration/BindableNumber.cs
resolves #1976 
Also, if we need to propagate precision/max/min to `Bindable<T>` objects, it can be achieved with Proxy and Decorator patterns.
> Fix propagation to bindings

- osu.Framework/Graphics/Shaders/ShaderPart.cs
Add included shader files inline rather than as additional shadercode entries.
Fixes an issue in OpenGL ES where the header was getting compiled before the float precision was set.
Also changed line splitting to ensure that a newline will appear at the end of the script rather than the start.
> Concatenate Shader Includes

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Not sure on the naming for such a method...
> Fix checkChildLife allocating anonymous delegates unnecessarily

- osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
THe previous method could cause accidental use of `Cache` when the consumer is meaning to use `CacheAs`.
ie.
```
Type obj = new Type();
deps.Cache(obj);        // caches as Type
deps.Cache<IType>(obj); // still caches as Type
deps.CacheAs<IType>(obj); // caches as IType
```
> Remove generics from Cache method

- osu.Framework/Audio/Track/Waveform.cs
Make filtering of waveform more mathematically sound. The waveform now looks significantly smoother at lower resolutions and flickers much less when zooming in and out.
This was achieved by making the filter kernel gaussian and adjusting its shape to fit the Nyquist frequency (i.e. twice the sampling frequency) of the signal to be filtered.
---
The waveform now looks significantly smoother at lower resolutions and flickers much less when zooming in and out.
> Improve filtering of waveform

- Directory.Build.props
- osu.Framework/osu.Framework.csproj
- See https://github.com/dotnet/sourcelink/issues/155
---
Workaround to fix build errors like this on mono:
```
error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
error MSB4018: System.BadImageFormatException: Method has no body
error MSB4018: File name: 'LibGit2Sharp'
```
> Disable sourcelink on mono

- osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
- osu.Framework/Screens/Screen.cs
It's pretty safe to just noop in this case.
> Fix MakeCurrent throwing an error when no child is present

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
- osu.Framework/IO/Stores/FontStore.cs
- osu.Framework/Logging/Logger.cs
- osu.Framework/Logging/RollingTime.cs
- Limits console debug log output to 50 messages over 10 seconds.
- Removed debug log target (was confusing; use `LogLevel.Debug` instead).
This can mainly be seen as a performance fix. Outputting to an IDE's console can add a very noticeable (blocking) overhead to execution.
> Rate limit console log output

- osu.Framework.Tests/Bindables/BindableBindingTest.cs
- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableCollection.cs
- osu.Framework/Configuration/IBindable.cs
- osu.Framework/Configuration/IUnbindable.cs
Allows the following sort of usage:
```
var bindable1 = new Bindable<int>();
var bindable2 = new Bindable<int>();
var bindable3 = new Bindable<int>();
bindable2.BindTo(bindable1)
bindable3.BindTo(bindable1)
bindable1.UnbindFrom(bindable2)
bindable1.Value = 5;
// bindable1.Value == 5
// bindable2.Value == 0
// bindable3.Value == 5
```
> Add UnbindFrom method to bindables

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
As we found out recently, CoreCLR exception handling takes some 60-120ms per exception with a debugger attached (depending on OS). This is likely due to having to wait for the debugger to respond to the event for breakpoints.
Presumably this is also at least partly the cause of object inspection being super slow in with execution paused.
> Improve PropertyDisplay performance with debugger attached

- osu.Framework.Tests/Bindables/BindableSerializationTest.cs
It's something that requires custom parsing logic that I wasn't sure if I implemented correctly, but is supported.
> Add serialisation test for population of bindable

- osu.Framework/IO/Network/WebRequest.cs
Can lead to pointless aggregate exceptions when trying to deserialize null strings, for instance.
> Don't process web request responses on timeout

- osu.Framework/Platform/Windows/Native/Icon.cs
- osu.Framework/Platform/Windows/Native/IconGroup.cs
- osu.Framework/Platform/Windows/WindowsGameWindow.cs
Cut down version of `System.Drawing.Icon` to remove dependency on the aforementioned class.  Required for Xamarin projects to correctly link, since `System.Drawing.Icon` and similar classes are not available.  We currently only use the `Icon` class to load in a .ico from a `Stream` and create an `HICON`, all of which can be done manually with PInvoke.
---
Removes dependency on `System.Drawing.Icon` for Xamarin compatibility.
> Reimplement System.Drawing.Icon

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Since components are not meant to display anything.
This was causing the IdleTracker to always be selected in osu!.
> Ignore components during drawvis search

- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- osu.Framework/Testing/TestBrowser.cs
The resulting testcase of a dynamic compilation has `UpdateSubTree` exceptions caught and subsequently removes the testcase from the hierarchy.
Due to recent changes in `DelayedLoadWrapper`, the testcase would be re-loaded in the next frame, throwing the same errors again.
> Fix testbrowser continuously throwing exceptions

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
- osu.Framework/IO/Stores/OnlineStore.cs
Until now, this was only allowed in debug mode. Which meant you'd have to compile your own osu-framework.
> Allow insecure web requests via setting

- README.md
Related to #2009 
Although it seems that only SampleGame and osu.Framework.Tests need .NET Core 2.2.
> Update README about SDK version

- osu.Framework/Platform/GameHost.cs
Allows `Exit` to be no-opped by host implementations (useful for mobile platforms).
The public `Exit` was made virtual rather than the private `exit` implementation, to prevent the game from becoming stuck in a `Stopping` state if `Exit` is called.
> Make GameHost.Exit virtual

- osu.Framework.Tests/Visual/TestCaseTextures.cs
- osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework.iOS/osu.Framework.iOS.csproj
- osu.Framework/Game.cs
- osu.Framework/Graphics/Textures/TextureLoaderStore.cs
- osu.Framework/Platform/GameHost.cs
Alternative to #2037 which avoids using a static loader class.
Untested (still can't compile xamarin on this PC).
> Use UIImage for iOS image loading

- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableCollection.cs
- osu.Framework/Lists/IWeakList.cs
- osu.Framework/Lists/LockedWeakList.cs
- osu.Framework/Lists/WeakList.cs
Resolves https://github.com/ppy/osu-framework/issues/2047
1. I didn't want to make `WeakList<T>` thread-safe, since it's currently used in GLWrapper where performance is a must.
2. Putting the locking inside `Bindable<T>` looked like a mess, it'd have to be locked at derived levels too (e.g. `BindableNumber<T>`). On top of that the code would be duped to `BindableCollection<T>`.
3. `LockedWeakList<T>` is my alternative, so that it's explicitly known that the list is locked.
`IWeakList` is a very slim implementation because the full functionality of `IList` is not used/needed anywhere in current use cases.
> Make bindable bindings thread-safe

- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Until now, we were using OnLoadComplete, which is problematic to say the least (((it's acutally 100% wrong))).
> Expose DelayedLoadComplete in DelayedLoadWrapper

- osu.Framework/Configuration/Bindable.cs
| Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
| ----------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
| Before           | 217.9 us |  2.234 us |  1.866 us |    152.3438 |           - |           - |           468.75 KB |
| After            | 69.00 us | 0.6921 us | 0.6135 us |           - |           - |           - |                   - |
Testing by calling `bindable.Value = x` 10000 times, with a different value of `x` every time.
> De-virtualize equality comparer

- osu.Framework.iOS/Audio/IOSTrackManager.cs
- osu.Framework.iOS/Audio/IOSWaveform.cs
- osu.Framework/Audio/Track/TrackBass.cs
- osu.Framework/Audio/Track/TrackManager.cs
- osu.Framework/Audio/Track/Waveform.cs
Changes `Waveform` to use JIT workarounds similar to `TrackBass`.
Note: Will require some minor changes in osu!, can't really make a PR for them until osu! is at least up to date with other recent framework changes.
---
Fix JIT errors creating Waveforms, which would cause the osu! editor to immediately crash on iOS.
> Fix JIT errors on iOS in Waveform

- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableNumber.cs
- osu.Framework/Configuration/IBindable.cs
- osu.Framework/Configuration/IBindableNumber.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
New `BindableNumber<T>` methods:
```diff
+ BindableNumber<T> GetBoundCopy()
+ BindableNumber<T> GetUnboundCopy()
```
`BindableNumber<T>` now implements `IBindableNumber<T>` providing similar functionality to `IBindable<T>`.
`IBindable<T>` now implements `IBindable`.
> Implement IBindableNumber<T> and more BindableNumber<T> methods

- osu.Framework/Configuration/BindableList.cs
BinarySearch method in lists can be useful when the consumer wants to add items in order.
> Add BinarySearch in BindableList<T>

- osu.Framework/Testing/TestCaseTestRunner.cs
Would incorrectly re-capture the exception.
> Fix nunit DI errors not propagating correctly

- osu.Framework.Tests/Visual/TestCaseBindingContainer.cs
- osu.Framework/Graphics/Containers/BindingContainer.cs
Prereqs:
It's becoming more common for us to have:
1. Giant stacks of bindables in a model class.
2. A super custom way of handling binding + re-binding to the model's bindables.
This provides a way to perform the functions of the `MyCachingComponent` mentioned in #2079 automatically, so bindables don't:
1. Need to be passed down and bound manually.
2. Create a helper class to handle binding + re-biding as https://github.com/ppy/osu/blob/master/osu.Game/Screens/Multi/RoomBindings.cs does.
> Implement a container to automatically cache values from models

- osu.Framework/osu.Framework.csproj
This reenables the sourcelink support by fixing the condition on the itemgroup that enables the sourcelink functionality.
if the value of EnableSourceLink is `true` then:
`'$(EnableSourceLink)' == 'true'` evaluates to `'true' = 'true'` evaluates to `true`
`'($EnableSourceLink)' == 'true'` evaluates to `'($EnableSourceLink)' = 'true'` evaluates to `false`
- This error was regressed by https://github.com/ppy/osu-framework/pull/2005
- Closes https://github.com/ppy/osu/issues/4039
---
Reenable SourceLink3 Support
> Reenable Sourcelink support by fixing the condition.

- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/Shaders/GlobalProperty.cs
- osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
- osu.Framework/Resources/Shaders/sh_Utils.h
Attempt at fixing undersaturated textures on OpenGL ES by disabling our manual `toSRGB` function via a global uniform if we aren't drawing to the back buffer.  Note that this check is removed on desktop with a `#ifdef GL_ES` directive.
OpenGL ES automatically gamma corrects shader output to sRGB textures, and the extension that allows for it to be disabled does not seem to be available (in OpenTK on iOS at least).
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_sRGB_write_control.txt
I would prefer to find a better way to do this, but changing `TexImage2D` to use `RGBA` format rather than `SRGB8_ALPHA8` seems to do nothing.
Note the blur looks much nicer now:
> Fix undersaturated textures on OpenGL ES

- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableList.cs
Turns out that allocating `WeakReference` is pretty expensive. I'm on a quest to leanify HitObjects where bindables are used as data stores, and ctor was the top profiled method.
| Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
| ----------------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
| HitCircleAllocationOld | 6.526 ms | 0.1289 ms | 0.1076 ms |   1445.3125 |           - |           - |             4.35 MB |
| HitCircleAllocationNew | 471.0 us |  6.980 us |  6.188 us |   1296.8750 |           - |           - |             3.89 MB |
|    SliderAllocationOld | 9.279 ms | 0.1532 ms | 0.1358 ms |   2515.6250 |           - |           - |             7.55 MB |
| …
> Reduce constructor overhead of bindables

- appveyor.yml
Otherwise trying to reference an appveyor build will give errors such as:
```
ppy.osu.Framework 0.0.8003 depends on ppy.osu.Framework.NativeLibs (>= 0.0.8003) but ppy.osu.Framework.NativeLibs 0.0.8003 was not found. An approximate best match of ppy.osu.Framework.NativeLibs 1.0.0 was resolved.
```
Don't merge until I've tested plz thx
> Make appveyor artifacts use nuget nativelibs

- osu.Framework/Screens/Screen.cs
- Closes ppy/osu#3050
`MainMenu` expects its child `ExitConfirmOverlay` to block exit input but when screen content is not yet visible `MainMenu.Content.IsPresent` being `false` and input is not blocked yet `MainMenu` receives input.
> Handle input on Screen only when its content propagates input

- appveyor_native_deploy.yml
This overrides anything I can do to stop it automatically deploying.
> Remove tag build rule for native deploy

- osu.Framework/IO/Network/WebRequest.cs
- Resolves #2095
My original plan was checking Content-Type but I couldn't make that work and probably this way is better.
---
> Suppress WebRequest logging for non-text response

- osu.Framework/Platform/GameHost.cs
This pull request simply adds a check for OpenGL ES when taking a screenshot. Without it, devices on GL ES will crash with SIGSEGV errors (iOS and Android devices, for instance).
* Tested on Windows 10 and Android. Got no errors.
> Fix screenshot for OpenGL ES

- osu.Framework/IO/Stores/DllResourceStore.cs
Adds support for nuget based resource projects, as an example.
> Allow loading assemblies from non-local DLL files via DllResourceStore

- osu.Framework/Audio/Track/TrackBass.cs
This was causing pops for me, and I'm hoping that this will help with ppy/osu#3648 (if it does we should follow up with un4seen).
It would be great to keep this here, but we don't use this flag in stable so it's safe to assume we won't get any audio degradation in comparison for now.
> Drop Float flag from audio stream creation

- osu.Framework/Graphics/Video/VideoDecoder.cs
- osu.Framework/Graphics/Video/VideoSprite.cs
`Texture`s weren't ever being returned to the reuse queue, which meant cleanup of underlying `TextureGLSingle`s were done on GC. If the host didn't realise it needed to GC this could cause OOM exceptions in GL.
Note that while `Sprite.Texture = ...` calls `Dispose` on the previous texture, this doesn't dispose the underlying `TextureGLSingle`. Arguable whether this is logical behaviour, but I believe there's a reason for it. Not relevant to this fix (we *don't* want the underlying `TextureGLSingle` to be disposed as we want to reuse it), just something I noticed.
> Fix video memory consumption

- .vscode/tasks.json
A regression caused by the addition of `osu-framework.iOS.sln`.
> Fix VSCode Restore task

- osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
- osu.Framework/Allocation/CachedModelDependencyContainer.cs
- osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
If two bindables had cross-dependencies in their `ValueChanged` (ie. one sets another's value) the rebind process could cause changes from one model on the previous model.
Just a proof-of-concept fix. Tests should be added before merge.
> Fix incorrect order of unbind/rebind of shadow model

- osu.Framework.Tests/Bindables/BindableMarginPaddingTest.cs
- osu.Framework.Tests/Visual/TestCaseContainer/TestCaseSafeArea.cs
- osu.Framework.iOS/IOSGameView.cs
- osu.Framework.iOS/IOSGameWindow.cs
- osu.Framework/Configuration/BindableMarginPadding.cs
- osu.Framework/Platform/GameWindow.cs
Newer phones and tablets often have notches and rounded corners.  This PR exposes these as a bindable, since they dynamically change when the device is rotated.  Framework consumers can use this to layout UI elements so that they are always visible.
Includes tests, but the results are only evident when running on a device.  Can't really add any asserts either, so it's mostly for visual verification.
Will need to implement this in Android too.
- Closes #2075
---
Add support for 'safe area' padding on mobile devices.
>  Add bindable for 'safe area' padding

- osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreen.cs
- osu.Framework/Screens/Screen.cs
- osu.Framework/Testing/TestCaseTestRunner.cs
This should not be allowed so now throws an exception.
> Disallow screens from being added to hierarchy without stack parent

- osu.Framework/Configuration/BindableMarginPadding.cs
This allows the tests to pass on my machine (I have the german lang pack installed. That results in `,` and `.` beeing swapped when it comes to decimals.)
------------------
Make the float.Parse calls culture invariant.
> Make the float parses culture invariant.

- osu.Framework/Game.cs
- osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs
- osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/GameWindow.cs
- osu.Framework/Platform/Linux/LinuxGameHost.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
- osu.Framework/Platform/Windows/WindowsGameHost.cs
- osu.Framework/Threading/GameThread.cs
- Fixes Game being `IsActive = false` during headless tests. (default `true`)
- `IsActive`'s state is now handled in one location - `GameWindow`.
- Removes the `OnActivated()`/`OnDeactivated()` methods in-favor of binding to the bindables.
> Rework GameHost/GameWindow IsActive state

- osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseFillFlowContainer.cs
- osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseBlending.cs
- osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseDropdownBox.cs
- osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderbar.cs
- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/Sample/SampleChannelBass.cs
- osu.Framework/Audio/Track/Track.cs
- osu.Framework/Audio/Track/TrackBass.cs
- osu.Framework/Audio/Track/TrackVirtual.cs
- osu.Framework/Configuration/Bindable.cs
- osu.Framework/Configuration/BindableBool.cs
- osu.Framework/Configuration/BindableMarginPadding.cs
- osu.Framework/Configuration/BindableNumber.cs
- osu.Framework/Configuration/BindableSize.cs
- osu.Framework/Graphics/UserInterface/Checkbox.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Platform/DesktopGameWindow.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
resolves #2150 
In order to avoid accidental misuse / misunderstandings, `.Value` must always be added to `Bindable` when requesting its value. One such case which used to be confusing:
```csharp
Bindable<Drawable> bindableDrawable = new Bindable<Drawable>();
if (bindableDrawable != null)
{
// true
}
if (bindableDrawable.Value != null)
{
// false
}
Drawable drawable = null;
if (bindableDrawable == drawable)
{
// ???
}
```
> Remove implicit operator from bindables

- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Game.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Threading/AudioThread.cs
- osu.Framework/Threading/GameThread.cs
- osu.Framework/Threading/InputThread.cs
- Allows potentially running more than one game in the lifetime of a host.
- Adds a method to unregister threads. Since this was allowing public usage of this interface, this seems logical. Note that `PerformanceOverlay` likely needs to have a bindable reference to GameThreads for completely fixing this.
> Audio thread and GameThread improvements

- osu.Framework/RuntimeInfo.cs
Avoids framework consumers having to check individual operating systems when showing or hiding features in their app.
The grouping is somewhat arbitrary, but in the majority of cases this is going to be what the developer expects (Windows/macOS/Linux = desktop, iOS/Android = mobile).
> Add IsDesktop and IsMobile to RuntimeInfo

- osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
- osu.Framework/Screens/ScreenStack.cs
stack.Push(new Screen()); // works correctly
stack.Push(new Screen()); // would not correctly suspend last screen
> Fix ScreenStack.Push behaving incorrectly when screen already present

- osu.Framework.iOS/GameViewController.cs
Requires users to swipe up twice to access the home bar or control centre, and down twice to access notifications.
Prevents accidental home bar usage on edge-to-edge iOS devices.
> Defer system gestures on screen edges on iOS

- osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
Because the ctor of BlendingInfo wasn't being called, `0` (literally) was being passed to `GL.BlendEquationSeparate` in `GLWrapper`.
> Fix buffered containers causing GL errors

- osu.Framework/Graphics/OpenGL/Buffers/LinearVertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
Currently, `VertexBuffer` is initialised at the point of construction. Going forward we'll want to assure it's only initialised on the draw thread.
> Ensure vertex buffers initialise on the draw thread

- osu.Framework/Audio/Track/TrackVirtual.cs
This fixes some potential issues that can occur where RaiseCompleted can be called many times until next() has properly finished executing.
Tested locally against osu! and seems to work fine.
> Stop RaiseCompleted being called multiple times for the same VirtualTrack

- osu.Framework/Graphics/BlendingInfo.cs
I was thinking about how to make sure cases like https://github.com/ppy/osu-framework/pull/2208 never happen again, had a bit of a brain-fart but realized this is the way to go (making sure BlendingInfo can't be instantiated the way it was being).
> Make BlendingInfo readonly

- osu.Framework.Tests/Bindables/BindableLeasingTest.cs
- osu.Framework/Bindables/Bindable.cs
Fixes a potential case where storing both the source and leased copy to fields and relying on `UnbindAllBindables` could potentially leave outward bound bindables in an incorrect state.
> Return any lease when calling UnbindAll on the lease source

- osu.Framework/IO/Network/WebRequest.cs
This fixes being unable to read returned json errors from the api when the server response code isn't in the 2xx range.
Defaults for the parameters taken from [here](https://source.dot.net/#System.Private.CoreLib/shared/System/IO/StreamReader.cs,802d803734748de8,references).
fixes ppy/osu#4271
> Fix premature disposal of ResponseStream

- osu.Framework.Tests/Platform/UserInputManagerTest.cs
- osu.Framework/Input/UserInputManager.cs
Currently, the very top level of the draw hierarchy never becomes alive. We need to make sure UserInputManager is always alive because checks dependent on parent life will always fail as a result.
> Ensure root UserInputManager is alive

- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
An update to docs of `[BackgroundDependencyLoader]`.
To me it wasn't so obvious that it was asynchronous, and I spent maybe 15 minutes figuring out why my API Request throws before even being sent.
I have a request manager inside the application, and one request was being started inside a `load` method. This caused the manager to try and add the request outside of the update thread for not a completely obvious reason at the time.
> Inform about dependency loader method being potentially asynchronous

- osu.Framework/Graphics/Containers/Markdown/MarkdownImage.cs
- osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Testing/TestBrowser.cs
This protects against bindings being overwritten.
Note that there are many other places we should be doing this, but I didn't want to break too much at once. On a quick check, these drawable ones are the important cases where a user could potentially overwrite framework-internal bindings. If/when we get object-initializer-inline event bindings, we should efinitely switch all remaining cases across (https://github.com/dotnet/csharplang/issues/307).
Closes #2250.
> Ensure public actions specify the event keyword

- osu.Framework.Tests/Visual/Containers/TestCaseTextFlowContainer.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
1. Fixes using x2/y2 anchors inverting the displayed words (e.g. `SOME TEXT` -> `TEXTSOME `).
2. Makes `TextAnchor` changeable post-load.
3. Fixes layout not being invalidated when children are added/removed/cleared/expired/etc.
Fixes issues presented in https://github.com/ppy/osu/pull/4467
> Fix TextFlowContainer not laying out correctly

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
- osu.Framework/Screens/IScreen.cs
- osu.Framework/Screens/ScreenStack.cs
Basic purpose here was to allow a `ScreenStack` to not fire `OnSuspend` until the next screen is ready to call `OnEntering`. This may be preferred for certain scenarios to create fluid transitions.
Required for https://github.com/ppy/osu/pull/4455.
Going forward we may want to add a new event for the beginning of a push occurring (`OnNextScreenLoading` or something like that) to allow for loading screens/states.
This also fixes quite a few issues with `Screen`/`ScreenStack`, and adds extensive testing. I tried to split these out into individual PRs but the logic is too intertwined. If necessary I'll give it another go.
Fixed:
- `TestScreenSlow` now uses a flag rather than `Thread.Sleep` to load "slow".
- Pushing to a non-loaded screen now throws an exception. This was undefined behaviour …
> Add non-immediate suspend support and fix many sanity issues with screens

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Allows targetting to work on `TestCaseDrawVisualiser`.
> Allow draw visualisers to be targetted by each other

- osu.Framework/Testing/TestCase.cs
Ensures framework consumers won't outright break from #2256.
> Add obsolete methods to avoid breaking test API change

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
- osu.Framework/Testing/TestBrowser.cs
- osu.Framework/Testing/TestCase.cs
Previously the test browser would not perform `[SetUp]` unless at least one `[Test]` was defined, which is outright incorrect.
> Ensure [SetUp] is run at least once when defined by a user test

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
When closed, the draw visualiser is cleared and reset to a clean slate, but the property display was not.
> Fix possible DrawVisualiser property display nullref

- osu.Framework.Tests/Visual/Testing/TestCaseTest.cs
- osu.Framework/Testing/SetUpStepsAttribute.cs
- osu.Framework/Testing/TestBrowser.cs
- osu.Framework/Testing/TestCase.cs
Allows adding steps global to all `[Test]`. Previously not possible due to `[SetUp]` discrepancies between nUnit and visual tests.
> Add attribute [SetUpSteps]

- osu.Framework.Tests/Threading/SchedulerTest.cs
- osu.Framework/Threading/Scheduler.cs
1. When scheduling from inside a `Schedule()`, the inner scheduled delegate would run instantaneously, even with `forceScheduled = true`.
2. `AddOnce()` would fail the equality comparison.
It's likely that this caused https://github.com/ppy/osu-framework/issues/2239 due to the inner re-schedule in `GLWrapper.ScheduleDisposal()`.
> Fix various Scheduler failure cases

- osu.Framework/MathUtils/RNG.cs
There's no reason to throw exceptions if minValue==maxValue, it'll just return the value.
> Relax RNG exception conditions

- osu.Framework.Tests/IO/TestWebRequest.cs
Issue with upstream httpbin.org (reported [here](https://github.com/postmanlabs/httpbin/issues/545)).
> Fix http (insecure) tests failing locally

- osu.Framework/Screens/Screen.cs
- osu.Framework/Screens/ScreenStack.cs
This prevents subclasses from overriding the property, making checking
for its truthiness and the associated ScreenWillBeRemovedOnPushException
superfluous
Since doing anything with RemoveWhenNotAlive that isn't setting it always to false it feels wrong to expose it as an overridable property on Screen. There are obscure scenarios this prevents (for example logging whenever the property gets read in a subclass or causing other side effects) but I do not think they are important concerns.
> Make Screen.RemoveWhenNotAlive sealed

- osu.Framework/Graphics/Batches/VertexBatch.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
Stops potentially resetting many more batches than are actually used within a frame.
> Remove potentially expensive iteration over all vertex batches

- osu.Framework/Lists/WeakList.cs
`RemoveAll()` is internally optimised to avoid O(n^2) operations.
Tested using the following code: https://hastebin.com/yanokamoze.cs
|                         Method |       Mean |     Error |     StdDev |     Median | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------------- |-----------:|----------:|-----------:|-----------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|           ForEachAliveNoRemove |   8.689 us | 0.5134 us |  1.4225 us |   8.449 us |  1.00 |    0.00 |           - |           - |           - |                88 B |
|        ForEachAliveNoRemoveNew |   6.988 us | 0.2016 us |  0.5753 us |   6.933 us |  0.82 |    0.13 |           - |           - |           - | …
> Improve performance of ForEachAlive

- osu.Framework/Graphics/Containers/ContainerExtensions.cs
In the case we can't use object initialiser (ie. for `CreateDrawable()` methods) constructing nested hierarchies has historically been ugly:
```csharp
var scaleContainer = CreatePlayfieldAdjustmentContainer();
scaleContainer.Child = Playfield;
KeyBindingInputManager.Child = scaleContainer;
InternalChildren = new Drawable[]
{
frameStabilityContainer = new FrameStabilityContainer { Child = KeyBindingInputManager },
Overlays = new Container { RelativeSizeAxes = Axes.Both }
};
```
now:
```csharp
InternalChildren = new Drawable[]
{
frameStabilityContainer = new FrameStabilityContainer
{
Child = KeyBindingInputManager
.WithChild(CreatePlayfieldAdjustmentContainer()
.WithChild(Playfield)
)
},
Overlays = new Container { RelativeSizeAxes = Axes.Both }
};
```
> Add container extensions to make adding nested drawables easier

- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Graphics/Containers/ContainerExtensions.cs
- osu.Framework/Graphics/Containers/IContainer.cs
Previously, `WithChild()`/`WithChildren()` would return the incorrect type:
This now uses contravariance to retain the original container type:
With...
```
public class DerivedContainer : Container<Box>
{
}
public class DerivedContainer<T> : Container
{
}
```
> Increase usability of WithChild/WithChildren

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
The exception will not be caught/displayed yet, but they will be in the future - I'm currently investigating nunit output.
In this case loading a `TestScreenSlow` will take up an entire thread of a limited concurrency thereadpool (the LCA threadpool) unless `AllowLoad = true`.
> Fix TestCaseScreenStack endlessly loading

- osu.Framework.Tests/Visual/Layout/TestCaseGridContainer.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
When implementing minimum grid size, I got increasingly annoyed at everything being inside a complex method.
I've split it out into components that perform specific tasks: `layoutCells` writes the size of cells, `getCellSizesAlongAxis()` retrieves the sizes of cells along a row or column span, and `distribute()` distributes any distributed dimensions along the span.
> Refactor GridContainer for readability + correctness

- osu.Framework/Graphics/BlendingInfo.cs
- osu.Framework/Graphics/DrawColourInfo.cs
No visible changes as far as I can tell, prevents brokenness due to ctor not being called.
> Fix incorrect instantiation of BlendingInfo

- osu.Framework.Tests/Configuration/FrameworkConfigManagerTest.cs
- osu.Framework.Tests/IO/TestDesktopStorage.cs
- osu.Framework.Tests/TemporaryNativeStorage.cs
- osu.Framework/Configuration/ConfigManager.cs
- osu.Framework/Configuration/FrameworkConfigManager.cs
- osu.Framework/Configuration/IniConfigManager.cs
- osu.Framework/Game.cs
- osu.Framework/Platform/GameHost.cs
Allows games to provide framework setting defaults.
- Closes #2203.
- Adds tests for `ConfigManager`.
> Add config manager default overrides

- osu.Framework/Platform/GameHost.cs
Since this is being done in `GLWrapper.Reset()` now.
> Remove extra GL clears

- osu.Framework/Graphics/Lines/PathDrawNode.cs
- osu.Framework/Graphics/OpenGL/DepthInfo.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
We'll want to be able to change the depth handling in more ways than `SetDepthTest()` allows.
> Replace SetDepthTest with stack-based depth information

- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
There's an increasing number of situations in which autosized grids are required.
> Allow GridContainer to be autosized

- osu.Framework.Tests/Visual/Layout/TestCaseTableContainer.cs
- osu.Framework/Graphics/Containers/TableContainer.cs
Expands on `GridContainer` to allow customization of columns/headers.
> Add TableContainer as an extension of GridContainer

- osu.Framework/Extensions/PolygonExtensions/ConvexPolygonExtensions.cs
- osu.Framework/Extensions/PolygonExtensions/PolygonExtensions.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- osu.Framework/Graphics/Primitives/IPolygon.cs
- osu.Framework/Graphics/Primitives/ProjectionRange.cs
- osu.Framework/Graphics/Primitives/Quad.cs
Originally I just wanted to get `ReadOnlySpan<Vector2> GetVertices()` in, but decided to take the time and optimise the existing intersection code since this code sometimes runs per-frame (see: `DelayedLoadWrapper`).
In this PR:
1. `Quad` vertices are made to be clockwise. This is now required for correct implementations of `IPolygon`.
2. Generics are used to avoid boxing of `IConvexPolygon` and `IPolygon`.
3. All allocations of vertex arrays have been removed, either through unsafe or use of stackalloc. Use of stack space should be fine for now since there's little vertices in all cases. In the future we may want to add a heuristic or a global buffer.
```diff
| Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- …
```
> Optimise IConvexPolygon.Insersects

- osu.Framework/Graphics/DrawableExtensions.cs
May be helpful in cases such as:
```
Drawable d;
InternalChildren = new Drawable[]
{
...,
d = CreateDrawable()
};
d.RelativeSizeAxes = Axes.Both
```
Which can now be written as:
```
InternalChildren = new Drawable[]
{
...,
CreateDrawable().With(d => d.RelativeSizeAxes = Axes.Both)
};
```
> Add extension method to provide drawable adjustments

- osu.Framework.Tests/Visual/Containers/TestCaseScrollContainer.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
Fixes https://github.com/ppy/osu-framework/issues/2306
Preview: https://streamable.com/20kg8
~~I've decided to only apply the clamp in OnDrag, as it seems to be the only case where clamping isn't applied via updatePosition (it looks bad if you clamp it that way when dragging).~~ Done so at scrollTo instead to resolve the jitter issue. I've tested the code paths into osu and it works fine, so it should be okay.
> Clamp scrollTo target to ClampExtension

- osu.Framework.Tests/Visual/Testing/TestCaseTest.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Testing/TestCase.cs
- osu.Framework/Testing/TestCaseTestRunner.cs
The `AddSteps()` ones aren't forced to be scheduled, but the clear was.
> Fix visual unit tests never running

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Screens/ScreenStack.cs
Closes https://github.com/ppy/osu-framework/issues/2277
Fixes ppy/osu#4530
Keep in mind that as a result of https://github.com/ppy/osu-framework/issues/2345, running tests in the test browser sequentially will not reach the test added in this branch as it will fail before then.
> Prevent non-current screens from handling input

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
Closes https://github.com/ppy/osu-framework/issues/2345
Since DisposeChildAsync unbinds bindables after it has already been unbound OnExiting, the OnUnbind check will fail. The actual second unbind gets blocked at the Drawable level, so correcting the test should be enough.
Also fixes TestMakeCurrentUnbindOrder to be resettable.
> Prevent OnUnbind from being invoked twice in TestScreens

- osu.Framework/Graphics/Sprites/FontAwesome.cs
Fixes `FontAwesome.cs(4340, 37): [CS0108] 'FontAwesome.Solid.Equals' hides inherited member 'object.Equals(object)'. Use the new keyword if hiding was intended.`
> Fix method hiding warning in FontAwesome

- osu.Framework.Tests/Visual/Containers/TestCaseContainerState.cs
- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Screens/ScreenStack.cs
I believe this is a more correct process for `ClearInternal()`:
1. Cleared containers will dispose children asynchronously.
2. Children aren't themselves cleared, so the hierarchy can be preserved.
3. The clearing process now calls `UnbindAllBindables` (now renamed `UnbindAllBindablesSubTree`) which can be overridden by `ScreenStack`.
Children removed without `disposeChildren = true` aren't unbound.
> Fix incorrectness of composite clearing

- osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
- osu.Framework/Screens/ScreenStack.cs
Prereqs:
If screens are suspended/exited, they won't be part of the stack's children, so they potentially won't be disposed & unbound (unless the screens are _exited_ and the stack updates for one more frame).
> Fix screen unbind/disposal sometimes not happening

- osu.Framework.Tests/Visual/UserInterface/TestCaseContextMenu.cs
- osu.Framework.Tests/Visual/UserInterface/TestCaseNestedMenus.cs
- osu.Framework/Graphics/Cursor/BasicContextMenuContainer.cs
- osu.Framework/Graphics/UserInterface/BasicMenu.cs
The variants try to *follow* the new design, because the design in #2135 didn't show them.
I'm also unsure if ``BasicContextMenuContainer`` should be in the ``UserInterface`` or the ``Cursor`` namespace
> Add basic variant of menu and context menu

- osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
- osu.Framework/Timing/InterpolatingFramedClock.cs
Fix interpolating clock seeking backwards on a failed interpolation. Now it will only seek backwards on an actual seek (as determined by `ElapsedFrameTime`).
> Fix interpolating clock seek

- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Testing/DrawFrameRecordingContainer.cs
- osu.Framework/Threading/AtomicCounter.cs
Haven't really been able to replicate in framework, the hierarchies we have are just not complex enough, but very easy to replicate in osu-side player testcases.
> Don't dispose drawnodes while being recorded

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Because `.Clear()` sets parent, which would happen after the disposal due to the schedule.
Also removed the recycle from `Dispose()` because it's unnecessary - this component is never disposed for the lifetime of the game. It causes cross thread operations otherwise with this change.
> Fix DrawVisualiser crashing on popout

- osu.Framework.Android/AndroidGameView.cs
Excludes the Android Volume keys from being consumed, and allows the device volume to be changed while playing the game.
Resolves #2383
> Fix android volume keys

- osu.Framework/Allocation/ObjectHandle.cs
- osu.Framework/Audio/Callbacks/FileCallbacks.cs
- osu.Framework/Audio/Callbacks/SyncCallback.cs
The main issue was that `FileCallbacks.staticProcedures` would create a new callback structure every time it was called, and was not being retained anywhere.  Changed to be a private static var that only gets set once.
As part of the change I also put in some safety to ensure we never try to work with a freed target.
Resolves #2200 
Will probably also resolve https://github.com/ppy/osu/issues/4384
> Fix AoT crashes on iOS when rapidly creating callbacks

- osu.Framework.Tests/Visual/Drawables/TestCaseDelayedLoad.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
The specific case this is fixing is DLWs within FillFlowContainers, where if `timeBeforeLoad = 0`, the intersection would be checked upon the first `Update()`, but the flow layout is only updated in a parent's `UpdateAfterChildren()`.
> Delay instant DelayedLoadWrapper intersection computation

- osu.Framework/Allocation/DependencyContainer.cs
Removed from https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations#value-types-as-dictionary-keys
Removes ~100MB garbage on a 13sec load of https://osu.ppy.sh/beatmapsets/470977#osu/1006822.
Most likely improves performance due de-virtualisation + inlining, but hasn't been tested for that purpose.
> Remove now-unnecessary custom comparer

- osu.Framework.Tests/Visual/UserInterface/TestCaseSearchContainer.cs
- osu.Framework/Graphics/Containers/SearchContainer.cs
Could be seen in test browser if a search term was present and dynamic recompilation was used.
This also improves the quality of `SearchContainer` tests substantially.
> Make SearchContainer re-filter after new child is added

- osu.Framework.Tests/Threading/AsyncDisposalQueueTest.cs
- osu.Framework/Allocation/AsyncDisposalQueue.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
This tackles two issues.
1. Calling `Task.Run(drawable.Dispose)` incurs a delegate allocation due to the capture of `drawable`.
2. There are potentially many calls happening to `Task.Run` here.
For this purpose, I've added a new component which allows us to both remove delegate allocation and batch multiple `.Dispose()` calls.
In a little test I made with `CompositeDrawable`, 10000 tasks were previously scheduled, and now only ~7 are. This further reduces as expected when the threadpool load is increased.
> Implement an async disposal queue

- osu.Framework/Threading/Scheduler.cs
`TestCaseDelayLoad` Previously:
> Avoid concurrent queue overhead in Scheduler.AddDelayed usage

- osu.Framework.Tests/Platform/TrackBassTest.cs
- osu.Framework/Audio/Track/TrackBass.cs
Adds more comprehensive testing in general. crossing my fingers for no random CI failures - I've run tests in a loop over 50 times and haven't had a local failure, but threading is hard here >_>.
`Restart()`, when called from the audio thread, inlines the Seek() and Start() calls into the current method. Because of this, `UpdateState()` doesn't get called before `Start()`, and `Start()` would early-return due to `CurrentTime` being out of date.
To resolve this, Start() now uses bass' raw position to figure out whether it should early-return.
> Fix looping tracks not restarting

- osu.Framework.Tests/Platform/TrackBassTest.cs
- osu.Framework/Audio/Track/TrackBass.cs
Prereqs:
Similar to the prereq PR - using bass' raw position to determine whether to early-return. I didn't notice a performance change with this from scrubbing in the music player.
> Fix TrackBass.Seek() potentially incorrectly returning early

- osu.Framework.Tests/Platform/TrackBassTest.cs
- osu.Framework/Audio/Track/TrackBass.cs
Prereqs:
Although the issue this caused is also resolved by https://github.com/ppy/osu-framework/pull/2416, I think this seems more correct? It's also what `TrackVirtual` does. Doesn't make sense to have `CurrentTime = 0` because `.Start()` would fail.
> Don't reset current time to 0 when track is stopped upon completion

- osu.Framework/Allocation/CacheInfo.cs
- osu.Framework/Allocation/DependencyContainer.cs
I noticed the memory usage of this (was somewhere in the top 5 on world.execute(me)), but turns out to have a significant impact on time as well:
```diff
| Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|---------:|---------:|------:|------:|------:|----------:|
- |    Get | 21.34 us | 1.099 us | 3.136 us |     - |     - |     - |     936 B |
+ |    Get | 870.2 ns | 48.47 ns | 134.3 ns |     - |     - |     - |         - |
```
(per `.Get()` call)
> Optimise DependencyContainer lookups

- osu.Framework/Graphics/UserInterface/BasicTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TabItem.cs
The previous default value felt unintuitive. This is a minor breaking change.
Also throw an exception when trying to remove a tab that should not be removed.
> Change TabItem.IsRemovable default to true

- osu.Framework/Graphics/Drawable.cs
We haven't experienced this yet, and this is hard to test without manual thread blocking, but it could happen via natural suspension of threads.
In the following test, the following exception gets thrown (aggregated into a parent):
```
System.NullReferenceException: Object reference not set to an instance of an object.
at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateClock(IFrameBasedClock clock) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 771
at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Drawable.cs:line 248
at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer …
```
> Fix potential disposal race condition

- osu.Framework.Tests/MathUtils/TestInterpolation.cs
- osu.Framework/Graphics/MarginPadding.cs
- osu.Framework/MathUtils/Interpolation.cs
- osu.Framework/Testing/Drawables/TestSceneHeaderButton.cs
Fixes #2284
The method has to be called `ValueAt`, must be static and have the same parameters as `InterpolationFunc<TValue>`
Already existing ``ValueAt`` methods inside ``Interpolation`` can also be moved to their own classes (e.g. ``ColourInfo``)
> Interpolation<T> searches for interpolation method inside the generic class

- osu.Framework/Input/GameWindowTextInput.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
- osu.Framework/Platform/MacOS/MacOSTextInput.cs
- osu.Framework/Platform/MacOS/Native/Cocoa.cs
Resolves #2392
Refactored the platform check in `GameWindowTextInput` into a separate class, instantiated from `MacOSGameHost`.
> Fix caps lock on macOS

- osu.Framework/Graphics/Primitives/Line.cs
1. `Line` is now readonly, to avoid unintentional struct copies.
2. `.At()` and `.IntersectWith()` now use raw coordinate operations to trigger JIT intrinsics and remove `Vector2` allocations. The `Vector2` allocations aren't _super_ expensive, but they add up here - around 300-400ns on a quad-quad convex polygon intersection.
3. `.IntersectWith()` / `.At()` are now inlined. I have measured ~40ns decrease from this in a simple quad-quad intersection.
I've also added a few more `.IntersectWith()` methods to drill down into more optimal cases but kept the remaining ones to ease usability for consumers that aren't as strict on perf.
> Improve performance of various Line operations

- osu.Framework.Tests/Bindables/AggregateBindableTest.cs
- osu.Framework/Bindables/AggregateBindable.cs
Takes multiple bindables and offers an aggregated (and bindable) result.
To be used to tidy up the existing audio subsystem (PR coming soon – feel free to wait for that to see this in action).
> Add AggregateBindable implementation

- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/AudioAdjustments.cs
- osu.Framework/Audio/IAggregateAudioAdjustment.cs
- osu.Framework/Audio/Sample/SampleChannelBass.cs
- osu.Framework/Audio/Track/TrackBass.cs
In preparation for being used in `DrawableAudioWrapper` (#2396).
> Move audio adjustment logic to separate class

- osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/AudioCollectionManager.cs
- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Audio/IAdjustableAudioComponent.cs
- osu.Framework/Audio/IAdjustableResourceStore.cs
- osu.Framework/Audio/Sample/SampleStore.cs
- osu.Framework/Audio/Track/TrackStore.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
`AudioManager.Track` -> `AudioManager.Tracks`
`AudioManager.Sample` -> `AudioManager.Samples`
`SampleManager` -> `SampleStore`
`TrackManager` -> `TrackStore`
This also tidies up the return types to not expose the underlying collection functionality. This was being used in dangerous ways osu!-side, so this is a step in simplifying the audio subsystem's usage in consumer apps.
> Rename sample/track managers to stores

- osu.Framework/Game.cs
Previously, it was possible to access any resource as a part of `TrackStore` and `SampleStore` via their `Get` methods because the entire resource store would be nested inside them. 
This nesting has been removed, so you can now only access files that are part of their specified namespaces. 
* For `TrackStore`, this will be the `Tracks` namespace. 
* For `SampleStore`, this will be the `Samples` namespace.
> Stop nesting all resources in global Track and Sample stores

- osu.Framework/Graphics/Textures/TextureLoaderStore.cs
* Resolves https://github.com/ppy/osu-framework/issues/2461
This implies that you can no longer nest stores inside TextureLoaderStore as you previously could have (for safety), and `GetStream` is now delegated to the inner `TextureLoaderStore.store`.
> Use IResourceStore for TextureLoaderStore instead of ResourceStore

- osu.Framework.Tests.iOS/osu.Framework.Tests.iOS.csproj
- osu.Framework.iOS.props
The visual test project does not currently compile properly as it still has explicit directory references per namespace.  Changed in-line with the Android visual tests.
Also updated package references in shared props file.
> Fix iOS visual tests

- osu.Framework/Graphics/Audio/WaveformGraph.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlasWhite.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
- osu.Framework/Graphics/Shapes/Triangle.cs
- osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
- osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
- osu.Framework/Graphics/Textures/Texture.cs
In https://github.com/ppy/osu-framework/pull/2318, the methods will receive a new "depth" parameter, which I don't want to be exposed publicly.
I've added helper methods in `DrawNode` to invoke the relevant methods instead.
---
Use `DrawNode.DrawTriangle()` and `DrawNode.DrawQuad()` instead.
> Internalise Texture/TextureGL DrawX() methods

- osu.Framework.Tests/Audio/AudioComponentTest.cs
- osu.Framework.Tests/Audio/TrackBassTest.cs
- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Audio/Sample/SampleStore.cs
- osu.Framework/Audio/Track/TrackStore.cs
This allows for adjustments to be placed on `AudioManager.Samples` and `AudioManager.Tracks` and have them apply to all tracks/samples game-wide, as one would expect.
Previously custom stores would be added at the top level (`AudioManager`) and therefore be immune to non-global adjustments.
> Nest all user-created sample and track stores in the global stores

- osu.Framework/Graphics/Sprites/SpriteText.cs
Accessing `SpriteText.Size` from a non-update thread can potentially cause a crash on the draw thread due to collection modification. This warns the user when this happens, rather than crashing on a different (untraceable) thread.
Closes #2457 (by providing a more relevant call stack when this happens again).
> Add thread check to SpriteText's character computation method

- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlasWhite.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
It's actually quite useful to have this one when drawing a custom vertex buffer.
> Re-expose TextureGL.Bind() publicly

- osu.Framework.Tests/Visual/Drawables/TestSceneProxyDrawables.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Drawable_ProxyDrawable.cs
- osu.Framework/Graphics/Shapes/Box.cs
Because `DrawOpaqueInterior()` wasn't passed through.
> Fix ProxyDrawables not drawing at the correct depth

- osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Drawable_ProxyDrawable.cs
Not sure how to really test this - it's removing an override so that buffered containers are drawn at the correct depth, but:
1. Children still don't get their opaque interiors drawn since `BufferedContainer` never invokes the required methods. It's not a `CompositeDrawable` anymore (it used to be, hence this code), so the base class doesn't handle it.
2. I've made the subtree method internal because it's pretty dangerous to let consumers adjust it as they wish.
> Fix BufferedContainers being drawn with the wrong depth

- osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
- osu.Framework.Tests/Visual/Platform/TestSceneSafeArea.cs
- osu.Framework.iOS/IOSGameWindow.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Input/GameWindowTextInput.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/GameWindow.cs
- osu.Framework/Platform/IWindow.cs
- osu.Framework/Platform/MacOS/MacOSTextInput.cs
First step in decoupling of `GameWindow` for #2448 
Eventually the `osuTK.IGameWindow` inheritance will go away as we replace many properties and events with bindables.
> Introduce IWindow interface on GameWindow

- osu.Framework/Platform/IWindow.cs
Missed a property that's used in osu! but not within the framework.
> Expose AvailableResolutions via IWindow

- osu.Framework/Graphics/OpenGL/Buffers/LinearVertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
They're very unwieldy to use by themselves, requiring custom implementation to check whether updates should/should not occur.
The whole process is functionally equivalent to what `VertexBatch` with numBuffers = 1 already does.
Breaking changes:
`LinearVertexBuffer` and `QuadVertexBuffer` can no longer be constructed outside of osu!framework.
For existing code, `LinearBatch(size, 1)` and `QuadBatch(size, 1)` may be used to replace vertex buffer usages. Code must be updated to always invoke `batch.Add(vertex)` with the vertices that should be drawn.
`VertexBuffer` may still be derived for custom implementations.
> Internalise vertex buffers

- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Threading/ThreadedTaskScheduler.cs
Easier identification of different scheduler pools when debugging.
> Allow providing a custom name for ThreadedTaskSchedulers

- osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
We don't do cross-thread operations anywhere. Even when the lock hasn't been taken it's still not a no-op:
|                 Method |     Mean |     Error |    StdDev |
|------------------ |--------:|--------:|----------:|
| No Lock                 | 310.1 ns |    1.837 ns |  1.628 ns |
| Locked                  | 20.96 us | 0.2716 us | 0.2540 us |
(per 1000 locking operations)
> Remove all locking from GlobalPropertyManager

- osu.Framework.Tests/Visual/Containers/TestSceneVisibilityContainer.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
- osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
- osu.Framework/Graphics/Containers/VisibilityContainer.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/LogOverlay.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
Move away from property implementation to allow for more flexibility in usage scenarios. Adds documentation and test coverage.
`VisibilityContainer` no longer implements `IStateful<Visibility>`, instead exposing a single `Bindable<Visibility> State`.
> Migrate VisibilityContainer to use a bindable for state

- osu.Framework/Graphics/OpenGL/GLWrapper.cs
I didn't notice a specific breaking case, just found this while refactoring. Will remove g_GammaCorrection at a later point.
> Fix g_BackbufferDraw not being set on framebuffer unbinds

- osu.Framework/Development/DebugUtils.cs
This is in cases, such as Android, where the Entry Assembly is NULL due to unmanaged calls.
> The assembly that is the process executable in the default application domain, or the first executable that was executed by ExecuteAssembly(String). Can return null when called from unmanaged code.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.8
> Add null check for debug check and fallback to Calling assembly

- osu.Framework.Android/AndroidGameHost.cs
Credit to @hex11 for the initial implementation in #2245. This will stop the keyboard constantly getting in the way every time there is a text field
> Set OnScreenKeyboardOverlapsGameWindow for Android

- osu.Framework.Tests/Visual/UserInterface/TestSceneDrawablePath.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/Lines/Path_DrawNode.cs
It should've only been removed when rendering the path to the framebuffers, but it was also removing blending when rendering to the screen.
From:
| From | To |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1329837/59523902-7615d580-8f0d-11e9-9eaa-e84257c5ca58.png) | ![image](https://user-images.githubusercontent.com/1329837/59523937-8f1e8680-8f0d-11e9-920a-9477a9566d43.png) |
| ![image](https://user-images.githubusercontent.com/1329837/59523912-7b732000-8f0d-11e9-8f46-40131e08ef7d.png) | ![image](https://user-images.githubusercontent.com/1329837/59523951-96459480-8f0d-11e9-9c3a-ae4e29bd3380.png) |
Also tested osu! side sliders / profile overlay.
> Fix path blending being removed too liberally

- osu.Framework/Input/InputManager.cs
Ensures that key repeats will be ended only by releasing the currently repeated key.  Previously it was possible to stop a key repeat from triggering by releasing a different key.  Especially noticeable when arrowing through text boxes, but would occur for any key.
Scenario:
1. Left key is pressed.  Key repeat timer starts, key is set to Left.
2. Right key is pressed.  Key repeat timer restarts, key is set to Right.
3. Left key is released.  Key repeat timer stops, key is set to null.
4. Right key is still held, but is not repeating even though it is the most recent key down.
This PR changes step 3, so that the key repeat timer is only stopped if the Right key is released.
> Fix key repeats sometimes being ignored

- osu.Framework/Logging/Logger.cs
Not added to `Logger.Error()` since I don't believe that's a desired use-case.
> Add logger override to hide output from console listeners

- osu.Framework/Graphics/Textures/TextureStore.cs
- osu.Framework/IO/Stores/DllResourceStore.cs
- osu.Framework/IO/Stores/IResourceStore.cs
- osu.Framework/IO/Stores/OnlineStore.cs
- osu.Framework/IO/Stores/StorageBackedResourceStore.cs
Resolves #2529
Prereqs:
Example:
Console:
```
[performance:verbose] 2019-06-17 07:20:38: Resource Textures/Grades/A.png was retrieved from a DllResourceStore on a non-background thread.
```
performance.log:
```
2019-06-17 07:20:38: Resource Textures/Grades/A.png was retrieved from a DllResourceStore on a non-background thread.
2019-06-17 07:20:38: at osu.Framework.IO.Stores.DllResourceStore.GetStream(String name)
2019-06-17 07:20:38: at osu.Framework.IO.Stores.ResourceStore`1.GetStream(String name)
2019-06-17 07:20:38: at osu.Framework.IO.Stores.ResourceStore`1.GetStream(String name)
2019-06-17 07:20:38: at osu.Framework.Graphics.Textures.TextureLoaderStore.Get(String name)
2019-06-17 07:20:38: at osu.Framework.IO.Stores.ResourceStore`1.Get(String name)
2019-06-17 07:20:38: at …
```
> Add logging for non-background resource retrievals

- osu.Framework.Tests/Visual/UserInterface/TestSceneCheckboxes.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/UserInterface/Checkbox.cs
- osu.Framework/Graphics/UserInterface/CircularProgress.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
If an implementation of a UI control was binding to its own `Current` internally, an external change to `Current` via the setter could cause loss of flow of information.
> Fix UI controls implementing IHasCurrentValue in an unsafe way

- osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
- osu.Framework.iOS/IOSGameView.cs
- osu.Framework.iOS/IOSGameWindow.cs
- osu.Framework.iOS/Input/IOSKeyboardHandler.cs
- osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs
Holding backspace on software keyboard was triggering "delete word" at the iOS level but not in the framework. This means delete events were being slowed down by the operating system.  Also backspace was not being correctly handled by the hardware keyboard.
> Fix backspace on iOS

- osu.Framework/Audio/Sample/SampleStore.cs
- osu.Framework/Development/DebugUtils.cs
- osu.Framework/Graphics/Textures/TextureStore.cs
- osu.Framework/IO/Stores/IResourceStore.cs
- osu.Framework/Platform/GameHost.cs
- `TextureStore` now only logs on cache misses. On checking, other stores are already doing this (`TrackStore`, `SampleStore` etc.) so I believe this is in line with expectations.
- Stack traces are only output in debug configurations. As an alternative, this could match `FrameworkSetting.PerformanceLogging` to allow for the ability to also log in release builds. I kind of like this idea, but it will likely result in the need of a static bool to track state. Thoughts?
> Reduce overhead of blocking resource store log events

- SampleGame.iOS/Application.cs
- osu.Framework.Tests.iOS/Application.cs
- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework.iOS/IOSGameView.cs
- osu.Framework.iOS/Input/IOSKeyboardHandler.cs
- osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs
Note that we remove the "placeholder" text if using hardware keyboard, because otherwise it allows the user to select the invisible text with shift+arrow keys, which will display the cut/copy icons in the on-screen command bar.
> Ensure iOS only ever uses one keyboard handler at a time

- osu.Framework/Input/Bindings/KeyCombination.cs
Aimed to solve ambiguous display.
> Change ReadableString output to not include a joining character

- osu.Framework/Graphics/UserInterface/Dropdown.cs
Fixes osu! chat not being draggable when too many channels are joined.
> Remove unnecessary hover handling in Dropdown

- osu.Framework.Tests/Visual/Drawables/TestSceneDrawNodeDisposal.cs
- osu.Framework/Graphics/Batches/VertexBatch.cs
- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
- osu.Framework/Graphics/Shaders/Shader.cs
- osu.Framework/Graphics/Shaders/ShaderManager.cs
- osu.Framework/Graphics/Shaders/ShaderPart.cs
Several important changes here.
1. `DrawNode.Dispose(bool)` now happens 3-frames into the future.
2. To tighten things as a consequence of (1), all disposed objects (framebuffers, vertexbuffers, vertexbatches) have had their 3-frame delay removed. Their finalisers still have the 3-frame delay, not for the delay but to force them onto the GL thread.
3. `DrawNode` now nulls the source on disposal - fixing the issue.
Also, all shader disposal methods have been removed - shaders should never be disposed with our current structures.
Finally, I've removed the finaliser from vertexbatch, since any time it gets finalised its vertex buffers will also be finalised.
> Fix potential memory leaks with disposed DrawNodes

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
- osu.Framework/Graphics/UserInterface/BasicDropdown.cs
- osu.Framework/Graphics/UserInterface/BasicMenu.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
This is a breaking change for everything that directly created instances of ``Menu`` and/or related classes.
> Make menu and related classes abstract

- osu.Framework/Configuration/FrameworkDebugConfig.cs
- osu.Framework/Platform/GameHost.cs
For now we have deemed this counter-productive. It may be added back int eh future as a framework-consumer Begin/EndGameplayExclusiveMode which would automatically optimise the GC (and other) workflows for periods of time when the user is involved exclusively in gameplay.
If you were manually setting this, you can do so via [.NET methods](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/latency?view=netframework-4.8).
> Remove custom GC mode changing

- osu.Framework/Game.cs
Avoids potentially initialising a texture atlas that would otherwise never be required. Also reduces startup overhead for normal users.
> Load debug overlays on demand rather than on startup

- osu.Framework.Android/AndroidGameHost.cs
- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework/Platform/GameHost.cs
On desktop this seems to result in around 50% lower LOH usage in most cases. We do cause some fragmentation along the way which should eventually be addressed, but I believe this should reduce mobile device memory pressure in the mean time.
> Limit ImageSharp memory usage on memory constrained devices

- osu.Framework/Graphics/Drawable.cs
Sometimes we want to know when our parent hierarchy has changed in any way, so tree traversals can be brought up-to-date. Until now this was basically impossible.
> Add invalidation event when a parent changes

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- Fixes unload not successfully dropping all references.
- Fixes excessive parent traversal when no parent optimising container is available.
- Adds more robust tests.
> Fix delayed load unload reference retention

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Cache revalidation was being blocked by an already-true condition.
> Fix DelayedLoadUnloadWrapper unnecessarily reloading after removal

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Resolves #2610
Uses a local variable in the fallback case, passing it into the content when loaded.
> Add lifetime support to DelayedLoadUnloadWrapper

- osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
In an effort to make these as low overhead as possible, we definitely do not want to be scheduling to a potentially hidden (non-updating) drawable.
> Avoid schedule invocations from global statistic changes

- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
`DelayedLoadUnloadWrapper` with no containing `OpitimisingContainer` would have incorrectly incremented the counter.
> Fix DelayedLoadUnloadWrapper loaded count being incorrect

- osu.Framework/Logging/Logger.cs
Closes https://github.com/ppy/osu/issues/5228.
Missed a second constructor.
> Fix nullref on using logger without a target specification

- osu.Framework/IO/Stores/GlyphStore.cs
Turns out the offset was from the buffer, not the stream.
> Fix regression causing all glyphs to appear incorrectly

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
In some cases it may be possible for children to be alive without actually being loaded - e.g. the parent updated its children's life but decided it doesn't need to be updated further due to presence.
> Fix non-loaded drawables potentially being drawn

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Not-loaded DelayedLoadWrappers would get in a perpetual state of checking-for-load if they were not explicitly disposed.
> Fix DelayedLoadWrapper potentially not cleaning up scheduled tasks

- osu.Framework/Platform/GameHost.cs
Adding this back as it seems to be better if anything. Leaving it in an always-on state to keep things simple. In the future we could consider exposing this to the game for use specifically during performance-dependent gameplay segments, or toggle it automatically when the window is inactive.
Should hopefully help resolve ppy/osu#5357.
> Use GC SustainedLowLatency again

- osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
With more than one joystick device where only one was connected, this would cause excess allocations / state changes.
This doesn't fix the fact that multiple joysticks providing different states will still exhibit the same behaviour (a more involved fix required for that).
> Avoid creating joystick states for disconnected devices

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
The `FirstOrDefault` here is still allocating an enumerator which may be able to be optimised away.
> Reduce transform allocation overhead of autosize updates

- osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
Allows us to optimise scenarios in which many VBOs get instantiated and disposed in quick succession, leading to ephemeral LOH usage and extra GC pressure.
A future consideration is adding support for a user-provided memory pool.
> Add memory pooling for VBO arrays

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
This is not a full fix (https://github.com/ppy/osu-framework/issues/2659) - it only covers the disabled-during-loadcomplete part.
Also adds a testcase for https://github.com/ppy/osu-framework/issues/2659.
> Fix TabControl throwing bindable disabled errors on load complete

- osu.Framework/IO/Stores/GlyphStore.cs
`readableHeight` / `readableWidth` are there to fix the issue (crash at results screen osu!-side).
Other changes are optimisations to remove per-iteration checks. Have been tested across all fonts we use currently.
> Fix glyphs being read outside of cached texture bounds

- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
Fixes #2661
Fixes ppy/osu#5391
There were several issues here:
1. Caching wasn't working at all - frame buffers unbound their render buffers immediately so only one render buffer was ever used game-wide.
2. Caching seems to be done at the wrong place - we don't want the associated memory from render buffers present until the game is exited.
3. As far as I can tell, you need to bind the render buffer to attach it to a framebuffer, which wasn't being done previously except for when the size changed.
This change is mostly a simplification which removes all caching.
This is also in preparation for caching framebuffers/renderbuffers at a higher level, where they can be both reused and recycled.
> Rework and simplify RenderBuffer to fix incorrect usages

- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
The previous setting assumes it would ever be batched, but in practice this basically never happens. Minimising batch size seems like a better short-term option until we have a better method of deciding and managing batch sizes.
> Reduce LinearBatch size of CircularProgress

- osu.Framework/Graphics/Lines/Path.cs
Potentially still being used by drawnode. Also stops needlessly disposing `Texture.WhitePixel` on `Texture_Set`.
> Avoid disposing Path texture

- osu.Framework/Graphics/Lines/SmoothPath.cs
Probably not measurable in any way, but I don't believe it is required either.
> Avoid creating mipmaps for SmoothPath

- osu.Framework/Graphics/Batches/TriangleBatch.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/Lines/Path_DrawNode.cs
- osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
We were using 3 vertices per triangle as specifications for LinearVertexBatch while it should have been 6. This centralises that logic to standardise and avoid similar issues in the future.
> Add TriangleVertexBatch to centralise and avoid incorrect vertex count specifications

- osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Vertices/DepthWrappingVertex.cs
```diff
| Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|----------:|----------:|------:|------:|------:|----------:|
- |    Add | 249.0 ns |  1.528 ns |  1.429 ns |     - |     - |     - |         - |
+ |    Add | 42.88 ns | 0.2655 ns | 0.2483 ns |     - |     - |     - |         - |
```
I go from 120fps -> 200fps with chat opened to #lazer.
> Optimise vertex buffer vertex additions

- osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
- osu.Framework/Platform/GameHost.cs
Removes any potential overhead of this process.
> Only consume ETW events after GlobalStatistics has become visible

- osu.Framework/Bindables/Bindable.cs
If a drawable is disposed via anything that is not a `CompositeDrawable`, there is a chance the `UnbindAllBindables` will be run on the finalizer/async disposal thread. In this case, with the use of leased bindables, it is possible to reach a deadlock scenario. One such example follows:
> Fix bindable potentially deadlocking on nested enumeration operations

- osu.Framework.Android/AndroidGameActivity.cs
- osu.Framework.Android/AndroidGameView.cs
- osu.Framework.iOS/GameAppDelegate.cs
- osu.Framework.iOS/GameViewController.cs
- osu.Framework/Platform/GameHost.cs
Moved out from per-platform implementations to allow for future agnostic additions (and potential invocation on desktop platform).
> Allow memory clean-up via GameHost.Collect

- osu.Framework.Tests/Visual/Drawables/TestScenePathApproximator.cs
- osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs
- osu.Framework.Tests/Visual/Input/TestScenePathInput.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneDrawablePath.cs
- osu.Framework/Graphics/Lines/Path.cs
Currently, `Path` can take one of two sizing modes: relative, or "auto" size. In the case of "auto" size, it doesn't use the standard `AutoSizeAxes` convention. In the case of relative size, it cannot be turned back into auto-size without manually invalidating the draw size or otherwise invalidating the layout.
Basically, current `Path` sizing is generally inadequate for advanced usage scenarios. One such scenario which will be used osu!-side is the case where paths are initially auto-sized, but then forced to a static size to avoid continuous resizing.
To achieve this I've gone the full way to make `Path` support `AutoSizeAxes` much like `CompositeDrawable`.
There are now three modes of operation for paths:
```
// Auto size
new Path()
// Static size
new Path
{
AutoSizeAxes = Axes.None, …
```
> Implement proper auto-sizing for Path

- osu.Framework/Input/Bindings/InputKey.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/osu.Framework.csproj
Adds media keys to InputKey enum, allowing them to be used in keybindings.
> Add media keys to InputKey enum

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
Previously, having `Masking` disabled on a `CompositeDrawable` means children contained inside it are able to receive positional input even if its from outside of the `CompositeDrawable`'s `DrawRectangle`. 
This behavior is undesirable for some scenarios, such as if we want to use a `Container` to denote the area for where input should be allowed, such as in https://github.com/ppy/osu/issues/5452.
This exposes a new virtual property that can be overridden to denote any `CompositeDrawable` as a positional input-confining drawable, forcing a `ReceivePositionalInputAt` check, as well as makes `ScrollContainers` override it by default.
> Expose CompositeDrawable's subtree specific positional input conditional

- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
Split out of https://github.com/ppy/osu-framework/pull/2692 as an important fix. Was relying on GC until now (which is not optimal as this is a native memory heavy class).
> Eagerly dispose FrameBuffers' backing textures

- osu.Framework/Caching/Cached.cs
- osu.Framework/Configuration/FrameworkDebugConfig.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
We haven't used this recently. It causes cross-thread issues when in an enabled state, so it's best to be removed for now.
Closes https://github.com/ppy/osu-framework/issues/2457
Closes https://github.com/ppy/osu/issues/3517
> Remove setting to bypass cached

- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
Currently, we need to perform the following in order to use a `FrameBuffer`:
```
if (!frameBuffer.IsInitialized)
frameBuffer.Initialise(filteringMode, formats);
```
This changes the process so that the framebuffer is initialised during `Bind()`, as is done for `VertexBuffer`. As a result of this:
1. `FrameBuffer` takes filtering mode and render formats as constructor arguments.
2. `BufferedDrawNodeSharedData` also ^
3. `BufferedContainer` takes ctor arguments for render format + filter mode.
Previous code:
```csharp
var buffered = new BufferedContainer() { PixelSnapping = true };
buffered.Attach(RenderbufferInternalFormat.DepthComponent16);
```
New code:
```csharp
var buffered = new BufferedContainer(new[] { RenderbufferInternalFormat.DepthComponent16 }, true)
```
You can no longer …
> Cleanup framebuffer initialisation process

- osu.Framework.Android/AndroidGameHost.cs
Resolves https://github.com/ppy/osu/issues/5562
Currently on my device, I can't seem to get the game to not close when switching to another app (even when not opening a URL) no matter what, so this change won't stop the app from closing. However, the URL will now open successfully.
This was implemented using the sample from https://developer.android.com/guide/components/intents-common.html#ViewUrl
> Implement URL opening for android

- osu.Framework/Bindables/Bindable.cs
- osu.Framework/Bindables/BindableList.cs
- osu.Framework/Caching/Cached.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- osu.Framework/Graphics/Containers/FlowContainer.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
- osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
- osu.Framework/Graphics/Containers/SearchContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Lines/Path.cs
- osu.Framework/Graphics/Lines/SmoothPath.cs
- osu.Framework/Graphics/Sprites/SpriteIcon.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
There were a few cases `Cached` was being used as a `readonly` variable, which causes it to never actually work (due to implicit struct copy before method calls). We have decided it is safer to just make it a class.
Usages of `Cached` without initialising (via `new Cached()`) will need to be updated.
> Change Cached to a class to avoid incorrect usage

- osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
I'm still pouring over the documentation, but can find nothing mentioning that this is an incorrect usage of render buffers yet...
> Add temporary hotfix for deflate mod crashes on iOS

- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt
> The command
void RenderbufferStorageMultisampleEXT( enum target, sizei samples, enum internalformat, sizei width, sizei height );
> When the renderbuffer is used as a source or destination for any
operation, when the attachment is flushed, or when the attachment is
broken, an implicit resolve of the multisample data may be performed.
After such a resolve, the contents of the multisample buffer become
undefined.
>  The command
void RenderbufferStorage( enum target, enum internalformat, sizei width, sizei height );
is equivalent to calling RenderbufferStorageMultisampleEXT with samples equal to zero.
https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_Programmin …
> Re-implement proper renderbuffer re-use

- osu.Framework.Tests/Visual/Sprites/TestSceneTextureUnit.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlasWhite.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
- osu.Framework/Graphics/Shaders/Shader.cs
Prior to changes, there was no way to bind more than one texture for use in a shader. The changes creates a `TextureUnit` parameter on the GLWrapper `Bind` function to allow it to to bind textures to other texture units if so desired. A default of `Texture0` is added as that is the most common use.
Additionally, to sample other texture units from a shader, `sampler2D` was added as a uniform on the `Shader` class. Previously this was not needed as the default value of 0 would always point to `Texture0`.
> Allow binding multiple textures for use in shaders

- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
1. Allows masking+effect `CompositeDrawable`s to be targeted. Sometimes these composites are combined with an `Alpha = 0, AlwaysPresent = true` box that is un-targetable.
2. Considers drawables outside the area of parents for targetting.
3. Disallows targetting of `Drawable`s without custom drawnodes (e.g. fullscreen input receptors).
4. Blocks game-wide input while searching.
5. Allows targeting of cursor containers.
Only tested by going around to various screens and cases in osu!. Let me know if testcases are desired, but this component is not easy to test yet.
> Improve DrawVisualiser selection heuristics

- osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaContainer.cs
- osu.Framework/Graphics/Containers/SafeAreaContainer.cs
Resolves #2748 
Fixes the case where a `SafeAreaContainer`'s padding may be set greater than than its `DrawSize`, potentially causing inverted children.
Also fixes `TestSceneSafeAreaContainer`'s checkboxes not triggering an update of the test containers.
> Fix safe area containers causing potentially incorrect display

- osu.Framework/Graphics/UserInterface/TextBox.cs
Fixes ppy/osu#5766
Textbox was considering all keys starting from `Keypad0` as keys outputting characters.
This now checks if key is in range `Key.Keypad0 .. Key.NonUSBackSlash`
> Fix textboxes consuming media keys as input

- osu.Framework/Graphics/Containers/SafeAreaContainer.cs
Invalidates the padding cache on `DrawInfo` rather than `Parent`.
> Fix SafeAreaContainer padding not updating with transforms

- osu.Framework.Tests/Visual/Sprites/TestSceneScreenshot.cs
- osu.Framework/Graphics/OpenGL/GLWrapper.cs
Fixes ppy/osu#5551, and also fixes the desktop appearing in the window on linux.
From:
To:
(Red should not be visible)
> Clear window with opaque blackness

- osu.Framework/Graphics/Drawable.cs
- Closes #2792
Allows custom events to be consumed by drawables.
> Call Handle in default case in TriggerEvent instead of returning false

- osu.Framework/Graphics/BlendingMode.cs
- osu.Framework/Graphics/Sprites/FontUsage.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Lists/LockedWeakList.cs
- osu.Framework/Lists/WeakList.cs
- osu.Framework/Testing/TestScene.cs
Obsoleted in 2019.221.0 (had no existing removal documentation)
> Remove obsolete FontUsage/SpriteText parameters

- osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Input/IHandleGlobalKeyboardInput.cs
- osu.Framework/Input/PlatformActionContainer.cs
- osu.Framework/Testing/TestBrowser.cs
This is a proposal to help resolve https://github.com/ppy/osu/issues/5134.
Note that optimally, we would *only* allow scroll events through, as it is weird to be able to hover things behind overlays and have them respond to the hover. Unfortunately, this isn't easily possible due to elements like `TooltipContainer` expecting to still receive the move events. The only solution I can think of for this would be to ensure each overlay has its own tooltip container (which may actually be preferrable?).
Open to suggestion for alternative implementations.
> Allow overlays to only block click events

- osu.Framework.Tests/Visual/Drawables/TestSceneProxyDrawableLifetime.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/Drawable_ProxyDrawable.cs
1. Fixes LifetimeStart/LifetimeEnd not being transferred from the original `Drawable`. This is two-part:
1. Lifetime is redirected.
2. The `LifetimeChanged` action is invoked on the proxy.
2. Fixes `ProxyDrawable`s getting into a weird state when the original `Drawable` disposes - the proxy is also disposed (parent nulled), but is still part of a composite.
1. `ProxyDrawable` is no longer disposed when the original `Drawable` disposes.
2. Various methods inside `ProxyDrawable` now check for the original's disposal state.
> Fix ProxyDrawable not correctly transferring LifetimeStart/LifetimeEnd

- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Uses the same algorithm/tolerance as the circular arc path approximation, just adapted for CircularProgress.
Got annoyed at my circles being too jagged:
| old | new |
| --- | ---- |
| ![image](https://user-images.githubusercontent.com/1329837/63842394-6ad82f00-c9bf-11e9-8a9e-07a3dbd1af87.png) | ![image](https://user-images.githubusercontent.com/1329837/63842405-6f044c80-c9bf-11e9-9645-9fd21ccaeab2.png) |
> Increase resolution of CircularProgress depending on radius

- osu.Framework/Input/MouseButtonEventManager.cs
Fixes #2809.
The same conditional already existed in HandleMouseUp...
> Fix nullrefs when clicking outside the window

- osu.Framework/Development/DebugUtils.cs
osu.Game.Rulesets.Custom.Tests -> osu.Game -> osu.Framework would cause the working directory to become the location of the `osu.Game.dll` in nuget cache. This was due to an incorrect lookup order for `GetEntryAssembly`.
Full testing:
```
osu.Framework.Tests (rider)
HostAssembly C:\Users\Dean\Projects\osu-framework\osu.Framework.Tests\bin\Debug\netcoreapp2.2\osu.Framework.Tests.dll
Assembly.GetEntryAssembly() C:\Users\Dean\Projects\osu-framework\osu.Framework.Tests\bin\Debug\netcoreapp2.2\osu.Framework.Tests.dll
Assembly.GetCallingAssembly() C:\Users\Dean\Projects\osu-framework\osu.Framework.Tests\bin\Debug\netcoreapp2.2\osu.Framework.dll
osu.Framework.Tests (nUnit rider)
HostAssembly C:\Users\Dean\Projects\osu-framework\osu.Framework.Tests\bin\Debug\netcoreapp2.2\osu.Framework.dll …
```
> Fix incorrect working directory when a nuget framework consumer is consumed by another project

- osu.Framework.Tests/Visual/Containers/TestSceneCachedBufferedContainer.cs
- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Statistics/FrameStatistics.cs
- osu.Framework/Threading/DrawThread.cs
Called it `RedrawOnScale`, am open to suggestions. It's `true` by default to not change current behaviour/behaviour when sprites/text are used.
> Add an option to not redraw BufferedContainers on scale change

- osu.Framework.Tests/Bindables/BindableDoubleTest.cs
- osu.Framework.Tests/Bindables/BindableFloatTest.cs
- osu.Framework/Bindables/BindableDouble.cs
- osu.Framework/Bindables/BindableFloat.cs
- Takes 50% of the precision to ensure no-underflow for values near to default (for example, `Value = 1.01f`, `Default = 1.00f`, `Precision = 0.01f`)
Fixes *"no revert button for UI-scale 1.01x"* part of ppy/osu#5940
> Fix BindableFloat.IsDefault returning true for non-default values

- osu.Framework.Tests/Bindables/BindableDoubleTest.cs
- osu.Framework.Tests/Bindables/BindableFloatTest.cs
- osu.Framework/Bindables/BindableDouble.cs
- osu.Framework/Bindables/BindableFloat.cs
- Fixes a regression occurred in #2816
> Use Precision.AlmostEquals for checking BindableNumber.IsDefault

- osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
Easily replicable by deleting a slider from the editor.
> Fix RenderBuffers disposing on the wrong thread

- osu-framework.Android.sln.DotSettings
- osu-framework.iOS.sln.DotSettings
- osu-framework.sln.DotSettings
Different local code style settings causes Rider/ReSharper to show warnings when it shouldn't. This PR explicitly sets some of these settings. It doesn't cover all cases where this happens, only the ones which differed from my configuration (I no longer get any warnings).
> Specify Rider analysis rules explicitly

- osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
- osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
Fixes #2836
Renamed `TestSceneKeyBindings` to `TestSceneKeyBindingsGrid` just to make it less of a catch-all test scene for where this stuff _should_ go. `TestSceneKeyBindingContainer` is its replacement.
> Fix TriggerPressed/TriggerReleased crashing with null keybindings

- osu.Framework.Tests/Exceptions/TestSceneDependencyInjectionExceptions.cs
- osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
- osu.Framework/Allocation/DependencyActivator.cs
- osu.Framework/Allocation/DependencyContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/Drawables/Steps/StepButton.cs
- osu.Framework/Testing/TestSceneTestRunner.cs
Fixes #2839
The DIE stuff was super ugly/wrong, and we only really needed to rethrow the inner exceptions while preserving stacktraces. This also fixes several other cases of unreadable exceptions.
> Improve output of exceptions thrown during dependency injection

- osu.Framework.Android/osu.Framework.Android.csproj
Fixes that you do not need to build the consuming project two times.
Also automatically adds the android native libraries to the apk.
No outputdirectory workarounds needed.
Contains commits from https://github.com/ppy/osu-framework/pull/2823. Merge that first.
> Fix android native libraries not being copied correctly on first build

- osu.Framework.Tests/Primitives/QuadTest.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/Primitives/Quad.cs
- osu.Framework/Graphics/Vector2Extensions.cs
Fixes pixel count being wholly incorrect on the transition into songselect (sheared buffered wedge).
Uses the same calculations as in the FTB pass. I've left the `Area` property as a ground-truth for unit testing.
Performance:
```diff
|           Method |       Mean |     Error |    StdDev |
|----------------- |-----------:|----------:|----------:|
- |             Area | 162.900 ns | 1.4873 ns | 1.3912 ns |
- | ConservativeArea |  60.541 ns | 0.8097 ns | 0.7178 ns |
+ |             Area |   4.551 ns | 0.0609 ns | 0.0540 ns |
```
Breaking changes:
It was inaccurate for certain `Quad`s. Use `Area` as a replacement.
> Fix Quad.ConservativeArea being inaccurate in some cases

- osu.Framework/Testing/DrawFrameRecordingContainer.cs
> Limit DrawVisualiser scope when clicking in tests

- osu.Framework/Resources/Shaders/sh_Utils.h
- Fixes blending potentially dividing by zero by returning `vec4(0)` immediately on `finalAlpha == 0`. (thanks to @bdach for pointing the issue)
|:--------------:|:-----------------:|
| ![dotnet_SwZPXHw0SM](https://user-images.githubusercontent.com/22781491/65332199-e1370e00-dbc6-11e9-900f-9a011d1544bd.png) | ![dotnet_pTY3f3roo4](https://user-images.githubusercontent.com/22781491/65332212-e6945880-dbc6-11e9-9aff-9e2fcd6ebd7a.png) |
Closes ppy/osu#5885
> Fix blending method potentially dividing by zero

- osu.Framework/Testing/Drawables/TestGroupButton.cs
Seems to be an annoying logic with namespaces that contain one test only as discussed.
|-----|-------|
| ![dotnet_6Q08PPLYrC](https://user-images.githubusercontent.com/22781491/65400707-72c39d00-ddcc-11e9-8f90-87b0862da87c.png) | ![dotnet_FAYC89Dk43](https://user-images.githubusercontent.com/22781491/65400711-7d7e3200-ddcc-11e9-99a0-90105805d27e.png) |
> Always show test group headers

- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Input/UserInputManager.cs
1. From my experimentation, o!f almost never goes above 50 vertices per draw, and every single draw uses a new VBO. osu! is even lower at <30 vertices per draw. So 50 is a good value but I picked 100 vertices for a "safe" value.
2. I found that using 8 as the minimum amount of children resulted in a slightly reduced number of VBO binds:
| old | new |
| --- | ---- |
| ![image](https://user-images.githubusercontent.com/1329837/65868166-c036a000-e3b2-11e9-87a4-470a854321b3.png) | ![image](https://user-images.githubusercontent.com/1329837/65868174-c3319080-e3b2-11e9-8aec-e90f59032d9a.png) |
The next step I believe is to implement mapped buffers which we can write to unsynchronised, and re-use the same VBO for subsequent `Draw()` calls.
This improves performance a tad (centipede is now mostly …
> Adjust vertex batching for modern-day use cases

- osu.Framework/Graphics/Batches/VertexBatch.cs
- `currentVertex` + `currentIndex` were confusing.
- `lastVertex` was unnecessary since every `Draw()` starts from the 0-th index.
> Refactor VertexBatch for readability

- osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
If the available view size of the `ScrollContainer` is larger than the `DrawSize` of the target `Drawable`, it is feasible that the wrong extremity will be scrolled into view, causing incorrect behaviour when the scroll view is restored to a larger size.
In such cases, the minimum extremity should be preferred to provide stable behaviour on resize (and arguably preferred beahviour even before resize).
This is mainly to fix the case where a `ScrollIntoView` is issues while a `ScrollContainer` is zero-size (as seen in osu!'s `PlaylistOverlay`).
> Fix ScrollIntoView not always working as expected

- osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
- osu.Framework/Timing/InterpolatingFramedClock.cs
Should fix test failures in the .net core 3.0 branch: https://ci.appveyor.com/project/peppy/osu-framework/builds/28006494
> Fix interpolating clock not considering rate in error allowance

- osu.Framework/Platform/HeadlessGameHost.cs
Will fix https://ci.appveyor.com/project/peppy/osu/builds/28032676/tests
This was causing interpolation to go out of control after the recent `InterpolatingFramedClock` change (https://github.com/ppy/osu-framework/pull/2880).
> Fix fast clock having a huge rate

- build.ps1
- build.sh
Fixes #2888
Mostly a revert back for args to https://github.com/ppy/osu-framework/tree/d246f862bd3289b05ce118042d245b88186a4b7f . There's a few changes like the script not being passed in, though.
> Fix build scripts not passing arguments to cake

- osu.Framework.Tests/Primitives/TriangleTest.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/Primitives/Triangle.cs
Closes #2846.
This is basically a copy of what was done in #2842.
Benchmark results:
```
|         Method |      Mean |     Error |    StdDev |
|--------------- |----------:|----------:|----------:|
|   Conservative |  1.377 ns | 0.0058 ns | 0.0055 ns |
|        AreaOld | 46.166 ns | 0.1231 ns | 0.1028 ns |
|        AreaNew |  3.445 ns | 0.0166 ns | 0.0156 ns |
```
This PR also implements `IConvexPolygon` and `IEquatable<Triangle>` for the Triangle struct.
Breaking changes:
Use `Triangle.Area` instead.
> Use the shoelace formula for Triangle.Area

- appveyor_deploy.yml
- appveyor_native_deploy.yml
Somehow got this back-to-front. Using preview still uses the wrong msbuild version.
> Don't use preview image for deploys

- BannedSymbols.txt
- osu.Framework.Tests/Visual/Bindables/TestSceneBindableNumbers.cs
- osu.Framework/Bindables/Bindable.cs
- osu.Framework/Bindables/BindableBool.cs
- osu.Framework/Bindables/BindableNumber.cs
- osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
- osu.Framework/Graphics/Shaders/Uniform.cs
- osu.Framework/Graphics/Sprites/IconUsage.cs
- osu.Framework/Graphics/Sprites/SpriteIcon.cs
- osu.Framework/Graphics/UserInterface/BasicSliderBar.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Localisation/LocalisedString.cs
- osu.Framework/Testing/Drawables/Steps/StepSlider.cs
- osu.Framework/Testing/TestScene.cs
- osu.Framework/osu.Framework.csproj
I'd rather call these "violation fixes" instead of "improvements".
`BindableNumber` violates some usage of exceptions, and they shouldn't be thrown ever.
The non-generic calls are harmful to both performance and architecture.
I'm a bit aggressive on this, and introducing banned API analyzer.
This is a technically **breaking change**, including:
- Generic constraints on some types are changed. Consumers are assumed to only construct them with primitive numbers, which always satisfy the constraints.
- `BindableNumber` can no longer be derived by consumer. No one should ever derived them though.
I assume it can't actually break anything.
> Get rid of some non-generic/boxing calls

- osu.Framework.iOS/Input/IOSTextInput.cs
- osu.Framework/Graphics/Primitives/RectangleF.cs
- osu.Framework/Graphics/Primitives/RectangleI.cs
- osu.Framework/Lists/ComparisonComparer.cs
- osu.Framework/Lists/SortedList.cs
- osu.Framework/Lists/WeakList.cs
- osu.Framework/osu.Framework.csproj
Mentioned when walking classes.
- Classes `RectangleF`, `RectangleI`
Seems xml doc get copied when copied from `System.Drawing`.
Note: The rectangle classes are included in `netstandard` now. Should we use them instead?
- Class `ComparisonComparer`
Overlapped by the standard type. The corresponding type exists from .NET Framework 4.5.
- Class `WeakList`
Nested type inherits type parameter from the outer type. I mentioned it long time ago in #15.
- Class `IOSTextInput`
Empty event avoids compiler warning CS0067.
- Package `System.Drawing.Common`
Not used, and causing IntelliSense reporting error in VS.
> Several class designation fixes

- osu.Framework.Android/AndroidGameActivity.cs
In a Xamarin Android App, the visibility of the status bar and the navigation bar can be changed by changing the value of `Window.DecorView.SystemUiVisibility` (see https://docs.microsoft.com/fr-fr/xamarin/android/user-interface/controls/navigation-bar).
This PR introduces the `UIVisibilityFlags` property in `AndroidGameActivity` which allows setting the visibility of the status & navigation bar in the form of bitwise flags.
Firing up the on-screen keyboard may cause the UI visibility flags to be altered to show the navigation (and or the status bar) while interacting with keyboard. An event handler tracking UI visibility flags changes has been added to return UI visibility flags to their original value once interaction with keyboard is finished.
> Introduce UIVisibilityFlags in AndroidGameActivity

- osu.Framework.Tests/Visual/Containers/TestSceneVisibilityContainer.cs
- osu.Framework/Graphics/Containers/VisibilityContainer.cs
If a `VisibiltyContainer` was visible at the point of checking `ShowHidden` (`LoadCompleteAsync`), but then changed to `Hidden` in a parent's `LoadComplete` method, the `UpdateState` call would not be fired and the initial display state would be incorrect.
> Fix visibility container potentially getting in wrong visual state

- osu.Framework.Tests/Containers/TestSceneContainerState.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Previous code was incorrectly decrementing the count value in the `for` loop, meaning some children could not be updated in the immediate frame they are expected to be when other drawables are removed in the same frame.
> Fix some children potentially not getting state updates due to incorrect iteration

- osu.Framework/osu.Framework.csproj
Seems our package just changed `lib/net40` to `lib/netstandard2.0`; effectively a workaround for `NU1701`.
Now official package contains `netstandard2.0` target from 1.0.0. We can move to it.
The risk should be low. I don't think they would ever make breaking changes after the latest version of 0.x.
> Update Microsoft.Diagnostics.Runtime to latest official package

- osu.Framework.Tests/Localisation/ThreadCultureTest.cs
Fixes for issues spotted in tests added as part of #2895.
This PR introduces two, partly orthogonal fixes for issues that could cause test failures for the thread culture setting functionality.
A test failure was spotted while locally running tests added in #2895 for setting culture loaded from the framework config, pertaining specifically to the invariant culture test. The desired invariant culture was being silently overwritten with the system culture.
The cause of this scenario was detected to be related to the way headless tests are ran.
1. When `GameHost` starts, it loads in default settings, as specified by `GetFrameworkConfigDefaults()`, and merges them with framework settings read from the `framework.ini` file. The invariant culture is used as the default locale, so at this point …
> Fix thread culture setting tests

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
- osu.Framework/Threading/GameThread.cs
Fixes #696.
The true issue here was cross-threaded access of `TimeSlept` and `ElapsedFrameTime`, which are updated on a different thread for all but the `Update` display.
> Fix negative frame time on frame time display

- osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
- osu.Framework/Input/MouseButtonEventManager.cs
Even if a movement frame has enough movement to also be considered for a valid drag, it would not be fired, only firing a DragStart.
> Fix first drag event potentially not being triggered 

- osu.Framework.Tests/Visual/Input/TestSceneClickLenience.cs
- osu.Framework/Graphics/Containers/OverlayContainer.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseButtonEventManager.cs
Changes `ScrollContainer` to no longer block clicks from contained items when a drag is only activated in the incorrect axis.
Also exposes `DragBlocksClick` to allow elements to avoid blocking clicks during a drag (used by `OverlayContainer`).
> Add DragBlocksClick and more correctly handle off-axis drags

- osu.Framework/Graphics/Containers/ScrollContainer.cs
Any reasons why it's not already the case? [`MouseButtonEventManager.EnableDrag`](https://github.com/ppy/osu-framework/blob/b5c05a5422e4f3cda45e99baa32428d9c9815c73/osu.Framework/Input/MouseButtonEventManager.cs#L41) already decides whether a button can drag or not (thanks to #1678). Middle mouse button for dragging things around is common in lots of software (FL Studio for example).
Right now even if you make an inherited `InputManager` with enabled dragging on the middle mouse button, dragging to scroll still won't work because `ScrollContainer` is hard-coded to work only with the left mouse button. This means that a user cannot change this behaviour without re-implementing `OnDragStart` and `OnMouseDown` functions from scratch for both `ScrollContainer` and `ScrollbarContainer`, and …
> Allow all buttons to drag in scroll container

- osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneCheckboxes.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
- osu.Framework.Tests/Visual/UserInterface/TestUIComponentsWithCurrent.cs
- osu.Framework/Bindables/BindableWithCurrent.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
- osu.Framework/Graphics/UserInterface/Checkbox.cs
- osu.Framework/Graphics/UserInterface/CircularProgress.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
Due to these classes storing a reference to the current bind target, on disposal they would forcefully unbind any bound bindables to that reference (due to automatically disposal logic in `UnbindAllBindablesSubtree`).
> Fix IHasCurrent UI components potentially unbinding unrelated bindables

- osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs
- osu.Framework/Testing/MenuTestScene.cs
- Moves menu testing helper functions and `MenuStructure` to a base test scene class.
- This is a dependency for testing different types of menus easily.
> Move menu testing helper functions and structure to a base class

- osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
Completely refactors `TestSceneContextMenu` to test specific scenarios / interactions, rather than hacking around testability shortcomings to write more tests.
I've added a few failing test cases, which are ignored for unit testing purposes (they fail visual tests). I'll make issues for these.
> Refactor context menu tests

- osu.Framework/Bindables/AggregateBindable.cs
- osu.Framework/Bindables/Bindable.cs
- osu.Framework/Bindables/BindableNumber.cs
- osu.Framework/Bindables/IBindable.cs
- osu.Framework/Bindables/IBindableNumber.cs
- osu.Framework/Bindables/ICanBeDisabled.cs
- osu.Framework/Extensions/ExceptionExtensions/ExceptionExtensions.cs
- osu.Framework/Extensions/PolygonExtensions/ConvexPolygonExtensions.cs
- osu.Framework/Graphics/Audio/WaveformGraph.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
- osu.Framework/Graphics/Sprites/FontAwesome.cs
- osu.Framework/Graphics/Textures/Texture.cs
- osu.Framework/Graphics/TransformableExtensions.cs
- osu.Framework/Graphics/Transforms/TransformCustom.cs
- osu.Framework/Graphics/Transforms/TransformSequence.cs
- osu.Framework/Input/Bindings/KeyBinding.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseButtonEventManager.cs
- osu.Framework/Input/StateChanges/ButtonInput.cs
- osu.Framework/Input/States/ButtonStates.cs
- osu.Framework/Text/MultilineTextBuilder.cs
- osu.Framework/Timing/FramedClock.cs
- osu.Framework/osu.Framework.csproj
Rider doesn't colorize tooltip, make users not realizing that reference is broken. To be honest and surprisingly, no colorized tooltip is one of the biggest reasons make me not willing to use Rider.
Every reference element in documentation should be able to be precisely navigated via F12.
> Fix bad references in xml doc

- SampleGame.Android/Properties/AndroidManifest.xml
- SampleGame.Android/SampleGame.Android.csproj
- SampleGame/SampleGame.csproj
- osu.Framework.Android.props
- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework.Tests.Android/Properties/AndroidManifest.xml
- osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
- osu.Framework/osu.Framework.csproj
Framework has more dependents than game repo. Should properly notify them, and update wiki when bumped.
The System.Runtime.InteropServices/System.Net.Http packages are more about providing opt-in updates to .NET Framework. It doesn't provide any asset for Xamarin and .NET Core.
System.Reflection.Emit.* are newly included in .NET Standard 2.1 .
> Move to .NET Standard 2.1 at framework side

- osu.Framework/Configuration/FrameworkConfigManager.cs
- osu.Framework/Configuration/FrameworkDebugConfig.cs
- osu.Framework/Development/DebugUtils.cs
- osu.Framework/Platform/GameHost.cs
As seen in https://github.com/ppy/osu/issues/6795, some users are turning on performance logging and leaving it on. This is not intended, as it adds a noticeable overhead to retrieve and write the stack traces to disk.
This change allows the setting to reset each game execution, rather than be saved to a user's configuration file.
> Move performance logging setting to debug config

- osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
- osu.Framework/Graphics/Lines/SmoothPath.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
- osu.Framework/Graphics/Textures/DisposableTexture.cs
- osu.Framework/Graphics/Textures/LargeTextureStore.cs
- osu.Framework/Graphics/Textures/TextureStore.cs
- osu.Framework/Graphics/Textures/TextureWithRefCount.cs
Between the `Available` check of `TextureStore` and the subsequent construction of the new `TextureWithRefCount`, no lock was held and `Available` could've been set to false in the mean time (disposing the texture). This could happen because `Available` is set by the draw thread.
This PR fixes this by ensuring that the entire `LargeTextureStore.Get()` method is locked until the increment happens, and that the disposal is locked on the same object until the decrement + disposal happens.
This fixes the case where exiting and re-entering song select rapidly causes backgrounds to disappear.
> Fix TextureWithRefCount thread races

- osu.Framework.Tests/MathUtils/TestInterpolation.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneEasingCurves.cs
- osu.Framework/MathUtils/Interpolation.cs
Resolves #3015.
`Elastic` and `Expo` curves due to the formulae used would not stop exactly at 0 or 1 at time 0 or 1, as pointed out in tests in c84b164. Resolve this discrepancy by introducing small linear factors to the appropriate easing curves.
The linear factors offset the differences at the extremities that were wrong, and then fade to 0 at the other ends which were correct. A special case are the `InOut` easings, in which the factor will be fully included at both ends and then fade out linearly to 0 at `time = 0.5`.
Since the adjustments involved are minuscule (less than 4 significant decimal places), they should not be noticeable during transitions, but fix the jumping at extreme points seen before.
Aside from the unit tests originally written by @peppy (sorry for taking co-credit …
> Fix interpolation extremities on exponential and elastic curves

- osu.Framework.Android/AndroidGameView.cs
This is a temporary targeted suppression for an outstanding Mono issue causing unobserved exceptions to pop up after cancellation of web requests (see ppy/osu#6264 and upstream issues: mono/mono#15462 and xamarin/xamarin-android#2159). Switching backends like in ppy/osu#6899 does not work for unknown reasons, and the legacy TLS provider is slated for removal anyway (see mono/mono#17391).
The suppression can hopefully be reverted when mono/mono#17393 makes its way into a release and gets integrated into Xamarin at xamarin/xamarin-android#3753.
The errors will still make their way into the logs, as per the current suppression logic:
https://github.com/ppy/osu-framework/blob/7f7dd04779bfa45d33d69a1c5599c894a9c64d33/osu.Framework/Platform/GameHost.cs#L228-L241
Therefore osu!-side there still …
> Suppress MobileAuthenticatedStream exceptions

- osu.Framework/Graphics/Textures/TextureLoaderStore.cs
- osu.Framework/Graphics/Textures/TextureUpload.cs
This is just a code quality thing, which doesn't affect any normal usage of the framework. Updates the deprecated method of texture loading to use the new Stbi pathway, and adds a note about it bypassing platform level implementations.
> Move texture loading logic to be more accessible

- osu.Framework.Tests/IO/FontStoreTest.cs
- osu.Framework/Game.cs
- osu.Framework/IO/Stores/FontStore.cs
- osu.Framework/IO/Stores/GlyphStore.cs
- osu.Framework/IO/Stores/RawCachingGlyphStore.cs
- osu.Framework/Testing/TestBrowser.cs
Allowing for better testing of different caching / parsing algorithms. `GlyphStore` can also now be used to load with zero caching, as a baseline.
This also does some clean-up on `RawCachingGlyphStore` for readability purposes.
> Move common logic to base implementation of GlyphStore

- osu.Framework.Tests/Audio/AudioManagerWithDeviceLoss.cs
- osu.Framework.Tests/Audio/AudioThreadTest.cs
- osu.Framework.Tests/Audio/DeviceLosingAudioTest.cs
- osu.Framework.Tests/Audio/DevicelessAudioTest.cs
- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Audio/Track/TrackBass.cs
Fixes https://github.com/ppy/osu/issues/1302
Fixes https://github.com/ppy/osu/issues/2598
Fixes https://github.com/ppy/osu/issues/5866
Supercedes https://github.com/ppy/osu-framework/pull/1165
This is my attempt at fixing this long standing issue.
- Prioritizes the preferred audio device when initializing devices, falling back gracefully to system default on fail, and then "No sound" device provided by Bass itself as last resort.
- Resumes track automatically when falling back to "No sound", because Bass will stop the track for some reason.
I only have tested this by disabling all audio devices, unplugging them and using service manager to stop the audio service.
There are no unit tests included because I don't know how to reproduce an environment with no or broken audio devices in a unit …
> Fix audio not working when no audio devices are present

- osu.Framework/Platform/Linux/LinuxGameHost.cs
- osu.Framework/Platform/Linux/Native/Library.cs
This reverts commit 6b8ff8a1809286ada21b541defafe74049c478c0. which fixes https://github.com/ppy/osu/issues/7018
> Fix startup crash regression on Linux

- osu.Framework/Graphics/Containers/CircularContainer.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Prevents regressions. See: https://github.com/ppy/osu-framework/pull/3020, https://github.com/ppy/osu-framework/issues/3047
> Change CornerExponent to default to 2

- osu.Framework/Platform/MacOS/Native/Cocoa.cs
- osu.Framework/Platform/MacOS/Native/NSStringEncoding.cs
Replaces the reflected osuTK calls in `MacOS.Native` with real implementations.  Required as part of dropping osuTK.  Implementations loosely borrowed from osuTK.
Note that the `FoundationLibrary` reference is not required and has been removed.
Related to #2448
> Replace macOS native osuTK reflection

- osu.Framework/Game.cs
- osu.Framework/Testing/TestScene.cs
- osu.Framework/Threading/AudioThread.cs
It may be possible for the audio thread to exit before tracks in the game get disposed. One such example is `TestScene`, which explicitly exits before disposing the host, however there isn't a reason why this couldn't occur via a normal game startup.
This is particularly dangerous in the case of `OsuTestScene`, which stops a track during its disposal. In this case, the `Stop()` event gets enqueued to the `AudioComponent`, then `Dispose()` gets invoked (stopping all further actions from getting enqueued), but the audio thread isn't running so the `Stop()` event just hangs endlessly.
In short:
```csharp
host.Run(game)
host.Exit()
host.Dispose() // Disposal of the host triggers a disposal of all drawable components
testScene.Dispose() // Invoked by the host disposal
track.Stop() // Invoked …
```
> Fix audio thread disposal ordering

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
Closes #3069.
Regressed in https://github.com/ppy/osu-framework/pull/2902.
> Fix LogOverlay causing a null reference on display via shortcut key

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
- osu.Framework/Screens/ScreenStack.cs
Can lead to unintended failure if doing initialisation in `LoadComplete` that is expected to be completed before `OnEntering` is hit.
> Fix OnEntering being called before drawable is loaded

- osu.Framework/Testing/DynamicClassCompiler.cs
Without this, some classes that use C# 8 things cannot be recompiled.
> Always use latest c# version for dynamic compilation
