ppy/osu-framework

- osu.Framework/Graphics/Batches/VertexBatch.cs
> Fix vertex buffers overflowing too early

- osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
- osu.Framework/Game.cs
- osu.Framework/Input/FrameworkActionContainer.cs
- osu.Framework/Platform/GameHost.cs
Fixes https://github.com/ppy/osu-framework/issues/2671
Also makes `FrameworkActionContainer` internal.
> Fix FrameworkActions not being handled in some scenarios

- osu.Framework/Audio/Sample/SampleBass.cs
- osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
- osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Adds tracking of known native allocations
- Samples
- RenderBuffers
- FrameBuffers
- VertexBuffers
- Textures
> Add native memory stats

- osu.Framework/Platform/GameHost.cs
Was an incorrect default (for windows).
> Remove Shift-Delete platform binding

- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Tried to make a test case but cannot reproduce correctly.
> Fix DelayedLoadUnloadWrapper potentially entering wrong optimisation mode

- osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
> Fix renderbuffers not attaching correctly

- osu.Framework.Tests/Visual/Containers/TestSceneContainerState.cs
- osu.Framework/Allocation/AsyncDisposalQueue.cs
> Fix AsyncDisposalQueue potentially causing deadlocks

- README.md
For now we are not packaging pre-built libraries for linux as they are regularly distribution dependent.
> Add note to README about ffmpeg requirement on linux

- osu.Framework/Graphics/UserInterface/Checkbox.cs
Required for https://github.com/ppy/osu/issues/5724.
> Expose method on checkbox that is fired when a user makes a change

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TabItem.cs
- Alternative to #2740.
- Resolves ppy/osu#5448.
- Regressed in #2431.
May add some further testing, just PRing for visibility.
>  Fix TabControl overflow tabs getting stuck after hidden

- osu.Framework.Tests/Visual/Drawables/TestSceneBorderSmoothing.cs
- osu.Framework/Graphics/Containers/Container.cs
- osu.Framework/Resources/Shaders/sh_TextureRounded.fs
- osu.Framework/Resources/Shaders/sh_Utils.h
> Fix incorrect colour sampling in border smoothing region

- osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
- osu.Framework/Graphics/Cursor/IHasAppearDelay.cs
- osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
- osu.Framework/Graphics/Cursor/IHasTooltip.cs
- osu.Framework/Graphics/Cursor/ITooltip.cs
- osu.Framework/Graphics/Cursor/ITooltipContentProvider.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
Required to support usage patterns like https://github.com/ppy/osu/pull/5036.
Better defines content handling but doesn't break support for existing usages.
> Improve tooltip container to better support custom tooltips

- osu.Framework.Tests/Visual/Drawables/TestSceneBorderSmoothing.cs
This reveals new breaking scenarios (as can be seen on osu! checkboxes).
> Add ability to adjust alpha on test

- osu.Framework/Audio/Sample/SampleBass.cs
> Fix SampleBass potentially adding invalid memory pressure

- osu.Framework/Audio/Sample/SampleStore.cs
- osu.Framework/Audio/Track/ISampleStore.cs
> Expose SampleManager's PlaybackConcurrency

- osu.Framework/Input/UserInputManager.cs
Closes https://github.com/ppy/osu/issues/5874.
Reproduces on windows with raw input *on*.
> Ignore clicks outside the game window

- osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextMaxWidth.cs
- osu.Framework/Graphics/Sprites/SpriteText.cs
Should help with https://github.com/ppy/osu/pull/6023
> Implement MaxWidth for SpriteText

- osu.Framework/Audio/Track/TrackBass.cs
> Fix silent tracks after changing audio device

- SampleGame.Android/SampleGame.Android.csproj
- osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
The include of the native libraries happens automatically thanks to https://github.com/ppy/osu-framework/pull/2824
> Remove not needed native library includes.

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
- osu.Framework/Screens/ScreenStack.cs
Resolves https://github.com/ppy/osu/issues/6173.
Requires a thorough review. I will take a second look at this before final merge.
> Fix blocking exit in an intermediary screen during MakeCurrent failing to resume

- osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
Due to an unfortunately assert mishap, these tests were not actually working until now.
> Fix ScrollTo tests not actually testing

- Directory.Build.props
- SampleGame.iOS/SampleGame.iOS.csproj
- appveyor.yml
- appveyor_deploy.yml
- appveyor_native_deploy.yml
- build/build.cake
- osu.Framework.Tests.iOS/osu.Framework.Tests.iOS.csproj
- osu.Framework.iOS.props
- osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
Originally based on #2896, but made orthogonal now.
> Build Xamarin components with VS2019

- osu-framework.sln.DotSettings
- osu.Framework.Tests/Clocks/TestClock.cs
- osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
- osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
- osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
- osu.Framework.Tests/Threading/SchedulerTest.cs
- osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
- osu.Framework.Tests/Visual/Containers/TestSceneSizing.cs
- osu.Framework.Tests/Visual/Containers/TestSceneVisibilityContainer.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
- osu.Framework/Caching/Cached.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/IO/Network/JsonWebRequest.cs
- osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
- osu.Framework/Platform/Linux/LinuxGameWindow.cs
- osu.Framework/Statistics/GlobalStatistic.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
- osu.Framework/Testing/Dependencies/CachedNullableProvider.cs
- osu.Framework/Testing/Dependencies/CachedStructProvider.cs
- osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
various small refactorings related to language features usage
> Use auto properties over private-field backings where possible

- osu.Framework/Testing/TestBrowser.cs
Fixes any ungrouped tests being in individual folders, duplicating all content.
> Group ungrouped tests

- osu.Framework.Tests/Visual/Drawables/TestSceneFillModes.cs
- osu.Framework.Tests/Visual/Layout/TestSceneFillFlowContainer.cs
Triggers an inspection in inspectcode 2019.3 (EAP).
> Remove unused classes

- osu.Framework.Tests/Visual/Platform/TestSceneResourceStores.cs
See https://github.com/ppy/osu-framework/pull/2933/files#r340339133.
> Fix one more failing resource retrieval test

- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
- osu.Framework/Timing/ThrottledFrameClock.cs
> Refactor throttled frame time display

- osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Automatically disables when an exception is hit. Closes https://github.com/ppy/osu-framework/issues/2970.
> Catch exceptions thrown by BackgroundStackTraceCollector

- osu.Framework/Graphics/Containers/ScrollContainer.cs
Needs more thinking to work correctly with ContextMenuContainer.
> Revert breaking scroll container changes

- osu-framework.sln.DotSettings
> Lower severity of suspicious type conversion inspections

- osu.Framework.Tests/Visual/UserInterface/TestSceneUnclosableMenu.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
> Allow menu items to not close menus on action click

- osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
- osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
- osu.Framework/Graphics/Cursor/IHasContextMenu.cs
Fixes https://github.com/ppy/osu-framework/issues/2990
Resolves https://github.com/ppy/osu-framework/issues/2991
Prereqs:
> Implement context menu pass-through + blocking

- osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
- osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs
- osu.Framework/Extensions/MatrixExtensions/MatrixExtensions.cs
- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Lines/Path_DrawNode.cs
- osu.Framework/Graphics/Primitives/Line.cs
- osu.Framework/Graphics/Primitives/RectangleF.cs
- osu.Framework/Graphics/Sprites/SpriteIcon.cs
- osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
- osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
- osu.Framework/Graphics/Vector2Extensions.cs
- osu.Framework/Input/InputResampler.cs
- osu.Framework/Physics/RigidBodyContainer.cs
Looks much cleaner and should even be a bit faster.
> Use .NET Standard 2.1 Math/MathF functions

- osu.Framework.Tests/IO/FontStoreTest.cs
- osu.Framework.Tests/TemporaryNativeStorage.cs
Fixes a common gotcha of this class.
> Add support for TemporaryNativeStorage to create directory if non-existing

- osu.Framework.Tests/Audio/DevicelessAudioTest.cs
Had a feeling I missed one..
https://ci.appveyor.com/project/peppy/osu-framework/builds/29163136/tests
> Fix one remaining case of incorrect audio testing

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
Caught both @smoogipoo and I off, so worth documenting for future travellers.
> Add link to wiki explaining LongRunningLoad exception

- osu.Framework.Tests/Bindables/BindableListTest.cs
- osu.Framework/Bindables/BindableList.cs
Closes https://github.com/ppy/osu-framework/issues/3062.
> Fix multiple enumeration in BindableList.AddRange

- osu.Framework/Game.cs
- osu.Framework/Graphics/Visualisation/LogOverlay.cs
> Fix debug log overlay setting not working correctly

- osu.Framework/IO/Stores/RawCachingGlyphStore.cs
- osu.Framework/IO/Stores/ResourceStore.cs
Closes https://github.com/ppy/osu-framework/issues/3078
Should be tested against osu!, due to the removed try-catch.
> Fix GlyphStore finalizer potentially nullref-ing

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
Ensures we test the exception we are intending to.
https://ci.appveyor.com/project/peppy/osu-framework/builds/29391166/tests
> Avoid incorrect exception being tested in screen test

- osu.Framework.Tests/Visual/Audio/TestSceneLoopingSample.cs
> Enable disabled audio tests

- osu.Framework/Bindables/BindableNumberWithCurrent.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
> Fix SliderBar's Current implementation

- osu.Framework.Tests/Bindables/BindableNumberTest.cs
- osu.Framework/Bindables/BindableNumber.cs
> Make BindableNumber able to handle more types

- osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
Ref: https://github.com/ppy/osu-framework/pull/3017/files#diff-891c30cfbc644d614d33fa9ae98f57f3L23-R23
> Revert vertex sizeof marshalling

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
https://ci.appveyor.com/project/peppy/osu-framework/builds/29471020/tests
> Fix potential failure in screen test

- osu.Framework/Platform/NativeStorage.cs
https://ci.appveyor.com/project/peppy/osu/builds/29482220
> NativeStorage should not throw when path does not exist

- osu.Framework/Platform/GameHost.cs
Fixes focus being pulled away while running tests.
> Fix nunit starting up window in headless mode

- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/HeadlessGameHost.cs
Toolkit required to initialise the window on macOS.
> Fix toolkit not initialising for headed game hosts

- osu.Framework/Bindables/BindableNumber.cs
See build warnings in https://ci.appveyor.com/project/peppy/osu-framework/builds/29516377
> Refactor BindableNumber to reduce compiler warnings

- .editorconfig
- .vscode/launch.json
- Directory.Build.props
- osu.Framework.Android.props
- osu.Framework.Benchmarks/Program.cs
- osu.Framework.Benchmarks/Properties/launchSettings.json
- osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
- osu.Framework.iOS.props
Add VS/VSC launcher arguments from my previous pushed branch.
Fix build warnings.
> Minor fixes for benchmark project

- osu.Framework/Graphics/Video/VideoDecoder.cs
Closes https://github.com/ppy/osu-framework/issues/3125.
> Fix decode loop potentially running after stream disposal

- .editorconfig
- .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/Benchmarks.xml
- .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/SampleGame.xml
- .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/VisualTests.xml
- .vscode/launch.json
- README.md
- SampleGame.Desktop/SampleGame.Desktop.csproj
- build/build.cake
- global.json
- osu-framework.sln.DotSettings
- osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
- osu.Framework/Graphics/Containers/FillFlowContainer.cs
- osu.Framework/Graphics/Vector2Extensions.cs
- osu.Framework/MathUtils/Clipping/ConvexPolygonClipper.cs
- osu.Framework/Text/TextBuilder.cs
- osu.Framework/Text/TruncatingTextBuilder.cs
ppy/osu#7208 and ppy/osu#7304 .
Not updating the libraries because 3.1 doesn't provide any related API.
> .NET Core 3.1 at framework side

- osu.Framework/Graphics/Drawable.cs
- osu.Framework/MathUtils/Validation.cs
It's newly included in .NET Standard 2.1.
> Replace custom IsFinite(float) with netstandard one

- osu.Framework.Tests/Lists/TestEnumerableExtensions.cs
- osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
Closes https://github.com/ppy/osu/issues/7349.
> Fix GetCommonPrefix extension method failing on empty enumerable source

- osu.Framework/Graphics/Drawable.cs
Found it while I was working on something else, no harm in simplifying it :P
> Remove redundant logic in Drawable

- osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
- osu.Framework.Tests/osu.Framework.Tests.csproj
Reported at https://youtrack.jetbrains.com/issue/RIDER-37769
> Downgrade NUnit adapter to fix discovery issue

- osu.Framework.Tests/Lists/TestWeakList.cs
- osu.Framework/Lists/WeakList.cs
Pathway wasn't tested :/
Would now cause unbind + re-bind to bindables to fail.
> Fix weak list incorrectly containing removed objects

- osu.Framework/Graphics/Video/VideoDecoder.cs
- osu.Framework/Lists/WeakList.cs
Minor cleanups that I found while browsing through the files.
> Minor cleanup

- README.md
GDEdit is a third-party editor for the game Geometry Dash. it has tons of bells and whistles that the normal editor does not have such as: a full on Guideline Editor, Proportional Editing, Camera indicator, Live-Editing, and a whole lot more. 
If you want to learn more about the features we're going to be implementing please head over [here](https://github.com/gd-edit/GDE/blob/master/FeaturesToBeAdded.md)
Current status: `Highly in works`
<details>
<summary>Previews</summary>
<h3>Level Selection Screen</h3>
<h3>Editor screen</h3>
<h3>ID Migration Overlay</h3>
<h3>File selection Overlay</h3>
</details>
> Add GDEdit the the projects listing

- osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
Fixes https://github.com/ppy/osu/issues/7505
> Fix text boxes crashing upon trying to delete words when empty

- osu.Framework/Input/PlatformActionContainer.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
> Add Save operation to PlatformActions

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
- osu.Framework/Game.cs
- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
- osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Drawable.cs
Resolves https://github.com/ppy/osu-framework/issues/2527
Also allows unloads to happen with non-scrolling containers (e.g. if hidden by movement inside a masking area).
The following tests now pass:
Also tested with social overlay osu!-side.
> Rework DLW/DLUW to support general unloads and intersections

- osu.Framework/Input/ButtonEventManager.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/MouseButtonEventManager.cs
In preparation for other button event managers existing (keyboard, joystick, keybindings).
> Abstract general implementation of button event managers

- osu.Framework.Tests/Input/JoystickInputTest.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/JoystickButtonEventManager.cs
> Implement per-button joystick input handling

- osu.Framework/Input/FrameworkActionContainer.cs
> Allow using F11 to toggle fullscreen

- osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
- osu.Framework.Tests/Visual/Input/TestSceneInputQueueChange.cs
- osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneButton.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
- osu.Framework/Testing/ManualInputManagerTestScene.cs
- osu.Framework/Testing/MenuTestScene.cs
Closes https://github.com/ppy/osu-framework/issues/2909.
> Fix ManualInputManager's initial cursor position not being deterministic

- osu.Framework/Testing/TestBrowser.cs
Via NUnit docs (https://nunit.org/docs/2.5/setup.html):
> NUnit will call base class SetUp methods before those in the derived classes.
Before:
After:
In invocation order. Where in this case `SetUp()` comes from `ManualInputManagerTestScene`.
> Fix incorrect setup order during visual tests

- osu.Framework/Testing/TestBrowser.cs
> Remove any common test method prefix in test browser display

- osu.Framework/Input/InputManager.cs
Fixes on-screen log spam that is mostly useless.
> Don't log spammy input events to debug log

- osu.Framework/Screens/ScreenStack.cs
It is a top-level component and should provide a sane default.
> Make ScreenStack relative sized by default

- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
Closes https://github.com/ppy/osu/issues/7447
> Call glFinish on macOS even when vsync is disabled

- osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
> Fix adding a transform in the past from a future vantage point potentially getting incorrect StartValue

- osu.Framework/Input/Events/ScrollEvent.cs
- osu.Framework/Input/StateChanges/Events/MouseScrollChangeEvent.cs
- osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs
Was unclear (https://github.com/ppy/osu/pull/7807#discussion_r379108025).
> Add xmldoc for precision / scrolling events

- osu.Framework.Tests/Visual/Testing/TestSceneIgnore.cs
- osu.Framework/Testing/TestBrowser.cs
> Handle IgnoreAttribute in TestBrowser

- osu.Framework.Tests/Audio/DevicelessAudioTest.cs
As seen [here](https://ci.appveyor.com/project/peppy/osu-framework/builds/30870875)
> Fix potential test failure due to not waiting long enough on track start

- osu.Framework.Tests/Bindables/BindableListTest.cs
- osu.Framework/Bindables/BindableList.cs
- osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Fixes https://github.com/ppy/osu/issues/7860
Prereqs:
Helps with implementing / solidifying the implementation of `RearrangeableListContainer`.
> Add method to move items within a BindableList

- osu.Framework/Graphics/Video/VideoDecoder.cs
In testing this seems fine. Setting back to sane value pending further feedback from @Pizzabelly
> Restore video texture buffer count to 3 for now

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Can't add test because very hard o test disposal happening in a very internal place.
> Fix exception when a single component loaded via LoadComponentAsync and it is disposed during load

- osu.Framework/Game.cs
- osu.Framework/Input/FrameworkActionContainer.cs
- osu.Framework/Platform/GameHost.cs
Unsure why it was not, but it meant it didn't work on iOS etc.
> Move frame sync toggle to platform action

- osu.Framework/Platform/MacOS/Native/Cocoa.cs
Fixes https://github.com/ppy/osu/issues/7791
Can be merged separate from https://github.com/ppy/osuTK/pull/62 (or a respective nuget release of it).
> Link against libSystem rather than libdl

- osu.Framework.Android.props
- osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
- osu.Framework.iOS.props
https://github.com/ppy/osu/issues/6355
> Never use LLVM

- osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
- osu.Framework/Testing/TestBrowser.cs
* Now supports `[Repeat]`.
* Now supports `[TearDownSteps]`.
> Fix incorrect handling of TestCaseAttribute

- osu.Framework.Tests/Audio/TrackBassTest.cs
https://ci.appveyor.com/project/peppy/osu-framework/builds/31232092/tests
> Guard against potential TrackBass test failures

- osu-framework.sln.DotSettings
- osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs
Split from #3138 
Added : 
- `Color4 FromHex(string hex)` : Copied from osu's [OsuColour](https://github.com/ppy/osu/blob/master/osu.Game/Graphics/OsuColour.cs)
- `string ToHex(this Color4 color, bool forceOutputAlpha = false)`
- `Color4 ToRGB(float h, float s, float v)`
- `ToHsv(this Color4 color, out float h, out float s, out float v)`
> Extend color extension

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
Fixes https://github.com/ppy/osu-framework/issues/3169
Supersedes / closes https://github.com/ppy/osu-framework/pull/3170
> Make tab switching include the dropdown items

- osu.Framework/Game.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs
- osu.Framework/Graphics/Visualisation/TextureAtlasVisualiser.cs
- osu.Framework/Input/FrameworkActionContainer.cs
Example:
https://drive.google.com/file/d/1zXF6QIpnf0YBzQcpd6KFkbr7bXbPklOX/view?usp=sharing
> Implement a texture atlas visualisation tool

- osu.Framework/Graphics/OpenGL/GLWrapper.cs
While testing [this beatmap](https://osu.ppy.sh/beatmapsets/584787#osu/1240804) I noticed that the upload logic changes in [this PR](https://github.com/ppy/osu-framework/pull/3291) actually regress game performance during large upload batches to the point of almost losing interactivity.
This change limits the number of textures, along with the number of pixels, that can be uploaded per frame. Sane limits were added to ensure the game stays above 30fps even in intense upload scenarios.
Further tweaking can be done as we see how this performs on different hardware. The settings are also adjustable by a consumer if required.
> Add per-frame texture and pixel upload limits

- osu.Framework/Audio/AudioManager.cs
- Closes https://github.com/ppy/osu/issues/7344
The addition of `UpdatePeriod` is not required but I feel better having it there for now.
> Fix stalls in audio playback after silence

- osu.Framework/Graphics/Video/VideoSprite.cs
Defaults to `true` as a sane default for framework consumers - the expectation is they'll add the video sprite to their hierarchy and expect it to start at 0 immediately.
Note that all current usages of `VideoSprite` set custom clocks that require this parameter to be `false`.
> Add option for VideoSprite to not assume current clock time

- osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs
- osu.Framework/Resources/Shaders/sh_Video.fs
- osu.Framework/Resources/Shaders/sh_VideoRounded.fs
Fixes the issue mentioned in https://github.com/ppy/osu/pull/8167
> Fix normal video shader not respecting vertex colour

- osu.Framework/Graphics/UserInterface/CircularProgress.cs
Resolves https://github.com/ppy/osu-framework/issues/3375
> Add generic easing overload for CircularProgress.FillTo()

- osu.Framework.Tests/Audio/AudioComponentTest.cs
- osu.Framework.Tests/Audio/AudioThreadTest.cs
- osu.Framework.Tests/Visual/Audio/TestSceneLoopingSample.cs
- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Threading/AudioThread.cs
This seems to fix the double init, as well as https://github.com/ppy/osu-framework/issues/3377
Let me know if you find any problems.
> Fix change detection in audioDevices list

- osu.Framework.Benchmarks/BenchmarkScreenExtensions.cs
- osu.Framework/Screens/IScreen.cs
- osu.Framework/Screens/ScreenStack.cs
Prereqs:
```diff
|          Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
- | IsCurrentScreen | 130.3 ns |  4.31 ns | 12.65 ns | 0.0243 |     - |     - |     128 B |
+ | IsCurrentScreen | 14.70 ns | 0.032 ns | 0.027 ns |      - |     - |     - |         - |
```
> Reduce IScreen extension method allocations

- .gitignore
- .idea/.idea.osu-framework.Android/.idea/modules.xml
- .idea/.idea.osu-framework.Desktop/.idea/modules.xml
- .idea/.idea.osu-framework.iOS/.idea/modules.xml
https://github.com/JetBrains/resharper-rider-samples/blob/master/.gitignore
> Update .gitignore to support JetBrain Rider

- osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
- osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
- osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
- osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
- osu.Framework/IO/Stores/DllResourceStore.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Input/States/ButtonStates.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/Storage.cs
And some other minor string optimizations/cleanups
> Use char overloads for string methods when possible

- osu.Framework/Graphics/Video/VideoSprite.cs
Same as https://github.com/ppy/osu-framework/pull/3419. Videos can't be stopped so I'm not sure this will be seen but no harm in adding it.
> Apply process frame fix to VideoSprite

- osu.Framework.Tests/Visual/Drawables/TestSceneBlending.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneComplexBlending.cs
- osu.Framework/Graphics/Drawable.cs
I actually cannot believe we haven't encountered this yet.
> Fix blending not working through multiple parents

- osu.Framework/Graphics/Animations/Animation.cs
Didn't intend to leave this here.
> Remove left over logging

- osu.Framework/Utils/NumberFormatter.cs
Noticed due to new r# inspections.
> Fix PrintWithSiSuffix handling large negative numbers incorrectly

- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
Was checking the local edge effect before it was assigned.
> Fix edge effect exception happening one frame too late

- osu.Framework.Tests/Containers/TestSceneContainerState.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Fixes https://github.com/ppy/osu-framework/issues/3448
> Fix dead children potentially not being removed

- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
- Closes #3462 
Best effort for minimal implementation.
> Add tree connection lines to make draw visualiser easier to visually parse

- osu.Framework/osu.Framework.csproj
Fixes https://github.com/ppy/osu-framework/issues/3507
> Fix package downgrade error

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
I can't find any documentation on this stuff :/
Tested both via attribute and via automatic exclusion on `OsuGameBase` (you can use the `dynamic-compilation.log` to see if it's been excluded, the attribute takes precedence).
> Fix dynamic compilation exclusions failing via nuget package

- osu.Framework.Tests/Visual/Sprites/TestVideo.cs
I don't like this, but it's the way things are set up right now :/
> Fix video test not working

- osu.Framework.Benchmarks/BenchmarkFontLoading.cs
- osu.Framework.Tests/IO/FontStoreTest.cs
- osu.Framework.Tests/IO/TestDesktopStorage.cs
- osu.Framework.Tests/TemporaryNativeStorage.cs
- osu.Framework/Platform/NativeStorage.cs
- Closes https://github.com/ppy/osu-framework/issues/3526.
> Fix calling GetStorageForDirectory with empty string failing lookup

- .idea/.idea.osu-framework.Desktop/.idea/projectSettingsUpdater.xml
Can't find solid documentation on whether this should be ignored or not, so let's just update it for now.
> Commit autogenerated rider VCS settings update

- osu.Framework/IO/Serialization/BindableJsonConverter.cs
- osu.Framework/IO/Serialization/SortedListJsonConverter.cs
It was introduced around 2019.
Just a minor code factor update. Somehow useful when annotating NRT.
> Use strongly-typed JsonConverter

- osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
- Closes https://github.com/ppy/osu/issues/9008
> Fix hard crash on MIDI initialisation failure

- .editorconfig
New feature in Visual Studio 16.6
> Add file header in editorconfig

- osu.Framework/Allocation/CacheInfo.cs
- osu.Framework/Graphics/Sprites/FontUsage.cs
- osu.Framework/Graphics/Sprites/IconUsage.cs
- osu.Framework/IO/Stores/NamespacedResourceStore.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
`System.HashCode` and slicing.
> Use some new features in .net standard 2.1

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
This introduces the concept of an "expansion factor", which tells us how many nodes (recursively) were expanded by opening up a type. That is, the count of all direct and indirect references to a type.
The expansion factor is a function of itself and its parents, meaning that the nodes corresponding to the changed file appear at the highest factor and the test scene appears at a factor of 0.
As the two values become more spaced apart, two types of hierarchies can generally be identified:
1. The test scene hierarchy is very large (usually not the case).
2. The expansion has blown up via some other pathway, such as expansion of `Ruleset` or `WorkingBeatmap`.
The trick is to figure out an "exclusion range", a subset within the two values which allows the changed file and the test scene (the …
> Limit the number of nodes expanded for dynamic compilation

- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Audio/BassUtils.cs
- osu.Framework/Audio/Sample/SampleBass.cs
- osu.Framework/Audio/Track/TrackBass.cs
Helps investigating ppy/osu#9045.
Not quite sure about the method naming though.
> Replace all BASS fail assertions with describing-exceptions

- osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
Fixes performance issues surfaced in https://github.com/ppy/osu/pull/9021
> Fix LifetimeManagementContainer not unbinding events on clear

- osu-framework.sln.DotSettings
- osu.Framework.Tests/Graphics/ColourTest.cs
- osu.Framework/Graphics/Colour4.cs
Adds various conversion functions from `Color4Extensions` as well as unit tests for said conversions.
> Colour4 functions and tests

- osu.Framework/Graphics/Visualisation/LogOverlay.cs
Closes https://github.com/ppy/osu-framework/issues/3591.
> Fix LogOverlay potentially showing entries out of order

- osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
> Add missing System.Numerics reference for Android tests project

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
> Switch TabControl tab if current tab is closed

- SampleGame.iOS/SampleGame.iOS.csproj
- osu-framework.sln
- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
- osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
> Fix clashing GUIDs in solution file

- osu.Framework.Tests/Layout/TestSceneSpriteLayout.cs
- osu.Framework.Tests/Visual/Sprites/TestSceneSmoothedEdges.cs
- osu.Framework/Graphics/Sprites/Sprite.cs
Fixes https://github.com/ppy/osu/issues/9326
> Fix Sprite.EdgeSmoothness not working

- SampleGame.iOS/Application.cs
- osu.Framework.Android/AndroidGameActivity.cs
- osu.Framework.Android/AndroidGameHost.cs
- osu.Framework.Android/AndroidGameView.cs
- osu.Framework.Android/AndroidGameWindow.cs
- osu.Framework.Android/AndroidStorage.cs
- osu.Framework.Android/Graphics/Textures/AndroidTextureLoaderStore.cs
- osu.Framework.Android/Input/AndroidKeyboardHandler.cs
- osu.Framework.Android/Input/AndroidTextInput.cs
- osu.Framework.Android/Input/AndroidTouchHandler.cs
- osu.Framework.Tests.iOS/AppDelegate.cs
- osu.Framework.Tests.iOS/Application.cs
- osu.Framework.iOS/GameAppDelegate.cs
- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework.iOS/IOSGameView.cs
- osu.Framework.iOS/IOSGameWindow.cs
- osu.Framework.iOS/IOSStorage.cs
- osu.Framework.iOS/Input/IOSKeyboardHandler.cs
- osu.Framework.iOS/Input/IOSMouseHandler.cs
- osu.Framework.iOS/Input/IOSTouchHandler.cs
There are some remaining namespace warnings about the tests project (included files from other project don't seem to correctly know their folder hierarchy) but this fixes everything else.
> Fix all iOS/Android project inspections that can be fixed

- osu.Framework/Input/PassThroughInputManager.cs
> Clarify properly why mouse buttons are not fully synchronised

- osu.Framework/Game.cs
- osu.Framework/Platform/DesktopGameHost.cs
- osu.Framework/Platform/GameHost.cs
Resolves https://github.com/ppy/osu-framework/issues/3615
> Add method to provide custom game storage

- osu.Framework/Graphics/Containers/ScrollContainer.cs
> Fix ScrollContainers accepting right-click drags on their scrollbars

- osu.Framework/Graphics/Video/VideoDecoder.cs
Fixes https://github.com/ppy/osu-framework/issues/3519
Unmanaged memory leaks are quite tough to debug >_<
> Fix video decoding memory leaks

- osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> Fix incorrect font specification for StepSlider

- osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
`Dispose()` (on async thread) calls `CancelTasks()` which calls `unloadSchedule.Cancel()`, which I was unaware takes a lock on the Scheduler since it's kinda new code.
So two nested locks were being taken: `DLUW.unloadLock` -> `Scheduler.runLock`.
Meanwhile, the game's scheduler is running and takes the same two locks in sequence `Scheduler.runLock` -> `DLUW.unloadLock`.
You can kinda replicate both the original exception and the deadlock via:
```csharp
[Test]
public void TestUnloadAndDispose()
{
BasicScrollContainer<Drawable> scroll = null;
AddStep("create hierarchy", () =>
{
Child = scroll = new BasicScrollContainer
{
Anchor = Anchor.Centre,
Origin = Anchor.Centre,
Size = new Vector2(200),
};
for (int i = 0; i < 1000; i++)
{
scroll.Add(new DelayedLoadUnloadWrapper(() => new Box { Size = …
```
> Fix potential disposal deadlock in DelayedLoadUnloadWrapper

- osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
Can be used to implement https://github.com/ppy/osu/issues/9479.
> Add property to allow sliderbar to handle input outside of its own hover area

- osu.Framework/Development/DebugUtils.cs
Going to assume this is going to carry forward for future releases.
> Fix unit tests under Rider 2020.2 EAP6

- osu.Framework/Testing/Input/ManualInputManager.cs
Seems like something we keep locally implemented. Unsure of method name, just trying to follow example (`Click`).
> Add function in ManualInputManager to press and release a key

- osu.Framework/Testing/DynamicClassCompiler.cs
Lags a lot and takes a long time to compile. It's probably either many exceptions being thrown internally and/or general performance issues with async that we've had for years by this point (the whole reference building thing is completely async'd). 
Perhaps in the future we can add a very slim way of doing this, maybe by bringing back the old type resolver.
> Disable dynamic compilation with debugger attached

- osu-framework.sln.DotSettings
Required for Rider from EAP6 onwards. Confirmed working with all tests.
> Ensure nUnit runs with correct CurrentDirectory

- osu.Framework/Graphics/OpenGL/DepthValue.cs
- osu.Framework/Platform/GameHost.cs
> Reduce allocations caused by DepthValue

- osu.Framework/Testing/DrawFrameRecordingContainer.cs
> Fix delegate allocation in DrawFrameRecordingContainer

- osu.Framework/Input/InputManager.cs
> Fix delegate allocation in PropagateBlockableEvent

- osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
- osu.Framework/Input/StateChanges/MouseButtonInput.cs
Found while resolving conflicts for the PR depending on this logic.
> Fix last mouse input source not updated for mouse buttons inputs

- osu.Framework/Graphics/Cursor/TooltipContainer.cs
> Fix TooltipContainer allocating excessively

- osu.Framework/Platform/GameHost.cs
> Fix Enumerable allocations from AvailableInputHandlers

- osu.Framework/Input/CustomInputManager.cs
- osu.Framework/Input/Handlers/InputHandler.cs
- osu.Framework/Input/InputManager.cs
- osu.Framework/Input/UserInputManager.cs
> Fix input handler enumerable allocs

- osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
- osu.Framework/Platform/MacOS/MacOSGameWindow.cs
- Closes https://github.com/ppy/osu/issues/9218
> Disable confine mouse mode in macOS to fix fullscreen cursor movement

- osu.Framework.iOS.props
- osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
- osu.Framework/osu.Framework.csproj
Not sure why the PR was closed.
> Update MarkDig package

- osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
- osu.Framework/Graphics/Animations/Animation.cs
Required for https://github.com/ppy/osu/pull/9786
> Add Animation.ClearFrames()

- osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
Fixes test failures (https://ci.appveyor.com/project/peppy/osu-framework/builds/34936995).
Regressed in https://github.com/ppy/osu-framework/pull/3850
> Fix regression in GlobalStatisticsDisplay behaviour

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Fixes https://github.com/ppy/osu-framework/issues/3644
`[ExcludeFromDynamicCompile]` should affect the entire rest of the file.
> Exclude entire files from dynamic compilation

- README.md
**About:** IWBTM is a platformer game based off of a "I Wanna ..." games. Original game is written using GameMaker Studio.
**Url**: https://github.com/EVAST9919/iwbtm
**Previews**:
> Add IWBTM to projects listing in README

- osu.Framework/Testing/TestingExtensions.cs
> Remove type constraint for ChildrenOfType<T>

- osu.Framework.Tests/Visual/Testing/TestSceneTestingExtensions.cs
- osu.Framework/Testing/TestingExtensions.cs
> Fix ChildrenOfType<> early exit for matching composite types

- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework.iOS.props
- osu.Framework.iOS/osu.Framework.iOS.csproj
- osu.Framework/osu.Framework.csproj
Weird that some platforms were at different version than others.
> Update osuTK & NativeLibs libraries

- osu.Framework/Graphics/Transforms/TransformBindable.cs
- osu.Framework/Graphics/Transforms/TransformCustom.cs
Deemed unnecessary after asking what it is for.
> Remove unnecessary interpolation delegate members

- osu.Framework/Bindables/IBindableList.cs
> Add BindCollectionChanged to IBindableList interface

- osu.Framework.Tests/TestGame.cs
- osu.Framework.Tests/Visual/Platform/TestSceneBlockExiting.cs
- osu.Framework/Platform/IWindowBackend.cs
- osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
- osu.Framework/Platform/Window.cs
- osu.Framework/Platform/WindowBackend.cs
Implements the missing `OnExitRequested` flow.
> Implement OnCloseRequested for SDL

- osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
Should resolve recent test failures: https://ci.appveyor.com/project/peppy/osu-framework/builds/35821420/tests
> Fix async load test not allowing child load

- osu.Framework/Audio/Track/Waveform.cs
Resolves https://github.com/ppy/osu/issues/9482.
The waveform graph had a tendency of seemingly randomly drifting back and forth on zoom changes. This was due to an overlooked shortcoming in the point generation algorithm, which resulted in floating-point errors.
The root cause of that was a for-loop in the point-generating routine. The fractional index `i` was kept to determine the neighbourhood from which to sample the next generated point. However, it was being incremented in each iteration of said for-loop by `pointsPerGeneratedPoint`. At larger zoom levels this could result in accumulating floating-point precision errors, causing the visible jitters back and forth.
Resolve by keeping two indices; one fractional for the sampling neighbourhood, and one integral for the point which is …
> Fix waveform graph drifting on zoom changes

- osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
Only passed due to super lucky test ordering I guess... https://ci.appveyor.com/project/peppy/osu-framework/builds/36021966
> Fix intermittent async load test failures

- osu.Framework.Tests/Graphics/LifetimeEntryManagerTest.cs
- osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
Fixes test failures in https://github.com/ppy/osu/pull/10613
> Fix past/future entries not removed after a lifetime change

- osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
- osu.Framework/Statistics/GlobalStatistics.cs
Should help when debugging issues with users and wanting to see a snapshot.
> Output global statistics to log file when displayed

- SampleGame.Desktop/Program.cs
Caught me off-guard that this isn't a thing.
> Add SDL support to SampleGame

- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/AudioComponent.cs
- osu.Framework/Audio/Sample/SampleChannelBass.cs
- osu.Framework/Audio/Track/TrackBass.cs
Fixes https://github.com/ppy/osu/issues/10727 (the focus-related portion).
> Change audio component invalidation logic to use flag instead of delegate

- osu.Framework/Platform/OsuTKWindow.cs
Caused android/iOS input to stop working completely
> Fix CursorInWindow default value being incorrect in tk window classes

- .vscode/tasks.json
- osu.Framework.Templates/templates/template-empty/.vscode/tasks.json
- osu.Framework.Templates/templates/template-flappy/.vscode/tasks.json
As per https://github.com/ppy/osu/issues/10721.
> Update visual studio code task arguments to use dash instead of slash

- .vscode/tasks.json
- README.md
> Remove `--no-restore` from VSCode build tasks

- osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Obstacles.cs
FlappyDon crashes during the normal play and the Obstacles test. This PR fixes both.
> Fix crash in FlappyDon sample project

- global.json
- osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
- osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGame.Game.csproj
- osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
- osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDon.Game.csproj
- osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
- osu.Framework.iOS.props
- osu.Framework/osu.Framework.csproj
Combines all feasible merges from dependabot.
> Update outdated dependencies

- osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
- osu.Framework/Graphics/Pooling/PoolableDrawable.cs
> Fix PoolableDrawable not preparing after clock rewind

- osu.Framework/Platform/SDL2DesktopWindow.cs
Tested on macOS
Closes https://github.com/ppy/osu-framework/issues/4044.
@ben9583 would appreciate confirmation that this fixes the issue for you too.
> Fix DPI scaling not working correctly when running under SDL2

- osu.Framework/Platform/Windows/WindowsWindow.cs
Have tested on windows, seems to fix all the issues I had.
> Manually set DPI aware on windows to fix SDL not handling correctly

- osu.Framework/Platform/Linux/LinuxGameHost.cs
- osu.Framework/Platform/Linux/OsuTKLinuxWindow.cs
- osu.Framework/Platform/Linux/SDL2/SDL2Clipboard.cs
- osu.Framework/Platform/SDL2/SDL2ControllerBindings.cs
- osu.Framework/Platform/SDL2/SDL2Extensions.cs
- osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
- osu.Framework/Platform/SDL2DesktopWindow.cs
- osu.Framework/osu.Framework.csproj
> Standardise naming of SDL2 references

- osu.Framework.Tests/Audio/AudioCollectionManagerTest.cs
- osu.Framework/Audio/AudioCollectionManager.cs
> Fix crash when AudioCollectionManager is modified on disposal

- osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
Fixes RenderDoc not attaching to o!f projects under SDL.
> Explicitly request compatibility profile

- osu.Framework/Resources/Shaders/sh_Bloom.fs
See: https://github.com/ppy/osu-stable-issues/issues/621
Not sure if this shader is even usable with o!f.
> Fix potential bloom shader compile errors

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
First step in attempting to resolve issue mentioned in https://github.com/ppy/osu/commit/4399e10fb7babb5abefd27f248e0072ab0f70953 properly.
> Allow to opt-out from automatic first tab selection

- README.md
README will now say .NET 5.0 is required
> Update .NET SDK requirements in README

- osu.Framework/Platform/IWindow.cs
- osu.Framework/Platform/OsuTKWindow.cs
> Expose IWindow.Resized event

- osu.Framework.Tests/Visual/Input/TestSceneInputPropagationForLoadStates.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Screens/ScreenStack.cs
Closes https://github.com/ppy/osu/issues/10988.
> Fix input propagating to drawables which are not yet in a loaded state

- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/AudioAdjustments.cs
- osu.Framework/Audio/IAdjustableAudioComponent.cs
- osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
I don't see any reason for it being a Bindable, or a Number.
> Change IAdjustableAudioComponent/AudioAdjustments to use IBindable instead of BindableNumber

- osu.Framework/Development/DebugUtils.cs
Aims to resolve https://github.com/ppy/osu/issues/11839. PRing for discussion.
On Android, `Assembly.GetEntryAssembly()` returns `null`. That is not at all surprising, as per the docs, there *is no* entry assembly - the game is being ran through mono.
`DebugUtils`'s entry assembly detection code would wrongly assume that if the entry assembly as given by the CLR is null, then the game was being ran in a test context (`IsNUnitRunning` is true). Therefore, on Android, all `DebugUtils` members that utilised the assembly detection, would use the properties of the `nunit.framework` assembly, instead of the executing assembly.
The reason why the `nunit.framework` assembly was chosen was that if an NUnit test context is requested outside of an actual test, NUnit will make up its own context …
> Fix incorrect entry assembly selection on android

- osu.Framework/Audio/AdjustableAudioComponent.cs
- osu.Framework/Audio/AudioAdjustments.cs
- osu.Framework/Audio/IAdjustableAudioComponent.cs
- osu.Framework/Audio/Sample/ISample.cs
- osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
- osu.Framework/Graphics/Audio/DrawableSample.cs
Just PRing for visibility; don't merge without further discussion.
> Use ISample in DrawableSample

- osu.Framework.Tests/IO/TestWebRequest.cs
- osu.Framework/IO/Network/WebRequest.cs
> Fix empty POST requests always having multipart body specification

- osu.Framework/Allocation/TimedExpiryCache.cs
- osu.Framework/Audio/Track/Waveform.cs
- osu.Framework/Configuration/ConfigManager.cs
- osu.Framework/Graphics/Textures/TextureLoaderStore.cs
- osu.Framework/IO/Network/WebRequest.cs
- osu.Framework/IO/Stores/DllResourceStore.cs
- osu.Framework/IO/Stores/GlyphStore.cs
- osu.Framework/IO/Stores/OnlineStore.cs
- osu.Framework/IO/Stores/ResourceStore.cs
- osu.Framework/IO/Stores/StorageBackedResourceStore.cs
- osu.Framework/Input/Handlers/InputHandler.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
- osu.Framework/Testing/DynamicClassCompiler.cs
I've left classes out of this PR which require a bit more thought to determine the correct approach.
Partly addresses #4229.
> Remove remaining no-brainer finalizers

- osu.Framework/Statistics/DotNetRuntimeListener.cs
It's not perfect, since it only triggers by the last object in 100KB allocation chunks, but it's the best shot we've got for now.
Only active while global statistics is open.
> Add log for finalizable object allocations

- osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
Just some miscellaneous clean-up as I go through raw input stuff
> Remove unused bindable from OsuTKRawMouseHandler

- osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
- osu.Framework/Platform/SDL2DesktopWindow.cs
Adds testability and fixes event flow a touch. Changes made while attempting to help with #4134, but don't yet have any idea what is going on so going to leave it here.
> Improve code quality surrounding confine mode changes

- osu.Framework/Utils/PathApproximator.cs
Fixes https://github.com/ppy/osu/issues/12109
I've verified that stable uses the same calculations. Will run a beatmap difficulty reprocess to visualise the changes, and have an osu!-side test case for the failure.
> Make circular approximation less prone to FP failures

- osu.Framework/Graphics/Drawable.cs
> Add xmldoc stating parent invalidations always propagate

- osu.Framework/osu.Framework.csproj
Tested on macOS and windows to work roughly as expected.
> Update SDL libraries

- osu.Framework/Platform/GameHost.cs
Noticed while I was improving messaging for GL context failures (https://github.com/ppy/osu-framework/pull/4325). Setting the window handle to `-1` will cause a segfault on the main thread, which delays termination for 10s.
I think it's a fair assumption that we can't guarantee the main thread will keep running if the CLR has informed us it will terminate, regardless of whether that exception comes from a `new Thread(() => ...)` callback or on the main thread outside of the `InputThread` loop.
> Don't delay application terminations on main-thread unhandled exceptions

- osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs
Changes which were helpful in creating the SDL-side fix for https://github.com/ppy/osu/issues/12169.
> Update TestSceneActiveState to better visualise what each box means

- osu.Framework/osu.Framework.csproj
Closes https://github.com/ppy/osu/issues/12244.
Closes https://github.com/ppy/osu/issues/12169.
Probably closes a dozen other SDL relative mouse mode related issues (related to alt-tab or mouse exiting/entering window), but time will tell.
> Update SDL2-CS to latest prerelease

- osu.Framework/Audio/Sample/SampleChannelBass.cs
Fixes https://github.com/ppy/osu/issues/11845
It's hard to unit test this, so I've left it out. It can be tested by adding a breakpoint on a condition such as:
```csharp
if (Bass.ChannelGetAttribute(channel, ChannelAttribute.Volume, out var vol) && vol > 0.8f)
{
}
```
After `Bass.ChannelPlay()` in `playChannel`.
This issue can only be repro'd in single-threaded mode because inline execution is only allowed in that mode.
`Sample`s and `SampleChannel`s are added to the audio hierarchy (and thus become alive) only when a `SampleChannel` is `Play`'ed. If at any point the `SampleChannel` becomes `Playing = false`, it's removed from the hierarchy, which also causes the parenting `Sample` to be removed from the hierarchy if no other `SampleChannel`s are alive.
Thus, in the case of …
> Fix 100% sample volumes for 1 frame in single-threaded execution

- osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
Closes https://github.com/ppy/osu-framework/issues/4322.
> Fix alt-tab not working well when in fullscreen mode

- osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
Was missing some IFDEF in test scene itself.
> Fix osu.Framework.Tests compilation on mobile platforms

- osu.Framework/Audio/AudioManager.cs
I noticed that it would take a little bit of time to shut down o!f naturally. This was caused by #4363, in which I started joining the sync device thread to make sure it's stopped before devices are freed.
I thought this would be unnoticeable, but it definitely is. There's only one path that can cause this: `onDevicesChanged()`. As long as it runs on the audio thread, which it is, there shouldn't be any issues with this.
> Improve shutdown performance by not joining the sync device thread

- osu.Framework/Input/InputManager.cs
Closes https://github.com/ppy/osu-framework/issues/4361.
> Don't collect input from non-active `InputHandler`s

- osu.Framework.Tests/Extensions/TestExtensions.cs
- osu.Framework/Extensions/ExtensionMethods.cs
Fixes the error mentioned in https://github.com/ppy/osu/pull/12485
> Fix possible nullref in GetDescription() extension method

- osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
- osu.Framework/Graphics/Drawable.cs
Supersedes and closes https://github.com/ppy/osu/pull/12504.
Closes https://github.com/ppy/osu/issues/12491.
> Add lock object specifically for scheduler to avoid deadlock scenario

- osu.Framework/Testing/ITypeReferenceBuilder.cs
- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
> Add dynamic recompilation message when changed file isn't referenced

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Prereqs:
Just a few more I found.
> Ignore exploring more types during dynamic compilation

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
> Multithreaded dynamic compilation type resolver

- osu.Framework.Tests/Visual/Input/TestSceneMidi.cs
- osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Closes https://github.com/ppy/osu/issues/12543.
Have tested with a virtual midi device to still work as expected.
> Close midi devices asynchronously to avoid blocking the game UI

- osu.Framework/Platform/SDL2DesktopWindow.cs
> Change default value of `CursorInWindow` to false

- osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Not sure how I missed these, guess rider didn't show them for some reason.
> Add ConfigureAwait(false) to DCC

- osu.Framework/osu.Framework.csproj
Closes https://github.com/ppy/osu/issues/12523.
> Update SDL2 version

- osu.Framework.Tests/Platform/GameHostSuspendTest.cs
Fixes the race condition causing the gamehost test failure in https://github.com/ppy/osu-framework/pull/4430#issuecomment-832154842
> Fix race condition in gamehost suspension test

- osu.Framework.Tests/Visual/Audio/TestSceneSampleChannels.cs
As seen in https://github.com/ppy/osu-framework/runs/2511077249
Can be repro'd by adding a `Thread.Sleep(3000);` at the start of the enqueued action in `SampleChannelBass.playChannel()`.
This test relied on some logic which has changed since https://github.com/ppy/osu-framework/pull/4336 - `Play()` now immediately sets `Playing = true`. So this was failing because the audio thread was not having enough time to run in-between update frames to set it back to false.
> Fix sample channel test failing intermittently

- osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithUnloading.cs
As seen in https://github.com/ppy/osu-framework/runs/2674812275
Just tested by adding some reasonable delays.
> Fix intermittent test failures

- osu.Framework/Graphics/Performance/LifetimeEntry.cs
- osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
To solve the issue described in ppy/osu#12878, a way to know about lifetime change is needed.
> Add `LifetimeChanged` event to `LifetimeEntry`

- osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
Currently, the flow that disables relative mode (based on whether the cursor is in the window) sometimes disables relative mode when the cursor is entering the window.
This PR adds a check so that the disable relative mode flow is only triggered if the cursor is leaving the window.
Closes https://github.com/ppy/osu-framework/issues/4341
Closes PR https://github.com/ppy/osu-framework/pull/4342
> Disable relative mode only when leaving the window

- osu.Framework/Audio/Track/Waveform.cs
```diff
-    /// Procsses
+    /// Processes
```
> Fix typo in Waveform xmldoc

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
As seen in https://github.com/ppy/osu-framework/pull/4496/checks?check_run_id=2790404156
> Fix potential ScreenStack test failure

- osu.Framework/Platform/SDL2DesktopWindow.cs
Closes https://github.com/ppy/osu/issues/13385.
> Fix `FrameworkConfigManager.WindowSize` not updating during resize operations

- osu.Framework/Testing/DynamicClassCompiler.cs
Closes https://github.com/ppy/osu-framework/issues/4511
> Add logging if dynamic compilation is disabled due to no solution file

- osu.Framework/Graphics/Containers/Markdown/MarkdownImage.cs
In order to resolve (https://github.com/ppy/osu/issues/13418), need these method so I can override some parts in `MarkdownImage`
I don't have the solution for the actual issue yet, still figuring out about it.
> Expose virtual method in `MarkdownImage`

- osu.Framework/Graphics/UserInterface/DirectorySelector.cs
- osu.Framework/Graphics/UserInterface/FileSelector.cs
Port of https://github.com/ppy/osu/pull/13619 for the framework-side component.
It was possible for a directory change to cause an endless recursion. If both the new value and the old value of `CurrentPath` was inaccessible to the user (due to being deleted, rendered inaccessible in another manner, etc.), then the selector would first try to enter the new directory, then failing that, endlessly attempt to enter the old directory.
To resolve, iteratively traverse the filesystem graph upwards to find an accessible directory on failure, and only set `CurrentPath` once when a suitable directory has been found.
Automated testing is feasible, but I'm unsure if worth. I tested manually with a two-level nested directory structure:
```
~
/test
/test
```
and by doing
```
~$ cd test && chmod -x test …
```
> Fix directory/file selector potentially entering recursion loop

- osu.Framework/Utils/Interpolation.cs
Closes #4581
I implemented the `Colour4` interpolation function, this does the same thing as `Color4`
> Implement `Colour4` interpolation function

- osu.Framework/Bindables/BindableLong.cs
This makes the ctor of BindableNumber accessible
> Add default value ctor to BindableLong

- osu.Framework.Benchmarks/BenchmarkHashing.cs
- osu.Framework/Extensions/ExtensionMethods.cs
nit: I know how to maximize performance, but it doesn't worth for code complexity.
> Minor optimization and cleanup for extension methods

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
- Makes every `ScreenStack` test also test mutation allowed in callbacks
- Add test coverage of reported breaking scenario (closes https://github.com/ppy/osu-framework/issues/4164 as not reproducible).
> Add more testing of `ScreenStack`

- osu.Framework/Bindables/BindableDictionary.cs
- osu.Framework/Lists/LockedWeakList.cs
- osu.Framework/Lists/WeakList_ValidItemsEnumerator.cs
Resolves https://github.com/ppy/osu-framework/issues/4625
Follows the example set by List<T>: https://source.dot.net/#System.Private.CoreLib/List.cs,1101
> Make WeakList<T> enumerator not force nullability

- osu.Framework/osu.Framework.csproj
Closes https://github.com/ppy/osu-framework/issues/2198.
Closes https://github.com/ppy/osu-framework/issues/2525.
Closes https://github.com/ppy/osu/issues/11489.
> Update SDL libraries with native library bump

- osu.Framework/Platform/Windows/Native/Input.cs
Companion to https://github.com/ppy/osu/pull/13856
> Fix new formatting inspection from EAP6

- osu.Framework/Input/PlatformAction.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Platform/MacOS/MacOSGameHost.cs
To be used by osu! to create new multiplayer rooms, as one example.
> Add `DocumentNew` platform binding

- osu.Framework.Tests/Visual/Testing/TestSceneManualInputManagerTestScene.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
- osu.Framework/Testing/Input/ManualInputManager.cs
Not 100% on the naming of the method (should it instead be `Key` as an
overload?).
> Add the ability to actuate `PlatformAction`s via `ManualInputManager`

- osu.Framework/Development/DebugUtils.cs
See https://github.com/ppy/osu-framework/pull/4653.
> Obsolete `DebugUtils.GetEntryPath()`

- osu.Framework.Benchmarks/BenchmarkBeginAbsoluteSequence.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Transforms/TransformSequence.cs
- osu.Framework/Graphics/Transforms/Transformable.cs
Tackling remaining super hot allocations during gameplay (based on number of objects allocated, not size of objects).
master:
|                     Method |       Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|--------------------------- |-----------:|---------:|---------:|--------:|-------:|------:|----------:|
|               NonRecursive | 1,032.7 us | 19.79 us | 19.44 us |       - |      - |     - |     198 B |
|                  Recursive |   994.2 us | 17.76 us | 16.61 us |  3.9063 |      - |     - |  56,294 B |
| SlightlyNestedNonRecursive | 1,025.9 us | 18.20 us | 16.13 us |       - |      - |     - |     198 B |
|    SlightlyNestedRecursive | 1,185.3 us | 23.11 us | 20.49 us | 17.5781 | 5.8594 |     - | 208,294 B |
|     VeryNestedNonRecursive | 1,019.5 us | …
> Optimise `BeginAbsoluteSequence` recursive case

- osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
- osu.Framework.Tests/osu.Framework.Tests.csproj
- osu.Framework/osu.Framework.csproj
Closes https://github.com/ppy/osu/issues/14399.
> Update SDL and other menial dependencies

- osu.Framework/Graphics/Textures/TextureUpload.cs
Closes https://github.com/ppy/osu/issues/14417
> Reduce verbosity of STBI errors

- README.md
Noticed this while looking for the template/getting-started resources myself.
> Add introduction to README for users looking to use the framework, not work on it

- README.md
> Fix duplicated section in readme

- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
- osu.Framework/Threading/GameThread.cs
- osu.Framework/Timing/ThrottledFrameClock.cs
Until now we weren't really handling the `0` and `MaxValue` cases consistently. This adds documentation and consistent handling. Not sure how I feel about the `0` value case, but this is the easiest path forward for now.
> Add better documentation and handling of update rate extremities

- osu.Framework.Templates/README.md
See https://github.com/ppy/osu-framework/issues/4760. Just adding this until we find the opportunity to update the templates to work better.
> Add a note warning against using spaces/hyphens when consuming templates

- osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
This doesn't fix the issue (touches a different test), but I noticed it along the way.
> Fix another potential DLUW test failure

- osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
As seen in https://github.com/ppy/osu-framework/pull/4783/checks?check_run_id=3728380421
> Remove online requirements from TestSceneTextures

- osu.Framework/Platform/GameHost.cs
This enforces the expectation that only one `GameHost` should be running at a time. I'm not yet sure if we should make this change as it means that parallel test runs are no longer possible (unless run under a different .NET host). Maybe okay, but also maybe not as it breaks default settings on some IDEs. And also makes running tests a lot slower.
PRing for discussion and to see if we trigger any failures on CI as a result (to help track the cause behind https://github.com/ppy/osu-framework/runs/3659452824?check_suite_focus=true).
> Add global mutex on `GameHost` running state

- osu.Framework.Tests/Visual/Localisation/TestSceneTextFlowContainerLocalisation.cs
- osu.Framework.Tests/Visual/Localisation/TestSceneTextFlowLocalisation.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
Adds testing of relevant scenarios too.
> Allow `TextFlowContainer` parts to be generated asynchronously where possible

- .config/dotnet-tools.json
See: https://github.com/laedit/vika/pull/311
> Upgrade to nvika 1.0.4

- SampleGame.iOS/Application.cs
- osu.Framework.Android/AndroidGameHost.cs
- osu.Framework.Android/AndroidGameView.cs
- osu.Framework.Android/Graphics/Textures/AndroidTextureLoaderStore.cs
- osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
- osu.Framework.Android/Input/AndroidTextInput.cs
- osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/Application.cs
- osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Obstacles.cs
- osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/Application.cs
- osu.Framework.Tests.iOS/Application.cs
- osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
- osu.Framework.iOS/Graphics/Video/IOSVideoDecoder.cs
- osu.Framework.iOS/IOSGameHost.cs
- osu.Framework.iOS/Input/IOSTextInput.cs
Just some minor things that were bugging me when opening the entire solution in Rider.
Haven't tested fa9fe268b47ad6925b614affed049f03be328a5a, but the fix seemed correct.
> Fix micelaneous inspections

- osu.Framework/Threading/AudioThread.cs
I added some logging in this pathway and got the following output:
```
Failed to select already-initialised audio device 1 (Init)!!
This is not the currently-selected device (-1).
Trying to get device info...
Got device info:
Name: Default, Driver: , Type: 0, Enabled: True, Initialised: False, Loopback: False
Devices:
0 | Name: No sound, Driver: , Type: 0, Enabled: True, Initialised: False, Loopback: False
1 | Name: Default, Driver: , Type: 0, Enabled: True, Initialised: False, Loopback: False
2 | Name: Soundflower (2ch), Driver: SoundflowerEngine:0, Type: 0, Enabled: True, Initialised: False, Loopback: False
3 | Name: Soundflower (64ch), Driver: SoundflowerEngine:1, Type: 0, Enabled: True, Initialised: False, Loopback: False
Retrying to init device 1...
Failed to init device (Already)!! …
```
> Reduce failures in audio device re-init sequence

- osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
- osu.Framework/Extensions/ExtensionMethods.cs
Framework-side PR for https://github.com/ppy/osu/pull/15990.
> Add extension for checking if a character is an ASCII digit

- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework.iOS.props
- osu.Framework.iOS/osu.Framework.iOS.csproj
- osu.Framework/osu.Framework.csproj
This time tested against actual hardware (14.4 and 15.2) to work correctly.
> Update osuTK once more (for iOS compatibility)

- osu.Framework/osu.Framework.csproj
In hopes of fixing stuff like https://github.com/ppy/osu/issues/14210 (does on my box in this case) or https://github.com/ppy/osu/discussions/16179.
Also allows consumers to actually receive the updates from https://github.com/ppy/osu-framework/pull/4903.
> Update nativelibs package

- osu.Framework/Configuration/InputConfigManager.cs
- osu.Framework/Platform/GameHost.cs
Just noticed while investigating https://github.com/ppy/osu-framework/issues/4950.
> Add missing xmldoc to `InputConfigManager`

- osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
See individual commits for more details. Standard async/schedule oversight failures, "unfortunately".
> Fix multiple test failures in screen stack tests

- osu.Framework/Logging/Logger.cs
As seen at https://github.com/ppy/osu/runs/4603823798?check_suite_focus=true.
> Avoid throwing exception during log file cleanup

- osu-framework.sln.DotSettings
- osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
- osu.Framework/Statistics/GlobalStatistics.cs
Just a few quick ones that bugged me.
I'm not sure about closure avoidance being at "suggestion" level. I think all suggestions should be things which are 100% applied, and we have very much not 100% applied that yet. But maybe it should be in the near future and left at that level.
> Tidy up some inspections

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
- osu.Framework/Graphics/Drawable.cs
Have run against osu! tests suite, looks okay.
> Add missing thread safety check in `LoadComponentsAsync`

- osu.Framework/Allocation/AsyncDisposalQueue.cs
Scenario:
- A drawable is loaded via `LoadComponentAsync`, but blocking on a long running task (ie. a web request that's taking too load inside a `BackgroundDependencyLoader` asynchronous method).
- Same component gets disposed, and added to the `AsyncDisposalQueue`
- `AsyncDisposalQueue` blocks on `LoadLock` until the load process is finished. In the case of a web request this could take 10-30 seconds to timeout
During this time, a TPL thread is blocked. This can actually cause multiple threads to get stuck in a blocking state due to the way `AsyncDisposalQueue` is written (it will start a new thread if the last one has already posted).
I've opted to solve this in the simplest way possible - by redirecting the work to a `ThreadedTaskScheduler`. At some point, we may want to rewrite the …
> Remove async disposal queue reliance on TPL thread pool to avoid locking scenarios

- osu.Framework.Tests/Visual/Containers/TestSceneCursorContainer.cs
- osu.Framework/Graphics/Cursor/CursorContainer.cs
Closes https://github.com/ppy/osu/issues/16792
> Allow `CursorContainer` to update cursor position while hidden

- appveyor.yml
- appveyor_deploy.yml
- appveyor_native_deploy.yml
Image we were targetting is missing .NET6.0.
> Update appveyor target image

- osu.Framework.Tests/Visual/Platform/TestSceneClipboard.cs
- osu.Framework.iOS/IOSClipboard.cs
- osu.Framework/Platform/Clipboard.cs
- osu.Framework/Platform/Linux/SDL2/SDL2Clipboard.cs
- osu.Framework/Platform/MacOS/MacOSClipboard.cs
- osu.Framework/Platform/Windows/WindowsClipboard.cs
ppy/osu#16775
Implements `GetImage`/`SetImage` in `WindowsClipboard`, hopefully with support for other platforms coming soon
> Implement `GetImage`/`SetImage`

- osu.Framework/Graphics/Containers/ScrollContainer.cs
- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
- osu.Framework/Graphics/UserInterface/TextBox.cs
- osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
- osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
- osu.Framework/IO/Network/UrlEncoding.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/InputResampler.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/TestBrowser.cs
Should hopefully be non-controversial.
> Apply new resharper non-obvious precedence inspections

- osu.Framework/Graphics/Audio/WaveformGraph.cs
Noticed this in an internal branch, can be reproed by entering the editor.
> Fix Waveform outputting NaN values in vertices

- .config/dotnet-tools.json
- .github/workflows/ci.yml
- .gitignore
- InspectCode.ps1
- InspectCode.sh
- osu.Framework.Tests/Bindables/BindableDictionaryTest.cs
- osu.Framework.Tests/Bindables/BindableListTest.cs
- osu.Framework.Tests/Bindables/BindableSerializationTest.cs
- osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Testing/TestScene.cs
I've run this 5 times in https://github.com/smoogipoo/osu-framework/runs/6017742926?check_suite_focus=true, seems to be working without deadlocks. Would like to merge into master for further testing.
> Upgrade Resharper to 2022.1.0-eap10

- osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
Was broken since https://github.com/ppy/osu-framework/pull/5068.
> Fix borderless test failing

- .github/workflows/ci.yml
Matches https://github.com/ppy/osu/pull/17903
> Move Code Quality check to top of checks list

- osu.Framework/Game.cs
- osu.Framework/Platform/IWindow.cs
- osu.Framework/Platform/OsuTKWindow.cs
Fixes https://github.com/ppy/osu-framework/issues/5117.
> Fix alt-f4 bypassing exit flow on windows

- .idea/.idea.osu-framework.Desktop/.idea/misc.xml
- Companion to https://github.com/ppy/osu/pull/17821
Interesting enough I can only get this file in the `osu-framework.Desktop` solution filter.
> Apply new rider metadata changes

- CodeAnalysis/BannedSymbols.txt
- osu.Framework.Benchmarks/BenchmarkLocalisedBindableString.cs
- osu.Framework.Tests/Configuration/FrameworkConfigManagerTest.cs
- osu.Framework.Tests/IO/TestDesktopStorage.cs
I'm open to `BannedSymbols` this if everyone agrees
> Fix incorrect usage of `new Guid()`

- osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
Turns out this thing is not thread-safe :sweat_smile:
> Make NullabilityInfoContext usage thread-safe

- osu.Framework.Android/Input/AndroidInputExtensions.cs
- osu.Framework.Android/Input/AndroidMouseHandler.cs
Closes #5249. Untested as of yet.
> Fix android mouse button handling not accounting for multiple buttons pressed at once

- osu.Framework/Graphics/Visualisation/ToolWindow.cs
- osu.Framework/Graphics/Visualisation/TreeContainer.cs
- osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Addresses [#5125](https://github.com/ppy/osu-framework/discussions/5125)
This seems like a straightforward implementation, however, I'm not entirely sure about the whole `WrapScrollContent()` approach here but I can't seem to figure out another possible solution.
https://user-images.githubusercontent.com/35349837/174502141-2fc988ec-d94d-461e-8cd1-938085a951a6.mp4
> Implement search text box within the draw visualizer

- osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
Startup time is abysmal of this component. I thought we already had this running async but seems not.
> Initialise OpenTabletDriver asynchronously

- .github/workflows/ci.yml
Reverts #5253 as the issue has since been [resolved](https://github.com/actions/virtual-environments/issues/5768#issuecomment-1165486519) upstream.
> Remove iOS build CI workaround

- osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
- osu.Framework/Graphics/UserInterface/SliderBar.cs
Pretty large oversight. As mentioned over at https://github.com/ppy/osu/discussions/18938.
> Fix slider bar drags not being relative to mouse down position

- osu-framework.sln.DotSettings
Copied over from [`osu.sln.DotSettings`](https://github.com/ppy/osu/blob/master/osu.sln.DotSettings#L807-L815) with the addition of `Java.Util.Logging` (for Android).
> Add code autocomplete blacklist

- osu.Framework/Testing/TestScene.cs
As discussed, this feels like a better default.
Have also documented all available envvars at https://github.com/ppy/osu-framework/wiki/Environment_variables.
> Change test GC to not force run by default

- SampleGame.Android/SampleGameActivity.cs
- osu.Framework.Android/AndroidGameActivity.cs
- osu.Framework.Android/AndroidGameHost.cs
- osu.Framework.Android/AndroidGameView.cs
- osu.Framework.Android/AndroidGameWindow.cs
- osu.Framework.Android/AndroidStorage.cs
- osu.Framework.Android/Graphics/Textures/AndroidTextureLoaderStore.cs
- osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
- osu.Framework.Android/Input/AndroidInputConnection.cs
- osu.Framework.Android/Input/AndroidInputExtensions.cs
- osu.Framework.Android/Properties/AssemblyInfo.cs
- osu.Framework.Tests.Android/TestGameActivity.cs
Includes everything except `AndroidInputHandler`s as those will be covered separately.
> Full NRT pass on Android

- osu.Framework/Platform/NativeStorage.cs
- osu.Framework/Utils/General.cs
Closes #5272.
Not sure about naming or location of the helper method. Implementation taken from tried and tested version [here](https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/IO/MigratableStorage.cs#L116-L123).
> Fix `File.Move` operations occasionally failing on windows due to star misalignment

- osu.Framework.Android/AndroidGameView.cs
- Closes https://github.com/ppy/osu-framework/issues/5312
> Fix startup crash on Android verison before 8.0 Oreo

- osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
- osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
- osu.Framework.Tests/Clocks/StopwatchClockTest.cs
- osu.Framework.Tests/Clocks/TestClock.cs
- osu.Framework.Tests/Visual/Clocks/LaggyFramedClock.cs
- osu.Framework.Tests/Visual/Clocks/TestSceneClock.cs
- osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
- osu.Framework/Timing/FrameTimeInfo.cs
- osu.Framework/Timing/FramedClock.cs
- osu.Framework/Timing/IAdjustableClock.cs
- osu.Framework/Timing/IClock.cs
- osu.Framework/Timing/IFrameBasedClock.cs
- osu.Framework/Timing/ISourceChangeableClock.cs
- osu.Framework/Timing/ManualClock.cs
- osu.Framework/Timing/OffsetClock.cs
- osu.Framework/Timing/StopwatchClock.cs
Remove nullable disable annotate in the clock namespace.
> Remove nullable disable annotation in the clock namespace

- osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
Looked into https://github.com/ppy/osu-framework/runs/7740377137?check_suite_focus=true and immediately saw this dodgy test. Hoping this fixes the test but it's hard to know since it's a rarely intermittent test.
> Refactor dodgy test to avoid TPL exhaustion

- osu.Framework.Tests/Threading/AsyncDisposalQueueTest.cs
- osu.Framework.Tests/Threading/SchedulerTest.cs
- osu.Framework.Tests/Threading/ThreadedTaskSchedulerTest.cs
- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
- osu.Framework/Platform/GameHost.cs
- osu.Framework/Threading/AudioThread.cs
- osu.Framework/Threading/DrawThread.cs
- osu.Framework/Threading/GameThread.cs
- osu.Framework/Threading/GameThreadScheduler.cs
- osu.Framework/Threading/GameThreadState.cs
- osu.Framework/Threading/InputThread.cs
- osu.Framework/Threading/ThreadedTaskScheduler.cs
- osu.Framework/Threading/UpdateThread.cs
Remove nullable disable annotate in the threading namespace.
> Remove nullable disable annotation in the threading namespace.

- osu.Framework/osu.Framework.csproj
This reverts commit c46b2519ef65a866e8de101ffd7b37fbe1ac53a3.
Regressed in multiple ways, will report upstream.
> Revert "Update SDL"

- osu.Framework/Graphics/UserInterface/CircularProgress.cs
In order to catch the cause of https://sentry.ppy.sh/organizations/ppy/issues/5740/?end=2022-08-11T03%3A10%3A59&project=2&query=firstRelease%3Aosu%402022.810.2&sort=freq&start=2022-08-10T08%3A52%3A00
> Add validation on circular progress properties

- osu.Framework/osu.Framework.csproj
Hopefully with less regress this time 🤞
> Update SDL (again)

- osu.Framework/Graphics/Containers/CompositeComponent.cs
To be used in places we currently (sometimes) mention using inline comments such as:
https://github.com/ppy/osu/blob/31a447fda0532fcf15f8c8251ca890c533386492/osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs#L30-L35
https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/Online/PollingComponent.cs#L19
> Add `CompositeComponent` marker class

- osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Closes https://github.com/ppy/osu/issues/19846#issuecomment-1221406051.
Also applied NRT while here.
> Fix potential crash if file with incorrect filename format is in font cache directory

- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
> Fix dropdown selected visual state not being maintained when `Items` are set after `Current`

- .config/dotnet-tools.json
- osu.Framework.Tests/Bindables/AggregateBindableTest.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Graphics/UserInterface/Menu.cs
Should contain a fix for this: https://youtrack.jetbrains.com/issue/RSRP-489541/InspectCode-caches-inconsistent-after-turning-on-NRT
> Update ReSharper CLI to 2022.2.3

- README.md
> Close open parenthesis in `README.md`

- osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
Not sure if this helps or (solves) https://github.com/ppy/osu-framework/issues/5423, but probably worth opening a PR for.
> Unsubscribe from tablet driver events on disposal

- osu.Framework/Audio/Track/Waveform.cs
> Fix potential `null` return to `ArrayPool` in `Waveform`

- osu.Framework/Input/Handlers/InputHandler.cs
https://discord.com/channels/188630481301012481/589331078574112768/1026572293935210596
> Fix `InputHandler` exceptions not being forwarded to logger

- osu.Framework/Platform/SDL2DesktopWindow_Input.cs
- osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Just something non-controversial so the final diff for #5448 doesn't contain too much stuff.
> Misc windowing changes

- osu.Framework/Graphics/Rendering/Renderer.cs
> Fix another unnecessary VBO flushing overhead in shader bind

- osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
https://discord.com/channels/188630481301012481/589331078574112768/1028988858345459752
> Fix release configuration not building

- osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
This also fixes a merge error in this function, where it would use the `displayIndex` and `currentDisplay` fields instead of the provided `Display`.
> Make `getClosestDisplayMode()` static

- osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
- osu.Framework.Tests/Input/MouseInputTest.cs
- osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
- osu.Framework/Development/DebugUtils.cs
- osu.Framework/Graphics/Drawable.cs
- osu.Framework/Host.cs
- osu.Framework/Input/Bindings/KeyCombination.cs
- osu.Framework/Platform/HeadlessGameHost.cs
- osu.Framework/Screens/Screen.cs
- osu.Framework/Testing/TestRunHeadlessGameHost.cs
Tested with osu! to work with no changes required.
> Clean up various obsoleted code

- osu.Framework/Utils/CircularArcProperties.cs
- osu.Framework/Utils/PathApproximator.cs
for https://github.com/ppy/osu/pull/20952
> Make CircularArcProperties public

- osu.Framework/Graphics/UserInterface/BasicDirectorySelectorBreadcrumbDisplay.cs
- osu.Framework/Graphics/UserInterface/DirectorySelectorBreadcrumbDisplay.cs
| -- | -- |
| ![osu Framework Tests 2022-11-01 at 08 06 45](https://user-images.githubusercontent.com/191335/199187376-7eaca20f-55cb-4844-b65d-6c8b63ce6233.png)|![osu Framework Tests 2022-11-01 at 08 05 53](https://user-images.githubusercontent.com/191335/199187297-34e329d4-611c-4cbd-ac9e-f3445f750627.png)|
> Fix directory selector breadcrumb flow not correctly wrapping vertically

- osu.Framework/Game.cs
To stop @Tom94 squinting at his screen.
> Fix tool overlays not scaling with DPI / window size

- osu.Framework/Game.cs
Just one step in the right direction. Could be improve by bringing-to-front if not already at the front, and working for mouse focus but that's for another day/year.
> Display tool overlays in front on toggle

- osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
Resolves https://github.com/ppy/osu-framework/issues/5524
> Initialise BufferedDrawNode FBOs as late as possible

- osu.Framework.SourceGeneration/Common/Emitters/DependenciesFileEmitter.cs
Weird how this is showing up now.
> Fix inconsistent body style inspection

- osu.Framework/osu.Framework.csproj
> Bump source generator package

- osu.Framework/Localisation/LocalisableString.cs
https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#StringFormatMethodAttribute
> Add `StringFormatMethod` annotation to `LocalisableString.Format`

- .github/workflows/ci.yml
- .github/workflows/deploy-pack.yml
- SampleGame/SampleGame.csproj
- appveyor_deploy.yml
- build/build.cake
- osu.Framework.Templates/osu.Framework.Templates.csproj
- osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGame.Game.csproj
- osu.Framework.Templates/templates/template-empty/TemplateGame.Resources/TemplateGame.Resources.csproj
- osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDon.Game.csproj
- osu.Framework.Templates/templates/template-flappy/FlappyDon.Resources/FlappyDon.Resources.csproj
- osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
- osu.Framework/Bindables/BindableDictionary.cs
- osu.Framework/Extensions/ExtensionMethods.cs
- osu.Framework/Extensions/StreamExtensions.cs
- osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
- osu.Framework/Graphics/Video/VideoDecoder.cs
- osu.Framework/IO/Network/WebRequest.cs
- osu.Framework/Input/Handlers/Tablet/AbsoluteTabletMode.cs
- osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs
- osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
- osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
- osu.Framework/Input/Handlers/Tablet/TabletInfo.cs
- osu.Framework/Localisation/CultureInfoHelper.cs
- osu.Framework/Platform/DesktopGameHost.cs
- osu.Framework/Platform/Windows/WindowsGameHost.cs
- osu.Framework/Properties/AssemblyInfo.cs
- osu.Framework/RuntimeInfo.cs
- osu.Framework/Statistics/BackgroundStackTraceCollector.cs
- osu.Framework/Statistics/DotNetRuntimeListener.cs
- osu.Framework/osu.Framework.csproj
Not much to say here. Tested to work correctly on macOS and iOS.
> Move away from .NET Standard

- osu.Framework/Platform/OsuTKGraphicsSurface.cs
Noticed while working towards #5590.
> Fix osuTK graphics surface causing mobile platforms to crash

- osu.Framework.Tests/Visual/Platform/TestSceneCurrentDisplay.cs
- osu.Framework/Platform/DisplayMode.cs
- osu.Framework/Platform/IWindow.cs
- osu.Framework/Platform/WindowState.cs
`OsuTKWindow` is not considered here.
> Apply NRT in `IWindow` and related classes

- osu.Framework.Tests/Visual/Sprites/TestSceneAnimationLayout.cs
- osu.Framework/Statistics/PerformanceMonitor.cs
Similar to https://github.com/ppy/osu/pull/22531.
> Apply a few new rider quick fixes

- osu.Framework.Tests/Visual/Drawables/TestSceneColourInfoInterpolation.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneColourPartialQuad.cs
- osu.Framework/Graphics/Colour/ColourInfo.cs
Used in 2 places osu-side already and seems like it belongs in the framework.
Naming can most likely be improved.
> Implement `ColourInfo.Interpolate(Quad)` function

- .github/workflows/build-ffmpeg.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-nativelibs.yml
- .github/workflows/deploy-pack.yml
Aiming to stop warnings which are telling us we need to do this (see https://github.com/ppy/osu-framework/actions/runs/4383176901).
> Update github actions to latest versions

- osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
- osu.Framework/osu.Framework.csproj
Contains:
- https://github.com/mellinoe/veldrid/pull/482
- https://github.com/mellinoe/veldrid/pull/481
- https://github.com/mellinoe/veldrid/pull/483
> Switch to using custom veldrid fork

- .github/workflows/deploy-pack.yml
Similar to https://github.com/ppy/osu-framework/pull/5691 but for deployment (see failure at https://github.com/ppy/osu-framework/actions/runs/4486862499/jobs/7889746150#step:6:38)
> Fix android restore for deployment github action

- osu.Framework/Platform/GameHost.cs
See https://github.com/ppy/osu/issues/23003
See https://github.com/ppy/osu/issues/22978
> Disable GL renderers on iOS pending fixes

- osu.Framework/osu.Framework.csproj
Includes https://github.com/mellinoe/veldrid/pull/491, which improves song select performance for me like 10x.
> Update veldrid to include desktop metal performance fix

- osu.Framework/osu.Framework.csproj
Pulls in all recent changes from @frenzibyte.
> Update veldrid package

- osu.Framework/Graphics/BufferedDrawNode.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
- osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
- osu.Framework/Graphics/DrawNode.cs
- osu.Framework/Graphics/OpenGL/Buffers/GLFrameBuffer.cs
- osu.Framework/Graphics/OpenGL/GLRenderer.cs
- osu.Framework/Graphics/Rendering/Dummy/DummyFrameBuffer.cs
- osu.Framework/Graphics/Rendering/IFrameBuffer.cs
- osu.Framework/Graphics/Rendering/Renderer.cs
- osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
- osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
- osu.Framework/Platform/GameHost.cs
This reverts commit 300b8d7a2b638a1fb7d13608528902e0c3c6d014, reversing
changes made to 68eecb7656dd0dbef3d8a9e13850fdf7cc0de7f0.
> Revert "Merge pull request #5745 from frenzibyte/separate-framebuffer-pass"

- .editorconfig
- osu-framework.sln.DotSettings
- osu.Framework.Tests/Visual/Containers/TestSceneBufferedContainerClipping.cs
- osu.Framework/Platform/SDL2DesktopWindow.cs
Seen a few PRs come up doing this wrong (one slipped through osu! side as well).
> Prefer block scoped namespaces

- osu-framework.sln.DotSettings
- osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
- osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
- osu.Framework.Tests/Visual/Containers/TestSceneCursorContainer.cs
- osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBox.cs
- osu.Framework.Tests/Visual/Drawables/TestSceneSynchronizationContext.cs
- osu.Framework/Audio/Track/TrackBass.cs
- osu.Framework/Input/Bindings/KeyBindingContainer.cs
- osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Fixes warnings when using a local framework checkout.
> Change method group inspection to warning to match osu!

- osu.Framework/Graphics/Cursor/CursorContainer.cs
Closes https://github.com/ppy/osu/issues/23547.
> Fix event bindings from long press flow in `CursorContainer` not being cleaned up

- global.json
In line with https://github.com/ppy/osu/pull/23595.
Closes #5799
> Pin builds to .NET 6

- osu.Framework.SourceGeneration/SyntaxHelpers.cs
This was mentioned in other PRs [here](https://github.com/ppy/osu-framework/pull/5763#discussion_r1190359079) and [here](https://github.com/ppy/osu-framework/pull/5761#discussion_r1190341674). Seems like something we should do.
> Match BDL SGen attributes by full type name

- osu.Framework.Tests/Dependencies/Reflection/DependencyContainerTest.cs
- osu.Framework.Tests/Dependencies/Reflection/ResolvedAttributeTest.cs
- osu.Framework.Tests/Dependencies/SourceGeneration/DependencyContainerTest.cs
- osu.Framework.Tests/Dependencies/SourceGeneration/ResolvedAttributeTest.cs
- osu.Framework/Graphics/Sprites/IHasLineBaseHeight.cs
- osu.Framework/Graphics/Textures/TextureTooLargeForGLException.cs
- osu.Framework/Graphics/Transforms/IEasingFunction.cs
- osu.Framework/Graphics/Transforms/ITransformSequence.cs
- osu.Framework/Graphics/UserInterface/Button.cs
- osu.Framework/Graphics/Visualisation/TreeContainerStatus.cs
- osu.Framework/IO/Network/RequestParameterType.cs
- osu.Framework/IUpdateable.cs
- osu.Framework/Input/ConfineMouseMode.cs
- osu.Framework/Input/IHandleGlobalKeyboardInput.cs
- osu.Framework/Input/IRequireHighFrequencyMousePosition.cs
- osu.Framework/Input/ISuppressKeyEventLogging.cs
- osu.Framework/Input/PlatformAction.cs
- osu.Framework/Input/StateChanges/ButtonStateChangeKind.cs
- osu.Framework/Input/TabletAuxiliaryButton.cs
- osu.Framework/Input/TabletPenButton.cs
- osu.Framework/Input/TouchSource.cs
Applied via codefix from [new Rider inspections](https://blog.jetbrains.com/dotnet/2023/05/15/rider-2023-2-eap1/#C#inspectionsfor#nullabledirectivesandNRTannotations).
> Remove redundant nullable suppression directives

- osu.Framework.SourceGeneration/Generators/HandleInput/HandleInputSourceEmitter.cs
Not sure how this snuck its way in. Non-EAP rider.
> Fix stray inspection showing up in rider

- osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
- osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
- osu.Framework/Graphics/Containers/BufferedContainer.cs
- osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
Fixes https://github.com/ppy/osu-framework/issues/5861
> Don't apply `RenderBufferFormat`s to effect buffers

- osu.Framework.Android/AndroidGameView.cs
- Fixes https://github.com/ppy/osu/issues/22940
> Fix android safe area not updating after returning to game with a different orientation

- .github/workflows/deploy-pack.yml
Logic taken from https://github.com/ppy/osu-web/blob/master/.github/workflows/pack.yml.
Haven't tested, will do next release.
> Update deployment workflow to automatically run on new tag

- osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
Fixes caching for these shaders.
> Make shaders with passthrough layouts deterministic again

- osu.Framework.Benchmarks/GameBenchmark.cs
| ![JetBrains Rider 2023-07-03 at 08 26 51](https://github.com/ppy/osu-framework/assets/191335/daee1ba2-6277-4300-a918-c3a96b17ab89) | ![JetBrains Rider 2023-07-03 at 08 25 00](https://github.com/ppy/osu-framework/assets/191335/7e0a8066-5f50-4445-8adf-ed53c20d63fe) |
> Fix game benchmarks being completely broken

- osu.Framework.Tests/Visual/Performance/TestSceneVertexUploadPerformance.cs
- osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
- osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
- osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBufferStorage.cs
See https://github.com/ppy/osu-framework/pull/5913#issuecomment-1628381235.
> Revert recent changes to UBO upload method for non-metal renderers for now

- osu.Framework.Tests/Visual/Performance/PerformanceTestScene.cs
- osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
- osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
- osu.Framework.Tests/Visual/Platform/TestSceneRaiseWindow.cs
- osu.Framework.Tests/Visual/Platform/TestSceneWindowed.cs
- osu.Framework/Testing/TestBrowser.cs
- osu.Framework/Testing/TestScene.cs
Since it was quite common to have a "do nothing" step, this makes sense as an option.
> Add option to avoid automatically running the first step in `TestScene`s

- osu.Framework/Utils/Interpolation.cs
- Works around https://github.com/dotnet/runtime/issues/89359
- Required for enabling AOT on osu!.
> Fix custom interpolation functions potentially causing SIGSEGV on iOS

- osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
- osu.Framework.Tests/Shaders/TestShaderLoading.cs
- osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
- osu.Framework/Graphics/OpenGL/GLRenderer.cs
- osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
- osu.Framework/Graphics/Rendering/Renderer.cs
- osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
- osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
Prereqs:
There will soon be other buffers bound here.
> Refactor global UBO binding

- osu.Framework.iOS/osu.Framework.iOS.Workarounds.targets
Reported in https://discord.com/channels/188630481301012481/188630652340404224/1139427983132725351
> Update workarounds file to fix iOS AOT build issues via command line

- SampleGame.Android/AndroidManifest.xml
- osu.Framework.Android/Properties/AssemblyInfo.cs
- osu.Framework.Tests.Android/AndroidManifest.xml
[Google wants this done by August 31.](https://developer.android.com/google/play/requirements/target-sdk)
The implications of this for framework projects appear to be minimal. The biggest one is probably the change to media permissions which makes them more granular - but we're not handling the permission granting flow correctly yet anyways, so it's really a nothingburger.
That said, to test the visual tests file picker, the visual tests android project now requests the three media permissions (but you still have to enable them yourself via the system UI). Not declaring them means that you couldn't even do that.
This will introduce a new build warning:
```
Microsoft.Android.Sdk.Tooling.targets(68, 5): [XA1008] The TargetFrameworkVersion (Android API level 31) is lower than the …
```
> Bump Android target SDK version to 33

- osu.Framework/Graphics/Shaders/ShaderCompilationStore.cs
To be used in conjunction with changes like https://github.com/ppy/veldrid-spirv/pull/4
> Add a cache busting mechanism to the shader compilation cache

- osu.Framework/osu.Framework.csproj
Don't mind the version name being weird.
> Update native libraries

- osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
- osu.Framework/Timing/FramedClock.cs
- osu.Framework/Timing/IFrameBasedClock.cs
- osu.Framework/Timing/ISourceChangeableClock.cs
- osu.Framework/Timing/InterpolatingFramedClock.cs
Just some initial preparation  for ongoing changes I will be making. This one should have no functional differences, and is intending to bring the class' code quality up to scratch before I begin to take things apart.
> Tidy up `InterpolatingFramedClock`

- osu.Framework.NativeLibs/scripts/ffmpeg/build-linux.sh
See https://github.com/ppy/osu-framework/pull/6013#issuecomment-1745935903
> Disable linux video hardware acceleration for now

- osu.Framework/osu.Framework.csproj
Pulls in new (restored) video codecs.
> Update native libs

- osu.Framework/Platform/SDL2Window.cs
- (wrongly) reported in https://github.com/ppy/osu/issues/25368#issuecomment-1793771361
Untested.
https://github.com/libsdl-org/SDL/blob/9302d7732dfbb3c6364da142efd06ea9846206c1/include/SDL3/SDL_hints.h#L1226-L1233
> Fix mouse not working as expected on iOS

- osu.Framework/Logging/LoadingComponentsLogger.cs
> Uncomment .NET 6 logging code

- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
I have been looking towards https://github.com/ppy/osu/issues/24315, and the test scene was way dated and quite bothersome to use, so I figured it was time to refactor it.
> Refactor dropdown test scene thoroughly

- osu.Framework/Audio/AudioManager.cs
- osu.Framework/Threading/AudioThread.cs
Need some more time to test this out. As I kinda expected, it doesn't work well across the board.
> Disable WASAPI initialisation mode for now

- osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Addresses https://github.com/ppy/osu-framework/issues/6117.
> Fix frame statistics display GC boxes not correctly being cleaned up

- osu.Framework/Input/UserInputManager.cs
- osu.Framework/Platform/IWindow.cs
- osu.Framework/Platform/OsuTKWindow.cs
- osu.Framework/Platform/SDL2Window_Windowing.cs
| ![CleanShot 2024-01-11 at 04 59 22](https://github.com/ppy/osu-framework/assets/191335/71f93dee-0d67-4275-a68c-84edbf5ff5f7) | ![CleanShot 2024-01-11 at 04 59 54](https://github.com/ppy/osu-framework/assets/191335/f2305123-5e65-4f87-a2d1-0217c5c9b980) |
> Remove allocations when checking if mouse outside all displays

- osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Just one, though. Low priority. At this point I'm just trying to get a clean slate.
> Remove overheads of MIDI device polling

- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Used very liberally in osu! hitobjects.
`ThreadStatic` is used because this can be used from:
- Either of the BDL load threads.
- The update thread.
The cost of `ThreadStatic` becomes basically negligible in .NET 8, but this pathway is not hot enough to cause performance issues on its own: https://github.com/smoogipoo/Benchmarks/blob/37dc7c07b16cc1dd4898987a06c43cce438150c9/BenchmarksProject/BenchmarkThreadStatic.cs
Before:
|                     Method |     Mean |   Error |  StdDev |    Gen0 | Allocated |
|--------------------------- |---------:|--------:|--------:|--------:|----------:|
|               NonRecursive | 972.8 us | 1.89 us | 1.68 us |       - |     187 B |
|                  Recursive | 972.7 us | 2.70 us | 2.52 us |  9.7656 |   24259 B |
| SlightlyNestedNonRecursive | …
> Reduce allocations when calling BeginAbsoluteSequence()

- osu.Framework.Tests/Visual/Layout/TestSceneGridContainer.cs
- osu.Framework.Tests/Visual/Sprites/TestSceneAnimationLayout.cs
- osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
- osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
- osu.Framework/Graphics/Containers/GridContainer.cs
- osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
Helps in container nesting reduction.
(34b3fda4b68306d3165a5e542d9a231e2c24c8dd includes some examples, is osu there are quite a few as well)
> Implement `Padding` property in `GridContainer`

- osu.Framework/Input/InputManager.cs
Just a very minor one. Avoids allocating when nothing has changed by reusing the object we just made earlier, rather than recreating.
| ![CleanShot 2024-01-21 at 05 31 01](https://github.com/ppy/osu-framework/assets/191335/7ced0238-c747-4c69-8c10-7d580b680610) | ![CleanShot 2024-01-21 at 05 30 06](https://github.com/ppy/osu-framework/assets/191335/bde4bcb7-876a-407f-808f-b1a151ce2193) |
Test:
```diff
diff --git a/SampleGame/SampleGameGame.cs b/SampleGame/SampleGameGame.cs
index ae72ffa24..50852edd6 100644
--- a/SampleGame/SampleGameGame.cs
+++ b/SampleGame/SampleGameGame.cs
@@ -7,6 +7,8 @@
using osuTK.Graphics;
using osu.Framework.Graphics.Shapes;
using osu.Framework.Allocation;
+using osu.Framework.Input;
+using osu.Framework.Input.Events;
namespace …
```
> Reduce mouse move overhead when `IRequireHighFrequencyMousePosition` are present

- osu.Framework.Tests/Visual/Drawables/TestSceneTransformSequence.cs
- osu.Framework/Graphics/Containers/CompositeDrawable.cs
Whoops. I forgot to consider this possibility.
Fixes the errors in https://github.com/ppy/osu/pull/26772#issuecomment-1914287313
> Fix nested absolute sequences

- osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
- osu.Framework/Graphics/Cursor/TooltipContainer.cs
Values have been taken in `TooltipTestScene` while hovering a drawable with a tooltip within 20s timespan.
|master|pr|
|---|---|
|![master](https://github.com/ppy/osu-framework/assets/22874522/c0c248e4-c1cd-4780-af8f-0c57b9d72af8)|![pr](https://github.com/ppy/osu-framework/assets/22874522/6b0a0e70-49c6-4388-a546-5c0e6e78ef2a)|
> Reducle allocations in `CursorEffectContainer` and `TooltipContainer`

- osu.Framework/Audio/Track/Waveform.cs
This fixes the first two failures in https://github.com/ppy/osu/issues/27588. In those cases, BASS appears to die on internal errors (`Codec` in the first case, `FileFormat` in the second). Weirdly enough no errors seem to happen when the same failing files are interpreted as _samples_ :shrug: 
Relevant docs:
- [`BASS_StreamCreate()`](https://www.un4seen.com/doc/#bass/BASS_StreamCreate.html)
- [`BASS_ChannelGetInfo()`](https://www.un4seen.com/doc/#bass/BASS_ChannelGetInfo.html)
- [`BASS_ChannelGetLength()`](https://www.un4seen.com/doc/#bass/BASS_ChannelGetLength.html)
- [`BASS_ChannelGetData()`](https://www.un4seen.com/doc/#bass/BASS_ChannelGetData.html)
- [`BASS_ChannelSetPosition()`](https://www.un4seen.com/doc/#bass/BASS_ChannelSetPosition.html)
- …
> Check BASS error codes more diligently when retrieving waveform data

- osu.Framework.Tests/Visual/UserInterface/TestSceneTabControlEvents.cs
- osu.Framework/Graphics/UserInterface/TabControl.cs
- osu.Framework/Graphics/UserInterface/TabItem.cs
- As proposed in https://github.com/ppy/osu/pull/27657#issuecomment-2060100727
See https://github.com/ppy/osu/compare/master...frenzibyte:osu:add-sound-to-tab-selection-change-2 for the benefit of this change in osu!.
> Move user tab selection events to `TabItem`s

- osu.Framework/Platform/SDL3Window.cs
Sample output:
```cs
2024-04-22 19:52:27 [verbose]: SDL3 Initialized
2024-04-22 19:52:27 [verbose]: SDL3 Version: 3.1.1
2024-04-22 19:52:27 [verbose]: SDL3 Revision: SDL-a2eb269
```
The revision shows the commit hash: https://github.com/libsdl-org/SDL/commit/a2eb269.
> Log SDL3 version and revision on successful initialisation

- osu.Framework/Graphics/Rendering/Deferred/DeferredFrameBuffer.cs
- osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
- osu.Framework/Graphics/Veldrid/Pipelines/GraphicsPipeline.cs
- osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
- osu.Framework/Graphics/Veldrid/Textures/VeldridVideoTexture.cs
- osu.Framework/Graphics/Veldrid/VeldridDevice.cs
- osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
- osu.Framework/osu.Framework.csproj
Prereqs:
These are the breaking changes required resulting from https://github.com/ppy/veldrid/pull/45
@peppy Don't make a Veldrid package immediately. I just wanted this PR so it's easier for me to test across different platforms.
> Apply breaking changes from Veldrid

- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
- osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
See `TestSceneOsuDropdown` failures in https://github.com/ppy/osu/pull/28286
> Add back support for opening dropdown by setting internal states

- osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
- osu.Framework/Graphics/UserInterface/Dropdown.cs
Will fix the skin editor layer dropdown crashing on select.
> Fix crash when dropdown is removed from hierarchy during select

- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework/osu.Framework.csproj
Pulls in https://github.com/ppy/SDL3-CS/pull/90
> Upgrade SDL3 package

- osu.Framework/Graphics/Containers/ScrollContainer.cs
Noticed in https://github.com/ppy/osu/pull/28553#discussion_r1660525764.
Before:
https://github.com/ppy/osu-framework/assets/22781491/d418b994-422e-4ea0-9b42-4b0b9784e5c3
After:
https://github.com/ppy/osu-framework/assets/22781491/e5e88fef-cb75-4c22-a817-83267e5f696c
> Add lenience to scrollbar visibility conditionals

- osu.Framework/Graphics/Rendering/Deferred/DeferredFrameBuffer.cs
Fixes https://github.com/ppy/osu/issues/28855
> Fix deferred FBO depth target texture leak

- .vscode/launch.json
> Fix SampleGame prelaunch tasks

- osu-framework.sln.DotSettings
- Counterpart for https://github.com/ppy/osu/pull/28934#event-13566251869
> Disable multi-line trailing comma inspections entirely

- osu.Framework.Android/AndroidGameActivity.cs
- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework.iOS/IOSWindow.cs
- osu.Framework/Platform/MacOS/SDL3MacOSWindow.cs
- osu.Framework/Platform/SDL3/SDL3Clipboard.cs
- osu.Framework/Platform/SDL3/SDL3GraphicsSurface.cs
- osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
- osu.Framework/Platform/SDL3/SDL3Window.cs
- osu.Framework/Platform/SDL3/SDL3Window_Windowing.cs
- osu.Framework/osu.Framework.csproj
With thanks to @hwsmm 
Intended to eventually work towards https://github.com/ppy/osu/issues/24041#issuecomment-2272478408
Testing:
> Update SDL3 bindings

- osu.Framework/osu.Framework.csproj
Pulls in https://github.com/atsushieno/managed-midi/pull/74.
Closes https://github.com/ppy/osu-framework/issues/4486.
> Update managed-midi to fix disposal issue

- osu.Framework/Graphics/UserInterface/BasicTextBox.cs
Just noticed in passing that it looks kinda wrong as it stands.
> Change textbox deletion animation easing to closer match gravity

- osu.Framework/Game.cs
- osu.Framework/IO/Stores/OnlineStore.cs
> Allow rewriting URL lookups in `OnlineStore`

- osu.Framework/Platform/SDL3/SDL3GraphicsSurface.cs
As per https://github.com/libsdl-org/SDL/issues/9430 / https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_syswmh.
> Implement getting OpenGL iOS main framebuffer on SDL3

- osu.Framework.iOS/GameApplicationDelegate.cs
There's no proper method to access the game host anywhere in an iOS project so I'm opening this PR to expose it as a property in the app delegate class.
> Expose game host from iOS app delegate class

- osu.Framework.Android/osu.Framework.Android.csproj
- osu.Framework/osu.Framework.csproj
- Closes https://github.com/ppy/osu/issues/28212
Tested to boot fine on android and windows.
> Update SDL3-CS to 2025.104.0

- osu.Framework/Game.cs
- osu.Framework/Platform/GameHost.cs
See https://github.com/ppy/osu/pull/31417 for usage. Basically I need a way to get sentry a `Storage` as early as possible as to capture the maximum exceptions.
> Add entry point to `Game` for logging setup purposes

- .github/workflows/deploy-pack.yml
Missed in https://github.com/ppy/osu-framework/pull/6505
https://github.com/ppy/osu-framework/actions/runs/13013778518/job/36297705258
> Roll back windows runner in another android workflow

- osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
- osu.Framework/Graphics/Containers/TextFlowContainer.cs
Resolves https://github.com/ppy/osu/discussions/32400
> Fix text flow container not handling non-1 relative width correctly

- osu.Framework.Tests/Text/TextBuilderTest.cs
- osu.Framework/Text/CharacterGlyph.cs
- osu.Framework/Text/MultilineTextBuilder.cs
- osu.Framework/Text/TextBuilder.cs
- osu.Framework/Text/TruncatingTextBuilder.cs
Remove nullable disable annotation in the text namespace.
After 2 years after #5307, i guess no conflict now.
> Remove nullable disable annotation in the text namespace.

- osu.Framework/osu.Framework.csproj
Tested for around 10 minutes with framework and osu! (macOS / windows 11), can't find any immediate issues.
> Update native libraries with latest bass versions

- osu.Framework/Bindables/BindableNumber.cs
Hopefully resolves https://github.com/ppy/osu/issues/32374
Using solution in https://github.com/ppy/osu/issues/32374#issuecomment-3052214849
> Work around subnormal floats being flushed to zero

- .github/workflows/ci.yml
- .github/workflows/deploy-pack.yml
We use this in the deploy workflow where we haven't had issues, so just pulling it down to here too.
> Force Xcode 16.4 on CI

- osu.Framework/osu.Framework.csproj
Includes https://github.com/ppy/SDL3-CS/pull/253 which should fix Android builds.
> Update SDL3-CS to 2025.920.0
