ppy/osu-framework

osu.Framework/osu.Framework.csproj
Rolling back due to a broken package (https://github.com/aspnet/Extensions/issues/2750).
=> Revert Microsoft.Extensions.ObjectPool update

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Threading/Scheduler.cs
This is the only thing I can think of that could cause https://ci.appveyor.com/project/peppy/osu-framework/builds/29385150 since it schedules from inside a scheduled delegate, though I'm not sure on the exact case or how it could happen given the testing procedure.
=> Fix scheduler running in-place unintentionally

osu.Framework/Bindables/BindableDouble.cs, osu.Framework/Bindables/BindableFloat.cs, osu.Framework/Bindables/BindableInt.cs, osu.Framework/Bindables/BindableLong.cs, osu.Framework/Bindables/BindableNumber.cs
Generally makes working with `BindableNumber<>` a lot better.
=> Combine BindableNumber implementations into base class

osu.Framework/Platform/GameHost.cs
Fixes tests causing system-wide hangs.
=> Don't initialise toolkit in headless mode

osu.Framework/Testing/TestBrowser.cs
Previously it was feasible for cross-test pollution, for instance in the shared `Game` context, as the previous test was disposed only after a new one was loaded.
=> Ensure test isolation in TestBrowser by disposing eagerly

osu.Framework/Graphics/Video/VideoDecoder.cs
If a video was not present, scheduled events were added even if the state hadn't changed due to missing early return (and non-matching delegate in `AddOnce`).
=> Fix runaway scenario in video decoding loop

osu.Framework/Platform/GameHost.cs
Previously the frame sync rate was always based on the refresh rate of the primary display.
The only caveat is that moving the window between displays will not automatically update the frame sync to the correct refresh rate until a change is triggered.
Needs testing on a system with multiple refresh rates.  I don't have access to one.
Note that this inadvertently fixes the broken macOS menu focus on the SDL branch as osuTK's `DisplayDevice` is no longer being initialised.
Related to #3013
=> Set framesync based on the refresh rate of the current display

osu.Framework.Android/AndroidGameWindow.cs, osu.Framework.iOS/IOSGameWindow.cs
Resolves https://github.com/ppy/osu/issues/7282
Regression from #3117 
The `CurrentDisplay` property in osuTK's Android and iOS implementations throws a `NotImplementedException`.  This change ensures we return null instead, which will then default to 60hz as per #3117 
The better solution would be to correctly implement `CurrentDisplay` and `DisplayDevice` in osuTK for iOS and Android, but this is non-trivial and an extreme edge case.  This problem can be easily solved with the SDL2 migration.  I would also like to avoid any and all large changes to osuTK where possible.
Edit: Would appreciate if someone could please test this on Android for me, as I do not have an Android device to test with.
=> Fix framesync regression on Android and iOS

osu.Framework/Testing/MenuTestScene.cs, osu.Framework/Testing/TestingExtensions.cs
Hopefully simple enough that test coverage is not required.
=> Add extension method to easily access children of a specific type without manual traversal

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
As there can be many similar tab controls on any one screen, the one with the highest depth will absorb all input. This change makes it more manageable by manually setting it where it's needed, and avoids nested classes.
=> Change TabControl.IsSwitchable to property

osu.Framework/IO/Stores/ResourceStore.cs
Closes https://github.com/ppy/osu/issues/7216.
See https://github.com/dotnet/runtime/issues/1149 for reasoning.
=> Ensure ResourceStore returns null rather than exception on null request

osu.Framework/Graphics/Drawable.cs
For patterns such as:
```
protected virtual Drawable CreateXYZ() => new Container();
```
which can now be written as:
```
protected virtual Drawable CreateXYZ() => Drawable.Empty;
```
Where: returning `null` feels wrong in hierarchical construction, and returning a `Container` feels arbitrary.
Note: Empty Drawable instances aren't shared.
=> Add Drawable.Empty static helper for empty construction

osu.Framework/Graphics/Drawable.cs
See discussion in https://github.com/ppy/osu-framework/pull/3143
Microsoft also seem to use this convention when `Empty()` creates a new instance, such as https://source.dot.net/#System.Linq.Expressions/System/Linq/Expressions/DefaultExpression.cs,52
=> Change Drawable.Empty to a method

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
alternative to https://github.com/ppy/osu-framework/pull/1962
This PR moves UserAgent assigning from `DefaultRequestHeaders` to `internalPerform` and makes it customizable via `WebRequest.UserAgent` virtual property.
=> Set UserAgent on WebRequest level

osu.Framework/Audio/Sample/SampleChannelBass.cs
Applies same fix as seen in https://github.com/ppy/osu-stable-issues/issues/286.
Search for `BASS_ATTRIB_NORAMP` on http://www.bass.radio42.com/help/html/f00d6245-b20b-f37d-7982-8cc6549f4ae3.htm for full details.
=> Disable sample ramping

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework/Bindables/Bindable.cs
I guess we should not allow binding to the same object multiple times.
=> Disallow binding to already bound object

osu.Framework/Graphics/Containers/ScrollContainer.cs
Fixes https://github.com/ppy/osu/issues/7471
Was causing a crash osu!-side due to uninitialised `DrawSize`
```
Unhandled exception. System.ArgumentException: '10' cannot be greater than 1.
at System.Math.ThrowMinMaxException[T](T min, T max)
at osu.Framework.Graphics.Containers.ScrollContainer`1.updateScrollbar()
at osu.Framework.Graphics.Containers.ScrollContainer`1.set_ScrollbarVisible(Boolean value)
at osu.Game.Overlays.SearchableList.SearchableListOverlay`3..ctor() in /Users/dean/Projects/osu/osu.Game/Overlays/SearchableList/SearchableListOverlay.cs:line 40
at osu.Game.Overlays.DirectOverlay..ctor() in /Users/dean/Projects/osu/osu.Game/Overlays/DirectOverlay.cs:line 86
at osu.Game.OsuGame.LoadComplete() in /Users/dean/Projects/osu/osu.Game/OsuGame.cs:line 611
at …
```
=> Fix ScrollBarVisible calling unsafe method before loaded

osu.Framework.Benchmarks/BenchmarkWeakList.cs
Might as well, while I'm here.
Before https://github.com/ppy/osu-framework/pull/3165
|            Method |           Mean |        Error |       StdDev |         Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |---------------:|-------------:|-------------:|---------------:|------:|------:|------:|----------:|
|               Add |     2,794.2 ns |    183.73 ns |    533.04 ns |     2,689.0 ns |     - |     - |     - |      80 B |
|            Remove |       389.6 ns |     11.60 ns |     22.35 ns |       388.0 ns |     - |     - |     - |         - |
|        RemoveEach | 4,202,945.1 ns | 79,652.43 ns | 74,506.93 ns | 4,207,885.5 ns |     - |     - |     - |         - |
|             Clear |     5,859.6 ns |     84.51 ns |     74.92 ns |     5,834.5 ns |     - |     - | …
=> Add weaklist benchmarks

osu.Framework.Benchmarks/BenchmarkWeakList.cs, osu.Framework/Lists/WeakList.cs
```diff
|               Method | ItemCount |           Mean |        Error |       StdDev | Ratio | RatioSD |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|--------------------- |---------- |---------------:|-------------:|-------------:|------:|--------:|--------:|-------:|------:|----------:|
- |                  Add |         1 |       228.5 ns |      2.95 ns |      2.62 ns |  1.00 |    0.00 |  0.0319 |      - |     - |     168 B |
+ |                  Add |         1 |       217.2 ns |      0.47 ns |      0.42 ns |  1.00 |    0.00 |  0.0260 |      - |     - |     136 B |
- |            RemoveOne |         1 |       251.9 ns |      1.47 ns |      1.38 ns |  1.10 |    0.01 |  0.0319 |      - |     - |     168 B |
+ |            RemoveOne |         1 |       226.6 ns |      1.30 ns |      1.15 …
```
=> Improve performance/allocations of WeakList

osu.Framework.Tests/Containers/TestSceneContainerState.cs, osu.Framework/Graphics/Containers/Container.cs
Useful for cases where you want to iterate over only alive children for performance reasons, e.g.:
https://github.com/ppy/osu/blob/ef735f106e0899fc11554b7d290d4c5bd1262323/osu.Game/Rulesets/UI/HitObjectContainer.cs#L16
https://github.com/ppy/osu/blob/ef735f106e0899fc11554b7d290d4c5bd1262323/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs#L484
=> Expose alive children from Container

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/UserInterface/TabItem.cs
Fixes https://github.com/ppy/osu-framework/issues/2659
Current weirdnesses (not caused by this PR):
1. The `Enabled` state of `TabItem`s isn't used as a precondition to invoking `ActivationRequested`. It can't be either, since `Enabled` is false by default (`TabItem`s aren't generally given an `Action`).
2. `TabItem`s are `ClickableContainer`s, meaning they invoke their own actions on click.
3. `TabItem`s have their own individual `Enabled` state.
All of these should probably not exist:
1. `TabItem` should probably be a `CompositeDrawable`.
2. `TabItem` should not have an `Enabled` state.
3. `TabItem` should not have/should not invoke its own `Action`.
But all of those are breaking changes and not done in this PR.
=> Make tab control not change tabs when clicked in a disabled state

osu.Framework.Tests/Bindables/BindableTest.cs, osu.Framework/Bindables/Bindable.cs
In my usage, this failed when parsing a `long` as a `double`, even though it's a supported conversion type in .NET.
Enum parsing was/is tested in `BindableEnumTest`.
=> Make Bindable.Parse() support all .NET conversions

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
Fixes https://github.com/ppy/osu-framework/issues/2813
It does make `Items` become ordered by addition order, but there's only one case osu!-side which relied on this, and arguably did so in a way that should be handled by `TabControl` itself (`ChannelTabControl`).
I'd say it's best to remove in favour of simplification and to fix the mentioned issue.
=> Make TabControl better return contained items

osu.Framework/Audio/AudioManager.cs
Helps investigating cause of #3176 
- Errors will be logged as `BASS failed to initialize with error code 0: Name.`.
=> Return if BASS failed to initialize instead of throwing assert exception

osu.Framework.Tests/Bindables/BindableLeasingTest.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/LeasedBindable.cs
- Forgotten override after addition of modifiable `Default` in #3123
Closes #3108
=> Fix binding leased to bindable potentially throwing exceptions

osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs, osu.Framework.Tests/Visual/Audio/TestSceneTrackAdjustments.cs, osu.Framework.Tests/Visual/Containers/TestScenePadding.cs, osu.Framework.Tests/Visual/Containers/TestSceneSizing.cs, osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs, osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs, osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs, osu.Framework.Tests/Visual/Sprites/TestSceneBufferedContainerView.cs, osu.Framework.Tests/Visual/Sprites/TestSceneTriangles.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Graphics/Visualisation/TitleBar.cs, osu.Framework/Testing/Drawables/Steps/StepSlider.cs, osu.Framework/Testing/Input/ManualInputManager.cs
While working on a related fix, I found an issue relating to mouse input whereby a hierarchy that received mouse-down events may not receive mouse-up events if a drawable above them blocked it.
This isn't limited to `OnMouseUp`, but all mouse-release events (`OnMouseUp`, `OnDrag`, `OnDragEnd`), for lack of better naming.
I'm doing this only for mouse events for now since they're the only input events that are correctly. Key, joystick, and keybinding events are all broken in other ways (I'm working on fixing them). Those other events will be changed after said fixes have been applied.
Here's an example illustrating this, although this isn't really testable anymore (hence why I haven't added a test):
```csharp
[Test]
public void DoTest()
{
var receptors = new InputReceptor[3]; …
```
=> Make OnDrag, OnDragEnd, and OnMouseUp return void instead of bool

osu.Framework.Tests/Input/JoystickInputTest.cs, osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs, osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs, osu.Framework/Graphics/Drawable.cs
Prereqs:
This event can no longer be blocked by other `Drawable`s in the hierarchy.
This guarantees that `Drawable`s that have received the respective `OnJoystickPress` event will receive accompanying `OnJoystickRelease` event.
=> Make OnJoystickRelease return void instead of bool

osu.Framework.Tests/Input/KeybindingInputTest.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingInputQueueChange.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/DropdownHeader.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/Bindings/IKeyBindingHandler.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Testing/TestBrowser.cs
I've re-implemented the same "remove subsequent drawables from input queue" from https://github.com/ppy/osu-framework/pull/3191, as a temporary measure to homogenise input handling.
`KeyBindingContainer` was already changed recently to correctly handle per-keybind input queues, so this was the only thing missing from it.
I've got a WIP branch (https://github.com/smoogipoo/osu-framework/tree/keybinding-event-manager) that attempts to use the new `ButtonEventManager` for keybindings, but the entirety of `KeyBindingContainer` needs to be re-thought instead because it's doing some weird stuff with keeping bindings in a pressed state while the underlying actions aren't pressed, etc. In conclusion, it's not a simple change.
The `OnReleased` method is probably a perfect candidate for a default …
=> Make IKeyBindingHandler<T>.OnRelease return void instead of bool

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
- This would fix cases where newly added text would conflict depths with existing ones which causes ordering and incorrect caret positioning issues.
Before reordering on removal:
After reordering on removal:
Closes #2904
=> Reorder text box characters depth after removal action

osu.Framework/Graphics/Drawable.cs
It's hard to check them all for consistency while they're split out, so I've concatted them:
```
Summaries:
/// An event that occurs every time the mouse is moved while hovering this <see cref="Drawable"/>.
/// An event that occurs when the mouse starts hovering this <see cref="Drawable"/>.
/// An event that occurs when the mouse stops hovering this <see cref="Drawable"/>.
/// An event that occurs when a <see cref="MouseButton"/> is pressed on this <see cref="Drawable"/>.
/// An event that occurs when a <see cref="MouseButton"/> that was pressed on this <see cref="Drawable"/> is released.
/// An event that occurs when a <see cref="MouseButton"/> is clicked on this <see cref="Drawable"/>.
/// An event that occurs when a <see cref="MouseButton"/> is double-clicked on this <see …
```
=> Refactor + add xmldocs to drawable input methods

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs
Still not 100% sure about the underlying input `KeyEventManager` logic here - it changed from previous and now uses the same input queue rather than refreshing it every time.
Regardless, this method would've failed if referenced previously (it's a public API), so I think this is a required fix in any case.
=> Fix ScrollContainer null-reference on key repeat

osu.Framework.Tests/Input/KeyboardInputTest.cs, osu.Framework.Tests/Input/MouseInputTest.cs, osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/KeyEventManager.cs
Similar to the old behaviour. This is probably more expected behaviour from the framework considering that mouse buttons do the same thing on click.
It would also solve the issue presented in https://github.com/ppy/osu-framework/pull/3206, but that's still a valid PR.
Adds further test cases for these scenarios.
=> Make OnKeyDown() repeats only occur on still-valid Drawables

osu.Framework/Testing/TestBrowser.cs
Previous merged method was a bit too aggressive, resulting in empty or illegible step names.
=> Only trim test from test methods

osu.Framework.Tests/Visual/Layout/TestSceneGridContainer.cs, osu.Framework/Graphics/Containers/GridContainer.cs
Resolves #3214.
If a `GridContainer` cell's content is not present and alive at the time of update, do not consider its bounding box dimensions and assume 0 instead.
Various test cases attached, also including setting `IsPresent = true` in addition to `Alpha = 0` to make sure that case still behaves as desired. Can expand if coverage is deemed insufficient.
=> Consider grid cell content presence and lifetime when auto-sizing

osu.Framework.Tests/Bindables/BindableTest.cs
Running `dotnet test` locally rather than via AppVeyor on a fork has revealed that the bindable conversion test was dependent on current system culture due to `Convert.ChangeType` being culture-aware (test failure message complained of a decimal comma instead of a decimal point). Resolve the dependence by passing invariant culture to the `ChangeType` call.
Only noticed this because you can't push only to the fork when updating an existing PR (#3226, to be exact), so I wanted to run tests locally before pushing again and found this in the process.
=> Fix culture dependence in bindable conversion test

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework.Tests/Bindables/BindableTest.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/IBindable.cs, osu.Framework/Bindables/IBindableList.cs
quick and easy.
* Closes #3212.
* Closes #3213.
`BindTarget` has been added as a convenience setter-only property, which is intended to be an alias for `BindTo` in object initializer scenarios.
=> Add BindTarget to IBindable and implementations

osu.Framework/Testing/ManualInputManagerTestScene.cs
Regressed in https://github.com/ppy/osu-framework/pull/3204.
=> Fix ManualInputManager incorrectly starting in wrong input mode

osu.Framework.Tests/Visual/Testing/TestSceneDerivedTest.cs, osu.Framework.Tests/Visual/Testing/TestSceneDerivedTestWithDerivedMethods.cs, osu.Framework.Tests/Visual/Testing/TestSceneDerivedTestWithDerivedMethodsWithAttributes.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestScene.cs
Fixes https://github.com/ppy/osu-framework/issues/3234
Uses internal nunit method to determine the methods to invoke, which is also used by their own code:
https://github.com/nunit/nunit/blob/c7df8ecb5fe8cbcbe26eb2c34e906452bedb77a4/src/NUnitFramework/framework/Internal/Tests/TestFixture.cs#L43-L46
=> Fix test methods potentially being duplicated

osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
There was nothing to stop an exception being thrown was a `Drawable` to be disposed before it started loading in an async context.
- Resolves https://github.com/ppy/osu/issues/7693.
=> Fix drawables potentially becoming disposed during an async load

osu.Framework.Android/Input/AndroidTouchHandler.cs
Mouse position events are sent while the pen is hovering.
Additionally, pressing the pen's side button while hovering will send a right click.
Closes ppy/osu#6401
=> Android pen hover support

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/Transforms/Transformable.cs
While this has not been noticed until now due to how transform methods like FadeInFromZero are implemented (they use two transforms), rewinding between transforms where the `EndValue` was different to the `StartValue` of the next transform could leave us in a bad state. Reverse playback would actually look different to forward playback.
Example (opposite fade direction to implemented test):
=> Apply correct current value on rewind between disparate transforms

osu.Framework.Tests/Visual/Testing/TestSceneManualInputManagerTestScene.cs, osu.Framework/Testing/ManualInputManagerTestScene.cs
The cause of this is that `UseParentInput` is set right after inputs have been enqueued to the pending list, I was quite unsure whether to solve this by applying pending inputs enqueued to `PassThroughInputManager` for the first time `GetPendingInputs()` is invoked **after** `UsePendingInput` is set, so I fixed it here for now.
Also added tests to ensure that this doesn't regress again. (and explicitly checks that `InitialMousePosition` works)
=> Fix ManualInputManagerTestScene not resetting input properly

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/IBindableList.cs, osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Resolves https://github.com/ppy/osu-framework/issues/3081
Follows the model of https://source.dot.net/#System.ObjectModel/System/Collections/ObjectModel/ObservableCollection.cs .
We're going to try out providing the complete event handler with this to:
1. Implement the interface.
2. Follow other implementations such as realm-dotnet.
3. Look into how this affects us in the long term complexity wise. I discovered early on one potential advantage of it, which is as a potential performance improvement to remove a variable capture.
Tests cover both scenarios simultaneously, pending removal in 20200817.
Breaking changes:
The `ItemsAdded` event failed to provide enough context when items are moved around or inserted into the list.
It has been replaced by the `CollectionChanged` …
=> Add BindableList.CollectionChanged event implementing NotifyCollectionChangedEventHandler

osu.Framework/Configuration/IniConfigManager.cs, osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs, osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Platform/NativeStorage.cs, osu.Framework/Testing/TestBrowser.cs
- Replace string.Substring(...).Trim() (or siimlar) calls with string.AsSpan(...).Trim().ToString()
- Replace remaining string.IndexOf(string, StringComparison.Ordinal) call with string.IndexOf(char)
No changes in behaviour.
=> Minor optimizations/cleanups

osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Until now, the mechanism we had in place for background texture uploading had a few issues:
- It would only upload one item per frame
- This wouldn't be so bad, but it would also only process one item, even if it was already uploaded
This was particularly bad when the `FrameStatisticsDisplay` was visible, as it would queue four texture uploads per frame (even though it was only performing one actual upload), causing a runaway scenario where the queue would never recover.
This PR makes the queue aware of the texture's upload and queued state to ensure the queue stays under control. It also allows more than one texture to be uploaded per frame if the queue grows too large.
Should hopefully resolve the issues experienced on https://github.com/ppy/osu-framework/pull/1842/files (I think this …
=> Improve texture queueing mechanism

osu.Framework/Graphics/Video/FFmpegFuncs.cs, osu.Framework/Graphics/Video/VideoDecoder.cs
Add delegate for calling into ffmpeg's `av_strerror` function to retrieve human-readable errors instead of error codes and call it within exception messages instead of directly embedding the numerical code
itself.
While ffmpeg's error messages can sometimes be sort of obtuse (i.e. `Invalid data found when processing input`), they did help me with diagnosing the issues with decoding on linux more than the random error code number.
Tested on Linux and Windows.
=> Improve video decoder error messages

osu.Framework/Graphics/Video/VideoDecoder.cs
Resolves ppy/osu#7947 (or at least the hard crash part of it).
After crashes on startup were reported osu!-side, I investigated and diagnosed two issues with the video decoder that could result in hard crashes.
If video initialisation failed in any way (in my case, it was due to a missing `libavformat.so` on linux), subsequent accesses to `GetConversionMatrix` could crash with a null reference exception due to uninitialised video stream. Guard `GetConversionMatrix()` with a null-check to alleviate this.
If `avformat_open_input()` failed when trying initialising a decoder, but a format context was created, it was possible that during disposal an attempt to call `avformat_close_input()` without a matching open was made, which led to a segfault.
Prevent unmatched close calls by introducing a …
=> Improve initialisation error handling in video decoder

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Statistics/GlobalStatistics.cs, osu.Framework/Statistics/TypePerformanceMonitor.cs
Generally we rely on existing profilers for tracking down performance issues, but as profilers do not show local class names, we end up having to work with this kind of mess:
This solves the issue and gives a quick overview of what components are using the most CPU during their update operations.
- Updates at most once every second for readability purposes.
- Aims to be lowest overhead possible. Split the update loop into two versions to avoid the function call overhead when disabled (it does make a difference).
=> Add update CPU time profiling to global statistics

osu.Framework/Threading/AudioThread.cs
While cleaning up branches I found this lying around. Might as well add it.
=> Report BASS CPU usage to global statistics

osu.Framework/Configuration/FrameworkDebugConfig.cs, osu.Framework/Development/DebugUtils.cs, osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs, osu.Framework/Platform/GameHost.cs
It was kind of a pain to manually turn this on. Now it can easily be toggled by opening global statistics (`Ctrl+F2`).
Performance logging is now toggled by opening "Global Statistics" overlay via Ctrl+F2. To manually toggle it, you may access `GameHost.PerformanceLogging`, but note that a change to this bindable will be overridden by toggling the statistics overlay.
=> Remove debug performance logging setting, instead making it activate when GlobalStatistics is open

osu.Framework/Graphics/Drawable.cs
Calls to get stopwatch time could add a perceivable overhead during execution:
- Only runs when performance logging is turned on.
- Adds logging of async loads which take >100ms (and changed cutoff for blocking loads to 16ms).
=> Reduce the overhead of checking for blocking synchronous drawable loads

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
Until now, we were reading `ElapsedFrameTime` from threads' clock, but only 10 times per second. This means it could be inaccurate if frame times were different between these polls.
- Now considers every frame
- Uses `FrameStatistics.CollectedTimes` instead of `ElapsedFrameTime`. This is a prerequisite for making the elapsed time display actually work with single threaded execution. In practice, this means a small framework overhead may be excluded from the calculation, but if anything this makes the display more correct in its context.
=> Calculate elapsed time values using FrameStatistics source instead of clock

osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Development/ThreadSafety.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/DrawThread.cs, osu.Framework/Threading/GameThread.cs, osu.Framework/Threading/InputThread.cs, osu.Framework/Threading/Scheduler.cs, osu.Framework/Threading/UpdateThread.cs
Allows for more flexibility in switching variables. For single-threaded execution this is imperative to ensure we are running things in the correct context (even though they are all on the same logical thread).
=> Use ThreadStatic for ThreadSafety implementation

osu.Framework.Android/AndroidGameHost.cs, osu.Framework.Android/osu.Framework.Android.csproj, osu.Framework.iOS.props, osu.Framework.iOS/IOSGameHost.cs, osu.Framework.iOS/osu.Framework.iOS.csproj, osu.Framework/Audio/AudioComponent.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Development/ThreadSafety.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Input/FrameworkActionContainer.cs, osu.Framework/Platform/ExecutionMode.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/HeadlessGameHost.cs, osu.Framework/Platform/ThreadRunner.cs, osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/DrawThread.cs, osu.Framework/Threading/GameThread.cs, osu.Framework/Threading/InputThread.cs, osu.Framework/Threading/UpdateThread.cs, osu.Framework/Timing/ThrottledFrameClock.cs, osu.Framework/osu.Framework.csproj
Toggle with Ctrl+Alt+F7
Note that the execution rate becomes dependent on the window loop at this point, which is generally locked to whatever the WM or OS is providing us with. Our local threads still attempt to keep their relative execution rates, meaning there is potential for sub-optimal frame times depending on frame limiter setting (using unlimited or vsync is recommended for consistency).
**This is intended only for profiling/benchmarking purposes.** It is a barebones implementation with missing safeties (for example, the thread checks are bypassed, rather than checking for input thread). I mainly just want this on appveyor for easier testability.
That said, I won't decline reviews or discussion on the direction of implementation.
Road forward:
- Test performance / heat / energy …
=> Add ability to toggle between single and multi-threaded execution

osu.Framework/Statistics/PerformanceMonitor.cs
Due to the call
https://github.com/ppy/osu-framework/blob/48143da22385831aebc9d0eee10ea84236b52576/osu.Framework/Platform/GameHost.cs#L264
being run inside an already running thread in the case of single thread execution, we were nesting frames. The clear call would clear the stack while inside a frame, causing it do become unbalanced and die on the outer `Pop`.
=> Fix collection stack becoming unbalanced during exit cancellation

osu.Framework.Tests/Layout/TestSceneContainerLayout.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
Fixes https://github.com/ppy/osu/issues/8056
This was caused by the judgements container inside `ManiaStage`, which is defined as:
```
judgements = new JudgementContainer<DrawableManiaJudgement>
{
Anchor = Anchor.TopCentre,
Origin = Anchor.Centre,
AutoSizeAxes = Axes.Both,
Y = HIT_TARGET_POSITION + 150,
BypassAutoSizeAxes = Axes.Both
},
```
Whenever a child was added to this container, its own auto-size would be recomputed, and then that would propagate upwards to invalidate the parent's auto-size.
At specific window sizes, the parent's auto-size would ping-pong between 350 and 349.99997 or something like that likely due to bounding box calculations. That would then invalidate the hierarchy of that container, which would invalidate the scrolling container, which would re-compute the …
=> Add fast invalidation path for bypass autosize axes

osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs, osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
The process is a little bit confusing, but casting from `ColourInfo` to `Color4` happens through the implicit operators:
```
implicit operator Color4(ColourInfo colour) => (SRGBColour)colour
implicit operator SRGBColour(ColourInfo colour) => colour.singleColour
implicit operator Color4(SRGBColour value) => value.Linear.ToSRGB()
```
The shader itself will also call `toSRGB` with our given colour. The end result is that we're doubly-SRGB'ing the colour.
The same effect can be observed by attaching a `.ToSRGB()` to the `.Linear` that was added in this PR.
This is something that we'll need to improve on in the future - shooting ourselves in the foot via SRGB conversion is a well-known issue for us at this point.
I've made minimal changes to the test scene since it needs to be completely …
=> Fix CircularProgress incorrectly SRGBing

osu.Framework.Tests/Audio/TrackVirtualTest.cs, osu.Framework/Audio/Track/TrackVirtual.cs
Also
- Adds test coverage
- Fixes `CurrentTime` exceeding `Length`
=> Fix virtual track entering a running state when length is zero

osu.Framework/Graphics/TransformSequenceExtensions.cs, osu.Framework/Graphics/TransformableExtensions.cs, osu.Framework/Graphics/Transforms/TransformBindable.cs, osu.Framework/Graphics/Transforms/TransformCustom.cs, osu.Framework/Utils/Interpolation.cs
Not going to put a breaking change on this one since I _highly_ doubt it was used. Certainly osu! had no usages of it. This will only become more complicated to implement for users.
The interpolation function should _always_ be defined by the type in question. It's likely that the code that did that came later than `interpolationFunc` itself.
=> Remove custom interpolation function from TransformCustom/TransformBinable

osu.Framework.Tests/MathUtils/TestInterpolation.cs, osu.Framework/Graphics/Transforms/TransformBindable.cs, osu.Framework/Graphics/Transforms/TransformCustom.cs, osu.Framework/Utils/Interpolation.cs
Prereqs:
1. Makes `Interpolation` the common point of all interpolation functions. Without this the user would explicitly have to do something like `func = MarginPadding.ValueAt` for every type, whereas now it's always exactly `func = Interpolation.ValueAt`.
2. Allows the user to have a generic type of their own.
=> Expose Interpolation.ValueAt<T>

osu.Framework.Benchmarks/BenchmarkInterpolation.cs, osu.Framework.Tests/MathUtils/TestInterpolation.cs, osu.Framework/Graphics/MarginPadding.cs, osu.Framework/Utils/IInterpolable.cs, osu.Framework/Utils/Interpolation.cs
Prereqs:
Interested on people's thoughts on this. It's not really required but it may ease implementation overhead, especially as this API is changed. Future changes will add an override for a general easing function.
It's a little bit hacky in that it's creating an uninitialised type and then calling a method on it, but maybe it's not too bad?
This is also one of those functions that is unlikely for consumers to have used just yet, since we have a pretty wide array of transforms/interpolations already.
In the case where a consumer did use it, they'll be provided with the helpful exception - "implement this interface on this type" where the interface has the correct function definition.
=> Explicitly define type interpolations via interfaces

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Statistics/BackgroundStackTraceCollector.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Threading/GameThread.cs
Was about to use this in https://github.com/ppy/osu/issues/8185 and found that the threading changes meant we were sending a null thread to the `BackgroundStackTraceCollector`
Also
- Fixes stack traces getting logged when window is made inactive.
- Fixes stack traces not logging in single threaded execution.
=> Fix stack traces not being logged when performance profiling is turned off

.idea/.idea.osu-framework.Desktop/.idea/modules.xml
Shouldn't be in the desktop solution configuration.
=> Remove stray android project from rider config

osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Visualisation/TextureAtlasVisualiser.cs
- Fixes references being held indefinitely (even when not open)
- Fixed bind count being incorrect (was counting usages, not binds)
- Shows bind count as a number
- Changes colour range to show even low usages
- Removes unnecessary `TextureRemoved` logic (relies on `WeakReference` now)
- Renames `TextureAdded` to `TextureCreated`
=> Fix multiple issues with TextureAtlasVisualiser

osu.Framework/Audio/AudioManager.cs
My attempt to fix: https://github.com/ppy/osu/issues/8185
This change starts up a new thread in the AudioManager that continuously polls for new audio DeviceInfo. Whenever new changes are detected, a task is scheduled to check to current device and whether it should be switched to a better one. (e.g. No Sound -> actual device)
Don't know if other people are actually affected by this latency problem, but I figured this device polling is non-critical and doesn't really need to be part of the main game threads.
=> Refresh audio DeviceInfo async from AudioThread

osu.Framework/Graphics/Video/VideoTexture.cs
This was causing the video texture to bind, bypassing GLWrapper, and then the atlas texture would try to bind but fail the "already bound" checks inside GLWrapper.
I'm not sure/don't think this (fixes) https://github.com/ppy/osu/issues/1488 since the issue is from 2017, but the uploading code and atlasing has changed a lot since then, so hopefully?
=> Fix VideoTexture causing characters to disappear

osu.Framework.Benchmarks/BenchmarkDependencyContainer.cs, osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs, osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
Prereqs:
Master:
|       Method |        Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------------:|---------:|---------:|-------:|------:|------:|----------:|
|          Get |    88.00 ns | 1.581 ns | 1.320 ns |      - |     - |     - |         - |
|  GetNullable |   715.65 ns | 2.539 ns | 2.375 ns | 0.0181 |     - |     - |      96 B |
|    InjectBdl |   894.11 ns | 4.200 ns | 3.724 ns | 0.1221 |     - |     - |     640 B |
| InjectCached | 1,045.52 ns | 9.256 ns | 8.206 ns | 0.0362 |     - |     - |     192 B |
This PR:
|       Method |        Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------------:|---------:|---------:|-------:|------:|------:|----------:|
|          Get |    95.56 ns | 0.466 ns | 0.413 ns | …
=> Reduce allocations during dependency injection

osu.Framework/Allocation/InvokeOnDisposal.cs, osu.Framework/Allocation/ValueInvokeOnDisposal.cs, osu.Framework/Graphics/BufferedDrawNode.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Transforms/ITransformable.cs, osu.Framework/Graphics/Transforms/Transformable.cs, osu.Framework/Platform/NativeMemoryTracker.cs
Along with https://github.com/ppy/osu-framework/pull/3390:
|                          Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
| CreateSequenceWithDefaultEasing | 1.987 us | 0.0097 us | 0.0081 us | 0.4311 |     - |     - |   2.22 KB |
I also get ~0.16ms faster draw time on `TestSceneEffects`.
There is a minor breaking change, however I see no need to list it: the return type of `BeginAbsoluteSequence` and `BeginDelayedSequence` has been changed to `IDisposable`. I've left it out because osu! hasn't ever overridden these or used their return types.
=> Remove allocations from InvokeOnDisposal delegates

osu-framework.sln.DotSettings, osu.Framework/Graphics/Transforms/TransformBindable.cs, osu.Framework/Graphics/Transforms/TransformCustom.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs
This is the result of a custom analyser I've written to look for these cases. It's not ready for the public yet.
This is not a complete list of issues which would close https://github.com/ppy/osu-framework/issues/3389. Other cases involve restructuring how we're doing delegates to support a sender model or are otherwise more complex. Examples include:
1. `BufferedDrawNode` + `BufferedContainerDrawNode` (via the `InvokeOnDisposal`)
2. `AdjustableAudioComponent` (via `InvalidateState()`)
Master:
|                          Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
| CreateSequenceWithDefaultEasing | 2.128 us | 0.0146 us | 0.0136 us | 0.4997 | …
=> Remove some minor delegate allocations

osu.Framework.Tests/Graphics/TextureAtlasTest.cs, osu.Framework/Graphics/Textures/TextureAtlas.cs
There are 2 bugs fixed by this PR:
* `Add` didn't account for the padding. This would either cause an infinite loop or create an invalid texture when the texture width or height was between 1008 and 1024.
* If a new textureatlas was created inside `findPosition` with `Reset`, the position checks would be skipped after the atlas is created. Since the 24x24 white pixel has been added, textures with a width between 984 and 1008 would skip the X position check and would be offset outside the texture by the white pixel. To fix this, I made sure that the position checks were always performed.
=> Handle TextureAtlas findPosition() edge cases

osu.Framework/Extensions/BridgingExtensions.cs, osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs, osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs, osu.Framework/Platform/DesktopGameWindow.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/GameWindow.cs, osu.Framework/Platform/IWindow.cs, osu.Framework/Platform/IWindowBackend.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/Sdl2WindowBackend.cs, osu.Framework/Platform/Window.cs, osu.Framework/Platform/WindowState.cs, osu.Framework/osu.Framework.csproj
Partially cleans up `IWindow` and `Window` to expose osu!framework and .NET standard types rather than osuTK and/or Veldrid types.
Breaking changes for consumers (but not osu!):
* `IWindow.WindowState` now uses a framework enum rather than osuTK.
* `IWindow.VerticalSync` is now a bool rather than an osuTK enum.
A future PR will also remove/replace `CurrentDisplay` and `AvailableResolutions` as they currently use osuTK types, but that's a larger job and a breaking change for osu!.
=> Expose less backend-specific types in IWindow

osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs, osu.Framework/Graphics/Video/VideoSprite.cs
Found this while copying logic for #3405. Wasn't tested properly.
=> Fix video sprite start-at-current offset being applied in the wrong direction

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/Animation.cs, osu.Framework/Graphics/Video/VideoSprite.cs
With the [recent change](https://github.com/ppy/osu-framework/pull/3405) to allow rewinding animations, support for `GotoFrame` was limited to when a custom clock was not in use.
This change allows `GotoFrame` and `startAtCurrentTime` to be used in combination with custom clocks. It also tidies up implementation to be (mostly, bar `GotoFrame`) shared between `Animation` and `VideoSprite`
=> Better support custom clocks in VideoSprite and Animation

osu.Framework/Platform/GameHost.cs
This was occurring due to the draw thread looping forever when no update frames are available:
https://github.com/ppy/osu-framework/blob/e4b92fd3733698117bac3a4681af0f748a154bcd/osu.Framework/Platform/GameHost.cs#L329-L337
In conjunction with the exception being sheduled to the input thread (which will only run after the draw thread exits):
https://github.com/ppy/osu-framework/blob/e4b92fd3733698117bac3a4681af0f748a154bcd/osu.Framework/Platform/GameHost.cs#L249-L250
Can't unit test this unfortunately, since headless tests don't run the draw thread (where this is occurring).
- Closes #3350.
=> Fix freeze (and failure to exit) when exception is thrown in single threaded mode

osu.Framework.Tests/Graphics/TextureAtlasTest.cs, osu.Framework/Graphics/Textures/TextureAtlas.cs
Resolves ppy/osu#8547.
Due to recent changes in the texture atlas area (cf6558b, in particular), a scenario could arise in which the first sprite to be added on a page of the texture atlas would receive a position that partially overlaps the white pixel in the upper left corner of the atlas.
The regression was caused by no longer using the `Add()` method to add the white pixel to the atlas, but by manually creating the upload and sub-texture. Due to this, inside of `Reset()` `currentPosition` would first be set to `(0, 0)`, and then to `(PADDING, PADDING)`. The previous way, using `Add()`, would silently mutate the value of `currentPosition` and therefore work fine.
To resolve, manually set the current position in the atlas to ensure space for the white pixel on the X axis and …
=> Fix first sprite on new atlas page overlapping white pixel

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/Animation.cs
Clock not being processed meant it had an incorrect time reference.
=> Ensure animation starts at zero if stopped before load complete

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/Animation.cs, osu.Framework/Graphics/Video/VideoSprite.cs
Proof of concept for testing purposes. Needs testing and application to `VideoSprite` if we go with this.
=> Fix transforms being applied on an animation from a parent's LoadComplete occurring at an incorrect point in time

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/Animation.cs
Would have been nice to do this using a `Schedule` in `GotoFrame` but it turns out schedulers don't work so well if the clock isn't running.
=> Ensure animation starts at correct frame/time if seeked+stopped to frame before load complete

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework/Graphics/Animations/Animation.cs, osu.Framework/Graphics/Animations/AnimationClockComposite.cs, osu.Framework/Graphics/Animations/AnimationExtensions.cs, osu.Framework/Graphics/Animations/DrawableAnimation.cs, osu.Framework/Graphics/Animations/FramedAnimationExtensions.cs, osu.Framework/Graphics/Animations/IAnimation.cs, osu.Framework/Graphics/Animations/IFramedAnimation.cs, osu.Framework/Graphics/Animations/TextureAnimation.cs, osu.Framework/Graphics/Video/Video.cs, osu.Framework/Graphics/Video/VideoSprite.cs, osu.Framework/Graphics/Video/VideoSpriteDrawNode.cs, osu.Framework/Timing/FramedClock.cs, osu.Framework/Timing/FramedOffsetClock.cs
- Closes https://github.com/ppy/osu/issues/8581
Turns out that Animation was processing the "source" clock a second time. Because in some cases this was the game's thread clock, this cause it to try and sleep as it thought it was running too fast, causing a frame rate decrease when frame limiters were enabled.
Because the animation class' clock setup has caused so much trouble, I've decided to refactor this whole thing a bit.
- New class `AnimationClockComposite` manages clock logic. It now uses a `ManualClock` rather than `FramedOffsetClock`, which tidies up the code and makes the time incrementing feel less hacky.
- Split `IAnimation` into two interfaces (`IAnimation` and `IFramedAnimation`) to allow code share between `Animation` and `VideoSprite`.
- `Animation` / `VideoSprite` no …
=> Fix animations incorrectly processing a parent clock

osu.Framework/Graphics/Containers/BufferedContainer.cs
"Regressed" from https://github.com/ppy/osu-framework/pull/3423, because blending is now handled correctly through multiple parents.
This is temporary because `BufferedContainer` blending is 100% messed up. It's incorrect because it's blending a pre-multiplied alpha texture as if it isn't pre-multiplied.
Over the last 3 days I've tried to get it to blend correctly, but it isn't an easy feat - premultiplying itself is theoretically very easy, but there's some weirdness going on inside the hierarchy of `BufferedContainer` that I need to investigate more.
For now, this restores the original behaviour prior to the PR mentioned above, in the hope that it'll be removed in a short while. This fixes the results screen.
Haven't written a test for this because there's really nothing of value to …
=> Add temporary blending "fix" for BufferedContainer

osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs, osu.Framework.Tests/Visual/Sprites/TestVideo.cs, osu.Framework/Graphics/Animations/Animation.cs, osu.Framework/Graphics/Animations/AnimationClockComposite.cs, osu.Framework/Graphics/Animations/CustomisableSizeCompositeDrawable.cs, osu.Framework/Graphics/Animations/DrawableAnimation.cs, osu.Framework/Graphics/Animations/TextureAnimation.cs, osu.Framework/Graphics/Video/Video.cs
Opening this reluctantly. Basically using what we know already "works" from Animation on video as well. Also fixes `FillMode` not working (never did). Wrapping drawables like this is still an area of the framework that falls over badly.
- Closes https://github.com/ppy/osu/issues/8600
=> Share layout logic between Animation and Video

osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/IDynamicallyCompile.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestScene.cs
For scenarios like needing access to the original assembly for accessing resources.
=> Expose original instance for dynamic compilation

osu.Framework.Tests/Layout/TestSceneContainerLayout.cs, osu.Framework/Graphics/Drawable.cs
Fixes https://github.com/ppy/osu/issues/8663
For some reason it just wasn't using the parameter passed in...
Very unlikely this would actually cause a performance issues (e.g. in autosize or flow) except for some specific scenarios like the above PR.
=> Fix position causing parent size invalidations

osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs
Has caught me off-guard a few times since flattening is a non-explicit operation.
I've benchmarked the `.GetType().DeclaringType`, and imo it's insignificant:
```
Method |     Mean |     Error |    StdDev | Allocated |
----------------------- |---------:|----------:|----------:|----------:|
GetDeclaringType | 76.75 ns | 0.3441 ns | 0.3219 ns |       0 B |
GetDeclaringTypeCached | 29.61 ns | 0.6685 ns | 0.8210 ns |       0 B |
```
(per invocation)
=> Ensure no flattening for custom composite drawnodes

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
Across osu!framework and osu!, there is only one use case for `DrawNode` invalidations: notifying yourself that your own `DrawNode` should change.
For example, `Container` invalidates `DrawNode` to signal its own `DrawNode` of changes to edge effect/corner radius/masking states/etc. Similar for `BufferedContainer`, every time `ForceRedraw()` is called - potentially every frame.
Potentially breaking change, but no changes are required o!f-side or osu!-side, so I'm not making a breaking change entry for this.
=> Never propagate DrawNode invalidations

osu.Framework/Graphics/Drawable.cs
Theoretically this should have some performance impact, but it is not visible on any benchmarks whatsoever, so I haven't included any.
This is only ever accessed on the update thread (inside `Invalidate()`, `GenerateDrawNodeSubtree()` and `DrawNode.ApplyState()`).
=> Remove atomic invalidation counter

osu.Framework.Benchmarks/BenchmarkInvalidationWithManyNotAlive.cs, osu.Framework.Benchmarks/BenchmarkMakeChildAlive.cs, osu.Framework.Benchmarks/BenchmarkSpinningParentWithManyAlive.cs, osu.Framework.Tests/Layout/TestSceneContainerLayout.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/InvalidationList.cs
It's unnecessary to propagate invalidations to non-alive children, as they are not part of the hierarchy yet. They don't receive any other updates, or even `LoadComplete` if they're not alive.
This provides a small benefit when there are many objects that aren't alive (e.g. hitobjects, currently) and when a parenting container changes (e.g. window size / screen scale).
```diff
|         Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |---------:|---------:|---------:|------:|------:|------:|----------:|
- |   ManyNotAlive | 17.67 ms | 0.107 ms | 0.100 ms |     - |     - |     - |     214 B |
+ |   ManyNotAlive | 15.72 ms | 0.312 ms | 0.321 ms |     - |     - |     - |     144 B |
- | MakeChildAlive | 992.7 us |  1.23 us |  1.15 us |     - | …
```
=> Don't invalidate non-alive children when not required

osu.Framework.Benchmarks/BenchmarkSpinningParentWithManyAlive.cs, osu.Framework/Graphics/Shapes/Box.cs
Prereqs:
Only needs to be computed when we know we're going to draw. This is inside `BoxDrawNode.ApplyState()`.
```diff
|            Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |---------:|----------:|----------:|------:|------:|------:|----------:|
- |         ManyAlive | 9.327 ms | 0.0518 ms | 0.0459 ms |     - |     - |     - |     128 B |
+ |         ManyAlive | 8.779 ms | 0.1085 ms | 0.0962 ms |     - |     - |     - |     112 B |
- | ManySpinningBoxes | 1.043 ms | 0.0053 ms | 0.0049 ms |     - |     - |     - |     133 B |
+ | ManySpinningBoxes | 987.1 us |   1.69 us |   1.58 us |     - |     - |     - |     113 B |
```
Changes in `ManyAlive` are due to the quad not being computed if `IsMaskedAway = true`.
Changes in …
=> Optimise conservative draw quad computations

osu-framework.sln
An interim solution so that we can keep the template projects somewhat up to date - dependabot will catch out of date packages for us. Seems to work on my fork: https://github.com/smoogipoo/osu-framework/pulls
I've put the templates into separate sln folders since they're 5 projects worth each, with the downside being the filtered solutions now get a few empty folders...
=> Add template projects to sln

osu.Framework/Graphics/UserInterface/BasicTabControl.cs
Currently `BasicTabControl` throws an exception because of https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/TabControl.cs#L115
=> Fix BasicTabControl not working by default

osu.Framework/Testing/DynamicClassCompiler.cs
Ran into this a few times recently with taiko/mania classes having the same names.
Has been tested against the cases that were failing for me.
=> Fix dynamic compilation potentially including files from wrong namespace

osu.Framework/RuntimeInfo.cs
Although the original comment mentions 2020/04/30.
=> Remove obsoleted RuntimeInfo properties.

osu.Framework/Audio/Sample/SampleChannelBass.cs
Stems from `SampleChannel`'s ctor `Action<SampleChannel> onPlay`, which is where the channel is added to its parent `AudioComponent` (and aggregate adjustments are bound). This was happening after the playback itself.
Closes https://github.com/ppy/osu/issues/8162.
Can be reproduced by adding a Thread.Sleep after the play call:
https://github.com/ppy/osu-framework/blob/78dbba4f63668da3dffe46d889fd41209105a2d2/osu.Framework/Audio/Sample/SampleChannelBass.cs#L80
Note that it will *not* reproduce in `TestSceneSamples` because this does not request new channels each playback, so it will only occur on the first playback (if that).
=> Fix samples occasionally playing before volume adjustment can be applied

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/EmptyTypeReferenceBuilder.cs, osu.Framework/Testing/ExcludeFromDynamicCompileAttribute.cs, osu.Framework/Testing/ITypeReferenceBuilder.cs, osu.Framework/Testing/RoslynTypeReferenceBuilder.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/osu.Framework.csproj
This is a complete rework of the type performed during dynamic compilation. It follows the following process with some optimisations in-between, which I hope to have documented in a somewhat readable way in code:
1. Map all types to the types which they reference.
2. Build a directed graph from the changed file towards the test scene type by following the map generated in (1).
3. Find all files corresponding to the types by following the graph in (2) by-parent.
Performance wise this is slightly slower on first initialisation (building the map in step (1)), but further changes are about as quick as they were previously. Step (1) could could probably be done in the background rather than on change, but I haven't done that in this PR.
Scenarios I've tested:
1. Changing …
=> Rework dynamic compilation to use Roslyn-backed type resolution

osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Logged to `logs/dynamic-compilation.log`, logs the traversed hierarchy when finding the required files.
Also excludes `Game` types from dynamic compilation.
=> Improve logging and exclude Game types from dynamic compilation

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs
Technically closes #3498, but will be more corrected with ppy/osu#8912 being fixed.
There may normally be dropdowns with no items selected inside them, this is aiming to fix the exception thrown when pre-selecting by pressing on the keyboard there.
=> Fix dropdown with nothing selected throwing on pre-selecting afterwards

osu.Framework/Platform/GameHost.cs
Currently if an `InputHandler` fails initialisation, no other input handlers will be initialised.  As discussed in Discord, it is preferred that all input handlers get a chance to initialise themselves.
=> Continue initialising InputHandlers if one fails

osu.Framework/Platform/Windows/WindowsGameHost.cs
- Closes https://github.com/ppy/osu/issues/8984
- Regressed with https://github.com/ppy/osu-framework/commit/3f9cb216a2be06137811e1a5461dcfd6db218cce#diff-ba0efd388bc6a3ecfc4e4ffad10d9c89 due to missing return.
=> Fix "open in explorer" occurring twice for windows directories

osu.Framework/Testing/TestBrowser.cs
Side effect of testing ppy/osu#9011.
Disable dynamic recompilation in Android visual test runs, as in its current state it causes the test browser to hang on startup. First, `DynamicClassCompiler.Start()` would silently fail [due to `AppDomain.CurrentDomain.BaseDirectory` being null](https://github.com/ppy/osu-framework/blob/7373bed57a480512ff8408b2c9530ca6c8a32260/osu.Framework/Testing/DynamicClassCompiler.cs#L46) (that exception is swallowed [here](https://github.com/ppy/osu-framework/blob/6bfb8880ed6e0b5f60b35657d0b1d8293f9ae548/osu.Framework/Testing/TestBrowser.cs#L261-L268)):
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
at System.IO.Path.InsecureGetFullPath (System.String path) [0x00003] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/r …
```
=> Disable dynamic recompilation on Android

osu.Framework.Tests/Visual/Containers/TestSceneCachedBufferedContainer.cs, osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaContainer.cs, osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs, osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs, osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs, osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework.Tests/Visual/Testing/TestSceneDrawVisualiser.cs, osu.Framework.Tests/Visual/Testing/TestSceneStepButton.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneButton.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneCheckboxes.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Testing/IDynamicallyCompile.cs, osu.Framework/Testing/MenuTestScene.cs, osu.Framework/Testing/TestScene.cs
No longer required due to improvements in dynamic compilation via roslyn.
=> Remove usage of RequiredTypes

osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneTemplateGameGame.cs, osu.Framework/Testing/TestScene.cs
I consider this a breaking change since it affects every project in existence (it was included in the template).
=> Restore RequiredTypes as an obsolete property

osu.Framework/Platform/Linux/LinuxGameHost.cs, osu.Framework/Threading/AudioThread.cs
Anything that touched bass would fail with:
```
Reason: Test host process crashed : /usr/share/dotnet/dotnet: symbol lookup error: /home/smgi/Repos/osu/osu.Game.Rulesets.Mania.Tests/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libbass_fx.so: undefined symbol: BASS_GetVersion
```
This also affected nunit tests since they use `HeadlessGameHost` (not `LinuxGameHost`).
=> Fix libbass_fx load errors during tests on linux

osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs
Fixes https://github.com/ppy/osu-framework/issues/3222
`childrenUpdateVersion` was set too soon, which blocked `UpdateSubTreeMasking` from proceeding to children.
Unsure 100% on the placement here, I feel like it really should be inside `GenerateDrawNodeSubtree` but I'm considering cases like `FrameStabilityContainer` which potentially trigger multiple updates per-frame without drawnode generation.
=> Fix ModelBackedDrawable not working inside BufferedContainer

osu.Framework/Game.cs
Resolves the framework side of ppy/osu#8420.
Due to semantics of file removal on Windows, the post-test host cleanup logic would leave behind font cache files, as they were being held open by `RawCachingGlyphStore`s. This meant that each new game host instantiated would leave behind a 1 MB file that wouldn't be cleaned up, summing up to gigabytes in leftover files after a full test suite run.
To resolve, dispose of both font stores in `Game`. I have confirmed that this leads to the cache files being cleaned up on Windows, and additionally that this change should not regress game-side tests.
I have refrained from touching the other disposable resources in `Game` as per the "if it isn't broken, don't fix it" philosophy. In fact I recall that doing so would cause game-side failures, and I'd …
=> Dispose of font stores in base game

osu.Framework.Tests/Lists/TestWeakList.cs, osu.Framework/Lists/IWeakList.cs, osu.Framework/Lists/LockedWeakList.cs, osu.Framework/Lists/WeakList.cs
Specifically, cases where items are sequentially removed from either end (`RemoveAllIteratively`).
Removal of items is done lazily - items are effectively "nulled" and removed on the next `GetEnumerator()` call. This could lead subsequent removals without an interleaved `GetEnumerator()` call into a very bad O(n^2) scenario.
The solution is to store an enumeration range such that sequential removals only operate on the subset of the range that is relevant after the removal.
```diff
|               Method | ItemCount |          Mean |        Error |       StdDev | Ratio | RatioSD |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|--------------------- |---------- |--------------:| ------------:| ------------:|------:|--------:|-------:|-------:|------:|----------:|
- |                  Add | …
```
=> Improve WeakList<> performance in degenerate scenarios

osu.Framework/Testing/DynamicClassCompiler.cs
Currently after your code have been dynamically compiled and if it throws an exception then you will see stack trace but without file and line where this exception happened.
Adding pdb stream to compilation will show that information even after dynamic assembly been created.
You can see the difference in image below.
=> Add pdb to DynamicClassCompiler to show more info in stack trace

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
`Log(0) = Infinity`
With expansion factor 0, this becomes `exclusionRange = (-Inf .. +Inf)`.
This entire method is going to be rewritten - I don't like the concept of this expansion factor anymore, so just treat it as a hotfix for now.
=> Fix dynamic compilation not working for testscenes

osu.Framework.Tests/Lists/TestWeakList.cs, osu.Framework/Lists/LockedWeakList.cs, osu.Framework/Lists/WeakList.cs
There's 2 fixes here:
First, `RemoveAt()` was broken.
1. It didn't include the start offset, meaning `RemoveAt(0)`, `RemoveAt(0)`, ..., would be a no-op after the first operation. This is a new function and doesn't affect, e.g. `Remove()` which used this method.
2. It would never decrement the end index when removing from the end. This could only really affect performance, and even then it would only be for cases where you constantly iterate over the whole list (like, I guess... `.Contains()` with an item that doesn't exist after a `.RemoveAt()`?).
I don't believe either of the above could cause the failure seen in https://ci.appveyor.com/project/peppy/osu/builds/33061305, because even with the above issues, `listEnd` is guaranteed to be less than or equal to the list count. There's only …
=> Fix WeakList<T> failure cases

osu.Framework.Tests/Bindables/BindableListTest.cs
Not actually an issue, but I wrote a test to confirm it was working correctly, and seems like it's worthwhile having.
=> Add test covering removing twice from a BindableList not firing events

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Since static classes are more often than not used to provide extension methods, they can't be re-compiled otherwise they lead to ambiguous names.
Technically this is also true for all statics, but there's no way to avoid that, and will be documented as a failure case.
=> Ignore static classes in dynamic compilation

osu.Framework/Bindables/BindableList.cs
Why didn't we do this from the start? Did something change?
=> Avoid Activator.CreateInstance when getting bound copy of BindableList

osu.Framework.Tests/Visual/Containers/TestSceneDrawSizePreservingFillContainer.cs, osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
Fixes https://github.com/ppy/osu-framework/issues/3592
As mentioned in the issue thread, `ChildSize` is the correct solution here.
Previous:
Now:
(Padding on the left side).
=> Fix DSPFC not considering parent padding correctly

osu.Framework.Tests/Platform/PortableInstallationTest.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/RuntimeInfo.cs
Using `Environment.CurrentDirectory` for storing / reading files is dangerous as the current directory is mutable and can be changed when performing certain operations (like opening solutions in roslyn type reference builder for example).
This fixes the issue by introducing a new immutable static `StartupDirectory` property (and `StartupStorage` for components that perform disk mutation operations in the startup directory) to use in place of `Environment.CurrentDirectory` uses.
=> Replace any potential usage of Environment.CurrentDirectory with an immutable static property

osu.Framework/Development/DebugUtils.cs, osu.Framework/Platform/GameHost.cs
Makes more sense to return the assembly containing the current running test as the entry assembly, instead of the game assembly. 
Also an upside with this change is that `DebugUtils.GetEntryAssembly()` will now return the exact same assembly value for normal runs on nunit runs as can be seen in the below results.
---
Only slightly improves code quality by avoiding use of mutable static members, not needed for any other PR but worth submitting this change for the sake of code quality.
Tested assembly values manually on different projects:
```
osu.Framework.Tests (normal run)
- Assembly.GetEntryAssembly(): /Users/salman/Desktop/osu-framework/osu.Framework.Tests/bin/Debug/netcoreapp3.1/osu.Framework.Tests.dll
- Assembly.GetCallingAssembly(): …
```
=> Replace returning host assembly with NUnit current test assembly

osu.Framework/Graphics/Colour4.cs
Until `Color4` is removed, which will occur much further down the line.
As it is it causes compiler warnings.
=> Remove obsoletion of implicit operators

osu.Framework.Tests/Layout/TestSceneDrawableLayout.cs, osu.Framework/Graphics/Drawable.cs
An optimisation that led to incorrectness :/
Noticed because of `TestSceneExpandedPanelMiddleContent` osu!-side.
Before:
After:
(Note position of the "Played on" text at the bottom)
Not suuuuuuuper keen on the extra parameter, but it's all pretty local so... Definitely don't want to expose it publicly since this is the only case it's ever used.
=> Fix changing Size/Position not invalidating self correctly

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
Allow's osu!'s `ChannelTabControl` to work again. Without this check, it was possible that the switch call would re-select the tab to be removed.
=> Fix TabControl's updated switching-on-removal logic not considering IsSwitchable

osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
Has caused a *huge* degradation in performance. Likely affects desktop too, just in a less noticeable way. I know it did on osu-stable (we use `unsafe` to get around this). I'm open to disabling this across desktop as well, until a better solution is applied with benchmarking.
Closes https://github.com/ppy/osu/issues/9307
=> Disable opacity checks on mobile platforms

osu.Framework.iOS/Input/IOSMouseHandler.cs
Closes #3621 
This PR extends the trackpad mouse support on iPadOS by adding a `UIPanGestureRecognizer` object to the main game view, which then converts any scrolling offsets into `MouseScrollRelativeInput` events. Tested and confirmed working in the Test Browser.
It doesn't behave like a native iOS scroll view in that when you over scroll, the content will snap back on its own. If this ends up not being desirable, an alternative might be to make this code simulate a soft mouse click and drag event (Depending on how easy that is to do).
Additionally, the scrolling is quite fast, so it might be necessary to add some damping to it.
=> Add trackpad scrolling support for iPadOS

osu.Framework.Android/AndroidGameActivity.cs
Closes ppy/osu#9321
This simply wraps the mutation of the WindowManager flags (which should always be done on the Android UI thread) into a closure that will always run on the UI thread through `RunOnUiThread()` and should fix the crashes occuring in multithreaded mode.
=> Always change the Android WindowManager flags on the UI thread.

osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs, osu.Framework/Audio/Sample/SampleChannelVirtual.cs
Step 1 towards addressing ppy/osu#8595.
This PR adds a `SampleChannelVirtual`, which analogously to `TrackVirtual` fulfills the code contract of being a sample channel, but in reality does nothing in terms of audio playback. Consumers can use it as an alternative to a null sample channel.
Adding it to framework was suggested by @frenzibyte and I would tend to agree with that suggestion as it keeps things consistent.
I haven't added any tests, but this seems pointless to test as it's a do-nothing class.
I opted for this solution so as not to have to change the game-side skin lookup fallback logic which is complex enough as-is without adding another layer on top.
Not 100% on the `UpdateState()` override. It made sense to me at the time.
=> Add virtual sample channel

osu.Framework.iOS/Input/IOSMouseHandler.cs
We discovered a crash occurring on iOS versions lower than 13.4 due to the fact that `IOSMouseHandler` properly checks the version upon initialisation, but neglects to do that during disposal. Sorry about that!
=> Fix crashes on iOS versions lower than 13.4

osu.Framework/Audio/Track/TrackBass.cs
While working on improving amplitude retrieval, I noticed that while this isn't being used in an unsafe way anywhere, the `activeStream` field was potentially being modified multiple times as bass effect channels are added.
As `activeStream` is only set to a final value once ever, this feels much safer.
=> Only set activeStream after it has been fully constructed

osu.Framework.Tests/Visual/Audio/TestSceneTrackAmplitudes.cs, osu.Framework/Audio/BassAmplitudeProcessor.cs, osu.Framework/Audio/Track/BassAmplitudes.cs, osu.Framework/Audio/Track/Track.cs, osu.Framework/Audio/Track/TrackBass.cs
Feels better from a code quality perspective, but may also pave the way to using this in `SampleChannel` (something I am currently looking in to.
=> Split out bass amplitude computation to separate class

.idea/.idea.osu-framework.Desktop/.idea/runConfigurations/SampleGame.xml, .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/VisualTests.xml
Been meaning to PR this for a while so I don't need to keep the changes locally. The run window popping up is really annoying in my opinion, so as long as there is consensus I'd like to push this change out across all non-CLI project configurations.
=> Don't activate run tool window on rider run

osu.Framework.Tests/Visual/Audio/TestSceneSampleAmplitudes.cs, osu.Framework.Tests/Visual/Audio/TestSceneTrackAmplitudes.cs, osu.Framework/Audio/BassAmplitudeProcessor.cs, osu.Framework/Audio/IHasAmplitudes.cs, osu.Framework/Audio/Sample/ISampleChannel.cs, osu.Framework/Audio/Sample/SampleChannel.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs, osu.Framework/Audio/Track/ChannelAmplitudes.cs, osu.Framework/Audio/Track/ITrack.cs, osu.Framework/Audio/Track/Track.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Graphics/Audio/DrawableSample.cs, osu.Framework/Graphics/Audio/DrawableTrack.cs
Not sure about the renaming breaking backwards compatibility. Can't add a temporary obsoleted class due to it being a struct.
=> Allow retrieving SampleChannel amplitudes

osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackTriangle.cs, osu.Framework/Graphics/Shapes/Triangle.cs, osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
* Closes ppy/osu#9351
Not a super huge fan of this but at least it's consistent with `Draw()`/`Blit()`...
Also adds the texture availability check, both to be consistent with `Draw()` and to prevent the potential error there.
=> Fix black square around triangle sprites due to front-to-back

osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Fixes https://github.com/ppy/osu-framework/issues/3306
Couldn't actually replicate this one (hence no test). It's actually quite hard to do so because you have to juggle 3 schedules: the one inside `DLW.OnInvalidate()`, the one for `checkForUnload()`, and then another one to actually trigger the disposal at the correct time. Then you have to deal with `perUpdateTasks` vs non-`perUpdateTasks` in the `Scheduler` and it gets very implementation-specific.
But I can imagine why this could occur.
=> Fix potential ObjectDisposedException in DelayedLoadUnloadWrapper

osu.Framework/Input/InputManager.cs, osu.Framework/Input/PassThroughInputManager.cs
Actually doesn't seem testable as there's no way to distinguish between whether a redundant input has been applied and whether not, as mouse input from touch will be produced in order from bottom-child up to top-parent.
But makes sense either way to put this toggle for things to be as expected.
=> Disallow mouse input from primary touch on PassThroughInputManagers

osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs, osu.Framework/Input/PassThroughInputManager.cs
All event managers propagate release events to the handler drawable and all of what its in front of it built in to the queue. And for `TouchEventManager` which propagates touch move events to the queue of `TouchDownEvent` (test coverage about that coming in dependent PR), the pass-through input manager must always stick itself to the queue.
The test case provided for this will not produce different results based on the fix due to the manager actually tries to synchronize itself with the parent manager per-frame because of "some non-positional events" being blocked, which I think this fix would render that redundant, but decided to separate that change into another PR as it also kinda changes behaviour.
=> Fix PassThroughInputManager potentially not receiving release events

osu.Framework/Input/States/InputState.cs
Noticed while updating osu!-side dependencies that:
1. `touch` was injected before `joystick` - build-time error.
2. `midi` wasn't passed through.
It's not a huge deal, but it's probably safer for the user to be able to specify the `InputState` to be copied from.
=> Add a copy constructor to InputState

osu.Framework.iOS/Input/IOSMouseHandler.cs, osu.Framework.iOS/Input/IOSTouchHandler.cs
This PR is a refinement on top of #3642. 
In my testing, I noticed that if a user had a physical mouse and clicked both buttons down at the same time, the "Unclick" mouse event for the left button wouldn't be called, and the cursor was consistently getting stuck in a "left button still clicked" state.
I discovered today that this was because I had assumed clicking the left and right buttons generated separate streams of  `UITouch` objects, but I found that actually only one `UITouch` object is ever used when a user is clicking a physical mouse, and that single touch object simply transitions between "left-click" and "right-click" states on demand.
This PR does two things:
1) Properly silos all of the custom right-click logic, so regular screen taps aren't affected by it.
2) Detects when …
=> Add improved state handling for right-click on iPadOS

osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs, osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
Resolves ppy/osu#8145 (*finally*).
As outlined in the issue thread, a storyboard usage of `LifetimeManagementContainer` revealed that setting `LifetimeStart` and `LifetimeEnd` inside a child's `Update()` was unsafe, as it was mutating `AliveInternalChildren` while they were being enumerated inside of `UpdateSubTree()` through the `childLifetimeChanged` callback.
Resolve by deferring all `childLifetimeChanged` executions until all alive children are processed during an update frame.
Here are two videos, demonstrating the manifestation of the bug on the map affected game-side and its resolution with this PR:
* [before](https://streamable.com/xxk4cq) - note the zombie samples highlighted in the draw visualiser and the lack of kick drum playback when they appear,
* …
=> Schedule lifetime change callbacks after children

osu.Framework/IO/AsyncBufferStream.cs
Started appearing in latest Rider EAP.
=> Fix volatile usage warnings in AsyncBufferStream

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
In investigating https://github.com/ppy/osu/issues/9324 I initially took the path of making `Remove` return a `bool`. While that could still be done it isn't enough to resolve the issue, since the issue occurs _while_ we're in the removal process (i.e. `bindable callback -> remove -> switch -> bindable callback -> remove`), and would also require a schedule of the callback. I think that's pretty hacky.
So probably the easiest way to do this is just adding an option to disable this behaviour altogether for cases like `BreadcrumbControl` that are `TabControl`s only in appearance and don't need such functionality.
Have also used this opportunity to document the rest of the class, as one of the goals I'm hoping to achieve is documenting any classes I touch framework-side.
=> Add option to disable TabControl switch-on-remove behaviour

osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs, osu.Framework/Input/PassThroughInputManager.cs, osu.Framework/Input/StateChanges/MidiKeyInput.cs, osu.Framework/Testing/Input/ManualInputManager.cs
Resolves #3686.
`MidiKeyInput` has been reworked to support pressing multiple keys with multiple velocities in one input, to bring MIDI inputs more in line with other input types in the framework.
* Instead of reading `MidiKeyInput.Button`, use `MidiKeyInput.Entries` to ascertain whether the input concerns a particular MIDI key.
* Instead of reading `MidiKeyInput.Velocity`, inspect the `MidiKeyInput.Velocities` dictionary to retrieve the velocity of the input for a given key.
* Instead of reading `MidiKeyInput.IsPressed`, use `MidiKeyInput.Entries` to match the key whose state you wish to retrieve and read the `ButtonInputEntry`'s `IsPressed` property.
As stated in the issue thread, `PassThroughInputManager` did not take MIDI events into account. This PR adds support for passing through …
=> Add MIDI input handling to passthrough input manager

osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
Resolves #3683 (hopefully).
The MIDI event parsing code was a little lax when it comes to treating incoming messages other than note on/off. This PR introduces checks and handling of special corner cases that can arise in MIDI messages.
The references I used are: [this part of the MIDI spec](https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message) and sources of managed-midi.
I have tested some of this; the device I own (a Kawai ES110 digital piano) does not unfortunately produce a lot of the weird MIDI messages (especially not the real-time ones). I have however tested the weird ones that I can produce and I got no crashes or logged exceptions (and I did get some on `master`, so it's *some* improvement).
This is not intended to be completely correct and per-spec, as …
=> Improve robustness of MIDI event parsing

osu.Framework/IO/Stores/FontStore.cs
Should fix https://ci.appveyor.com/project/peppy/osu-framework/builds/33945568 + https://ci.appveyor.com/project/peppy/osu-framework/builds/33945025
I couldn't replicate this in practice but I have a pretty good idea of what's causing it. It seems like the unobserved handler [is only invoked on GC](https://github.com/dotnet/runtime/issues/21269), so what we're reaching here is a very time-critical scenario that requires:
1. Running two `GameHost`s one after another. The first will trigger the exception, dispose (removing its own handler), then the second will bind its handlers and attempt to run as normal. The exception likely actually happens in the second `GameHost`, where the font loads from the first are running in a background thread and trigger exceptions in the second.
2. A GC to …
=> Fix font load exceptions potentially crashing the game

osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/PassThroughInputManager.cs, osu.Framework/Input/StateChanges/Events/TouchStateChangeEvent.cs, osu.Framework/Input/StateChanges/TouchInput.cs, osu.Framework/Input/TouchSource.cs
As discussed and considered, mapping mouse input to any new / moved touches instead of first touch is more better as a good starting point.
Huge note though is that now with this new logic, there will be "false drags" raised when still holding a touch and pressing a new one (mouse moves from one to other while left still pressed, thus a false drag raised), discussed about that with the result of opening an issue post-merge as it doesn't seem easy to resolve.
=> Map mouse input to new / moved touches instead of only first

osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs, osu.Framework/Allocation/CachedModelDependencyContainer.cs
See: https://github.com/ppy/osu/pull/9478
Since `CachedModelDependencyContainer` relies on being able to `UnbindFrom(previousBindable)`, we can't have these fields changing their values beyond the ctor.
Mutating bindables of models attached to a `CachedModelDependencyContainer` can lead to crashes or otherwise unexpected behaviour, and is now disallowed.
=> Disallow non-readonly fields in CachedModelDependencyContainer

osu.Framework/Testing/Input/ManualInputManager.cs
Sometimes it can block what you're trying to test.
=> Add the ability to disable the ManualInputManager cursor guide

osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs, osu.Framework/Graphics/Pooling/DrawablePool.cs, osu.Framework/Graphics/Pooling/IDrawablePool.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs
Proof of concept for early comment. Not ready for merge pending confirmation that it covers intended use cases osu!-side.
- `PoolableDrawable` or `PooledDrawable`? I went for the first since I've allowed them to be used outside of a pool context for flexibility.
- There may come a time we need to move the `PoolableDrawable` implementation to an interface (potential multiple inheritance woes?) but I didn't do this for the time being because it's a relatively lightweight base class and can be slotted in beneath `DrawableJudgement` and `SkinReloadableDrawable` (for the `DrawableHitObject` case).
- `DrawablePool` may eventually need to take a `LoadTarget` to specify the container used for BDL loading. For now it just loads using its parent.
=> Add DrawablePool for avoiding allocation overhead of drawables

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs, osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Fixes the second issue brought up in https://github.com/ppy/osu/pull/9478.
=> Fix potential duplicate items in RearrangeableListContainer

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/AnimationClockComposite.cs
The sequence:
```
Hide()
{wait some time}
GotoFrame(0)
Show()
```
Would cause the clock to consume the `{wait some time}` period the first frame it becomes visible.
Unsure whether it's better for the consumption to be ignored during `Update()`. Thoughts? May be tricky to implement...
=> Fix seeking animation not consuming clock

osu.Framework/Statistics/BackgroundStackTraceCollector.cs
We weren't correctly disposing the `DataTarget`, which results in it building  up a huge unmanaged memory footprint. Reference: https://lowleveldesign.org/2019/02/22/a-story-of-fixing-a-memory-leak-in-minidumper/
=> Fix memory leak when retrieving stack traces

osu.Framework.Tests/Containers/TestSceneContainerState.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs
Setting `Parent` transfers the parent's clock to the target drawable, but it isn't set on the parent until it's started loading.
=> Fix exception when adding loaded drawable to unloaded parent

osu.Framework/Graphics/OpenGL/GLWrapper.cs
Fixes https://github.com/ppy/osu/issues/8487
Round 2 of fixes towards the above issue, because I could also still replicate it. I guess my RDP solution interfered (tested without RDP this time).
It's specifically the `Clear()` that affects this - I remember doing a similar fix to osu-stable at one point for a different reason, iirc the backbuffer is initialised to an invalid colour or something. Perhaps on these GPUs they're using the backbuffer to re-sample...?
=> Upload textures after clearing backbuffer

osu.Framework/Threading/DrawThread.cs
(Should) fixes https://github.com/ppy/osu/issues/6387
(Should) fixes https://github.com/ppy/osu/issues/4068
Haven't been able to replicate in the last 50 attempts. Seems like this is also the true reason for https://github.com/ppy/osu-framework/pull/3720.
=> Always make the graphics context current on the draw thread

osu.Framework/Graphics/Performance/PerformanceOverlay.cs
This is actually a reproducible in live builds of osu!, and I wouldn't be surprised if some users are hitting it (requires slow startup performance to trigger).
=> Fix hard crash if PerformanceOverlay is toggled before loaded

osu.Framework/Statistics/GlobalStatistics.cs
=> Remove linq allocation on GlobalStatistics.Clear

osu.Framework/Input/InputManager.cs
=> Fix LINQ allocations in focusTopMostRequestingDrawable

osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/InputManager.cs
=> Fix excessive list allocation in GetPendingInputs paths

osu.Framework/Audio/BassAmplitudeProcessor.cs
I've left the `readonly struct` data structure in place as it seems to still work correctly.
=> Remove array allocations in BassAmplitudeProcessor by removing consistency guarantee

osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/StateChanges/ISourcedFromTouch.cs, osu.Framework/Input/StateChanges/MouseButtonInputFromTouch.cs, osu.Framework/Input/StateChanges/MousePositionAbsoluteInput.cs, osu.Framework/Input/StateChanges/MousePositionAbsoluteInputFromTouch.cs, osu.Framework/Input/StateChanges/MousePositionRelativeInput.cs, osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs, osu.Framework/Input/States/MouseState.cs
Alternative to https://github.com/ppy/osu-framework/pull/3675/files using interface rather than polluting non-touch classes with touch-specific booleans. Took same test from other PR to make it easy to compare implementation / usage.
=> Add marker interface and store source of last change to MouseState

osu.Framework.Benchmarks/BenchmarkSlimReadOnlyCollection.cs, osu.Framework/Extensions/ListExtensions/ListExtensions.cs, osu.Framework/Lists/SlimReadOnlyListWrapper.cs
This should help with https://github.com/ppy/osu-framework/pull/3739 (it's a drop-in replacement). Supports `List<T>` for now, though in the future it could be upgraded to support more lists with minimal performance cost (~5us in the benchmarks).
|             Method |      Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------- |----------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
|               List |  29.03 us | 0.051 us | 0.045 us |  1.00 |    0.00 |      - |     - |     - |         - |
|     ListAsReadOnly | 124.87 us | 0.520 us | 0.461 us |  4.30 |    0.02 | 1.7090 |     - |     - |   64000 B |
| ListAsSlimReadOnly |  28.89 us | 0.051 us | 0.045 us |  0.99 |    0.00 |      - |     - |     - | …
=> Add wrapper to create a slim read-only list

osu.Framework/Graphics/Cursor/CursorEffectContainer.cs, osu.Framework/Graphics/Cursor/TooltipContainer.cs, osu.Framework/Input/InputManager.cs
=> Fix CursorEffectContainer allocating excessively

osu.Framework/Input/InputManager.cs
Two small changes:
- Don't alloc lists for `IRequireHighFrequency`
- Don't alloc enumerator in `PropagateBlockingEvent` (due to `IEnumerable` param type)
As one requires the other I did this in a single PR.
Before:
After:
=> Fix LINQ / List alllocations in PropagateBlockableEvent

osu.Framework/Input/StateChanges/ButtonInput.cs, osu.Framework/Input/States/ButtonStates.cs
Reduces allocations when moving the mouse with no buttons pressed.
Before:
After:
=> Avoid comparing buttons when there is guaranteed to be no difference

osu.Framework/Input/States/ButtonStates.cs
This reduces allocations when buttons are pressed, such as a drag operation.
Before:
After
=> Avoid using LINQ to calculate button differences

osu.Framework/Input/States/ButtonStates.cs
When moving mouse, this will avoid unnecessary enumeration allocations
Before
After
=> Remove HashSet enumeration via static readonly

osu.Framework/Input/InputManager.cs
I'm not 100% on the logic here (whether checking for pending inputs is enough to guarantee `CurrentState` is not mutated. I can't find a case otherwise, but need feedback from @smoogipoo.
Before:
After:
=> Avoid allocating MouseMoveEvents for high frequency when not required

osu.Framework.Benchmarks/BenchmarkButtonInput.cs, osu.Framework.Benchmarks/BenchmarkButtonStates.cs, osu.Framework/Input/StateChanges/ButtonInput.cs
Follows on from the previous performance improvements, which now allows `ButtonInput` to use the builder and forego an extra `.ToArray()` + allocations therein.
Master:
|        Method | count |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------- |------ |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|         Apply |     ? | 1,060.5 ns |  4.93 ns |  4.61 ns | 0.0706 |     - |     - |    2416 B |
| FromTwoStates |     1 |   370.1 ns |  2.30 ns |  2.04 ns | 0.0219 |     - |     - |     744 B |
| FromTwoStates |     5 |   849.8 ns |  4.34 ns |  3.85 ns | 0.0448 |     - |     - |    1528 B |
| FromTwoStates |    10 | 1,439.6 ns |  5.94 ns |  5.27 ns | 0.0820 |     - |     - |    2752 B |
| FromTwoStates |    50 | 5,172.2 ns | …
=> Improve performance/reduce allocations in ButtonInput

osu.Framework.Android/AndroidGameActivity.cs
It turns out the logic wasn't even right for android screen suspension as it was missing a negation. Until now, the `KeepScreenOn` flag was set when `AllowScreenSuspension.Value = true`, which should actually be the other way around.
=> Fix android screen suspension logic

osu.Framework.Tests/Audio/SampleBassTest.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs
Fixes https://ci.appveyor.com/project/peppy/osu/builds/34357847/tests (I reproduced the failure in < 5 minutes of repeated tests, and could not for 1 hour of repeated testing with the fix applied). Should be obvious why this was breaking (the sample channel could still not be loaded at the time `Stop` is called).
Third new test fails on master 100%:
Also resolves https://github.com/ppy/osu/issues/9698.
=> Fix sample potentially being left in a playing state due to threading

osu.Framework/Statistics/BackgroundStackTraceCollector.cs, osu.Framework/osu.Framework.csproj
- Closes #3768 via new disposal of runtime
Stack traces must be stored as strings at the point of retrieval, else their underlying data is not available to be read at the point of logging. Sample output:
```
2020-07-29 16:06:30 [verbose]: | Stack trace:
2020-07-29 16:06:30 [verbose]: |- [GCFrame]
2020-07-29 16:06:30 [verbose]: |- [HelperMethodFrame]
2020-07-29 16:06:30 [verbose]: |- osu.Framework.Graphics.Sprites.SpriteText.CreateTextBuilder(osu.Framework.Text.ITexturedGlyphLookupStore)
2020-07-29 16:06:30 [verbose]: |- osu.Framework.Graphics.Sprites.SpriteText.computeCharacters()
2020-07-29 16:06:30 [verbose]: |- osu.Framework.Graphics.Sprites.SpriteText.computeScreenSpaceCharacters()
2020-07-29 16:06:30 [verbose]: |- osu.Framework.Graphics.Sprites.SpriteText+SpriteTextDrawNode.ApplyState …
```
=> Update to latest Microsoft.Diagnostics.Runtime

osu.Framework/Graphics/Drawable.cs, osu.Framework/Utils/Precision.cs
Resolves https://github.com/ppy/osu/issues/9200
Resolves https://github.com/ppy/osu-framework/issues/3780
Should resolve https://github.com/ppy/osu/issues/9460
I can't seem to be able to write a test that exhibits the issue, so I haven't included one in here.
I'm not sure how to feel about this conceptually. It seems like it may be a bit of a hit-or-miss sort of scenario where the acceptable difference may still be too low in complex hierarchies with autosize/etc.
=> Approximate IsMaskedAway with Precision

osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
This was allocating a ton with many hidden visualisers. E.g. the many-invalidation scenario in https://github.com/ppy/osu-framework/issues/3785 would allocate over 1GB/min.
These schedules don't seem to be required - they were likely here to prevent disposal-related failures but this code has also changed quite a lot over the years and I haven't been able to make it fail.
=> Fix allocations by hidden drawable visualisers

osu.Framework.Benchmarks/BenchmarkTransformUpdate.cs, osu.Framework.Tests/Visual/Containers/TestSceneVisibilityContainer.cs, osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Transforms/TargetMemberTransformTracker.cs, osu.Framework/Graphics/Transforms/Transformable.cs
Focuses on decreasing the iteration overhead of per-frame transform processing when many transforms are present in the transforms list (and cannot be removed due to rewind support or otherwise).
Store the last fully applied transform index and only continue processing from that point onwards. To keep things simple, invalidate this cache on any add/remove/rewind operation. These scenarios can be optimised in the future if/when required.
To make this work, transforms had to be split into per-`TargetMember` lists. If this was not the case, it becomes hard to choose a starting index (originally I was using the "minimum" of any `TargetMember` but this can lead to situations with no optimisation is possible).
As such, there is now one new `TargetMemberTransformTracker` class per `TargetMember` …
=> Improve performance of transform logic when many transforms are present

osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs, osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
Closes #3712.
Only issue left seems to be rounding errors that are particularly visible on large deadzones, which is fairly easy to replicate using triggers.
On my Dualshock 4, extreme values on triggers (deadzone `0.999f`) without clamping are `-1.0152590` and `0.9847410`.
=> Rescale joystick axis values according to deadzones

osu.Framework/Audio/Track/ITrack.cs, osu.Framework/Audio/Track/Track.cs, osu.Framework/Graphics/Audio/DrawableTrack.cs
Since `DrawableTrack` is seen as a complete alternative to `Track` that can be used in the draw hierarchy, it seems reasonable that the interface should be complete.
=> Complete the ITrack interface and DrawableTrack implementation

osu.Framework/Audio/Sample/SampleChannelBass.cs
Not sure why it isn't done already, it is a major problem for long samples, as the previous one would not get freed and stay playing without the game being aware of, which is a resource leak to my knowledge.
Untestable as it is an audio code, but I believe it should be very clear.
=> Fix previous sample channels not immediately freed on new playbacks

osu.Framework.Tests/Audio/TestSceneDrawableTrack.cs, osu.Framework/Graphics/Audio/DrawableTrack.cs
Fixes `DrawableTrack` resetting the underlying track, when it should be resetting its local adjustments instead. https://github.com/ppy/osu-framework/pull/3790 added the ability to add adjustments to `DrawableTrack`.
Also makes `DrawableTrack` an `IAdjustableClock` so it is interface-compatible with `Track`.
=> Fix DrawableTrack not resetting adjustments correctly

osu.Framework/Input/Bindings/KeyCombination.cs
Renames +/- to Plus/Minus to avoid conflict.
Before:
After:
=> Add better separator for KeyCombination display

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Always displayed at full size anyway, so not required.
=> Disable mipmapping on FrameStatisticsDisplay textures

osu.Framework/Game.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Visualisation/TextureVisualiser.cs, osu.Framework/Graphics/Visualisation/ToolWindow.cs
While looking into texture memory consumption, it became obvious that we are missing most of the picture and need to resort to 3rd party profilers to find where texture memory is being consumed outside of atlas textures.
This adds the ability to see all textures, no matter what usage.
Future work could split this view by `Type` name for better definition (ie. being able to see all `BufferedContainer` backing textures separately).
split into two categories:
aspect ratio support:
added tooltip information:
=> Atlas viewer view all textures

osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Video/VideoTexture.cs, osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
Two fixes here:
1. Making `VideoTexture.Bind()` forcefully upload the texture. This is already done in the base `TextureGLSingle.Bind()` so I thought of just copying the same usage. Probably fixes cases where GLWrapper's upload is running behind and doesn't upload the texture in time.
2. Fixing crash due to potentially null array + adding the bind count.
The texture visualiser will only show the ID of the first internal texture for each `VideoTexture`, and only the representation for the texture bound to slot 0 on the GPU, but will display an accurate frame size. It's a bit of a best-case effort sort of scenario for now, and we can maybe change that in the future but it requires `VideoTexture` to use `TextureGLSingle`s for the internal textures.
Also interesting to note that we somehow …
=> Fix VideoTexture not working with the texture viewer

osu.Framework/Audio/AudioManager.cs
Resolves https://github.com/ppy/osu/issues/3800
This should hopefully not cause any issues, because the buffer length remains unchanged from the previous value. This value is also ignored on Windows.
With that being said this needs confirmation on macOS and iOS, and possibly Android. On macOS/iOS specifically, buffer length is [documented](http://www.un4seen.com/doc/#bass/BASS_CONFIG_DEV_BUFFER.html) as being twice the device period, ignoring our custom value and potentially behaving badly after this change.
The other effect is CPU% increase from ~0.5% to ~1.5%.
Also I'm not sure what the removed lines were doing outside of the main `InitBass()` function, so I've moved them in there. I'm also further confused as to what `PlaybackBufferLength` does since I can't seem to find docs for it, …
=> Reconfigure bass for lower latency on linux

osu.Framework/Graphics/Textures/LargeTextureStore.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Graphics/Textures/TextureStore.cs
Regressed with the introduction of wrap modes (changing the key but not using it in all locations).
Also takes the load off the finalizer for actually disposing the gl-side texture.
=> Fix LargeTextureStore never purging textures

osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Turns out this is also too slow now to be useful. We can revisit this when we need it again. We are still far from requiring this for performance diagnostics.
=> Disable stack trace collection on windows

osu.Framework.Tests/Clocks/DecoupleableClockTest.cs, osu.Framework.Tests/Visual/Containers/TestSceneSizing.cs, osu.Framework/Graphics/Containers/SearchContainer.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/IO/Stores/IResourceStore.cs, osu.Framework/Platform/MacOS/MacOSGameWindow.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Timing/InterpolatingFramedClock.cs
Somehow, somewhere, several build warnings have popped up yet again; this PR is supposed to resolve them in the framework. Taking it from the top:
This one is actually split into three commits; e3563b9 is supposed to deal with the most obvious cases where you can either eliminate the default or even straight up convert to a get-only constant property with no additional cost.
d2f4ada removes `AverageFrameTime` from `InterpolatingFramedClock`, which was a remnant from an old `IFramedClock` member [removed in this commit](https://github.com/ppy/osu-framework/commit/9ad78a1335d7e764b59bb25654f363b225a14f5c).
6dfd270 contains the most interesting cases. One is a declaration of a virtual property that is supposed to default to `null` (so I left the initialiser in and suppressed the warning to …
=> Fix build warnings

osu.Framework/Audio/AudioManager.cs
Resolves https://github.com/ppy/osu/issues/9865
Needs more testing, especially with existing user configs (I tested with default PA config).
=> Revert device period to fix linux audio crackling

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/TransformableExtensions.cs, osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs, osu.Framework/Graphics/Transforms/Transform.cs, osu.Framework/Graphics/Transforms/TransformCustom.cs, osu.Framework/Graphics/Transforms/Transformable.cs
This basically brings back logic that was removed in the previous PR (#3779) as it is still required. The tracker class will now potentially be tracking more than one target member in the case they touch the same underlying property. Less optimal, but this is the best we can do (and should still be fine for most use cases).
For reference, I brought the `xAt(targetMember)` logic back from https://raw.githubusercontent.com/ppy/osu-framework/d0fc93793e7d4aac79d34dbdec7190a0951bdc16/osu.Framework/Graphics/Transforms/Transformable.cs, which can be cross-checked during review.
- Closes https://github.com/ppy/osu-framework/issues/3817
=> Fix transforms operating on same properties being applied out of order

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs, osu.Framework/Graphics/Transforms/Transformable.cs
Aims to resolve ppy/osu#9832, although I'm not sure if wasted effort in light of #3837.
Most of the paper trail as to why this arose is [in the issue](https://github.com/ppy/osu/issues/9832#issuecomment-674459266). In short: adding a transform during load or outside hierarchy would wrongly update a single tracker's last applied transform index, while the transformable itself kept a last transform time which was not updated in line, leading to a desync.
Resolve as proposed [here](https://github.com/ppy/osu/issues/9832#issuecomment-674482116) by updating the entire transformable.
This resolution actually let me uncover #3837, as I went to check a storyboard and saw that it wasn't processing `X` transforms properly (but `Y` transforms worked). That was due to them having an equal …
=> Fix transforms added during load being potentially not processed

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
Closes ppy/osu#9882
Regression from #3289
Replaces text mutation events to only being called when the mutation is done by user input.
- There is a commented piece of the pushed test case, which is about pressing a key and checking if the event handler has been invoked, but currently, the text input consumption logic is limited at a host level from manipulating or creating a test class for it, making this not straightforward to test, didn't want to bother with it so I added a TODO comment on top of it for now.
- First time using regions inside methods, but felt better than splitting each in an own test case method as it requires setting up the same textbox for each, lengthening the test scene even more.
- There is also a side-issue with the textbox text property that became visible on the …
=> Invoke text mutation method events only when done by user input

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
- Closes https://github.com/ppy/osu-framework/issues/3837.
Best understood by going through commits one by one and looking at test failures in `TestSceneTransformRewinding` in visual tests, but basically:
- We don't want to be applying transforms in the rewind code. This is iterating in the wrong direction through the transforms list and will not lead to correct application order between overlapping TargetMembers.
- With the removal of the application just mentioned, a regression shows up when adding a transform in the past which will immediately complete in the next frame – rewind logic will not be run to reset `AppliedToEnd` so the end value may not be updated correctly. This is resolved by marking as *not* `AppliedToEnd` in `AddTransform` when required.
- All dictionary / cache logic …
=> Fix transforms potentially being skipped due to incorrect order of application

.editorconfig
As per osu!-side change:
https://github.com/ppy/osu/pull/9925
=> Disable CA2225 warning regarding operator overloads

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs, osu.Framework/Graphics/Animations/AnimationClockComposite.cs
Resolves #3847 / usable with ppy/osu#9985 (although not necessarily a hard dependency)
Setting `PlaybackPosition` before the animation was loaded could result in a `NullReferenceException` due to not necessarily having received a clock in `Time` yet.
As proposed in the issue, resolve this by not consuming time in the setter of `PlaybackPosition` if the animation isn't yet loaded -`LoadComplete()` will do it anyway before the update loop starts to run.
I opted not to add the guard to `consumeClockTime` itself as other call sites should be safe and should actually throw if the operation doesn't succeed. The other call sites are:
* `Clock.set` - should have access to `Time` by the virtue of actually setting the animation's clock,
* `LoadComplete()` - should have correct clock in place …
=> Add support for seeking a non-loaded animation

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/IBindableList.cs, osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Utils/Validation.cs
Would appreciate a double check on `BindableListTest` changes as there are actually a good amount of asserts on the obsolete events there along with the new one. (I've removed what's under the obsolete warning suppress and any assertion that uses a variable declared inside).
Also looks like `IBindableList` hasn't marked `ItemsAdded` and `ItemsRemoved` as obsolete, thus `GlobalStatisticsDisplay` and `Dropdown` not updated to use `CollectionChanged` instead. I think it's fine to remove the obsolete events? not sure... (currently removed them)
=> Remove obsolete members

osu.Framework/Audio/AdjustableAudioComponent.cs, osu.Framework/Audio/AggregateAdjustmentExtensions.cs, osu.Framework/Audio/AudioAdjustments.cs, osu.Framework/Audio/IAggregateAudioAdjustment.cs, osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
To avoid aggregate adjustment implementations from having to implement both `Aggregate{Volume,Balance,Frequency,Tempo}` and `GetAggregate()`, the latter has been made an extension method returning one of the aforementioned four values for the appropriate property of the adjustment.
Possible compilation failures related to `GetAggregate()` should be resolved by adding a using statement for the `osu.Framework.Audio` namespace to the files affected. 
---
Probably incorrect to have both `Aggregate{Volume/Balance/etc..}` and `GetAggregate()` require implementation from the class when one should redirect to the other.
Could use default interface implementation for this, but would cause changing every usage to do an explicit cast to the interface …
=> Move IAggregateAudioAdjustment.GetAggregate() to extensions method

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework/Bindables/BindableList.cs
Noticed this while investigating #3852.
=> Avoid firing CollectionChanged on no-op BindableList.RemoveAll

osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/DesktopWindow.cs, osu.Framework/Platform/Display.cs, osu.Framework/Platform/DisplayMode.cs, osu.Framework/Platform/IWindowBackend.cs, osu.Framework/Platform/Sdl/Sdl2Extensions.cs, osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs, osu.Framework/Platform/Window.cs
Adds some minor missing features to the `DesktopWindow` class without making significant changes to the SDL window backend.  The work in this PR will be required regardless of the windowing toolkit we end up using.
* Last window display and relative position are now remembered between sessions
* Window mode is now remembered between sessions
Alternative to part of #3781.  If we end up sticking with SDL, much of the code in that PR can be rebased/reused.
Needs testing on Linux.
=> Remember window position between sessions (SDL)

osu.Framework.Tests/Platform/ComponentAsyncDisposalTest.cs, osu.Framework.Tests/Platform/GameHostSuspendTest.cs, osu.Framework.Tests/Threading/AsyncDisposalQueueTest.cs, osu.Framework/Allocation/AsyncDisposalQueue.cs, osu.Framework/Game.cs
Wait for global async disposal queue to empty before disposing the game itself, as the components within may be relying on game/host access in their ongoing background functions (ie. if they are still in an async load cancelling state).
Fixes test failures seen in https://github.com/ppy/osu/pull/10026, that started to show up from various usage of `DelayedLoadUnloadWrapper` (which is using the async disposal queue in a slightly different way since https://github.com/ppy/osu-framework/pull/3825/files).
I also fixed an edge case in `AsyncDisposalQueue` which can't be easily tested but should be easy enough to understand:
- Enqueue an item
- Processing begins on that item
- New item enqueued before processing ends. Task isn't started because one is already running, but that task will not …
=> Fix Game.Dispose potentially ending before children have been (async) disposed

osu.Framework/Game.cs
Previous change (#3860) was not enough to always fix the issue (happened again [here](https://ci.appveyor.com/project/peppy/osu/builds/35023352/tests)).
I was able to reproduce the failure locally, and this more solid fix has not failed over 1000+ test runs.
=> Change disposal order to better protect against async disposal queue failures

osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
Wild guess for why that check is there is to early-return on invalid axes (i.e. ones that a controller supports less axes from reaching), but that's very wrong for the case where a user just puts his controller on the desk and waits for the game to load up first.
Here's the axis values and deadzones while leaving the controller on the desk on `master`:
```
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick Axis0: Value=0, Deadzone=0
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick Axis1: Value=0, Deadzone=0
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick Axis2: Value=0, Deadzone=0
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick Axis3: Value=0, Deadzone=0
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick Axis4: Value=0, Deadzone=0
[runtime] 2020-09-05 04:07:50 [verbose]: Joystick …
```
=> Fix default deadzones not set properly for idle axes

osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Android/Input/AndroidKeyboardHandler.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Bird.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs, osu.Framework/Audio/Track/Waveform.cs, osu.Framework/Bindables/BindableNumber.cs, osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs, osu.Framework/Graphics/Containers/AudioContainer.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Primitives/Line.cs, osu.Framework/Graphics/Primitives/RectangleF.cs, osu.Framework/Graphics/Transforms/TransformSequence.cs, osu.Framework/Input/Bindings/InputKey.cs, osu.Framework/Input/ButtonEventManager.cs, osu.Framework/Input/Events/DoubleClickEvent.cs, osu.Framework/Input/Events/DragEndEvent.cs, osu.Framework/Input/Events/DragEvent.cs, osu.Framework/Input/Events/DragStartEvent.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Platform/ThreadRunner.cs, osu.Framework/Threading/Scheduler.cs, osu.Framework/Utils/Blur.cs
Judging by https://github.com/ppy/osu/commit/da41b70d438108d09b058bdc05b8f6f93c8d1f19, replacing MathHelper with Math seems fine.
=> Typo fixes & Math.Clamp

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/BasicDropdown.cs, osu.Framework/Graphics/UserInterface/BasicTabControl.cs
Fixes https://github.com/ppy/osu-framework/issues/3881
Added some basic styling that isn't a plain box like the "styled tab controls" already in the test:
Side note: what the heck is this pattern? This is so inverse to how anything in the framework should work... `TabControl` + `Dropdown` are long due for a makeover.
=> Fix BasicTabControl not working

osu.Framework.Tests/Audio/TrackVirtualTest.cs, osu.Framework/Audio/Track/TrackVirtual.cs
Actual playback rate wasn't being tested, and turns out the aggregate portion wasn't being correctly accounted for.
=> Fix virtual track tempo propagation

osu.Framework/Graphics/Drawable.cs
Hoisted out of https://github.com/ppy/osu-framework/pull/3894 because that PR needs more consideration.
Sets the parent field instead of the property, bypassing the invalidation which is unnecessary for all propagation sources (self, parent, child).
Explanation for why the propagate-invalidation-to-parent case is unnecessary: disposal can not occur unless either 1) the drawable is removed from the parent (i.e. the parent will have invalidated from elsewhere) or 2) the parent is also being disposed.
Before:
After:
=> Improve performance of drawable disposal

osu.Framework/Graphics/Textures/LargeTextureStore.cs, osu.Framework/Graphics/Textures/TextureStore.cs
Prereqs:
This is pretty visible by scrolling through beatmap listing with https://github.com/ppy/osu-framework/pull/3894.
The contention occurs between `Get()` and `Purge()`, especially when online resources are involved.
Another level of locking has been added to ensure that only one retrieval is happening concurrently (preserves current behaviour) and that the lock on `textureCache` is taken for as short of a period as possible.
=> Reduce TextureStore lock contention

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/TransformableExtensions.cs, osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs, osu.Framework/Graphics/Transforms/Transformable.cs
Closes #3821
Supersedes #3902 
See https://github.com/ppy/osu-framework/pull/3902#issuecomment-699742964 for reason why superseded.
---
`ReadIntoStartValue()` is added before `Apply()` to fix cases where the position offset transform would be applied without its value being read, therefore leading to incorrect results. (as the commit says https://github.com/ppy/osu-framework/commit/1589926137f8e295bad6923bd939ea8af96d9c43)
=> Fix offset-based position transform not respecting previous transforms

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Testing/TestBrowser.cs
The text should make the issue self-explanatory. Also converts the `OnCommit` delegate to a proper `event` type.
=> Fix TextBox.OnCommit firing with incorrect "isNew" value after manual text change

README.md
We had a project rename to not confuse us being a part of HoloLive - hence we're updating our project references from other listings to the new name.
=> Update holotrack to Vignette

osu.Framework/Graphics/Textures/LargeTextureStore.cs, osu.Framework/Graphics/Textures/TextureStore.cs
The reduction in lock contention from https://github.com/ppy/osu-framework/pull/3895 brought in some race conditions centred around caching. This has failed a few of our CI runs: https://ci.appveyor.com/project/peppy/osu/builds/35530150/tests
I had 3 goals in mind:
1. Fix the race condition.
2. Maintain the performance improvements from that original PR.
3. Avoid deadlocks.
The failures can be explored with the following repro:
```csharp
public class TestSceneTesting : FrameworkTestScene
{
private LargeTextureStore largeStore;
[BackgroundDependencyLoader]
private void load(GameHost host, Game game)
{
largeStore = new LargeTextureStore(host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(game.Resources, @"Textures")));
}
[Test]
public void RunTest()
{
AddStep("start threads", …
```
=> Fix LargeTextureStore reference count race conditions

osu.Framework/Audio/Sample/ISampleChannel.cs, osu.Framework/Audio/Sample/Sample.cs, osu.Framework/Audio/Sample/SampleBass.cs, osu.Framework/Audio/Sample/SampleChannel.cs, osu.Framework/Graphics/Audio/DrawableSample.cs
PRing for potential use with ppy/osu#10358, albeit I'm not 100% convinced it will prove useful just yet.
Expose the length of `Sample`s, `SampleChannel`s and `DrawableSample`s to framework consumers. The unit chosen to expose at is milliseconds, for consistency with other members (`Time.Current`, `Track.Length`).
`VirtualSample`s and `SampleChannelVirtual` instances will report a zero length by default.
=> Expose sample length

osu.Framework/Graphics/Containers/CompositeDrawable.cs
While we'd like to say that reference leaks will never occur, when they do, having a reference to dependencies still live can cause a runaway scenario where the single reference leak can be holding references to a whole subtree for good.
Adding this as a failsafe avoids such scenarios.
=> Clear reference to dependencies aggressively on CompositeDrawable disposal

osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs, osu.Framework/Graphics/Audio/WaveformGraph.cs
Fixes https://github.com/ppy/osu/issues/10460
Now respects alpha + parent colour.
`Colour` now uniformly affects the entire graph as expected.
=> Fix WaveformGraph bypassing parent colour

osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs
This is a huge oversight: calling `LoadComponentAsync` with a live `IEnumerable` will result in the provided drawable(s) being constructed multiple times. The final returned values are also not the loaded once, but fresh instances.
I've confirmed the test I added behaves per expectations on master / this branch, but I've somehow broken exceptions and reference retention with this change. PRing for feedback.
=> Fix LoadComponentAsync enumerating input enumerable multiple times

osu.Framework.Benchmarks/BenchmarkBindableList.cs, osu.Framework/Bindables/BindableList.cs
For the rare case when someone may enumerate a `BindableList<T>`.
```diff
|    Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
- | Enumerate | 8.641 us | 0.1626 us | 0.1597 us | 0.1068 |     - |     - |   3.91 KB |
+ | Enumerate | 2.360 us | 0.0106 us | 0.0083 us |      - |     - |     - |         - |
```
=> Remove BindableList<T> enumerator allocations

osu.Framework.Tests/Lists/TestSortedList.cs, osu.Framework/Lists/SortedList.cs
The `List<T>` enumerator has additional safety guards preventing against modifying the collection during enumeration. There was no reason for `SortedList<T>` to have a custom enumerator other than to prevent boxing, but `List<T>.Enumerator` is already exposed for that purpose.
=> Remove custom SortedList<T> enumerator

osu.Framework/Platform/DesktopWindow.cs, osu.Framework/Platform/MacOS/MacOSDesktopWindow.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/MacOS/MacOSWindowBackend.cs, osu.Framework/Platform/MacOS/Native/Class.cs, osu.Framework/Platform/MacOS/Native/Cocoa.cs, osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs, osu.Framework/Platform/Window.cs
Adds support for "precise" scrolling on macOS for the SDL backend.
Due to the way SDL handles scroll wheel events on macOS, the precise deltas in the `NSEvent` are ignored.  Unfortunately, the originating `NSEvent` is not available to us anywhere in the SDL event loop itself.
To solve this, we swizzle out `[SDLView scrollWheel:(NSEvent *)]` to use our own custom function that handles precision deltas.  If precision deltas are unavailable (due to using a physical notched scroll wheel rather than a trackpad), it calls the original implementation of the method.
The logic for converting and scaling precise deltas is the same as that in osuTK's `CocoaNativeWindow`.
Instantiation of `IWindowBackend` and `IGraphicsBackend` have been moved to abstract methods rather than being passed down through …
=> Implement precise scrolling for SDL

osu-framework.sln.DotSettings, osu.Framework.Tests/IO/TestDesktopStorage.cs, osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs, osu.Framework/Graphics/Shaders/ShaderPart.cs, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/IO/Stores/DllResourceStore.cs, osu.Framework/IO/Stores/NamespacedResourceStore.cs, osu.Framework/Platform/NativeStorage.cs, osu.Framework/Testing/TestBrowser.cs
Turns out we had these disabled for whatever reason. As they recently caused issues in stable, I wanted to get these out of the way to ensure they can't be an issue here. I'm guessing it may resolve some issues specific regions may already be seeing (ruleset loading?).
Also applies a couple of new inspections that come from Rider EAP.
=> Enable string StartsWith/EndsWith culture inspections and fix usages

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
This aims to let ppy/osu#10493 be merged. I am PRing this just to have this out/visible/editable by someone other than me, so that me looking at this is not a blocker.
There are three distinct issues this PR aims to fix. As they touch the same places I don't really want to split this into three PRs as it'd probably significantly harm readability.
As I outlined in the PR thread already, DLW has two flags that determine whether the content needs to be loaded: `DelayedLoadTriggered` and `DelayedLoadCompleted`. On current `master`, the first is a shorthand for `loadTask != null`, and the second is a shorthand for `InternalChildren.Count > 0`.
Because the addition of `Content` is scheduled in DLW, there is a one-frame window of opportunity in which `DelayedLoadTriggered` becomes `false` (as …
=> Improve robustness of DLW/DLUW logic

osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/GameThread.cs
This is really only ever going to be an issue in tests.
I noticed while running tests via `dotnet test` on Windows, that memory would spike up above 2GB on the test runner. Dumped the process and found...
So previous `AudioManager` instances were being left alive, but how?
Well the only way that this delegate stops is if the cancellation token is cancelled, which happens in `AudioManager.Dispose(bool)`: https://github.com/ppy/osu-framework/blob/93bd7a6e9bb75cc2232c3582e76ba960db680bcb/osu.Framework/Audio/AudioManager.cs#L160-L162
Note that this is the **virtual** Dispose, which is enqueued onto the audio thread.
When exiting, the audio thread correctly disposes the manager:
https://github.com/ppy/osu-framework/blob/93bd7a6e9bb75cc2232c3582e76ba960db680bcb/osu.Framework/Threading/AudioThrea …
=> Fix AudioManagers not disposed on audiothread disposal

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Not only does this tidy up the `DelayedLoadUnloadWrapper` flow, but it allows us to (in both cases) avoid the overhead of construction of the content drawable until a load actually occurs.
Tested against my beatmap carousel changes, this reduces finalizer disposal to zero (and greatly reduces allocs in fast scrolling) as expected.
- Make sure you are okay with the Relative/AutoSize propgation. I haven't changed anything for the old-style ctor for compatibility reasons, but now the transfer is done at load time, overwriting anything set locally. Maybe this needs to be mentioned somewhere in the xmldoc?
- Should we obsolete the old ctor?
=> Allow DelayedLoadWrapper to late-construct its content

osu.Framework/Platform/HeadlessGameHost.cs
Noticeable in benchmarks. Doesn't seem to affect tests at all (likely due to the clock override) but seems safe to put in headless as a catch-all anyways.
before:
|              Method |     Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------:|--------:|--------:|------:|------:|------:|----------:|
|   TestEmptyGameLoop | 994.6 us | 1.49 us | 1.25 us |     - |     - |     - |      20 B |
|  TestAllocContainer | 993.8 us | 1.92 us | 1.80 us |     - |     - |     - |    1665 B |
| TestLoadedContainer | 993.6 us | 2.14 us | 2.00 us |     - |     - |     - |    2124 B |
|     TestAllocSprite | 994.0 us | 1.93 us | 1.80 us |     - |     - |     - |    1424 B |
|    TestLoadedSprite | 993.9 us | 2.62 us | 2.45 us |     - |     - |     - |    1706 B | …
=> Fix headless being limited to 1000hz

osu.Framework.Benchmarks/BenchmarkManySpinningBoxes.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs, osu.Framework/Graphics/Transforms/TransformSequence.cs, osu.Framework/Graphics/Transforms/Transformable.cs
A collection of a few low-effort allocation optimisations. Most applicable to the edge case where `AutoSizeDuration > 0` and size is updated every frame. This happens at the osu! menu.
I think a more permanent solution would be using a Lerp call in place of this, but we will need to obsolete / remove `AutoSizeEasing` (not sure we want this - it can give correct results in the case autosize is only changed once in a while... but maybe it's just not worth supporting?).
before
|                       Method |       Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-----------:|--------:|--------:|------:|------:|------:|----------:|
|                     RunFrame |   739.0 us | 5.82 us | 4.86 us |     - |     - |     - |       1 B |
| …
=> Improve transform allocation overhead (with focus on AutoSize)

osu.Framework/Graphics/Pooling/DrawablePool.cs
This can be/has been useful in visualising pool usage.
Preview: https://drive.google.com/file/d/16bMpWYfDMOecs67TBJMY2M7-7bEs7eEG/view?usp=sharing
The current format is `count_available / count_newed (count_in_use)`, but please provide an alternative if this doesn't sit right with you.
=> Add DrawablePool statistics to GlobalStatistics

osu.Framework/Graphics/Pooling/DrawablePool.cs, osu.Framework/Graphics/Pooling/IDrawablePool.cs
Hitobject pooling has brought up a case where it's necessary to retrieve drawables from a set of untyped pools where constraints on the types retrieved are locally guaranteed.
This makes the following (example) scenario possible:
```csharp
private List<IDrawablePool> pools = new List<IDrawablePool>();
void Register<T>(DrawablePool<T> pool)
where T : DrawableHitObject, new()
{
pools.Add(pool);
}
DrawableHitObject Retrieve()
{
// DrawableHitObject type guaranteed by the constraint on Register().
return (DrawableHitObject)pools[2].Get(d => ((DrawableHitObject)d).SomeMethod());
}
```
=> Add a way to retrieve unknown types from DrawablePool

osu.Framework.Tests/Lists/TestSortedList.cs, osu.Framework.Tests/Visual/Containers/TestSceneCompositeDrawable.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Lists/SortedList.cs
Re-sorting children on comparer change is really ugly and error prone. It's done in at least `HitObjectContainer` osu!-side, where the comparer is sorted by `HitObject.StartTime` (a mutable variable), and the solution is to remove-then-readd:
https://github.com/ppy/osu/blob/89797d7a57e6c86bb9c15c03fd67e4b60cedbfaa/osu.Game/Rulesets/UI/HitObjectContainer.cs#L67-L75
The upcoming hitobject pooling changes demonstrate the error-proneness of this - remove-then-add is not possible with `PoolableDrawable` because they're returned to the `DrawablePool` when the parent is changed:
https://github.com/ppy/osu-framework/blob/d42278299b1b3ce1b06781563f063b71f89238e3/osu.Framework/Graphics/Pooling/PoolableDrawable.cs#L115-L124
Based on the several workarounds I've tried to get around this, I've come to …
=> Add a way to re-sort CompositeDrawable children

osu.Framework/Platform/Sdl/Sdl2Extensions.cs
Aims to address [some](https://github.com/ppy/osuTK/pull/67#issuecomment-715893612) [complaints](https://github.com/ppy/osuTK/pull/67#issuecomment-715893732) with SDL keyboard handling.
Users have reported that when using SDL on some regional keyboard layouts (German QWERTZ/French AZERTY, for one), some keys which are used to insert characters like ü, ä, ß, do not seem to trigger text box input.
As it turns out, not all possible values of the `SDL_Keycode` enumeration (https://wiki.libsdl.org/SDL_Keycode) have their symbolic names. In the case of those special keyboard layouts, pressing the special diacritics keys would emit a `Keycode` with a value correspondent to the Unicode code point of the character pressed by the user, which has no osuTK correspondent, therefore getting converted …
=> Use scan codes instead of key codes in SDL mapping

osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
[SDL_TEXTINPUTEVENT.text](https://wiki.libsdl.org/SDL_TextInputEvent) is incorrectly parsed as ANSI instead of UTF-8, leading to incorrect non-ascii text inputs.
Before:
After:
=> Fix unmanaged string being incorrectly parsed as ANSI in SDL

osu.Framework/Testing/TestingExtensions.cs
Could potentially fail when components are being asynchronously loaded.
```
osu.Game.Tests.Visual.Editing.TestSceneEditorClipboard.TestCutPaste(2000)
TearDown : System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
--TearDown
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at osu.Framework.Testing.TestingExtensions.ChildrenOfType[T](Drawable drawable)+MoveNext()
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
at osu.Game.Tests.Visual.EditorTestScene.get_EditorComponentsReady()
```
Not that this really solves the issue but it should be fine for this test-only method.
=> Fix ChildrenOfType being thread-unsafe

osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs, osu.Framework/Screens/ScreenStack.cs
An issue that arose while looking into https://github.com/ppy/osu/issues/10418. Not required to fix that issue, but probably good to fix this while we're here.
=> Fix OnResume being called twice when calling Exit from a blocked OnExiting implementation

osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs, osu.Framework/Screens/ScreenStack.cs
Fixes issue mentioned [here](https://github.com/ppy/osu-framework/pull/3956#discussion_r513874990).
=> Fix incorrect resume source when exit is blocked midway

osu.Framework/Platform/MacOS/MacOSDesktopWindow.cs, osu.Framework/Platform/MacOS/MacOSGraphicsBackend.cs, osu.Framework/Platform/MacOS/Native/Cocoa.cs
Fixes a potential crash where SDL can incorrectly attempt to call `[NSOpenGLContext update]` on a non-main thread from within `SDL_GL_SwapWindow`.
=> Replace SDL_GL_SwapWindow with flushBuffer call on macOS

README.md, osu.Framework.Templates/README.md
Long overdue, really. Hopefully will make starting off easier for people who might not be aware that these exist.
The README link will look bad if clicked from the rich diff, but [this](https://github.com/bdach/osu-framework/tree/templates-readme/osu.Framework.Templates) is how it's supposed to look (link points to same subdirectory on my fork/branch - git shows `README.md` file contents in subdirectories too).
Wording ~~stolen~~ borrowed and slightly tweaked from the [ruleset templates](https://github.com/ppy/osu-templates).
=> Add documentation about project templates

.idea/.idea.osu-framework/.idea/indexLayout.xml, osu.Framework.Android/AndroidGameWindow.cs, osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs, osu.Framework.iOS/IOSGameWindow.cs, osu.Framework/Graphics/Containers/SafeAreaDefiningContainer.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/IWindow.cs, osu.Framework/Platform/Linux/LinuxGameHost.cs, osu.Framework/Platform/Linux/OsuTKLinuxWindow.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/MacOS/MacOSWindow.cs, osu.Framework/Platform/MacOS/OsuTKMacOSWindow.cs, osu.Framework/Platform/OsuTKDesktopWindow.cs, osu.Framework/Platform/OsuTKWindow.cs, osu.Framework/Platform/Windows/OsuTKWindowsWindow.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
Part of an effort to make the window hierarchy understandable to the point I can work with it.
=> Add OsuTK prefix and drop "Desktop" naming where redundant

osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs, osu.Framework/Platform/Window.cs
This is mostly for windows, where the window can be drawn bright white while initialising, but also seems to have an effect on macOS (draws transparent/gray otherwise).
=> Fix SDL drawing window white on first display on windows

osu.Framework.Android/AndroidGameWindow.cs, osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework.iOS/IOSGameWindow.cs, osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs, osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandlerBase.cs, osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameWindow.cs, osu.Framework/Platform/IWindow.cs, osu.Framework/Platform/Window.cs, osu.Framework/Platform/Windows/WindowsDesktopWindow.cs
Simplest possible implementation. Note that this ends up using osuTK's fallback when mouse is outside the window / non-focused. I don't think this is a huge deal.
=> Allow SDL to use existing raw input implementation

osu.Framework/Game.cs, osu.Framework/Platform/GameHost.cs
As proposed in https://github.com/ppy/osu/pull/10496, this splits out cache storage to its own immutable location. We can add game customisation of it if/when that need arises, but for now the idea is to have it on the OS drive / default install location for highest performance.
=> Expose and define cache storage

osu.Framework/Graphics/Pooling/DrawablePool.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs
Tried a few things osu-side, but I think this is the simplest/least hacky solution.
Will fix the test failures in https://github.com/ppy/osu/pull/10717
=> Avoid resetting drawable lifetime on PooledDrawables that aren't assigned a pool

osu.Framework/Audio/Sample/SampleChannelBass.cs, osu.Framework/Audio/Track/TrackBass.cs
Turns out calling `UpdateState` is not enough since it still checks the `pendingInvalidation` flag.
Closes https://github.com/ppy/osu/issues/10778.
=> Fix initial application of state not occurring if invalidation not pending

osu.Framework/Audio/Sample/SampleStore.cs, osu.Framework/Graphics/Textures/TextureStore.cs
While this is still generally a no-go (you can never be sure that the underlying texture/sample lookups are cached, which is why we always logged) the overhead from logging these issues can become overwhelming, with megabytes of output per second.
This should still be enough to generally cover cases a developer would care about.
=> Don't log performance issues on non-async lookups if they are cached

osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs, osu.Framework/Graphics/Transforms/Transform.cs, osu.Framework/Graphics/Visualisation/DrawVisualiser.cs, osu.Framework/Graphics/Visualisation/DrawableInspector.cs, osu.Framework/Graphics/Visualisation/DrawableTransform.cs, osu.Framework/Graphics/Visualisation/PropertyDisplay.cs, osu.Framework/Graphics/Visualisation/TransformDisplay.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs
This PR adds a way to preview transform application progress from the draw visualiser. See [video showing preview of behaviour](https://drive.google.com/file/d/1cDzC90larwbeEQEBmOLcJdVrZV_dmu7t/view?usp=sharing).
Display code partially shamelessly stolen from existing test scene and wedged into the draw visualiser. Allocating drawables every frame is admittedly wasteful, but seeing that it's for debugging purposes... Tracking transforms externally is not an easy task anyway (I fiddled some with `WeakReference`s but my attempts appeared crazily unsafe - could seemingly die on a nullref even if `TryGetTarget` returned `true`). For what it's worth I confirmed that the code doesn't run unless the tab is specifically opened.
Mostly usable for rewindable transforms. I made a proof-of-concept of …
=> Add transform preview to draw visualiser

.config/dotnet-tools.json, build/build.cake, osu-framework.sln.DotSettings, osu.Framework.Tests/Text/TextBuilderTest.cs, osu.Framework/Allocation/CachedModelDependencyContainer.cs, osu.Framework/Graphics/Containers/GridContainer.cs, osu.Framework/Graphics/Transforms/Transformable.cs
ReSharper command-line tool and `NVika` is updated to the latest version. The new versions publish itself as `dotnet tool` and it makes the build script simpler. The new versions also allow `InspectCode` target of the Cake build script to run in non-Windows machines.
There were new ReSharper errors due to the version difference. I used several ad-hoc struct types to workaround the issue (it seems like the tuple types are the issue). I also added a setting to prevented `*.h` shader header files to be analyzed as C++ header files and causing errors.
=> Update tools to allow InspectCode to run in non-Windows environment

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Motivated by all the DCC failures we've been having recently, I've tried to change the heuristic to something that is more statistically sound rather than guesswork attempting to do the same.
The tl;dr is to exclude traversing into parents that are outliers depending on how many subsequent parents they would expand.
For example, if we're iterating through judgements which aren't really referenced that much and thus expand 1-2 parents, but then reach `OsuPlayfield` that is referenced by a lot of the hierarchy and thus expands 100 parents, `OsuPlayfield` is treated as an outlier.
Up to you whether these changes should be merged at this point or wait until another DCC issue comes up and it can be tested to work there. My current testing:
```
Pass:
TestSceneScorePanel -> AccuracyCircle …
```
=> Rework DCC class expansion heuristic to reduce failures

osu.Framework/Testing/AssemblyReference.cs, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/EmptyTypeReferenceBuilder.cs, osu.Framework/Testing/IDynamicallyCompile.cs, osu.Framework/Testing/ITypeReferenceBuilder.cs, osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
This is a bit of a proof-of-concept and I'm not sure on the viability of it going forward, ready for merge if you think it's fine. It fixes the `TestSceneDrawableJudgement -> LegacyJudgementPieceNew` case pointed out in Discord (accessing `SkinInfo.DEFAULT_SKIN`, etc).
See https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/ for more info.
There is an internal compiler attribute `IgnoresAccessChecksTo(assemblyName)` which acts inversely to `InternalsVisibleTo(assemblyName)`. However it:
1. Requires setting internal compiler option `TopLevelBinderFlags`, and thus the API surface may change.
2. Requires importing all `internal` symbols, which can be an issue because it means there is the possibility of type conflicts in matching …
=> Allow dynamic recompilation to access internal members

osu.Framework/osu.Framework.csproj
- Closes https://github.com/ppy/osu-framework/issues/4004
- Fixes crashes on mojave.
=> Update SDl2 native libraries to fix issues on windows and macOS

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework/Graphics/Drawable.cs
closes #4014
As mentioned in the issue, unbinding external bindables is pretty dodgy. I updated the unbinding code and changed the test to test for the opposite behaviour.
=> Do not include bindable properties in UnbindAllBindables

osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs
This turns out to be quite dangerous and the cause for https://github.com/ppy/osu/issues/10938. It also fixes hitobjects disappearing in the editor at random.
Closes https://github.com/ppy/osu/issues/10938.
=> Fix PrepareForUse potentially getting called twice on the same pooled usage

osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs
Prereqs:
Discovered in https://github.com/LumpBloom7/sentakki/pull/144, which adds its own sound to the hierarchy: https://github.com/LumpBloom7/sentakki/blob/0f6747f305f1ce0cff18c2b4b50196046b1b5fa4/osu.Game.Rulesets.Sentakki/Objects/Drawables/DrawableSlideNode.cs#L50-L55
This wasn't discovered on our side since we're always adding to child containers, and child invalidations only propagate upwards one level. It's probably arguable whether a child's `Parent` invalidation should propagate to its parent, but that's a consideration for another day.
=> Fix PoolableDrawable being returned from child invalidations propagating upwards

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Threading/Scheduler.cs
As discussed in Discord, there's been very few times when a `bool` return has been useful here.
Additionally, in some places such as `PoolableDrawable`, it's unsafe to use `AddDelayed` unless you're fully conscious of potential rewindability because `AddDelayed` adds the clock's current time to the execution time. At this point, I'd say none of us are able to do this since such a regression went completely unnoticed in https://github.com/ppy/osu-framework/pull/4017.
Another point to consider is `Drawable.Schedule()` forwards to `Scheduler.AddDelayed` to apply the transform delay (even if 0), which is also "unsafe" as above if you're only expecting something to be executed in the next update. Such cases can be handled in two ways:
```
using (BeginAbsoluteSequence(double.MinValue)) …
```
=> Make Scheduler.Add() return the scheduled delegate

osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
Should fix https://github.com/ppy/osu/issues/10969
I'm not currently able to test this, so would appreciate a confirmation. Should be replicable by adding a `GC.Collect(); GC.WaitForPendingFinalizers()` after the `openedDevices.Remove(key);` line.
=> Close midi devices on disconnect

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
Can reproduce this 100% when running tests from rider (headless). Not sure if this covers the test scenario completely (seems like the drawables are loaded asynchronously), can add some wait and re-assert steps if that's deemed required.
Closes https://github.com/ppy/osu-framework/issues/3930.
=> Fix RearrangeableList tests failing via headless run

osu.Framework/Platform/GameHost.cs
From:
To:
Discovered this mostly by accident, but it seems like having the crashed thread exit before the debugger does its thing causes the stack trace to not display correctly.
Scenarios I've tested:
- Throw in `DrawableHitObject.load()` single/multi-threaded.
- Throw in `DrawableHitObject.Update()` single/multi-threaded.
- Throw in `DrawableHitObject.load()` with `TestSceneOsuPlayer.TestConstructor`.
- This doesn't launch your debugger but that seems to just be a function of how nunit works since it runs all test code within exception-safe blocks.
=> Fix some debuggers not correctly showing exception stacks

osu.Framework/Platform/SDL2DesktopWindow.cs
Didn't notice this as it only happens when startup occurs fast enough to GC to have run (not in my VM or with a debugger attached, but can happen on my gaming PC).
Fixes the following startup crash:
```
Process terminated. A callback was made on a garbage collected delegate of type
'SDL2-CS!SDL2.SDL+SDL_EventFilter::Invoke'.
at SDL2.SDL.SDL_ShowWindow(IntPtr)
at SDL2.SDL.SDL_ShowWindow(IntPtr)
at osu.Framework.Platform.SDL2DesktopWindow+<>c__DisplayClass67_0.<set_Visible>b__0()
```
=> Fix native delegate callback getting garbage collected

osu.Framework/Graphics/Visualisation/DrawableInspector.cs
Closes #4042.
Apparently that wasn't how fill flows work, so there's a grid in there now.
=> Fix draw visualiser trimming last property in scroll

osu.Framework/Platform/SDL2DesktopWindow.cs
With previous logic we were not handling `WINDOWEVENT_RESTORED`. As it turns out, the `FOCUS_GAINED` event is not fired in cases where a window is restored from a minimised state, potentially leaving the game thinking it is not active (and blocking input).
on winkey-d:
```
SDL_WINDOWEVENT_MINIMIZED
SDL_WINDOWEVENT_LEAVE
SDL_WINDOWEVENT_FOCUS_LOST <-- focus lost fired, but focus gained doesn't
SDL_WINDOWEVENT_RESTORED
SDL_WINDOWEVENT_EXPOSED
SDL_WINDOWEVENT_ENTER
SDL_WINDOWEVENT_EXPOSED
```
on minimise:
```
SDL_WINDOWEVENT_LEAVE
SDL_WINDOWEVENT_MINIMIZED
SDL_WINDOWEVENT_FOCUS_LOST
SDL_WINDOWEVENT_RESTORED
SDL_WINDOWEVENT_FOCUS_GAINED
SDL_WINDOWEVENT_EXPOSED
```
on alt-tab:
```
SDL_WINDOWEVENT_LEAVE
SDL_WINDOWEVENT_FOCUS_LOST
SDL_WINDOWEVENT_ENTER
SDL_WINDOWEVENT_FOCUS_GAINED
```
Handling …
=> Fix SDL2 window restore event not being forwarded to active state

osu.Framework/Allocation/AsyncDisposalQueue.cs, osu.Framework/Platform/GameHost.cs
The first commit is just a cleanup of the condition, which has been bothering me since I wrote the code in the first place. When debugging this I found it challenging to immediately compute the result of the binary operations.
The second commit ensures that the handler can't be hit a second time from another `Task` failing. This is always going to be a no-op because the input thread has died.
The third commit makes sure that the async disposal queue signals its completion if it itself dies. It would only block for a maximum of 10 seconds, but it should still quit ASAP otherwise e.g. the test runner could be left running.
I can replicate both above issues with the osu!-side `TestSceneSpectator` (crashes in disposal).
=> Fix some exceptions potentially leading to deadlocked process

osu.Framework/Platform/SDL2DesktopWindow.cs
Closes https://github.com/ppy/osu-framework/issues/4061
Reading from `CurrentDisplayMode` is awkward as it is only valid when in fullscreen (and only initialised below the usage here).
=> Fix borderless size being based on a potentially outdated value

osu.Framework/Platform/SDL2DesktopWindow.cs
This is really painful to need to do, but is required due to two other hacks/workarounds:
This addition for fullscreen, where we enter windowed mode briefly:
https://github.com/ppy/osu-framework/blob/6272037fdf3eb9d17afe40b3823e47f6340b9c1e/osu.Framework/Platform/SDL2DesktopWindow.cs#L963-L966
In conjunction with the SDL event filtering where we handle resize events (to stop blocking updates when resizing the window):
https://github.com/ppy/osu-framework/blob/6272037fdf3eb9d17afe40b3823e47f6340b9c1e/osu.Framework/Platform/SDL2DesktopWindow.cs#L420-L427
Closes https://github.com/ppy/osu-framework/issues/4060
=> Fix switching fullscreen resolutions potentially resulting in incorrect render resolution

osu.Framework/Platform/Windows/WindowsWindow.cs
Closes #4071
Attempted to test this on windows 7 but the hoops required to jump through to get net core working are too time consuming. No reason it shouldn't work unless there are further issues related to SDL2 itself (but we can wait for user reports for that).
=> Fix startup crash on older windows releases

osu.Framework/Graphics/Pooling/DrawablePool.cs, osu.Framework/Statistics/GlobalStatistics.cs
Open to suggestion on how to improve this visually. We could potentially add an identifier string to better describe multiple instances of the same pool (allow them to override or provide a string based on their specifics).
=> Remove disposed pool statistics from global statistics

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/DropdownHeader.cs
Follow-up on https://github.com/ppy/osu/pull/11101 and the issues with disabling dropdowns I found there.
In general, the existing support for disabled dropdowns was lacking. They were fully interactable, but trying to click on dropdown items just did nothing. This pull aims to achieve the following effects:
- Disabled dropdowns are no longer interactable. Clicking on them does not expand the dropdown, and hovering on them does not change their background colour.
- Disabled dropdowns now have a visual indication of their state, by being partially faded out. This is done by adding a `DisabledColour` to `DropdownHeader`.
- Disabled dropdowns no longer handle changing value via keyboard. They would previously attempt to do so, and promptly crash due to `Current` being disabled.
- If an …
=> Improve support for disabled dropdowns

osu.Framework/Platform/SDL2/SDL2Extensions.cs, osu.Framework/RuntimeInfo.cs
Closes #2728 (in the SDL case).
In order to properly support the behaviour of <kbd>NumLock</kbd> that is in line with user expectations, check the state of <kbd>NumLock</kbd> when unmapping SDL's scancodes and return the appropriate alternative keys for keypad numbers and the comma key when <kbd>NumLock</kbd> is off.
I can imagine this could be wrong on Apple platforms as they don't have the notion of a <kbd>NumLock</kbd> key, hence I'd be grateful if this could be checked. I don't really want to pepper in platform checks unless I absolutely have to.
Briefly considered not using `HasFlag` due to its memory concerns but I don't necessarily think it's the hottest path out there and there are way more worrying places that use `HasFlag` already performance-wise, so for now I opted for …
=> Support NumLock in SDL key mapping function

osu.Framework/Platform/SDL2DesktopWindow.cs
Previously, only normal (un-maximised) window state would use the window position to determine the global cursor position in relation to the game's position when being outside of the window, which results in incorrect mouse positions when in maximised window state (due to it *incorrectly* using the location of the entire monitor instead) as can be seen below.
Before:
After:
---
One side effect from this is that now the position and size of a maximized window would be saved to config as well, which may not be a good thing to have, although it still saves in some cases on master, and I think saving whether the window was last in maximised state or not and create the window based on it would be a better choice IMO (in a separate PR).
=> Fix mouse polling on maximised SDL window calculating incorrectly

osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
This employs the age-old hack that we've been relying on in stable/osuTK of misaligning the window with the screen. On a quick check, many other games use this same method, so it seems like the best we're going to do for the time being.
I've left the existing borderless operation mode for non-windows platforms, since it works better.
Closes https://github.com/ppy/osu-framework/issues/4068
Addresses part of https://github.com/ppy/osu-framework/issues/4074#issuecomment-739690107
Brings back issue mentioned in https://github.com/ppy/osu-framework/issues/3456 (i believe we may be able to solve this, but this is a separate task which requires further investigation into how other games/windowing systems get it working).
=> Fix borderless fullscreen unexpectedly running in exclusive mode on windows

osu.Framework/Platform/SDL2DesktopWindow.cs
Closes #4070
The issue is coming from the window implementation setting `WindowState` to `Normal` regardless of whether it is maximised or not, which causes the window to potentially have its position changed according to the config while being in maximised state.
This also adds `SDL_RestoreWindow(handle)` to normal state for correct window state updating, as, previously, switching from maximised/minimised state to normal state via `WindowState` property would do absolutely nothing.
=> Fix window getting moved out-of-place while in maximised state

osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs, osu.Framework/Screens/ScreenStack.cs
Previously, it was feasible for a push operation to fail, but the new screen to be already part of the stack, leaving *no* screen displayed to the user (rather than the screen before the push).
Found when investigating https://github.com/ppy/osu/issues/11135. Doesn't solve the issue, but should at least leave the game in a better state if such a scenario comes up again.
=> Fix ScreenStack getting into an invalid state if a push fails due to load state

osu.Framework/Platform/SDL2DesktopWindow.cs
Fixes maximised window's size silently getting saved internally to framework config.
This is occurring due to us updating window sizes on an `SDL_WINDOWEVENT_RESIZED`, as that event seems to be sent before SDL finishes processing the external change (putting the window in maximised mode, in this case), unlike `SDL_WINDOWEVENT_SIZE_CHANGED`. Here are the window events I got, and what the value of `WindowState` was for each:
as you can see `SDL_WINDOWEVENT_RESIZED` is sent while the window state is still at `Normal`, while `SDL_WINDOWEVENT_SIZE_CHANGED` is sent while the window state has changed to `Maximised`.
Also, `SDL_WINDOWEVENT_RESIZED` would always have an `SDL_WINDOWEVENT_SIZE_CHANGED` event sent afterwards, [as stated in the docs](https://wiki.libsdl.org/SDL_WindowEventID), so …
=> Fix maximised window position and size being saved to config

osu.Framework/Platform/DesktopGameHost.cs
Wanted to test out this MIDI controller I got recently, and found the input not working due to a missing input handler registration. Not sure how that happened.
=> Add back MIDI input handler for SDL2 window

osu.Framework/Platform/SDL2DesktopWindow.cs
Noticed while looking through #4093.
The whole window state management really needs refactoring anyway, but this is not intended to be that - this PR has just a few simple renames to keep the WTF factor down for now.
=> Rename a few members in SDL2DesktopWindow for readability

osu.Framework/Platform/SDL2DesktopWindow.cs
Regressed in https://github.com/ppy/osu-framework/pull/4085
The aforementioned PR (by me..) removed the case handling the `RESIZED` event thinking that it gets fired before the SDL has processed it, while it actually gets sent after the `SIZE_CHANGED` event, [as noted there](https://github.com/ppy/osu-framework/pull/4085#issuecomment-742707285).
Turns out that there was an event filter set to listen for it to handle continuous resize events (as `SDL_PollEvent` blocks those), and since the `SDL_WINDOWEVENT_RESIZED` case was removed, these events are no longer handled, causing the window to not update the client size while resizing:
This fixes it by updating the client size on those continuous resize events, **but** without saving the new size to config, as we don't know what state the …
=> Fix continuous resize events no longer handled

osu.Framework/Platform/SDL2DesktopWindow.cs
Closes #4088 
The reason is as mentioned here https://github.com/ppy/osu-framework/issues/4088#issuecomment-742722081.
Fixed by removing the scale on `sizeWindowed` bindable as it should not have it on. Also adds `updateWindowSize()` before `WindowMode.TriggerChange()` to get the correct display scale for setting up normal state properly.
=> Fix window size doubling up every startup on macOS retina displays

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Threading/Scheduler.cs
A bit of an oversight that we somehow hadn't encountered until now.
The conditional was far too early in the flow, meaning that `ExecutionTime` is completely ignored in the case that `RepeatInterval` is zero.
=> Fix zero-length repeat delegates ignoring initial delay

osu.Framework/Platform/Windows/WindowsWindow.cs
Reproduction requires at least 2 displays, one of which has to have a non-zero `Bounds.Location`.
On `master`, moving a framework window to that secondary display and entering borderless will then switch displays to the one with `Location` at `(0, 0)`.
=> Fix display changing on transition to borderless on Windows

osu.Framework/Testing/TestBrowser.cs
Without this, two test scenes with the same name but different namespace didn't behave as expected (the first instance would always be loaded on starting the test browser up).
=> Store full namespace for last accessed test in test browser

osu.Framework.Tests/Graphics/ColourTest.cs, osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs, osu.Framework/Graphics/Colour4.cs
As an example, previously, attempting to parse `#1ABF` would return the value coresponding to `#1A11`
Not sure if this test-worthy
=> Fix hex-parsing #RGBA colours returning #RGRR based colours

osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs, osu.Framework/Input/Bindings/InputKey.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/Bindings/KeyCombination.cs, osu.Framework/Testing/Input/ManualInputManager.cs
Closes https://github.com/ppy/osu/issues/11326.
First commit makes the game not-crash if the wheel is used in a binding, second adds actual support.
Tested with the `xdotool` as suggested in the issue thread and it seems to work fine, however - @bob8677 - it'd be nice if you were able to test this game-side with a framework checkout (steps how to do this are described [here](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects)).
=> Add support for horizontal mouse scroll wheels

osu.Framework.Tests/Bindables/BindableTest.cs, osu.Framework/Bindables/Bindable.cs
Fixes a case osu!-side in testing where invoking `ToMod()` on a non-deserialized (manually constructed) `APIMod` instance would attempt to parse a `Bindable`, and would result in an "Type must be IConvertible" exception because of falling to the `default` case in the parse method. Upon discussing, parsing `Bindable`s sounds OK to do.
=> Allow parsing same-type bindables

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework/Bindables/BindableList.cs
As noted in https://github.com/ppy/osu/pull/11320 and [on discord](https://discord.com/channels/188630481301012481/188630652340404224/792367615229427712). Also means no collection change events raised anymore in that scenario (as evidenced by the added tests).
Just a basic change, nothing fancy or too breaking. Considered not always eating the list copy but it's painful in general to write (`ICollection<T>` and `IReadOnlyCollection<T>` have no common supertype), and I figure this isn't going to get called that often anyway. Will change on request.
=> Preserve bindable list items if parsing equivalent list

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/JsonWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
- No longer throw AggregateExceptions where we really don't need to.
- No longer attempt to deserialise a potentially null json response.
Helps to solve https://github.com/ppy/osu/issues/11347. I guess touches on the issue reported in https://github.com/ppy/osu-framework/issues/4112 too.
=> Improve exception handling in WebRequest

osu.Framework/Bindables/BindableNumberWithCurrent.cs
Came across that one while looking at BindableNumberWithCurrent class source.
=> Remove duplicated license header

osu.Framework.Tests/Visual/Drawables/TestSceneStressGLDisposal.cs, osu.Framework/Graphics/OpenGL/GLDisposalQueue.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs
Resolves #4108.
To quote my comment there:
> Commit messages and inline comments should hopefully explain the main idea. From testing:
>
> * It passes the 100k drawable stress test given above.
> * I've benchmarked it on the test using dotTrace. Also tried adding a Benchmark.NET, but it's not trivial as it requires an actual game host and measuring that would probably be useless. It doesn't seem to be worse with the reworked concept, and it certainly seems to be better with the optimisation (times given are total times of the appropriate operations, measurement was once each time, over 2 minutes of running the stress test):
>
> | | current `master` | with `GLDisposalQueue` | with optimised `GLDisposalQueue` |
> | :- | -: | -: | -: |
> | scheduling disposals | 342ms | 311ms | 301ms |
> | …
=> Improve reliability and performance of GL disposals

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Transforms/Transformable.cs
Until now, thread safety has been enforced only on child mutation (in `CompositeDrawable`). This extends the same checks to `Transformable`, covering common operations which can lead to game crashes from cross-thread enumeration and other weirdness.
I implemented this out of necessity after crashing twice from cross-thread enumeration in the transform stack and wanting to find the bad actor. It helped locate this and several other cases, which I will be fixing as follow-up pull requests (~2 osu! side, one harder one framework side in `VisibilityContainer`, only affecting custom implementations).
This may mean that as a framework consumer you need to re-think how you are performing operations between drawables. The easiest way to avoid issue is to use `Schedule` to force the target code to …
=> Enforce thread safety on common transform operations

osu.Framework/Platform/ThreadRunner.cs, osu.Framework/Threading/GameThread.cs
Null checks were missing from `GameThread.Thread` access. It can actually become null on a different thread due to execution completing normally.
I repro'd this on osu!-side, but unfortunately didn't save the log. Should be pretty straight-forward though.
=> Fix potential crash on shutdown due to thread race condition

Directory.Build.props, LICENCE, osu.Framework/Graphics/Sprites/Sprite.cs
Late for the first release of 2021, but ¯\\\_(ツ)\_/¯
Also trims a stale obsolete member I found along the way.
=> Update references to current year

osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
May (resolve) #4141 
Same to what https://github.com/ppy/osu-framework/pull/4037 does, but this is in the case `MidiInputHandler` is disabled / [disposed of](https://github.com/ppy/osu-framework/blob/9901b9648ef316d62afaeb05cff5b129ea1922d5/osu.Framework/Input/Handlers/InputHandler.cs#L64).
Also, I don't have a MIDI device to test this, so I would appreciate someone testing this for me.
=> Close MIDI devices when disposing of / disabling MIDI input handler

osu.Framework/Extensions/ExtensionMethods.cs
As [stated in the docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.types?view=net-5.0#property-value), `ReflectionTypeLoadException.`could potentially include null types instances in the array, causing `TestBrowser` to eat a null reference exception as it uses it:
https://github.com/ppy/osu-framework/blob/99a640861a45a4e9f5c2e32c8dffb483c5ecf457/osu.Framework/Testing/TestBrowser.cs#L72 https://github.com/ppy/osu-framework/blob/99a640861a45a4e9f5c2e32c8dffb483c5ecf457/osu.Framework/Testing/TestBrowser.cs#L87
This fixes test browser no longer working for me due to the above.
---
Also not entirely sure how to handle that `ConditionIsAlwaysTrueOrFalse` resharper warning, the array is declared as `Type[]?`, which, if I understand correctly, means …
=> Fix `GetLoadableTypes()` extension potentially including null `Type` instances

osu.Framework.Tests/Input/KeybindingInputTest.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingInputQueueChange.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs, osu.Framework/Input/Bindings/IKeyBinding.cs, osu.Framework/Input/Bindings/KeyBinding.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/Bindings/KeyBindingExtensions.cs, osu.Framework/Input/FrameworkActionContainer.cs, osu.Framework/Input/PlatformActionContainer.cs, osu.Framework/Testing/TestBrowser.cs
This is a prerequisite for my realm `KeyBindingStore` implementation.
When working with realm, it is beneficial to have interfacing defining the underlying model types due to the restrictions on inheritance. I think in general having interfaces for model types like this is a good step forward, regardless.
Probably resulting in a breaking change for rulesets, but not sure that is avoidable (or an issue at this point in development).
=> Add IKeyBinding interface type for flexibility in key bindings

osu.Framework/Graphics/OpenGL/GLWrapper.cs
I think this is harmless to get in without testing if it fixes the crash. Some drivers may reset the internal GL bind states on a new frame, so `last_bound_buffers` should be reset on our side to prevent early returns.
Crash reported by @peppy:
```
Thread 37 Crashed:
0   libsystem_kernel.dylib            0x00007fff202ec462 __pthread_kill + 10
1   libsystem_pthread.dylib           0x00007fff2031a610 pthread_kill + 263
2   libsystem_c.dylib                 0x00007fff2026d720 abort + 120
3   libGPUSupportMercury.dylib        0x00007fff46bf60a8 gpusGenerateCrashLog.cold.1 + 95
4   libGPUSupportMercury.dylib        0x00007fff46bed20d gpusGenerateCrashLog + 89
5   com.apple.AMDRadeonX4000GLDriver    0x0000000113651622 gpusKillClientExt + 9
6   libGPUSupportMercury.dylib …
```
=> Attempt to fix macOS crash

osu.Framework/Graphics/Video/Video.cs
Depending on the timing of the decode loop, it is possible for there to still be frames arriving (or already arrived) from the end of the last playback when a loop is requested. We weren't accounting for this, meaning that some videos would fail the initial loop and only begin playing again after the seek lenience is exceeded.
Tested against and closes https://github.com/ppy/osu/issues/11490.
=> Fix video looping failing when frames are in available post-seek

osu.Framework.Tests/Input/KeyCombinationTest.cs, osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs, osu.Framework/Extensions/EnumExtensions/OrderedEnumExtensions.cs, osu.Framework/Input/Bindings/InputKey.cs, osu.Framework/Input/Bindings/KeyCombination.cs, osu.Framework/Utils/HasOrderedElementsAttribute.cs, osu.Framework/Utils/OrderAttribute.cs
Fixes #4153
- Introduce OrderAttribute from osu.Game
- To avoid adding an order to all `InputKeys`,  an `AllowPartialOrdering` flag was added on the `HasOrderedElements` to allow for only certain member to define a custom order as the current implementation of `GetValuesInOrder` would throw an exception. For now when a member does not define the OrderAttribute it will default back to the Enum value to keep ordering.
- Added simple tests to verify correct ordering of KeyCombination 
Unsure what to do with the current osu.Game `OrderAttribute`, removing it would introduce a dependency on this change ? Please let me know if I have to do anything else.
=> Fix key combination display ordering

osu.Framework.Tests/IO/TestLogging.cs, osu.Framework/Platform/GameHost.cs
We have generally agreed that these should be left unobserved, as it is quite common to fire a `Task.Run` without expecting it to cause the whole application to crash.
I've left logging in as that part will definitely be useful for tracking down edge cases where we actually do care about the exceptions.
Aims to fix issue observed in https://github.com/ppy/osu/issues/11608#issuecomment-767839973.
=> Stop handling unobserved exceptions

osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
Turns out there was a [game-side usage that used a naked open generic type](https://github.com/ppy/osu/blob/15e455231edd6556b67fe61d9fe0a337fec4051e/osu.Game/Overlays/BeatmapListing/BeatmapSearchFilterRow.cs#L81-L85) that wasn't scoped to `Enum`, and which as such could not be bound to the ordering static methods.
This sucks on multiple levels, is my fault for not checking, and is perhaps the worst timing imaginable, but the C# type system is only as strong.
I tried a few ways of circumventing game-side but they're just flat out dumb compared to this solution, due to how the aforementioned usage site is structured.
(I don't even know how to tag this pull. Not tagging as `code-quality` as code quality this does not improve.)
=> Drop type constraints on `EnumExtensions` methods

osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Bird.cs
Closes https://github.com/ppy/osu-framework/issues/4174.
As per https://github.com/ppy/osu-framework/issues/4174#issuecomment-770377429, have checked the other projet but no issues in there.
May be worth looking at a way to run CI on templates projects ensuring templates build just fine.
=> Fix framework templates not updated with API changes

osu.Framework.Android/AndroidGameActivity.cs
As said in https://github.com/ppy/osu/issues/11630#issuecomment-770571982, this makes it in line with iOS, but introduces the same issue of not being able to click stuff near the cutout area until the UI-side stuff is implemented. Can still use the scaling workaround in osu!-side, or just rotate device when viewing settings, etc. Won't cause any issues in gameplay.
Tested with Pixel 3a using the display cutout toggle in developer options (punch hole cutout):
Before:
After:
=> Make window render to the cutout areas of android devices

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Seems like an update to the Roslyn tooling made it so that syntax trees are identified by the compilation they're in. Makes sense.
This is a pretty small overhead.
=> Re-retrieve syntax trees on the correct compilation

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
This will come in handly when adding cancellation support to `OnlineStore`.
I overloaded `PerformAsync` instead of adding an optional parameter to not break o!f consumers.
=> Add cancellation support to WebRequest

osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/Development/ReflectionUtils.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/osu.Framework.csproj
At NUnit's end this method changed to a generic method, which doesn't suit our use case. So I just copied the code across for our own use.
Only did this because it causes weird errors when triggering dynamic compilation on a consumer project that has a newer version of NUnit referenced.
=> Update NUnit and pull in dependent (removed) code locally

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/Container.cs
Mainly to change it from explicitly reading "only one", when the children could actually be empty. Since that was just misleading.
=> Improve the exception message when Child is accessed with incorrect Children count

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs, osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
The logic in this container used the current position of items within the FillFlow it contains, but positions of items are not updated when they are not present. In scenarios where items are hidden (ie. for filtering) this would result in incorrect drag behaviour as it "found" the hidden items at their previous locations and exited the relocation loop.
Closes https://github.com/ppy/osu/issues/10509.
=> Fix RearrangeableListContainer considering hidden items when dragging selection

osu.Framework/IO/Network/WebRequest.cs
[Not yet supported](https://github.com/dotnet/runtime/issues/26177) by .NET itself, so we need to do this ourselves.The case where this can happen is where DNSv6 succeeds, but the actual connection cannot be established. Without this added logic, a fallback to IPv4 (dns and connection) does not occur.
See inline comments for further rationale.
Closes https://github.com/ppy/osu/issues/3507.
=> Add IPv4 fallback support on IPv6 failures

osu.Framework/Audio/Sample/SampleBassFactory.cs
Although the PR has been merged in, it still requires a new nupkg and for us to update to it, which is a non-trivial task considering their recent removal of dllmap.
=> Internalise per-sample playback concurrency for now

osu.Framework.Tests/Audio/SampleBassTest.cs, osu.Framework/Audio/Sample/Sample.cs
This used to be a thing before the recent sample changes, and it seems like the safer thing to do. Will regress https://github.com/ppy/osu/issues/5798, which was temporarily alleviated by this local regression (but this is intentional).
Closes #4198.
=> Fix samples allowing retrieval after they are disposed

osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/IO/Stores/OnlineStore.cs, osu.Framework/IO/Stores/ResourceStore.cs
PRing this for feedback. I believe the code could be further simplified by using `Task.Run` instead of `TaskCompletionSource`, but in an effort to not add more new unknowns I went with this to avoid TPL usage.
Closes ppy/osu#11141.
=> Fix TextureStore and ResourceStore locks being held globally across all lookups

osu.Framework/IO/Stores/RawCachingGlyphStore.cs
As seen in https://ci.appveyor.com/project/peppy/osu/builds/37847069/tests. Regressed in https://github.com/ppy/osu-framework/pull/4197 (due to increased concurrency of underlying lookups from `TextureStore`).
To test this, modifying `TestSceneSpriteText` to [load asynchronously](https://gist.github.com/peppy/7d48f0fdb6cb138306f7769969447d0c) can work quite well (will result in corruption of characters if not working correctly).
=> Fix RawCachingGlyphStore performing operations on same files from multiple threads

osu.Framework/IO/Stores/RawCachingGlyphStore.cs
As it turns out, the actual texture upload creation accesses cached stream handles, which can cause mayhem when accessed from multiple threads. Aiming to keep this as a simple fix for now; the inline comment still applies to the scenario where we want to improve performance.
Closes ppy/osu#11838.
=> Fix remaining portion of glyph store lookup happening outside of locked region

osu.Framework/Timing/IFrameBasedClock.cs
This is just a silly fix, I realized when I was looking at the interface summary.
=> Correct misspelled word in the interface summary

osu.Framework/Audio/AdjustableAudioComponent.cs, osu.Framework/Audio/AudioAdjustments.cs, osu.Framework/Audio/IAdjustableAudioComponent.cs, osu.Framework/Audio/IAdjustableResourceStore.cs, osu.Framework/Audio/Track/ITrack.cs, osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Exposes the Aggregate[Adjustment] bindables in ITrack.
Closes #4208
=> Make `IAdjustableAudioComponent` inherit `IAggregateAudioAdjustment`

osu.Framework/Audio/Sample/SampleBassFactory.cs
Internally, `ManagedBass` does a similar thing to our own `ObjectHandle`: https://github.com/ManagedBass/ManagedBass/blob/0cdc873a3b2eeb33bb338d254a76d20fc4f36c1b/src/Bass/Shared/GCPin.cs#L27-L38, with the difference that it only frees the handle when Bass provides `SyncFlags.Free`.
In the context of samples, this leaks the pinned handle, as bass will not invoke sync callbacks for `HSAMPLE`s. See [`Bass_ChannelSetSync`](http://www.un4seen.com/doc/#bass/BASS_ChannelSetSync.html) which is documented as accepting a handle of type `HMUSIC`, `HSTREAM` or `HRECORD`, and not `HSAMPLE`.
Don't really know how to benchmark this, but I've tested that the sync callback is not invoked, and have seen the reduction in pinned handles via dotMemory.
=> Fix leak of pinned sample handles

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework.Tests/Visual/Sprites/TestSceneRomanisableSpriteText.cs, osu.Framework/Localisation/RomanisableString.cs
I think it makes more sense to put the unicode (or as it is now named, original) string first, as it represents the "main" display version of the string. Or so you would think, but `ShowUnicode` is set to `false` by default sooo...
I believe this feels better anyway. Also added xmldoc.
=> Switch order of parameters on RomanisableString to make the original version come first

.editorconfig, CodeAnalysis/BannedSymbols.txt, osu.Framework.Benchmarks/BenchmarkEnum.cs, osu.Framework.Benchmarks/Program.cs, osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs, osu.Framework.Tests/Visual/Drawables/TestSceneIsMaskedAway.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs, osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs, osu.Framework/Graphics/Containers/AudioContainer.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/ContainerExtensions.cs, osu.Framework/Graphics/Containers/FillFlowContainer.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs, osu.Framework/Graphics/Containers/SafeAreaContainer.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Lines/Path.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Graphics/UserInterface/Menu.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Input/Handlers/Mouse/OsuTKMouseState.cs, osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/MacOS/OsuTKMacOSWindow.cs, osu.Framework/Platform/OsuTKWindow.cs, osu.Framework/Platform/SDL2/SDL2Extensions.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
On a RELEASE (this is important, will be explained later) startup of osu!, I noticed that a few enum values would thrash about in Gen0. This doesn't appear in dotMemory, but they're revealed via dotnet-sos:
```
> dumpheap -type Axes
Address               MT     Size
...
00007f938cd7f680 00007f93b9b12b88       24
Statistics:
MT    Count    TotalSize Class Name
00007f93b9b12b88     4222       101328 osu.Framework.Graphics.Axes
Total 4222 objects
> gcwhere 00007f938cd7f680
Address            Gen   Heap   segment            begin              allocated           size
00007F938CD7F680   0      0     00007F9383FFE000   00007F9383FFF000   00007F938CFD9FE8    0x18(24)
```
I originally noticed this issue with `CompositeDrawable.ChildLifeStateChange`, however I was originally testing with the DEBUG …
=> Add optimised HasFlagFast<T> extension to Enum

Directory.Build.props
This has been giving us build warnings for a while now. The FxCopAnalyzers package is [deprecated](https://docs.microsoft.com/en-gb/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019)
I've chosen to use the nuget package against their guidelines of using the SDK, since this is in a `Directory.Build.props` which affects iOS/Android projects too.
=> Update analyser package

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
This is done every frame. Drops allocations from 11MB/sec to 5MB/sec @ 4000UPS in main menu.
=> Don't use transforms in frame statistics

osu.Framework/Input/InputManager.cs
Screenshots should only be compared using relative % (run times were different):
Before:
After:
=> Fix enumerating HoveredDrawables causing excessive allocations

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
=> Remove remaining enumerator allocations from frame time display updates

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Text/TextBuilder.cs, osu.Framework/Text/TruncatingTextBuilder.cs
Before:
After:
Provides the `InvalidateTextBuilder()` method for any consumers that have a custom `TextBuilder` and provide properties to control it other than truncate/ellipsisstring/multiline.
=> Reuse TextBuilder when validating SpriteText

osu.Framework/Utils/NumberFormatter.cs
Before:
After:
By holding down ctrl to show text in the frame statistics.
=> Fix number formatter allocating many arrays

osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
Just something I noticed a few days ago. I'm not sure on the performance cost of this / have not profiled.
The disadvantage is we don't get accurate output to logs when F2 is opened, so merging of this PR is dependent upon whether that's fine.
=> Dispose .NET runtime listener when not in use

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs
This fixes the frame statistics display potentially doing huge allocations in the case a user is running at low draw FPS (uploads only happen every 16ms) but have threads running at full 1000hz (ie. input/audio), causing exhaustion of the source bucket in the default/shared `MemoryAllocator`.
The memory overhead of this (when the FrameStatisticsDisplay has been shown at least once) is around 52kb (400bytes * 132bucketsize):
Before:
After:
=> Allow specifying a custom MemoryAllocator in ArrayPoolTextureUploads

osu.Framework/Graphics/Video/VideoTextureUpload.cs
This is one rare case outside of `FrameStatisticsDisplay` that we are performing many texture uploads, where the finalizer of the uploads can, as we have seen, add considerable overhead.
I've confirmed that all loss-of-reference paths result in disposal of these instances (but failing that, one would hope that ffmpeg would clean up when the owning video is freed).
=> Remove finalizer from video texture uploads

osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs, osu.Framework/Graphics/Textures/TextureUpload.cs
I've checked every usage and this looks safe.
Partly addresses #4229.
=> Remove finalizers from TextureUpload classes

osu.Framework/Graphics/BufferedDrawNodeSharedData.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/DrawNode.cs, osu.Framework/Graphics/Drawable.cs
These are the bigger ones. Will address the remaining finalizers (on lesser used classes) in a separate PR.
I haven't done intensive testing on this yet, only checked at a code-level, so please consider when reviewing.
Partly addresses #4229.
=> Remove finalizer from Drawable and DrawNode

osu.Framework/Statistics/DotNetRuntimeListener.cs
Just so that it doesn't trigger osu!-side notifications.
=> Reduce finalizer allocation log level

osu.Framework.Tests/Audio/SampleBassTest.cs, osu.Framework/Audio/AudioComponent.cs, osu.Framework/Audio/Sample/SampleBassFactory.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs, osu.Framework/Audio/Track/TrackBass.cs
I tried to get this to work with `SafeHandle`, however I still need to figure out:
1. Best practices for passing safe handles downwards. Intuitively I'd think to pass with `ownsHandle = false` and have each level call `handle.Dispose()`, but this doesn't seem to be right.
2. Why it's causing a _huge_ stutter with every creation/disposal.
So for now I just did it locally in the cases it's required (all BASS classes). Additionally, I've also made `Dispose()` non-virtual to abide by the disposable reference implementation, which was overridden and implemented incorrectly in `SampleChannelBass` (it would occur on the executing thread rather than the audio thread).
One thing I don't like is the usage of `IsDisposed` - proper standards would have us declare a local `isDisposed` at every step of …
=> Remove finalizer from AudioComponent

osu.Framework/Statistics/DotNetRuntimeListener.cs
Turns out these can get updated quite often, at which point get `Get` overhead is noticeable. I haven't applied this to the remaining GC-related counters in the same class as they are seldom called in comparison.
=> Retain a local reference to arraypool global statistic counters to reduce overhead

osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs, osu.Framework/Graphics/Textures/ITextureUpload.cs, osu.Framework/Graphics/Textures/MemoryAllocatorTextureUpload.cs
While we optimised away the overflow of the array pool, it turns out that the `MemoryAllocator` structure offered by ImageSharp uses a `WeakReference` internally, which has a finalizer.
This renames the existing upload class to `MemoryAllocatorTextureUpload` and refactors the existing implementation to actually use `ArrayPool` directly. I've only replaced the usage in `FrameStatisticsDisplay` for now (unsure about the remaining padding ones; need to check what kind of usage patterns they follow before making any calls there I think).
=> Remove WeakReference overhead when FrameStatisticsDisplay is visible

osu.Framework/Audio/Sample/SampleChannelBass.cs
`Dispose()` only exists to stop the sample playback early upon disposal, however the lifetime of this object is completely managed by `SampleBass`. Channels don't need cleanup BASS-level cleanup.
=> Remove SampleChannelBass finalizer

osu.Framework/Graphics/Video/VideoDecoder.cs, osu.Framework/Host.cs, osu.Framework/Logging/Logger.cs, osu.Framework/Platform/SDL2/SDL2Extensions.cs, osu.Framework/RuntimeInfo.cs
Before:
```
2021-03-02 06:46:01 [verbose]: ----------------------------------------------------------
2021-03-02 06:46:01 [verbose]: runtime Log for dean (LogLevel: Debug)
2021-03-02 06:46:01 [verbose]: visual-tests 1.0.0.0
2021-03-02 06:46:01 [verbose]: Running on Unix 11.0.0, 32 cores
2021-03-02 06:46:01 [verbose]: ----------------------------------------------------------
```
After:
```
2021-03-03 06:03:45 [verbose]: ----------------------------------------------------------
2021-03-03 06:03:45 [verbose]: runtime Log for dean (LogLevel: Debug)
2021-03-03 06:03:45 [verbose]: Running visual-tests 1.0.0.0 on .NET 5.0.3
2021-03-03 06:03:45 [verbose]: Environment: macOS, (Unix 11.0.0), 32 cores
2021-03-03 06:03:45 [verbose]: ----------------------------------------------------------
```
=> Add RuntimeInfo's determined OS to log output

osu.Framework/Statistics/DotNetRuntimeListener.cs
As per suggestions in https://github.com/dotnet/runtime/issues/48937#issuecomment-789352441, I've added logging for `FinalizeObject` ETW events. It only provides the type id, so we have to jump some hoops to get the type name.
Although it doesn't catch `WeakReference<T>`, it does give a better indication as to exactly how many objects are being finalized. Sample log changing beatmaps in song select:
```
[performance] 2021-03-03 05:06:01 [verbose]: Allocated finalizable object: osu.Framework.Audio.Sample.SampleChannelBass
[runtime] 2021-03-03 05:06:03 [verbose]: updating selection with beatmap:2053 ruleset:0
[runtime] 2021-03-03 05:06:03 [verbose]: beatmap changed from "Sasaki Sayaka - Zzz (Sumisola) [Normal]" to "Sasaki Sayaka - Zzz (Sumisola) [Okamiroy's Hard]"
[runtime] 2021-03-03 …
```
=> Add another event for tracking finalizations

osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
No other framework-level texture implementations should require this immediately.
=> Move TextureGL's finalizer local to TextureGLSingle

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextMaxWidth.cs, osu.Framework/Graphics/Sprites/SpriteText.cs
Resolves https://github.com/ppy/osu-framework/issues/4248.
As it turns out this was covered by framework tests, but only visually. I've hacked up something not-overly-pretty that will fail a test if this breaks again.
Not entirely sure I did this 100% correctly. It seems to work at least, but `DrawSize` might not be enough? I'm always confused by those flags.
Also this will technically invalidate `DrawSize` twice when setting `Width`/`Height` (once via base, once via the manual `invalidate(true, true);` call), but I wasn't sure if I should trim it and explain with a comment, and it shouldn't have any performance impact anyways.
Figured I'd open this for the test, at the very least.
=> Fix text builder not invalidating on indirect relative size changes 

osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
Still just as fast. Now matches the implementation of `Enum.HasFlag`: https://github.com/dotnet/runtime/blob/9849163f7b24f94b3294732290929d182c2109e8/src/coreclr/vm/reflectioninvocation.cpp#L2551-L2592
=> Fix HasFlagFast not working for 0 values

osu.Framework/Graphics/Containers/ScrollContainer.cs
While debugging my game I noticed that [ScrollDistance](https://github.com/ppy/osu-framework/blob/74a3308d505ffd45b646b246ca598d07e7419473/osu.Framework/Graphics/Containers/ScrollContainer.cs#L78) has no effect. It turns out the value is hardcoded and the variable is not being used.
=> Usage of unused variable

osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/PlatformActionContainer.cs
I'm not sure I understand how this is happening, but this does fix the hard crash on osu! startup when running under iOS/Release (with debugger mode disabled). 
This is the only change required to make iOS work again. That said, I still think we want to get the `ConfigureAwait` changes in (#4261) because it's only a matter of time before we cause a deadlock like that.
This would explain why the await specific cases in `osu.Framework.Tests` where reproducible in the simulator while the osu! side crash was not.
A few things:
- The exception is silently eaten, causing the game to startup (and the draw thread to be waiting to draw). Not sure if this is an iOS specific issue, or if we are handling exceptions incorrectly across all platforms in some code path. We definitely need to investigate …
=> Fix crash on startup on iOS due to host being null?

CodeAnalysis/osu-framework.ruleset, osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework.Tests/Visual/Drawables/TestSceneConcurrentLoad.cs, osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs, osu.Framework.Tests/Visual/Sprites/TestVideo.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/Waveform.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/IO/Stores/DllResourceStore.cs, osu.Framework/IO/Stores/FontStore.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/IO/Stores/OnlineStore.cs, osu.Framework/IO/Stores/ResourceStore.cs, osu.Framework/IO/Stores/StorageBackedResourceStore.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/TcpIpcProvider.cs, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/EmptyTypeReferenceBuilder.cs, osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
This should have been quite obvious from the start (I have dealt with simlar issues in a distant past) but it didn't cross my mind that Xamarin.iOS' window initialisation could have been setting a `SynchronizationContext`.
This is the simplest recommended solution to resolve the issue. I'm not sure whether we want to further suppress the `SynchronizationContext` from being visible to our tasks - further issues (and unnecessary blocking overhead) may still exist. Fixing the deadlock scenarios is the first goal, though.
I've turned on the analyser to require this everywhere.
Closes https://github.com/ppy/osu-framework/issues/4214.
Huge thanks to @TheDomco for investigating this issue and pointing out the root cause. Further reading for people wishing to get more familiar with the cause and …
=> Update usages of await to always call ConfigureAwait(false)

osu.Framework.Benchmarks/BenchmarkLocalisableString.cs, osu.Framework.Tests/Localisation/LocalisableStringTest.cs, osu.Framework.Tests/Visual/Testing/TestSceneTest.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Localisation/LocalisableString.cs, osu.Framework/Localisation/LocalisableStringEqualityComparer.cs, osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs, osu.Framework/Localisation/RomanisableString.cs, osu.Framework/Localisation/TranslatableString.cs
Fixes https://github.com/ppy/osu/issues/11974
Preferring `.Equals()` implementations to `operator==` for internal comparison of LocalisableString data. Note that `operator==` forwards to `string.Equals(a, b, StringComparison.Ordinal)` internally (though it does this via a by-byte-span helper so it's not immediately obvious).
I've left in `operator==` and `operator!=` because removal would be a breaking change. I can obsolete them if people think that's the right path forward, but I'm not convinced on that.
In short:
```csharp
LocalisableString localisable = "a";
string str = "a";
// Ordinal comparisons
localisable.Equals(str);
str.Equals(localisable);
// Ordinal comparisons
localisable == str;
str == localisable;
// Culture-specific comparisons
localisable.ToString().Equals(str, …
```
=> Fix LocalisableString operator== failing for non-interned strings

osu.Framework/IO/Network/WebRequest.cs
Resolves some build warnings I just noticed today. Missed by CI because *grumbles about dual-targeting and conditional compilation*.
.NET 6 can't come soon enough...
=> Add missed `ConfigureAwait(false)` calls for netstandard

osu.Framework/Graphics/Drawable.cs
Can/will cause midi events to not be received by drawables implementing `OnMidiDown`/`OnMidiUp`. Something I found along the way of reviewing the OTD PR.
=> Fix midi events not making RequestsNonPositionalInput=true

osu.Framework/Graphics/Sprites/SpriteText.cs
This comes as the result of @smoogipoo discovering a deadlock osu!-side, which can be considered a regression of the localisation changes we made recently. The case is where a `Bindable` is assigned to `text.Current` during BDL (in a `LoadComponentAsync` context) while the `SpriteText` is also changing the value of `current` via the localised implementation. This could cause a deadlock in `GetEnumerator` as `Bindable`s are not intended to be thread safe for this kind of usage.
Example case:
thread 1:
thread 2:
...
=> Move SpriteText's bind logic to LoadComplete to alleviate potential threading issues

osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
Reproduced once while testing, you'll have to take my word on this one. The fail case was where there were two items in the array, first being `null`, second being the single device I actually have connected.
=> Fix potential null reference when iterating open midi devices

osu.Framework.Tests/Configuration/InputConfigManagerTest.cs, osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework/Configuration/ConfigManager.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Configuration/InputConfigManager.cs, osu.Framework/Configuration/TypedRepopulatingConverter.cs, osu.Framework/Platform/GameHost.cs
This paves a path forward to allow individual `InputHandlers` to specify their own settings. Intended to be consumed via reflection (portions of that may arrive at the framework in a future PR).
Using `json` as the storage format will allow, as an example, per-device configurations in `TabletHandler` without further implementation from our end.
=> Add new configuration store for InputHandlers

osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
It turns out with the introduction of relative mouse support in `MouseHandler`, we were toggling the state far more often than necessary. It was feasible that feedback loops when at the edge of the window could cause the state to flip-flop multiple times, causing what seems to be race conditions inside SDL or winapi. This is likely also the reason for https://github.com/libsdl-org/SDL/issues/4165 occurring (this change does greatly reduce the chance of this triggering, to the point I don't think users will ever encounter the issue).
FWIW, the underlying issue here is that the `SDL_WINDOWEVENT_ENTER` / `LEAVE` events stop arriving altogether.
@smoogipoo this resolves the issue you pointed out where the framework test cursor gets stuck at the edge of the window.
=> Fix CursorInWindow not updating as expected

osu.Framework/Platform/SDL2DesktopWindow.cs
Noticed it while I was trying the relative mouse mode, was causing mouse to jump far away from the window when exiting in retina screens:
=> Fix SDL2 mouse position warping not respecting DPI scaling

osu.Framework.Tests/Configuration/InputConfigManagerTest.cs, osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs, osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBox.cs, osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs, osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework.Tests/Visual/Sprites/TestSceneRomanisableSpriteText.cs, osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Configuration/ConfigManager.cs, osu.Framework/Testing/TestBrowser.cs
Previously this method was `public` for convenience, but as it implicitly set the `Default` value of bindables it touched, could cause unexpected behaviour.
- For initialising defaults, continue to use `Set` from `InitialiseDefaults`
- For changing configuration values externally, first retrieve the `Bindable` and then change its value, ie.
```csharp
// previously
config.Set(ConfigType.Name, true);
// now
config.GetBindable<bool>(ConfigType.Name).Value = true;
```
=> Make ConfigManager.Set protected to avoid accidentally setting default values

osu.Framework/IO/Serialization/Vector2Converter.cs, osu.Framework/Platform/GameHost.cs
To be used by `TabletHandler`. Taken from osu! and applied globally.
=> Add support for osuTK Vector2 json serialisation

osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs, osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs, osu.Framework/Input/Handlers/Tablet/TabletInfo.cs
This exposes the bare minimum required for osu!-side configuration. Intended to be an initial MVP. Depending on how quickly this is merged, I may also add rotation.
Note that the `TabletInfo` class is required to ferry information away from the .netcore OTD library and avoid conditional compilation nightmares. It may eventually disappear.
=> Expose required bindables via ITabletHandler interface for end-user configurability

osu.Framework.Tests/Configuration/InputConfigManagerTest.cs, osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs, osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBox.cs, osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs, osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework.Tests/Visual/Sprites/TestSceneRomanisableSpriteText.cs, osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Configuration/ConfigManager.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Configuration/FrameworkDebugConfig.cs, osu.Framework/Configuration/IniConfigManager.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestBrowserConfig.cs
1. Public `Set()` methods added back as obsolete.
2. Protected `Set()` methods renamed to `SetDefault()`.
3. Public `SetValue()` method added as a shortcut to `GetBindable<>().Value = value`.  This also sets the default if one hasn't already been set, as a conscious decision in order to not throw exceptions.
=> Add public `SetValue()` method to `ConfigManager`

osu.Framework/Platform/MacOS/MacOSWindow.cs
```
2021-03-19 07:30:45.649 dotnet[74568:4030645] -[NSTextField orig_scrollWheel:]: unrecognized selector sent to instance 0x7fdad08669b0
2021-03-19 07:30:45.651 dotnet[74568:4030645] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTextField orig_scrollWheel:]: unrecognized selector sent to instance 0x7fdad08669b0'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff204b46af __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff201ec3c9 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff20536c85 -[NSObject(NSObject) __retain_OA] + 0
3   CoreFoundation                      0x00007fff2041c07d ___forwarding___ + 1467
4   CoreFoundation                      0x00007fff2041ba38 …
```
=> Fix macOS hard crash when performing non-precise scroll on titlebar

osu.Framework/Input/Handlers/Midi/MidiHandler.cs
There is a general expectation that the enabled state of input handlers is only changed from the update thread. `MidiHandler` was an exception to this rule.
Closes ppy/osu#12102.
=> Avoid changing the enabled state of MidiHandler from the input thread

osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
In the old sensitivity setting flow (via the framework config), the precision was set via a `SetDefault()` call:
https://github.com/ppy/osu-framework/blob/add64ff760caaa9a44569994573ed2aabdda14f7/osu.Framework/Configuration/FrameworkConfigManager.cs#L44
but the mouse handler's bindable had no precision specified, therefore defaulting to `double.Epsilon`. This PR applies that same precision value of `0.01` to the mouse handler's sensitivity bindable.
This also incidentally closes https://github.com/ppy/osu/issues/12112, since game-side setting sliders automagically read the precision of the bindables they're bound to, and use it to format their tooltip text.
=> Specify precision for mouse handler sensitivity bindable

osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
In my profiling, I was lucky to spot `AddMemoryPressure` causing gen2 GC collections exceeding 16ms. This comes from our usages of `NativeMemoryTracker`.
For VBOs specifically, native memory lifetime is very tightly controlled by us such that any VBO unused for 300 frames is deleted: 
https://github.com/ppy/osu-framework/blob/322245a44f6c65cb107ca993319c0b0b9a4e9fda/osu.Framework/Graphics/OpenGL/GLWrapper.cs#L371-L383
In this case, we're basically telling the GC that a 24KB object is allocated quite frequently, but there's rarely an useful work it can do by running more frequently due to our tight control over native memory. In most cases it ends up promoting "200MB" of VBOs to gen2 that then results in the blocking collection.
Similar reasoning could be applied to all other GL objects - …
=> Remove artificial memory pressure from VBOs

osu.Framework/Platform/SDL2DesktopWindow.cs
As it turns out, only one of a few of the paths where the window size is updated actually fired this underlying event. Luckily it wasn't used in many places (until now).
Closes https://github.com/ppy/osu-framework/issues/4294.
=> Fix OnResized events not always being fired on SDL window size changes

osu.Framework/Audio/Sample/SampleChannel.cs
This felt like a very anti-user method of handling this. At the point the channel is disposed, it's guaranteed to be stopped, meaning subsequent `Stop` calls are noop anyway.
=> Don't throw when attempting to `Stop` a `SampleChannel` post-disposal

osu.Framework/Graphics/Pooling/DrawablePool.cs
After the removal of finalizers from `Drawables` in #4242, disposals must be invoked manually.
`Drawables` within the draw hierarchy do get properly disposed since the disposal of a parent drawable would also trigger a disposal on their children. 
https://github.com/peppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L299
However, in `DrawablePool`, a stack is used to store `PoolableDrawable`s, which means that they aren't within the drawable hierarchy, so the pool's contents aren't disposed properly. 
This PR adds a change that ensures that the pool's contents are disposed properly.
<sub>This is something I've noticed when pooling drawables within another pooled drawable in my ruleset, and the failure to properly dispose drawables within the pool led to …
=> Ensure disposal of drawables within DrawablePool

osu.Framework/IO/AsyncBufferStream.cs
This is `internal` and the only usages are in `TrackBass`, which has its own finaliser. This one is unnecessary. Note that finalizer suppression is already handled along with the rest of the disposal flow in `Stream`.
Closes #4229.
=> Remove finaliser from AsyncBufferStream

osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
This is a second attempt at https://github.com/ppy/osu-framework/pull/4212, minus the breakage.
The only part of this I'm not 100% sure about is the logic added to ensure no self-references. An alternative to this is to fix each occurrence that uses interface delegation (see https://github.com/ppy/osu/compare/master...peppy:audio-interafce-delegation-fixes?expand=1). In theory this looks like a better approach, until you realise that to make it works, `PoolableSkinnableSample` needs to have similar code to this framework-side change in order to get the parent adjustments (since it is pretending to be a wrapper without actually being one).
Tested to work well osu! side. Not sure if it's worth adding test coverage for this.
=> Avoid using DI for audio component adjustment lookup to better support pooling

osu.Framework/Platform/SDL2DesktopWindow.cs
Have tested on windows and macOS. Seems to work as expected.
Also tested on windows with the osu! side caps lock warning and that works once again.
As such, closes https://github.com/ppy/osu/issues/12165.
=> Allow caps lock events to fire via KeyDown / KeyUp

osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
Idea taken from https://github.com/ppy/osu/issues/11731#issuecomment-806177375. I've left the windows specific implementation in place because it doesn't seem to be causing any harm. Could be removed on request I guess.
Tested on macOS; should probably be checked on linux as well.
Closes https://github.com/ppy/osu/issues/11731.
=> Add caps lock state querying support for the general desktop platform case

osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework/Input/Handlers/Mouse/MouseHandler.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
It turns out this was quite simple to implement due to `MouseHandler` already preferring relative mode given circumstances of the game. The result now is that even if the `MouseHandler` is set to prefer relative mode, it will automatically be disabled when the OS cursor is visible. I think this makes sense.
Closes https://github.com/ppy/osu-framework/issues/4309.
=> Ensure relative mouse mode is never set when the cursor has not been hidden

osu.Framework.Android/Input/AndroidKeyboardHandler.cs, osu.Framework.Android/Input/AndroidTouchHandler.cs, osu.Framework.iOS/Input/IOSKeyboardHandler.cs, osu.Framework.iOS/Input/IOSMouseHandler.cs, osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs, osu.Framework.iOS/Input/IOSTouchHandler.cs, osu.Framework/Input/CustomInputManager.cs, osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/Handlers/Joystick/JoystickHandler.cs, osu.Framework/Input/Handlers/Keyboard/KeyboardHandler.cs, osu.Framework/Input/Handlers/Midi/MidiHandler.cs, osu.Framework/Input/Handlers/Mouse/MouseHandler.cs, osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/Windows/WindowsMouseHandler.cs, osu.Framework/Testing/Input/ManualInputManager.cs
With the introduction of tablet support, there have been a number of users reporting their mouse jumping or "rubber banding" between two locations. The cause of this is having tablet drivers or software running external to a game, reporting back as mouse cursor updates, in addition to our local handling of tablets via OTD.
Until now, the general advice for such cases is to "close the other drivers/software", but this is a pretty bad user experience. For instance, an illustration may use the wacom software for their graphical work while also using the tablet to play games.
This PR aims to ignore externally occuring mouse events while a tablet is reporting via OTD. It may also be used in the futrue for other input handler where similar patterns can occur. This is done via a simple debounce …
=> Avoid feedback from input devices reporting via multiple handlers

osu.Framework/Input/Handlers/INeedsMousePositionFeedback.cs, osu.Framework/Input/Handlers/Mouse/MouseHandler.cs, osu.Framework/Input/InputManager.cs
Tested on windows and macOS to not break anything.
Closes #4317.
=> Transfer cursor position updates from non-mouse input handlers back to OS cursor

osu.Framework.Tests/Visual/Drawables/TestSceneCircularArcBoundingBox.cs, osu.Framework/Utils/PathApproximator.cs
We only need the end-points and each side of the arc to compute the bounding box. This method should be less intensive and marginally more accurate compared to approximating the entire circular arc and then computing the bounding box from resulting points.
Math logic used is the same, hence `circularArcHelper`. Because the interesting output from that helper method is not just one value, it passes them on to a given function instead. An alternative to this would be using the `out` keyword, or a custom struct, not sure which is preferred.
---
Main use case is https://github.com/ppy/osu/pull/12122. Here the bounding box is used as a limit for how large a PerfectCurve path is allowed to be before defaulting to Bezier. Said bounding box is computed every time the control points update, for …
=> Add bounding box method for circular arcs

osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
As seen in https://github.com/ppy/osu-framework/issues/4324
Shows up as something like:
```
Unhandled exception. System.InvalidOperationException: Failed to create an SDL2 GL context (Invalid window)
at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.CreateContext() in /home/smgi/Repos/osu-framework/osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs:line 28
at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window) in /home/smgi/Repos/osu-framework/osu.Framework/Platform/PassthroughGraphicsBackend.cs:line 40
at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window) in /home/smgi/Repos/osu-framework/osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs:line 45
at osu.Framework.Platform.SDL2DesktopWindow.Create() in …
```
=> Improve messaging from SDL2 GL context failures

osu.Framework/Platform/MacOS/MacOSWindow.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
Just looking to make tracking flow a touch easier when working with this class. These were left over from a forgotten time.
=> Remove unnecessary redirection methods when triggering SDL window events

osu.Framework/Input/Handlers/Midi/MidiHandler.cs
- Should close ppy/osu#12198
Note On/Off messages include channel data on it's status byte's low nibble, which caused messages sent over channels other than 1 (hex 0) to be discarded.
As we only handle Note On/Off messages it should be safe to ignore this nibble.
Tested using a Novation Launchpad Mk2 set to channels 6-8 and 14-16.
=> Listen to midi messages on all channels

osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Tests/Visual/Platform/TestSceneAllowSuspension.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Platform/GameHost.cs
In osu!, we're using a component which controls the value of this bindable: https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/ScreenSuspensionHandler.cs
This is quite fragile due to the assert, and I would like this to not be a thing as I'm showing more players concurrently.
Can now be controlled by multiple sources via `AllowScreenSuspension.AddSource()` and `AllowScreenSuspension.RemoveSource()`.
=> Make GameHost.AllowScreenSuspension into an AggregateBindable

osu.Framework/Input/Handlers/Mouse/MouseHandler.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
The default value for `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS` has changed in SDL 2.0.14
The change was made in https://github.com/libsdl-org/SDL/commit/1947ca7028ab165cc3e6cbdb0b4b7c4db68d1710
Setting it to `true` restores the expected behavior, which we had before the bump of SDL libraries.
This PR also reverts the change made in #4344 as it's not needed, and that change created more problems.
Closes #4346 because of the revert.
=> Set the SDL hint to minimize on focus loss in fullscreen

osu.Framework/Input/InputManager.cs, osu.Framework/Input/PassThroughInputManager.cs, osu.Framework/Input/UserInputManager.cs
Closes https://github.com/ppy/osu-framework/issues/4347 via proposed solution in that issue thread.
I tested this manually using `TestScenePassThroughInputManger` via the hover event count. Not sure it's worth adding automated test coverage of this, but can be done if required.
=> Fix PassThroughInputManager ignoring parent HandleHoverEvents state

osu.Framework.Tests/Input/KeyCombinationModifierTest.cs, osu.Framework.Tests/Input/KeyCombinationTest.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs, osu.Framework/Input/Bindings/InputKey.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/Bindings/KeyCombination.cs
Don't really have much to say about this one. Pretty hellish to get the implementation right, and likely not going to be a simple one to review/understand, but it works.
May need to assess whether the array allocation overhead is an issue (although I think the scenarios where it is called are already limited to when input changes, so should be okay).
Closes https://github.com/ppy/osu-framework/issues/2136.
=> Add left/right modifier support to KeyBindingContainer

osu.Framework/Platform/SDL2DesktopWindow.cs
The local change is required as there is a possibility that the window does not start focused, and it's easier to change this bindable to rely on SDL reporting to us that the focus has been gained (seems to be quite reliable on macOS and windows).
Note that this does introduce a short period during startup where the game may not be considered active (seems to be about one frame). I'm not sure if this will become an issue, but I can't notice any behavioural changes in testing against osu!. The only way I noticed is by starting up the framework `VisualTests` project with the `TestSceneIsActive` as the active test.
=> Fix window potentialy having an incorrect focused state on windows

osu.Framework.Tests/Input/KeyCombinationTest.cs, osu.Framework/Input/Bindings/KeyCombination.cs
Was causing key combinations like `(Shift, LShift, Control, LControl, R)` to display as `Ctrl-LCtrl-Shift-LShift-R`, instead of `LCtrl-LShift-R`, as can be seen in osu!'s key binding configuration:
Now written to hide the main modifier if the direction-specific one exists in the combination, otherwise show it.
=> Fix readable key combination string including main modifier along direction-specific

osu.Framework/osu.Framework.csproj
[Full changelog](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3)
- Fixed Wacom touch reports being handled as auxiliary buttons (now reports touch data through `ITouchReport`)
> Touch implementation is subject to change once we find more touch capable tablets and parse their data structures. 
- Added 26 new tablet configurations (Wacom, Huion, XP-Pen)
- Fixed and/or renamed 33 existing tablet configurations (Gaomon, Huion, Wacom, XP-Pen)
- Improved common exception messages to be more descriptive and link to OpenTabletDriver FAQ
- Workaround bad/partial reports resulting in device detection failing
=> Update OpenTabletDriver package to 0.5.3

osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs, osu.Framework/Graphics/Containers/OverlayContainer.cs
As proposed in https://github.com/ppy/osu/pull/12375#issuecomment-817562409.
Will add test coverage if this is seen as an amicable direction.
=> Allow OverlayContainers to optionally not block scroll

osu.Framework.Tests/Audio/AudioComponentTest.cs, osu.Framework.Tests/Audio/SampleBassTest.cs, osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Threading/AudioThread.cs
Closes #3700, closes #3387
On Linux, freeing the 0 (no-sound) device can sometimes cause a deadlock internal to BASS. I previously tried to repro this in native code, but it seems to happen after quite a few `Init() -> Free()` cycles which I didn't realise was the case before.
I've reworked the whole init/freeing flow a bit here:
1. Init does not `Free()` if BASS gives an `Already` error. Instead, it just sets the current device.
2. When freeing, the target device is selected via `Bass.CurrentDevice`. This is required as per [BASS docs](http://www.un4seen.com/doc/#bass/BASS_Free.html), which was not done previously.
3. On disposal, `AudioManager` joins the sync thread, to prevent any `setDevice()` from potentially happening post-dispose/post-AudioThread-exit.
4. On Linux, the no-sound …
=> Fix audio device freeing on Linux

osu.Framework/osu.Framework.csproj
- Fixed report parser dictionary lookup not including `Wacom64bAuxReportParser` (https://github.com/OpenTabletDriver/OpenTabletDriver/pull/985)
Required for touch data parsing,  pretty big oversight in the v0.5.3 package release
=> Update OpenTabletDriver package to v0.5.3.1

osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs, osu.Framework/Timing/FramedClock.cs, osu.Framework/Timing/FramedOffsetClock.cs, osu.Framework/Timing/InterpolatingFramedClock.cs, osu.Framework/Timing/ThrottledFrameClock.cs
When the source clock is not an `IAdjustableClock`, setting `DecoupleableInterpolatingFramedClock.Rate` would nullref.
=> Fix possible nullref when setting DecoupleableInterpolatingFramedClock.Rate

osu.Framework.Tests/Visual/Containers/TestSceneCursorContainer.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs
This logic would result in a displayed cursor drifting from the true cursor position if the `Container` (or any parent hierarchy) is transformed in any way.
Expected behaviour is that no matter how the draw hierarchy is transformed, the cursor is always displayed at the tracking location (based on the parent `InputManager`'s `Mouse` position.
I'm not actually sure if we need to make any further changes osu! side, as the issue referenced by the original pull request does not seem to return, even with this change reverted. Regardless, I'd like to get this into a framework build if it's seen as a more correct direction, then deal with any regressions osu! side if/when they are found.
=> Revert weird CursorContainer logic that causes incorrect cursor positioning

osu.Framework.Tests/Bindables/BindableTest.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/IBindable.cs, osu.Framework/Bindables/IBindableList.cs, osu.Framework/Configuration/IniConfigManager.cs
Without this, the following appears as a totally valid operation at compile time, but will completely fall over at run time:
```csharp
Bindable<string> bindable = new Bindable<string>();
MyClass c = new MyClass();
c.MyBindable.BindTo(bindable);
public class MyClass
{
public readonly IBindable<int> MyBindable = new Bindable<int>();
}
```
Note that this is still possible if `MyBindable` is exposed as an `IBindable` instead.
I've also removed `IParseable` from `IBindable` as that allowed directly changing the value of the `IBindable*`, which is something that should only be allowed on `Bindable<T>`/`BindableList<T>`.
`IParseable` is only implemented on the `Bindable<>` and `BindableList<>` classes. Code that relied on this functionality should instead cast to `IParseable`.
=> Remove IBindable interface inheritance

osu.Framework.Tests/Bindables/BindableEnumTest.cs, osu.Framework/Bindables/Bindable.cs
Closes ppy/osu#12454
On `master`, only strings are allowed to be parsed to enum bindables, all other object types would fall under `Convert.ChangeType(...)` causing `InvalidCastException`s, which means JSON-deserialized enum values cannot be easily parsed to bindables. 
In the linked thread, the issue was occurring due to attempting parsing enum values (integer types) from the database to their own enum bindables, and the same can happen for web responses.
Therefore I've changed the parser to allow any value to be parsed to an enum bindable, as long as `Enum.Parse(underlyingType, ...)` allows it, as I feel it's more logical to allow as such. Also added test cases showing what can and what can't be parsed in https://github.com/ppy/osu-framework/commit/b5bcdfa9269062bc7a595449557964ea9f69f0a …
=> Allow parsing any enum-parsable value to enum bindables

osu.Framework.Tests/Visual/Drawables/TestSceneTransformSequence.cs, osu.Framework/Graphics/Drawable.cs
To make them look more user-friendly when used in dropdowns, like the existing rotation direction setting for barrel roll mod osu!-side.
I wasn't sure about lumping the framework with that at first, but since it's already done in other places and is just about adding description attributes, I think it's fine. 
---
As it appears to be often one word, the enum member `CounterClockwise` has been renamed to `Counterclockwise`.
=> Add descriptions to rotation directions

osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework/Audio/Track/TrackBass.cs
Resolves https://github.com/ppy/osu-framework/issues/4375 by setting the bitrate while preparing the stream.
Also adds a test which fails prior to this PR.
=> Move bitrate assignment to before reversing stream

osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs, osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
Should resolve https://github.com/ppy/osu-framework/issues/4323, and resolve https://github.com/ppy/osu/issues/12156.
Not much to say, `WindowsMouseHandler` uses `Window.Position` when calculating the mouse position for absolute input devices, and since `Window.Position` may not be updated sometimes (, the handler miscalculates the cursor position and causes it to be locked in a certain area or potentially completely freeze and not able to move.
Here's a video of reproducing the bug above:
https://user-images.githubusercontent.com/22781491/115179660-7f10f880-a0dc-11eb-9bfb-e50b859f5c11.mp4
There were two I cases I've found where the position property doesn't get updated, and are the only ones apparently:
1. when switching to other window modes …
=> Fix SDL2 window `Position` property not updated sometimes

osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
Resolves https://github.com/ppy/osu-framework/issues/4378.
Tested on windows with wacom tablet.
=> Only forward feedback cursor updates when the framework window is active

osu.Framework/Audio/Track/TrackBass.cs
Currently casts bitrates to `int`, which easily produces errors of ~1 kbps in cases like these:
Probably best to round before casting to fix that. I don't think storing them as doubles (like I did here to debug) is necessary.
Bitrate in the test doesn't have this problem, so we'd need a separate sample to test this. Not sure where to find one we could use.
=> Improve bitrate precision

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
1. Adding a HashSet to prevent calling `GetSymbolInfo()` on the same syntax node seen in multiple locations.
* This is currently only per-file to not run into failed recompilations. Additional perf improvements are possible by using the hashset globally, but the implementation becomes complex so I've added a todo for now.
2. Caching various `.ToString()` invocations.
3. Ignoring variable declarators - the name of a variable.
4. Ignoring variable name of assignment expressions, which is particularly important with our use of object initialisers.
Tested osu!-side by changing `EffectRowAttribute` in `TestSceneTimingScreen`:
Before:
After:
~50% speedup
=> Speed up dynamic compilation type resolution

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Fixes a regression caused by https://github.com/ppy/osu-framework/pull/4382 because I was assuming the syntax name matched the type name.
In `TestSceneEditorChangeStates`, the base class has a member named `Editor` which is referenced in code. This `Editor` syntax has the symbol name (i.e. type) `TestEditor`. The previous code would add `Editor` to the cull list.  
Later down the file, `Editor` is found as a type, but it will be culled and not explored due to the above.
This slows down perf a touch (9.4 sec -> 10.3 sec when recompiling `TestSceneTimingScreen`), but I have changes that speed things up another 50% over current.
=> Fix dynamic compilation culling types without resolving type name

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
The biggest gain here is ignoring invocation expressions. Since we're already skipping past static classes, the only invocation expressions we potentially care about are those on local members, however those members must be fully defined in a variable somewhere, at which point this is only doing redundant computation.
The removal of other switch cases are due to them eventually resolving to `IdentifierName` syntaxes, and processing them multiple times is redundant. This can be confirmed with [Roslyn Quoter](https://roslynquoter.azurewebsites.net/):
```
a as B;
a is B;
sizeof(B);
typeof(B);
(B)a;
new B();
CompilationUnit()
.WithMembers(
List<MemberDeclarationSyntax>(
new MemberDeclarationSyntax[]{
GlobalStatement(
ExpressionStatement(
BinaryExpression(
SyntaxKind.AsExpression, …
```
=> Further speed up dynamic compilation type resolution

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Ignoring the complete invocation expression is incorrect, for cases such as `Method(new X())` - `X` needs to be discovered.
This relates to one of the cases in https://github.com/ppy/osu-framework/issues/4387 - `ChannelManager` constructs `InfoMessage`s in exactly this fashion, without referencing them anywhere else.
I've also added some logging output to show the points of exclusion, as these were previously hidden and thus failed to indicate whether something was excluded or just never explored.
Unfortunately, this does slow down recompilation time :( (1.5sec -> 5sec via profiler)
=> Fix invocation expression arguments not being explored

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
This seems to work fine, but I'm not sure if there's a possibility of assembly conflicts or something like that as a result of adding too many assemblies.
As it turns out - it seems like assemblies are lazy-loaded upon first reference. In some cases, we're exploring classes that reference the Humanizer assembly, but that class has actually never been used before and so the Humanizer assembly isn't loaded, and thus not present in `AppDomain.CurrentDomain.GetAssemblies()`.
So this change takes all assemblies from the compilation and adds them in too. The current domain assemblies are still required for .NET internal types - there's probably a way around this but I'm not sure yet, various sources say to add some other package and add .csproj attributes, etc... Pretty gross stuff.
=> Resolve more assemblies for dynamic compilation

osu.Framework/Input/Bindings/KeyCombination.cs
Closes https://github.com/ppy/osu/issues/12430.
=> Add "numpad" prefix to `KeyCombination`'s readable output to discern from normal keys

osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework.Tests/Audio/TrackVirtualTest.cs, osu.Framework/Audio/Track/TrackBass.cs
Fixes https://github.com/ppy/osu/issues/12541
When seeks are performed in-line, there's a bit of an expectation that the resultant time is updated immediately rather than in the next frame.
This is also an issue with Play() and Stop(), but I'll be making an issue for those to be tackled later - they're a bit involved. (https://github.com/ppy/osu-framework/issues/4396)
=> Fix TrackBass not updating current time after seek

osu.Framework/Audio/Track/TrackBass.cs
The recent changes to `TrackBass` (#4395) added an instantaneous current time value update on a seek. As it turns out, it is not necessarily safe to unconditionally run that update, as BASS callbacks (such as the mixtime callback) could run from a separate unmanaged thread rather than the audio thread, tripping the `CanPerformInline` assertion check if a track had `Looping` and `RestartPoint` set.
This can be reproduced game-side with a framework checkout by seeking to the end of a track in song select and waiting for it to complete.
To fix, add an explicit check for whether the current time update can be safely performed via `seekInternal()` before trying to attempt it.
---
I wanted to write a test case for this, but as it turns out `TrackBassTest` magically sidesteps this issue, because …
=> Fix assertion tripping when seeking from within the mixtime callback

osu.Framework/Input/MouseButtonEventManager.cs
Matches behaviour as hover lose and focus lose, where the property would have its state changed before triggering the event.
Have checked for any usages of this property, none of them needs any action.
Both `Drawable.IsDragged` and `InputManager.DraggedDrawable` now change their state before the `DragEndEvent` is triggered, rather than after, matching other similar events like `FocusLostEvent` and `HoverLostEvent`.
=> Change dragging states before triggering end event

osu.Framework/Development/ThreadSafety.cs
Would come in useful with components like https://github.com/ppy/osu/pull/11461, which have components that must be run on a specific game thread.
`ExecutionMode` is not exposed as:
1. It's `GameHost`-specific. It should probably be moved out of `ThreadSafety` or be made thread-static.
2. There isn't much reason for the execution mode to be known.
`EnsureInputThread()` + `EnsureAudioThread()` added for conformity.
=> Expose ThreadSafety

osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TemplateGameTestScene.cs, osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneMainScreen.cs, osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneSpinningBox.cs, osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneTemplateGameGame.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/FlappyDonTestScene.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestSceneBackdrop.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestSceneFlappyDonGame.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestSceneObstacles.cs, osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestScenePipeObstacle.cs
Must be implemented for providing the correct dependencies for the test scene to run properly, 
I also have another PR almost ready for making `TestScene.CreateTestSceneTestRunner()` abstract as it's very recommended to be implemented per game tests project, rather than using the default `TestSceneTestRunner`.
=> Add headless test runner for templates tests projects

osu.Framework/Graphics/Performance/LifetimeEntry.cs, osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
`RequestLifetimeUpdate` logic is changed so `SetLifetime` can be safely called from non-internal user and overridden.
For motivation, see osu-side PR: ppy/osu#12592.
Note that I'm not just making `LifetimeStart` and `LifetimeEnd` virtual. This is because those properties are critical to the correctness of the `LifetimeManager`.
=> Simplify LifetimeEntry logic, and make SetLifetime overridable

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Turns out that ignoring variable declarators completely is wrong. Consider the following snippet from `HitErrorDisplay`:
```
var display = new BarHitErrorMeter(hitWindows, rightAligned)
{
...
};
CompilationUnit()
.WithMembers(
SingletonList<MemberDeclarationSyntax>(
GlobalStatement(
LocalDeclarationStatement(
VariableDeclaration(
IdentifierName(
Identifier(
TriviaList(),
SyntaxKind.VarKeyword,
"var",
"var",
TriviaList())))
.WithVariables(
SingletonSeparatedList<VariableDeclaratorSyntax>(
VariableDeclarator(
Identifier("display"))
.WithInitializer(
EqualsValueClause(
ObjectCreationExpression(
IdentifierName("BarHitErrorMeter"))
.WithArgumentList(
ArgumentList(
SeparatedList<ArgumentSyntax>(
new SyntaxNodeOrToken[]{
Argument(
IdentifierName("hitWindows")),
Token(SyntaxKind.CommaToken), …
```
=> Fix variable declarations not explored by DCC

osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Consider, in isolation, the following class: https://github.com/ppy/osu/blob/da624deb3223cfb2f041d54a0bebada0696d9209/osu.Game/Skinning/Editor/SkinSelectionHandler.cs
The class `SkinnableHUDComponent` is only ever referenced via type parameters.
=> Fix type arguments not explored by DCC

.config/dotnet-tools.json, .editorconfig, .github/workflows/ci-nativelibs.yml, .github/workflows/ci.yml, osu.Framework.Tests/osu.Framework.Tests.csproj
Similar vein to GH-4407, but in a feature-complete state. Resolves GH-4288.
- We're now using a standardized reporting with NUnit using the NUnit Logger with the NUnit Reporter Action. 
- CFS, MSBuild, Vika and Roslyn warnings will show up as warning and error annotations natively with no additional change needed.
- Secrets will be managed natively in GitHub, and can be called using a reference, making it much safer to use secrets.
- Currently there is no distinction between artifacts, you have to download the entire archive containing the nuget packages regardless if you have made a change in this specific package.
- Legacy scripts and AppVeyor definitions have not been cleaned out of this PR to allow AppVeyor checks to still pass. This can be tackled on a future PR once transition has …
=> Migrate osu!framework to GitHub Actions

.github/workflows/ci.yml, .github/workflows/report-nunit.yml, osu.Framework.Tests/osu.Framework.Tests.csproj
Fixes Test coverage not reporting as it should due to GitHub Limitations. This also uses the TRX format instead of requiring a seperate logger for coverage reporting.
**REQUIRES `report-nunit` WORKFLOW TO BE PRESENT IN THE BASE REPO TO ACTUALLY WORK!**
=> Fix Test Coverage Reporting

osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/ThreadRunner.cs
Addresses one of the failures from #4430. At least two others remain.
The culture-switching code would not work if the game was started single-threaded without ever switching to multi-threaded. The cause of this was two-fold:
* First off, when the game is started in single-threaded mode, the four `GameThread`s are never actually created via `ThreadRunner`. Therefore, the `GameThread.CurrentCulture` sets did nothing but set the culture value on the `GameThread`s. They did not actually change any actual real OS thread's culture.
https://github.com/ppy/osu-framework/blob/0386fd340d147a884606c86f9bc09b34333c2437/osu.Framework/Threading/GameThread.cs#L211-L217
* Secondly, in single-threaded mode, the main thread is actually the one that is running frames of all four types …
=> Fix culture changes not working when single-threaded

osu.Framework/Audio/Sample/SampleChannelBass.cs
Fixes the sample channel test failure mentioned in https://github.com/ppy/osu-framework/pull/4430#issuecomment-832154842.
This was caused by the playChannel() callback temporarily setting `Playing` to false by virtue of setting `enqueuedPlaybackStart` to false.
In multi-threaded execution, this is not a problem because `UpdateState` will then run and set `Playing` back to true by setting `playing` to true.
In single-threaded execution, this _is_ a problem because `UpdateState` only runs on the next audio frame, at which point the `SampleChannel` is now dead (due to `Playing = false`) and won't receive the `UpdateState`.
=> Fix SampleChannels with zero frequency not playing in single-threaded execution

osu.Framework/Audio/AudioManager.cs
Closes https://github.com/ppy/osu-framework/issues/4435
It seems like on some platforms, the audio device is initialised by default. Or this is dependent on ordering of tests:
```
[runtime] 2021-05-05 14:55:09 [important]: Simulating device loss...
[runtime] 2021-05-05 14:55:09 [important]: Attempting to sync audio devices...
[runtime] 2021-05-05 14:55:09 [important]: Enumerated devices: No sound
[runtime] 2021-05-05 14:55:09 [important]: Setting audio device (name: )
[runtime] 2021-05-05 14:55:09 [important]: Setting audio device (index: -1)
[runtime] 2021-05-05 14:55:09 [important]: Device ManagedBass.DeviceInfo not enabled.
[runtime] 2021-05-05 14:55:09 [important]: Setting audio device (index: -1)
[runtime] 2021-05-05 14:55:09 [important]: Device ManagedBass.DeviceInfo not enabled. …
```
=> Remove early return before bass init

.github/workflows/ci.yml, .github/workflows/report-nunit.yml
Closes #4426. This will run the `test` job against all supported platform runners in GitHub Actions on SingleThread and MultiThread mode.
Currently tests are flaky so I'm not sure how to fix this.
=> Run Test Job as Matrix

osu.Framework/Graphics/Containers/Markdown/MarkdownTableCell.cs
- Prereq for https://github.com/ppy/osu/pull/12688
As mentioned in https://github.com/ppy/osu/pull/12688#discussion_r626979310, `CreateTextFlow` method can't be overridden because it's not virtual method.
=> Change `CreateTextFlow` to virtual method in `MarkdownTableCell`

osu.Framework/Platform/GameHost.cs
Noticed this while looking into https://github.com/ppy/osu/issues/12543. Specifically the startup case, which seemed odd because if a user has set the `MidiHandler` to disabled, it shoudln't be closing any devices on startup.
Turns out that due to startup order, the initialisation code was run before the config has a chance to set the disabled state.
Have tested against the scenario in the linked issue to no longer run the `Enabled.BindValueChanged` where `NewValue==true` code path on startup.
=> Fix `InputHandler`s being initialised before enabled state is read from config

osu.Framework/Graphics/Containers/ContainerExtensions.cs
Closes https://github.com/ppy/osu/issues/12733 as per https://github.com/ppy/osu/issues/12733#issuecomment-835938318
Seems arbitrary to revert the anchor/origin of the wrapped drawable back to `TopLeft` as the container should have the same exact size as the wrapped drawable, rendering that pointless.
And reverting the `Origin` could cause issues to drawables that, for example, rescale themselves from inside the implementation, rather than externally on the wrapper container.
=> Keep anchor and origin when wrapping drawable via `ContainerExtensions.Wrap`

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs
The `KeyCollection` class does not use the default `EqualityComparer` as one would expect, falling back to a reference comparison. This was causing the skin dropdown to behave incorrectly osu!-side.
I've added a new test here, but the existing `TestBasic` will already fail with the move away from `string`s as the model type in all dropdown tests.
=> Fix incorrect comparison in `Dropdown` resulting in deselection of valid selection

.github/workflows/ci.yml
Resolves #4451. this includes `-warnaserror` on the compile step which elevates these warnings to errors. This has been tested locally, refer to following screenshot.
=> Run Compile Step with `-warnaserror` flag

osu.Framework/Graphics/Drawable.cs
`Anchor` and co. also have to be updated, but they're a bit more complicated due to mentioning the parent.
=> Reword xmldocs of Origin* properties

osu.Framework.Tests/Bindables/BindableDictionaryTest.cs, osu.Framework/Bindables/BindableDictionary.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/IBindableDictionary.cs, osu.Framework/Bindables/NotifyDictionaryChangedEventArgs.cs
Most of the implementation is similar to that of `BindableList`, including the tests which were mostly copied across.
One core difference between this and `BindableList` is that I've implemented `NotifyDictionaryChangedEventArgs` instead of using `NotifyCollectionChangedEventArgs`, because the latter didn't work well in real-world use.
Perhaps we could consider implementing a custom event for `BindableList` too though for greater type safety...
=> Add BindableDictionary<TKey, TValue>

osu.Framework.Tests/Lists/TestEnumerableExtensions.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs, osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs, osu.Framework/Screens/ScreenStack.cs
Also found that the implementation of `Enumerable.GetPrevious()` has always been incorrect in the same fashion.
=> Fix incorrect GetParentScreen()/GetChildScreen() values for screens not in stack

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework/Localisation/LocalisationManager.cs, osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs, osu.Framework/Localisation/TranslatableString.cs
I've chosen to make the storage nullable as it's a bit of a pain to provide an empty default. That said, if that's the preferred direction it can be done.
=> Fix `TranslatableString.Format` null ref when no languages are added to `LocalisationManager`

osu.Framework/Graphics/UserInterface/SliderBar.cs, osu.Framework/Testing/TestSceneTestRunner.cs
Ran into the following case osu-side:
```csharp
osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the Transforms of a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 2612
at osu.Framework.Graphics.Drawable.EnsureTransformMutationAllowed() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 2583
at osu.Framework.Graphics.Transforms.Transformable.AddTransform(Transform transform, Nullable`1 customTransformID) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Transforms/Transformable.cs:line 336
at …
```
=> Fix test scene restoring volume at an unsafe point in execution

osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs
Maybe it's fine to get this in for further testing? Seems like Chromium has experienced similar crashes/full system lockups as a result of FBOs and integrated this fix themselves:
http://crbug.com/1181068
http://crbug.com/783979
https://github.com/google/angle/commit/ce89d99fdeda61d9bc88fc7abd2aa3b4666d770e
=> Flush framebuffer after FBO bind on macOS

osu.Framework/Platform/SDL2DesktopWindow.cs
Allows usage of joysticks and controllers which are already connected on startup.
=> Populate connected controllers after SDL init.

.github/workflows/ci.yml
As seen in https://github.com/ppy/osu-framework/pull/4467/checks?check_run_id=2674918731 There was likely some changing in tooling in the GH Actions image that is now causing this.
`dotnet-format` is currently a no-op because it won't support .NET 5 until the tool version is upgraded:
https://github.com/ppy/osu-framework/blob/870e5d2dd7a535157dbc5fb46b2a4b8a165825b9/.config/dotnet-tools.json#L10-L16
Upgrading the tool is not simple because there's inspection conflicts with Resharper - in particular with ordering of `using`s which are not simple to resolve because Rider doesn't automatically sort usings. I thought it did but @peppy apparently experienced different.
Easiest solution is to just disable for now.
=> Disable dotnet-format from running on CI

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
If the content is added to the DLUW but the DLUW stops receiving updates, the content won't finish its load and will remain in `LoadState.Ready`.
=> Fix DelayedLoadUnloadWrapper asserting incorrectly

osu.Framework/Audio/AudioManager.cs, osu.Framework/Threading/AudioThread.cs
This is a speculative fix that should be mergeable if we want to get things back on track. Needs further investigation into whether this is expected behaviour on bass's end or not.
This fixes the case where:
- The user disconnects a device, causing the windows default to change to another existing device. They then reconnect their preferred device and windows switches back.
- The user disconnects a device, and it is the last available device (causing bass to enter virtual device mode). They then reconnect the device and it becomes available for use again.
Closes ppy/osu#12638.
=> Fix audio devices not working after being disconnected then reconnected

osu.Framework.Tests/Visual/Testing/TestSceneDerivedTestWithDerivedSource.cs, osu.Framework.Tests/Visual/Testing/TestSceneTestWithExternalSource.cs, osu.Framework.Tests/Visual/Testing/TestSceneTestWithSource.cs, osu.Framework/Testing/TestBrowser.cs
Done mostly as in the [documentation](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html), might have a small difference between but don't want to stuff more things into this any further.
=> Add support for `TestCaseSourceAttribute` in test scenes

osu.Framework.Tests/Audio/SampleBassInitTest.cs, osu.Framework/Audio/Sample/SampleBassFactory.cs
Fixes https://github.com/ppy/osu/issues/13266
If samples are loaded before `Bass.Init()`, `SampleLoad` fails with `Errors.Init`. In this case, and only this case, I want to reload the sample when a device is received afterwards.
I've added some safeguards in the hopes that it won't, but if the test fails intermittently then I can't see a good way to test this other than to ignore the test.
=> Fix samples not reloading if loaded too early

CodeAnalysis/BannedSymbols.txt, osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
=> Fix `MarkdownContainer` not translating relative URLs correctly on android/iOS

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
I've implemented this in a way which is least likely to break anything.
Closes https://github.com/ppy/osu/issues/12964.
=> Fix inability to backspace text after typing shifted characters

osu.Framework.Tests/Input/KeyBindingInputTest.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/Bindings/KeyCombination.cs
Fixes https://github.com/ppy/osu/issues/12936
`KeyBindingContainer` previously built the key combination directly from the `InputState`, not caring whether the event which changed the state ever reached the KBC. I identified two issues as a result of this:
1. Triggers the wrong binding when the KBC becomes alive.
1. The KBC has bindings `{ A, B }, { B }`.
1. `A` is held down.
2. The KBC becomes alive.
3. The user presses `B`.
4. The binding for combination `{ A, B }` is triggered when only the one for `{ B }` is expected.
2. Triggers when other `Drawable`s handled input.
1. The KBC has a binding for `{ A }`.
2. `A` is held down.
3. Another `Drawable` in the hierarchy handling input before the KBC handles `A` (never reaches the KBC).
4. The user presses `B`, which reaches the KBC.
5. The …
=> Fix KeyBindingContainer using InputState to build combinations

osu.Framework/Platform/Windows/TimePeriod.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs
In an attempt to figure out what is causing https://github.com/ppy/osu/issues/12702 we looked at all the operations we are performing on window active state change. This is the one that stood out the most.
Since this is a hard one to reproduce (does not affect all users), just going to get this out for user testing. Thinking about it, this could only be affecting users that have no other applications system-wide requesting a time period elevation. In general this is pretty rare as even Chrome will request it.
For reference, we don't do this in stable, and there is little reason to reset it on active state change (although it may be something we would consider if the game is ever minimising to system tray and expected to use zero resources).
=> Avoid changing windows time period when focus changes

CodeAnalysis/BannedSymbols.txt, osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs, osu.Framework/Utils/Validation.cs
...Which means URIs with a colon after the scheme name but no following double-slashes, and is basically an euphemism for `mailto:` URIs. I can't really imagine ever hitting a case of this with another URL scheme.
Fixed by applying [the first workaround listed in mono docs](https://www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/) more directly. I have tested on Android to confirm that doing so does not regress #4483, and it seems that it doesn't, but may be safer to double-check iOS, too.
Unsure of the placement of the new method, but `Validation` as an existing static class seemed fitting enough.
Closes https://github.com/ppy/osu/issues/13386.
=> Fix Markdown container crashing on absolute URIs with no authority part

osu.Framework.Tests/Bindables/BindableSerializationTest.cs
Made when testing https://github.com/ppy/osu-framework/issues/4493. Feels like some coverage that is good to have regardless.
=> Add test coverage of bindable serialisation from ctor parameter initialisation

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework/Localisation/LocalisationManager.cs
During initialisation, it may be that locales are added in an order which means the user's selected locale is not immediately present. This ensures that the configuration setting is never modified by `LocalisationManager`, so even if we are still firing many `TriggerChange` events, they will eventually end in the correct state.
Not sure if there's a better way to avoid firing so many events, but I don't think it's of immediate concern as this is generally early in startup, before many strings would be consuming the manager. We may want to consider exposing an `AddLanguages` method or something, though.
Closes https://github.com/ppy/osu/issues/13383.
=> Avoid overwriting user configuration locale when falling back to a default locale

osu.Framework/Threading/GameThread.cs
Noticed in passing that there's a potential for failure with the way this flag is handled: the thread could be `!IsAlive` for a brief moment before it is nulled. Calls to `Start` are checking for null, which may result in an invalid operation if the previous thread had not been nulled out yet.
https://github.com/ppy/osu-framework/blob/7d10a151ae4230e595fa912f64bb16761e9b48f1/osu.Framework/Threading/GameThread.cs#L250-L254
I have not reproduced this one, nor was it reproduced anywhere. Just seemed a bit dodgy..
This also makes `GameThread.Start` blocking, to give it symmetry with `GameThread.Pause` (which blocks in a similar fashion).
=> Improve safety of `GameThread.Running` (and make `GameThread.Start` blocking)

.github/workflows/report-nunit.yml
Just a simple rename of the run-annotating workflow to reduce the WTF factor when browsing the [actions view](https://github.com/ppy/osu-framework/actions). The "Test Report" items look like they should contain test results by their name, but they have no such thing and the main CI check run is actually the one to look at.
In general there is a filter view there too that also helps some:
but I don't believe it is possible to filter these annotation runs out to not show on the list by default.
=> Rename CI run-annotating workflow to explain its purpose better

osu.Framework.Tests/Graphics/ColourTest.cs, osu.Framework/Graphics/Colour4.cs
Something I ended up needing for the upcoming hex colour picker to implement preview-during-colour-type logic without simulating something like this using `try`/`catch` blocks, which is both bad practice and slow.
Generally reflects the .NET `Parse`/`TryParse` method philosophy.
=> Add `TryParseHex` methods to `Colour4`

osu.Framework/Platform/SDL2DesktopWindow.cs
Regressed in https://github.com/ppy/osu-framework/pull/4499 because the schedule call was not forced (and thus running incorrectly inline).
Closes https://github.com/ppy/osu-framework/issues/4507.
=> Fix switching to borderless window incorrectly overwriting window size configuration

osu.Framework/Input/PassThroughInputManager.cs, osu.Framework/Testing/Input/ManualInputManager.cs, osu.Framework/Testing/ManualInputManagerTestScene.cs
Noticed while reviewing another pull request. This regressed in https://github.com/ppy/osu-framework/pull/4484 and will also require a similar osu!-side fix.
`PlatformActionContainer` does block actions it handles, but due to the `ManualInputManager`'s presence the blocking stops at that point (and is handled a second time in the parent handling context). This PR allows the nested platform action container to only be used when automated actions are involved (as that is what it was added for).
Can be tested by backspacing in `TestSceneTextBox`.
=> Fix platform actions activating twice in `ManualTestScene`s

osu.Framework/Threading/GameThread.cs
Hopefully covers remaining test failure issues. The main resolution here is ensuring that `Thread` is `null` before `Running` is updated, but the lock has been added for extra safety, as we should never be starting/pausing a `GameThread` from different threads concurrently.
=> Add extra safety over thread start/pause logic

build/build.cake
#4468, but for appveyor as well. Also see https://github.com/ppy/osu/pull/13496.
PRing for visibility/ease of merge if this is deemed the way to go for now. An alternative would be to revisit #4410 (the reason why that one was abandoned is not entirely clear to me).
=> Disable `dotnet format` from running on appveyor too

osu.Framework.Tests/Visual/UserInterface/TestSceneHexColourPicker.cs, osu.Framework/Graphics/UserInterface/BasicHexColourPicker.cs, osu.Framework/Graphics/UserInterface/HexColourPicker.cs
Another part of #3134. The last part will be combining the two, which is basically a glorified way of saying "two `.BindTo()` calls with extra steps".
https://user-images.githubusercontent.com/20418176/121752419-60454600-cb10-11eb-9b87-dfba104a5b07.mp4
A note on the UX of this: Signaling input errors better than just discarding the value input by the user - by flashing the text box or otherwise - would definitely make this feel better, but the issue is that the structure of `TextBox` does not support that very well. What I mean by that is that both the things that control the appearance of it, and the things that control its behaviour wrt input validity (`NotifyInputError()`, `CanAddCharacter(char)`) are driven by virtual members.
So I cannot really define just the latter without the …
=> Add hex colour picker

InspectCode.ps1, InspectCode.sh, README.md
`build.sh`/`build.ps1` scripts also exist but they're a bit more all-encompassing, including running tests. The new scripts are sufficient for only running code inspections.
=> Add inspectcode scripts

.config/dotnet-tools.json, .github/workflows/ci.yml, osu.Framework/Game.cs
Fixes https://github.com/ppy/osu-framework/issues/4502
For the time being, I've published my own nuget package (smoogipoo.nvika) which has a GitHub build server built in. I've PR'd the change (https://github.com/laedit/vika/pull/290) and intend to use the official package once that's merged in. And if it isn't merged, I'll adopt it into the ppy org.
It can be seen working here: https://github.com/smoogipoo/osu-framework/pull/28/checks
- CI job fails
- Annotations in the `Files changed` view.
=> Make Resharper inspections fail the CI job

osu.Framework/Graphics/Shaders/ShaderManager.cs
Few simple changes to `ShaderManager` to become similar to other resource stores. Required for supporting https://github.com/ppy/osu/issues/13586.
- Make `LoadRaw` public and virtual, for the ability of overriding it and making a `FallbackShaderManager` osu!-side in `DrawableRulesetDependencies`.
- Add disposal logic that disposes of the underlying store, matches others like `TextureStore` which inherits `ResourceStore` that disposes of underlying stores.
- Make `ShaderManager` accept null underlying stores and make it an optional parameter, similar to `TextureStore` as well.
Also reorganizes the methods and xmldocs `Load` methods.
As a side note, I was also thinking about making `ShaderManager` inherit from `ResourceStore<byte[]>` and remove `LoadRaw` in favour of `ResourceStore.Get` …
=> Apply few changes to the `ShaderManager` structure

osu.Framework/Graphics/Shaders/ShaderManager.cs
`LoadRaw` returns `null` if the requested file could not be found. Didn't notice this as `ResourceStore`s don't have `#nullable enable` yet, which would make such mistakes easier to spot.
As an aside, I've double-checked ppy/osu#13594 with framework master + this PR, to ensure nothing requires changing any further.
=> Fix `LoadRaw` return value not marked as nullable

osu.Framework/Graphics/Containers/Markdown/MarkdownHeading.cs
Closes #4525
As I mentioned in https://github.com/ppy/osu-framework/issues/4525#issuecomment-864344644
Currently, `GetFontSizeByLevel` returns scale number value instead of actual font size value. Then that value is used to change heading size using scale.
This changes is make `GetFontSizeByLevel` to return actual font size value and then change the font size directly instead of using scale.
This is a bit breaking changes, so I need more advise for this PR.
=> Change markdown heading text size to use actual font size

osu.Framework/Platform/GameHost.cs, osu.Framework/Threading/DrawThread.cs, osu.Framework/Threading/GameThread.cs
PRing for comment. Intended to be used as a way for realm to clean up after itself.
Not sure if we want to instead expose somewhere in `GameThread` itself.
=> Expose an event from `GameHost` before update thread changes native threads

osu.Framework/Platform/GameHost.cs, osu.Framework/Threading/GameThread.cs
As discussed, this seems to feel better.
Also made a `GameHost`'s threads read-only. Oops.
=> Move pause event to only exist at `GameThread`

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownLinkText.cs, osu.Framework/Graphics/Cursor/IHasTooltip.cs, osu.Framework/Graphics/Cursor/TooltipContainer.cs, osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
Pushing this to make localisation of the tooltips text possible in osu! by changing the `IHasTooltip.TooltipText` property to a `LocalisableString`. 
I guess I could have kept the string version of this property around to prevent breakage for other framework users and have a defaut implementation in the interface point to the string one, but I'm not sure default interface methods are being used in framework.
`IHasTooltip.Text` now takes a `LocalisableString` instead of  regular string. Users of custom tooltip containers may also have to change checks in the `SetContent()` method of their tooltip type to check if content is a `LocalisableString` instead of a regular string.
=> Make tooltips text localisable

osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework/Platform/SDL2/SDL2Extensions.cs
Considering them the same looks to be wrong and have been causing state management problems (e.g. switching to borderless in a maximised window applies no effect).
For confirmation, I've added a "current window state" to `TestSceneFullscreen`, and started playing with the window states while checking what the `WindowState` value is, after applying this change. Looks to be correct in all scenarios.
https://user-images.githubusercontent.com/22781491/123504990-3427da00-d665-11eb-84b6-93dcd1807508.mp4
=> Differentiate between maximised and fullscreen borderless state in macOS

osu.Framework/Platform/SDL2DesktopWindow.cs
Resolves https://github.com/ppy/osu/issues/13638.
https://github.com/ppy/osu-framework/issues/4543 may touch more on the underlying issues, which is likely that the maximised state we are managing internally is flimsy during non-windowed display modes.
I'm just looking to fix this in the most resilient way possible, and this change does that. Appreciate testing on linux to make sure it doesn't regress anything (if there's even a concept of "maximised" conveyed there..)
=> Restore window before maximising to ensure the correct size is used

osu.Framework.Tests/Platform/GameHostSuspendTest.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/ThreadRunner.cs, osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/DrawThread.cs, osu.Framework/Threading/GameThread.cs, osu.Framework/Threading/GameThreadState.cs, osu.Framework/Threading/InputThread.cs
Not sure where to start or end on this one. Found many issues along the way. I'm sure there's more but this is running in a stable state and seems to be safer than what we had.
Would recommend taking the diff with a grain of salt and just parsing the whole classes involved. I guarantee we will find more areas of improvement during review (although try and keep scope in check).
Fixes issues listed in https://github.com/ppy/osu-framework/issues/4541 except for exposure of methods to consumers. Not addressing that yet because it's kind of their fault if they try to mess with threads directly.
I have not yet tested this with realm requirements, so blocking until I get to doing that.
=> Rewrite `GameThread` and expose state as `IBindable<GameThreadState>`

osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs, osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/GameHost.cs
This is not a new regression, and can be reproduced on previous framework releases before the `GameThread` changes.
Most of these changes are not actually related to the fix (see individual commit messages). Only the final two really matter.
=> Fix deadlock if disposing a `GameHost` which was never `Run()`

osu.Framework.Tests/Audio/TrackVirtualTest.cs, osu.Framework/Audio/Track/TrackVirtual.cs
- `Seek(CurrentTime)` failed even though the time is a valid value.
- `Seek(EndTime+1000)` succeeded even though the time is an invalid value.
- Following `TrackBass`, this should fail but seek to the end.
=> Fix TrackVirtual seeks failing in unexpected ways

.github/workflows/ci.yml, .github/workflows/report-nunit.yml
https://github.com/ppy/osu/pull/13639 but for framework.
Time limit for the main job matches appveyor. Briefly thought about going lower but /shrug. Not touching old deploy workflows either because those don't really run yet.
=> Set more appropriate time limits for GH Actions workflows

osu.Framework/Platform/GameHost.cs
I'm not sure if this had any adverse side effects (seems like it *should* have), but should make things saner in general regardless. Logging can be removed if preferred, but it seems like something good to have around.
Previously:
```csharp
[runtime] 2021-06-29 10:07:10 [verbose]: Host execution state changed to Running
[runtime] 2021-06-29 10:07:10 [verbose]: Execution mode changed to MultiThreaded
[runtime] 2021-06-29 10:07:10 [verbose]: BASS Initialized
[runtime] 2021-06-29 10:07:10 [verbose]: BASS Version:               2.4.15.26
[runtime] 2021-06-29 10:07:10 [verbose]: BASS FX Version:            2.4.12.3
[runtime] 2021-06-29 10:07:10 [verbose]: Device:                     No sound
[runtime] 2021-06-29 10:07:10 [verbose]: Drive:
[runtime] 2021-06-29 10:07:10 [verbose]: Host execution …
```
=> Avoid running exit sequence when it has already been run once

osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs, osu.Framework/Bindables/BindableNumber.cs, osu.Framework/Bindables/BindableNumberWithCurrent.cs, osu.Framework/Bindables/BindableWithCurrent.cs, osu.Framework/Bindables/IBindableWithCurrent.cs, osu.Framework/Utils/Validation.cs
Allows for having a `BindableWithCurrent` or `BindableNumberWithCurrent` instance depending on the value type itself, [as proposed here](https://github.com/ppy/osu/issues/13649#issuecomment-870006577).
Initially, I was going to privatize the classes' constructors and force all usages to call `IBindableWithCurrent<T>.Create()` to avoid potentially constructing `BindableWithCurrent<float>` instead of the correct `BindableNumberWithCurrent<float>`, but since that results in severe breaking changes, I've let that as-is for now.
=> Add factory method creating `BindableWithCurrent`s depending on the value type

osu.Framework.Tests/Visual/UserInterface/TestSceneColourPicker.cs, osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
This regressed in 3035d06 without me noticing. While improving the performance, those `AddOnce` calls broke my impromptu mechanism of detecting value change callback cycles using the `changeInProgress` flag, because after adding the schedule directly like in that commit, the `Current -> Hue/Saturation/Value` changes were happening in frame N, while the `Hue/Saturation/Value -> Current` changes, closing the undesired feedback loop, were happening in frame N+1, at which point the flag was already unset.
The proposed solution (which I don't entirely like but I don't see anything better) is to use that same flag for deciding whether to schedule the second part. I added inline comments to explain what is going there - hopefully they suffice.
In general colour storage is a nightmare. Going back …
=> Fix HSV colour picker spuriously changing some externally-set colour values

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/GameHost.cs
Without the check for `Idle` state, the `threadRunner` would attempt to stop threads which are not in a running state, causing a subsequent exception in the exit process, leaving the game in a `Stopping` state and waiting on the `stoppedEvent` in disposal logic.
=> Fix deadlock state if an exception is thrown during `GameHost.Run()`

osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
`VertexUtils<T>` is already documented but to reiterate, it is a helper class that keeps track of how many vertex attributes are enabled and enables and/or disables them as needed.
It will be needed for our project [vignette-project/vignette-live2d](https://github.com/vignette-project/vignette-application-live2d) which allows the framework to render Live2D models as the framework's current way, specifically making use of `VertexBatch<T>` is not suitable for our needs as we directly provide vertex and indices data to OpenGL.
One can argue that we can directly use `GL.EnableVertexAttribArray` directly but doing so will cause the class, or specifically `VertexUtils<T>.amountEnabledAttributes` to be in an invalid state.
Example code of how we use the class is this:
```csharp
public void …
```
=> Make `VertexUtils<T>` public

osu.Framework.Tests/Visual/UserInterface/TestSceneColourPicker.cs, osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
I had thought I had fixed an issue I was seeing when trying to push forwards with integration game-side, but it turns out I actually had two separate issues, depending on when `Current` was set...
Unfortunately the fix proposed is subtle and brittle, like the entire bindable flow in there is increasingly starting to be. I could maybe afford be a bit more haphazard and not have to worry about these small details, if the colour conversions weren't so lossy and imprecise. Better ideas very welcome.
=> Fix colour picker mutating current colour set before load complete

osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs, osu.Framework/Bindables/BindableNumberWithCurrent.cs, osu.Framework/Bindables/BindableWithCurrent.cs, osu.Framework/Bindables/IBindableWithCurrent.cs
Both missing constructors with `T defaultValue` parameter for `GetBoundCopy()` to successfully create an instance of the bindable type. Not sure if that can be enforced in some way.
Attached test case before change:
=> Fix `GetBoundCopy()` not working on "bindable with current" classes

osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs, osu.Framework/Graphics/Shaders/Shader.cs, osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Graphics/Shaders/ShaderPart.cs
Closes #4534 
Follows the existing pattern for GL disposal, if a `Shader`/`ShaderPart` gets finalised, the 3-frame delay will be applied, but if it's explicitly disposed, then there won't be any delay from the class itself, it would come from whatever's disposing of it internally (the `ShaderManager` in this case).
Double-checked with osu!lazer master and ppy/osu#13594. Looks to be working as intended. 
Also added a simple test case ensuring `Shader` references aren't leaked after disposing of `ShaderManager` (which heavily depended on doing https://github.com/ppy/osu-framework/commit/cd36ea3b8608aaa305603c0763c142a2ffd063f9 for testing without GL context, kinda ugly but needed).
=> Add shader disposal support

osu.Framework.Benchmarks/BenchmarkLocalisableString.cs, osu.Framework.Tests/Localisation/LocalisableStringTest.cs, osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework/Localisation/ILocalisableStringData.cs, osu.Framework/Localisation/LocalisableFormattable.cs, osu.Framework/Localisation/LocalisableFormattableString.cs, osu.Framework/Localisation/LocalisableString.cs, osu.Framework/Localisation/LocalisableStringEqualityComparer.cs, osu.Framework/Localisation/LocalisationManager.cs, osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs, osu.Framework/Localisation/LocalisationParameters.cs, osu.Framework/Localisation/RomanisableString.cs, osu.Framework/Localisation/TranslatableString.cs
Introduces a `LocalisableFormattable` class, containing the `IFormattable` object and the format string, and a method for formatting the `IFormattable` with the provided format provider.
Allowing for localising any `IFormattable` object (integers, floats, `DateTime`s, etc...) with the currently selected locale, like in [here](https://github.com/ppy/osu/commit/feb67bee58f071c0cfddba75dccdaf648275a0e5) for example.
---
I've initially written this for resolving https://github.com/ppy/osu/issues/13559, but I think it's worth actually using this for localising all `IFormattable`-formatted strings osu!-side (i.e. `double.ToString("N0")` and otherwise) while at it, will look into that now.
=> Add support for localising `IFormattable` objects

osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
The test scene in question was adding `Visual` prefixes to all other test scenes in typical fashion without the headless attribute.
While the test mentions "shaders" it's only really testing reference retention (or rather, lack thereof), so I believe it should be fine as a headless test. If it was hitting actual GL parts it should have been `[Ignore]`d anyway, because headless hosts don't get a GL context.
=> Mark shader disposal test scene headless

osu.Framework.Android/AndroidGameHost.cs, osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs, osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework.iOS/Graphics/Video/IOSVideoDecoder.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Graphics/Video/Video.cs, osu.Framework/Graphics/Video/VideoDecoder.cs, osu.Framework/Platform/GameHost.cs
This was suppsoed to just be adding a test to confirm that the decoding loop is not running while a `Video` is non-present, but turned out to be a bit of a refactor. Initially I tried to write the test using the `State` bindable, but it would never change from `Running` state when the video becomes hidden, because the scheduler was not being run. Our usual workaround of overriding `IsPresent` and adding a `Scheduler.HasPendingTasks` check would just cause the decoding to start again.
It was weird that `VideoDecoder` - a non-drawable component - was requiring a scheduler at construction time just to run a bindable update on the update thread. As the `State` bindable was not being used anywhere, I have removed it, along with the scheduler requirement.
=> Remove bindable `State` and `Scheduler` requirements of `VideoDecoder`

osu.Framework/Graphics/UserInterface/BasicDirectorySelectorBreadcrumbDisplay.cs, osu.Framework/Graphics/UserInterface/BasicDirectorySelectorDirectory.cs, osu.Framework/Graphics/UserInterface/BasicFileSelector.cs, osu.Framework/Graphics/UserInterface/DirectorySelectorBreadcrumbDisplay.cs, osu.Framework/Graphics/UserInterface/DirectorySelectorItem.cs
There were two areas where the customisation structure was lacking in order to migrate the game-side components to use the framework ones: sprite text construction (so that game can use `OsuSpriteText`), and a  "caption" on the breadcrumb display, by which I mean the "Current Directory" text below:
I couldn't just expose the flow for the breadcrumb thing since all breadcrumb items get reconstructed on directory change. Maybe a bit wasteful but I'm not super sure it's worth having nested flows instead... Game was reconstructing every time too already, for what that's worth.
This PR should not incur any breaking changes.
=> Expose extension points for replacing game-side file/directory selector 

osu.Framework/Graphics/Containers/CompositeDrawable.cs
This has been a point of contention for quite some months now, causing test failures at a rate of 50% (or maybe higher). The actual fix for this issue likely involves locking or changing the asynchronousity of the whole disposal/unbind/load process, which is quite involved.
This is intended to be a temporary fix until we get around to addressing the underlying issue. The case where a drawable is potentially missed due to `for` loop is generally not critical (just means they will be bound to other bindables for slightly longer than expected, but they will not be in a loaded state so in most cases this doesn't mean much).
=> Avoid collection-modified exceptions during unbind process

osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs
This was a weird overload added for a very specific use case in osu!, which has since been deemed to add very hidden input handling functionality that we'd rather avoid.
It doesn't make sense for a slider bar to handle input when it's not hovered under any circumstances.
=> Obsolete ability for slider bar to handle keyboard input when not hovered

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownLinkText.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
As seen in https://github.com/ppy/osu/issues/13848, currently markdown container does not support autolink.
Example of autolink syntax:
```markdown
<https://discord.gg/ppy>
```
This PR add overloading constructor in `MarkdownLinkText` to handle autolink and also add `AddAutoLink` virtual method in `MarkdownTextFlowContainer`.
=> Add support for parsing autolinks in Markdown container

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/BindableNumber.cs, osu.Framework/Bindables/RangeConstrainedBindable.cs
Spotted during [osu!-side PR review](https://github.com/ppy/osu/pull/13701#discussion_r666529763), quite bad this wasn't noticed at all.
Open to suggestions how this can be properly tested, the test case I wrote feels almost pointless, but can't think of anything better.
=> Unbind remaining events during `UnbindEvents` call

osu.Framework.Tests/Containers/ContainerEnumerableTest.cs, osu.Framework.Tests/Containers/TestSceneContainerState.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/UserInterface/Menu.cs, osu.Framework/Testing/MenuTestScene.cs
Gets rid of the usual mistake of setting a `Container` to `Children`, or passing a `Container` to `AddRange`, which causes weird behaviour such as "May not add a drawable to multiple containers" without any trace of being related to this.
Tests seem to pass, double-checked and removed any usages to this quirk.
=> Throw when attempting to set container to `Children` and similar cases

osu.Framework.Tests/Visual/UserInterface/TestScenePopover.cs, osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Graphics/Cursor/PopoverContainer.cs, osu.Framework/Graphics/UserInterface/Popover.cs
Some assorted fixes and improvements which resulted from @peppy attempting to use the control for multiplayer room password input. I recommend reading commit-by-commit; I didn't want to split this into 3 or 4 pulls because noise.
* 58863c6 removes the weird `OnMouse{Down,Up}` handling that seemed to be unnecessary in the end. Shaves a fair bit of complexity off as well.
* 7fed4ba fixes not being able to use the popover container in hierarchies that had auto-size axes on them. Fix mirrors what `ContextMenuContainer` and `TooltipContainer` already do.
* 26cde79 is intended to guide towards the proper usage of popovers (which is putting what should go inside the popover into `Children` rather than `InternalChildren`).
* f32bebb adds support for sizing the popovers directly rather than them …
=> Improve usability of popover & popover container

osu.Framework.Tests/Visual/UserInterface/TestScenePopover.cs, osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Extensions/PopoverExtensions.cs, osu.Framework/Graphics/Cursor/PopoverContainer.cs, osu.Framework/Graphics/UserInterface/Popover.cs
Another thing that fell out of @peppy's attempt of integrating the popover into the multi screen is that sometimes the "automagic" way of showing the popover, via handling the mouse events and target finding, doesn't work for various reasons in some scenarios (for instance, if a click never reaches the popover, like when the popover target is inside a scroll, or it might be desired to show a popover as a result of another user interaction, such as focusing a text box).
This pull adds a method to manually drive the nearest `PopoverContainer` via extension methods that traverse the drawable hierarchy. The test scene shows what can be done with this (showing a popover when a textbox is focused).
A side thing that also happens in this pull to allow the above test scene to happen, is relaxing …
=> Allow drawables to manually show and hide popovers

osu.Framework/Testing/Drawables/Steps/StepSlider.cs
Allows the user to right-click a SliderStep in the test browser to reset it to its default value.
[Streamable](https://streamable.com/xihrgd)
=> Reset a StepSlider to its default value when right-clicked

osu.Framework/Bindables/Bindable.cs
This is the most unsafe thing I've seen all year. Potentially leaving one side of the bindables completely bound.
Seems to only be used in this one method.
=> Remove extremely unsafe Bindable.Unbind() method

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/LeasedBindable.cs
Prereqs:
For bindables that override `BindTo()`, they should also override `UnbindFrom()` to revert changes. I don't know the deep implications (e.g. re: performance) of `UnbindAll()` calling `UnbindFrom()`, but it seems to be alright.
=> Make Bindable.UnbindFrom() virtual and called in all cases

osu.Framework.Tests/Visual/UserInterface/TestScenePopover.cs, osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Graphics/Cursor/PopoverContainer.cs, osu.Framework/Graphics/UserInterface/Popover.cs
This is intended to simplify how the dismissal of popovers works, removing the required logic inside `CreateBody()`'s resultant container. Passes all tests but probably needs some manual testing to ensure nothing weird has regressed.
- Refactor dismissal handling to avoid popover-level focus logic
- Remove exposed `CreateBody` (doesn't seem to be required)
- Update tests to cover new click-between behaviour (clicking a second popover provider will open immediately)
=> Refactor `PopoverContainer` to simplify dismissal process

osu.Framework/Extensions/PopoverExtensions.cs
The intention is to help framework consumers to understand how this component should be used, if they happen to be attempting to misuse it (rather than silently failing).
=> Throw an exception if a popover is attempted to be shown without a parent `PopoverContainer`

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Graphics/UserInterface/Popover.cs
Closes #4600.
Aside from the automated testing here, I tested with the game-side room password PR. It half-works, because currently two escape presses are needed (the first one is handled by the password textbox to yield focus, and only the second one is seen by the popover itself). I *think* that's something to fix at the usage site...?
=> Dismiss popovers on pressing Escape

osu.Framework/Graphics/Cursor/PopoverContainer.cs
Closes #4597.
Popovers that have been dismissed by the user could be displayed in the wrong location, due to sharing the `popoverContainer` with the currently displayed popover, which is attached to the current (new) target.
To resolve, use the popover itself as a replacement for the popover container. This works because both the removed container and the popover were/are 0x0 absolute-sized drawables, so the removed container's position can be combined with the move-back-in-bounds adjustment.
This isn't the general positioning refactor which was asked for, I'm more trying to just make things mostly work for now and move forward with other things.
=> Fix popovers fading out in wrong location

osu.Framework/Graphics/OpenGL/GLWrapper.cs
This neither fixed https://github.com/ppy/osu/issues/12944 nor peppy's crashes, so pretty safe to disable. I don't want to be causing too many unnecessary flushes.
=> Remove speculative macOS crash fix

osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/IWindow.cs, osu.Framework/Platform/OsuTKWindow.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
Due to initialisation order of the window, there's no guarantee that the `DisplayMode` will be in a good state when the `frameLimiter.TriggerChange()` call is performed.
This converts that property to a bindable to allow for late initialisation.
Closes https://github.com/ppy/osu/issues/13888.
Has been tested by @PandaDriver156 to fix the issue (one of those that reported it). I can't test locally because parallels decided to gimp their shit even more.
=> Fix refresh rate potentially being incorrect on startup

osu.Framework.Android/Input/AndroidTextInput.cs, osu.Framework.iOS/Input/IOSTextInput.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/GameWindowTextInput.cs, osu.Framework/Input/ITextInputSource.cs
As discussed in https://github.com/ppy/osu-framework/pull/4613#discussion_r671718379.
=> Remove unused `object sender` in ITextInputSource

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
Closes #4611.
Found at least two cases in which focus was incorrectly grabbed or not yielded by a readonly textbox:
* When dragging - as reported in the aforementioned issue; fixed by 9ee8c9a.
* When setting flag to `false` after construction and addition to hierarchy; fixed by d440c50.
The thing that is tested most is the reception of focus by the textbox. I skimped on doing paste/delete thoroughly except for one step + assert for brevity, but those should be handled correctly as long as this guard is there:
https://github.com/ppy/osu-framework/blob/08ffacbb0733efeb8973842321aed7dab7f1d61e/osu.Framework/Graphics/UserInterface/TextBox.cs#L150-L155
and there is one deletion step in there so if that is ever removed then the test will fail anyhow (alongside many others, I would hope?)
The …
=> Fix textbox readonly flag not working in all cases

osu.Framework.Templates/templates/template-flappy/README.md
Since this link didn't have a protocol part it would get recognized as a relative path in github, meaning it wouldn't work.
=> Fix link in FlappyDon template

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework/Localisation/TranslatableString.cs
Closes #4530
Also allows for cases like the one mentioned in https://github.com/ppy/osu/pull/13921#pullrequestreview-709051043 (`TranslatableString` accepting a `LocalisableFormattableString` argument) to be possible.
=> Handle localisable strings during `TranslatableString` formatting

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework/Localisation/LocalisableStringExtensions.cs
Similar to the C# built-in `ToString`, this adds a `ToLocalisableString` extension creating a `LocalisableFormattableString` for the `IFormattable` with the specified format string.
Simplifies usages from:
```csharp
Text = new LocalisableFormattableString(value, "#,##0");
```
to
```csharp
Text = value.ToLocalisableString("#,##0");
```
=> Add extension for localisable formattable strings

osu.Framework.Tests/Visual/UserInterface/TestSceneColourPicker.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneHSVColourPicker.cs, osu.Framework/Graphics/UserInterface/ColourPicker.cs, osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
Closes #4620.
This is incidentally the perfect counterexample for why blanket-including `this.Scheduler.HasPendingTasks` in the base `Drawable.IsPresent` is not a be-all and end-all of these types of issues.
Doing "the obvious" does not work with this component's structure. The child components are not the ones accessible outwardly, the picker itself is. And if someone is messing with the inner components, they are creating a problem entirely by themselves by misusing them.
=> Fix colour picker current not updating on HSV changes when not present

osu.Framework.Android/Input/AndroidTextInput.cs, osu.Framework.iOS/Input/IOSTextInput.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/GameWindowTextInput.cs, osu.Framework/Input/ITextInputSource.cs
Closes https://github.com/ppy/osu/issues/5284
Right now, if you manually close the keyboard by pressing the system back button, the keyboard will not open again if you tap on the currently focused TextBox. This PR fixes that.
`ToggleSoftInputFromWindow` is depricated in Android API level 31 (see [here](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#toggleSoftInputFromWindow(android.os.IBinder,%20int,%20int))) so `ShowSoftInput` is used instead.
**For iOS:**
The way `UpdateFirstResponder` works means that just calling `view.KeyboardTextField.UpdateFirstResponder(true)` in `ShowSoftKeyboard()` won't work as expected, as the keyboard might not close when the textbox is unfocused.
I don't have an iOS device to test with, so it's on somebody else to …
=> Show soft keyboard on Android on click of an already focused TextBox

osu.Framework/Screens/IScreen.cs
Using `nameof(ScreenStack.Push)` alone will only output `Push`, this should clarify to call the one in `ScreenStack` specifically.
=> Clarify to use `ScreenStack.Push` on null stack exception from extension

osu.Framework.Tests/Audio/TestSceneDrawableTrack.cs, osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
I don't know if this breaks anything (quick check says no) - hopefully we've built around the assumption that this is working correctly, but it's now working as it was initially intended.
=> Fix DrawableTrack/DrawableSample not receiving new parent adjustments when parent changes

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
This does not really do anything towards https://github.com/ppy/osu/issues/13966 yet, but it fixes a possible analogue of it that could occur for plain GET requests.
=> Fix GET request params not being percent-encoded

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/RequestParameterType.cs, osu.Framework/IO/Network/WebRequest.cs
PRing for discussion. The end goal is to use this change for https://github.com/ppy/osu/issues/13966 and fixing a TODO item therein in one fell swoop, by applying the following diff game-side:
```diff
diff --git a/osu.Game/Online/Rooms/JoinRoomRequest.cs b/osu.Game/Online/Rooms/JoinRoomRequest.cs
index b2d772cac7..d9d4f2eb5c 100644
--- a/osu.Game/Online/Rooms/JoinRoomRequest.cs
+++ b/osu.Game/Online/Rooms/JoinRoomRequest.cs
@@ -22,10 +22,10 @@ protected override WebRequest CreateWebRequest()
{
var req = base.CreateWebRequest();
req.Method = HttpMethod.Put;
+            req.AddParameter(@"password", Password, RequestParameterType.Query);
return req;
}
-        // Todo: Password needs to be specified here rather than via AddParameter() because this is a PUT request. May be a framework bug. …
```
=> Allow adding query string params to non-GET `WebRequest`s

osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Graphics/Containers/TextChunk.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs
This is a mostly "code quality" sort of change, but one that is pretty conducive to adding localisation to `TextFlowContainer` on the path that I have explored on my WIP/MVP branch. The commits are mostly simple source transformations:
* 578d6d3 renames `TextLine` to `TextChunk`. It was never really a "line" of text anyways; adding consecutive "lines" via repeated `AddText()` calls would make the text flow as normal and *not* add lines. The actual "new line" logic is in `AddLine()`.
* dfd39a8 splits the class to a new file - I intend it to grow, and contain all of the drawable-constructing logic that currently resides in the text flow itself.
* ede05f7 folds the `newLineIsParagraph` flag into the chunk - aside from simplifying data flow, it ensures that all information required to …
=> Split `TextChunk` from `TextFlowContainer`

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Graphics/Cursor/PopoverContainer.cs
Aims to ensure that popovers are cleaned up properly when their target gets disposed.
The schedule of `SetTarget(null)` is required as disposal can happen on non-update thread - omitting it was causing invalid transform mutation exceptions due to indirectly invoking `PopOut` otherwise. The scheduled `SetTarget(null)` call intends to ensure that both the reference to the disposed drawable is released and that the `OnDispose` subscription is removed.
=> Hide popovers on target disposal

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Graphics/Cursor/PopoverContainer.cs, osu.Framework/Graphics/UserInterface/Popover.cs
PRing for discussion. The reason that this is written so awkwardly (and the primary issue I was intending to resolve) was that with the current implementation, hover events were leaking to background drawables.
Unfortunately, doing
```csharp
protected override bool OnHover(HoverEvent e) => Body.ReceivePositionalInputAt(e.ScreenSpaceMousePosition);
```
is not viable. The reason why is that as you may recall, popovers have `ReceivePositionalInputEvent()` overridden to return `true` for any screen-space point. This in turn makes it so that the popover is *always* hovered, so long as the mouse is in bounds of the screen.
The thing about hover events is that a drawable will (correctly) *not* have its `OnHover()` called again if it is hovered, until it is finally unhovered. And the popover will …
=> Ensure that popover handles all mouse events within the bounds of its body

osu.Framework/Graphics/Drawable.cs
In profiling we have seen these `lock` objects add up. There's no reason to have one of these per drawable as the contention is so low that multiple drawables locking over a single instance should never be a problem.
=> Make `Drawable`'s `Scheduler` acquisition lock static

osu.Framework/Graphics/Sprites/SpriteText.cs
Resolves https://github.com/ppy/osu-framework/issues/3349
Autosize disallows cyclic invocations itself, so we are safe to incur an extra computation until autosize is split into two passes.
=> Disable SpriteText assertion on cyclic computation

.config/dotnet-tools.json, .github/workflows/ci.yml
Resharper CLI 2021.2.0 seems to have a deadlock somewhere: https://github.com/ppy/osu-framework/pull/4660#issuecomment-894178455
I'll report to JetBrains and update this description ASAP.
=> Revert InspectCode to 2020.3.2

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Uploading glyphs, which are usually `rgba(255,255,255,x)` to a texture atlas initialised with `rgba(0,0,0,0)` would cause incorrect interpolation of edge pixels in the case where a glyph has a non-zero alpha value.
I attempted to fix this in multiple different ways, but the solution here is the best combination of being performant and future-proof. A faster method would be to change the initialisation colour of the texture atlas in the case of glyph stores and call it a day, but this would break any potential usages where a user has fonts with colour data.
Note that the new `initialisationColour` flow is (in the end) unused in this PR, but I've left it in place for potential future usage and clarity as to what is going on. If you want to test the performance of the alternative method …
=> Fix glyph edge interpolation for non-transparent pixels

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs, osu.Framework/Audio/Track/TrackBass.cs
* Fixes #4670 (mostly)
* Fixes #4671
PRing for comment / CI verification. Tests passed locally.
As stated in the issues above, there is a dedicated mixer function for syncs and the above two issues were caused by not using it. Caveats:
* The syncs are manually unregistered and re-registered on each mixer change. The first is not necessarily required, but I decided to do it for safety, as [ManagedBass internally tracks callbacks](https://github.com/ManagedBass/ManagedBass/blob/0d46c12a8a9bdf8ceffdf60950cbb905cd5719b7/src/AddOns/BassMix/BassMix.cs#L773-L784), so I wasn't entirely comfortable with reusing the callbacks or leaving their unregistration to BASS.
* The mixtime stop sync is replaced by a standard sync. This is intentional, because due to mixer playback buffering the mixtime sync …
=> Migrate track BASS sync usages to mixer infrastructure

osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Fixes https://github.com/ppy/osu/issues/14184
This reverts all the changes to this test which were made in https://github.com/ppy/osu-framework/pull/4291.
It seems like the proper way is to flush the mixer, by setting its position to 0: http://www.un4seen.com/forum/?topic=6895.msg46426#msg46426
I've applied this to `ChannelSetPosition()` and to `ChannelStop()` (already had the flush) and `ChannelPause()`. The latter of which seems to be more required for stopping playback upon 0 frequency for `TestZeroFrequencyHandling`.
Tested over 100 times locally with no test failures, and can't repro the osu!-side issue after these changes.
=> Flush audio mixer on critical BASS operations (seek/stop)

osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs, osu.Framework/Input/StateChanges/JoystickAxisInput.cs
The `Precision.AlmostEqual` check meant that a transition from `0.0000302` to `0` would never fire an event, and as such all components would believe there is still an input to the physical device. This is an edge case where we should actually be handling true zero and allowing the event to still fire.
Note importantly that this can only currently happen when the deadzone is set to 0, rather than its current value. As such this incorrect behaviour will not trigger in realistic usages. We may allow tweaking the deadzone in the future though, at which point this *will* be required.
Incorrect behaviour:
https://user-images.githubusercontent.com/191335/128610877-6b586d6f-9de8-45aa-9e42-2f7f1f465d34.mp4
=> Fix joystick/controller axes potentially sticking at non-zero values

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs
Fixes https://github.com/ppy/osu/issues/14199
`NoRamp` flag was being applied to the (incorrect) decoding channel.
=> Disable audio mixer channel ramping

osu.Framework.Benchmarks/BenchmarkLocalisedBindableString.cs, osu.Framework/Localisation/LocalisationManager.cs, osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
master:
**benchmark will not complete** (performance consistently degrades enough from the `WeakList` overhead that benchmark.net will not allow it).
|                Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
| BenchmarkNonLocalised | 827.4 ns |  9.59 ns |  8.01 ns | 0.0591 |     - |     - |     680 B |
|    BenchmarkLocalised | 939.9 ns | 14.54 ns | 11.35 ns | 0.0668 |     - |     - |     776 B |
|                Method |      Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------- |----------:|----------:|----------:|-------:|------:|------:|----------:|
| BenchmarkNonLocalised |  68.50 ns |  1.397 ns |  1.307 ns | …
=> Fix localisation overhead in `SpriteText` / `LocalisedBindableString`

osu.Framework.Tests/Audio/BassAudioMixerTest.cs, osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Fixes https://github.com/ppy/osu/issues/14214
Decoding channels enter the `PlaybackState.Stopped` state when they reach the end, but are resumed into the `PlaybackState.Playing` state once seeked backwards. This is contrary to our expectation that the channel remains in a stopped state.
This change pauses the mixer channel on seeks while in the stopped state in order to match expectations.
=> Pause channels on seek from a stopped state

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs, osu.Framework/Audio/Track/TrackBass.cs
Fixes https://github.com/ppy/osu/issues/14262
Previously, stopping `SampleChannel`s would cause the mixer to get flushed. This would occur when slider sliding samples were stopped in particular: https://github.com/ppy/osu/blob/00ca066c39a66a31ade67b8ad33be8f57d377b7b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs#L136-L148  
Flushing messes with `ChannelGetPosition()`, as one would expect, causing it (and the `Track`'s current time) jump to a more up-to-date value. Unlike `Track`s, this is not useful for `SampleChannel`s due to the lack of a way to seek or retrieve their current time.
Gameplay comparison via `FrameStabilityContainer` logging:
Pre-bassmix: [runtime-old.log](https://github.com/ppy/osu/files/6979490/runtime-old.log)
Post-bassmix: …
=> Reduce amount of audio mixer flushes

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
In a similar way as https://github.com/ppy/osu-framework/pull/2128, hoping this re-fixes the issue for macOS users that have been experiencing it since https://github.com/ppy/osu-framework/pull/4291.
If it does, I'll add myself a todo to follow up with un4seen.
=> Drop float flag from audio mixer

osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
Helps me not lose my sanity. Closes #4464
=> Disable timeout in until-steps when debugger attached

osu.Framework/Graphics/Containers/ScrollContainer.cs
Closes https://github.com/ppy/osu/issues/14413.
Scrollbar scrolls were not marked as "user" scrolls, therefore breaking the game-side `UserScrollTrackingContainer`'s logic.
No tests included because there's not much to test in framework without moving the container here, pretty much. Which I can do on request, just wasn't sure if it's worth it.
=> Mark scrollbar drag-sourced scrolls as user scrolls

osu.Framework.Android/osu.Framework.Android.csproj, osu.Framework.iOS.props, osu.Framework.iOS/osu.Framework.iOS.csproj, osu.Framework/osu.Framework.csproj
See discussion in https://github.com/ppy/osu-framework/issues/2669.
Not sure why android has even been working in the mean time, as the specified package seems to have not been available on nuget...
=> Update osuTK again (with android build corrected)

osu.Framework/Graphics/Sprites/SpriteText.cs
Closes https://github.com/ppy/osu/issues/14523.
| :-: | :-: |
| ![2021-08-28-174949_749x171_scrot](https://user-images.githubusercontent.com/20418176/131223546-d0cfd1b1-364d-4a65-8d6d-ef4163e3469f.png) | ![2021-08-28-175118_746x168_scrot](https://user-images.githubusercontent.com/20418176/131223549-e3fbbfbb-8815-4d52-8414-03017553ebf5.png) |
| ![2021-08-28-175001_327x160_scrot](https://user-images.githubusercontent.com/20418176/131223551-c52a3288-cbff-428a-9ff0-83b6e0f90660.png) | ![2021-08-28-175128_289x154_scrot](https://user-images.githubusercontent.com/20418176/131223555-e193e0ce-b921-4ec1-81cb-e945685127f9.png) |
I would have included a test case for this but the roboto font actually does not have a glyph generated for `U+00A0` using bmfont it seems, so it shows up …
=> Exclude non-breaking space from fixed width in sprite texts by default

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs, osu.Framework/Extensions/PopoverExtensions.cs
This [came up previously as a usability issue](https://github.com/ppy/osu/pull/13861/commits/4dea2d97782151a1a8e383cd09cd225662b99d15). Due to the way `.FindClosestParent<T>()` works, you couldn't actually call `.HidePopover()` on a `PopoverContainer` and expect that same container to hide its popover, for no real reason at all. This change makes that possible.
Aside from being a usability improvement I need this for an upcoming game-side change.
=> Allow `HidePopover()` to be called directly on popover containers 

osu.Framework/Graphics/UserInterface/Menu.cs
From blame history, it looks like this was only done to consolidate the invalidation logic call. I've split this out to ensure correct behaviour, while avoiding the actual state change operations being unnecessarily run.
Closes https://github.com/ppy/osu/issues/14553.
=> Avoid running menu animation code on `Clear()` calls

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
Fixes #4742 
I've tested this and it works fine.
Not sure if tests should be added for this.
=> Fix `GetBackwardWordAmount()` going back two words if the last word is only one character long

osu.Framework/Graphics/Video/VideoDecoder.cs
Without this change, on reaching the end of a video the decode loop would spin on the `av_read_frame` loop, with no `sleep`. While this in general is not super-expensive, it's also not free, and can result in around 5-10% of a single core being used when video playback is no longer relevant.
Note that this doesn't occur during actual playback/pause (ie. before reaching the end of stream) due to the frame render count being upheld.
Closes https://github.com/ppy/osu/issues/14548, which is an edge case that performance overhead *is* a concern due to the video file throwing an error each `av_read_frame` in this state. With this PR, the error is no longer thrown. This means I can now playback the video mentioned in that issue without 100% cpu usage, and also without rider crashing immediately …
=> Reduce video decode overhead after reaching end of stream

osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework/Graphics/Video/Video.cs
=> Fix video stopping playback permanent when reaching end of stream

osu.Framework.Android/AndroidGameHost.cs, osu.Framework.Tests/Platform/UserStorageLookupTest.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/HeadlessGameHost.cs, osu.Framework/Platform/Linux/LinuxGameHost.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs, osu.Framework/Testing/TestRunHeadlessGameHost.cs
It was pointed out recently by @p00ya (after encountering this precise scenario) that user data could be completely unlinked from an existing "install" of an osu!framework game via the following steps:
- Run via release and have data created (previously defaults on macOS to `~/osu`, which is super weird but ok)
- Decide to help develop the game, install `dotnet-sdk` which makes a `.local/share` folder
- Run via release again and have data create at `.local/share/osu`, losing existing install at less-preferred `~/osu`
This changes the resolution to be a two-part lookup, with the first half checking for existing data folders and the second deciding where to create a *new* data folder.
Still not sure about the macOS default paths, but that's for another PR. We probably want to use …
=> Fix user storage potentially losing true existing install directory

osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs, osu.Framework/Graphics/Animations/AnimationClockComposite.cs, osu.Framework/Graphics/Video/Video.cs
Noticed that we were continuously decoding frames before a video started due to no checks in place.
Note that I did some code quality improvements around the `outOfSync` logic but the only part which matters is the early return.
=> Fix video decode running before start time

osu.Framework/Platform/HeadlessGameHost.cs, osu.Framework/Testing/TestBrowserTestRunner.cs, osu.Framework/Testing/TestSceneTestRunner.cs
Turns out that by running at unlimited frame rates during tests we were probably impeding performance. The specific issue is the draw thread, which is both unnecessary for this kind of testing, and also uninhibited (in headless mode there's no `SwapBuffer` to limit it to some sane speed) meaning it was just spinning a core at all times.
This was only noticeable in multi-thread execution mode, but this is also the default for headless testing. I've only tested on a 16 physical core system, but on less powerful dev machines the real-time improvement is probably much more significant.
Real time measurements come from rider runs (time reported in rider).
CPU time measurements come from total sampled times.
This is a test where a large number of frames are required to run to complete, so if …
=> Improve headless test run efficiency

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
`TabControl` was relying on `TabContainer` to have correct layout for the initial autosort, but the layout isn't correct yet and all children in `TabContainer` have y=0. 
`y==0` is used by `TabItem` for its `IsPresent` which is checked by `selectTab()` when considering whether to sort the new selection or not.
If the tab is present then it isn't sorted, but the tab might not be present if the initial selected tab is changed when constructing the `TabControl`. The result was the initial selection being hidden in the dropdown.
This PR calls `performTabSort()` directly in `LoadComplete` so the initial selection is always auto-sorted.
=> Let `TabControl` always sort initial selection if auto sort is on

osu.Framework.Benchmarks/BenchmarkDrawableLoad.cs
Same structures as used in `BenchmarkBeginAbsoluteSequence` but focused on the load of the drawables this time. Probably handy to have around.
=> Add benchmarks testing overhead of drawable load process

osu.Framework/Platform/GameHost.cs
Something I got bit by when working on support for transferring editor state between difficulties.
Game-side `ComposeScreen` uses `GetClipboard()` unprotected once for copying out object timestamps to the OS clipboard, which crashes headless. This never came up before likely because editor clipboard tests use `Editor.{Copy,Paste}()` directly, rather than firing platform actions, so that code path was never exercised.
In the ideal world this would also happen to `CreateWindow()` as well, but I don't want to detour to do that right now as that has a *lot* more usages.
=> Mark `GetClipboard()` as possibly returning null

osu.Framework/Graphics/Batches/QuadBatch.cs, osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
Now throws instead. This should be a very edge case that can only be hit with custom usage of `QuadVertexBuffer`, and is intended to avoid a runaway scenario where the game becomes unresponsive.
sample exception:
```csharp
[runtime] 2021-09-15 09:30:10 [error]: An unhandled error has occurred.
[runtime] 2021-09-15 09:30:10 [error]: System.OverflowException: Attempted to initialise a QuadVertexBuffer with more than QuadVertexBuffer.MAX_QUADS quads (10922).
[runtime] 2021-09-15 09:30:10 [error]: at osu.Framework.Graphics.Batches.QuadBatch`1..ctor(Int32 size, Int32 maxBuffers) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Batches/QuadBatch.cs:line 19
```
=> Avoid GL crash from vertex buffer index upload overflow

osu.Framework.Benchmarks/BenchmarkTextBuilder.cs, osu.Framework.Tests/Text/TextBuilderTest.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/IO/Stores/FontStore.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/IO/Stores/IGlyphStore.cs, osu.Framework/Text/CharacterGlyph.cs, osu.Framework/Text/ICharacterGlyph.cs, osu.Framework/Text/TextBuilder.cs, osu.Framework/Text/TextBuilderGlyph.cs, osu.Framework/Text/TexturedCharacterGlyph.cs
Previously characters were *implicitly aligned* using their `YOffset`s, and that works when only one font is used, but not when more than one font gets used inside one `SpriteText`/`TextBuilder`.
This PR aims to resolve the "multiple fonts" case by offsetting their `DrawRectangle`s based on the difference between the `Baseline` of the new character and the previous characters.
I've worked on this initially so that font-mixed sprite texts with #3271 don't look badly misaligned (as I noticed after implementing #3271), but apparently, there are already alignment improvements osu!-side with this PR alone (although slightly unnoticable):
- Before:
- After:
(notice `(TV Size)` aligned correctly with the other glyphs)
I have added in-depth test coverage in `TextBuilderTest` which had the perfect …
=> Align `TextBuilder` characters by their baselines during addition/removal

osu.Framework/Platform/FlushingStream.cs, osu.Framework/Platform/NativeStorage.cs
Following twitter advice (see https://github.com/EverestAPI/Everest/pull/301 / https://twitter.com/WEGFan/status/1438409484779491328?s=20).
Alternative to #4776 I guess? Probably fine to roll without that one and just tell any remaining users which hit this issue to delete their cache folder.
=> Flush all stream writes on dispose to avoid potential disk write failures

osu.Framework/Lists/SlimReadOnlyListWrapper.cs
Seems like an oversight as far as I can tell.
=> Publicly expose `SlimReadOnlyListWrapper.Count`

osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs, osu.Framework/Graphics/Containers/SearchContainer.cs
Allows matching `MultiplayerLoungeSubScreen` using `MLSScre` and the likes. Seems like behaviour we'd probably want in all search containers, but if that's a point of conflict it can be done via a property or derived class.
=> Add ability for `SearchContainer` to match even when letters are missing

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/GameHost.cs
Regressed with https://github.com/ppy/osu-framework/pull/4771.
=> Fix test execution running indefinitely after exception thrown in asynchronous load thread

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
If an effect is replaced in the `Effects` list with another of the same effect type (`FXType`), there's no need to remove the old effect before applying the new one. The new one can be applied on top through `FXSetParameters()`.
=> Replace BassAudioMixer effects in-place 

osu.Framework/Input/Bindings/KeyCombination.cs
Discussed in https://github.com/ppy/osu-framework/issues/4618#issuecomment-882590413.
Changes are:
- change capitalization of page up/down (to be in line with the new numpad keys)
- move the number keys to their place (separate from numpad keys)
- add missing numpad keys
- fix the bracket keys
=> Fix inconsistencies in `KeyCombination.getReadableKey()`

osu.Framework/Platform/SDL2DesktopWindow.cs
Closes #4608
This code seems to be doing nothing productive, the only thing it can do is reset the `windowPosition` in the config to unwanted values. Resulting in the windowed window appearing in the center if the screen when changing modes or opening the game.
Tested only on Windows.
=> Fix `windowPositionX/Y` being reset to `0.5` on startup

osu.Framework/Platform/ThreadRunner.cs
Hard one to write a test for, but should be obvious why this is needed. An alternative is to make `ExecutionMode` a field-backed computed property and lock on `set`. Either works for me if that is preferred.
=> Fix `ExecutionMode` potentially changing between equality and set calls

osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
As seen in https://github.com/ppy/osu-framework/pull/4794/checks?check_run_id=3716997033
Can be repro'd by adding a `Thread.Sleep(5000)` in `AsyncDisposalQueue`'s disposal task. This PR moves everything into a per-test isolated container.
=> Fix TestSceneTextures test failures

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
Has been happening intermittently for a while now, only just now had an idea for why it could occur.
Can be tested by adding a `Thread.Sleep(1000)` in `TestBox.load()`.
=> Fix TestSceneDelayedLoadUnloadWrapper test failures

osu.Framework.Tests/Visual/Platform/TestSceneResourceStores.cs
Not really sure how useful this test scene is, but the fix is easy enough so may as well just make it work properly. 
Initially I was thinking there was some cross-talk from other tests, but it looks like the `performance.log` file that keeps causing this issue is generated (due to many atlas backings being created for the `SpriteText` tests in the same scene) so it's a very local issue.
Fixes CI failures as seen at https://github.com/ppy/osu-framework/pull/4784/checks?check_run_id=3712782332.
=> Fix CI failures due to file access denied to log files

osu.Framework/Platform/NativeStorage.cs, osu.Framework/Platform/Storage.cs
Not sure how these got here, but they shouldn't be in o!f, as it is considered database backend agnostic.
=> Remove SQLite specific methods from framework `Storage` classes

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
I've run the test over a thousand times locally with no failures, including with sleeps during async processes (`AsyncDisposalQueue`, `load()`). It doesn't make sense to be any of those async processes though, because unload is run completely on the update thread, which is definitely running.
So I'm completely stumped but it fails quite often on CI. If others can repro locally then this PR can be closed.
=> Disable intermittently-failing test for now

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs
This is mainly to fix the only framework-side test scene relying on two `GameHost`s running at the same time.
=> Update `IsPrimaryInstance` on first access rather than after `GameHost.Run`

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
- Closes #3919
- Supersedes / closes #3831
This is another issue that has long plagued `TextBox` - I could never fully grasp how the `Current.Value` propagation there worked, there were no comments, I have several times tried to tweak around it to no avail. This PR is a proposal of how that could be cleaned up.
All operations that mutate `text` (the field) will now transfer it out to `Current.Value` at the end of the operation. This is only possible sanely due to tearing out the scheduler logic as done in #4522.
The initial version of this was much simpler, but unfortunately is complicated by the fact that a text operation could be compound with regard to how `TextBox` methods are shaped. For example, a text insertion with a selection present is really just a removal of the selection and …
=> Ensure text box's `Text` and `Current.Value` are synchronised

osu.Framework/Graphics/Video/VideoDecoder.cs
Temporary fix for #4858
This should resolve AVI videos not playing at all, except on Android with HW decoding enabled.
However there are still some pretty big problems with most HW decoders when used for AVI playback. I'm afraid these affect all of them except DXVA...
- seeking backwards breaks the video playback, it freezes at the current frame and starts spamming `Video too far out of sync`
- enabling it mid-playback can pin the GPU to 100% for a bit because it basically starts decoding from the start, it'll stop once it reaches the correct frame
Both of these are caused by the missing timestamps as the HW decoders only read `pts` and if it's missing they start counting the timestamps by themselves from 0.
I still plan to properly fix all of this but I couldn't find a solution that …
=> Fix video playback failing on invalid frame timestamps

osu.Framework/Graphics/BufferedDrawNode.cs, osu.Framework/Graphics/BufferedDrawNodeSharedData.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs, osu.Framework/Graphics/Lines/Path.cs
fixes ppy/osu#15434
caching the root node might cause problems in the future, but there doesn't seem to be any better way of getting the window resolution from here that i can think of
=> Allow BufferedDrawNode's frame buffer to be clipped to the root node

osu.Framework.Tests/Visual/Containers/TestSceneCachedBufferedContainer.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Effects/BlurEffect.cs, osu.Framework/Graphics/Effects/GlowEffect.cs, osu.Framework/Graphics/Effects/OutlineEffect.cs
As seen by the [regressions](https://github.com/ppy/osu/issues/15475#issuecomment-961382253), with the current invalidation structure we have, clipping to the root node does not mix well with `BufferedContainer` in the case it is caching its framebuffer.
To minimise user error, this PR hard couples the state of caching with the state of clipping. The rationale is that when not buffering, you would never want to draw to an area larger than the screen, while when you *are* caching you are usually aware of the size of the container, and may be explicitly using caching to draw to a larger area than is currently being displayed.
We can iterate on this if other use cases come up which don't obide by these rules.
Closes #15475.
---
```csharp
// old code:
var bufferedContainer = new …
```
=> Move `CacheDrawnFrameBuffer` property to constructor, replacing `clipToRootNode`

osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs, osu.Framework/Graphics/Video/FFmpegCodec.cs, osu.Framework/Graphics/Video/VideoDecoder.cs
Closes #4858 and fixes both problems that I mentioned in #4860
Android's MediaCodec unfortunately turned out to be a lost cause, I just couldn't get it to work properly no matter what I tried, so I added a check that disables HW decoding if the source is an AVI file...
As before, I only got to test this with the following HW devices, I highly recommend testing this on everything before merging.
Patch for testing:
```csharp
Index: osu.Framework.Tests/Visual/Sprites/TestVideo.cs
===================================================================
diff --git a/osu.Framework.Tests/Visual/Sprites/TestVideo.cs b/osu.Framework.Tests/Visual/Sprites/TestVideo.cs
--- a/osu.Framework.Tests/Visual/Sprites/TestVideo.cs	(revision bb82b3c57715f2f26532053ea1436b9102e5c34b)
+++ …
```
=> Fix .avi video seeking and Android playback when HW acceleration is enabled

osu.Framework/Platform/MacOS/MacOSReadableKeyCombinationProvider.cs
Is as well understood as "cmd" and much shorter.
=> Rename `Option` to `Opt` in key combination output

osu.Framework/Platform/GameHost.cs
Built SDL with debug, and got this warning when opening visual-tests:
The title does get set as expected, SDL probably has a good reason to complain.
=> Set window title after creation

osu.Framework/Audio/AudioCollectionManager.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Mixing/AudioMixer.cs
It doesn't support adjustments and is not in the expected location in the hierarchy. This only leads to confusion.
=> Make `AudioMixer` non-adjustable

osu.Framework/Audio/Track/TrackBass.cs
Rationale is that it can no longer work without being in the audio hierarchy. A `TrackStore` should be used instead.
Note that I am still working on the osu!-side changes to support this. Will block until I'm 100%.
- Closes https://github.com/ppy/osu-framework/issues/4813
=> Stop exposing `TrackBass`'s constructor

osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Mixing/AudioMixer.cs, osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs, osu.Framework/Graphics/Visualisation/Audio/AudioMixerVisualiser.cs, osu.Framework/Graphics/Visualisation/Audio/MixerDisplay.cs
The underlying events would potentially be fired too early and never reach the hooking methods due to the fact the invocation call site is run on the audio thread, before the binding may have completed.
Also done some restructuring for a future PR which allows showing an identifying string on the visualiser.
Can be tested via the existing `TestSceneAudioMixerVisualiser` while running in multi-thread mode (previously the new mixers would usually not display).
=> Fix audio mixers potentially not showing in `AudioMixer` visualiser

.idea/.idea.osu-framework.Android/.idea/indexLayout.xml, .idea/.idea.osu-framework.Android/.idea/projectSettingsUpdater.xml, .idea/.idea.osu-framework/.idea/indexLayout.xml, .idea/.idea.osu-framework/.idea/misc.xml, .idea/.idea.osu-framework/.idea/projectSettingsUpdater.xml
Feels a bit weird having something called `com.jetbrains.rider.android.RiderAndroidMiscFileCreationComponent` be in the root `.sln`, but it does exist for desktop as well ¯\\\_(ツ)_/¯
https://github.com/ppy/osu-framework/blob/1035fb17fea1fe9e39a179164bae275a1746514c/.idea/.idea.osu-framework.Desktop/.idea/misc.xml#L3
=> Add Rider autogenerated .idea files

osu.Framework.iOS.props, osu.Framework/osu.Framework.csproj
- Resolves https://github.com/ppy/osu/issues/13302
- Resolves the first point mentioned in https://github.com/ppy/osu-framework/issues/4677
- Works around https://github.com/mono/mono/issues/21188.
This is the simplest solution for the time being. Ideally we wouldn't want this package to be included in Xamarin projects to begin with, but not really sure if there's a simple way to do that without using `#if` directives (not sure we want that).
=> Downgrade `Microsoft.Diagnostics.Runtime` back to avoid AOT issues with iOS

osu.Framework.Tests/MathUtils/TestInterpolation.cs, osu.Framework/Utils/Interpolation.cs
This function can be used to to interpolate a value in a frame-rate independent manner without maintaining additional variables.
It should replace the current frame-rate dependent transition used in osu e.g. <https://github.com/ppy/osu/blob/f9d5abff8a8d3b6752343c185eb7767a3944a532/osu.Game/Screens/Play/SkipOverlay.cs#L132>.
=> Add more user-friendly variant of the exponential damp interpolation

osu.Framework.iOS.props, osu.Framework/osu.Framework.csproj
- Fulfills the second point in https://github.com/ppy/osu-framework/issues/4677 ("Testing of new bass library version")
Also resolves visible `ManagedBass` reference conflicts in iOS projects:
Tested this update to work on macOS and iOS, would appreciate testing on other platforms just in case.
=> Use upstream `ManagedBass` packages again and update to 3.1.0

osu.Framework/Audio/AudioManager.cs
Useful for ascertaining whether BASSmix has been properly loaded.
=> Log BASSmix version on successful BASS device initialization

osu.Framework/Graphics/Visualisation/Audio/AudioChannelDisplay.cs, osu.Framework/Graphics/Visualisation/Audio/MixerDisplay.cs
Previously only the levels of the source/mixer channels would be shown, not the mixer output itself.
=> Add mixer output levels to audio visualizer

osu.Framework.iOS.props
Matches [osu!](https://github.com/ppy/osu/blob/f208a931b8c725ab49413f2f715b0f86b986fec0/osu.iOS.props#L15) and [the template game projects](https://github.com/ppy/osu-framework/blob/a8429246cd22b686db420a89c049a57792f37923/osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj#L58). Saves time having to set the codesign key everytime (although I would still have to change the bundle identifier to match my provisioning profile anyways)
=> Add "iPhone Developer" codesign key to iOS projects

osu.Framework/Graphics/Video/VideoDecoder.cs
Possibly affected some other formats as well.  
[Docs for `AVFormatContext.duration`](https://ffmpeg.org/doxygen/4.1/structAVFormatContext.html#ad0ea78ac48f5bb0a15a15c1c472744d9)
=> Fix .webm videos reporting incorrect duration

osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs, osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/PlatformActionContainer.cs
Reasoning mentioned in https://github.com/ppy/osu-framework/issues/4773.
See a pretty shocking oversight in db22119df which went unnoticed until now as tests were focused on the non-event-based repeat handling (which is removed in this PR). Existing tests cover the fail case - revert the commit to confirm.
Use the `KeyBindingPressEvent` provided in `OnPressed` delegates to identify (and ignore or handle) repeats instead.
=> Remove `KeyBindingContainer.SendRepeats`

osu.Framework/Input/Bindings/KeyBindingContainer.cs
We want to use this for gameplay cases osu!-side.
=> Add back ability to disable key repeat firing in `KeyBindingContainer`

osu.Framework/Graphics/Containers/FillFlowContainer.cs
This fixes an issue where an array rented from `ArrayPool` would have its `Length` read. The reason why you should never read the length of a rented array is because you have no guarantee on its size since (documentation) it is **at least** the requested size, meaning it can be longer than requested.
In this case the `[^1]` indexer is translated to `[target.Length - 1]` and as such it could access an element outside the requested range, which caused longer `FillFlowContainer`s to read `0` or a "random" value as their total height.
=> Fix improper access to rented array in `FillFlowContainer` with `^` indexer

osu.Framework.iOS/osu.Framework.iOS.Dllmaps.props, osu.Framework.iOS/osu.Framework.iOS.csproj
Turns out the current dllmap configuration (via `BundleResource`) was only working with projects referencing framework locally.
While looking at a way for nupkg reference support, I've stumbled upon [Realm](https://github.com/realm/realm-dotnet/blob/588d58c5efcd0f4a3d1fea55f868dc7f92e7ad2c/Realm/Realm/Realm.csproj#L42-L48)'s [iOS setup](https://github.com/realm/realm-dotnet/blob/588d58c5efcd0f4a3d1fea55f868dc7f92e7ad2c/Realm/Realm/RealmWrappersReferences.props#L5-L14), which was perfect for referencing dllmap configuration in all projects referencing via nupkg, as the `.dll.config` files get automatically included in the projects as can be seen:
Tested this to work with osu!framework local projects, osu! via local reference, and osu! via nupkg reference.
---
One issue with this however is …
=> Include `ManagedBass` dllmaps in projects referencing via nupkg

osu.Framework.Tests/Visual/Containers/TestSceneCustomizableTextContainer.cs, osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs
Which includes both the language/locale setting and the 'prefer unicode'/romanisation setting.
This was crashing because I missed that `CustomizableTextContainer` was keeping placeholders in a separate list, and so they are like manual text parts in that they are given once externally and cannot be recreated if disposed. The fix is analogous to manual text parts - the placeholders are removed manually before every text flow content recreation triggered by the localisation parameters changing.
Test coverage included.
Closes ppy/osu#15698.
=> Fix customizable text container placeholders being disposed on localisation parameter change

osu.Framework.iOS.props, osu.Framework/osu.Framework.csproj
Resolves a runtime issue with `Markdown` seen in osu! when running in Release configuration:
```
2021-11-22 20:29:27 [error]: An unhandled error has occurred.
2021-11-22 20:29:27 [error]: System.TypeInitializationException: The type initializer for 'Markdig.Markdown' threw an exception. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2021-11-22 20:29:27 [error]: at Markdig.Markdown..cctor () <0x10c023520 + 0x00050> in <303bd4757e5f496993647645edf2c14e#ea2eaafc0823b3d3502b57b3688dec27>:0
2021-11-22 20:29:27 [error]: --- End of inner exception stack trace ---
2021-11-22 20:29:27 [error]: at osu.Framework.Graphics.Containers.Markdown.MarkdownContainer.validateContent () <0x105ee71a0 + 0x00070> in <dc6fe624359a411c96b2b0dddc1c998c#ea2eaafc0823b3d3502b57b3688dec …
```
=> Downgrade `Markdig` back to avoid runtime issue on iOS

osu.Framework/Graphics/UserInterface/TextBox.cs
A blinking cursor signals to the user that keyboard input will appear at that cursor.
This PR hides the caret when we lose keyboard focus to conform with that expectation.
Only hides the caret if there is no selection. The current show/hide logic on focus/unfocus is kept.
Native applications will usually grey-out the selection when inactive, but that is unnecessary for us.
=> Hide `TextBox` caret when `GameHost` is inactive / keyboard focus is lost

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
I intend to get this out in a release to see if this fixes all crashed test runs. E.g.:
https://github.com/ppy/osu/runs/4306364513?check_suite_focus=true
https://github.com/ppy/osu/runs/4306364580?check_suite_focus=true
https://github.com/ppy/osu/runs/4307525554?check_suite_focus=true
https://github.com/ppy/osu/runs/4307525591?check_suite_focus=true
I have a suspicion it may be caused by applying effects on the no-sound device.
=> Temporarily bypass FXSetPriority in NUnit runs

osu.Framework/Threading/AudioThread.cs
Attempting to fix test intermittent such as https://github.com/ppy/osu/runs/4311311823?check_suite_focus=true
Thinking it's something like the audio device getting cleaned up external to osu!, since it only happens on the macOS test runners.
=> Add additional safeguards to BASS device cleanup

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
For example, latest `master` with `LeftRightPadding = 100`:
https://user-images.githubusercontent.com/16479013/143657321-d029b6e7-1c18-4e6d-8dd0-84001cb2448d.mp4
Happens because [this check](https://github.com/ppy/osu-framework/blob/fe00cc23f6393fd8891fc1d94e3ee37041e242fc/osu.Framework/Graphics/UserInterface/TextBox.cs#L389-L392) doesn't succeed because of wrongly calculated `cursorRelativePositionAxesInBox`.
This isn't easily noticeable with TextBox's default of 5, or OsuTextBox's default of 10, but the caret will go ever so slightly more to the right before scrolling the view.
**This PR:**
https://user-images.githubusercontent.com/16479013/143657575-e6629333-4108-46a1-9019-b465dbcc4297.mp4
=> Fix caret potentially going out of textbox bounds with sufficiently high LeftRightPadding

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/IIpcHost.cs, osu.Framework/Platform/IpcChannel.cs, osu.Framework/Platform/TcpIpcProvider.cs
1. Allows sending responses back to incoming requests.
2. Allows sending an IPC request with a response.
3. Extracts the port out from a const.
The goal here is to be able to accept IPC messages from osu!stable (e.g. to calculate difficulty) and send a response back.
=> Improve IPC to allow sending responses

osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
Saw this a few times [on CI](https://github.com/ppy/osu-framework/runs/4349401930?check_suite_focus=true), but I could reproduce 100% on a certain subset of the tests. The main issue revolves around the test scene running in accelerated time, causing the elapsed time to not match the decode process' expectations. This can lead to things potentially getting in a weird state where the decode never starts process frames, or reaches the end of the video when it shouldn't.
Without these changes, I would see the following failures 100% of the time:
Post changes, I ran for 10 minutes with no failures.
=> Fix video seek tests failing on macOS

osu.Framework/Audio/AudioManager.cs
- Closes https://github.com/ppy/osu/issues/14729
- Resolves https://github.com/ppy/osu/discussions/15886
Starting in BASS 2.4.16, BASS pauses audio output completely when the selected audio device stops processing, which can happen when a computer switches to sleep mode, for example.
There is a flag defined for this behaviour (`BASS_CONFIG_DEV_TIMEOUT`) which has now been disabled in this PR, bringing back the old behaviour which is to keep audio output running regardless of whether the selected audio device has stopped processing, resolving both of the issues mentioned at the top.
See https://www.un4seen.com/forum/?topic=19601 for discussion.
---
Also in case anyone wondering, I've got the bits of the `BASS_CONFIG_DEV_TIMEOUT` flag via the `bass.h` header included in the BASS libraries, …
=> Keep BASS audio output from pausing on device processing timeout

osu.Framework/Platform/GameHost.cs
Fixes exceptions potentially not appearing in logs even though they occurred and caused a halt in execution.
Closes https://github.com/ppy/osu-framework/issues/4920.
=> Force flushing logger during unhandled/unobserved exception handling

SampleGame.iOS/Info.plist, osu.Framework.Android/osu.Framework.Android.csproj, osu.Framework.Tests.iOS/Info.plist, osu.Framework.iOS.props, osu.Framework.iOS/osu.Framework.iOS.csproj, osu.Framework/osu.Framework.csproj
Unlocks `CADisplayLink` to reach frame rates higher than 60hz (when combined with https://github.com/ppy/osuTK/pull/71).
Also adds a missing key to `SampleGame.iOS` that is already present in `osu.Framework.Tetss.iOS`, while there.
=> Disable minimum frame durations on iOS framework projects

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/Container.cs
Until now, this was falling through to an exception firing on the (framework-internal) logic of nulling the `Parent` (see https://github.com/ppy/osu-framework/blob/dde9eb08ede4aa94d21590f92b7c60f85cac3947/osu.Framework/Graphics/Drawable.cs#L1481-L1482) which doesn't read too well to a framework consumer.
In the above example ([ci failure](https://github.com/ppy/osu/runs/4453854462?check_suite_focus=true)) it reads so badly the actual cause of failure is uncertain.
=> Improve exception messaging when calling `CompositeDrawable.InternalChild` on disposed drawable

osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/TcpIpcProvider.cs
The hope here is that this will fix intermittent test failures I see specifically on my local macOS install, osu!-side. I believe the root cause was the short `ipcThread.Join()` length meaning the socket potentially wasn't unbound in time.
But at the same time, this was a dated class and needed some clean-up.
Note that I'm still using a thread to do the listening loop as `TcpListener` isn't a great `async` resident, without proper support for `CancellationTokens`. Sticking to what works for now.
=> Refactor `TcpIpcProvider` to bring up to date with code standards

osu.Framework/Screens/ScreenStack.cs
Generally pushing screens is quite a rare event, and should add context to most log usages (tracking down issues reported by users etc.).
We already did this osu! side but moving to framework seems to make sense. I've left at a `Verbose` level so it is actually logged in release builds.
Not sure about the log format, especially the `[]` as they are also used for the verbosity level.
```csharp
985366: Running ScreenStack (TestSceneScreenStack) visual test cases...
[runtime] 2021-12-16 08:47:43 [verbose]: [ScreenStack] transition (none >> TestScreen)
985366: TestSceneScreenStack
[runtime] 2021-12-16 08:47:43 [verbose]: [ScreenStack] transition (TestScreen >> TestScreen)
985566: step 1 push screen1
985766: step 2 Repeat: ensure current (1 tries)
985966: step 3 preload screen2
986166: step 4 …
```
=> Add screen stack logging

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Threading/ScheduledDelegate.cs, osu.Framework/Threading/ScheduledDelegateWithData.cs, osu.Framework/Threading/Scheduler.cs
Bit of an unfortunate scenario with the constructor requiring a static delegate. Open to suggestions on how to improve this.
=> Fix `AddOnce` scheduled tasks not getting updates to data from subsequent calls

osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs, osu.Framework.Tests/Visual/Input/TestSceneMidi.cs, osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs, osu.Framework/Screens/ScreenStack.cs, osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs, osu.Framework/Testing/TestBrowserTestRunner.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/Testing/TestSceneTestRunner.cs
Also uses `Logger` rather than `Console.WriteLine` everywhere.
=> Use icons and reduce clutter in test logging

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Logging/LoadingComponentsLogger.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/osu.Framework.csproj
May help with figuring out the cause of intermittent failing tests. Just maybe.
```csharp
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #4 push slow
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #5 push slow
[runtime] 2021-12-16 10:42:53 [verbose]: 📺 ScreenStack transition (TestScreenSlow » TestScreenSlow)
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #6 push slow
[runtime] 2021-12-16 10:43:03 [verbose]: 💥 Step #7 Until: wait for screen 2 to load (23962 tries)
[runtime] 2021-12-16 10:43:03 [verbose]: ⏳ Currently loading components
[runtime] 2021-12-16 10:43:03 [verbose]: - TestSceneScreenStack+TestScreenSlow LoadState:Loading Thread:ThreadedTaskScheduler (LoadComponentsAsync (standard))
[runtime] 2021-12-16 10:43:03 [verbose]: - TestSceneScreenStack+TestScreenSlow LoadState:Loading …
```
=> Log loading components on test failure or game exit

osu.Framework/Logging/LoadingComponentsLogger.cs, osu.Framework/Logging/Logger.cs
These are cases we expect to work when a framework consumer (running a release framework build) builds as debug. The attribute won't work as it is compile-time baked.
=> Fix incorrect usages of `ConditionalAttribute` for debug isolation

osu.Framework.Tests/Audio/TrackBassTest.cs, osu.Framework.Tests/Audio/TrackVirtualTest.cs, osu.Framework/Audio/Track/TrackVirtual.cs
After trying and failing to write a game-side test for a scenario involving track disposals, I've discovered that `TrackBass` and `TrackVirtual` do not behave the same wrt disposal. The former would stop the track (as in `Clock.CurrentTime` would not increase), and the latter would let the inner stopwatch continue, and therefore you could have a virtual track which is both disposed and elapsing.
This PR changes the behaviour of `TrackVirtual` to stop the track on disposal.
While disposal is a bit of a grey / undefined area in these sorts of cases, I feel like stopping the track in such a case is not unreasonable and unifies expectations across different `Track` implementations. Samples [already behave in a similar manner](https://github.com/ppy/osu-framework/blob/7d8e6d048d75cf0fb60e14d9c6 …
=> Stop virtual tracks on disposal

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs, osu.Framework/Graphics/Sprites/SpriteIcon.cs
Added properties for `ShadowOffset` and `ShadowColour`. 
Noticed these weren't exposed when working on my own framework project.
Example
Default values have been set to visually match previous behaviour. 
Test steps also added to `TestSceneSpriteIcon`.
=> Add Shadow Colour and Offset to SpriteIcon

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Logging/LoadingComponentsLogger.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/Threading/ThreadedTaskScheduler.cs
See individual commit messages for the changes applied.
Before:
```csharp
[runtime] 2021-12-20 04:52:42 [verbose]: 💨 LoadComponentAsync (TestSceneLoadComponentAsync) running
[runtime] 2021-12-20 04:52:42 [verbose]: clearing children
[runtime] 2021-12-20 04:52:42 [verbose]: children cleared
[runtime] 2021-12-20 04:52:42 [verbose]: 🔸 Step #1 clear all children
[runtime] 2021-12-20 04:52:42 [verbose]: 🔸 Step #2 load async
[runtime] 2021-12-20 04:52:42 [verbose]: 🔸 Step #3 Until: component loaded (3 tries)
[runtime] 2021-12-20 04:52:42 [verbose]: 🔸 Step #4 Assert: invocation count is 1
[runtime] 2021-12-20 04:52:42 [verbose]: 🔸 Step #5 load many components
[runtime] 2021-12-20 04:52:52 [verbose]: 💥 Step #6 Until: wait for loads (31301 tries)
[runtime] 2021-12-20 04:52:52 [verbose]: ⏳ …
```
=> Improve test logging output further

osu.Framework/Graphics/Drawable.cs, osu.Framework/Screens/ScreenStack.cs
There may be a problem somewhere within its logic, so I've added some more verbose logging so we can maybe track it down. May remove the "scheduled load" logs after we resolve any issues, as those aren't really helpful to the user (should just be part of the "push" logging under one name).
This also splits out the transition events into two lines, describing the individual operations. This makes more sense because in the case of a `Push` operation, the point at which the new screen is pushed versus when the previous screen is separated could be separated by a longer duration, due to load times.
Example output:
```csharp
[runtime] 2021-12-20 06:42:14 [verbose]: Opened realm "/var/folders/qt/mf5nyxrn07s0_mwpb_t8bl5h0000gn/T/of-test-headless/TestSceneHostOnlyQueueMode-b481a6a0-ae7d-438e-9111- …
```
=> Add more detailed `ScreenStack` logging

osu.Framework/Logging/LoadingComponentsLogger.cs
Was a bit confusing having this use a different display method to everything else.
=> Use `Drawable.ToString` in `LoadingComponentsLogger`

osu.Framework/Screens/ScreenStack.cs
Weren't being logged, to the point the last log entry could say "loading" followed by radio silence. Note that this would only be the case for the top level screen. In the case where it's not, the `exitFrom` would likely log.
=> Add logging of `ScreenStack` push failures due to `ValidForPush` being `false`

osu.Framework.Tests/Localisation/LocalisationTest.cs, osu.Framework.Tests/Visual/Localisation/TestSceneTextFlowContainerLocalisation.cs, osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs, osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs, osu.Framework/Audio/Sample/SampleStore.cs, osu.Framework/Audio/Track/TrackStore.cs, osu.Framework/Graphics/Textures/TextureLoaderStore.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/IO/Stores/DllResourceStore.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/IO/Stores/IResourceStore.cs, osu.Framework/IO/Stores/OnlineStore.cs, osu.Framework/IO/Stores/ResourceStore.cs, osu.Framework/IO/Stores/StorageBackedResourceStore.cs
Noticed that a lot of avatars get stuck in a loading state, even though they are likely not required for loading purposes (they have since been disposed or forgotten).
Having cancellation token support should allow for improving such cases, cancelling the underlying web request if it is already in progress.
Note that this will require usages to be updated to pass the `CancellationToken` from DI. And maybe `async` support for BDL. But it's a start and doesn't look to break anything.
=> Add `CancellationToken` support to `IResourceStore.GetAsync`

osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Android/AndroidGameView.cs, osu.Framework.Android/osu.Framework.Android.csproj, osu.Framework.iOS.props, osu.Framework.iOS/osu.Framework.iOS.csproj, osu.Framework/osu.Framework.csproj
* Removes the "kill on pause" behaviour which was in place due to the context loss.
* Ensures that the game host is not created multiple times on resuming game.
* Suspends all threads on activity pause and resumes them again on activity resume.
* Additionally I've had to manually pause/start all audio output on pause/resume via BASS as unfortunately pausing the audio thread itself did not appear to be sufficient (the audio would continue playing even after the app was paused/backgrounded). Not sure how this isn't an issue on iOS.
Tested on two Android devices that I own:
* Samsung Galaxy J7 2016 / SM-J710F (Android 7),
* OnePlus 8T / KB2003 (Android 11)
=> Adjust Android lifecycle code in line with context preservation changes

osu.Framework/Testing/Drawables/Steps/StepButton.cs, osu.Framework/Testing/TestScene.cs, osu.Framework/Testing/TestSceneTestRunner.cs
Was bugging me
```
[runtime] 2021-12-23 07:03:47 [verbose]: 💨 Video(TestSceneVideo) TestJumpForward("avi")
[runtime] 2021-12-23 07:03:47 [verbose]: 🔸 Step #1 "Reset clock" SingleStepButton
[runtime] 2021-12-23 07:03:47 [verbose]: 🔸 Step #2 "load .avi video" SingleStepButton
[runtime] 2021-12-23 07:03:47 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2021-12-23 07:03:47 [verbose]: Successfully initialized decoder: h264
[runtime] 2021-12-23 07:03:47 [verbose]: 🔸 Step #3 Until: "Wait for video to load" UntilStepButton
[runtime] 2021-12-23 07:03:47 [verbose]: 🔸 Step #4 "Reset clock" SingleStepButton
[runtime] 2021-12-23 07:03:47 [verbose]: 🔸 Step #5 Until: "Wait for decode start" UntilStepButton
[runtime] 2021-12-23 …
```
=> Output test method name in log output

osu.Framework.Tests.Android/TestGameActivity.cs
Fixes the titlebar being constantly visible and therefore hiding the test search box as well as a few first items on the test list, making audio visual tests nigh unreachable on mobile.
Method used [stolen from game](https://github.com/ppy/osu/blob/048ca98f4aa11c1685ee3af41fbb33429129bba4/osu.Android/OsuGameActivity.cs#L62). Didn't set `WindowManagerFlags.KeepScreenOn` because I don't really think that's super needed in a test activity.
=> Use fullscreen mode in Android visual test activity

SampleGame.Android/SampleGameActivity.cs, osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Android/Properties/AssemblyInfo.cs, osu.Framework.Tests.Android/TestGameActivity.cs
Relevant osu!-side permissions have been moved over. Theme is changed to a pure black one, so we don't get the ugly gradient at startup. Added some relevant config changes, so the activity doesn't unwantedly get restarted.
=> Standardize Android activity and permissions

osu.Framework.Benchmarks/BenchmarkLogger.cs, osu.Framework/Logging/Logger.cs
Came up while I was profiling the test threading issue, and I couldn't help myself (sorry). While running tests, logger overhead is around 10% so seems quite beneficial.
I believe we used to have something along the lines of this, but switched to scheduling the full stream operation for some reason or another.
Before:
|                Method |         Mean |      Error |     StdDev |      Gen 0 |     Gen 1 |  Allocated |
|---------------------- |-------------:|-----------:|-----------:|-----------:|----------:|-----------:|
|     LogManyLinesDebug |     1.256 ms |  0.0160 ms |  0.0133 ms |   89.8438  |         - |   1,016 KB |
| LogManyMultiLineLines | 1,457.323 ms | 27.5232 ms | 43.6547 ms | 11000.0000 | 1000.0000 | 128,522 KB |
|          LogManyLines | 1,384.930 ms | 27.5977 ms | …
=> Avoid doing individual file operations for each line of log output

osu.Framework/Logging/LoadingComponentsLogger.cs
Still have a suspicion this is the issue we are seeing with the "stuck ready" test failures osu! side.
=> Add logging of TPL threadpool state on test failures

osu.Framework.Benchmarks/BenchmarkWeakList.cs, osu.Framework/Lists/WeakList.cs
@peppy Please re-test this with your scenario, as the previous code used Gen2 GC callbacks.
This change will trim the `WeakList<T>` once the number of items changed (either added to increase the count of the list or removed) since the last trim crosses a threshold of 100. It is aimed to fix cases where many items are added and removed from `WeakList<T>` without an enumeration ever taking place.
Baseline measurements:
```
|                                      Method | ItemCount |               Mean |            Error |           StdDev |     Ratio | RatioSD |        Gen 0 |        Gen 1 |        Gen 2 |    Allocated |
|-------------------------------------------- |---------- |-------------------:|-----------------:|-----------------:|----------:|--------:|-------------:|-------------:|---- …
```
=> Opportunistically trim WeakList<T> on additions after many removals or additions

osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Logging/LoadingComponentsLogger.cs
There is no reason for this to be run asynchronously. It's a lean continuation and has no user code. This should improve performance of async load tasks as there is one less thread transition.
It also means if the TPL thread pool is saturated, drawables will still load. This may in turn cause unblocking of other threads in the thread pool (due to bad user implementations in drawable load code, for instance) and avoid potential deadlocks.
This should 100% resolve the `TestMultiplayer` failures where screens are stuck in a `Ready` but not `Loaded` state.
It does *not* fix the actual TPL saturation in said case, which is likely due to bad `async` implementation (ie. a `.Wait()` waiting on a blocking `Task.Run`). Haven't pinpointed yet but am going through all usages systematically. …
=> Fix `LoadComponentAsync` running load continuation asynchronously

osu.Framework/Graphics/BufferedDrawNodeSharedData.cs, osu.Framework/Graphics/DrawNode.cs, osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs, osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs, osu.Framework/Graphics/OpenGL/GLDisposalQueue.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Shaders/Shader.cs, osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Graphics/Shaders/ShaderPart.cs, osu.Framework/Graphics/Video/VideoTexture.cs
Testing at song select since that's where I noticed it the most (`DrawNode` specifically).
Before:
After:
Of note, the delegate overhead is gone. The remaining allocation cost is from `PendingDisposal`. Could theoretically make is a `struct`, but due to the generic `T`, it would incur one boxing cast for the interface. Not sure it's worth that. For `DrawNode` the invocation is always inline, so `PendingDisposal` is never constructed, so that particular case is fixed 100%.
=> Reduce allocation overheads on all GL disposal paths

osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs, osu.Framework/Graphics/Pooling/PoolableDrawable.cs, osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Threading/ScheduledDelegate.cs, osu.Framework/Threading/ScheduledDelegateWithData.cs, osu.Framework/Threading/Scheduler.cs
Tested at osu! song select while scrolling. I've only addressed the cases which are excessive for now.
Before:
After:
Main targets are `DelayedLoadWrapper` and mouse movement.
Note that `DelayedLoadWrapper` still allocates quite a few `ScheduledDelegateWithData`, but this is harder to avoid. Still an improvement.
=> Reduce delegate allocation overheads

osu.Framework/Platform/SDL2DesktopWindow.cs
As discussed in https://github.com/ppy/osu-framework/pull/4969#issuecomment-1001160919.
Remaining things that are scheduled to the `eventScheduler`:
- [`storeWindowSizeToConfig()`](https://github.com/Susko3/osu-framework/blob/54fa49710ee92bd17d91fdc7ea257ace5229c53f/osu.Framework/Platform/SDL2DesktopWindow.cs#L481-L483) - rationale in inline comment
- in [`RequestClose()`](https://github.com/Susko3/osu-framework/blob/54fa49710ee92bd17d91fdc7ea257ace5229c53f/osu.Framework/Platform/SDL2DesktopWindow.cs#L494) - could be a `ScheduleCommand()`, but probably scheduled as event to possibly remove one frame of delay when closing (untested)
- [`TriggerMouseWheel` in `MacOSWindow`](https://github.com/Susko3/osu-framework/blob/54fa49710ee92bd17d91fdc7ea257ace5229c53f/osu.Framework/Platform/MacOS/MacO …
=> Don't fake-schedule SDL events

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/IO/Network/FileWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
Would have liked to split into synchronous and asynchronous paths completely, but can't be done until https://github.com/dotnet/runtime/pull/45300 is available to use (.net 6) as we depend on it for IPv4 fallback.
=> Fix multiple deadlock cases in `WebRequest`

osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Android/AndroidGameHost.cs, osu.Framework.Android/AndroidGameView.cs, osu.Framework.Android/Input/AndroidInputExtensions.cs, osu.Framework.Android/Input/AndroidInputHandler.cs, osu.Framework.Android/Input/AndroidKeyboardHandler.cs, osu.Framework.Android/Input/AndroidMouseHandler.cs, osu.Framework.Android/Input/AndroidTouchHandler.cs, osu.Framework/Properties/AssemblyInfo.cs
This brings us one step closer to resolving https://github.com/ppy/osu-framework/issues/4373.
In addition to separating mouse from touch events, `AndroidMouseHandler` enables the following:
- support for all mouse buttons (including forward and back)
- support for scrolling
- starting point for implementing [pointer capture](https://github.com/ppy/osu-framework/issues/4373#issuecomment-836278499).
---
Tested on Realme 6, Android 11 (API 30) with a bluetooth mouse.
On-screen keyboard input works as expected.
Test works with:
Test existing behaviour isn't broken for:
=> Improve Android mouse input and restructure Android input handlers

osu.Framework/Audio/AudioManager.cs
Main goal here is to allow viewing the helpful xmldoc attached to the new method calls, rather than be redirected through an enum.  All the lines which haven't been updated don't contain properties on `Bass` for one reason or another (even when they sometimes imply they do).
Also adds some extra log output.
=> Reorder Bass configuration operations and use more direct method calls

osu.Framework/Input/InputManager.cs
While the previous method worked fine, it means that a consumer would not be able to alter the flow of events (ie. blocking the "click" operations by changing the incoming touch).
In osu!, we wish to use this to allow the user to block the "click" portion while still convey movement of the "cursor".
Tested against iOS.
=> Consume touch `IsActive` state rather than checking for "any" touch for mouse mapping

osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs, osu.Framework/Configuration/ConfigManager.cs, osu.Framework/Extensions/ExtensionMethods.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs
Have not addressed `FrameworkConfigManager` input related items yet. They require further attention.
Note that one of these is not obsolete for 9 more days but figured it's easier to batch it here. If we care enough then hold off merge, but probably fine at this point.
=> Remove obsoleted methods/members

osu.Framework.Tests/Bindables/BindableLeasingTest.cs, osu.Framework/Bindables/ILeasedBindable.cs, osu.Framework/Bindables/LeasedBindable.cs
Leases are commonly returned automatically by the framework. One such example is `ScreenStack` (https://github.com/ppy/osu-framework/blob/ceef26fa2675e89937e01b87e2ea40be83d14c58/osu.Framework/Screens/ScreenStack.cs#L349).
We likely do want this automatic cleanup, but it turns out to be very hidden to the end user. If a user attempts to clean up themselves without understanding this detail, it can lead to unexpected failures.
The example that came up is an osu!-side test failure which took 2-3 hours to hunt down the cause. Said example is very well protected against to the point I thought the issue was a threading one, but it turns out it is not: https://github.com/ppy/osu/blob/c6ca0e58956c2d64f69c2d24eef2b87eb0c76e79/osu.Game/Screens/OnlinePlay/Lounge/LoungeSubScreen.cs#L247-L251.
I …
=> Don't throw when returning a leased bindable that has already been returned

CodeAnalysis/BannedSymbols.txt, osu.Framework.Benchmarks/BenchmarkFontLoading.cs, osu.Framework.Tests/Exceptions/TestLoadExceptions.cs, osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework.Tests/Visual/Sprites/TestSceneScreenshot.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/Waveform.cs, osu.Framework/Extensions/TaskExtensions.cs, osu.Framework/Graphics/Audio/WaveformGraph.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/Graphics/Video/VideoDecoder.cs, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/Input/Handlers/Midi/MidiHandler.cs, osu.Framework/Platform/TcpIpcProvider.cs, osu.Framework/Testing/TestScene.cs
As seen recently, it is quite easy in our semi-`async` world to accidentally cause a deadlock in the TPL thread pool. The cause of this is a `.Wait()` or `.Result` from within an already `async` context.
Finding these cases by reading code is quite hard, as they can be nested multiple calls deep. Likewise, I couldn't find an existing analyser that finds such cases (and to some it is considered a non-issue as the thread pool should grow to add new threads when it gets in this state - but for us this can take too long).
This is a proposal to replace all calls with a custom method with added safety. Note that this PR will intentionally fail as it points out the issues that are fixed in https://github.com/ppy/osu-framework/pull/4973.
The rationale for this change was that I couldn't cover all …
=> Replace all usages of `Task.Wait`/`Task.Result` with safer alternatives

osu.Framework.Tests/Visual/UserInterface/TestSceneClosableMenu.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneUnclosableMenu.cs, osu.Framework/Testing/MenuTestScene.cs
`MenuTestScene` was overly rigid to the point wherein you *had* to share one single menu with a single configuration for all tests in a file which is kind of wasteful and difficult to work with. You can't, for instance. switch the direction of the menu, without creating a whole separate test scene for that.
This changes that by exposing the set-up of `MenuTestScene` members to inheritors via a `CreateMenu()` method rather than hard-coupling the entire test fixture to a given menu via `[SetUp]`.
I need this for tests for a fix to #3861 (coming shortly after this).
=> Refactor menu test scenes to be less rigid

osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework/Extensions/TaskExtensions.cs
Closes https://github.com/ppy/osu/issues/16396#issuecomment-1008687513.
Not 100% sure on this since long running tasks shouldn't really be run within `Task.Run` in the first place, but let's make things work again for the time being.
=> Allow waiting on tasks which were created with `LongRunning` regardless of thread

osu.Framework/Platform/SDL2/SDL2Extensions.cs, osu.Framework/Platform/SDL2/SDL2Structs.cs, osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Platform/Windows/Native/Imm.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
SDL2 text input shows some problems, mainly the 10 character limit and selection not working properly.
Existing issues on SDL's side: https://github.com/libsdl-org/SDL/issues/1879 and https://github.com/libsdl-org/SDL/issues/3385.
So I decided to write my own implementation for Windows IME handling. This is completely transparent to `TextBox` and even to `SDL2DesktopWindowTextInput`. The composition text is no longer arbitrarily limited, and selection works as expected.
It's unfortunate that we can't use `SDL_SetWindowsMessageHook` as we do in [`WindowsMouseHandler`](https://github.com/ppy/osu-framework/blob/6a2250ee584f1e38601b5cdb4b7397d27f730304/osu.Framework/Platform/Windows/WindowsMouseHandler.cs#L40) (reasoning: eb44a5c44aa43a383ef671c8b82759c14a92900e). Seems a bit strange that …
=> Add native Windows IME support

osu.Framework.Android/Input/AndroidTextInput.cs, osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework.iOS/Input/IOSTextInput.cs, osu.Framework/Graphics/UserInterface/BasicPasswordTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/SDL2DesktopWindowTextInput.cs, osu.Framework/Input/TextInputSource.cs, osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Platform/Windows/Native/Imm.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
Adds a new option `AllowIme` to `TextBox` that can be used to disallow/disable the IME when that text box has focus. (Currently, the IME will always be active/allowed.)
This is useful for situations where IME input is not wanted, such as for passwords, numbers, romanised text, etc.
Currently only works on windows.
=> Add option to disallow IME to `TextBox`

osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs, osu.Framework/Graphics/UserInterface/Menu.cs
- Fixes #3861
https://user-images.githubusercontent.com/20418176/148696343-f1198d58-0aaa-49be-910c-c227abacf608.mp4
PRing primarily for comment.
This implementation mirrors observed behaviour of most nested menus that I could find, namely that determining whether to flip a menu or not happens locally to the given menu level (i.e. even if the parent menu is right-aligned to its parent's left side, the child menu of that can be left-aligned again if there is enough space).
The contentious part of this may be that I'm using `GetContainingInputManager()` to perform this positioning. This is done because the menu's parent is not necessarily its clipping bounds. And it's not like the menu *has* to have a parenting `ContextMenuContainer` or other drawable to work correctly. So clipping to the …
=> Fix nested menus overflowing past screen bounds

osu-framework.sln.DotSettings, osu.Framework.Benchmarks/BenchmarkDependencyContainer.cs, osu.Framework.Tests/Dependencies/DependencyContainerTest.cs, osu.Framework.Tests/Visual/Testing/TestSceneAudioMixerVisualiser.cs, osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs, osu.Framework/Graphics/Video/Video.cs, osu.Framework/Graphics/Video/VideoSprite.cs, osu.Framework/Graphics/Visualisation/LogOverlay.cs, osu.Framework/Testing/TestBrowser.cs
Adds `ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature` to `[MeansImplicitUse]` attribute for BDL.
The flag does exactly what we'd want, the BDL method itself is treated as used implicitly, but the params are not.
"More" info on jetbrains' site:
https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ImplicitUseKindFlags
Discussed shortly on [discord](https://discord.com/channels/188630481301012481/589331078574112768/931314763718340628).
=> Change `[MeansImplicitUse]` attribute on BDL so that unused params are treated as such

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Logging/Logger.cs, osu.Framework/Threading/Scheduler.cs
This intends to expose cases of schedulers being enqueued to but not running, which is something that has come up in the past and can cause unforeseen overheads or memory leaks.
Would be nice if we could better identify the owner of the scheduler, but not sure it's worth passing a reference in to the drawable or not. Can be added if that's seen as a requirement.
=> Output performance log messages when schedulers have long queues

osu.Framework/Graphics/Video/VideoDecoder.cs
When using the AVFormatContext calculated duration, cast AV_TIME_BASE to double to avoid rounding that could result in an inaccurate duration.
=> Avoid rounding when calculating video duration

osu.Framework/Graphics/OpenGL/GLWrapper.cs
Fixes https://github.com/ppy/osu-framework/issues/5000
The most simple fix because I don't expect performance to be impacted as a result of potentially one redundant `glBindTexture` call.
=> Fix texture bind early return bypassing glActiveTexture()

osu.Framework/Graphics/Drawable.cs
Usually we'd avoid this level of micro optimisation, but this was showing up when assessing remaining song select performance concerns and seems like a no-brainer fix (the list is safe as it cannot be used post-load).
If this requires any thought beyond a quick merge then closing is fine. Had this left over from a profiling session.
(removes the `MoveNext` overhead at 18% of invalidation flow)
=> Use `for` loop instead of `foreach` for critically hot path in invalidation

osu.Framework.iOS/GameViewController.cs
Not much to say. Works as one would expect. I think making this default behaviour is fine until a framework consumer requests otherwise (we are already doing the same for the status bar).
=> Hide iOS home indicator when possible

osu.Framework/Graphics/Containers/SafeAreaDefiningContainer.cs
As mentioned in https://github.com/ppy/osu/pull/16772#discussion_r799393996. Changes from the `host.Window.SafeAreaPadding` bindable are scheduled to the update thread instead of unsafely propagating them down the drawable hierarchy (also moved to `LoadComplete` becuase we probably don't want to bind on BDL?).
=> Improve `SafeAreaDefiningContainer` bindable callback thread safety

osu.Framework/Platform/Linux/SDL2/SDL2Clipboard.cs
The code existed in late 2018, way back before SDL2 was fully implemented to osu!framework. Seems it can now directly use the `SDL2` wrapper and simplify linux clipboard code.
Would appreciate testing this as I'm slightly hesitant about this given it's linux but I'm not sure about just leaving it behind.
=> Remove no longer required SDL2 P/Invokes in Linux clipboard

osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs, osu.Framework/Input/InputManager.cs
- Resolves https://github.com/ppy/osu/discussions/16797
- See https://github.com/ppy/osu/discussions/16797#discussioncomment-2120029 for the reason behind this, which led to this PR.
=> Fix `InputManager.ChangeFocus()` potentially switching focus to an invalid target

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownFencedCodeBlock.cs
Fixes https://github.com/ppy/osu/issues/16808
It still draws the background, which looks to be expected for this sort of input (tested via both dillinger.io and github).
=> Fix crash with empty markdown fenced code blocks

osu.Framework.Android/AndroidGameView.cs, osu.Framework.Android/AndroidGameWindow.cs
Superseded https://github.com/ppy/osu-framework/pull/5012.
Tested on:
- Realme 6 / RMX2001 (Android 11 / API 30)
- LG G7 Fit / LG-Q850EMW (Android 9 / API 28)
- LG G Pad 8.3 / LG-V500 (Android 8.1 / API 27)
Testing methodology involves using multi-window and trying out different screen orientations.
Some of the extra code (compared to the original PR) seems to be working around a platform issue with my main device (Realme 6), as the original PR works just fine on the LG G7 Fit 🙃
At least we got non-complaint devices covered.
Anyways, I feel much safer calculating all the insets on the screen area, and then intersecting with the view at the very end.
=> Implement `SafeAreaPadding` on Android

SampleGame.Android/SampleGame.Android.csproj, osu.Framework.Android.props, osu.Framework.Android/osu.Framework.Android.csproj, osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
Sample of the warnings we currently get:
- C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(434,3): Warning XA0119 : Using fast deployment and the linker at the same time is not recommended. Use fast deployment for Debug configurations and the linker for Release configurations.
- The docs also suggest to `<UseInterpreter>true</UseInterpreter>` for hot reload support, but this makes the game really laggy.
- C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(400,5): Warning XA0125 : 'osu.Framework.Tests.Android.pdb' is using a deprecated debug information level.
Set the debugging information to Portable in the Visual Studio project property pages or edit the project file …
=> Bring Android build to zero warnings and cleanup configuration

.vscode/launch.json, .vscode/tasks.json
With the recent bump to .net6, the vscode launch tasks needed to be updated to accommodate.
I've also added tasks for SampleGame, and a build task for the benchmark project.
=> Update vscode launch tasks

osu.Framework.Android/Input/AndroidMouseHandler.cs
Closes #5030.
All the other events in `AndroidMouseHandler` have been added prior to API 21 and as such do not require their own guards.
@Susko3 please test that this doesn't regress any mouse capture functionality from #4989 as I lack the requisite hardware.
=> Don't subscribe to pointer capture events on unsupported Android devices

osu.Framework.Tests/Extensions/TestStreamExtensions.cs, osu.Framework/Extensions/ExtensionMethods.cs, osu.Framework/Extensions/StreamExtensions.cs, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/IO/Stores/DllResourceStore.cs, osu.Framework/IO/Stores/StorageBackedResourceStore.cs, osu.Framework/Platform/TcpIpcProvider.cs
Based loosely around the solution proposed [here](https://stackoverflow.com/a/221941).
The only thing I'm not 100% on is whether we should use the `EndOfStreamException` here as there could be a super edge case where a stream reads past the end of the expected length? Not sure that will ever happen though.
=> Create helper methods to ensure stream reads are read correctly to the expected length

osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Android/AndroidGameHost.cs, osu.Framework.Android/Input/AndroidKeyboardHandler.cs, osu.Framework.Android/Input/AndroidTextInput.cs, osu.Framework.Tests.Android/TestGameActivity.cs
5161624f036e68e82672a6232b2579964dce6bbb **Use correct lifecycle methods for suspending and resuming host**
- the host would get suspended (even it was visible) when using split-screen on older android version (in Android 9 and lower) https://source.android.com/devices/tech/display/multi_display/multi-resume
- more info: https://developer.android.com/guide/components/activities/activity-lifecycle#alc - the image explains it well
dac31eb47340ca40ee52ad6a5565fa09d6d60783 **Always hide the status bar**
- we don't really support showing the status bar right now, so it's best to always hide it
- this matches iOS system bars behaviour
- can be revisited in the future if there is demand for showing it
=> Cleanup Android (and use fullscreen by default)

osu.Framework.Android/AndroidGameView.cs
Width and Height default to the ones in `GameViewBase`, no wonder they were invalid.
Since the native View properties are valid on creation, we can update earlier.
=> Use `View` properties instead of osuTK ones for calculating `SafeArea`

appveyor_xamarin_deploy.yml, build/build.cake
Minimal required changes to get nuget packing working again on appveyor.  Basically, xamarin builds need the 2019 image, while net6.0 requires the 2022 image.
Example passing runs:
https://ci.appveyor.com/project/peppy/osu-framework-ecq46/builds/42564987
https://ci.appveyor.com/project/peppy/osu-framework-a4n7e/builds/42565005
=> Add separate build script for xamarin packing

osu.Framework/Extensions/StreamExtensions.cs
Fixes https://github.com/ppy/osu/issues/16900
Network streams block on `.Read()` while awaiting more data. Still not sure on these helpers existing, but I think this change makes sense...
=> Fix potential blocking on stream.Read() when reading exact length

osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs, osu.Framework/Graphics/Containers/SafeAreaContainer.cs
I'm not 100% sure this will provide the correct behaviour when negatively sized. It's hard to tell what the expectation would be in this case (sizing the `SafeAreaContainer` in this manner will give completely unexpected results unless it completely ignores the negative component... since the intention of these containers is to handle device edge scenarios).
Fixes https://github.com/ppy/osu-framework/issues/5015.
=> Fix crash in `SafeAreaContainer` when working with negative sizing

osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs, osu.Framework/Graphics/UserInterface/Menu.cs
Fixes https://github.com/ppy/osu/issues/16953
I have other fixes/cleanups to this class coming up, but I want to test them out a little bit more while fixing the root cause of this issue.
The cause of this issue is that osu!-side menus fade out when closed: https://github.com/ppy/osu/blob/ebdffb3cd91e89466c0c6c00dcdbb8da814ee4e5/osu.Game/Graphics/UserInterface/OsuContextMenu.cs#L61-L69, and so when another Drawable is clicked and the parent menu is "transferred" to it (i.e. it adopts that new Drawable's elements) there is a period of time where the submenu is fading out and receiving updates.
During this time, if the submenu tries to reposition itself beside the `MenuItem` which opened it, it would be doing so with a Drawable that doesn't exist and would receive an undefined position. If …
=> Fix sub-menu getting an invalid position when parent menu is transferred to another drawable

osu.Framework.NativeLibs/runtimes/osx/source/ffmpeg/fetch_and_build.sh
Generally advised against, and codefactor was complaining.
=> Don't use backtick syntax for inline command running in ffmpeg build script

osu.Framework/Platform/SDL2DesktopWindow.cs
This used to work and likely regressed with the SDL implementation at some point.  Note that this implementation is MVP and may not work in certain configurations or on certain platforms, but is better than nothing (in theory).
See https://github.com/ppy/osu-framework/issues/5055.
Worth noting that this is now adding an extra pending mode change request on startup due to the initial trigger flag. In my limited testing this didn't seem to adversely affect anything on windows, but I'd appreciate testing on other platforms (and even on windows to confirm this).
=> Handle changes to `CurrentDisplay` to allow switching active display

osu.Framework/Graphics/UserInterface/Dropdown.cs
Manifested in the following case (`TestSceneFullscreen`):
```csharp
Unhandled exception. osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the Transforms on a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String action) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 2618
at osu.Framework.Graphics.Drawable.EnsureTransformMutationAllowed() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 2589
at osu.Framework.Graphics.Transforms.Transformable.AddTransform(Transform transform, Nullable`1 customTransformID) in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Transforms/Transform …
```
=> Fix dropdown potentially mutating transforms when dealing with async bindable changes

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs
Well aware that I've made this change without prior discussion but this seemed like an obvious fix.
Before:
https://user-images.githubusercontent.com/8362491/156944239-5074b07e-1542-4a6b-bd84-c1fbc213d14e.mp4
After:
https://user-images.githubusercontent.com/8362491/156944232-c32eba55-34e8-48b6-9791-84361411b2e2.mp4
=> Ensure scrollbar respects `ScrollContainer` padding

osu.Framework.Tests/Graphics/TestSceneDrawableScheduling.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
In master, performing `Drawable.Schedule` with no transform delay prior to a regular `Scheduler.Add` does not make it execute in order, as the first gets enqueued to `timedTasks` while the second gets enqueued to `runQueue` directly, causing the second to execute before the first.
At first I was going to resolve this by making `Scheduler.AddDelayed(..., 0)` enqueue to `runQueue` directly, but looking at it again, I felt that to be weird and unnecessary logic compared to updating usages itself to use `Add` if there's no delay.
I'm honestly not sure which to pick at this point. For reference, here's a branch of the alternative direction (https://github.com/frenzibyte/osu-framework/compare/drawable-schedule-no-delay).
=> Fix potential out-of-order execution with `Drawable` scheduling method

osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs, osu.Framework.iOS/Graphics/Video/IOSVideoDecoder.cs, osu.Framework/Graphics/Video/FFmpegFuncs.cs, osu.Framework/Graphics/Video/Video.cs, osu.Framework/Graphics/Video/VideoDecoder.cs, osu.Framework/Graphics/Video/VideoTexture.cs, osu.Framework/Graphics/Video/VideoTextureUpload.cs
This fixes some issues I noticed in a simple video playback program using osu-framework.
1. If `UploadComplete` was false on the first attempt to display a frame, it wouldn't retry even after `UploadComplete` became true.
2. The check in `Video` to see if there was a seek after the video had finished would fire before the video was actually done playing, causing the video to jump around at the end. This was 2 issues. First, while the decoder state was EOF there could still be available frames. Second, checking if `PlaybackPosition` is less than `VideoDecoder.Duration` will be true even after the last frame is shown.
3. `Video` would not show the last couple frames or only return them after a seek.  This was because the decoder was not flushed on EOF.
=> Video playback and decoding fixes

osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
Closes #5060.
Additionally adds relevant test step to `TestSceneFullscreen` for testing convenience but it's a bit useless for CI which runs headless and therefore is not able to check anything window-related.
=> Set default of `CurrentDisplayBindable` to primary display

osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/IWindow.cs, osu.Framework/Platform/OsuTKWindow.cs, osu.Framework/Platform/SDL2DesktopWindow.cs
Related: https://github.com/ppy/osu/issues/16956.
[SDL_SetWindowMouseRect](https://wiki.libsdl.org/SDL_SetWindowMouseRect) works quite well on Windows. Using the mouse rect and relative mode at the same time is intentionally avoided in case of SDL2 bugs (there were some weird bugs with it when I checked some time ago).
To verify this works on macOS and Linux, I suggest the following testing methodology;
- enable `ConfineMouseMode` and `cursor confine rect`
- verify the cursor is confined to the expected area (check the OS cursor with `Toggle cursor visibility`)
- check that toggling relative mode doesn't warp the cursor in any way (keep in mind that relative mode will not work with the OS cursor shown)
- repeat for other window modes
- also test that it works with display scaling != 100%
=> Add a way to confine the mouse cursor to a specific window area

osu.Framework/Platform/SDL2DesktopWindow.cs, osu.Framework/Platform/Windows/WindowsWindow.cs
Closes https://github.com/ppy/osu-framework/issues/3456.
Goals for this change
---
1. have the hack not be noticeable by multi-monitor users
- partially resolved, will now show black instead of bleeding the game over. would be great if the pixels could be transparent
2. render the game at display resolution
3. don't cause off-by-one errors (eg. in mouse input, when translating game coordinates to window/screen space)
4. don't break things reliant on window size, such as screenshots
5. still prevent windows or drivers from putting the game in exclusive fullscreen
Implementation/changes
---
Will now only increase the window width by 1px (as opposed to both width and height, in addition to offsetting the window position). This is done to satisfy 2. and 3. while keeping 5.
Modifying the …
=> Improve the Windows borderless hack

osu.Framework.Tests/Visual/Containers/TestSceneCompositeDrawable.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs
Closes #5064 
A similar case can be seen with `FlowContainer`'s layout transform, but that's more involved as the transforms are applied to the children, which makes catching them in `FlowContainer.ClearTransformsAfter` not enough to avoid the issue there (since the transform can still be cleared by the child itself).
=> Fix `ClearTransforms` potentially discarding container autosizing

osu.Framework/Graphics/Video/VideoDecoder.cs
Closes #4857
If any FFmpeg function that works with HW decoding fails with an unexpected error, HW decoding is disabled for the current "decoding session". If the error is `ENOMEM` then HW decoding is also disabled at framework config level.
I only tested this manually with the following patch:
```csharp
diff --git a/osu.Framework/Graphics/Video/VideoDecoder.cs b/osu.Framework/Graphics/Video/VideoDecoder.cs
index 8dd912716..b563d754f 100644
--- a/osu.Framework/Graphics/Video/VideoDecoder.cs
+++ b/osu.Framework/Graphics/Video/VideoDecoder.cs
@@ -534,6 +534,12 @@ private int sendPacket(AVFrame* receiveFrame, AVPacket* packet)
// send the packet for decoding.
int sendPacketResult = ffmpeg.avcodec_send_packet(codecContext, packet);
+            if (codecContext->hw_device_ctx != null && …
```
=> Disable HW video decoding if an unexpected error occurs

osu.Framework.Android/AndroidGameHost.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/HeadlessGameHost.cs, osu.Framework/Platform/NativeStorage.cs, osu.Framework/Platform/Storage.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs
Mobile platforms were throwing `NotImplementedException` for these methods, which is very easy to overlook. Providing a return code makes it very clear that it is not guaranteed that these method will result in success.
Closes https://github.com/ppy/osu-framework/issues/5073.
=> Change signature of `OpenFileExternally` and `PresentFileExternally` to gracefuly fail
