osu.Framework/Game.cs
=> Added Exit method

osu.Framework/Audio/Sample/SampleManager.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/MathUtils/RNG.cs, osu.Framework/osu.Framework.csproj
Some prerequisites for my continued work on TextBox and SpriteText.
=> General fixes

osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/Resources/GlyphStore.cs, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
SharpText -> BMFont.
https://github.com/peppy/osu-new/commit/29470f6318f4a89b4d3c10e6baa9aa6219a0399a for full example.
=> Texture based glyph support

osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Sample/SampleManager.cs, osu.Framework/Audio/Track/TrackManager.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/Resources/ResourceStore.cs
Some changes to get things working as they should do.
=> General improvements to ResourceStore.

osu.Framework.Desktop/Input/BackingTextBox.cs, osu.Framework.Desktop/Input/ImeTextBox.cs, osu.Framework.Desktop/OS/DesktopGameWindow.cs, osu.Framework.Desktop/OS/Linux/LinuxGameHost.cs, osu.Framework.Desktop/OS/Windows/WindowsGameHost.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework/Framework/BasicGameHost.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/TextInputSource.cs, osu.Framework/osu.Framework.csproj
Text input is handled by creating a winform textbox on desktop platforms. Until now this wasn't present in the new framework.
Fulfills the requirements of getting text into TextBoxes (subsequent PR in osu repo).
=> Implement TextInputSource

osu.Framework.Desktop/OS/DesktopGameWindow.cs
Quick fix for osu framework
Fixing creating a window with no resolution.
=> Fixing window with no window size

osu.Framework/Game.cs, osu.Framework/Graphics/Performance/FpsDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/osu.Framework.csproj
merge or wait for more, your call.
=> Add basic FPS display for update/draw loops.

osu.Framework/Timing/ThrottledFrameClock.cs
Getting rid of unused locals, and minor restructuring of code to aid readability.
=> Refactor ThrottledFrameClock's ProcessFrame().

.travis.yml, osu-framework.sln, osu.Framework.Tests/Lists/TestSortedList.cs, osu.Framework.Tests/MathUtils/TestInterpolation.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework.Tests/packages.config
=> Add test suite and some simple tests, take 2

osu.Framework.Desktop/OS/Windows/TimePeriod.cs, osu.Framework.Desktop/OS/Windows/WindowsGameHost.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj
Not sure if we should restore the period `OnDeactivated` `OnActivated`.. opinions?
=> Add adjustment for the winmm timer frequency during runtime.

osu.Framework.VisualTests/Tests/FieldTest.cs, osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/Graphics/Containers/AutoSizeContainer.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Transformations/TransformColour.cs, osu.Framework/Graphics/Transformations/TransformFloat.cs, osu.Framework/Graphics/Transformations/TransformVector.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/MouseState.cs
Only supports scrollbar based scrolling for now.
=> Scroll container

osu.Framework/Extensions/IEnumerableExtensions/IEnumerableExtensions.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Lists/LifetimeList.cs, osu.Framework/Lists/SortedList.cs, osu.Framework/osu.Framework.csproj
Suggestions? Comments? Yay or nay?
=> Enumerable children

osu.Framework/Game.cs, osu.Framework/GameModes/GameMode.cs, osu.Framework/Graphics/Containers/AutoSizeContainer.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/LargeContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs
Not sure if AddTarget should be at `Drawable` or `Container`.
=> Remove ProcessingContainer

osu.Framework/Cached/Cached.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/AutoSizeContainer.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/ProcessingContainer.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/OpenGL/Textures/TextureUpload.cs, osu.Framework/Graphics/Performance/FpsDisplay.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Lists/LifetimeList.cs, osu.Framework/OS/BasicGameHost.cs, osu.Framework/Statistics/FrameStatistics.cs, osu.Framework/Statistics/PerformanceCollectionPeriod.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/osu.Framework.csproj
Please merge https://github.com/ppy/osu-framework/pull/60 first.
=> Frame time display

osu.Framework/Input/Handlers/Mouse/CursorMouseHandler.cs, osu.Framework/OS/BasicGameHost.cs, osu.Framework/Threading/Scheduler.cs
=> Run cursor position updates on the input thread

osu.Framework.Desktop/OS/Windows/TimePeriod.cs, osu.Framework/Allocation/BufferStack.cs, osu.Framework/Allocation/InvokeOnDisposal.cs, osu.Framework/Allocation/ObjectStack.cs, osu.Framework/Extensions/IEnumerableExtensions/IEnumerableExtensions.cs, osu.Framework/Graphics/OpenGL/Textures/TextureUpload.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/OS/BasicGameHost.cs, osu.Framework/Statistics/FrameStatistics.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/osu.Framework.csproj
Minor restructuring + less heap allocation / garbage collects.
=> General improvements

osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
=> Fix obsolete tk calls.

README.md
Wanted to add this to set a general understanding of why this framework isn't as bare-bones as many people are expecting.
=> Add objectives section to readme.

osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/Sprites/SpriteCircular.cs, osu.Framework/Input/UserInputManager.cs
```Drawable.Contains()``` is now a public Method
=> Key Counter necessary changes/additions

osu.Framework.VisualTests/Benchmark.cs, osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs, osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs, osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework.VisualTests/VisualTestGame.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/osu.Framework.csproj
Keeping it simple for now. This class will receive a lot of new functionality in the next pass.
=> Add TestBrowser: a new reusable test loader/browser mode.

osu.Framework/Audio/AdjustableAudioComponent.cs, osu.Framework/Audio/AudioCollectionManager.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/Graphics/Containers/AutoSizeContainer.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Lists/LifetimeList.cs
A WIP to move Children out of Drawable for clarity. Currently hitting an assert we shouldn't be in `Invalidation`. Haven't figured out why yet; feedback is welcome.
=> Move children to container

osu.Framework/Input/IKeyboardState.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/KeyboardState.cs
Some Chinese IME related issues are solved magically.
=> Treat Win key as a modifier.

osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
This fixes elements not being removed from the DrawVisualiser when they have been removed from the DrawNode tree. It also adds weird issues with autosize, but these are unrelated and need to be fixes elsewhere.
=> Changes to DrawVisualiser to avoid some weird rendering bugs

osu.Framework.VisualTests/Tests/TestCaseGameMode.cs, osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/GameModes/GameMode.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Containers/ClickableContainer.cs
A simple test of stacking game modes on top of each other.
Request for comment, but good for merge too.
=> Improve GameMode and add TestCase.

osu.Framework/Audio/Track/AudioTrackBass.cs, osu.Framework/Cached/Cached.cs, osu.Framework/IO/AsyncBufferStream.cs, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/IO/Stores/ResourceStore.cs, osu.Framework/Threading/SleepHandle.cs
`GlyphStore` changes reverted. Only exception changes here now.
=> General tidy ups

osu.Framework.Desktop/OS/Linux/LinuxGameForm.cs, osu.Framework.Desktop/OS/Linux/LinuxGameWindow.cs, osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs, osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Textures/Png/LICENSE.txt, osu.Framework/Graphics/Textures/Png/PngCommon.cs, osu.Framework/Graphics/Textures/Png/PngReader.cs, osu.Framework/Graphics/Textures/Png/ZlibStream.cs, osu.Framework/Graphics/Textures/PrefixTextureStore.cs, osu.Framework/Graphics/Textures/RawTexture.cs, osu.Framework/Graphics/Textures/RawTextureLoaderStore.cs, osu.Framework/Graphics/Textures/TextureLoader.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/Lists/LifetimeList.cs, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
Can someone run this on Windows and show what it looks like? It doesn't look perfect on Linux but if it's good on Windows then that's fine for the moment.
If it's crappy on Windows my next step will be to just call ImageMagick directly. But that will require DllImport in osu-framework, which I guess we're trying to avoid.
=> Fix font rendering on Linux

osu.Framework.Desktop/Input/Handlers/Keyboard/FormKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/CursorMouseHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/FormMouseHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs, osu.Framework.Desktop/OS/DesktopGameHost.cs, osu.Framework.Desktop/OS/Linux/LinuxGameHost.cs, osu.Framework.Desktop/OS/Windows/WindowsGameForm.cs, osu.Framework.Desktop/OS/Windows/WindowsGameHost.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework/Input/Handlers/IKeyboardInputHandler.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/OS/BasicGameHost.cs, osu.Framework/osu.Framework.csproj
- Fixes reported low mouse update rates on linux.
- Makes the input handler subsystem more flexible.
- Simplifies and tidies the desktop implementation classes.
=> Per-platform Input Handlers

osu.Framework.VisualTests/Tests/TestCaseNestedHover.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj
might as well add this back before it's lost
=> Add back TestCaseNestedHover.

osu.Framework.VisualTests/Tests/TestCaseNestedHover.cs, osu.Framework.VisualTests/Tests/TestCasePadding.cs, osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/Game.cs, osu.Framework/GameModes/GameMode.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Containers/AutoSizeContainer.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/PaddingContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/DrawVisualiser.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/osu.Framework.csproj
=> PaddingContainer

osu.Framework.Desktop/Input/Handlers/Keyboard/FormKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/CursorMouseHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/FormMouseHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/BasicGameHost.cs
Makes more sense to have it here, and allows handling of key events in Game implementations directly.
=> Move UserInputManager to a host level.

osu.Framework/Graphics/Drawable.cs
Fixes regression in background stack management.
=> Add ugly (but stable) stable comparer.

osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Sprites/SpriteText.cs
- Fixes TextSize changes not invalidating properly.
- Refactors how ChildScale is set to match other Child* properties.
=> ChildScale improvements

osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/InputManager.cs
Can't reproduce any issues anymore. Likely got addressed by our other invalidation improvements.
=> Get rid of hacky Cached bypass.

osu.Framework/Graphics/UserInterface/TextBox.cs
Fixes https://github.com/ppy/osu-framework/issues/124
=> Fix incorrect behavior of doubleclick+drag in text boxes.

osu.Framework/Graphics/Containers/OverlayContainer.cs, osu.Framework/osu.Framework.csproj
Consider name and namespace of `enum Visibility`. Comment please if needs change.
=> Move Overlay to framework and rename to OverlayContainer.

osu.Framework.VisualTests/Tests/TestCaseMasking.cs, osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ContainerDrawNode.cs, osu.Framework/Graphics/DrawNode.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/Shaders/ShadedDrawNode.cs, osu.Framework/Graphics/Shaders/ShadedDrawable.cs, osu.Framework/Graphics/Shaders/Shader.cs, osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Graphics/Sprites/Box.cs, osu.Framework/Graphics/Sprites/Sprite.cs, osu.Framework/Graphics/Sprites/SpriteDrawNode.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Resources/Shaders/sh_Colour.vs, osu.Framework/Resources/Shaders/sh_Glow.fs, osu.Framework/Resources/Shaders/sh_TextureRounded.fs, osu.Framework/osu.Framework.csproj
Todo for the future: We need to make it easier to share static shaders among multiple modules. I am not happy with the way ContainerDrawNode just grabs the shader from SpriteDrawNode.
=> Add support for glow around masked regions.

osu.Framework/Graphics/Batches/IVertexBatch.cs, osu.Framework/Graphics/Batches/VertexBatch.cs, osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Graphics/Sprites/Box.cs, osu.Framework/Graphics/Sprites/Sprite.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Graphics/Textures/TextureAtlas.cs, osu.Framework/Graphics/Textures/TextureStore.cs, osu.Framework/Platform/BasicGameHost.cs
Actually batch textures. They used to be but regressed at some point.
=> More batching

osu.Framework/Caching/Cached.cs, osu.Framework/Graphics/Batches/VertexBatch.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/Statistics/FrameStatistics.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Threading/AtomicCounter.cs, osu.Framework/osu.Framework.csproj
The draw hierarchy of FrameStatisticsDisplay may need some revisions.
=> Performance counters

osu.Framework.Desktop.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework.Desktop/Platform/DesktopGameHost.cs, osu.Framework.Desktop/Platform/HeadlessGameHost.cs, osu.Framework.Desktop/Platform/Linux/LinuxGameHost.cs, osu.Framework.Desktop/Platform/Windows/WindowsGameHost.cs, osu.Framework.Desktop/Platform/Windows/WindowsGameWindow.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework.VisualTests/Benchmark.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/Platform/BasicGameWindow.cs, osu.Framework/Threading/GameThread.cs, osu.Framework/Threading/InputThread.cs, osu.Framework/Timing/ThrottledFrameClock.cs, osu.Framework/osu.Framework.csproj
Had to be done.
- New thread model, encapsulating Scheduler, PerformanceMonitor and Clock.
- Draw rate is now set to 4 * RefreshRate.
- Tidied up a lot of code.
- Alt-F4 exits on windows.
- Alt-Enter toggles exclusive fullscreen.
- Ctrl-F7 toggles frame limiters (draw and update).
=> Game thread refactor

SampleGame/SampleGame.csproj, SampleGame/packages.config, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework.Desktop/packages.config, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework.VisualTests/packages.config, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
See https://github.com/ppy/opentk/commit/dcad4aadc59399c99100bf23207aa5b737449d04.
=> Update OpenTK to support exclusive fullscreen on intel GPUs.

osu.Framework.VisualTests/Tests/TestCaseMasking.cs
=> Add smooth variation of CornerRadius to TestCaseMasking.

osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ContainerDrawNode.cs, osu.Framework/Graphics/DrawNode.cs, osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs, osu.Framework/Graphics/Shaders/Shader.cs, osu.Framework/Graphics/Shaders/UniformBase.cs, osu.Framework/Graphics/Sprites/SpriteDrawNode.cs, osu.Framework/Platform/BasicGameHost.cs
Hitting pretty high framerates now. Notably, getting 2.5k FPS while scrolled to the top of the SpriteText test, whereas before these changes there were only 1.3k FPS.
=> Local quad batches

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/IO/Stores/GlyphStore.cs
Quite a naive implementation, but will do for now.
=> Add the ability to specify the font of a SpriteText.

osu.Framework/Graphics/Containers/ScrollContainer.cs
~~~Also makes CheckBox use OnMouseDown.~~~
=> Add ScrollContainer.ScrollIntoView(Drawable)

osu.Framework/Audio/Track/AudioTrackBass.cs
Seems Bass does not provide internal support of difference between 0 and END.
=> Fix implement of AudioTrackBass

osu.Framework/Platform/BasicGameHost.cs
This fixes window size saving behaviors.
Further:
=> Fixes for window sizing issues

SampleGame/SampleGame.cs, osu.Framework.Desktop.Tests/osu.Framework.Desktop.Tests.csproj, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework.VisualTests/Benchmark.cs, osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Performance/FpsDisplay.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Transformations/Transform.cs, osu.Framework/Graphics/Transformations/TransformColour.cs, osu.Framework/Graphics/Transformations/TransformFloat.cs, osu.Framework/Graphics/Transformations/TransformVector.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Graphics/Visualisation/LogOverlay.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Lists/IHasLifetime.cs, osu.Framework/Lists/LifetimeList.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/Timing/FramedClock.cs, osu.Framework/Timing/IFrameBasedClock.cs, osu.Framework/Timing/InterpolatingFramedClock.cs, osu.Framework/Timing/TimeInfo.cs, osu.Framework/osu.Framework.csproj
=> Remove clock

osu.Framework/Resources/Shaders/sh_Texture.fs, osu.Framework/Resources/Shaders/sh_TextureRounded.fs
Also fixes some indentation issues
=> Fix type issue in sh_TextureRounded.fs

osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework.VisualTests/Tests/TestCasePadding.cs, osu.Framework.VisualTests/Tests/TestCaseSmoothedEdges.cs, osu.Framework/BaseGame.cs, osu.Framework/GameModes/GameMode.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/Container_AutoSize.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/IContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/IDrawable.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Visualisation/DrawVisualiser.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/osu.Framework.csproj
open to feedback.
can potentially make an `internal` interface to keep some of the stuff non-public if necessary.
=> Generic FlowContainer.

osu.Framework.VisualTests/Tests/TestCaseBufferedContainer.cs, osu.Framework.VisualTests/Tests/TestCaseColourGradient.cs, osu.Framework.VisualTests/Tests/TestCaseSmoothedEdges.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/Extensions/ColourExtensions/ColourExtensions.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/Graphics/BlendingInfo.cs, osu.Framework/Graphics/ColourInfo.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs, osu.Framework/Graphics/Containers/ContainerDrawNode.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/DrawInfo.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Graphics/Transformations/TransformColour.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/MathUtils/Interpolation.cs, osu.Framework/osu.Framework.csproj
This might look a little over-engineered because it is. It lays some foundation for proper nesting of colour gradients (i.e. container colour gradients) which will work without any additional shader-level features.
=> Colour gradients

osu.Framework/Graphics/UserInterface/TextBox.cs
This allows you to, for example, subclass TextBox and create a bindable
version.
=> Add support code for textbox derivatives

osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework/BaseGame.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
This gets rid of x/y mirroring whenever Right or Bottom Anchors are used, respectively. Also cleans up some code by generalizing the way Anchor coordinates are computed and adds the ability to specify a custom AnchorPosition.
=> Better anchors

osu.Framework/Graphics/Colour/ColourInfo.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ContainerDrawNode.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Transformations/TransformGlowAlpha.cs, osu.Framework/Resources/Shaders/sh_TextureRounded.fs, osu.Framework/osu.Framework.csproj
Also adds ability to trasnform glow alpha.
=> Apply container colour information to border.

osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs
And some minor refactoring that makes the code a bit clearer.
=> Fix local input getting offset by margin.

osu.Framework/Graphics/Colour/ColourInfo.cs, osu.Framework/Graphics/Containers/BufferedContainer.cs, osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/IDrawable.cs, osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/Platform/BasicGameHost.cs
Depends on https://github.com/ppy/osu-framework/pull/329
=> Various fixes

osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs
This disallows certain sketchy things that were previously possible.
=> Container improvements

osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/BaseGame.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/IDrawable.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Platform/BasicGameHost.cs
Also exposes UserInputManager (and its last state) for use in ParallaxContainers (osu!).
=> Fix cursor updates outside window bounds.

osu.Framework/BaseGame.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/Threading/GameThread.cs
This may get rid of the black screen issue some people have when starting up the game. :)
=> Fix threading

osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Sprites/SpriteText.cs
* Adds TransformSpacing for FlowContainers
* Supersedes SpriteText's TransformSpacing
For https://github.com/ppy/osu/pull/202 (Transitions/Animations of buttons on PopUpDialogs and the Song Select options menu)
=> Adds TransformSpacing for FlowContainers

osu.Framework.Desktop/Platform/Windows/WindowsClipboard.cs, osu.Framework.Desktop/Platform/Windows/WindowsGameHost.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Platform/BasicGameHost.cs, osu.Framework/Platform/Clipboard.cs, osu.Framework/osu.Framework.csproj
=> Add clipboard support (windows only).

osu.Framework.Desktop/Platform/TcpIpcProvider.cs
Fix crash import beatmap via IPC
https://github.com/ppy/osu/issues/248
=> Fix length calculation error when str contains unicode character

osu.Framework.VisualTests/Tests/TestCaseDropDownBox.cs, osu.Framework/Graphics/UserInterface/DropDownComboBox.cs, osu.Framework/Graphics/UserInterface/DropDownMenu.cs, osu.Framework/Graphics/UserInterface/DropDownMenuItem.cs
Now more closely matches the model of checkboxes and sliders, where the framework user is expected to provide their own implementation derived from abstract classes.
=> Allow for better customization of dropdowns

osu.Framework/Configuration/BindableLong.cs, osu.Framework/osu.Framework.csproj
I need this for a project I'm working on using this framework, and I see no reason not to include it in the framework.
=> Add BindableLong

osu.Framework.VisualTests/Tests/TestCaseDropDownBox.cs, osu.Framework/Graphics/UserInterface/DropDownComboBox.cs, osu.Framework/Graphics/UserInterface/DropDownMenuItem.cs
At least more cleanly. Technically the old way might work if you
squinted hard enough.
=> Refactor dropdown colors to support DI

osu.Framework.Desktop/Platform/DesktopGameHost.cs
Useful for rapid development of UI when coupled with VisualTests.
=> Add support for automatically reloading framework on a change to the executable assembly.

osu.Framework/Graphics/Containers/ScrollContainer.cs
Fixes weird padding being present when no scrollbar is needed.
=> Only add padding for the scrollbar when the scrollbar is being displayed

osu.Framework/BaseGame.cs, osu.Framework/Configuration/FrameSync.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Graphics/Visualisation/LogOverlay.cs, osu.Framework/osu.Framework.csproj
Depends on https://github.com/ppy/osu-framework/pull/413.
=> Move window size and audio volume configuration to a framework level.

osu.Framework/Graphics/Containers/Container_AutoSize.cs, osu.Framework/Graphics/UserInterface/Button.cs, osu.Framework/Graphics/UserInterface/DropDownComboBox.cs
=> Add transition ability to autosize.

osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/Container_AutoSize.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_Interaction.cs, osu.Framework/Graphics/IDrawable.cs, osu.Framework/Graphics/ProxyDrawable.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Visualisation/DrawVisualiser.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Platform/BasicGameHost.cs
Depends on https://github.com/ppy/osu-framework/pull/432
=> Clean up drawable interaction

osu.Framework/Allocation/DependencyContainer.cs
Bad threading handling was the culprit.
Fixes random crashes on startup.
=> Fix dependency injection randomly failing.

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
=> Invisible characters will now be displayed as boxes.

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
=> Show invisible characters

osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
=> Textbox improvements

osu.Framework/Input/InputManager.cs
InputState was keeping references forever.
=> Memory fixes

osu.Framework.VisualTests/Tests/TestCaseDropDownBox.cs, osu.Framework/Graphics/UserInterface/DropDownMenu.cs
Improves dropdown menus. This branch is based on the audio-device-fix branch and should only be merged after that branch is merged (PR: https://github.com/ppy/osu-framework/pull/436).
If this is undesirable, I can rebase this on master to make the two independent.
=> Dropdown menu change

osu.Framework/Audio/AudioManager.cs, osu.Framework/Extensions/PolygonExtensions/ConvexPolygonExtensions.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Line/Path.cs, osu.Framework/Graphics/Primitives/Quad.cs, osu.Framework/Graphics/ProxyDrawable.cs, osu.Framework/Graphics/Sprites/Sprite.cs
Contains a collection of small incremental fixes and one performance optimization.
=> Small fixes

osu.Framework.VisualTests/Tests/TestCaseAutosize.cs, osu.Framework.VisualTests/Tests/TestCaseCheckBoxes.cs, osu.Framework.VisualTests/Tests/TestCaseScrollableFlow.cs, osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs, osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework/BaseGame.cs, osu.Framework/GameModes/Testing/TestBrowser.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Drawable_TransformationHelpers.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/Graphics/UserInterface/BasicCheckBox.cs, osu.Framework/Graphics/UserInterface/DropDownMenu.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
In the future this can be extended to allowing scroll in both dimensions simultaneously.
Technically, this should already is possible by nesting 2 scroll containers with little changes to how axes are assigned inside scroll containers.
This will be useful for things like the editor timeline.
=> Horizontal scroll

osu.Framework/Configuration/Bindable.cs, osu.Framework/GameModes/Testing/TestCase.cs, osu.Framework/Graphics/UserInterface/Button.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs, osu.Framework/IO/Network/FileWebRequest.cs, osu.Framework/IO/Network/WebRequest.cs
=> HTTP handling improvements & more

osu.Framework.Desktop/Platform/Architecture.cs
It's quite easy to do this, FYI
=> Use RuntimeInfo.IsLinux to check for Linux

osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework/Graphics/Containers/TabbableContainer.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/osu.Framework.csproj
Only added for TextBox, since I was looking at other controls and they don't seem to get focused like TextBoxes do.  Let me know if you think it should be made more generic for all controls.
Tested it with the login form, just need to add:
```
username.TabNext = password;
username.TabPrev = password;
password.TabNext = username;
password.TabPrev = username;
```
=> Allow Tabbing between TextBoxes

osu.Framework.Desktop.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework.Desktop/Platform/DesktopGameHost.cs, osu.Framework.Desktop/Platform/TcpIpcProvider.cs, osu.Framework.VisualTests/Tests/TestCaseOnlineTextures.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/IIpcHost.cs, osu.Framework/Platform/IpcChannel.cs, osu.Framework/Screens/Screen.cs
Also renames Preload to LoadAsync and PerformLoad to Load.
=> Add "Async" suffix to asynchronous methods

osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/TrackManager.cs
- Fix horrible memory leak.
- Don't trigger an exception when stopping a non-running track.
=> Bass fixes.

osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Screens/Screen.cs
Adds disposal logic for InputHandlers.
=> Fix memory leak

osu.Framework/Graphics/Drawable.cs, osu.Framework/IO/Stores/GlyphStore.cs
Reduces startup time by a magnitude or more (osu! game project).
=> Load fonts asynchronously.

osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/PassThroughInputManager.cs, osu.Framework/osu.Framework.csproj
I'll add a VisualTest for this, just PRing for feedback.
=> Add PassThroughInputManager.

osu.Framework.VisualTests/Tests/TestCaseTextBox.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Primitives/MarginPadding.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
I can't believe textbox ever worked.
Also, I can't believe people actually used negative margin and padding.
=> Fix textbox, Prohibit negative Margin and Padding

osu.Framework/Input/InputManager.cs, osu.Framework/Input/KeyboardState.cs, osu.Framework/Input/MouseState.cs, osu.Framework/Input/PassThroughInputManager.cs
=> Fix PassThroughInputManager being able to modify the state of the parent InputManager.

osu.Framework/Graphics/Transforms/TransformFloat.cs, osu.Framework/MathUtils/Interpolation.cs
Also fixes some whitespace/line endings as part of auto-refactor.
=> Add double ValueAt method.

osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/IMouseState.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/InputState.cs, osu.Framework/Input/MouseState.cs, osu.Framework/Input/PassThroughInputManager.cs
=> Add InputState clone logic and storing of an OriginalState.

osu.Framework/Graphics/UserInterface/DropDownMenuItem.cs
> There is some known weird behavior with random items in dropdown becoming invisible until you hover.
from: https://github.com/ppy/osu/pull/455
=> Fixed bug with Foreground colors

osu.Framework/Game.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Sprites/Triangle.cs, osu.Framework/Input/UserInputManager.cs
Avoid constant overriding of Contains just to accept all input.
=> AlwaysReceiveInput

osu.Framework.VisualTests/Tests/TestCaseTabControl.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
and adjust CursorContainer a bit.
=> Add documentation to TabControl.

osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/IDrawable.cs, osu.Framework/Graphics/Sprites/Sprite.cs
Various small fixes of things that previously led to crashes when using DrawVisualiser.
=> Fix drawvis

osu.Framework.VisualTests/Tests/TestCaseOnlineTextures.cs
No more input handling. Also fixes a potential crash.
=> Improve performance of TestCaseOnlineTextures.

osu.Framework/Graphics/UserInterface/Menu.cs
Focus wasn't triggering because IsPresent was early-returning. Adding a schedule does the job.
=> Fix dropdown focus regression.

osu.Framework.VisualTests/Tests/TestCaseFlow.cs, osu.Framework/Graphics/Containers/FillFlowContainer.cs, osu.Framework/Graphics/Drawable.cs
This PR fixes up some regressions and adds new features to the flow test case. Also generalizes fillflow to support arbitrary child origins.
=> Better fill flow

osu.Framework.VisualTests/Tests/TestCaseCheckboxes.cs, osu.Framework.VisualTests/Tests/TestCaseDropdownBox.cs, osu.Framework.VisualTests/Tests/TestCaseFlow.cs, osu.Framework/Graphics/UserInterface/BasicCheckbox.cs, osu.Framework/Graphics/UserInterface/Checkbox.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/DropdownMenuItem.cs, osu.Framework/Graphics/UserInterface/IHasCurrentValue.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/osu.Framework.csproj
SliderBar is an exception as it needs some further work. Will come later.
=> Add IHasCurrentValue interface for UI controls.

osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Screens/Screen.cs, osu.Framework/Threading/Scheduler.cs, osu.Framework/Timing/InterpolatingFramedClock.cs
Still not happy with this overall, but let's stick with it for now as it works.
=> HighFrequencyMousePosition changes

osu.Framework/Configuration/Bindable.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/UserInterface/Checkbox.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs
=> Bindable Disabled propagation

osu.Framework.VisualTests/Tests/TestCaseSizing.cs
=> Fix invalid IL code in tester in class InfofulBoxAutoSize on linux

osu.Framework.VisualTests/Tests/TestCaseParagraph.cs, osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/Graphics/Sprites/Paragraph.cs, osu.Framework/osu.Framework.csproj
=> Add Paragraphs with word-wrap support.

osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Platform/GameHost.cs
=> Add basic nested DI support.

osu.Framework.Desktop/Platform/DesktopGameWindow.cs, osu.Framework.VisualTests/VisualTestGame.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Platform/GameWindow.cs
See https://github.com/ppy/osu-framework/issues/686 for reasoning as to why this isn't 100% support.
Is enough for osu!, fortunately.
=> Add support for confined mouse modes (mostly).

osu.Framework/Configuration/FrameSync.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/GameWindow.cs
The settings may not be final, but this is a step up from nothing.
=> Add support for frame limiters.

osu.Framework/Graphics/UserInterface/TextBox.cs
=> Fix committing being posible when TextBox is disabled.

osu.Framework/Configuration/Bindable.cs
=> Caching and sharing WeakReferences breaks everything

osu.Framework/Input/InputManager.cs
Hover can change even if the mouse has not moved. This should account for that.
=> Always update hover events

osu.Framework/Graphics/Visualisation/LogOverlay.cs, osu.Framework/Logging/Logger.cs
=> Log overlay improvements

osu.Framework/Logging/Logger.cs
The first log file to be written to was never being cleared due to this bug.
=> Ensure we have populated the log directory before clearing

osu.Framework/Graphics/UserInterface/TextBox.cs
Regression from fixing textbox being too greedy with control handling.
=> Fix control key not working for some textbox shortcuts where it should

osu.Framework/Graphics/Containers/SearchContainer.cs, osu.Framework/Graphics/Containers/TabbableContainer.cs
`SearchContainer` can now search by word.
Fix potential fail with other generic type parameters on `TabbableContainer`.
=> Improvements of 2 containers

osu.Framework/Graphics/Drawable.cs
For overriding purposes (I don't want to expose creationId).
=> Give drawable depth comparers virtual compare methods.

osu.Framework/Graphics/Containers/ScrollContainer.cs
=> Further scrollbar fixes

osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs
Fixes keyboard input on macOS (for me, at least).
=> Handle Keyboard events rather than polling

osu.Framework.Desktop/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseHandler.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKMouseState.cs, osu.Framework.Desktop/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs, osu.Framework.Desktop/Platform/DesktopGameHost.cs, osu.Framework.Desktop/Platform/HeadlessGameHost.cs, osu.Framework.Desktop/Platform/Linux/LinuxGameHost.cs, osu.Framework.Desktop/Platform/Windows/WindowsGameHost.cs, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Game.cs, osu.Framework/Input/Handlers/IHasCursorSensitivity.cs, osu.Framework/Input/Handlers/IHasSensitivity.cs, osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/UserInputManager.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/osu.Framework.csproj
Involves quite a large refactor of input handlers for more flexibility. Stored enabled handlers to configuration. Adds global sensitivity setting (will be per-device in the future; just keeping things simple for now).
=> Add raw input and sensitivity

osu.Framework.VisualTests/Tests/TestCaseSpriteText.cs
=> Make TestCaseSpriteText test for multiline behavior

osu.Framework.VisualTests/Tests/TestCaseSizing.cs
smoogipooo wanted this to define behaviour in this scenario.
=> Add a TestCaseSizing for RelativeSize inside AutoSize

osu.Framework/Allocation/BackgroundDependencyLoader.cs, osu.Framework/Allocation/DependencyContainer.cs
Documentation and error messages relevant for BackgroundDependencyLoader.
=> Document BackgroundDependencyLoader

SampleGame/SampleGame.csproj, SampleGame/packages.config, osu.Framework.Desktop.Tests/osu.Framework.Desktop.Tests.csproj, osu.Framework.Desktop.Tests/packages.config, osu.Framework.Desktop/osu.Framework.Desktop.csproj, osu.Framework.Desktop/packages.config, osu.Framework.Testing/osu.Framework.Testing.csproj, osu.Framework.Testing/packages.config, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework.Tests/packages.config, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework.VisualTests/packages.config, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
- Includes large OpenTK updates (including some custom commits).
- Doesn't update ManagedBass (needs further investigation; doesn't target net45).
=> Update nuget packages

osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
=> Fix context menu blocking right-clicks

osu.Framework/Audio/Track/TrackAmplitudes.cs, osu.Framework/Audio/Track/TrackBass.cs
=> Add FrequencyAmplitudes to TrackAmplitudes

osu.Framework.VisualTests/Tests/TestCaseAnimation.cs, osu.Framework.VisualTests/osu.Framework.VisualTests.csproj, osu.Framework/Graphics/Animations/Animation.cs, osu.Framework/Graphics/Animations/AnimationExtensions.cs, osu.Framework/Graphics/Animations/DrawableAnimation.cs, osu.Framework/Graphics/Animations/FrameData.cs, osu.Framework/Graphics/Animations/IAnimation.cs, osu.Framework/Graphics/Animations/TextureAnimation.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/osu.Framework.csproj
This pull request adds animations to the framework.
I ran my initial design by Tom, who didn't have any complaints.
Further feedback and discussion is welcome, although I believe this design to be pretty good for frame-based animations.
Support for other kinds of animations seemed to unnecessarily complicate the API and would be a much much more obscure use-case to begin with, which is why this API explicitly does not add support for types of animations that are not frame-based.
Depends on
=> Add Animation System

osu.Framework/Graphics/Cursor/CursorContainer.cs
=> Fix mouse cursor not correctly exiting window

osu.Framework/Audio/AudioComponent.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Sample/SampleManager.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Batches/VertexBatch.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Performance/PerformanceOverlay.cs, osu.Framework/MathUtils/NumberFormatter.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Properties/AssemblyInfo.cs, osu.Framework/Statistics/FrameStatistics.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/DrawThread.cs, osu.Framework/Threading/GameThread.cs, osu.Framework/Threading/InputThread.cs, osu.Framework/Threading/UpdateThread.cs, osu.Framework/osu.Framework.csproj
The code no longer checks hardcoded thread indices, and the increment
operation is now literally an integer increment without overhead.
=> Greatly simplify performance counters (performance & code)

osu.Framework/Audio/Track/TrackVirtual.cs
Also correctly implements HasCompleted state
=> Expose TrackVirtual

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Performance/FpsDisplay.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Timing/FramedClock.cs, osu.Framework/Timing/InterpolatingFramedClock.cs
See individual commit messages for more details.
=> Various framework improvements

osu.Framework.Testing/Drawables/TestCaseButton.cs, osu.Framework.Testing/TestBrowser.cs, osu.Framework.VisualTests/Tests/TestCaseColourGradient.cs, osu.Framework.VisualTests/Tests/TestCaseDrawablePath.cs, osu.Framework.VisualTests/Tests/TestCaseDynamicDepth.cs, osu.Framework.VisualTests/Tests/TestCaseFillModes.cs, osu.Framework.VisualTests/Tests/TestCaseHollowEdgeEffect.cs, osu.Framework.VisualTests/Tests/TestCaseInputResampler.cs, osu.Framework.VisualTests/Tests/TestCaseNonAsyncContainer.cs, osu.Framework.VisualTests/Tests/TestCasePadding.cs, osu.Framework.VisualTests/Tests/TestCaseSmoothedEdges.cs, osu.Framework.VisualTests/Tests/TestCaseTransformSequence.cs, osu.Framework.VisualTests/Tests/TestCaseTriangles.cs, osu.Framework/Game.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/Container.cs, osu.Framework/Graphics/Containers/IContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs, osu.Framework/Graphics/Performance/FpsDisplay.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/ContextMenuItem.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Graphics/Visualisation/PropertyDisplay.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/Screens/Screen.cs
This was finally possible! I feel like this is a huge milestone for us in terms of code cleanliness.
=> Make Container implement ICollection and IReadOnlyList

osu.Framework/Configuration/Bindable.cs, osu.Framework/Configuration/NonNullableBindable.cs, osu.Framework/osu.Framework.csproj
A bindable which can never take on a null value.
=> Implement NonNullableBindable

osu.Framework/Audio/Track/TrackManager.cs
This was very flaky in the first place. Will be reimplemented in the osu! project.
=> Remove SetExclusive logic

osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/Allocation/InvokeOnDisposal.cs, osu.Framework/Graphics/Drawable.cs
Effectively what the title says. See File Changes for more details.
=> Add a bit of additional documentation and rename DependencyContainer.Initialize to Inject

osu-framework.sln.DotSettings, osu.Framework/Extensions/ExtensionMethods.cs
=> Add helper method for SHA-2 hash computation

osu.Framework.Desktop/Platform/DesktopStorage.cs, osu.Framework/Platform/Storage.cs
=> Add a method to storage to delete whole directories

.vscode/launch.json, .vscode/tasks.json
More is planned, but I want to get this out asap because I'm ready to merge visual tests stuff in the osu! project.
=> Update VSCode with new configurations.

osu.Framework/Input/InputState.cs, osu.Framework/Input/PassThroughInputManager.cs
Resolves https://github.com/ppy/osu-framework/issues/949.
=> Remove InputState.Data

osu.Framework/Graphics/Containers/CompositeDrawable.cs
Regressed in https://github.com/ppy/osu-framework/pull/954
=> Fix incorrectly firing assertions when recursively disposing children

osu.Framework.Desktop.Tests/Visual/TestCaseKeyBindings.cs, osu.Framework/Input/Bindings/KeyBinding.cs, osu.Framework/Input/Bindings/KeyBindingInputManager.cs, osu.Framework/Input/Bindings/KeyCombination.cs, osu.Framework/Input/UserInputManager.cs
- Better API.
- Method to convert `Key`s to human-readable strings.
- More
=> Key binding improvements

osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs, osu.Framework/Graphics/Containers/OverlayContainer.cs, osu.Framework/Graphics/Cursor/CursorContainer.cs, osu.Framework/Graphics/Visualisation/LogOverlay.cs, osu.Framework/Input/InputManager.cs
No longer rely on weird OnFocusLost checks.
=> Improve escape key handling

osu.Framework.Desktop.Tests/Visual/TestCaseTextFlow.cs, osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs, osu.Framework/Graphics/Sprites/IHasLineBaseHeight.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/osu.Framework.csproj
The most notable thing in this PR is the addition of the CustomizableTextContainer class.
This is a subclass of TextFlowContainer that allows easily interspersing icons with regular text.
There are three flavors of use I chose to support:
```
text.Text = "This [HeartIcon] is a permanent health upgrade";
text.Text = "Press [KeyboardKeyIcon(65)] to advance text."; // <- 65 = keycode for "A"
text.Text = "I can escape [[0]] too!";
var phIndex = text.AddPlaceholder(someComplexDrawable);
text.Text = $"Something [{phIndex}] very special!"
```
The way that users should use CustomizableTextContainer is by either subclassing it and adding named factories (such as HeartIcon or KeyboardKeyIcon in the example above), essentially like this:
```
class Custom : CustomizableTextContainer
{
public Custom() …
```
=> Add an API to create text with icons

osu.Framework.Tests/Lists/TestSortedList.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Lists/SortedList.cs
As discussed, this was determined to be a better solution.
=> Fix container contains

osu.Framework.Desktop.Tests/Visual/TestCaseDelayedLoad.cs, osu.Framework.Desktop.Tests/osu.Framework.Desktop.Tests.csproj, osu.Framework.Desktop/Platform/HeadlessGameHost.cs, osu.Framework.Testing/TestCase.cs, osu.Framework/Platform/GameHost.cs
Improves efficiency of unit testing.
=> Add the ability for headless runs to exceed realtime

osu.Framework/Graphics/MarginPadding.cs
Does what it says. This just bugged me cuz I had to look up the implementation of Horizontal/Vertical to double-check what they do.
=> Document MarginPadding

osu.Framework.Desktop.Tests/Visual/TestCaseNestedMenus.cs
=> Make TestCaseNestedMenus use NUnit tests

osu.Framework.Testing/TestCase.cs
=> Make RunTest virtual again

osu.Framework.Desktop.Tests/Visual/TestCaseNestedMenus.cs, osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs, osu.Framework/Graphics/UserInterface/Menu.cs, osu.Framework/Input/InputManager.cs
Fixes issues with focus and state.
Selected no longer correlates 1:1 to menu open state. This should work better when we decide to add keyboard support.
=> Fix menus, again

osu.Framework/Graphics/UserInterface/TextBox.cs
- Individual letters have gradient fades to avoid appearing right of the caret during animation.
- Caret is slightly thicker and has rounded corners.
=> TextBox caret improvements

osu.Framework/Graphics/UserInterface/TextBox.cs
Here I was thinking Color4.Transparent was transparent black...
=> Use constant for transparent white

osu.Framework.Desktop.Tests/Visual/TestCaseNestedMenus.cs, osu.Framework.Testing/TestBrowser.cs, osu.Framework.Testing/TestCase.cs
- Integrates NUnit test methods to be visually accessible.
- RunAllSteps button no longer gets stuck.
- Scrolling step buttons.
=> Improvements to test browsing

osu.Framework/Audio/Track/TrackVirtual.cs
or running any audio thread events.
=> Fix TrackVirtual never getting disposed

osu.Framework.Desktop.Tests/Visual/TestCaseSearchContainer.cs, osu.Framework/Graphics/Containers/IHasFilterTerms.cs
Fixes https://github.com/ppy/osu-framework/issues/961
=> Changed type of IHasFilterTerms.FilterTerms to IEnumerable

osu.Framework.Desktop.Tests/Visual/TestCaseTooltip.cs, osu.Framework/Graphics/Cursor/TooltipContainer.cs
Fixes https://github.com/ppy/osu-framework/issues/790
=> Hide empty or nulled tooltips

osu.Framework.Testing/DynamicClassCompiler.cs, osu.Framework.Testing/IDynamicallyCompile.cs, osu.Framework.Testing/TestBrowser.cs, osu.Framework.Testing/TestCase.cs, osu.Framework.Testing/osu.Framework.Testing.csproj, osu.Framework/Graphics/UserInterface/Dropdown.cs
You can now specify a list of types in a TestCase to get dynamic recompilation support for those classes.
=> Dynamically compile more than just TestCases

osu.Framework/Platform/HeadlessGameHost.cs
Fixes parallel nunit runs having file/db access conflicts
=> Isolate headless runs' storage paths

.vscode/launch.json, .vscode/tasks.json
- Fixes capitalisation in task names
- Adds a launch configuration for visual tests in release mode
- Adds missing "build" type to release build task
=> Improve VSCode build / debug tasks

osu.Framework/Logging/Logger.cs, osu.Framework/Platform/DesktopStorage.cs, osu.Framework/Platform/Storage.cs
Supersedes #1075
Reverting stuff is quite painful and creates a lot of meaningless commits.
=> Add Storage.GetDatabaseConnectionString method

osu.Framework/Testing/TestBrowser.cs
_docs are probably not that good_
=> Allow TestBrowser to load non osu assemblies

osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
=> Update BitmapFont nuget package

osu.Framework/Graphics/Drawable.cs
Seems like copying the line but forgetting to change all X's to Y.
=> Fixed a typo in Drawable.cs

osu.Framework/Graphics/Batches/VertexBatch.cs
It looks sane to me since it has proper IDisposable pattern implementation.
=> Make VertexBatch IDisposable

osu.Framework/Configuration/BindableNumber.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs
Another PR is coming for osu! that adds snap intervals to all the settings.
=> Add the ability to snap slider bars if holding shift

osu.Framework/IO/File/FileSafety.cs, osu.Framework/Platform/DesktopStorage.cs, osu.Framework/Platform/GameHost.cs
Adds cleanup on start of GameHost.
=> Use FileSafety to perform storage deletions

osu.Framework/Input/InputManager.cs
=> Fix double-clicks being handled by drawables that aren't clicked

osu.Framework/app.config, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
Hopefully this helps with osu! unit tests failing. ¯\_(ツ)_/¯
=> Update System.ValueTuple to 4.4.0 in line with osu! projects

.vscode/launch.json, osu.Framework/IO/Network/WebRequest.cs
We need to have the ability to null-check values placed in these dictionaries.
=> Privatise WebRequest dictionaries

LangVer.props, README.md, SampleGame/Properties/app.manifest, SampleGame/SampleGame.csproj, SampleGame/app.config, SampleGame/packages.config, appveyor.yml, osu-framework.sln, osu.Framework.Tests/Properties/AssemblyInfo.cs, osu.Framework.Tests/app.config, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework.Tests/packages.config, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/app.config, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
Due to incompatibilities when referencing netstandard and non-netstandard assmeblies in combination with mono runtime, let's keep things sane for now as to not destroy productivitiy in tooling.
=> Revert csproj changes from master

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/MathUtils/Interpolation.cs
In the future we can consider having this "roll" the text somehow. But for now, this is adequate enough to be able to use SpriteText.Text in transformation sequences.
=> Add Text transform to SpriteText

osu.Framework.Tests/Visual/TestCaseCountingText.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/Counter.cs, osu.Framework/MathUtils/Interpolation.cs, osu.Framework/osu.Framework.csproj
Removes the bad TransformTextTo that I previously added.
=> Add counter class + transforms + usage

osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs, osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs, osu.Framework/Platform/DesktopGameWindow.cs
- No longer handle input when minimised.
- No longer incorrectly resize the window on minimise.
Fixes https://github.com/ppy/osu/issues/1473.
=> Fix minimising window causing weird issues

osu.Framework/Platform/DesktopGameWindow.cs
Fixes problem with saving window position(see #1023 , #1146 )
=> Update window position in OnMove method

osu.Framework/Graphics/DrawInfo.cs
It's expensive. Roughly 4% of update thread was being consumed by this. In release builds.
=> Don't concatenate strings unless actually necessary

osu.Framework/Input/InputManager.cs
Holding A and tap S while moving the mouse in the KeyBinding test case would previously cause A to flicker between states.
Resolves https://github.com/ppy/osu/issues/1021
=> Fix keys being released and re-pressed when mouse movement interleaves keyboard states

osu.Framework/Graphics/Sprites/SpriteText.cs
Improves performance in many use cases.
=> Allow SpriteText to compute its initial layout asynchronously

osu.Framework/Input/InputManager.cs, osu.Framework/Input/InputState.cs
On second thought, it doesn't need to be at an InputState level and this just complicates stuff further. This tidies up the code significantly (applies the improvements I made int he previous alternations).
=> Move distinct state creation back to InputManager

osu.Framework/Input/InputManager.cs
this is really annoying if you just want to scroll on another window while osu is still focused
=> Fix scrolling outside the window

osu.Framework/IO/AsyncBufferStream.cs
Required for .NET Core - Thread.Abort is deprecated and results in exceptions upon being called (ref: https://github.com/dotnet/coreclr/pull/2342). The standard is to use tasks + cancellation tokens.
=> Use a task for AsyncBufferStream to remove Thread.Abort usage

osu.Framework/Graphics/Containers/CompositeDrawable.cs
=> Make AutoSizeAxes virtual to allow implementations to track changes

osu.Framework/Logging/Logger.cs
Better solution than https://github.com/ppy/osu-framework/pull/1205.
=> Don't add log header until the first time a log is written to

osu.Framework/Graphics/UserInterface/BasicSliderBar.cs, osu.Framework/Testing/TestBrowser.cs
=> Add playback speed adjustment to TestBrowser

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/MathUtils/Validation.cs, osu.Framework/osu.Framework.csproj
Resolves https://github.com/ppy/osu-framework/issues/1211.
=> Add additional IsFinite checks and remove check from computeDrawInfo

osu.Framework/Input/InputManager.cs, osu.Framework/Input/UserInputManager.cs
Fixes regression caused by #1174.
=> Fix hover events being ignored in InputManagers that don't even handle user input

osu.Framework/Audio/AudioComponent.cs, osu.Framework/Audio/Track/Track.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/TrackVirtual.cs
This fixes songs not looping because they got cleaned up before they had a chance to start anew.
Solves https://github.com/ppy/osu/issues/1522
=> Fix audio tracks not looping

iOS.props, osu-framework.sln
This project GUID seems to be required for now... Glad to have this somewhat fixed for now.
=> Make osu.Framework load in VS for Mac

osu.Framework/Graphics/Containers/TextFlowContainer.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/Visualisation/LogOverlay.cs
=> Add back a few input blocks in hot areas

osu.Framework/Testing/TestBrowser.cs
=> Allow exiting TestBrowser using escape key

osu.Framework/Graphics/Drawable.cs
Triggers in a future vresion of resharper. Also add a comment to better explain what's going on with reflection.
=> Fix possible null inspection in HandleInputCache

osu.Framework/Graphics/UserInterface/BasicCheckbox.cs, osu.Framework/Graphics/UserInterface/BasicSliderBar.cs, osu.Framework/Testing/Drawables/Steps/AssertButton.cs, osu.Framework/Testing/Drawables/Steps/StepButton.cs, osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestCase.cs
- Don't hard crash TestBrowser when assertion fails.
- "Run all tests" button became checkbox.
- `BasicCheckbox`es styled to look more presentable.
- Optional descriptions for steps missing them.
- Improve Asert/Until steps buttons (and all StepButtons in general).
=> Various QOL improvements for TestBrowser

osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
Headless tests run in non-realtime, causing timeouts to happen unrealistically early. Our usage of `UntilStep` is usually to wait on a (CPU/IO bound) load task, so we want to timeout on a real-time value instead.
Fixes a regression introduced in #1251.
=> Give until steps a local stopwatch to calculate timeout

osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestCase.cs
Fixes a regression introduced in #1251.
=> Fix previous tests not correctly getting removed from TestBrowser

osu.Framework.Tests/IO/TestSortedListSerialization.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/IO/Serialization/SortedListConverter.cs, osu.Framework/Lists/SortedList.cs, osu.Framework/osu.Framework.csproj
Allows serialization/deserialization from/into a `SortedList<T>`.
=> Make SortedList serialize correctly with JSON.Net

osu.Framework/Logging/Logger.cs, osu.Framework/Threading/Scheduler.cs
=> Fix thread race condition in logger

osu.Framework/Configuration/Bindable.cs
Splits `UnbindAll` into `UnbindEvents` and `UnbindBindings`.
=> More specific unbinding

osu.Framework/Configuration/Bindable.cs
=> Don't fail on UnbindBindings when there are no bindings

osu.Framework/Graphics/Cursor/TooltipContainer.cs
=> Fix incorrect null tooltip check

osu.Framework.Tests/Visual/TestCaseTabControl.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/FlowContainer.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
This reverts commit d5bdf96a887646be92e670bd30fd4cda4c588718.
Easiest path forward for now, there are a lot of osu!-side changes to be done.
=> Revert "Merge pull request #1261 from default0/explicit-flow-order"

osu.Framework/Audio/AudioManager.cs
Fixes https://ci.appveyor.com/project/peppy/osu/build/master-6442/tests
=> Fix possible race condition where global Track/SampleManagers are unexpectedly null

osu.Framework/Testing/Drawables/Steps/AssertButton.cs, osu.Framework/Testing/Drawables/Steps/RepeatStepButton.cs, osu.Framework/Testing/Drawables/Steps/StepButton.cs, osu.Framework/Testing/Drawables/Steps/ToggleStepButton.cs, osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestCase.cs
Fixes ppy/osu#1850, fixes ppy/osu#1851
Can't check if actually works after recloning the fork because internet decided to reach dial-up levels of speed.
=> Fix RepeatStepButton and RunAllSteps

osu.Framework/Graphics/Containers/OverlayContainer.cs, osu.Framework/Graphics/Containers/VisibilityContainer.cs, osu.Framework/Graphics/Cursor/TooltipContainer.cs
There's no reason it needs to be an OverlayContainer.
=> Make Tooltip a VisibilityContainer instead of OverlayContainer

osu.Framework/Input/Bindings/KeyBindingContainer.cs
=> stop bindings from interrupting each other when in unique mode

osu.Framework/Configuration/Bindable.cs, osu.Framework/Configuration/ConfigManager.cs, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Configuration/FrameworkDebugConfig.cs, osu.Framework/Configuration/IniConfigManager.cs, osu.Framework/Testing/TestBrowserConfig.cs, osu.Framework/osu.Framework.csproj
Prerequisites for storing config to other places.
=> Make ini based config manager its own class

osu.Framework/Testing/DynamicClassCompiler.cs
Fixes #1325.
Hope I didn't miss anything, but this worked fine in all my testing.
=> Ensure correct assembly for dynamic compilation

SampleGame/SampleGame.csproj, SampleGame/packages.config, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework.Tests/packages.config, osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Input/Handlers/Mouse/OpenTKMouseState.cs, osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/MouseState.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/DesktopGameWindow.cs, osu.Framework/Platform/GameWindow.cs, osu.Framework/Platform/Windows/Native/Input.cs, osu.Framework/app.config, osu.Framework/osu.Framework.csproj, osu.Framework/packages.config
- Fixes raw input not working correctly on macOS.
- Fixed absolute raw input devices (tablets etc.) not working correctly.
Closes #1333 via OpenTK update.
=> Raw input improvements

osu.Framework/Threading/AudioThread.cs, osu.Framework/Threading/GameThread.cs
I'm pretty much ready to call this a fix to the nunit stuff right now, after over 130 nunit runs.
=> Fix GameThread exits not running on the encapsulated thread

osu.Framework/Testing/TestCase.cs
As seen here https://ci.appveyor.com/project/peppy/osu/build/master-7270#L3388
=> Avoid test cases failing on directory cleanup exception

osu.Framework/Configuration/Bindable.cs
Was causing weird things to happen.
=> Fix Bindable's GetBoundCopy using MemberwiseClone

osu.Framework/Graphics/Transforms/Transformable.cs
As pointed out [here](https://github.com/ppy/osu-framework/pull/1413#discussion_r170508493)
=> Use same argument order in all transformable conditionals

osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
=> Always confine cursor when left mouse button is pressed

osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/Allocation/TimedExpiryCache.cs, osu.Framework/Audio/AudioComponent.cs, osu.Framework/Audio/Sample/SampleManager.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/Waveform.cs, osu.Framework/Configuration/IniConfigManager.cs, osu.Framework/Extensions/ExtensionMethods.cs, osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs, osu.Framework/Graphics/Shaders/Shader.cs, osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Graphics/Shaders/ShaderPart.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/Vector2Extensions.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/IO/Stores/CachedResourceStore.cs, osu.Framework/IO/Stores/GlyphStore.cs, osu.Framework/IO/Stores/ResourceStore.cs, osu.Framework/Input/Handlers/InputHandler.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Lists/WeakList.cs, osu.Framework/Logging/Logger.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Threading/Scheduler.cs
We might want to do it in order to reduce LOC number a little.
=> Inline out variables

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs, osu.Framework/Timing/FramedClock.cs
Prerequisite to fixing ppy/osu#1821 (again).
=> Cleanups to clock handling

osu.Framework/Testing/DynamicClassCompiler.cs
`DynamicClassCompiler` was adding all directories recursively in the git repository. This unnecessarily includes things like `.git` which can have upwards of 10,000 files. Under mono this adds a huge startup overhead.
This change only adds directories containing csproj files. Has the added advantage of not including the framework when working on osu!.
- Also threads initialisation of the `FileSystemWatcher` to further improve startup performance.
- Also fixes compilation happening more than once for a single file change.
- Also improves dynamic compilation performance as it doesn't have to process through as many files to find dependencies.
=> Avoid including directories with many files in dynamic compile watch list

osu.Framework/Graphics/Cursor/CursorContainer.cs
Allows a custom content container to be specified.
=> Move CursorContainer's Add to BDL

LICENCE
=> Update licence year

osu.Framework/Graphics/UserInterface/TabControl.cs
The flow ordering was changed here, we need this to be overridable so we can adjust it at osu!'s end.
=> Make TabControl's tab flow overridable

osu.Framework/Platform/DesktopGameWindow.cs, osu.Framework/Platform/GameWindow.cs, osu.Framework/Platform/MacOS/MacOSGameWindow.cs, osu.Framework/Platform/Windows/WindowsGameWindow.cs
Looks to have been merged without the requested testing on windows/linux.
High priority revert
=> Revert GameWindow changes

osu.Framework/Graphics/Containers/BufferedContainer.cs
We don't have 3 frame buffers, we have 3 draw nodes.
=> Rename frameBufferX -> drawNodeX

osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Regressed with GameWindow changes.
=> Fix macOS platform modifiers not being properly loaded

osu.Framework.Tests/Visual/TestCaseEffects.cs, osu.Framework/Graphics/Containers/ContainerExtensions.cs
Pure coincidence that it previously worked at osu!'s end. 😛 
Closes ppy/osu#2263.
=> Fix Incorrect Behaviour of ContainerExtensions.Wrap in Certain Cases

osu.Framework/Platform/TcpIpcProvider.cs
=> Add check for IsCancellationRequested in TcpIpcProvider

osu.Framework/Configuration/FrameworkConfigManager.cs, osu.Framework/Platform/GameHost.cs
I revoke my own permission to review code.
=> Fix regression in input handler configuration

osu.Framework/Graphics/UserInterface/TextBox.cs
=> Consume all pending text from input in OnKeyUp

osu.Framework/IO/Stores/GlyphStore.cs
=> Fix potential nullref if GlyphStore is used too quickly

osu.Framework/Logging/ThrowingTraceListener.cs, osu.Framework/Platform/GameHost.cs
=> Throw an (unhandled) exception on assert failure

osu.Framework/Configuration/Bindable.cs
Not sure how this happened :(.
=> Commit missed change from #1545

osu.Framework/Graphics/UserInterface/CircularProgress.cs
Not sure how I missed this when I changed the signature to remove other useless stuff >_<
=> Fix wrong signature on FillTo

osu.Framework/Graphics/UserInterface/TextBox.cs
=> Fix textbox not always blocking all handled key presses

osu.Framework/Testing/Input/ManualInputManager.cs
Allows testing keyboard + scroll wheel.
=> Expose scroll wheel and key methods from ManualInputManager

osu.Framework/Graphics/OpenGL/GLWrapper.cs
=> Fix infinite queuing of expensive operations in GLWrapper

osu.Framework/Input/InputManager.cs
Closes ppy/osu#2384.
Closes ppy/osu#2661.
=> Fix LastMousePosition not always being present when expected

osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
Resolves ppy/osu#2658, resolves ppy/osu-framework#1377.
=> Fix wheel values not being aggregated in raw mouse handler

.idea/.idea.osu-framework/.idea/runConfigurations/VisualTests__netcoreapp2_1_.xml, .vscode/launch.json, .vscode/tasks.json, SampleGame/SampleGame.csproj, appveyor.yml, osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework.Tests/Visual/FrameworkTestCase.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/IO/Network/WebRequest.cs, osu.Framework/Platform/DesktopStorage.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/Windows/WindowsStorage.cs
Let me know if I missed anything.
=> Update framework to .NET Core 2.1

README.md
Clearly the most important pull request since the inception of this framework
=> Update README.md with .net Core 2.1

osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
Resolves #811.
Resolves ppy/osu#2015.
Testing on windows only.
=> Fix raw mouse position not being clamped to window bounds

appveyor.yml, appveyor_deploy.yml
=> Don't build tags in standard CI runs

osu.Framework/Configuration/BindableNumber.cs
[Original issue](https://youtrack.jetbrains.com/issue/RSRP-467870)
[Following issue](https://github.com/JetBrains/ExternalAnnotations/issues/108) which got closed/fixed.
Oh, and I also fixed a typo.
=> Remove now obsolete "ReSharper disable once" comment

osu.Framework/Graphics/UserInterface/TextBox.cs
=> Make TextBox selection colour customizable

osu.Framework/Graphics/Drawable.cs
=> Fix a potential nullref in Drawable's ToString function when parent is null

osu.Framework.Tests/Visual/TestCaseInputQueueChange.cs
Made to show a fault in #1611.
=> Add test for input queue updates

osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/HeadlessGameHost.cs
Closes ppy/osu-framework#1592.
=> Add host-level methods to replace direct calls to Process.Start

osu.Framework/Platform/DesktopStorage.cs, osu.Framework/Platform/HeadlessGameHost.cs, osu.Framework/Platform/Linux/LinuxGameHost.cs, osu.Framework/Platform/Linux/LinuxStorage.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/MacOS/MacOSStorage.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs, osu.Framework/Platform/Windows/WindowsStorage.cs
=> Fix Storage.OpenInNativeExplorer not working under netcore2.1

.github/pull_request_template.md
Add a template with the new changelog-friendly PR description format.
=> Add a simple Pull Request template

osu.Framework.Tests/Visual/TestCaseScreen.cs, osu.Framework/Screens/Screen.cs
Building block for resolution of ppy/osu#2681.
=> Allow screens to be exited before they are completely loaded

osu.Framework/Graphics/Drawable.cs, osu.Framework/Statistics/PerformanceMonitor.cs
Its priority is lower than priority of other operators in its left part.
---
=> Fix incorrect usage of null coalesce

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Containers/OverlayContainer.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Input/Bindings/KeyBindingContainer.cs, osu.Framework/Input/InputManager.cs, osu.Framework/Input/PassThroughInputManager.cs
- Missing tests
- PRing for comment
- Closes #1569
=> Allow KeyBindingContainer actions to travel past PassThroughInputManagers

osu.Framework.Tests/Visual/TestCaseScreen.cs, osu.Framework/Screens/Screen.cs
Required for ppy/osu#2842.
---
=> Add typed exceptions for various failures that can occur on Screen operations

osu.Framework/Platform/DesktopStorage.cs, osu.Framework/Platform/Storage.cs
Storage already had ``GetDirectories``
---
=> Add GetFiles to Storage

osu.Framework/Allocation/BackgroundDependencyLoader.cs
=> Mark dependency-injected methods as implicitly-used

osu.Framework/Input/InputManager.cs
I should have tested with a virtual joystick.
=> Fix joystick button handling being completely incorrect

README.md, SampleGame/SampleGame.csproj, appveyor.yml, osu-framework.sln, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/Platform/GameHost.cs, osu.Framework/RuntimeInfo.cs
=> Remove net471 targeting

osu.Framework.Tests/Visual/TestCaseGridContainer.cs, osu.Framework/Graphics/Containers/GridContainer.cs
From: https://streamable.com/zsdlb
To: https://streamable.com/04w7b
---
=> Fix autosizing gridcontainer cells not resizing

osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/osu.Framework.csproj
Should be regression tested against osu! (especially audio) before merging.
=> Update nuget dependencies

osu.Framework/Graphics/Shaders/ShaderManager.cs, osu.Framework/Platform/GameWindow.cs
Also fixes log level of GL initialisation output.
=> Fix shader log output being ugly and non-useful

osu.Framework.Tests/Visual/TestCaseSizing.cs
See: https://github.com/ppy/osu-framework/issues/1762
No better way to deal with it at this current time.
=> Apply an interim fix for a StackOverflowException

osu.Framework.Tests/IO/LoggerTest.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Track/TrackBass.cs, osu.Framework/Audio/Track/Waveform.cs, osu.Framework/Logging/Logger.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Threading/GameThread.cs
Previously two log entries would be added for errors, making doing anything with them quite
=> Allow exceptions to be resolved from LogEntries

osu.Framework.Tests/Visual/TestCaseConcurrentLoad.cs, osu.Framework.Tests/Visual/TestCaseDrawableLoadCancallation.cs, osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
This doesn't yet add support for asynchronous BDL methods, but is a first step.
=> Support for cancellation on drawables’ load

osu.Framework/Graphics/UserInterface/TextBox.cs
Also shows red "error" flash when characters are not accepted.
- Resolves #1777.
=> Fix unhandled exceptions being thrown by textbox

osu.Framework.Tests/Visual/TestCaseScreen.cs
https://ci.appveyor.com/project/peppy/osu-framework/build/6624/tests
=> Fix failing screen testcase

osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
Resolves [OSU-LAZER-6P](https://sentry.io/ppy/osu-lazer/issues/654828995)
=> Fix CollectionModifiedException occurring when refreshing joystick devices

osu.Framework.Tests/Visual/TestCaseSizing.cs
=> Fix TestCaseSizing visual test not shown

osu.Framework/Logging/Logger.cs
Reduces overheads that come from GameThread usage.
=> Use Timer for logger instead of GameThread

osu.Framework/Statistics/BackgroundStackTraceCollector.cs
`GameThread` has some overheads we don't want to subject this class to.
=> Reduce overhead of BackgroundStackTraceCollector

osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs, osu.Framework/Graphics/Performance/FrameTimeDisplay.cs, osu.Framework/Statistics/PerformanceMonitor.cs, osu.Framework/Timing/FramedClock.cs, osu.Framework/Timing/IFrameBasedClock.cs, osu.Framework/Timing/ThrottledFrameClock.cs
Also removes AverageFrameTime from FramedClock as it didn't feel like the right place for it.
=> Fix elapsed frame time not accounting for sleep time correctly

osu.Framework/Platform/DesktopGameHost.cs
Outdated and no longer working. Plus we now have a better method (`VisualTetsts`) that replaces the need for this.
=> Remove shadow copy logic

osu.Framework/IO/Stores/FontStore.cs, osu.Framework/IO/Stores/GlyphStore.cs
Reduces thread concurrency to one. Also adds fairness preference to force FIFO behaviour.
=> Improve load logic of glyph stores

osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs, osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Threading/ThreadedTaskScheduler.cs
- Allow loading multiple components at once via `LoadComponentsAsync`.
- Adds cancellation support.
- Moves execution to a custom thread pool via `ThreadedTaskScheduler`.
=> Improvements to LoadComponentAsync

osu.Framework.Tests/Visual/TestCaseSizing.cs
=> Fix TestCaseSizing being empty by default

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/Transforms/Transformable.cs
It turns out this is much better performance than manually handling it.
=> Use Lazy<T> in every case we can

osu.Framework/Audio/AdjustableAudioComponent.cs, osu.Framework/Audio/AudioComponent.cs
Fixes:
```
System.AggregateException : One or more errors occurred. (A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.))
----> System.AggregateException : A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.)
----> System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
TearDown : System.AggregateException : One or more errors occurred. (A Task's exception(s) …
```
=> Fix potential race condition causing collection modified exceptions

osu.Framework.Tests/Visual/TestCaseDelayedUnload.cs, osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs, osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs
Handles unloading of textures after a given time offscreen. Working a an addition to `DelayedLoadWrapper`.
~TODO: testcase~
=> Add DelayedLoadUnloadWrapper

osu.Framework/Platform/DesktopGameWindow.cs, osu.Framework/Platform/GameWindow.cs, osu.Framework/Platform/MacOS/MacOSGameWindow.cs
=> Don't expose fullscreen resolutions on macOS

osu.Framework.Tests/Visual/TestCaseTextures.cs
https://ci.appveyor.com/project/peppy/osu-framework/build/7178/tests
=> Fix unit tests failing due to async load

osu.Framework/Graphics/Textures/TextureStore.cs
Resolves https://ci.appveyor.com/project/peppy/osu-framework/build/7184/tests
=> Fix potential thread race condition in TextureStore's refresh logic

osu.Framework.Tests/Exceptions/TestLoadExceptions.cs, osu.Framework/Testing/TestCase.cs
=> Improve dotnet test run storage cleanup and naming

appveyor.yml, osu.Framework.Tests/IO/TestWebRequest.cs, osu.Framework.Tests/Visual/TestCaseNestedMenus.cs, osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs, osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs
HttpBin has fallen over one too many times for comfort.
https://ci.appveyor.com/project/peppy/osu-framework/build/7232/tests
=> Deploy a local httpbin server for webrequest tests

osu.Framework/Input/MouseButtonEventManager.cs
- Fix an issue found in https://github.com/ppy/osu/pull/3453#discussion_r218698548 .
---
=> Fix double click handling accessing dead drawable

osu-framework.sln.DotSettings, osu.Framework/Host.cs, osu.Framework/Platform/DesktopGameHost.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/Linux/LinuxGameHost.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs, osu.Framework/Platform/Windows/WindowsGameHost.cs
This will make opentk prefer running with native code when running under macos
---
Fix crashes on macOS when having SDL2 installed
=> Prefer native MacOS code over SDL on OSX

osu-framework.sln.DotSettings, osu.Framework/MathUtils/PathApproximator.cs
Requires for osu! sliders, but decided it would be more helpful to have at a framework level.
=> Add PathApproximator helper method

osu.Framework/Allocation/CachedAttribute.cs
Rest of the comment says "If null, the value will be cached as the value's most derived type", this disagreed.
=> Fix incorrect comment

osu.Framework/Testing/DynamicClassCompiler.cs
Rider is complaining about this one as of late.
=> Remove on unnecessary null check

osu.Framework/Platform/GameHost.cs, osu.Framework/Platform/MacOS/MacOSGameHost.cs
Bug reported in #osu that I happened to catch.
=> Fix incorrect handling of shift-backspace and shift-delete on windows and macOS

osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs, osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs, osu.Framework/osu.Framework.csproj
Use the new API of <s>ppy/opentk#25</s> -> ppy/opentk#42.
- Closes ppy/osu#3073
---
=> Read all device states at once for raw input handlers

osu.Framework/Graphics/Containers/CustomizableTextContainer.cs, osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs, osu.Framework/Graphics/Containers/TextFlowContainer.cs
Allows for better control from consumers.
=> Return all drawables in TextFlow add methods, including newlines

SampleGame/SampleGame.csproj, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/osu.Framework.csproj
=> Update projects to target .NET core 2.2

osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
=>  Update ModelBackedDrawable before loading is completed 

osu.Framework.Tests/Visual/TestCaseSliderbar.cs, osu.Framework.Tests/Visual/TestCaseSpriteTextScenarios.cs, osu.Framework.Tests/Visual/TestCaseWaveform.cs, osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/Checkbox.cs, osu.Framework/Graphics/UserInterface/CircularProgress.cs, osu.Framework/Graphics/UserInterface/Dropdown.cs, osu.Framework/Graphics/UserInterface/IHasCurrentValue.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/UserInterface/TextBox.cs, osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs, osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs, osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
This was removed because it was shoddily implemented previously.
=> Implement IHasCurrentValue on SpriteText

.idea/.idea.osu-framework/.idea/runConfigurations/VisualTests.xml
=> Update VisualTests.xml to reference netcoreapp2.2

osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
Potentially avoids one copy operation.
=> Improve efficiency of iOS texture loading

osu.Framework.Tests/Visual/TestCaseJoystick.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Graphics/Cursor/TooltipContainer.cs, osu.Framework/Localisation/LocalisationManager.cs
Find implementation:
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L422
LINQ First implementation
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/First.cs#L76
As far as I understand, for loop is faster than enumerator.
=> Use List<T>.Find instead of LINQ

osu.Framework/Graphics/UserInterface/SliderBar.cs
Should allow us to resolve https://github.com/ppy/osu/issues/4011 along with the sound/tick issue.
=> Provide new value to SliderBar.OnUserChange()

osu.Framework.Tests/Dependencies/CachedAttributeTest.cs, osu.Framework.Tests/Dependencies/DependencyContainerTest.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/Allocation/CacheInfo.cs, osu.Framework/Allocation/CachedAttribute.cs, osu.Framework/Allocation/DependencyActivator.cs, osu.Framework/Allocation/DependencyContainer.cs, osu.Framework/Allocation/IReadOnlyDependencyContainer.cs, osu.Framework/Allocation/ResolvedAttribute.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs
Summary:
- Cached values are now identified by a `CacheInfo`.
- A few new methods exist as part of `DependencyContainer`/`IReadOnlyDependencyContainer` to cache and retrieve values identified by a `CacheInfo`.
- `[Cached]` is now allowed on _auto_ properties that have:
1. A `get` method.
2. A private or non-existent `set` method.
- `DependencyContainer` is backwards-compatible with existing usages.
```diff
+ public string Name { get; set; }
+ public Type Parent { get; set; }
+ internal Type Type { get;set; }
```
For now, the additional properties which members can be identified by are `Name` and `Parent`. We can extend these in the future if required, but currently allows for the following:
```csharp
class ToCache:
[Cached]
public string CachedMember { get; set; }
[Cached(Name = "2")] …
```
=> Extend dependency injection with additional caching information

osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
=> Fix RenderBuffers not correctly being unbound

osu.Framework/IO/Network/WebRequest.cs
- Supersedes and closes ppy/osu#4066.
- Closes ppy/osu#4058.
=> Output web request failures

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs
Closes ppy/osu#4032. Hopefully improves performance enough to make this feasible by moving the reflection overhead to async load.
=> Fix automatic unbinding not running soon enough on async disposal

osu.Framework/Screens/Screen.cs
Fix a regression introduced by #2096.
Was not sure about this case. Hopefully it is correct this time.
---
=> Screen input propagation: fix for root screen case

osu.Framework/Graphics/Sprites/SpriteText.cs
Alternative to and closes #2108
=> Avoid potential stack overflow in SpriteText fallback logic

osu.Framework/Graphics/Containers/CompositeDrawable.cs, osu.Framework/Graphics/Drawable.cs, osu.Framework/Screens/ScreenStack.cs
=> Remove + dispose exited screens

Directory.Build.props, osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj, osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreen.cs, osu.Framework.Tests/osu.Framework.Tests.csproj, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/osu.Framework.csproj
Also updates dynamic class compiler to support c# 7.2.
=> Fix screen testcase not working after dynamic compile

osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs, osu.Framework/Input/InputManager.cs
=>  Fix screens (drawables) retaining focus when not alive

osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderBar.cs
Came across random failures that seemed to happen intermittently depending on the size of the window, this should fix that.
=> Fix SliderBar test case

osu.Framework/Allocation/CachedModelDependencyContainer.cs
One weird inspection r# could find but couldn't fix.
=> Move variable local

osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderBar.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs, osu.Framework/Platform/HeadlessGameHost.cs
Also refactors/adds additional tests for SliderBar
fixes ppy/osu#4274
=> Fix SliderBar trying to change bindable values when not the target

osu.Framework.Tests/Clocks/InterpolatingClockTest.cs, osu.Framework/Timing/InterpolatingFramedClock.cs
Regressed in https://github.com/ppy/osu-framework/pull/2166.
=> Fix interpolating clock not seeking backwards correctly

build/build.cake
This should have updated the build version automatically....
but apparently that did not work... because cake only reads that values on startup .-.
=> Replace .Build.Version with .Repository.Tag.Name

osu.Framework/Graphics/Sprites/SpriteText.cs, osu.Framework/Graphics/UserInterface/MenuItem.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
Indirectly fixes ppy/osu#4310.
=> Use string.Empty instead of null for some central bindables

build/build.cake
Turns out this doesn't work so nicely on appveyor
=> Revert iOS inspections

osu.Framework/osu.Framework.csproj
Should resolve #2202 (see https://github.com/dotnet/sourcelink/issues/197).
=> Update sourcelink version

osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
=> Fix linux libraries not being referenced in the .csproj

osu.Framework/Input/InputManager.cs
- Closes https://github.com/ppy/osu/issues/4350
~~Blocked while waiting on tests~~ Added tests in other pr instead
=> Check for parent lifetime when deciding focus

osu.Framework/Audio/IHasTempoAdjust.cs, osu.Framework/Audio/Track/Track.cs
=> Disallow setting Track.Rate directly

osu.Framework/MathUtils/RNG.cs
Whoops, I actually made it less lenient.
=> Revert "Relax RNG exception conditions"

osu.Framework.iOS/GameUIApplication.cs, osu.Framework.iOS/GameViewController.cs, osu.Framework.iOS/IOSGameHost.cs, osu.Framework.iOS/IOSGameView.cs, osu.Framework.iOS/IOSGameWindow.cs, osu.Framework.iOS/Input/IOSKeyboardHandler.cs, osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs, osu.Framework/Platform/MacOS/MacOSClipboard.cs
Just found these while reading through the code.
=> Apply general clean-ups to iOS classes

build.sh, build/build.cake, osu.Framework/osu.Framework.csproj
this mainly targets the inspect code command.
=> Decrease the verbosity of the build script's inspections

osu.Framework/Graphics/UserInterface/TextBox.cs
=> Make Textbox's background colours settable

osu.Framework.Tests/Visual/UserInterface/TestCaseSliderBar.cs, osu.Framework/Graphics/UserInterface/SliderBar.cs
=> Fix SliderBar not correctly handling disabled bindables in commit logic

osu.Framework/Logging/Logger.cs
previously:
`03/22/2019 09:06:59`
now:
`2019-03-22T09:11:34`
=> Use ISO 8601 datetime for logger output

osu.Framework/Game.cs, osu.Framework/Platform/GameHost.cs
Related to upcoming font store changes where the user should not be overwriting `Fonts`.
=> Protect Game's public fields

osu.Framework/Development/DebugUtils.cs, osu.Framework/Testing/TestCase.cs
Nunit still won't write to console, there seems to be an issue open for it (https://github.com/nunit/nunit3-vs-adapter/issues/343), and other issues where people have commented at the lack of resolution (https://github.com/Microsoft/vstest/issues/799).
At least, this adds output to the `Tests` tab in appveyor.
=> Fix appveyor test output

osu.Framework.Tests/Visual/Layout/TestCaseGridContainer.cs, osu.Framework/Graphics/Containers/GridContainer.cs
=> Implement GridContainer dimension minimum size

osu.Framework/Testing/Drawables/TestCaseButton.cs, osu.Framework/Testing/Drawables/TestCaseButtonGroup.cs, osu.Framework/Testing/DynamicClassCompiler.cs, osu.Framework/Testing/TestBrowser.cs, osu.Framework/Testing/TestCase.cs
Also centralises the "TestCase" prefix retrieval.
=> Fix non-grouped test cases not showing up

osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs, osu.Framework/Graphics/OpenGL/ClearInfo.cs, osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Platform/GameHost.cs
Wanted a more centralised place to handle this. At some point in the future we'll probably need clear flags in there, but this is fine for now.
=> Add ability to clear Depth and Stencil

osu.Framework/Testing/DynamicClassCompiler.cs
I'm not sure however if this has any side effects
Fixes #2340
=> Fix dynamic compilation

osu.Framework/Graphics/FrameworkColour.cs, osu.Framework/Graphics/UserInterface/FrameworkColour.cs, osu.Framework/Testing/Drawables/TestCaseButton.cs, osu.Framework/Testing/Drawables/TestCaseHeaderButton.cs, osu.Framework/Testing/Drawables/TestCaseSubButton.cs, osu.Framework/Testing/TestBrowser.cs
I'm unsure about the colours names, the design only had a palette in the top right corner.
=> Add FrameworkColour

osu.Framework/Graphics/OpenGL/GLWrapper.cs, osu.Framework/Platform/GameWindow.cs
Not sure how the original comment got there... I distinctly remember rewriting it :/
=> Fix glClearDepth for embedded systems

osu.Framework.Tests/Polygons/LineIntersections.cs, osu.Framework/Graphics/Primitives/Line.cs
Line-line intersections (not segment-segment) so intersection can lie outside the line segment.
=> Implement line-line intersections

osu.Framework/Graphics/Audio/WaveformGraph.cs
Want to use it to debug some CI errors.
=> Expose resampled waveform

osu.Framework.Tests/Visual/Drawables/TestCaseWaveform.cs, osu.Framework/Audio/Track/Waveform.cs
Fixes the "editor menu bar" test in https://ci.appveyor.com/project/peppy/osu/builds/24006765/tests (the exception actually comes from a background thread, just timed very well to appear in the editor test case).
=> Improve waveform testing + fix div-by-0

osu.Framework.Tests/Visual/UserInterface/TestCaseRigidBody.cs, osu.Framework.Tests/Visual/UserInterface/TestCaseSearchContainer.cs, osu.Framework.Tests/Visual/UserInterface/TestCaseTooltip.cs, osu.Framework/Graphics/UserInterface/BasicSliderBar.cs, osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs, osu.Framework/Testing/Drawables/TestBrowserToolbar.cs, osu.Framework/Testing/TestBrowser.cs
- Also update remaining cases of ``TestBox`` usage
- Add reset functionality to the playback rate by clicking the percentage next to the slider (I was unsure where to put it an how to mark it, the textbrowser doesn't have a default tooltip container)
=> Update parts of the testbrowser toolbar

osu.Framework.Tests/Visual/Testing/TestCaseTest.cs, osu.Framework/Development/DebugUtils.cs, osu.Framework/Platform/GameHost.cs, osu.Framework/Testing/TestCase.cs
Still wasn't correctly working via nuget consumption.
=> Move NUnitRunning to DebugUtils and improve entry assembly lookup

osu.Framework.Tests/Clocks/DecoupleableClockTest.cs, osu.Framework.Tests/Clocks/TestClock.cs, osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs, osu.Framework/Timing/InterpolatingFramedClock.cs
This could be considered a partial/temporary fix. Further clean-up will come via #2380.
=> Fix decoupled backwards seek

osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs, osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs, osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
Like mentioned in #2135, I wasn't sure what to do about the red circle and the time.
The backdrop of this section is also coded a bit ugly 😕
=> Add parts of the new testbrowser toolbar's record section design

osu.Framework/Graphics/Lines/Path_DrawNode.cs
=> Fix colour issue

osu.Framework.Tests/Visual/Drawables/TestCaseColourGradient.cs
The tests weren't actually testing linear vs srgb (srgb was used in all cases).
=> Add linear/srgb colour tests

osu.Framework.Tests/Bindables/BindableBindingTest.cs, osu.Framework.Tests/Lists/TestWeakList.cs, osu.Framework/Bindables/Bindable.cs, osu.Framework/Bindables/BindableList.cs, osu.Framework/Bindables/BindableNumber.cs, osu.Framework/Lists/LockedWeakList.cs, osu.Framework/Lists/WeakList.cs
```diff
|           Method |       Mean |     Error |     StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |-----------:|----------:|-----------:|------:|--------:|------:|------:|------:|----------:|
- |       BindUnbind |   2.932 us | 0.1667 us |  0.4863 us |  1.00 |    0.00 |     - |     - |     - |     336 B |
+ |       BindUnbind |   3.866 us | 0.3166 us |  0.9134 us |  1.00 |    0.00 |     - |     - |     - |     336 B |
- |      ChangeValue |  17.885 us | 0.3567 us |  0.5554 us |  5.99 |    0.93 |     - |     - |     - |   39960 B |
+ |      ChangeValue |  18.398 us | 1.0671 us |  3.0271 us |  5.04 |    1.49 |     - |     - |     - |         - |
- | ChangeBoundValue | 178.934 us | 3.4242 us |  4.0763 us | 57.79 |    7.79 |     - |     - |     - | …
```
=> Add enumerator to reduce WeakList allocations

osu.Framework/Game.cs
=> Remove unused PreFrame and PostFrame functions

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs
=> Allow null selections in tab controls

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs, osu.Framework/Graphics/UserInterface/TabControl.cs, osu.Framework/Graphics/UserInterface/TabItem.cs
=> Add support for multiline tab controls

osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs, osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
Fixes ppy/osu#4574
I've maintained the previous logic for the time being - the placeholder is loaded without a delayed load wrapper.
=> Refactor ModelBackedDrawable and improve testing

osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs
https://ci.appveyor.com/project/peppy/osu-framework/builds/24805254/tests
=> Fix potential ModelBackedDrawable testcase failures

osu.Framework/Audio/Track/TrackManager.cs
Not sure why it wasn't already. Mirrors implementation in SampleManager.
=> Make TrackManager implement IResourceStore

osu.Framework/Audio/AdjustableAudioComponent.cs, osu.Framework/Audio/AudioCollectionManager.cs, osu.Framework/Audio/AudioComponent.cs, osu.Framework/Audio/AudioManager.cs, osu.Framework/Audio/Sample/SampleChannelBass.cs, osu.Framework/Audio/Track/Track.cs, osu.Framework/Audio/Track/TrackBass.cs
- Refactors some documentation in audio components along the way.
=> Use aggregate bindable in AdjustableAudioComponent

osu.Framework/Audio/Sample/ISampleChannel.cs, osu.Framework/Audio/Sample/SampleChannel.cs, osu.Framework/Audio/Track/ITrack.cs, osu.Framework/Audio/Track/Track.cs
In preparation for drawable counterparts.
=> Add interfaces for audio components

osu.Framework/Bindables/AggregateBindable.cs
Aggressive locking. Closes #2455.
=> Fix potential thread safety issues with AggregateBindable

osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
=> Fix potential TextureWithRefCount test failure

osu.Framework/Graphics/UserInterface/Button.cs
Was previous white text on white background.
=> Give Button a sane default background colour

osu.Framework/Testing/ManualInputManagerTestScene.cs
Mirrors https://github.com/ppy/osu/pull/4945 for framework tests
=> Add toggle for input priority in manual input tests

osu.Framework/Graphics/Lines/Path.cs, osu.Framework/Graphics/Lines/Path_DrawNode.cs
=> Fix paths using the incorrect texture/rounded texture shaders

osu.Framework/Graphics/BufferedDrawNode.cs, osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs, osu.Framework/Graphics/DrawNode.cs
Can be useful elsewhere than `BufferedDrawable`.
=> Move DrawFrameBuffer() to DrawNode

osu.Framework/Graphics/DrawNode.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs, osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs, osu.Framework/Graphics/OpenGL/Vertices/DepthWrappingVertex.cs, osu.Framework/Graphics/Textures/Texture.cs, osu.Framework/Resources/Shaders/sh_Backbuffer_Internal.h
None of this has any effect, not even the `DepthWrappingVertex` change. Just cleanups.
=> Tidy up some loose ends from FTB changes

osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBufferedContainer.cs, osu.Framework/Graphics/BufferedDrawNode.cs, osu.Framework/Graphics/DrawNode.cs
Need to implement a software renderer at some point...
=> Fix draw depth not being set for BufferedContainer vertices

osu.Framework.iOS/Input/IOSKeyboardHandler.cs
=> Fix iOS not firing KeyEvent on software keyboard spacebar

osu.Framework/Graphics/Transforms/TransformCustom.cs, osu.Framework/MathUtils/Interpolation.cs
Quick/minor optimisation:
```diff
|    Method |       Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |-----------:|----------:|----------:|-------:|------:|------:|----------:|
- | Construct10 | 1.063 us | 0.0085 us | 0.0075 us | 0.8888 |     - |     - |   2.73 KB |
+ | Construct10 | 710.7 ns |  9.082 ns |  8.496 ns | 0.3805 |     - |     - |   1.17 KB |
```
=> Reduce allocations for each TransformCustom ctor

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs, osu.Framework/Graphics/Containers/BasicScrollContainer.cs, osu.Framework/Graphics/Containers/ScrollContainer.cs
=>  Fix clamped scrollbars moving beyond the scroll bounds

osu.Framework/Graphics/UserInterface/Menu.cs
Not splitting it into a basic component just yet - I'll leave that up to jorolf to do ;) (and see what other custom styling exists in these classes).
=> Add abstraction for menu's scroll container

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs, osu.Framework/Graphics/UserInterface/TextBox.cs
Also adds tests for other flows and improves test code quality.
Can be used to resolve https://github.com/ppy/osu/issues/5106.
=> Add ability to trigger textbox commits on focus loss

osu.Framework/Graphics/UserInterface/Dropdown.cs
Follows the same pattern defined in #2547
=> Store a reference to Dropdown.ItemSource internally

osu.Framework/IO/Network/WebRequest.cs
Fixes the issue mentioned [here](https://github.com/ppy/osu/pull/5000#discussion_r295394527).
=> Fix accessing disposed stream when a FileWebRequest 404s

osu.Framework.Tests/Bindables/BindableListTest.cs, osu.Framework/Bindables/BindableList.cs
Required for https://github.com/ppy/osu-framework/pull/2255
=> Add BindableList.RemoveRange

SampleGame.Android/Properties/AndroidManifest.xml, SampleGame.Android/SampleGame.Android.csproj, osu.Framework.Android/AndroidGameActivity.cs, osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj, osu.Framework.iOS/GameViewController.cs
Testing in simulator. Seems to work well enough.
=> Handle iOS/android memory alerts and free any memory we can

osu.Framework.Tests/Visual/Testing/TestSceneDrawVisualiser.cs, osu.Framework/Graphics/FrameworkFont.cs, osu.Framework/Graphics/UserInterface/Button.cs, osu.Framework/Graphics/Visualisation/PropertyDisplay.cs, osu.Framework/Graphics/Visualisation/TitleBar.cs, osu.Framework/Graphics/Visualisation/TreeContainer.cs, osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs, osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
As an aside, we may want to consider removing OpenSans and moving Roboto to the base framework distro.
=> Update draw visualiser design

osu.Framework/Statistics/PerformanceMonitor.cs
Aggregated at end of each frame.
=> Show all FrameStatistics in GlobalStatistics

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
Fixes [test failures](https://ci.appveyor.com/project/peppy/osu-framework/builds/25680590/tests).
=> Fix Markdown test by waiting for online retrieval to finish

osu.Framework.Tests/Threading/SchedulerTest.cs, osu.Framework/Threading/Scheduler.cs
To be used for https://github.com/ppy/osu/issues/5220
=> Add support for disabling automatic catch-up support in repeating tasks

osu.Framework/Graphics/Containers/FlowContainer.cs
It allows us to cleanup client code a little.
usage https://github.com/ppy/osu/pull/5205
=> Add FlowContainer.Insert method

osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs, osu.Framework.Tests/Platform/HeadlessGameHostTest.cs, osu.Framework/Platform/GameHost.cs
According to the PVS-Studio, these while loop based waitings are unreliable. See https://www.viva64.com/en/w/v3032.
Also, in my opinion they are ugly. :(
=> Replace Thread.Sleep waits with ManualResetEventSlim

osu.Framework.Android/AndroidGameView.cs, osu.Framework.Android/Input/AndroidInputConnection.cs, osu.Framework.Android/Input/AndroidKeyboardHandler.cs, osu.Framework.Android/Input/AndroidTextInput.cs
Using a custom IInputConnection to catch all input data produced by keyboard.
Closes #2631.
=> Fix android keyboard input

osu.Framework/Graphics/UserInterface/TextBox.cs
Prerequisite for https://github.com/ppy/osu/pull/5372
=> Remove unnecessary nested class in TextBox

osu.Framework.Tests/Visual/Testing/TestSceneGlobalStatisticsDisplay.cs, osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs, osu.Framework/Statistics/GlobalStatistic.cs, osu.Framework/Statistics/IGlobalStatistic.cs
=> Remove bindable/string allocation overhead of global statistics

osu.Framework/Graphics/Cursor/TooltipContainer.cs
Reduced to zero overhead when tooltip is not visible.
=> Reduce overhead incurred by TooltipContainer when no tooltip is visible

osu.Framework/Statistics/PerformanceMonitor.cs
I'm pretty sure this is what we intended it to be.
=> Fix HandleGC flag being set to an incorrect default

osu.Framework/Platform/NativeStorage.cs
Just reverting this for now (regressed in #2637).
=> Fix deleting logs potentially throwing exceptions

osu.Framework/Graphics/Lines/SmoothPath.cs, osu.Framework/Graphics/Textures/TextureWithRefCount.cs
Takes advantage of the disposal in https://github.com/ppy/osu-framework/pull/2672 to reduce finalizer load.
=> Use TextureWithRefCount for paths
