osu.Framework/Graphics/Shapes/Triangle.cs
osu.Framework/Graphics/Sprites/SpriteDrawNode.cs

The real issue I wanted to address here is the `InflationAmount / DrawRectangle` divisions leading to `NaN` values, but I think it makes more sense to simply not draw sprites with zero sizes than inlining conditions.

Fix zero-size sprites being drawn

---

osu.Framework/Threading/GameThread.cs

Allows for a bit of added flexibility. I am able to use this for instance to give `RealmAccess` a way to subscribe for notifications without being required to be called from the update thread. Without exposing this context here, the earliest point of obtaining it is in `Game.LoadComplete` which can be too late (and less guaranteed) for such scenarios.

Expose synchronisation context on `GameThread`

---

osu.Framework.Tests/Threading/SchedulerTest.cs

I'm still unsure if this one works every time...

Add test coverage of `AddOnce` with inline delegate

---

.git-blame-ignore-revs

ppy/osu#17569 but for framework

Ignore `Normalize all the line endings` commit in git blame

---

osu.Framework.Android/AndroidGameHost.cs
osu.Framework.Benchmarks/BenchmarkFontLoading.cs
osu.Framework.iOS.props
osu.Framework.iOS/GameAppDelegate.cs
osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/osu.Framework.iOS.csproj
osu.Framework/Extensions/ImageExtensions/ImageExtensions.cs
osu.Framework/Extensions/ImageExtensions/ReadOnlyPixelMemory.cs
osu.Framework/Extensions/ImageExtensions/ReadOnlyPixelSpan.cs
osu.Framework/IO/Stores/GlyphStore.cs
osu.Framework/IO/Stores/RawCachingGlyphStore.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/osu.Framework.csproj

This is required for supporting macOS image clipboards, requiring TIFF encoder/decoder which is supported in ImageSharp v2.1.0.
Breaking changes come from https://github.com/SixLabors/ImageSharp/pull/1730/https://github.com/SixLabors/ImageSharp/issues/1739.
The important one is that `ArrayPoolMemoryAllocator` has been completely replaced with the new and default [`UniformUnmanagedMemoryPoolMemoryAllocator`](https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs), which is still partially `ArrayPool`-based for smaller allocations, but uses a [different pool implementation](https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Memory/Allocators/Internals/UniformUnmanagedMemoryPool.cs) for larger allocations. …

Bump `SixLabors.ImageSharp` to v2.1.0

---

osu.Framework.Tests/Visual/Platform/TestSceneClipboard.cs
osu.Framework/Platform/MacOS/MacOSClipboard.cs
osu.Framework/Platform/MacOS/Native/Cocoa.cs
osu.Framework/Platform/MacOS/Native/NSData.cs

The implementation focuses on conversion between `NSImage` and `ImageSharp.Image<TPixel>` using [`TIFFRepresentation`](https://developer.apple.com/documentation/appkit/nsimage/1519841-tiffrepresentation?language=objc) (which requires ImageSharp v2.1.0 for TIFF decoding/encoding support).
This would've been much easier without implementing the interop logic for it. Waiting for the day where we can separate macOS platform to its own project targeting `net6.0-macos`, and not have to do all this interop stuff.

Add image clipboard support for macOS

---

osu.Framework/Graphics/OpenGL/GLWrapper.cs

Was causing issues in my VBO optimisations branch, because this is being used to clip quads in the FTB pass and would sometimes result in unmatching vertices.
Unsure if this would be noticeable normally.

Fix MaskingInfo equality not considering conservative quad

---

osu.Framework.Tests/Audio/SampleBassTest.cs
osu.Framework.Tests/Audio/TrackBassTest.cs
osu.Framework/Audio/Sample/SampleChannelBass.cs
osu.Framework/Audio/Track/TrackBass.cs

- Closes https://github.com/ppy/osu-framework/issues/4396 
- Resolves https://github.com/ppy/osu/discussions/17361
`SampleChannelBass` is refactored to work in a similar manner to `TrackBass`, for ensuring that the zero frequency handler doesn't affect the state of `playing` when manipulating that during a stop call.
It has been mentioned in https://github.com/ppy/osu-framework/pull/4395#issue-865952658 that this is a bit involved, so I'm slightly wondering if I'm missing something with the current solution (cc @smoogipoo).

Fix tracks/samples not updating running state immediately

---

osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs

At first I started over-complicating the algorithm further, before realising it doesn't need to be so complicated in the first place for basically 3-5x speedup in all cases.
I'm PRing this still in a disabled state because it's as good as the performance is going to get for this method, but I'm still not sure about enabling it because the worst case is still significant. Any other tricks like using `unsafe` or similar either doesn't yield any benefit or yields a benefit of 200us in the worst (3840x2160) case I tested.
For the record, I have done some profiling with this and:
1. This method takes ~2ms every entry of song select. Takes ~7ms scrolling through around 100 beatmaps in the beatmap listing.
2. On average get ~0.05ms HIGHER frametime, but also on average less GPU utilisation in …

Optimise texture opacity computation algorithm

---

osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
osu.Framework/Graphics/Animations/Animation.cs
osu.Framework/Graphics/Animations/DrawableAnimation.cs
osu.Framework/Graphics/Animations/TextureAnimation.cs

Added test fails at two different places depending on which of the two follow-up commits are built. Felt it was easier to bunch these together due to how intertangled they are.
- efc56b9bb Fixes `Animation` not updating display on adding a single frame after clearing previous frames.
- 0ce46fb60 Fixes previous display not getting cleared on calling `Animation.ClearFrames`

Fix issues with `Animation.ClearFrames` behaviour

---

.github/workflows/ci.yml

Run 1:
https://github.com/smoogipoo/osu-framework/runs/6018943569?check_suite_focus=true
Run 2:
https://github.com/smoogipoo/osu-framework/runs/6019049500?check_suite_focus=true
According to https://github.com/actions/cache, the default branch cache is available in other branches.

Add inspectcode CI cache

---

osu.Framework/Allocation/DependencyActivator.cs

Added to the static ctor since this can be used during normal game execution as well (though we don't encourage development that way).

Clear DI activators on hot reload

---

osu.Framework.Tests/TestGame.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Testing/TestBrowser.cs

This has been a pain point while testing for the longest time, where you hit escape expecting to interact with a test scene but instead exit the test browser.
Use Alt+F4, Cmd-W/Q or similar to exit instead. Or hook escape back up in your own `TestBrowser` implementation if you so choose.

Remove escape to exit test browser

---

osu.Framework/Audio/AudioManager.cs
osu.Framework/Testing/TestSceneTestRunner.cs

Over the past few days, it has been quite annoying running full tests suite in terms of audio, as initializing mixers could result in some soft audio ticks (due to mixers having 0ms buffer), and some tests may directly modify the audio volume levels for testing convenience (see https://github.com/ppy/osu/blob/0099af87ff7e43e75c30c2105cd39fc52cfc996a/osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs#L239-L249).
Have gone with the simplest fix of limiting audio devices to only "No sound", to make sure absolutely nothing is outputted to any of my actual audio devices. This is done as a better replacement to the current `AudioManager.Volume.Value = 0` logic in `TestSceneTestRunner`.
Alternative solution would be muting BASS at a global level, but we might as well never output to an …

Always use "No sound" audio device on headless test runs

---

osu.Framework/Game.cs

With the recent change to test browser exit logic (https://github.com/ppy/osu-framework/pull/5101), it became obvious that... no game can actually exit without manually overriding `OnExiting`. Like what? Am I missing something? How did people use osu!framework until now?
Can reproduce with `SampleGame` or osu! visual test browser..

Fix incorrect `Game` exit blocking default

---

osu.Framework/Graphics/UserInterface/Dropdown.cs
osu.Framework/Graphics/UserInterface/Menu.cs

As of https://github.com/ppy/osu-framework/pull/5054, it was feasible that `OnSelected` would be fired by a `DrawableDropdown` on its child items before they were `IsLoaded`. If an implementation relied on `OnSelected` to update the colour state correctly, this would have caused a potential regression in behaviour due to calls to `Update*Colour` not happening when `!IsLoaded`.
https://github.com/ppy/osu-framework/blob/963f15675c07c654cbb8f5627d5999080131f1e9/osu.Framework/Graphics/UserInterface/Dropdown.cs#L496-L503
Note that the framework implementation was saved by the ad-hoc logic in `LoadComplete` (which would not work for osu! due to not having the correct overrides):
https://github.com/ppy/osu-framework/blob/963f15675c07c654cbb8f5627d5999080131f1e9/osu.Framework/Graphics/UserInterfac …

Standardise `DrawableMenuItem` colour update logic

---

osu.Framework.Tests/Platform/GameExitTest.cs
osu.Framework.Tests/TestGame.cs
osu.Framework/Game.cs
osu.Framework/Platform/GameHost.cs

As correctly pointed out by @Joehuu, all of the recent troubles with the exit flow breaking originated in #5097, namely the [change to `GameHost` therein](https://github.com/ppy/osu-framework/pull/5097/files#diff-c694d93cea53f76879738dce61918a64bc3110e7df817250864f1f4754607512). This led to *unintentional API breakage in the latest framework release* and as such I think it makes sense to just revert it. The explanation why it is a regression is very simple but also stems from some very confusing code:
| `response` | `response ?? false` | `response == false` |
| :-: | :-: | :-: |
| `true` | `true` | `false` |
| `false` | `false` | `true` |
I'm not including the `null` case, as it was never reachable due to how the surrounding code is structured - [it is guaranteed that `response` is not …

Fix accidental API breakage of `Game.OnExiting()` return value

---

osu.Framework/IO/Network/WebRequest.cs

Partially solves https://github.com/ppy/osu/discussions/17897.
See https://github.com/dotnet/runtime/issues/30222 for reference.
As a disclaimer, I haven't tested this apart from confirming it doesn't
break a flow with no proxy specified. But should work in theory.

Provide default proxy credentials to `HttpClient`

---

osu.Framework.Tests/Platform/GameExitTest.cs
osu.Framework/Platform/GameHost.cs

Initially I was just looking to fix the weird conditional (3b8c1a36e), but noticed the test is quite slow to execute.
I think the original code was a bit too safe. Internally the `host.RequestExit()` call is blocking until the exit has been handled, but I can understand that we may be trying to black box test here to avoid any uncertainty.
If this solution is seen as unsatisfactory then we can count update frames or something. I'd just like to avoid a single test taking 10 seconds to run while spinning.

Fix `TestExitBlocking` taking 10 seconds to run

---

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
osu.Framework.Tests/Visual/Input/TestSceneClickLenience.cs
osu.Framework/Graphics/Containers/ScrollContainer.cs
osu.Framework/Input/Events/DragStartEvent.cs

- Closes #3576
This changes drag event handling and scroll event handling in `ScrollContainer`s to be based on their `ScrollDirection`, to allow for layered scroll containers to coexist.
This however becomes a nuisance on two parts:
- https://github.com/ppy/osu-framework/commit/20c1d72502c4f85d5e23def9a28aa02a5725dbb6: In order for scroll containers to coexist, the innermost must not `OnMouseDown` to let the parenting scroll containers enter the mouse-down/drag input queue, for receiving drag events.
I'm not entirely sure if there's a reason for that in the first place, checking with git blame threw me back to 4 years ago (https://github.com/ppy/osu-framework/pull/316).
- https://github.com/ppy/osu-framework/commit/7bff9b96bebc982b5dfabf75cd714b41237bf25a: When a scroll container is …

Allow layered `ScrollContainer`s to coexist on input handling

---

osu.Framework/Platform/SDL2/SDL2Extensions.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

The log message renders as:
```cs
[runtime] 2022-04-23 16:09:22 [verbose]: Unknown SDL key: SDL_SCANCODE_APPLICATION, SDLK_APPLICATION
```
The log will help if more unknown keys crop up in the future (as there are many scancodes we're not handling).
The menu key is reported by windows/SDL as `SDL_SCANCODE_APPLICATION`, and is listed as such on the [SDL wiki](https://wiki.libsdl.org/SDL_Scancode):
- "Application" (the Application / Compose / Context Menu (Windows) key)

Add mapping for the windows context menu key (and log unknown SDL keys)

---

osu.Framework.Tests/Visual/UserInterface/TestSceneClosableMenu.cs
osu.Framework/Graphics/UserInterface/Menu.cs

- Closes ppy/osu#17961
Was previously relying on its `ScrollContainer` layer which used to block mouse down from drawables behind it, until https://github.com/ppy/osu-framework/pull/5118.

Fix `Menu` not handling mouse down events

---

osu.Framework/Game.cs
osu.Framework/Graphics/UserInterface/Menu.cs

For some reason these didn't get caught up by CI in #5121, I guess `IDExxxx` inspections in general don't get caught unless using `dotnet format`..?
(inspection is `IDE0062`)

Mark local methods as `static` where possible to appease Rider

---

osu.Framework/Game.cs
osu.Framework/Localisation/LocalisationManager.cs
osu.Framework/Localisation/LocalisationParameters.cs

After writing up a [wiki page regarding localisation](https://github.com/ppy/osu-framework/wiki/Localisation), it turns out `LocalisationParameters` isn't actually extensible given the way it's currently created and updated in `LocalisationManager`, along with the fact that there's no `CreateLocalisationManager` to create the custom subclass with.
The end goal would be to extend `LocalisationParameters` from a consumer project with simplicity in mind:
```csharp
protected override LocalisationManager CreateLocalisationManager(FrameworkConfigManager frameworkConfig) 
=> new CustomLocalisationManager(frameworkConfig, localConfig);
public class CustomLocalisationManager : LocalisationManager
{
private readonly IBindable<int> custom = new BindableInt();
public …
```

Improve extensibility of `LocalisationParameters`

---

osu.Framework.Tests/Localisation/LocalisableDescriptionAttributeTest.cs
osu.Framework/Extensions/ExtensionMethods.cs

As reported in [discord](https://discord.com/channels/188630481301012481/589331078574112768/968412471448707092), `GetLocalisableDescription` does not handle the case where the generic type is `Type`, since `Type.GetType() != Type`.

Fix `GetLocalisableDescription` not handling `Type` inputs properly

---

osu.Framework.Benchmarks/BenchmarkLocalisableString.cs
osu.Framework.Tests/Localisation/LocalisableStringTest.cs
osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework/Extensions/LocalisationExtensions/LocalisableStringExtensions.cs
osu.Framework/Localisation/LocalisableFormattableString.cs
osu.Framework/Localisation/LocalisableString.cs
osu.Framework/Localisation/TranslatableString.cs

- May resolve https://github.com/ppy/osu/issues/17953
Upon discussion in [discord](https://discord.com/channels/188630481301012481/589331078574112768/966564266343817266), it turns out the current way to format `LocalisableString`s or create interpolation is via `TranslatableString` with a random key (e.g. `_`), which feels counter-intuitive.
I've cleaned things up by moving the format and interpolation logic from `TranslatableString` to `LocalisableFormattableString`, and sharing it to `TranslatableString` via inheritance (rationale is that `TranslatableString` shouldn't really bother with the formatting logic, and `LocalisableFormattableString` currently exists but has been incomplete). 
Allowing for formatting and interpolation support via `LocalisableFormattableString` instead:
```diff …
```

Improve `LocalisableString` formatting and interpolation API

---

osu.Framework.Tests/Visual/Drawables/TestSceneUpdateBeforeDraw.cs
osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
osu.Framework/Extensions/ExtensionMethods.cs
osu.Framework/Platform/Display.cs
osu.Framework/Platform/DisplayMode.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2/SDL2Extensions.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

Should fix https://github.com/ppy/osu/issues/17804.
The problem boils down to differences between [`SDL_GetWindowDisplayMode`](https://wiki.libsdl.org/SDL_GetWindowDisplayMode) and [`SDL_GetCurrentDisplayMode`](https://wiki.libsdl.org/SDL_GetCurrentDisplayMode). The former (roughly) gives the display mode that would be used if the window were set to fullscreen (without changing the mode). So in windowed, it could match a resolution lower than the native one (and presumably a high refresh rate display supports only 60 Hz on lower resolutions).
For that reason, we use `SDL_GetCurrentDisplayMode` in windowed modes which will give us the correct (desktop) mode.
As noted by the TODOs, some things are still broken.
- `CurrentDisplayMode` will always have an invalid index (-1) (not really …

Improve `CurrentDisplayMode` logic in `SDL2DesktopWindow`

---

osu.Framework.iOS/GameUIApplication.cs
osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/IOSGameView.cs
osu.Framework.iOS/Input/IOSHardwareKeyboardHandler.cs
osu.Framework.iOS/Input/IOSTextFieldKeyboardHandler.cs
osu.Framework.iOS/Input/IOSTextInput.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

- Closes #5143 
Gladly this didn't require reverting #5106. Done by keeping the `IOSHardwareKeyboardHandler` active all the time, and avoid duplicating input if handled by `IOSTextFieldKeyboardHandler`.
This can be best reviewed commit-by-commit, to explain how this was approached and what it has changed.
I have tested this on an iOS simulator and confirmed text shortcuts work now, but as I was testing this, for some reason some keys get stuck in a pressed state, and I have no clue how to tell if it's due to the game running poorly due to OpenGL or otherwise.
@peppy please check that this is working alright for you, and that pasting works properly from both hardware keyboard and software keyboard, and that no keys actually get stuck in pressed state (if that occurs, pressing left/right or …

Fix iOS text key shortcuts no longer working

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs
osu.Framework/Properties/AssemblyInfo.cs

So that iOS key bindings don't have to be updated separately. Currently, `IOSGameHost` is missing some key bindings from `MacOSGameHost`, while all the existing ones match:
```diff
diff --git a/osu.Framework.iOS/IOSGameHost.cs b/osu.Framework.iOS/IOSGameHost.cs
index ffed393d1..267cff408 100644
--- a/osu.Framework.iOS/IOSGameHost.cs
+++ b/osu.Framework.iOS/IOSGameHost.cs
@@ -132,9 +132,24 @@ public override VideoDecoder CreateVideoDecoder(Stream stream)
new KeyBinding(new KeyCombination(InputKey.Super, InputKey.Shift, InputKey.Right), PlatformAction.SelectForwardLine),
new KeyBinding(new KeyCombination(InputKey.Alt, InputKey.Super, InputKey.Left), PlatformAction.DocumentPrevious),
new KeyBinding(new KeyCombination(InputKey.Alt, InputKey.Super, InputKey.Right), …
```

Use same key bindings on macOS and iOS

---

SampleGame.iOS/Info.plist
osu.Framework.Tests.iOS/Info.plist

Having these match `sh.ppy.*` allows for using a single wildcard provisioning certificate.

Fix iOS bundle identifiers not having correct prefix

---

.github/workflows/build-ffmpeg.yml
osu.Framework/Graphics/Video/VideoDecoder.cs

Aimed at increasing compatibility with older systems: https://github.com/ppy/osu-framework/issues/4349#issuecomment-1114013393
Supports Ubuntu 16.04 and Ubuntu 18.04 (both of which are LTS). Note that o-f won't actually run on 16.04 because our libSDL2 doesn't support it.
Sample workflow run: https://github.com/smoogipoo/osu-framework/actions/runs/2252698181
Tested on:
- Ubuntu 18.04
- My much more up to date Arch Linux with glibc 2.35.

Use ubuntu:16.04 for linux FFmpeg builds

---

osu.Framework/Graphics/Containers/Markdown/IMarkdownTextComponent.cs
osu.Framework/Graphics/Containers/Markdown/IMarkdownTextFlowComponent.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs

As seen in https://github.com/ppy/osu/pull/18049, it can be easy to forget adding the caching of these interfaces. I believe all usages of the interfaces intend to also cache (as that is the main purpose of the interface existing).
Rendering still seems to work okay.
Closes https://github.com/ppy/osu/issues/18039.

Move caching specifications of markdown interfaces to be attached to the interfaces

---

osu.Framework.Tests/Platform/GameExitTest.cs

I've gone through the testing procedure and code and cannot understand nor replicate how this can happen. Might be able to understand better with these modifications?
Reference:
https://github.com/ppy/osu-framework/runs/6254153200?check_suite_focus=true
https://github.com/ppy/osu-framework/runs/6240530753?check_suite_focus=true
https://github.com/ppy/osu-framework/runs/6227330132?check_suite_focus=true
Interested if anyone else can see an issue with the testing methodology.

Adjust `GameExitTest` to attempt to understand CI failures

---

osu.Framework.Tests/Platform/GameExitTest.cs

As has been seen in multiple CI builds:
- https://github.com/ppy/osu-framework/runs/6254153200?check_suite_focus=true
- https://github.com/ppy/osu-framework/runs/6254441826?check_suite_focus=true
`GameExitTest` has been failing intermittently when ran in single-thread mode. 
The reason is that, as the host is running in the background using a .NET long running task, the test requests exiting by directly calling it from the test's main thread.
When waiting for result from the `Exiting` event, on single-thread mode, `GameHost` would loop on the threads from the thread the exit was requested from:
https://github.com/ppy/osu-framework/blob/3b8c1a36e7ed73803c042f645c9eee34e0700386/osu.Framework/Platform/GameHost.cs#L407-L414
In a normal scenario, this can only be the one and only thread …

Fix intermittent test failures in `GameExitTest` due to race condition

---

osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
osu.Framework/Graphics/Video/VideoDecoder.cs
osu.Framework/IO/Network/WebRequest.cs
osu.Framework/Input/Handlers/Tablet/AbsoluteTabletMode.cs
osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
osu.Framework/Platform/DesktopGameHost.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs
osu.Framework/Properties/AssemblyInfo.cs
osu.Framework/Statistics/BackgroundStackTraceCollector.cs
osu.Framework/Statistics/DotNetRuntimeListener.cs

This has became an issue on Xamarin projects when using Rider, as it assumes `NET6_0` is defined in `AssemblyInfo.cs` for some reason, while works correctly with `NET6_0_OR_GREATER`.
https://user-images.githubusercontent.com/22781491/166141013-a84e2c83-14b5-48c6-95be-92e44ad6e9c7.mp4
Best to migrate to `NET6_0_OR_GREATER` anyways since it's the correct way of checking.
Note that regardless of this change, ReSharper on `AssemblyInfo.cs` in the desktop project will for some reason think neither `NET6_0` nor `NET6_0_OR_GREATER` is defined (only `NETSTANDARD2_1`). Probably a ReSharper bug.

Replace `NET6_0` with `NET6_0_OR_GREATER` instead

---

osu.Framework.Tests/Visual/Input/TestScenePlatformActionContainer.cs
osu.Framework/Platform/GameHost.cs

Closes #5157
I believe this shouldn't apply to macOS, because that has [an entirely disparate set of platform keybindings](https://github.com/ppy/osu-framework/blob/80cffac85458e307d02bfa804d7da4d47405095f/osu.Framework/Platform/MacOS/MacOSGameHost.cs#L67-L118), but would appreciate testing to make sure.
Diff includes simple manual test scene for testing convenience (press any platform binding and the boxes will flash):

Add Ctrl+Y as an alternative "redo" platform binding

---

osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
osu.Framework/Allocation/CachedAttribute.cs

This has been a point of confusion twice (?) this week now, with the latest instance being [here](https://github.com/ppy/osu/pull/18101#discussion_r865650509). So this expands xmldoc to the point where this *hopefully* isn't an issue anymore.
Test coverage for the inheritance edge cases described in the new xmldoc attached within.

Clarify usage of `[Cached]` when placed on classes/interfaces in xmldoc

---

osu.Framework.Tests/Visual/Input/TestScenePlatformActionContainer.cs

Eg. `Delete` and `DeleteForwardChar` are both mapped to the `Del` key, and only one would highlight previously.
`Exit` is still handled to allow testing without closing the window.

Fix `PlatfomAction` test not highlighting actions that map to the same key combination

---

osu.Framework.Tests/Visual/Platform/TestSceneWindowed.cs
osu.Framework/Configuration/FrameworkConfigManager.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

Not sure why, but Windows treats `int.MaxValue` as zero here.
This would result in the window being forced to resize to minimum size (640x480) when trying to move or resize it.

Fix default maximum size being invalid on Windows

---

osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

Depends on:
Partially resolves #4055. Now the issue only happens when relative mode is enabled.
To get mouse capture for relative mode, we'd probably want to do it locally in `MouseHandler` by keeping track of pressed buttons.

Enable `SDL_HINT_MOUSE_AUTO_CAPTURE` when not using relative mode

---

osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs
osu.Framework/Graphics/Containers/IHasFilterTerms.cs
osu.Framework/Graphics/Containers/SearchContainer.cs
osu.Framework/Graphics/Sprites/SpriteText.cs
osu.Framework/Testing/Drawables/TestButtonBase.cs
osu.Framework/Testing/Drawables/TestGroupButton.cs

- Needed for https://github.com/ppy/osu/pull/18270, from feedback.
Note this change will require each class which inherits `IHasFilterTerms` (about 20 in osu!lazer) to have their definition of `FilterItems` be a `IEnumerable<LocalizedString>`
Now SearchContainer should match based on base text **and** localised text.

Support matching by both base and localised text in `SearchContainer`

---

osu.Framework.Android/Input/AndroidMouseHandler.cs
osu.Framework/Input/Events/ScrollEvent.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Testing/Input/TestCursorContainer.cs

- Closes: #5167
Tested on:
- iPadOS/iOS (just to confirm it's the same as macOS)
Breaking changes
---
`ScrollEvent.ScrollDelta.X` (horizontal scrolling) is now consistent across platforms. Previously, Windows, Linux and Android were inverted. As a reminder:
> Delta is positive when mouse wheel scrolled to the up or left, in non-"natural" scroll mode (ie. the classic way).

Fix horizontal scrolling being inverted on non-Apple platforms

---

osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/Application.cs
osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/Info.plist
osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/Info.plist

- Fixes iOS template projects not running at all
- Enables 120Hz support on template projects
- Enables indirect input events for proper mouse support on template projects

Sync iOS template projects inline with latest changes

---

osu.Framework.Android/global.json
osu.Framework.Android/osu.Framework.Android.csproj
osu.Framework.iOS/global.json
osu.Framework.iOS/osu.Framework.iOS.csproj

An interim fix until https://github.com/ppy/osu-framework/pull/5080 is merged, intended to fix the recent Android build failures such as https://github.com/ppy/osu-framework/runs/6464582633?check_suite_focus=true
I've changed the iOS project to match.
Haven't tested @peppy 's local build/deploy pipelines.

Fix Android project failing to build on CI

---

osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs

- Closes #5183
Brings other platforms in line with macOS, where horizontal scrolling is applied at OS level.
Doesn't apply to [precision touchpads](https://discord.com/channels/188630481301012481/589331078574112768/976734156576915516), as 2D scrolling is always supported there natively.
Shift+scroll is used in the osu! editor for faster scrolling, but this change doesn't affect that as the components are [added together](https://github.com/ppy/osu/blob/ab5c736da1a8d3ab99f85a4621bc97a254834dc2/osu.Game/Screens/Edit/Editor.cs#L530).

Add support for horizontal scrolling via Shift key 

---

osu.Framework/Platform/NativeStorage.cs
osu.Framework/Platform/Storage.cs

Abstract methods in storage are only required where they are used to change actual file or path access. Because `CreateFileSafely` is performing all actions via calls to the `Storage` API, it does not need an `abstract` implementation.
---
For the full ratification of this change:
While integrating these changes in osu! side, I found unexpected test failures due to the fact that the `NativeStorage` implementation of this function is passing itself as a storage.
In osu!, we have the concept of a `WrappedStorage`, where all calls for path lookups are supposed to be re-routed. Due to the structure of how this was implemented, it was actually impossible to get correct behaviour, unless changing `WrappedStorage` to implement `NativeStorage` (and use the existing implementation of …

Move `CreateFileSafely` implement to non-virtual to avoid potential misuse

---

.github/workflows/ci.yml

Linux `libavformat` native libraries are now packaged with framework.

Remove redundant installation of `libavformat` in Linux CI runs

---

osu.Framework.NativeLibs/scripts/ffmpeg/common.sh

Hoping to pre-empt any future issues like https://github.com/ppy/osu/issues/18379 from arising.
As per https://github.com/ppy/osu-framework/runs/6209510854?check_suite_focus=true (see the `Build` step):
- The Windows build does not link to lzma/bz2/sdl/etc because those libs are unavailable in the first place.
- This PR disables lzma/bz2/sdl for Linux/macOS to match, as well as ALSA/X11 linking.
- The Windows build links to `schannel`, which is for TLS/SSL support, but we don't support networking in FFmpeg.
- This PR disables `schannel`.
I've tested the Linux build on the o!f visual test + https://osu.ppy.sh/beatmapsets/6687#osu/29955, haven't tested the Windows/macOS build.

Disable more unnecessary FFmpeg external libs

---

osu.Framework/Platform/SDL2/SDL2Extensions.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

Helps for debugging issues such as:
- https://github.com/ppy/osu/issues/18273#issuecomment-1126901064
- https://github.com/ppy/osu-framework/issues/5190
I originally intended to check return values for all native SDL calls, but this resulted in really ugly (and unnecessary) code.
This PR is an intermediate step to better handling of SDL errors, allowing us to see where potential problems may arise, and where special handling may be needed.
Setting the log handler before `SDL_Init` is probably wrong, so that has separate handling.
Since setting `SDL_LogSetOutputFunction` will take full control over SDL logging, all log messages need to be handled. Can't only handle the errors, as that will drop logs from eg. `SDL_HINT_EVENT_LOGGING`, which are useful for debugging.
The log priority for …

Log SDL errors (and forward SDL logs to framework logs)

---

osu.Framework/Input/Handlers/Midi/MidiHandler.cs

Also fix initialisation loop continuing to execute every 500ms even after an error.
As noticed at https://sentry.ppy.sh/organizations/ppy/issues/836/events/ce98f382a4cb4aa990c22c90def42c27.

Reduce verbosity of midi initialisation failure

---

osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs

The following is a typical usage of binding to events of DI'd members:
```csharp
#nullable enable
public class MyDrawable : Drawable
{
[Resolved]
private SomeObject SomeDependency { get; set; } = null!;
protected override void LoadComplete()
{
base.LoadComplete();
SomeDependency.SomeEvent += someMethod;
}
private void someMethod()
{
}
protected override void Dispose(bool disposing)
{
base.Dispose(disposing);
if (SomeDependency != null) // WARNING: Expression is always true according to NRT rules.
SomeDependency.SomeEvent -= someMethod;
}
}
```
I propose the `IsNull()`/`IsNotNull()` extension methods in order to bypass the warning inside `Dispose()` and increase our coverage of NRT. The resultant code becomes:
```csharp
protected override void Dispose(bool disposing)
{ …
```

Add IsNull()/IsNotNull() helper extensions

---

osu.Framework/Testing/TestScene.cs

Previously this would be occurring many times during game load, causing crippling test performance in scenarios where the game takes considerable time to load.

Avoid GC overhead during game load by only doing a full blocking collect at the end of a test run

---

osu.Framework/IO/Stores/GlyphStore.cs

This doesn't improve test performance in local testing as much as I hoped for, but it does reduce alloc traffic and may convert to better savings on CI runs. Note that the benefit is not seen in o!f test runs due to far less fonts being loaded in the first place.
If this isn't seen as a quick merge for one reason or another I'm okay with closing instead.

Statically cache font parsing results to reduce unit test overhead

---

osu.Framework/Threading/GameThread.cs
osu.Framework/Threading/GameThreadSynchronizationContext.cs

During test runs, realm could potentially hold a `SynchronizationContext` open beyond known `GameHost` lifetime. By extension, a previous game instance could be referenced via a long reference path.
I foresee this change may be hard to swallow in the current location (I'm not sure how correct it is to stop executing events that reached the `SynchronizationContext` when the `scheduler` goes away). Open to any other suggestions of where we should be resolving this. Potentially calling `UnregisterThread` on host shutdown? Using a `WeakReference` to the `GameThread`?
Note that I'm also looking into multiple other similar issues, including why realm is holding the reference in the first place (is probably our fault). If this direction or the others proposed above are not seen as correct, the …

Fix test performance overhead due to held references of previous `GameHost`s

---

osu.Framework/Graphics/Textures/TextureUpload.cs

Running osu! navigation test namespace sees a reduction of around 6%
(Left is this PR)

Use pooled memory for texture uploads to avoid an extra memory allocation

---

osu.Framework/Platform/Windows/FullscreenCapability.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

Using the API [`SHQueryUserNotificationState`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shqueryusernotificationstate).
The state enters `QUNS_RUNNING_D3D_FULL_SCREEN` even for OpenGL applications. Otherwise, like on my Optimus-enabled laptop, the state enters `QUNS_BUSY`.
You can't seem to be able to query this value right away - it takes some time after the mode change. I've set a 5s timer before the value is queried.
Testing:
- Message does not show.
- Detects capable.
- Detects capable.
- Detects incapable.
- Detects capable.
Not sure about these ones:
- Optimus laptop + Windows (Intel HD Graphics 530 + GTX 960M) iGPU:
- Detects incapable.
- Laptop + Windows (Intel HD Graphics 4400, iGPU only)
- Detects incapable.
- Desktop + Windows (Intel HD Graphics …

Detect exclusive fullscreen on Windows

---

osu.Framework/Graphics/Audio/WaveformGraph.cs

As seen osu!-side during profiling spiky behaviour on waveforms changing position (but not actually being resampled).
https://user-images.githubusercontent.com/191335/171110238-2da561de-7a0d-47e2-aeac-1ec0efaf1811.mp4

Avoid unnecessary copy operations between `Waveform` and its draw node

---

osu.Framework/Platform/ThreadRunner.cs
osu.Framework/Threading/GameThread.cs

- Closes #5216
- Fixes [OSU-G6](https://sentry.ppy.sh/organizations/ppy/issues/547/?referrer=github_integration)
I've omitted the timeout as it will break the synchronicity of the exiting process. If the timeout is something that is wanted, it can be added back, but `throw`ing instead of just logging (and should probably apply to the `while` loops as well).

Synchronously exit `ThreadRunner` threads

---

osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
osu.Framework.Tests/Extensions/TestIsNullableTypeExtensions.cs
osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
osu.Framework/Allocation/ResolvedAttribute.cs
osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs

```csharp
#nullable enable
class MyDrawable : Drawable
{
// Non-null dependency.
[Resolved]
private object NonNullDependency { get; set; } = null!;
// Nullable dependency.
// [Resolved(CanBeNull = true)] : Not required anymore!
[Resolved]
private object? NullableDependency { get; set; } 
// [BackgroundDependencyLoader(true)] : Not required anymore!
[BackgroundDependencyLoader]
private void load(object param1, object? param2)
{
}
}
```
This is only supplementary behaviour - supplying the nullable parameters of `[Resolved]` and `[BackgroundDependencyLoader]` preserves the previous functionality of injecting nulls.

Support nullable reference types for dependency injection

---

osu.Framework.Tests/IO/TestWebRequest.cs
osu.Framework/IO/Network/WebRequest.cs

This allows identifying this scenario in client usage. This can be used to fix the issue seen at https://github.com/ppy/osu/issues/18524#issuecomment-1144428852, where the flow is:
- Game makes request
- Game cancels request before `Perform` fires its `Task`'d `PerformAsync` 
- `WebRequest` reports invalid operation
I'm not sure about the exception types here. Should we also throw an `OperationCanceled` from the `Perform` flow, rather than `TaskCanceled` that comes from .NET itself?
osu-side relevant fix would be something like https://github.com/ppy/osu/compare/master...peppy:web-request-canceled-fix?expand=1

Throw `OperationCanceledException` when `Perform`ing a `WebRequest`after `Abort`

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

- Closes #5170
Not really sure what the existing code was doing. `insertString()` will move the caret to the expected position (end of text).
Includes some very rudimentary tests.

Clear textbox selection when setting via `Text` or `Current`

---

osu.Framework.Tests/Polygons/ConvexPolygonClipperFuzzingTest.cs
osu.Framework.Tests/Polygons/ConvexPolygonClippingTest.cs
osu.Framework.Tests/Polygons/LineIntersections.cs
osu.Framework/Graphics/Primitives/SimpleConvexPolygon.cs
osu.Framework/Graphics/Vector2Extensions.cs
osu.Framework/Utils/ConvexPolygonClipper.cs

Should fix https://github.com/ppy/osu/issues/17215
Although I'm not entirely sure on what's causing the above issue, I believe it will be fixed based on running the new fuzzing test for 1hr with no failures. It generates many millions of polygons; concave, convex, lines, etc, and then performs clipping on them.
To be honest, this is a bit of a workaround because I can't really find that much documentation on these edge cases nor can I find documentation of others using a fixed buffer size as we're doing. I can only assume that using a fixed buffer size for this algorithm is incorrect.
There are two fixes applied here:
1. Increasing the total buffer size to assume every line can be intersected with every other.
2. Making collinear points not be counted as being "in the right half plane of …

Fix convex polygon clipper edge cases

---

osu.Framework.Tests/Platform/GameExitTest.cs
osu.Framework/Game.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

- Resolves #5194 
- Closes #5193 
- Fixes [OSU-C](https://sentry.ppy.sh/organizations/ppy/issues/13/?project=2)
The 'exit requested' event is now processed like any other window event, leaving it to the `Game` to handle it and exit the host.
Since `Game.OnExitRequested()` is called the same as before, this PR has no breaking changes.

Simplify exiting flow

---

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
osu.Framework/Graphics/Containers/IScrollContainer.cs
osu.Framework/Graphics/Containers/ScrollContainer.cs

- Closes https://github.com/ppy/osu/issues/18550
In #5118, scroll containers have changed to not accept drags/scrolls when containing a greater horizontal component, but that produces a bad UX as seen in https://github.com/ppy/osu/issues/18550, especially on dragging where starting a horizontal drag then continuing vertically no longer works.
Now the new behaviour will only happen when the scroll container is nested inside of another scroll container that accepts the other direction.

Improve scrolling/dragging experience on singular scroll containers

---

osu.Framework.Tests/Visual/Drawables/TestSceneSynchronizationContext.cs
osu.Framework/Threading/GameThread.cs

- Closes https://github.com/ppy/osu/issues/18569
[As discussed in discord](https://discord.com/channels/188630481301012481/188630652340404224/982717832649375764), the scheduler shouldn't be disassociated when changing execution modes, since the `GameThread` instance is preserved on that case, only the underlying thread is reinstantiated.

Fix synchronisation context disassociating scheduler on execution mode changes

---

osu.Framework/Graphics/OpenGL/GLWrapper.cs

If a `DrawNode` causes an exception after a shader is bound, and the exception is "allowed" via overriding `GameHost.ExceptionThrown`, then the next draw iteration will throw an assert in `GLWrapper.Reset()`.
Can be tested via the following:
```diff
diff --git a/osu.Framework.Tests/Program.cs b/osu.Framework.Tests/Program.cs
index 8fb25e4db1..65257ea49c 100644
--- a/osu.Framework.Tests/Program.cs
+++ b/osu.Framework.Tests/Program.cs
@@ -17,6 +17,13 @@ public static void Main(string[] args)
using (GameHost host = Host.GetSuitableDesktopHost(@"visual-tests", new HostOptions { PortableInstallation = portable }))
{
+                bool allowException = true;
+                host.ExceptionThrown += _ =>
+                {
+                    allowException = !allowException;
+ …
```

Reset shader stack every frame to silence assertion

---

osu.Framework.Android/AndroidGameHost.cs
osu.Framework.Android/Input/AndroidTouchHandler.cs

- Closes https://github.com/ppy/osu/issues/9996
The problem described in https://github.com/ppy/osu/issues/9996#issuecomment-1116245041 occurs because framework treated `ACTION_CANCEL` as only cancelling the 0th pointer (`ActionIndex` would always return `0`). [`ACTION_CANCEL`](https://developer.android.com/reference/android/view/MotionEvent#ACTION_CANCEL) and [`ACTION_UP`](https://developer.android.com/reference/android/view/MotionEvent#ACTION_UP) now properly apply to every pointer.
Turns out `getActionIndex()`/`ActionIndex` is only valid for `ACTION_POINTER_DOWN` and `ACTION_POINTER_UP` events:
https://developer.android.com/reference/android/view/MotionEvent#ACTION_POINTER_DOWN
> Use [getActionIndex()](https://developer.android.com/reference/android/view/MotionEvent#getActionIndex()) …

Fix and cleanup android touch handling

---

osu.Framework/Audio/Sample/SampleStore.cs

Thread safety is already enforced via a `lock`, so this is unnecessary.

Switch `SampleStore` `ConcurrentDictionary` usage to be a normal `Dictionary`

---

osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
osu.Framework/Input/UserInputManager.cs

- Closes https://github.com/ppy/osu/issues/18159
Previously, moving the mouse outside the window in fullscreen would warp it and give back control to the OS. The OS would then warp the cursor back into the game window. In this short period, the cursor would jitter between being inside and outside the window.
The solution provided is not perfect, the cursor can still jitter if `Sensitivity < 1`:
Eg. on a 1920x1080 display, it can go down to 1079.9999999999, but will warp to 1079 flat. Importantly, it'll never leave the window.
This can probably be fixed by checking if there are adjacent displays, and then warping if `> 1079` instead of `>= 1080`, but it's not really that important. (Always checking for `> 1079` would leave the cursor in an invalid position when it's in-between two …

Implicitly confine the cursor when it can't leave to another display

---

osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs

This was already added in the test method above the one I've fixed.  Basically during decode the decoder is constantly switching between `Running` and `Ready`, so checking for `Ready` just once doesn't guarantee the full decode process has stopped.
https://user-images.githubusercontent.com/191335/172117884-89ee17a1-293d-4e4f-81d0-1d1451ea30c4.mp4
https://github.com/ppy/osu-framework/runs/6750920076?check_suite_focus=true

Attempt to fix `TestSceneVideo` incorrectly failing due to intermittent state changes

---

osu.Framework/Configuration/FrameSync.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Threading/GameThread.cs

This was already discussed internally and agreed on.
I'd also like to change the remaining options to be more in line with stable (ie. have an "optimised" setting that keeps update fps around 500 regardless of refresh rate), but that's for another day.
---
Games using osu!framework can generally run at *very* high frame rates when not much is going on.
This can be counter-productive due to the induced allocation and GPU overhead.
- Allocation overhead can lead to excess garbage collection
- GPU overhead can lead to unexpected pipeline blocking (and stutters as a result).
Also, in general graphics card manufacturers do not test their hardware at insane frame rates and therefore drivers are not optimised to handle this kind of throughput.
- We only harvest input at 1000hz, so running any …

Rename "unlimited" to "basically unlimited" and add sane frame limiter

---

osu.Framework/Platform/SDL2DesktopWindow.cs

Continuation of https://github.com/ppy/osu-framework/pull/5186#issuecomment-1132064369.
Tested on a windows precision touchpad, and with a regular mouse.

Properly set `IsPrecise` for SDL scroll events

---

osu.Framework/Audio/Sample/SampleChannelBass.cs
osu.Framework/Audio/Track/TrackBass.cs

- Closes #5237 
After deep investigation, enabling mixer buffering avoids some of the stuttering at the cost of playback latency (see [explanation](https://discord.com/channels/188630481301012481/589331078574112768/984492141919240192)), therefore it is not desired to enable it for o!f and we can still continue without it.
The stuttering occurs when opening song select or switching between beatmaps in osu!, and looks to generally happen due to gen1/gen2 collections (meaning you can manually cause a stutter by pressing "Clear all caches" in game settings).
Instead, a flag is now used for streams (and samples with `SampleChannelStream`) for having data buffered internally ahead-of-time to read without getting stalled by CLR being stuck due to GC collection or otherwise.
It is also generally …

Let BASS read stream data ahead of time to reduce audio stuttering

---

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
osu.Framework/Statistics/FrameStatistics.cs

See https://sentry.ppy.sh/share/issue/8af58e085ca14af4a7bfd15beeef62b1/.
This is the only variable I can see which can cause a `NaN`. Throwing will mean the game still may crash (although potentially not, since it will only fire once rather than every frame), but also mean we can track down the faulty flow.
I've checked each call to `Add` and can't find anything immediately. Welcome others to double-check.

Clean up `FrameStatisticsDisplay` and add exception to track down `NaN`

---

osu.Framework.Android/AndroidGameView.cs
osu.Framework.Android/osu.Framework.Android.csproj
osu.Framework.iOS.props
osu.Framework.iOS/osu.Framework.iOS.csproj
osu.Framework/osu.Framework.csproj

Workaround for the other crash described in #4994.
For reasons that are currently unclear, sometimes `SwapBuffers()` calls on android fail with `BAD_SURFACE` just before the game activity is suspended, and just after the game activity is resumed - but if given ample time to recover from the initial failures after resume, the game will continue functioning as usual.
As a temporary solution, suppress `SwapBuffers()` failures. The ideal solution would be to hook onto one of the many callbacks of
`GLSurfaceView`, but in testing it does not appear that the obvious ones fit the bill.

Suppress `SwapBuffers()` failures on android

---

osu.Framework.Tests/IO/TestDesktopStorage.cs
osu.Framework/Platform/Storage.cs

`[Pure]` seems to be as useful as JetBrains' own `[MustUseReturnValue]` here, so I'm going with it.

Indicate some `Storage` methods as must-use

---

osu.Framework/Audio/Sample/SampleChannelBass.cs
osu.Framework/Audio/Track/TrackBass.cs

Closes #18652.
Doing this to get a hotfix release out. Will report the issue to BassIan to get more information surrounding how it is implemented and how this could happen.
Reasoning for still having this enabled on other platforms: We haven't had anyone report an issue yet, but I'd like to continue testing to get more insight into where the issue is occurring. If it's only happening on windows I think we should keep using the flag elsewhere until it's reported as being an issue. For one, it fixes very rare stutters on macOS for me.

Only apply `AsyncFile` flag to non-windows platforms for now

---

.github/workflows/ci.yml

Recently, the macOS agents have bumped NuGet, and in return broke both Android and iOS CI from passing beyond the restore step. Android was fixed by reverting back to Windows agent, but iOS was left broken.
However, [the issue has since been reported to `virtual-environments`](https://github.com/actions/virtual-environments/issues/5768), and [a workaround was brought up in there as well](https://github.com/actions/virtual-environments/issues/5768#issuecomment-1159364290). The workaround looks to work for us therefore I'm PR'ing it to bring iOS CI back.
An alternative would be providing project-level `nuget.config` files, but we don't really use any other package sources so I refrained from doing that.

Work around macOS agent regression affecting iOS CI builds

---

osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
osu.Framework/Extensions/ExtensionMethods.cs

Use the new static one-shot APIs introduced in .NET 5 to improve performance and allocations.
Benchmark numbers on my Windows machine:
Before:
|    Method |       Mean |    Error |   StdDev |  Gen 0 | Allocated |
|---------- |-----------:|---------:|---------:|-------:|----------:|
| StringMD5 |   905.6 ns | 13.56 ns | 12.68 ns | 0.0839 |     352 B |
| StringSHA | 1,060.0 ns |  2.35 ns |  2.19 ns | 0.1068 |     448 B |
After:
|    Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|---------- |---------:|--------:|--------:|-------:|----------:|
| StringMD5 | 648.2 ns | 9.07 ns | 8.04 ns | 0.0439 |     184 B |
| StringSHA | 820.9 ns | 4.85 ns | 4.30 ns | 0.0629 |     264 B |

Use new static HashData methods for .NET 6+ targets

---

osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs

Probably should be applied to all interfaces asap as it leads to weirdness in usages otherwise.

Enable NRT on `IHasCustomTooltip` interface

---

CodeAnalysis/BannedSymbols.txt
osu.Framework.Benchmarks/GameBenchmark.cs
osu.Framework.Tests/Containers/TestSceneCompositeMutability.cs
osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithLoading.cs
osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
osu.Framework/Platform/GameHost.cs

Adds timeouts and exceptions when timeouts are exceeded.

Ban usage of `ManualResetEventSlim.Wait()` without a timeout value

---

osu.Framework/Graphics/Containers/CompositeDrawable.cs
osu.Framework/Graphics/Transforms/Transformable.cs

As seen at https://sentry.ppy.sh/share/issue/8d469f0003bd446eb4bda7865b2e9bc9/.
Can probably figure out a repro case if test coverage is seen as beneficial, but it's obvious how this could happen (and the inline comment should guard against regression).

Fix potential exception when calling `FinishTransforms` results in child changes

---

osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs

Setting `OSU_TESTS_NO_TIMEOUT` to `1` will call any `UntilStep`s to run forever. This can allow attaching a debugger or performing a memory dump to investigate edge case scenarios.
Tested manually to work as expected.

Add environment variable flag to cause until steps to never timeout

---

CodeAnalysis/BannedSymbols.txt
osu.Framework.iOS/Input/IOSTextFieldKeyboardHandler.cs
osu.Framework/Logging/Logger.cs
osu.Framework/Platform/SDL2/SDL2ReadableKeyCombinationProvider.cs
osu.Framework/Statistics/BackgroundStackTraceCollector.cs

Due to it relying on ambient current culture. Vaguely related to https://github.com/ppy/osu/issues/18729. I intend to apply this over there too later.
No major breakage here (though I did see a `performance-ınput.log`, that's dotless i, in my testing).

Disallow usage of `string.To{Upper,Lower}()` without explicit culture

---

osu.Framework.Tests/Localisation/LocalisableDescriptionAttributeTest.cs
osu.Framework/Extensions/ExtensionMethods.cs

This is implicitly what `GetDescription` does, but `GetLocalisableDescription` fails with returning a `string`-backed `LocalisableString` instead of the actual localised string data (since it's falling back to the `GetDescription` branch).
Instead, now `GetDescription` and `GetLocalisableDescription` explicitly check if the type is already string and return the value instead of going through reflection.
This came up in https://github.com/ppy/osu/pull/18803#discussion_r903224609 where the method is trying to do too much just to display a localisable string with upper case. We might end up not relying on `LocalisableString`-typed tab items, but leaving this PR out just to match behaviour with `GetDescription` at least.

Early-return on `GetDescription`/`GetLocalisableDescription` if already string type

---

osu.Framework.Tests/Visual/Drawables/TestSceneTransformSequence.cs
osu.Framework/Graphics/Containers/CompositeDrawable.cs
osu.Framework/Graphics/TransformableExtensions.cs

- Closes #5258 
On master, queuing transforms with invalid/infinite value only throws during the next update pass, rather than immediately on queue. This makes it impossible to figure out the root cause of the issue behind providing NaN transforms.
This should cover most, if not all, cases of invalid new values, with https://github.com/ppy/osu-framework/commit/f84c08ae5787948c41fd95ee49ed327e533fdbab pushed to handle `RelativeChildSize`'s special case of not allowing zero values.
Haven't overthought the logic too much, was initially going to consider throwing on every `TransformTo` usage (i.e. `ResizeTo`/`ScaleTo`/`MoveTo`/etc.), but realized I'm essentially checking the same thing over and over again everywhere, and NaN values cannot be interpolated, so I went with throwing on …

Validate transform values before queuing to drawable

---

osu.Framework.Tests/Graphics/TripleBufferTest.cs
osu.Framework/Allocation/ObjectUsage.cs
osu.Framework/Allocation/TripleBuffer.cs
osu.Framework/Platform/GameHost.cs

Previous version was using `Thread.Sleep(1)` when waiting on data, but with two threads running at roughly the same frame rate this would result in highly inefficient synchronisation. Using `ManualResetEventSlim` allows spinning for quick resolution cases.
Hopefully the changes should be self-explanatory and the code should be pretty straightforwards. Went through a few iterations to get to this point, have left some commits along the way to show different approaches leading up to the final one.
I've only tested this on macOS so far, which shows an increase of draw FPS from 500 to 900 with "Basically Unlimited" setting.
Addresses concerns raised at https://github.com/ppy/osu/discussions/18814.

Fix `TripleBuffer` sleeping too long at high frame rates

---

osu.Framework/Platform/GameHost.cs

`GetCultureInfo` is both case insensitive and caches lookups. Meanwhile, whatever we were calling...

Avoid retriving every `CultureInfo` on startup

---

osu.Framework/Audio/Track/Waveform.cs

```csharp
2022-06-26 06:20:32 [error]: An unobserved error has occurred.
2022-06-26 06:20:32 [error]: System.DivideByZeroException: Attempted to divide by zero.
2022-06-26 06:20:32 [error]: at osu.Framework.Audio.Track.Waveform.<>c__DisplayClass13_0.<.ctor>b__0()
2022-06-26 06:20:32 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2022-06-26 06:20:32 [error]: --- End of stack trace from previous location ---
2022-06-26 06:20:32 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-06-26 06:20:32 [error]: --- End of stack trace from previous location ---
2022-06-26 06:20:32 [error]: at …
```

Avoid div-by-zero in waveform resampling code

---

osu.Framework.Android/AndroidGameView.cs

https://developer.android.com/reference/android/view/View#getDefaultFocusHighlightEnabled()
The green border in question, shown when pressing keys on a hardware keyboard when a textbox is focused:
(Can also be seen in https://github.com/ppy/osu-framework/issues/4373)
<details>
<summary>Tall image</summary>
</details>

Disable ugly green border when using hardware keyboard on Android

---

osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
osu.Framework/Graphics/Containers/OverlayContainer.cs

All mouse events are limited to the `ButtonDownInputQueue`, which is determined by which drawable handles `MouseDownEvent`. Therefore `OverlayContainer`s don't need to handle all mouse events, but only `MouseDownEvent` to block positional input from propagating outside its hierarchy.
The previous logic was causing clicks and double-clicks to be handled as well, which in turn result in next clicks targeted at UI controls being blocked by the handled double click.
It was also handling drag start events, which marks this as a breaking change for any `OverlayContainer` implementation which was handling drag events without `OnDragStart` (there's none osu!-side).
- Closes https://github.com/ppy/osu/issues/18838

Fix overlay containers handling click and double-click events

---

osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework/Localisation/LocaleMapping.cs
osu.Framework/Localisation/LocalisationManager.cs

Noticed that each language added would trigger a bindable change, causing a re-fetch of the current language. Can get kind of expensive, especially as more languages are added.

Allow initial locale mappings to be added in a single call

---

osu.Framework.Android/AndroidGameView.cs
osu.Framework.Android/Input/AndroidTextInput.cs

- Closes https://github.com/ppy/osu/issues/17561
- Closes https://github.com/ppy/osu/issues/6282 
- can't repro, but not returning `null` and forcing `OnCheckIsTextEditor() => true` is the probable cause
[By default](https://user-images.githubusercontent.com/16479013/176005749-ecb6a979-1772-4d1a-99ef-d5808fcfe2d8.png), Android will show the software keyboard while text input is active even if a hardware keyboard is connected. And since we were always returning a valid `IInputConnection`, Android would "conveniently" show the software keyboard when any hardware keys are pressed.
Pressing keys will (re)focus the current view and probe `OnCreateInputConnection()` to see if the input method is to be activated.
The [docs](https://developer.android.com/reference/android/view/View#onCreateInputCo …

Fix pressing keys on a hardware keyboard showing the software keyboard

---

osu.Framework.Android/AndroidGameView.cs

- Closes https://github.com/ppy/osu/issues/17803
Depends on:
Android basically doesn't send the key up event for backspace. Really strange behaviour, I guess they expect text boxes not to care about key up events and instead rely on native key repeat.
Key up events works just find when text input is disabled (a.k.a. when `OnCreateInputConnection()` returns `null`).

Fix backspace not working properly with hardware keyboards

---

osu.Framework/Input/Handlers/Joystick/JoystickHandler.cs
osu.Framework/Input/StateChanges/JoystickAxisInput.cs
osu.Framework/Input/States/JoystickState.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

This will allow `AndroidJoystickHandler` (coming soon) to reuse this logic without code duplication.
Inheritance is not an option as `AndroidInputHandler` is used on Android.
This code does look a bit dubious as `JoystickButtonInput.Apply` is called within `JoystickAxisInput.Apply`, but the current order of events is preserved.
`KeyCombination` does have a similar [scroll delta to button](https://github.com/ppy/osu-framework/blob/ba1385330cc501f34937e08257e586c84e35d772/osu.Framework/Input/Bindings/KeyCombination.cs#L619-L632) conversion, but putting the logic there will break existing `JoystickButton.JoystickAxisN` usages.

Move joystick-axis-to-button simulation out of `JoystickHandler`

---

osu.Framework.Benchmarks/BenchmarkTransformUpdate.cs
osu.Framework/Graphics/Transforms/Transformable.cs

As noticed by @smoogipoo during multiplayer spectator profiling, `updateTransforms` can become quite expensive as it is called millions of times. Even in cases where there are actually not transforms on drawables.
Before:
|                          Method |     Mean |   Error |  StdDev | Allocated |
|-------------------------------- |---------:|--------:|--------:|----------:|
| UpdateTransformsWithNonePresent | 101.2 us | 0.31 us | 0.25 us |         - |
| UpdateTransformsWithManyPresent | 383.3 us | 2.21 us | 2.07 us |       1 B |
After:
|                          Method |       Mean |     Error |    StdDev | Allocated |
|-------------------------------- |-----------:|----------:|----------:|----------:|
| UpdateTransformsWithNonePresent |   5.091 us | 0.0303 us | 0.0269 us |         - | …

Reduce overhead of transform processing when no transforms are present in a drawable

---

osu.Framework/Utils/Blur.cs
osu.Framework/Utils/ConvexPolygonClipper.cs
osu.Framework/Utils/HasOrderedElementsAttribute.cs
osu.Framework/Utils/IInterpolable.cs
osu.Framework/Utils/Interpolation.cs
osu.Framework/Utils/MathUtils.cs
osu.Framework/Utils/NumberFormatter.cs
osu.Framework/Utils/OrderAttribute.cs
osu.Framework/Utils/PathApproximator.cs
osu.Framework/Utils/Precision.cs
osu.Framework/Utils/RNG.cs

Remove nullable disable annotate in the utils namespace.
Seems there's no test case for the utils.

Remove nullable disable annotation in the utils namespace

---

osu.Framework/Testing/TestScene.cs

I'm not saying we should do this, but I want the flexibility to experiment with it. Once we have things in a stable state, it may make sense to disable for Github Actions to improve performance of test runs (from recollection, about 40% faster) and enable only when an issue comes up, or as a background runner on teamcity or otherwise.

Allow disabling forced GC during test runs

---

osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs

~~Turns out `AsNonNull` never works osu!-side, due to the asserts being made for debug configuration only. Haven't checked if this works as expected when packaging framework yet (blocking until I confirm).~~
~~Alternative would be to explicitly throw exception, but not sure what's best fit for this.~~
I've been confused into thinking that `AsNonNull` should throw when the instance is null, but the intention behind it is to silently return the instance as non-nullable regardless of whether it's null (i.e. act exactly like a null-forgiving operator).
PR'ing this just to clear that confusion up.

Use null-forgiving operator for `AsNonNull` rather than assertion

---

osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
osu.Framework/Graphics/Textures/TextureLoaderStore.cs

- Closes https://github.com/ppy/osu/issues/18989
Tournament texture storage [uses a `StorageBackedResourceStore`](https://github.com/ppy/osu/blob/1ccfd69690c45aaad0057877aa5642896646d3d7/osu.Game.Tournament/TournamentGameBase.cs#L65), which is not of type `ResourceStore`, therefore `TextureLoaderStore` can't append the image extensions and fail lookups:
https://github.com/ppy/osu-framework/blob/e918d33889a39c4895c01bcca384e88c89b52a57/osu.Framework/Graphics/Textures/TextureLoaderStore.cs#L24-L29
This is a regression from https://github.com/ppy/osu-framework/pull/5240, since prior to that PR, [`TextureStore` appends extensions as well](https://github.com/ppy/osu-framework/blob/84758b770872e8f332ae0e5503206c5a941c89bb/osu.Framework/Graphics/Textures/TextureStore.cs#L44-L45) (this is also …

Fix `TextureLoaderStore` not always appending extensions to lookups

---

osu.Framework/Input/Handlers/Midi/MidiHandler.cs

MIDI devices generally send traffic such as clock sync data, which we don't care about. For me, if I have my midi controller connected this creates a flow of 2-3 logger messages per second.
Uploading JetBrains Rider-EAP 2022-07-06 at 05.12.44.mp4…

Remove noisy MIDI handler log output

---

osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs

This change is the only exact combination of things I can find that replicates the inspections provided by `!`.
My tests are:
```
#nullable enable
object a = new object();
object a1 = a!;
object a2 = a.AsNonNull();
Debug.Assert(a1 == null);
Debug.Assert(a2 == null);
object? b = new object();
object b1 = b!;
object b2 = b.AsNonNull();
Debug.Assert(b1 == null);
Debug.Assert(b2 == null);
object? c = null;
object c1 = c!;
object c2 = c.AsNonNull();
Debug.Assert(c1 == null);
Debug.Assert(c2 == null);
int d = 5;
int d1 = d!;
int d2 = d.AsNonNull();
Debug.Assert(d1 == null);
Debug.Assert(d2 == null);
int? e = 5;
int? e1 = e!;
int? e2 = e.AsNonNull();
Debug.Assert(e1 == null);
Debug.Assert(e2 == null);
int? f = null;
int? f1 = f!;
int? f2 = f.AsNonNull();
Debug.Assert(f1 == null);
Debug.Assert(f2 …
```

Remove class constraint on AsNonNull()

---

osu.Framework/Graphics/Visualisation/DrawVisualiser.cs

Fixes draw visualiser taking hover away from components when open. Regressed in #5268 since the events changed to be handled per-method rather than at `Handle` (which `DrawVisualiser` has overriden).

Fix `DrawVisualiser` blocking positional input while not searching

---

osu.Framework.Benchmarks/BenchmarkScheduler.cs
osu.Framework/Threading/Scheduler.cs

A common scenario is that a drawable will use a `Schedule` call once then become mostly inactive. The `Scheduler` that was used for this call stays remnant, and has quite a large overhead due to the locking in `Scheduler.Update`. This aims to reduce that overhead considerably.
Before:
|                         Method |        Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------------- |------------:|----------:|----------:|-------:|----------:|
|           UpdateEmptyScheduler |    82.15 us |  0.662 us |  0.553 us |      - |         - |
| UpdateSchedulerWithManyDelayed | 1,389.42 us | 20.222 us | 17.926 us |      - |       3 B |
| UpdateSchedulerWithEveryUpdate |   147.62 us |  2.294 us |  2.034 us |      - |         - |
|   UpdateSchedulerWithManyAdded |   144.63 …

Reduce `Scheduler` overhead when no tasks are pending

---

osu.Framework/Graphics/UserInterface/BasicDirectorySelector.cs
osu.Framework/Graphics/UserInterface/BasicDirectorySelectorBreadcrumbDisplay.cs
osu.Framework/Graphics/UserInterface/BasicDirectorySelectorDirectory.cs
osu.Framework/Graphics/UserInterface/BasicDirectorySelectorParentDirectory.cs
osu.Framework/Graphics/UserInterface/BasicFileSelector.cs
osu.Framework/Graphics/UserInterface/DirectorySelector.cs
osu.Framework/Graphics/UserInterface/DirectorySelectorDirectory.cs
osu.Framework/Graphics/UserInterface/DirectorySelectorItem.cs
osu.Framework/Graphics/UserInterface/FileSelector.cs

Discussed in ppy/osu#15759, resolves ppy/osu#18573.
This change includes hidden items in `DirectorySelector` dialogues and provides a way to reduce their opacity to distinguish them from non-hidden items.
I elected to make opacity reduction a defaulted constructor argument for `DirectorySelectorDirectory` to avoid making any breaking changes, but this could be changed to a property to force implementations to state their opacity preference explicitly.
I've only tested this on Linux with dotfiles, would appreciate someone checking it on macOS and Windows (though I can't immediately think of anything that would be different).

Show hidden items in DirectorySelectors

---

osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs

It seems this is better fit for this method for non-NRT contexts. Will resolve inspections such as https://github.com/ppy/osu/runs/7229529245?check_suite_focus=true. Also still seems to work with the new bindable NRT work in https://github.com/ppy/osu-framework/pull/5099.

Change AsNonNull to NotNull return

---

osu.Framework/Input/Handlers/Touch/TouchHandler.cs
osu.Framework/Platform/DesktopGameHost.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/Windows/Native/Input.cs
osu.Framework/Platform/Windows/WindowsMouseHandler.cs
osu.Framework/Statistics/FrameStatistics.cs
osu.Framework/Threading/InputThread.cs

- Closes https://github.com/ppy/osu-framework/issues/1514
- Closes https://github.com/ppy/osu-framework/issues/5033
- Closes https://github.com/ppy/osu/issues/18889
Touch currently uses [mouse emulation](https://github.com/libsdl-org/SDL/blob/6a2e6c82a0764a00123447d93999ebe14d509aa8/include/SDL_hints.h#L1367-L1376) on desktop platforms. This PR sets the correct flag and implements [`SDL_TouchFingerEvent`](https://wiki.libsdl.org/SDL_TouchFingerEvent) handling. Windows also emulates mouse events for touch, and those events have also been properly ignored in `WindowsMouseHandler`.
Initial testing [by peppy on discord](https://discord.com/channels/188630481301012481/589331078574112768/993813779160760340).
Raw input touch event detection …

Touch support for desktop platforms

---

osu.Framework.Android/AndroidGameHost.cs
osu.Framework.Android/AndroidGameView.cs
osu.Framework.Android/Input/AndroidInputExtensions.cs
osu.Framework.Android/Input/AndroidInputHandler.cs
osu.Framework.Android/Input/AndroidJoystickHandler.cs
osu.Framework.Android/Input/AndroidKeyboardHandler.cs
osu.Framework/Input/Handlers/Joystick/JoystickHandler.cs

- Closes https://github.com/ppy/osu/discussions/18856
- Closes https://github.com/ppy/osu-framework/issues/2863
- tablet support still missing https://github.com/ppy/osu/issues/17382
Initial implementation based on https://developer.android.com/training/game-controllers/controller-input.
Axis and button values taken from there and by manually inspecting the android Keycode enum and docs.
During initial osu!-side testing I noticed that D-pad events were being dropped (on song select, where the game lags the most). The cause was not properly handling `MotionEvent` [batching](https://developer.android.com/reference/android/view/MotionEvent#batching), something that has already come up in [`AndroidMouseHandler`](https://github.com/ppy/osu-framework/blob/193238a90215b0e97ac2aa244ed7d30edc0a9880 …

Add support for joysticks/gamepads on Android

---

osu.Framework/Audio/Track/Waveform.cs
osu.Framework/Graphics/Audio/WaveformGraph.cs

Also fixes a few other things I noticed along the way.
See breadcrumbs in https://sentry.ppy.sh/organizations/ppy/issues/92/events/ae89bc05396e436d9d91ca3e55123fb1/?project=2&query=is%3Aunresolved&sort=user&statsPeriod=14d for reference. Not sure this will fix the issue but I really want better diagnostic output regardless.

Fix waveform generation function not freeing bass stream after usage

---

osu.Framework.Tests/Audio/BassTestComponents.cs
osu.Framework/Audio/Track/TrackBass.cs

I'm still in talks with Ian since this shouldn't be happening anyway, but what's happening is that Bass will call `Bass_Free()` on application exit (i.e. after all user code has exited) and deadlock because we haven't removed the track syncs.
I don't think there's any reason for us to not remove the syncs on disposal. But not only were we not removing the track syncs - the tests weren't disposing the components at all.
The deadlocks can be reproed on Linux by starting `TrackBassTest.TestBitrate` with debugger attached.

Fix running Bass tests causing deadlocks on Linux

---

osu.Framework.Tests/Audio/BassTestComponents.cs
osu.Framework/Threading/AudioThread.cs

This was added in https://github.com/ppy/osu-framework/commit/ddf3fc212414bc5f741ef00da521a77c917f680e, but I'm not sure it's necessary since the switch to BassMix. If platform-specific deadlocks return a result of this revert, then I hope we can report and get them fixed. Test that both o!f and osu! tests pass with this change.

Free Bass device 0 on Linux

---

osu.Framework/Platform/MacOS/MacOSGameHost.cs

- Addresses https://github.com/ppy/osu/discussions/19093
Wasn't aware there is fallback support for user storage paths, that makes switching to the new path much easier. Looks to work as intended on testing.

Prefer `~/Library/Application Support` as user storage path on macOS

---

osu.Framework/Platform/NativeStorage.cs
osu.Framework/Platform/Storage.cs

- Closes https://github.com/ppy/osu/issues/19116
- See discussion on [Discord](https://discord.com/channels/188630481301012481/188630652340404224/997304567526080583)
The operation was initially added to fix a Windows-specific issue regarding zeros being written to the file, and after switching to .NET 6, the behaviour of the operation changed on macOS to become much stronger / more expensive (see https://github.com/dotnet/runtime/pull/44443).
We do not want this overhead on non-Windows platforms as there has been no signs of such issues occurring there, therefore the flush-to-disk operation is now limited to Windows platforms (we may eventually not need flushing at all on `SafeWriteStream`, see https://github.com/ppy/osu-framework/issues/5231).

Remove flush-to-disk operation on non-Windows platforms for lower overhead

---

osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
osu.Framework/Audio/Track/Waveform.cs

Closes https://github.com/ppy/osu/issues/18479 (probably... unless there are other cases. fine to close until it comes up again).

Fix `Waveform` generation failing when using "no sound" device

---

osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
osu.Framework/Graphics/Containers/OverlayContainer.cs

- Addresses https://github.com/ppy/osu/discussions/19213
- Alternative to https://github.com/ppy/osu/pull/19217
Another regression by https://github.com/ppy/osu-framework/pull/5268, `OnMouseMove` should not propagate to parent if the overlay blocks positional input.

Fix `OverlayContainer` no longer blocking mouse move events

---

osu.Framework/Audio/Track/Waveform.cs
osu.Framework/Graphics/Audio/WaveformGraph.cs

Was so focused on the `task.GetResultSafely()` line that I missed the issue being in the `Logger` call itself. The outer waveform could change during the async `ContinueWith` operation, which would cause undefined behaviour. Note that this was an issue before the logger call was added – it was only brought to light by the recent failures. Probably leading to weirdness in other ways.
Closes https://github.com/ppy/osu-framework/issues/5314

Fix bad access to `Waveform.GetPoints()` if waveform changes during regeneration

---

osu.Framework/Graphics/Audio/WaveformGraph.cs

As seen in game-side [test failures](https://github.com/ppy/osu/runs/7413532468?check_suite_focus=true).
Prior to #5316, accessing `resampledPointCount.Value` is safe since it's within the same thread it's updated in, but after moving it to `Task.Run`, the field can be changed in the update thread while the async task hasn't ran yet, resulting in a null value access during task execution.
Adding a test case for this doesn't seem that easy since it involves manipulating time spent inside internal executions, so I bailed off for now.

Fix unsafe value access in `WaveformGraph` async resampling logic

---

osu.Framework/Threading/ScheduledDelegate.cs
osu.Framework/Threading/ScheduledDelegateWithData.cs
osu.Framework/Threading/Scheduler.cs

```csharp
[performance] 2022-07-25 07:43:12 [verbose]: osu.Framework.Threading.Scheduler has 2000 timed tasks pending
[performance] 2022-07-25 07:43:12 [verbose]: - First task: method "Void <displayTemporarily>b__30_0()" targeting "FPSCounter" executing at 29,283 with repeat -1
[performance] 2022-07-25 07:43:12 [verbose]: - Last task: method "Void <displayTemporarily>b__30_0()" targeting "FPSCounter" executing at 31,283 with repeat -1
```

Improve log output for too-many-scheduled-tasks

---

osu.Framework/Testing/Drawables/Steps/AssertButton.cs
osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
osu.Framework/Testing/TestScene.cs

I want to start figuring out why failures such as https://github.com/ppy/osu/runs/7573977900?check_suite_focus=true occur.
This PR adds constrained assertions, which allows for more details to be output when assertions fail.
Testing:
```csharp
public class TestSceneOutput : TestScene
{
private const int value_1 = 1000;
private const int value_2 = 2000;
[Test]
public void TestAssert()
{
AddAssert($"{nameof(value_1)} almost equals {nameof(value_2)}", () => value_1, () => Is.EqualTo(value_2).Within(100));
}
[Test]
public void TestUntilStep()
{
AddUntilStep($"{nameof(value_1)} almost equals {nameof(value_2)}", () => value_1, () => Is.EqualTo(value_2).Within(100));
}
}
```
```
$ dotnet test --filter "TestSceneOutput"
Determining projects to restore...
All projects are up-to-date for restore. …
```

Add constrained assertions

---

osu.Framework/Graphics/Containers/ModelBackedDrawable.cs

This is mostly guarding against misuse of the component, but seems good
to have at a framework level to avoid crashes.
Guards against a potential update of the model property post-disposal
causing an actual crash.
https://sentry.ppy.sh/share/issue/ceaf54b7da61445faac5675cc0a4fa44/

Fix `ModelBackedDrawable` attempting to mutate children after disposal

---

osu.Framework/Graphics/Audio/WaveformGraph.cs
osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
osu.Framework/Graphics/DrawNode.cs
osu.Framework/Graphics/Lines/Path_DrawNode.cs
osu.Framework/Graphics/OpenGL/Batches/LinearBatch.cs
osu.Framework/Graphics/OpenGL/Batches/QuadBatch.cs
osu.Framework/Graphics/OpenGL/Batches/VertexBatch.cs
osu.Framework/Graphics/OpenGL/Buffers/LinearVertexBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
osu.Framework/Graphics/OpenGL/GLWrapper.cs
osu.Framework/Graphics/OpenGL/OpenGLRenderer.cs
osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/PrimitiveTopology.cs
osu.Framework/Graphics/Textures/Texture.cs
osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs

Prereqs:
- Makes `VertexBatch`,`VertexBuffer`, et-al `internal` and moves them to the OpenGL namespace.
- Exposes methods to create `IVertexBatch<T>` via `IRenderer`.
- Adds `PrimitiveTopology`, replacing the OpenGL-specific `PrimitiveType`.
They should instead be created via the `IRenderer` and stored as an `IVertexBatch<T>` :
```diff
class MyDrawNode : DrawNode
{
-   private readonly QuadBatch<TexturedVertex2D> myBatch = new QuadBatch<TexturedVertex2D>(1, 1);
+   private IVertexBatch<TexturedVertex2D> myBatch;
public override void Draw(IRenderer renderer)
{
base.Draw(renderer);
+       myBatch ??= renderer.CreateQuadBatch<TexturedVertex2D>(1, 1);
}
protected override void Dispose(bool disposing)
{
base.Dispose(disposing);
batch?.Dispose();
}
}
```
The new `PrimitiveTopology` enumeration …

Internalise vertex batches and expose via `IVertexBatch`

---

osu.Framework.Benchmarks/BenchmarkLocalisedBindableString.cs
osu.Framework.Tests/Localisation/CultureInfoHelperTest.cs
osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework.Tests/Localisation/ThreadCultureTest.cs
osu.Framework.Tests/Visual/Localisation/TestSceneTextFlowContainerLocalisation.cs
osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs
osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs
osu.Framework/Game.cs
osu.Framework/Localisation/CultureInfoHelper.cs
osu.Framework/Localisation/LocalisationManager.cs
osu.Framework/Platform/GameHost.cs

- Closes #5328 
`CultureInfoHelper.TryGetCultureInfo` unifies the two usages of `GetCultureInfo`/`new CultureInfo`, fixing `LocalisationManager` crashing on startup when an invalid culture is set.
`CultureInfo.GetCultureInfo` still sometimes fabricates cultures when using `predefinedOnly: true` so the `ZZZ` check will have to remain.

Unify usages of `GetCultureInfo` and fix `LocalisationManager` throwing on invalid culture

---

osu.Framework/Platform/SDL2DesktopWindow.cs

SDL behaviour looks to have changed when calling `SDL_GetWindowSize` while minimised from a fullscreen state. This fixes crashes due to div-by-zero propagating into the draw hierarchy.
Haven't investigated in detail why this happened, but the fix seems solid enough to get out as a hotfix.

Fix crash when minimising while fullscreen on windows

---

build/build.cake

Theoretically, this should just work™
Following the guide on https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
I've tested that the build script generates a `snupkg` artifact.

Generate and upload symbol packages to nuget

---

osu.Framework/Graphics/Rendering/RendererExtensions.cs

Just to fix a potential crash for now. The failure is occurring somewhere in the `Area` calculation, which I don't really want to dive into.

Guard against pixel count attempting to be decremented

---

osu.Framework/Graphics/OpenGL/Batches/LinearBatch.cs
osu.Framework/Graphics/OpenGL/Batches/QuadBatch.cs
osu.Framework/Graphics/OpenGL/Batches/VertexBatch.cs
osu.Framework/Graphics/OpenGL/Buffers/LinearVertexBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
osu.Framework/Graphics/OpenGL/OpenGLRenderer.cs
osu.Framework/Graphics/OpenGL/OpenGLUtils.cs

While investigating https://sentry.ppy.sh/organizations/ppy/issues/5729/events/906dabeba7884d34a0ef448030f72ce8/?end=2022-08-11T03%3A10%3A59&project=2&query=firstRelease%3Aosu%402022.810.2&sort=freq&start=2022-08-10T08%3A52%3A00#exception, I found that exceptions are thrown kinda weirdly. They're sometimes completely missing (`LinearVertexBuffer`, `size <= 0` check), or trace assertions (`VertexBatch`), or even the incorrect type (`QuadBatch`).
This is just cleaning this up. At this point I can only imagine the error above happen via the ctor exiting early, so the `VertexBuffer` assertion is suspect. Possibly in combination with https://github.com/ppy/osu-framework/pull/5349 causing the `CircularProgressDrawNode` to pass in <=0 values triggering the `VertexBatch` assertion.

Refactor exceptions thrown from vertex buffer construction

---

osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
osu.Framework/Graphics/OpenGL/OpenGLRenderer.cs
osu.Framework/Graphics/OpenGL/OpenGLUtils.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/StencilInfo.cs
osu.Framework/Graphics/Rendering/StencilOperation.cs
osu.Framework/Platform/IGraphicsBackend.cs
osu.Framework/Platform/PassthroughGraphicsBackend.cs
osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

This adds `StencilInfo` and appropriate methods to renderers. It also adds an 8-bit stencil buffer to the screen buffers (please doublecheck if all window types have it, I only added it to the SDL window as I have no way to check if the mobile ones or OsuTkWindow work).
This is a part of my work towards #3510 - the even-odd fill algorithm is very easy to implement with a stencil buffer.

Add stencil support for renderers

---

osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs

Noticed while using this clock to implement a higher-level beatmap clock osu! side.

Fix performing a `Seek` on decouplable clock while coupled and stopped not updating the `CurrentTime`

---

osu.Framework/Graphics/OpenGL/OpenGLUtils.cs
osu.Framework/Graphics/Rendering/DepthStencilFunction.cs

Matches `LessThan`, `LessThanOrEqual`, and `GreaterThanOrEqual`.

Fix naming of depth stencil function function type

---

osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs

This came up when attempting to use coupled mode in the editor (it was using decoupled until now).
When the track finished, the decoupled clock would be at a different `CurrentTime` to the source track (sometimes ahead, sometimes behind it) due to a final value transfer not occurring.
This would in turn cause the track to not loop correctly, as the editor was relying on checking `Current` vs `Length` to check whether playback has finished.
I know this is adding even more complexity to the existing clocks, but right now I'm just trying to get everything working. I'm plannning to probably do a full rewrite of interpolating/decoupling in the future.

Make position transfer more reliable when track is stopped

---

osu.Framework.Tests/Localisation/LocalisableStringTest.cs
osu.Framework/Localisation/LocalisableString.cs

For use in https://github.com/ppy/osu/pull/19695
Matches the interface exposed by `string`: https://source.dot.net/#System.Private.CoreLib/String.cs,486

Add `LocalisableString.IsNullOrEmpty` and `LocalisableString.IsNullOrWhiteSpace`

---

Directory.Build.props
build/build.cake
osu.Framework/osu.Framework.csproj

While checking to see why Sourcelink isn't working osu!-side, I came up with a few things.
1. Update the package from `1.0.0` to `1.1.1`.
2. Remove embedded PDBs. Embedding PDBs [is not recommended](https://github.com/dotnet/sourcelink#alternative-pdb-distribution) by Microsoft. The downside to this is that we lose local symbolicated debugging support (which is why it was working for me), but we don't ever really debug with a local package anyway so I don't think this will affect us.
Compare:
- https://www.nuget.org/packages/ppy.osu.Framework/2022.818.0
- https://www.nuget.org/packages/smoogipoo.osu.Framework/0.0.0
Notice how my package has a "Download symbols" link. I believe this is the source of the issue - either by embedding the PDBs, or these extra options, nuget wasn't getting the …

Sourcelink improvements

---

osu.Framework/Configuration/ConfigManager.cs

Implementation borrowed from [OsuConfigManager](https://github.com/ppy/osu/blob/3fb3a18e68e58bb016d3340a84c44517b3b520f7/osu.Game/Configuration/OsuConfigManager.cs#L175-L187).
Allows logging framework configuration to sentry, which can be quite useful in tracking down certain issues. The case I'm interested in which made me want to add this was knowing whether the game is running in single or multithreaded mode.

Add method to get configuration from a `ConfigManager` for logging purposes

---

osu.Framework/Graphics/UserInterface/DirectorySelectorDirectory.cs

A small QoL commit to fix the DirectorySelectorDirectory applying hidden state to system drives, thus fixing a color discrepancy between local drives and network drives. Breadcrumbs are not affected by this issue.
**Seen on: osu-framework & osu-lazer**
**Tested on: Windows 10 21H2 (Build 19044.1826)**
Original behavior (master):
Additional Information (`directory` Attributes):
Local Drive:
Network Drive:
Fixed:
P.S This is my first time contributing to an open-source project, feel free to point out anything that needs to be improved. Thank you.

Do not apply hidden state to system drives in directory selector

---

osu.Framework/Graphics/Containers/RearrangeableListContainer.cs

Without this it's basically impossible to perform post-change filtering.
Will be used to fix remaining test failures noticed in `TestScenePlaylistOverlay`.

Expose method to allow implementations to perform operations when drawable items change in `RearrangeableListContainer`

---

osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs

With https://github.com/ppy/osu-framework/pull/5355, we are now always performing a source seek. On the surface this seemed like it would be fine, but it turns out there is a performance issue if `Seek` is called too often.
This reverts the non-`Coupled` case to not perform a source seek if not required.
~I'm still cross-testing this with my ongoing clock changes to make sure it works well.~ Seems fine.

Avoid performing `Seek` operations on a decoupled source when the source is not running

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

Will be used for adding audio feedback to text selection in lazer

Add callbacks to text selection events of TextBox

---

osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs
osu.Framework.Tests/Audio/TrackVirtualTest.cs
osu.Framework/Audio/Mixing/IAudioChannel.cs
osu.Framework/Audio/Sample/ISample.cs
osu.Framework/Audio/Sample/ISampleChannel.cs
osu.Framework/Audio/Sample/Sample.cs
osu.Framework/Audio/Sample/SampleBass.cs
osu.Framework/Audio/Sample/SampleBassFactory.cs
osu.Framework/Audio/Sample/SampleChannel.cs
osu.Framework/Audio/Sample/SampleChannelBass.cs
osu.Framework/Audio/Sample/SampleChannelVirtual.cs
osu.Framework/Audio/Sample/SampleStore.cs
osu.Framework/Audio/Sample/SampleVirtual.cs
osu.Framework/Audio/Track/ITrackStore.cs
osu.Framework/Audio/Track/Track.cs
osu.Framework/Audio/Track/TrackBass.cs
osu.Framework/Audio/Track/TrackStore.cs
osu.Framework/Audio/Track/TrackVirtual.cs
osu.Framework/Graphics/Audio/DrawableSample.cs

Not displayed anywhere yet. I was hoping to display this in the audio mixer overlay (`Ctrl+F9`) but it turns out to be a bit harder than expected - that overlay is retrieving raw handle IDs from bass.
This is still useful in debug scenarios, where you want to know which samples are playing. ie.
```csharp
Logger.Log($"Playing sample {Name} with volume {AggregateVolume.Value}");
```
can now be done in a `Play()` call, whereas previously it was nigh impossible to know the name of the sample that was firing the call.

Add `Name` to samples and channels

---

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Statistics/FrameStatistics.cs

Still kept the name `Reset` as it makes sense for what the underlying operation is doing, despite the fact that it's called `BeginFrame` now.

Remove "GL" prefix from performance collection type enum

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs

Was working on unrelated things regarding `KeyDownEvent` and `KeyUpEvent` and the `performKeypress()` did not work with those changes.
So I fixed the test to use proper simulation of keyboard keys and mouse clicks (bonus!).
This tests still fail due to not being properly isolated when running interactive, but I couldn't find a quick fix for it (other than pressing Ctrl+R).

Don't fabricate `UIEvent`s in `TestSceneDropdown`

---

osu.Framework/Graphics/OpenGL/Batches/GLLinearBatch.cs
osu.Framework/Graphics/OpenGL/Batches/GLQuadBatch.cs
osu.Framework/Graphics/OpenGL/Batches/GLVertexBatch.cs
osu.Framework/Graphics/OpenGL/Buffers/GLLinearBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/GLQuadBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/GLVertexUtils.cs
osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
osu.Framework/Graphics/Rendering/Dummy/DummyShader.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/IVertexBatch.cs
osu.Framework/Graphics/Rendering/Vertices/DepthWrappingVertex.cs
osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
osu.Framework/Graphics/Shaders/GlobalUniform.cs
osu.Framework/Graphics/Shaders/IShader.cs
osu.Framework/Graphics/Shaders/IUniformWithValue.cs
osu.Framework/Graphics/Shaders/Uniform.cs
osu.Framework/Graphics/Shaders/UniformMapping.cs

Required for Veldrid as it disallows updating vertex/uniform buffers with values that do not use the `unmanaged` constraint (see [`UpdateBuffer`](https://github.com/mellinoe/veldrid/blob/b881f7dcb444c4856e29464435b10d4be0ff38e0/src/Veldrid/CommandList.cs#L799-L803)). I've also updated non-required GL variants for consistency.

Add `unmanaged` constraint to vertex/uniform generic types

---

osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
osu.Framework/Graphics/Rendering/Dummy/DummyShader.cs
osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
osu.Framework/Graphics/Shaders/IShader.cs
osu.Framework/Graphics/Shaders/IUniform.cs

Was initially going to define a generic-less `GetUniform` method and move the generic variant to an extensions or seal it, but `GlobalPropertyManager` isn't aware whether the global uniform is defined by the shader or not, and `GetUniform` throws if the uniform could not be found.
Therefore I've went with an internal uniforms dictionary and called it a day.

Update `GlobalPropertyManager` to support registering `IShader`s

---

osu.Framework.Benchmarks/BenchmarkInvalidationList.cs
osu.Framework/Graphics/InvalidationList.cs

Initial:
|     Method |      Mean |     Error |    StdDev |
|----------- |----------:|----------:|----------:|
| Invalidate | 2.4286 ns | 0.0092 ns | 0.0072 ns |
|   Validate | 0.8363 ns | 0.0022 ns | 0.0020 ns |
Removing exception:
|     Method |      Mean |     Error |    StdDev |
|----------- |----------:|----------:|----------:|
| Invalidate | 0.5200 ns | 0.0233 ns | 0.0218 ns |
|   Validate | 0.8370 ns | 0.0063 ns | 0.0056 ns |
Removing branching:
|     Method |      Mean |     Error |    StdDev |
|----------- |----------:|----------:|----------:|
| Invalidate | 0.5070 ns | 0.0161 ns | 0.0143 ns |
|   Validate | 0.5107 ns | 0.0126 ns | 0.0098 ns |
I suspect the branching is different on different CPUs and different workloads, but will now be consistent across the board.
I expect this …

Improve invalidation/validation performance

---

osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
osu.Framework/Graphics/OpenGL/GLUtils.cs
osu.Framework/Graphics/Rendering/BufferTestFunction.cs
osu.Framework/Graphics/Rendering/DepthInfo.cs
osu.Framework/Graphics/Rendering/StencilInfo.cs

Around the time #5351 was merged, `DepthTestFunction` was renamed to `DepthStencilFunction` (#5352) to allow the enum to be reused.
At the time I didn't pay too much attention to it, but I believe the name `BufferTestFunction` works better as a generalisation of the `{Depth,Stencil}TestFunction` concept.

Rename `DepthStencilFunction` to `BufferTestFunction`

---

osu.Framework.Tests/Visual/Drawables/TestSceneDrawableScale.cs
osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
osu.Framework/Graphics/DrawInfo.cs
osu.Framework/Graphics/Drawable.cs

I don't know the original issue with storyboards so @peppy please test if this works for you.
`DrawInfo` still needs to handle zero scale. As it turns out, this value cannot be 0 for either the scale or the inverse scale, as input breaks either way. Tests have been added for this case.

Allow Drawable `Scale` to be exactly zero

---

build/build.cake

I'm seeing callbacks to this in various places like https://help.appveyor.com/discussions/questions/44202-how-to-publish-symbol-packages-snupkg-on-nuget and https://help.appveyor.com/discussions/questions/49442-snupkg-symbols-are-not-uploaded-to-nugetorg where they specifically mention adding `-Type NuGetPackage`. By default it seems that cake uses `-Type Auto`

Attempt to fix AppVeyor not publishing .snupkgs

---

osu.Framework/Graphics/Drawable.cs

This is stupid and I hope we will remove `DrawScale` at some point, but I'm not entirely sure how to handle storyboard just yet. It (storyboard) is the only consumer of `DrawScale`.
No consumer should be overriding `DrawScale` for the simple reason that it bypasses invalidation.

Make `IsPresent` consider `DrawScale` instead of `Scale`

---

osu.Framework.Tests/Containers/TestSceneEnumeratorVersion.cs
osu.Framework.Tests/Visual/Containers/TestSceneEnumerator.cs
osu.Framework/Graphics/Containers/Container.cs

Closes https://github.com/ppy/osu-framework/issues/5379
I believe I've covered all the methods that can mutate `Children`?
Also not sure if I should also check the version in `Reset()` of the enumerator. `List<T>` does it but I can't think of the case where that would throw

Throw exception when modifying contents of Container<T> while iterating through it

---

osu.Framework.Tests/Containers/TestSceneEnumeratorVersion.cs

Shouldn't display in visual test browser. Caused all tests to be prefixed with `Visuals.`.

Mark `TestSceneEnumeratorVersion` as headless

---

osu.Framework.Benchmarks/BenchmarkUnbindAllBindables.cs
osu.Framework/Graphics/Containers/CompositeDrawable.cs
osu.Framework/Graphics/Drawable.cs

At a small memory footprint cost (in the `static` cache), we can improve throughput of `UnbindAllBindables` significantly. I believe this is worth it because we are usually running `UnbindAllBindables` synchronously and every bit helps there, especially in edge case scenarios where many drawables are involved.
This also reduces allocs in construction of the drawable due to not checking the caching at each base type anymore.
For what it's worth, this came up in editor profiling:
---
master
|                  Method |          Mean |      Error |     StdDev |  Gen 0 | Allocated |
|------------------------ |--------------:|-----------:|-----------:|-------:|----------:|
|            TestBaseline |     0.0000 ns |  0.0000 ns |  0.0000 ns |      - |         - |
|   TestCompositeDrawable | …

Remove `EnumerateBaseTypes` overhead in `UnbindAllBindables`

---

osu.Framework/Graphics/Pooling/PoolableDrawable.cs

If a drawable is taken from a pool but never `IsPresent` before being returned, the schduled `PrepareForUse` operation may never run. This can cause a single pooled drawable to end up with thousands of schduled delegates.
In this version, I removed usage of `Scheduler` completely. Rationale is that there was already a flag tracking whether prepare has been run (`waitingForPrepare`) and it may avoid creating a `Scheduler` in the case it is not used elsewhere (as these are lazily created in `Drawable`).
If preferred, [see this branch](https://github.com/ppy/osu-framework/compare/master...peppy:osu-framework:fix-pooling-shit-v1?expand=1) for a version which switches to using `AddOnce`.
This fixes one portion of editor performance during slider rotation eventually degrading …

Fix `PoolableDrawable` prepare call schedules potentially creating overhead if drawable never updated

---

osu.Framework.Benchmarks/BenchmarkWaveform.cs
osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
osu.Framework/Audio/Track/Waveform.cs
osu.Framework/Graphics/Audio/WaveformGraph.cs

Noticed that waveform points are up in the top 5 memory usages in editor (*game*-wide) so did a bit of refactoring. There's likely much more that can be improved here, but this was the low-hanging pass.
Before:
After:
Note that the counts here are a bit off (one more retained array in the "after" run) so savings are probably a touch better than displayed. Also the main goal was to switch away from `Point` being a `class`.
I also looked into reducing overall allocations during construction and resampling. The main fix for this was to reduce the `points_per_iteration` to a more sane number (it was previously allocating a very large buffer with no real benefit performance-wise). And then using `ArrayPool` for it (now that the size is beneath the `ArrayPool` allowance).
These results are …

Reduce overhead of `Waveform`

---

osu.Framework/Graphics/Drawable.cs

This was causing osu! side failures. It "regressed" with #5411, but was only "working" previously due to the relevant base types being cached elsewhere. So a bit of luck that things have been working until now.
I'm not sure how to write test coverage for this (or if it's required), but I've run osu! side tests and confirmed they now pass (see failure on [update attempt](https://github.com/ppy/osu/pull/20328)).

Fix unbind action caching occurring too late

---

osu.Framework/Graphics/Drawable.cs

Caching is still left in place to defer the overhead to a potentially asynchronous load operation. But as we've found, there's a chance `UnbindAllBindables` can be called while a load is also running, and in such cases we want to be assured that the unbind action still runs.
master:
|                  Method |          Mean |      Error |     StdDev |        Median |  Gen 0 | Allocated |
|------------------------ |--------------:|-----------:|-----------:|--------------:|-------:|----------:|
|            TestBaseline |     0.0018 ns |  0.0073 ns |  0.0061 ns |     0.0000 ns |      - |         - |
|   TestCompositeDrawable | 2,075.5773 ns | 21.8103 ns | 17.0280 ns | 2,075.6587 ns | 0.1450 |   1,680 B |
|           TestContainer | 2,243.6053 ns | 23.6792 ns | 20.9910 ns | 2,245.7282 ns | …

Ensure unbind action is always available on request

---

osu.Framework/Graphics/Textures/TextureAtlas.cs

Resolves https://github.com/ppy/osu-framework/issues/5399
I ended up not making this thing an `IDisposable`, because `.Reset()` loses references to the previous texture. I'd have to at least make this into a `List<>`, but I'm also not sure such complexity is required since it's a rare usage. The underlying `TextureGL` will eventually dispose via the finaliser.
Can change this upon request.

Expose `TextureAtlas.Add()`

---

osu.Framework/Graphics/BlendingMask.cs
osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Platform/GameHost.cs

Dependency for supporting front-to-back passes in non-OpenGL renderers.

Add support for blending "write mask" in `IRenderer`

---

osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
osu.Framework/Input/Handlers/Tablet/TabletDriver.cs

Oversight from https://github.com/ppy/osu-framework/pull/5424. Apparently CI does not catch any critical failures on the input handler classes. That's spooky.

Fix unsubscription logic not handling null tablet drivers

---

osu.Framework.Android/Input/AndroidInputHandler.cs
osu.Framework.Android/Input/AndroidJoystickHandler.cs
osu.Framework/Input/Handlers/InputHandler.cs
osu.Framework/Input/Handlers/Midi/MidiHandler.cs
osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs
osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
osu.Framework/Logging/Logger.cs

One step towards better tablet notifications for osu!, see https://github.com/ppy/osu/issues/20324.
This stops them from being posted as notifications with raw messages ([notice `entry.Target == null`](https://github.com/ppy/osu/blob/a2492a4ff5e4b07bc24bca171e9c73efa25b3f8f/osu.Game/OsuGame.cs#L1003)). Instead, it allows the game to treat them differently by checking against `entry.LoggerName == ITabletHandler.LOGGER_NAME` when subscribed to logger events.
Also improves console log output in general:
```
[runtime] 2022-09-16 12:39:24 [verbose]: Starting legacy IPC provider...
[runtime] 2022-09-16 12:39:25 [verbose]: Attempting to use custom storage location /Users/salman/osu-lazer-development/
[runtime] 2022-09-16 12:39:25 [verbose]: Storage successfully changed to …
```

Forward tablet driver output to custom logging target

---

osu.Framework.Tests/IO/TestDesktopStorage.cs
osu.Framework/Platform/NativeStorage.cs

Resolves https://github.com/ppy/osu/issues/19996#issuecomment-1229428045.
Tests do not fail as it stands. I can't figure out the correct call to reproduce what the user was seeing. Help.

Fix nested storage lookup check not accounting for case insensitive filesystems

---

osu.Framework/Graphics/Rendering/Renderer.cs

Previously, we were maintaining a variable pointing to the current shader such that if a `Pop` then `Push` happened resulting in the same shader being bound, it would not trigger a buffer flush or any draw call overhead.
This check was removed incorrectly.
Regressed in https://github.com/ppy/osu-framework/pull/5404.
Closes ppy/osu#20421.

Fix VBO incorrectly flushing on no-op shader bind

---

osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
osu.Framework/Graphics/Containers/ScrollContainer.cs

No reason not to have these methods exposed, quite useful.

Expose `ScrollContainer.Target`

---

osu.Framework/Platform/Windows/IWindowsRenderer.cs
osu.Framework/Platform/Windows/WindowsGLRenderer.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

Resolves https://github.com/ppy/osu/issues/19961
I've moved the code to `WindowsGLRenderer` since it now queries the GL vendor to check if it's `Intel`. I've tested this to work as expected on a PC with only an Intel iGPU and a laptop with both iGPU and dGPU (Optimus).
Hopefully this won't interfere with @frenzibyte 's changes.

Always show exclusive fullscreen as enabled on Intel platforms

---

osu.Framework/Graphics/Rendering/Renderer.cs

As mentioned in https://github.com/ppy/osu-framework/pull/5431#discussion_r979790479.

Fix `Shader` not reset to null when completely unbound

---

osu.Framework/Graphics/Rendering/Renderer.cs

Haven't profiled this yet, but I've noticed certain cases where VBO could be flushed while no actual changes occur. Most of these cases may come from a path where flushing VBO wouldn't add any overhead, but still worth having it to define the real purpose of this method for any future renderer states (we could also consider encapsulating these methods into a `RendererState` class, but that's for a rainy day).
Everything seems to still work fine, but double-checking would be appreciated.

Avoid flushing VBO when the renderer state is not affected

---

osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/SDL2DesktopWindow_Input.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

This mostly moves code around, the only actual code changes are enabling NRT and c760ade059cc852a86b84b05f3c853345fdda5cb.
Hopefully this will make future changes easier, as the relevant code is now closer together.

Split out windowing and input of `SDL2DesktopWindow` into partial classes

---

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextSizing.cs
osu.Framework/Graphics/Sprites/SpriteText.cs

Previously, it would wait until the end of the current frame for the `DrawNode` to be created and the `charactersCache` invalidation to cause the `Width`/`Height` to change. Only then would `Drawable.drawSizeBacking` be invalidated and queries to `DrawWidth` return the correct value.

Fix `SpriteText` size not immediately responding to changes in text

---

osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
osu.Framework/Platform/Display.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

peppy reported it [on discord](https://discord.com/channels/188630481301012481/589331078574112768/1019675813953683568): `Displays` were queried in a hot path (every frame).
Adds `DisplaysChanged` event to `IWindow` so consumers can watch for display changes. For now, this doesn't check if the displays actually changed, and will be invoked every time the displays are queried.

Fix `Displays` querying on every access and add `DisplaysChanged`

---

osu-framework.sln.DotSettings
osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
osu.Framework.Tests/IO/TestWebRequest.cs
osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework.Tests/Visual/Drawables/TestSceneSynchronizationContext.cs
osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
osu.Framework.Tests/Visual/Sprites/TestSceneAnimationLayout.cs
osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
osu.Framework/Audio/AudioManager.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Development/DebugUtils.cs
osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
osu.Framework/Extensions/ExtensionMethods.cs
osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
osu.Framework/Graphics/Pooling/PoolableDrawable.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs
osu.Framework/Graphics/Video/VideoDecoder.cs
osu.Framework/IO/Network/JsonWebRequest.cs
osu.Framework/IO/Stores/DllResourceStore.cs
osu.Framework/Input/KeyEventManager.cs
osu.Framework/Input/MouseButtonEventManager.cs
osu.Framework/Platform/NativeStorage.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/Storage.cs
osu.Framework/Testing/TestBrowser.cs
osu.Framework/Threading/Scheduler.cs
osu.Framework/Timing/FramedOffsetClock.cs

Most of the inspections were weaker in o!f, except `UnusedParameter.Local` which lowered from `warning` to `hint`.

Copy DotSettings `CodeInspection`s from osu! sln

---

osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

As suggested in https://github.com/ppy/osu-framework/issues/5448#issuecomment-1271688677 / https://github.com/ppy/osu-framework/issues/5448#issuecomment-1271743831.
'Fetch' means that the method queries SDL state and saves it.
'Update' means the SDL state is updated by a change in framework state.

Rename `update` → `fetch` where applicable in `SDL2DesktopWindow`

---

osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

Preparation for bigger changes for #5448.
Removes the weird 'refetch on failure' logic.

Cleanup `fetchDisplayMode()`

---

osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs

Required for inline country flag rendering support osu!-side.

Allow handling `CustomContainerInline` markdown objects for custom components

---

osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
osu.Framework.Tests/Visual/Platform/WindowDisplaysPreview.cs

The new `WindowDisplaysPreview` might be useful for future tests, so this is a preemptive refactor.
Before:
After:

Refactor borderless test for component reuse and to show more info

---

osu.Framework/Input/Handlers/Tablet/TabletDriver.cs

- Addresses https://github.com/ppy/osu/discussions/20660
This was never noticed because tablet pointer is still reported correctly as it goes through another flow that's independent from the `TabletDriver` logic. Bit of a weird code, but gonna restrain myself from touching it further for now.

Fix tablets connected on startup not working properly

---

osu.Framework/Resources/Shaders/sh_HueSelectorBackground.fs
osu.Framework/Resources/Shaders/sh_HueSelectorBackgroundRounded.fs
osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
osu.Framework/Resources/Shaders/sh_SaturationSelectorBackgroundRounded.fs

- Closes https://github.com/ppy/osu/issues/14383
Follows a similar solution to what https://github.com/ppy/osu-framework/pull/5065 did. See https://github.com/ppy/osu-framework/pull/5065#discussion_r825536715 for detailed explanation. Renders correctly on iOS now.

Fix colour picker background not rendering correctly on mobile platforms

---

osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs

Noticed in https://github.com/ppy/osu-framework/pull/5459#issuecomment-1277748045.

Fix fullscreen test failing if window is on non-primary display

---

osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs
osu.Framework/Graphics/UserInterface/CircularProgress.cs

- Regressed in https://github.com/ppy/osu-framework/pull/5065
As far as my knowledge in framework rendering goes, "opaque interiors" are for drawables which have a completely opaque rectangular shape such as `Sprite`s with white pixel texture and singular opaque colours. This doesn't fit `CircularProgress`, which has a circular shape with non-opaque areas regardless of the texture/colour.
Before:
After:

Fix `CircularProgress` having an opaque interior drawn on FTB pass

---

osu.Framework/Platform/SDL2/SDL2Extensions.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

- Supersedes https://github.com/ppy/osu-framework/pull/5371
Trying to fix:
- https://github.com/ppy/osu/issues/19064
- https://github.com/ppy/osu/discussions/20481
- https://github.com/ppy/osu/issues/19877
- https://github.com/ppy/osu/issues/20347
This PR expands `getClosestDisplayMode()` to use [`SDL_GetDesktopDisplayMode`](https://wiki.libsdl.org/SDL_GetDesktopDisplayMode), and to query the first display mode of a display directly with [`SDL_GetDisplayMode`](https://wiki.libsdl.org/SDL_GetDisplayMode). Also includes additional logging.
Let's get this in for user testing, if it proves to work without crashes then I'd hope to cut down this logic to:
- try requested `display index`, `size`, `refresh rate`
- try requested `display index`, `size`
- try requested `display index` (use default …

Harden `getClosestDisplayMode()` to return a valid display mode in more scenarios

---

CodeAnalysis/BannedSymbols.txt

- Companion to https://github.com/ppy/osu/pull/20855

Ban `char.ToLower()`/`char.ToUpper()` as well for better safety

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs

Fixes https://discord.com/channels/188630481301012481/589331078574112768/1033248812862554122.
Scheduling changes is already done for `Current` so doing it for `ItemSource` shouldn't cause problems.
Having an atomic way to replace items in `BindableList` would also be beneficial. Currently, items must first be removed, and only then added.

Fix replacing items in dropdown changing selection

---

osu.Framework.Benchmarks/BenchmarkColourInfo.cs
osu.Framework/Graphics/Colour/ColourInfo.cs
osu.Framework/Graphics/Lines/Path_DrawNode.cs

The performance gains here are mostly theoretical and I can't benchmark them meaningfully in a real-world scenario. Consider this more of a refactoring that adds an optimal (and more user-friendly) method for checking whether a `ColourInfo` represents a single colour and then returning that colour.
This comes off the back of the osu!-side smoke implementation (where I initially noticed this), which potentially uses this method for tens of thousands of vertices (up to 30k is what I was able to achieve after [the recent changes](https://github.com/ppy/osu/pull/20827)). Similar is also done with slider paths (e.g. at some point https://osu.ppy.sh/beatmapsets/756794#osu/1605148 draws some 20k vertices). So _at most_ you'd see ~0.2ms frametime improvement.
Before
|              Method | …

Optimise `ColourInfo` conversion and add conversion helper method

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs

Fixes https://github.com/ppy/osu/issues/7477
These texture uploads may be crucial for the few frames before the texture's usage has concluded.

Fix texture uploads potentially disposed too early

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs

Just things I find while reviewing my code 100 times over.

Make `GLTexture` disposal action not capturing

---

osu.Framework/Resources/Shaders/sh_CircularBlobUtils.h

* `pointCount` is based on input parameters now (in ctb case should become around 10 instead of 50)
* Removed early loop exit as suggested

CircularBlob shader improvements

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Rendering/Dummy/DummyNativeTexture.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/INativeTexture.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Visualisation/TextureVisualiser.cs

Fix `Renderer` holding a permanent reference to every texture ever created

---

osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
osu.Framework/Graphics/Pooling/DrawablePool.cs

I was confused by the previous output, as it didn't do a great job showing the current pool usage – specifically it was not showing the current pool size in the denominator portion of the display, but the total usages. Which didn't make much sense at all.
The new format is `currentUsage / poolSize (x excess)`. Hopefully this is self-explanatory, so check that your understanding matches the following:
- `currentUsage` includes all current usages that started with a `Get` from the pool, and is decremented on each `Return`. This includes excess usages (that will not be returned to the pool).
- `poolSize` is the current size of the pool, ranging from `initialSize` to `maximumSize`. It is increased at the point of construction, not `Return`
- `excess` is the total excess drawables constructed …

Refactor drawable pool statistics output to make more sense

---

osu.Framework/Graphics/UserInterface/CircularBlob.cs
osu.Framework/Resources/Shaders/sh_CircularBlob.fs
osu.Framework/Resources/Shaders/sh_CircularBlobRounded.fs
osu.Framework/Resources/Shaders/sh_CircularBlobUtils.h

Should potentially fix iOS visual issue, but it's hard to tell beforehand.
Calculating the same value for each pixel was not clever anyway.

Compute CircularBlob's noise position in the DrawNode

---

osu.Framework.Tests/Audio/BassTestComponents.cs
osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs
osu.Framework.Tests/Audio/TrackVirtualTest.cs
osu.Framework/Threading/GameThread.cs

This is just for my own sanity due to limitations in dotTrace. Without this, the actual part we care about (the thread's purpose) is truncated in the dotTrace interface with no way to properly view it.
I'm open to any other proposals
| -- | -- |
|![image](https://user-images.githubusercontent.com/191335/200158184-675891d1-32fb-44b0-a20d-286e892ad32a.png)|![image](https://user-images.githubusercontent.com/191335/200158186-68d785eb-5ca2-4f63-933d-0773be61ad6c.png)|

Change game thread prefixes to suffixes

---

osu.Framework.Tests/Localisation/ThreadCultureTest.cs
osu.Framework/Platform/ThreadRunner.cs
osu.Framework/Threading/GameThread.cs

While the `Thread == null` check does make some sense, `InputThread` never has a backing native `Thread` and the culture change therefore fails there.
In single threaded, it's basically setting the thread culture 5 times on the same thread, but I don't see this causing any problems.
Changed to always use `CultureInfo.CurrentCulture` as per [MS docs recommendations](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.currentculture?view=net-6.0#remarks).

Fix `FrameworkSetting.Locale` not changing `InputThread` culture

---

osu.Framework.Tests/Localisation/CultureInfoHelperTest.cs
osu.Framework.Tests/Localisation/ThreadCultureTest.cs
osu.Framework/Localisation/CultureInfoHelper.cs
osu.Framework/Localisation/LocalisationManager.cs

Changes the default culture (when `FrameworkSetting.Locale` is set to `string.Empty`) to use the system culture (instead of the invariant culture) for all usages (and not only in `LocalisationManager`).
First step towards resolving https://github.com/ppy/osu/issues/21146.

Default `CurrentCulture` to system culture

---

osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
osu.Framework/Platform/NativeMemoryTracker.cs

Especially in cases like song select, we are churning a lot of GPU memory. This will eventually be fixed, but until then it seems that making the GC aware of this usage is detrimental to performance. In some very non-scientific benchmarks, removing these calls reduced gen 2 GC run counts by around 40-50% while paginating at song select.
@smoogipoo mentioned that he noticed this in the past, which resulted in https://github.com/ppy/osu-framework/pull/4298.  This PR undoes the changes there so we can once again see VBO memory usage in the global statistics overlay, but removes the underlying calls to `AddMemoryPressure` and `RemoveMemoryPressure` to maintain the expected behaviour.

Remove all usage of `Add`/`RemoveMemoryPressure`

---

osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
osu.Framework/Platform/Windows/Native/Execution.cs
osu.Framework/Statistics/FrameStatistics.cs
osu.Framework/Statistics/PerformanceMonitor.cs
osu.Framework/Threading/GameThread.cs
osu.Framework/Timing/FramedClock.cs
osu.Framework/Timing/ThrottledFrameClock.cs

Intends to fix the remaining inaccuracy that can be seen when running at frame rates close to the maximum precision provided by `Thread.Sleep` on windows.
A few preliminary notes:
- This is windows only. Other (unix/linux) platforms already had higher precision thread sleep. Of note, this does now perform `Thread.Sleep` using floating point rather than hard `int` rounding, so it may marginally improve results on non-windows platforms
- Frame jitter is now displayed on the frame statistics display. This is standard deviation between `NewFrame` calls averaged over last 256 frames
- Don't trip over the pinvoke code. I considered using [Vanara](https://github.com/dahall/Vanara) for this but that had a few issues (and the DLL is a bit large so we'd want pruning support). See …

Use (high resolution) waitable timers on windows when available

---

osu.Framework/Timing/ThrottledFrameClock.cs

As discussed IRL. This might help marginally in cases where the game is not able to keep up with the user's specified frame limiter, by removing the yield overhead (~0.2ms for me, but maybe higher on lower end hardware).

Don't yield when game can't keep up

---

osu.Framework/Graphics/Rendering/FlushBatchSource.cs
osu.Framework/Graphics/Rendering/IVertexBatch.cs
osu.Framework/Graphics/Rendering/Renderer.cs

Log sources of VBO flushes (aka batching interruptions) to global statistics

---

osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
osu.Framework/Graphics/Animations/AnimationClockComposite.cs
osu.Framework/Graphics/Containers/CompositeDrawable.cs
osu.Framework/Graphics/Containers/Container.cs
osu.Framework/Graphics/Containers/FlowContainer.cs
osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
osu.Framework/Graphics/Containers/SearchContainer.cs
osu.Framework/Graphics/UserInterface/Popover.cs
osu.Framework/Testing/TestScene.cs

Not actually required.
`RemoveInternal` and `ClearInternal` are a bit more involved to remove, so I've just hit this one for now. It bit me and I didn't like it.

Remove `internal` access modifier from `CompositeDrawable.AddInternal`

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs

Ran into this while trying to show system default language in osu! settings.
The following causes a NRE with `localisation`:
```cs
protected class LanguageDropdownControl : DropdownControl
{
[Resolved]
private LocalisationManager localisation { get; set; } = null!;
protected override LocalisableString GenerateItemText(Language item)
{
if (item == Language.SystemDefault)
{
if (LanguageExtensions.TryParseCultureCode(localisation.SystemDefaultLocaleMapping?.Name, out var language))
return GeneralSettingsStrings.DefaultLanguage(language.GetDescription());
return CommonStrings.Default;
}
return base.GenerateItemText(item);
}
}
```

Fix `Dropdown` calling `GenerateItemText` before it's loaded

---

osu.Framework.Tests/Text/TextBuilderTest.cs

Makes it easy to test a variety of scenarios without adding more glyphs to the test, and also bring some sanity while mentally parsing test failures arising from text builder changes.

Load genuine font for text builder test in favour of hardcoded glyph numbers

---

osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/BindableBool.cs
osu.Framework/Bindables/BindableDictionary.cs
osu.Framework/Bindables/BindableDouble.cs
osu.Framework/Bindables/BindableFloat.cs
osu.Framework/Bindables/BindableInt.cs
osu.Framework/Bindables/BindableList.cs
osu.Framework/Bindables/BindableMarginPadding.cs
osu.Framework/Bindables/BindableNumber.cs
osu.Framework/Bindables/BindableSize.cs
osu.Framework/Bindables/IBindable.cs
osu.Framework/Configuration/IniConfigManager.cs

Noticed while looking into https://discord.com/channels/188630481301012481/589331078574112768/1040392278348398703.
This results in the following problem when decoding osu! config when using `Norsk` language:
```cs
2022-11-13 22:35:08 [important]: Unable to parse config key LastProcessedMetadataId: System.FormatException: Input string was not in a correct format.
2022-11-13 22:35:08 [important]: at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
2022-11-13 22:35:08 [important]: at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
2022-11-13 22:35:08 [important]: at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
2022-11-13 22:35:08 [important]: at osu.Framework.Bindables.Bindable`1.Parse(Object …
```

Make `IBindable : IFormattable` to allow formatting its value with `InvariantCulture`

---

osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs

Intended to be used for performance testing overhead of texture uploads in a `TextureAtlas`.
https://user-images.githubusercontent.com/191335/201859146-d7bb821f-f22c-4d10-8af7-4ba870fc912d.mp4

Refactor `SpriteIcon` tests to allow slowly adding new icons

---

osu.Framework/Platform/SDL2DesktopWindow_Input.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

Only possible behaviour change is combining `currentDisplay` and `CurrentDisplay` into one field, but looking at the flow, this shouldn't change anything.
Other changes are purely code-quality.

Small code quality pass on `SDL2DesktopWindow`

---

osu.Framework/Graphics/Drawable.cs

See https://www.jetbrains.com/help/rider/ReadAccessInDoubleCheckLocking.html.
It was probably maybe fine but best to follow standards.
Importantly, it's no longer using the `??=` operator, which is apparently maybe not safe (according to a rider inspection that didn't trigger here but did in a similar case in #5533).

Fix potentially incorrect implementation of double-locking in `Drawable.Scheduler` retrieval

---

osu.Framework/Audio/AdjustableAudioComponent.cs

This is beneficial due to the number of samples which are retrieves during BDL load but never played. In cases they aren't played the `Sample`s retrieved from a `SampleFactory` can avoid the `AudioAdjustments` overhead, which will now only be instantiated when they are played (see https://github.com/ppy/osu-framework/blob/32e7571aa858c4d055f45cc487c08a11aab64817/osu.Framework/Audio/Sample/SampleBassFactory.cs#L100-L105)
Logging can be performed using this adjustment:
```diff
diff --git a/osu.Framework/Audio/AdjustableAudioComponent.cs b/osu.Framework/Audio/AdjustableAudioComponent.cs
index 41b834da0..f5813a763 100644
--- a/osu.Framework/Audio/AdjustableAudioComponent.cs
+++ b/osu.Framework/Audio/AdjustableAudioComponent.cs
@@ -2,6 +2,7 @@
// See the LICENCE file in the repository root for …
```

Lazy init `AudioAdjustments` in `AdjustableAudioComponent` usage

---

osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

- Closes https://github.com/ppy/osu-framework/issues/5451
First idea for a fix was to cover all the cases of `SDL_WindowEvent` that might be sent when displays update, but that quickly spiraled out of control. SDL might send the events in a different order, so the first one would fail the assertion, even though a later event would trigger `fetchDisplays()` as expected. Moving the assert to after the event loop fixed some of those cases.
Fetching the displays in `updateWindowStateAndSize()` also seems amicable as changing the window state will almost always change the displays (if using a non-native resolution).

Fix displays sometimes not getting updated and failing assertion

---

osu.Framework.Benchmarks/BenchmarkBindableInstantiation.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/BindableNumber.cs
osu.Framework/Bindables/RangeConstrainedBindable.cs

This method is used heavily in `AudioAdjustments`, which is how I got here.
https://github.com/ppy/osu-framework/blob/ba1385330cc501f34937e08257e586c84e35d772/osu.Framework/Audio/AudioAdjustments.cs#L68
|         Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|--------------- |---------:|--------:|--------:|-------:|----------:|
| GetUnboundCopyOld | 940.6 ns | 6.14 ns | 5.13 ns | 0.0629 |     736 B |
| GetUnboundCopyNew | 38.95 ns | 0.848 ns | 1.160 ns | 0.0153 |     176 B |
To improve the performance of creating clones of bindables (ie. via `GetUnboundCopy()`), the copy portion of `BindTo()` has been split out into its own method. If you have any custom bindable types which were copying values across within a `BindTo()` override, please move the copy operation to …

Add `Bindable<T>.CopyTo` and use in `GetUnboundCopy` implementation

---

osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework/Game.cs
osu.Framework/Localisation/CaseTransformableString.cs
osu.Framework/Localisation/CultureInfoHelper.cs
osu.Framework/Localisation/LocalisationManager.cs
osu.Framework/Localisation/LocalisationParameters.cs
osu.Framework/Localisation/RomanisableString.cs

Just some small changes to be used in follow-up PRs.
The `protected`/`virtual` methods in `LocalisationManager` couldn't ever be used, because inheriting `LocalisationManager` would break everything as it wouldn't be cached as `LocalisationManager`. Therefore a04cb19d074a12f89693e9e8f39c2a2e3816bb81 is not a breaking change.
These methods are also strange in general since inheritors can't use the `private` fields that are required for `LocalisationParameters`.

Cleanup `LocalisationManager` and related classes

---

osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework/Localisation/CultureInfoHelper.cs
osu.Framework/Localisation/LocalisationManager.cs

This PR adds `SystemDefaultLocaleMapping` as a way to get which mapping is the default (for `Locale = ""`).
The `LocaleMapping.Name` now needs to match `FrameworkSetting.Locale` exactly (case-insensitive) for it to be used.
Loose matching doesn't make sense as `FrameworkSetting.Locale` is controlled by the game. The game knows what locales it has added and can set the `Locale` appropriately.
Loose matching is used for the `SystemDefaultLocaleMapping`, where it's needed.

Refactor `LocaleMapping` lookup to require an exact match to `FrameworkSetting.Locale`

---

osu.Framework/Graphics/Video/VideoDecoder.cs

See: https://github.com/FFmpeg/FFmpeg/blob/98f6c59f4f614f7409b225930a16a2172512c432/libavformat/avio.h#L405

Correctly return `AVERROR_EOF` in `VideoDecoder`

---

osu.Framework.Tests/Bindables/RangeConstrainedBindableTest.cs
osu.Framework/Bindables/RangeConstrainedBindable.cs

Regressed in 9faae09581d9c4aa24175ed78197720fd983e40e.
When copying over values of a range-constrained bindable, the range bounds need to be transferred first, because otherwise assignment to `.Value` of a range-constrained bindable will automatically clamp the value to [`MinValue`, `MaxValue`], leading to a scenario where a new value being transferred across would get clamped to stale bounds.
This affected both `.CopyTo()` and `.BindTo()`, as the latter calls the former.

Fix wrong range constrained bindable value transferal in `CopyTo()`

---

osu.Framework/Graphics/UserInterface/CircularBlob.cs
osu.Framework/Graphics/UserInterface/CircularProgress.cs
osu.Framework/Resources/Shaders/sh_CircularBlob.fs
osu.Framework/Resources/Shaders/sh_CircularProgress.fs

Moved to the `DrawNode` instead.
Also fixes an issue when `CircularProgress` is rendering nothing when `progress = 0` with rounded caps enabled.

Move early return conditions away from CircularProgress and CircularBlob shaders

---

osu.Framework.Tests/Dependencies/SourceGeneration/CachedAttributeTest.cs
osu.Framework.Tests/Dependencies/SourceGeneration/CachedModelDependenciesTest.cs

These were added and documented in https://github.com/ppy/osu-framework/pull/5543, but have been solved now that the `IDependencyInjectionCandidate` interface exists.

Remove unnecessary caching in dependencies tests

---

osu.Framework.SourceGeneration/Common/Emitters/DependenciesFileEmitter.cs
osu.Framework.SourceGeneration/Common/GeneratorClassCandidate.cs
osu.Framework.SourceGeneration/Common/SyntaxHelpers.cs
osu.Framework.SourceGeneration/Roslyn3.11/DependencyInjectionSourceGenerator.cs
osu.Framework.SourceGeneration/Roslyn3.11/GeneratorClassCandidateComparer.cs
osu.Framework.SourceGeneration/Roslyn3.11/osu.Framework.SourceGeneration.Roslyn3.11.csproj
osu.Framework.SourceGeneration/Roslyn4.0/DependencyInjectionSourceGenerator.cs
osu.Framework.SourceGeneration/Roslyn4.0/SyntaxTarget.cs
osu.Framework.SourceGeneration/Roslyn4.0/SyntaxTargetNameComparer.cs
osu.Framework.SourceGeneration/Roslyn4.0/osu.Framework.SourceGeneration.Roslyn4.0.csproj

Supersedes https://github.com/ppy/osu-framework/pull/5559
The layers are explained in the inline comments of [Roslyn4.0/DependencyInjectionSourceGenerator.cs](https://github.com/ppy/osu-framework/compare/master...smoogipoo:generator-perf-improvements-2?expand=1#diff-19b184a8412fdfa700026f76634239a74d7d87479e7be62b5665d80d9385d3eb), however for a quick explanation:
- In the first layer, `ClassDeclarationSyntax`es arrive and are transformed into `SyntaxTarget`s.
- `SyntaxTarget` initially contributes to caching via the `ClassDeclarationSyntax`. That is, when the same class arrives again, the _previous_ `SyntaxTarget` is used (even though a new one is created, it's discarded right away).
- The above allows us to store some information in the `SyntaxTarget`, with a few caveats:
- We can …

Rework source generator to promote memoisation

---

.github/workflows/report-nunit.yml

The only reason I'm bothering to do this is that I mistakenly clicked on one of the execution logs of the "Annotate CI with test results" workflow and [noticed a bunch of deprecation warnings](https://github.com/ppy/osu-framework/actions/runs/3609327841).
Judging from the release notes [[1]] and diffstat [[2]] of version 1.6.0 of the action affected, a bump should silence these.
Tested to have the expected result [on my fork's master][3].
[1]: https://github.com/dorny/test-reporter/blob/main/CHANGELOG.md
[2]: https://github.com/dorny/test-reporter/compare/v1.4.2...v1.6.0
[3]: https://github.com/bdach/osu-framework/actions/runs/3610527220

Bump `dorny/test-reporter` action to 1.6.0

---

osu.Framework/Bindables/IBindable.cs
osu.Framework/Configuration/IniConfigManager.cs
osu.Framework/Extensions/FormattableExtensions.cs
osu.Framework/Extensions/IFormattableExtensions.cs

This is essentially a workaround for what is ostensibly going to be a xamarin or mono bug which is causing https://github.com/ppy/osu/issues/21530.
The explanation is thus: The reason why the config files were zero-byte is that an exception was being thrown ([and silenced](https://github.com/ppy/osu-framework/blob/07ef9aa7f3053eeb750e8e4a43fd8a6f19bbe5b0/osu.Framework/Configuration/IniConfigManager.cs#L96-L99)) in `PerformSave()`. This is the exception:
```
System.InvalidCastException: Object must implement IConvertible.
at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) [0x00040] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Convert.cs:340 
at …
```

Remove `IBindable.ToString()` default interface implementations

---

osu.Framework.SourceGeneration/Build.targets
osu.Framework.SourceGeneration/pack.sh

Getting this error when loading the project in Visual Studio 2022 (v17.4.1):

Fix source generator csproj wildcard

---

osu.Framework/IO/Stores/RawCachingGlyphStore.cs

Just happened across this while profiling something completely unrelated and it was too good to pass on:
Before:
| Method                   | FetchCount |           Mean |        Error |       StdDev | Ratio | RatioSD |     Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|--------------------------|------------|---------------:|-------------:|-------------:|------:|--------:|----------:|----------:|----------:|----------:|
| BenchmarkRawCachingReuse | 1          |       901.2 us |      4.16 us |      3.89 us |  0.07 |    0.00 |    1.9531 |    0.9766 |         - |     28 KB |
| BenchmarkRawCaching      | 1          |    12,293.7 us |    122.75 us |    108.82 us |  1.00 |    0.00 |   15.6250 |   15.6250 |   15.6250 |     78 KB |
|                          |            |                | …

Retrieve span outside of loop to improve performance of glyph texture creation

---

osu.Framework/Graphics/Textures/TextureWhitePixel.cs

Supersedes https://github.com/ppy/osu-framework/pull/5575 as an actual fix.

Fix WhitePixel texture rectangle doesn't respect provided area

---

osu.Framework/Graphics/Video/FFmpegFuncs.cs
osu.Framework/Graphics/Video/VideoDecoder.cs

As we shifted towards using `FFmpegFuncs` for constants to avoid runtime exceptions on mobile platforms, one more case popped up recently from https://github.com/ppy/osu-framework/pull/5539 which wasn't updated before merging https://github.com/ppy/osu-framework/pull/5080.
I've also removed the namespace alias of the class as it's no longer used frequently.

Fix one more case of using AutoGen's `ffmpeg` class for constants

---

osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

This just fixes the error on startup, the min and max size worked fine and applied properly on startup here:
https://github.com/ppy/osu-framework/blob/1e54caf879c4abb7c382e7f182cab589f4e51040/osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs#L109
The error in the logs:
```cs
2022-12-15 20:37:37 [verbose]: SDL error log [debug]: Invalid window
2022-12-15 20:37:37 [verbose]: SDL error log [debug]: Invalid window
```

Fix SDL error on startup caused by setting min/max size before window creation

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Platform/ILinuxGraphicsSurface.cs
osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

- Selects X11/Wayland surface.
- Fixes nulled pointers caused by lack of passing the version via `SDL_GetWindowWMInfo`.
It works to the point I can get it to run, but crashes soon after with
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Veldrid.Vk.VkSwapchainFramebuffer.get_ColorTargets()
at Veldrid.Vk.VkCommandList.SetFramebufferCore(Framebuffer fb)
at Veldrid.CommandList.SetFramebuffer(Framebuffer fb)
at osu.Framework.Graphics.Veldrid.VeldridRenderer.SetFrameBufferImplementation(IFrameBuffer frameBuffer) in /home/smgi/Repos/osu-framework/osu.Framework/Graphics/Veldrid/VeldridRenderer.cs:line 244
at osu.Framework.Graphics.Rendering.Renderer.setFrameBuffer(IFrameBuffer frameBuffer, Boolean force) in …
```

Fix some issues with Veldrid/Vulkan on Linux

---

osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj

Brought from `osu.Framework.iOS.props`, required properties for consumers to have their projects build successfully.

Include missing properties to iOS templates

---

.github/workflows/deploy-pack.yml
osu.Framework.Templates/replace-references.sh
osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj

Allows the workflow to be used in favour of AppVeyor, which is practically dead recently with the migration to net6.0-ios (see https://ci.appveyor.com/project/peppy/osu-framework-a4n7e/build/job/451dtsr68hu8hepa).

Replace project references during packing templates in GH workflow

---

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnote.cs
osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteBacklink.cs
osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteGroup.cs
osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteLink.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs

Step one for https://github.com/ppy/osu/issues/21666.
The framework-side implementation is purposefully ~~barebones~~ basic. I didn't want to spend too much time on it and instead focused on the game-side implementation. But if you think there were too many shortcuts taken here, then do let me know and I'll revisit.
There is a test scene to preview this in available:

Add footnote support to Markdown container

---

osu.Framework/Platform/GameHost.cs

This has been causing Metal to not render anything on my end when I bypass front-to-back pass, and looks to be an actual oversight that has miraculously not affected OpenGL all these years.

Fix bypassing front-to-back not actually disabling depth test

---

osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs

Was an annoying one to me, as the moment I accidentally switch to this test scene everything crashes because of the GL occlusion queries being performed in the draw node, and there's no way to escape this crash without commenting the entire test scene.

Avoid performing GL occlusion queries on Veldrid

---

osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs

Having `yield return` here is weird and unnecessary. Using a plain `ImmutableArray` makes things clearer.

Remove unnecessary `yield return` from `getSDLDisplays()` and log errors

---

.github/workflows/deploy-pack.yml

Oversight from #5594, explains why the templates package wasn't included in the artifacts output.

Fix wrong path separator used in templates pack CI

---

.github/workflows/ci.yml

GH actions recently rolled a new image for macOS that comes with .NET 7.0.1 installed, and apparently restoring workloads with it on .NET 6 macOS/iOS projects no longer works correctly (see https://github.com/xamarin/xamarin-macios/issues/16400). Until .NET 8, explicitly install the required workloads instead.

Fix iOS workflow failing to restore workloads

---

osu.Framework/Resources/Shaders/sh_Texture2D.vs
osu.Framework/Resources/Shaders/sh_Texture3D.vs

- Closes ppy/osu#21775
As deduced by @NiceAesth in https://github.com/ppy/osu/issues/21775#issuecomment-1364735197 after thorough investigation and trial-and-error. It appears that due to iPads having a maximum texture size of 16384x16384, the texture coords/rectangle of a white pixel texture (which exceed `mediump` range due to max texture size being high) already get lost while plotting fragments for colour picker shaders and circular progresses/blobs, and that turns out to be due to the vertex shader being limited to `mediump`. 
I am not sure why this isn't the case on my iPhone, but my humble guess is that the way OpenGL determines the best precision for each variable differs between an iPhone and an iPad for unknown reasons. I'm also assuming this doesn't happen on Android devices …

Fix iPad devices not rendering colour pickers and circular progresses/blobs

---

osu.Framework/Graphics/Containers/Markdown/MarkdownFencedCodeBlock.cs

Noticed this one when looking at the `wiki/Skinning/skin.ini/Blank` wiki page in the `WikiOverlay` in osu!. That wiki page in particular has some good examples of this, which are shown below.
Behaviour should be the same, changed `AddParagraph()` to `AddText()` to allow for paragraphs to be created on new lines as before. Unsure we need tests for this one?
(Sorry for the horrible formatting of the table below...)
| ------- | ------ |
| ![image](https://user-images.githubusercontent.com/29103029/211207320-3b707322-928e-45e1-892d-d1b66d5140da.png) | ![image](https://user-images.githubusercontent.com/29103029/211207648-efc038ea-4f15-4e2f-a511-fcebf61bfaa3.png) |
| ![image](https://user-images.githubusercontent.com/29103029/211207350-36eb4880-95a4-4abf-9ff8-075a9307f3e5.png) …

Fix `MarkdownFencedCodeBlock` potentially adding empty space at the end of the block

---

osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGame.cs
osu.Framework/Game.cs

- Companion to https://github.com/ppy/osu/pull/22141 
`Game` already wraps a container for `Content`, so there have been two ways to add components to a game, which lead to broken drawable order as seen in ppy/osu#22141 due to using both ways (`AddInternal` and `Add`). 
To limit this from happening, `AddInternal` has been completely disabled in favour of using `Add` instead.

Disallow using `AddInternal` in game class

---

osu.Framework/Platform/Windows/WindowsWindow.cs

This hack is not needed on Direct3D 11 as exclusive fullscreen is [disabled by default in DirectX](https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/) (as evident by overlays showing on top of the game).
The hack appears to also be required on Vulkan (tested on AMD GPU):
> Amount of extra width added to window size when in borderless mode on Windows.
> Some drivers require this to avoid the window switching to exclusive fullscreen automatically.
I don't have this exact exclusive fullscreen issue, but I do get something similar: disabling the hack (set value to 0) results in a short black flicker when alt-tabbing in and out of the game (both OpenGL and Vulkan). There is no flicker when using Direct3D 11, in both fullscreen and borderless modes.
---
I tried out …

Disable 1px width hack when using Direct3D 11

---

osu.Framework/Host.cs
osu.Framework/Platform/IconGroup.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/Windows/Native/Icon.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs
osu.Framework/Platform/Windows/WindowsMouseHandler.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

It was really wrong that `SDL2DesktopWindow` was using `osu.Framework.Platform.Windows.Native`. This was caused by `IconGroup` being in that namespace, even though most of `IconGroup` is platform-agnostic.
This PR moves `IconGroup` to the more general `osu.Framework.Platform` namespace and then appropriately annotates the windows-specific `Icon`/`CreateIcon` API usage with [`SupportedOSPlatform`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-7.0).

Move `IconGroup` out of `osu.Framework.Platform.Windows.Native` namespace and annotate with `SupportedOSPlatformAttribute`

---

.github/workflows/deploy-nativelibs.yml

Noticed while checking #5629. 
- Failed run: https://github.com/frenzibyte/osu-framework/actions/runs/3967472136/jobs/6799488672. 
- "Successful" run: https://github.com/frenzibyte/osu-framework/actions/runs/3967529353/jobs/6799603895 (failed because I'm pushing with wrong package ID).

Fix nativelibs deployment script installing outdated .NET version

---

osu.Framework/Input/Bindings/KeyBindingContainer.cs

A change i have floating around which may or may not be used for touch support, but good to have anyway.

Return the handling drawable on calling `TriggerPressed`

---

osu.Framework.Tests/Bindables/BindableBindingTest.cs
osu.Framework.Tests/Bindables/BindableDictionaryTest.cs
osu.Framework.Tests/Bindables/BindableListTest.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/BindableDictionary.cs
osu.Framework/Bindables/BindableList.cs

I've also changed `Bindable` to match the message (and removed the instance string output part because it's already bound and will share the same value, therefore pointless). 
This may be the ultimate key as to why we're seeing these `IndexOutOfRangeException`s osu!-side with multiplayer tests (cc @smoogipoo, might interest you). It's significantly hinted in the error output:
As it can be seen, `MultiplayerClient` removes the playlist item via index, and that first propagates the change from the first bindable to the second bindable, which then propagates to another bindable that since fails with the `IndexOutOfRangeException`. What I'm thinking is that the third bindable is actually the original bindable, and that couldn't be caught both in `removeAt` because that only checks one level …

Fix bindable list/dictionary not correctly checking for already bound instances

---

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
osu.Framework/Graphics/Containers/TextChunk.cs
osu.Framework/Graphics/Containers/TextFlowContainer.cs

Fix emphasised markdown text not flowing correctly

---

osu.Framework.Tests/Visual/Platform/TestSceneRaiseWindow.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2DesktopWindow.cs

Use case is raising the primary window when opening files/links via IPC (non-primary instance passing arguments to the primary), see https://github.com/ppy/osu/issues/22519.
Only implemented on desktop platforms. Raising a window is not a thing on mobile platforms, the OS has full control there (on Android we set `LaunchMode.SingleInstance` so every intent is passed to the same instance).
The tests are finicky on windows, as windows doesn't allow a window to raise/focus itself and will instead flash the taskbar button orange. If the window is minimised beforehand, there is a much better chance of the raise working.
For the use case described above, the raise always works. Windows probably does some heuristics to figure out if this is a "valid" raise request, and doing IPC like this is a …

Add a way to raise the window

---

osu.Framework.Tests/Visual/Platform/TestSceneWindowed.cs
osu.Framework/Extensions/OSPlatformExtensions.cs
osu.Framework/Testing/TestBrowser.cs

- Alternative to https://github.com/ppy/osu-framework/pull/5641
This allows test classes to be marked with `SupportedOSPlatform` and `UnsupportedOSPlatform` to specify on which platforms the tests should be visible in the test browser.
This is [supposed to work](https://github.com/nunit/nunit/issues/3866) for automated nunit tests, but doesn't currently.

Add a way to hide visual tests by using ``(Un)SupportedOSPlatformAttribute``

---

osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Noticed in #5647. Pipeline descriptions contain array fields, which are stored by reference. Modifying those arrays affect stored lookup keys in the cache dictionary, therefore cloning for the arrays are required before storing the description as a lookup key.
This resolves the first issue mentioned in https://github.com/ppy/osu-framework/pull/5647#issuecomment-1421562057.

Fix veldrid pipeline caching not working properly

---

osu.Framework/Graphics/UserInterface/DirectorySelector.cs

Ran into this while tapping around visual tests on iOS. `TestSceneFileSelector` would result in a startup crash due to the call to `DriveInfo.GetDrives()` throwing an AOT failure exception.

Fix potential crash when displaying `DirectorySelector` on AOT platforms

---

osu.Framework.iOS.props

Noticed while trying to figure out a good diff for local framework reference on `osu.iOS` solution.

Fix `osu.Framework.iOS.props` overwriting previous warning exclusions

---

osu.Framework.Tests/Bindables/BindableColour4Test.cs
osu.Framework/Bindables/BindableColour4.cs
osu.Framework/Configuration/ConfigManager.cs

For osu!-side config stuff.
Serialization uses hex codes to make it easier for users to edit. This sacrifices precision but I assume that's okay given that `BindableFloat`/`BindableDouble` serialize with a limited number of significant figures.

Add BindableColour4

---

SampleGame.Android/AndroidManifest.xml
osu.Framework.Tests.Android/AndroidManifest.xml
osu.Framework.Tests/Visual/Platform/TestSceneExternalLinks.cs

- Framework side of https://github.com/ppy/osu/pull/22790

Fix external links not working on Android

---

osu.Framework.Benchmarks/BenchmarkQuad.cs
osu.Framework.Tests/Primitives/QuadTest.cs
osu.Framework/Graphics/Primitives/Quad.cs

Closes #5669.
I will pre-empt this by saying that I am only *mostly* confident of this fix, so please be on the look-out if you don't like anything here. It took me the better part of an hour to convince myself that this works due to reasons I will elaborate on below.
To the point: In order to avoid the issue demonstrated by the test in #5668, a different way of computing whether a given point is inside of the quad is used. Namely, this method uses the perpendicular dot product, which has the property of
$$ \textbf{a}^\perp \cdot \textbf{b} = |\textbf{a}| |\textbf{b}| \sin \theta $$
wherein $\theta$ is the angle between the vectors $\textbf{a}$ and $\textbf{b}$.[^1] In particular, this means that because the sine of an angle is positive in the range [0, 180deg], and negative in the range …

Fix `Quad.Contains` sometimes failing due to floating point precision issues

---

osu.Framework.Tests/Localisation/LocalisationTest.cs
osu.Framework.Tests/Text/TextBuilderTest.cs

These have been causing warnings on android CI for a while now that we've just been ignoring. I'd consider looking into why they are only failing there, but to be honest it doesn't really make much sense to reference private methods in the first place like this, so let's just remove them and call it a day.
See https://github.com/ppy/osu-framework/actions/runs/4383176901 for an example.

Remove xmldoc references to private methods

---

osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs

Fixes https://github.com/ppy/osu-framework/issues/5674
When setting `Data`, if the value is `default(T)` then the equality comparer will exit early. But it turns out that macOS (maybe M1 specific) needs the call to `GL.BufferData()` to initialise the buffer's memory.
I don't know if this will also affect the Veldrid implementation, since we can't currently run that with OpenGL on macOS.

Fix UBOs not being initialised when data is default

---

osu.Framework.Tests/Primitives/QuadTest.cs
osu.Framework/Graphics/Primitives/Quad.cs

As reported [on discord](https://discord.com/channels/188630481301012481/188630652340404224/1085495571202183208). Regressed in #5670.
Test coverage added to cover this case and a few others that did not end up needing targeted fixes; the fix pretty much targets the zero-sized case directly.
|   Method | NumPoints |        Mean |      Error |     StdDev | Allocated |
|--------- |---------- |------------:|-----------:|-----------:|----------:|
| Contains |        10 |    64.12 ns |   1.296 ns |   2.056 ns |         - |
| Contains |       100 |   580.51 ns |  11.631 ns |  20.674 ns |         - |
| Contains |      1000 | 5,989.39 ns | 118.540 ns | 188.017 ns |         - |
|   Method | NumPoints |        Mean |     Error |     StdDev | Allocated |
|--------- |---------- …

Fix `Quad.Contains()` failing for zero-sized drawables

---

osu.Framework/Graphics/Rendering/Renderer.cs

Noticed this when working on some unrelated changes. Because this is not reset, a subsequent call to `setMaskingInfo` exits early on the precondition:
https://github.com/ppy/osu-framework/blob/b87b7545ee89a073a244635e1b39ad4d3e6ba75d/osu.Framework/Graphics/Rendering/Renderer.cs#L609-L614

Fix masking info not reset on new frame

---

osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

I noticed this when entering and exiting song select, which would retain about 100MB VRAM every time.
Unlike with GL, resizing Veldrid FBOs requires them to be recreated. This PR is a three part fix:
- It was recreating them but not disposing the old ones. 
- It was not disposing the depth texture, which would likely have exacerbated this issue during gameplay (sliders).
- It was not rebinding the FBO upon such recreation. ~~I'm still evaluating whether this was the cause of other brokenness I was seeing.~~ (it is not)
The changes are hard to read since this is practically a total refactoring of the flow of this class.

Fix Veldrid framebuffers leaking GPU memory

---

.github/workflows/ci.yml

Successful run: https://github.com/Susko3/osu-framework/actions/runs/4472707773/jobs/7859184672
The same tactic is used in [`osu`](https://github.com/ppy/osu/blob/88700c85fd22a74750fcdac223b661c7774e22f9/.github/workflows/ci.yml#L117) repo.

Fix Android CI workload

---

osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Threading/DrawThread.cs

- Closes #5688 
I'll preface this by saying this only affects Veldrid/OpenGL, so this doesn't need immediate attention at all and can be left for another release if preferred.
`MakeCurrent` calls are supposed to happen internally within the renderer whenever it's expecting to execute GL commands. In Veldrid, all GL commands are executed in a separate thread, therefore calling `MakeCurrent` here is unnecessary and will fail due to being acquired in the Veldrid thread.
I've kept the `ClearCurrent` call though since I'm not entirely sure of a better place for it that exists on `GLRenderer`, and I'm slightly skeptical of doing it in `FinishFrame`.

Fix draw thread unnecessarily marking GL context as current

---

osu.Framework.Tests/Visual/Platform/TestSceneRenderer.cs
osu.Framework.iOS/IOSGameHost.cs
osu.Framework/Configuration/FrameworkConfigManager.cs
osu.Framework/Configuration/Renderer.cs
osu.Framework/Configuration/RendererType.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/HeadlessGameHost.cs
osu.Framework/Platform/OsuTKGameHost.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs

RFC
The goal here is to provide both renderer fallback logic, but also expose the renderer to the user in a way they can interact with it from game settings (or via config file for recovery, should that ever be required).
Example with user set configuration that is invalid:
```csharp
[runtime] 2023-03-16 10:45:09 [verbose]: 🖼 Configuration renderer choice: Vulkan
[runtime] 2023-03-16 10:45:09 [verbose]: 🖼️ Renderer fallback order: [ Vulkan, Metal, OpenGLLegacy ]
[runtime] 2023-03-16 10:45:09 [verbose]: 🖼️ Attempting initialisation using renderer: veldrid surface: Vulkan
[runtime] 2023-03-16 10:45:09 [verbose]: Updated display mode to desktop resolution: 2560x1440@144, SDL_PIXELFORMAT_ARGB8888
[runtime] 2023-03-16 10:45:09 [verbose]: 🖼️ Renderer initialisation failed with:
[runtime] …
```

Allow renderer choice to be stored in user configuration (and add automatic fallbacks)

---

osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs

I noticed that every once in a while certain vertices would get incorrect data.
Furthermore this would always occur on vertices that were 0-initialised, which is _always_ the case with exactly one vertex in FBOs since the FtB pass doesn't do anything there (depth = 0). That explains why the issues I was seeing was always when `BufferedContainer` + blur were involved (e.g. backgrounds, in-gameplay break overlay arrows, song select leaderboard glows).
This makes it so that we always perform one buffer update with 0-initialised data when initialising a VBO. In `GLRenderer` we are relying on `glBufferData` to both initialise the storage for us _and_ clean out the driver/GPU buffer, so this was just missed in the port to Veldrid.

Fix D3D VBOs sometimes initialised with junk data

---

osu.Framework/Graphics/Sprites/SpriteText.cs

I'm very deep into debugging D3D right now and noticed this coming up potentially causing unnecessary & invalid vertex uploads.

Fix possible division by 0 in SpriteText

---

osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBuffer.cs

This doesn't fix any issue, it's just a preventative measure that is mostly the same implementation as `VeldridVertexBuffer`.

Add a finaliser to Veldrid UBOs

---

osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
osu.Framework/Graphics/Rendering/IUniformBuffer.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridLinearBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridQuadBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBufferStorage.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Statistics/FrameStatistics.cs
osu.Framework/Threading/DrawThread.cs

Veldrid's `CommandList` corresponds to a [`MTLCommandBuffer`](https://developer.apple.com/documentation/metal/mtlcommandbuffer) in Metal.
To write to a `MTLCommandBuffer`, you use command encoders. There are two particular encoders which are relevant for us:
1. A [`MTLRenderCommandEncoder`](https://developer.apple.com/documentation/metal/mtlrendercommandencoder) which allows us to render things - set viewports, call `DrawIndexed`, etc.
2. A [`MTLBlitCommandEncoder`](https://developer.apple.com/documentation/metal/mtlblitcommandencoder), which, for our purposes, allows us to upload data into VBOs/UBOs.
By interleaving VBO/UBO updates, we are essentially pausing and resuming the render pass, which is causing a huge amount (~9GB/frame at song select) of GPU memory traffic at song select. The …

Fix Metal performance with a separate command list for buffer updates

---

osu.Framework/Graphics/BufferedDrawNode.cs
osu.Framework/Graphics/Sprites/BufferedContainerView.cs
osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
osu.Framework/Graphics/TexturedShaderDrawNode.cs
osu.Framework/Graphics/UserInterface/CircularBlob.cs
osu.Framework/Graphics/UserInterface/CircularProgress.cs
osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
osu.Framework/Graphics/Video/VideoSpriteDrawNode.cs

This caused Metal to crash when loading a colour picker, due to the UBO not being bound in the front-to-back pass. Rather than duplicating code there, I've refactored the API to force UBOs to always be bound whenever the `DrawNode` wishes to bind the shader.
`DrawNode`s that bind other shaders will have to manually bind UBOs themselves. One alternative direction I had was to completely mark `IShader.Bind/Unbind` internal and re-define the methods in `DrawNode` instead, along with logic to store uniform blocks in the shader in order to be bound on `DrawNode.BindShader`.
This is partially done to force consumers into binding uniform blocks in the newly defined `TexturedShaderDrawNode.BindUniformResources` method, such that uniform blocks are always bound whenever the corresponding shader is …

Fix local uniform buffers not always bound on draw

---

osu.Framework.iOS.props

This makes iOS development less PITA in multiple ways:
- Works around https://github.com/xamarin/xamarin-macios/issues/17708 which is encountered very frequently during work sessions.
- Fixes SDL P/Invokes oddly throwing `DllNotFoundException` despite a resolver already being attached.
- Decreases build time immensely.

Enable Mono Interpreter on iOS

---

osu.Framework/Graphics/OpenGL/GLRenderer.cs

See https://github.com/ppy/osu-framework/issues/5694.
Not closing the issue because I don't see this as a permanent fix. That said, maybe it won't be required if we switch to veldrid GL and it works there? Not even testing that at this point because I just want to ensure we can get the next release out on android without everything toppling over.
Tested on my only test device to work as expected.

Add workaround for incorrect SRGB conversion inside `BufferedContainer`s on android

---

osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj.DotSettings
osu.Framework.Tests.iOS/osu.Framework.Tests.iOS.csproj.DotSettings

Fixes:
Caused by files being included from a directory which causes namespace checks to fail.

Fix namespace warnings in iOS / android test projects

---

osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
osu.Framework/Graphics/OpenGL/Buffers/GLFrameBuffer.cs
osu.Framework/Graphics/Rendering/GlobalUniformData.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
osu.Framework/Resources/Shaders/Internal/sh_GlobalUniforms.h
osu.Framework/Resources/Shaders/Internal/sh_Vertex_Output.h

Fixes https://github.com/ppy/osu-framework/issues/5701
The core of the issue is that in OpenGL textures are inverted with the bottom-left texel being (0,0). Historically, we've always been rendering to FBOs such that their output is stored as if the top-left texel was (0,0), and then we had some logic to invert the FBO's texture when it was used for drawing.
So this is a two part fix:
1. Making FBOs rendered to as expected by the surface. For OpenGL if you view them in RenderDoc, they'll now be inverted. This makes all surfaces render the same way.
2. Removing the custom inversion logic for the blur direction. This only existed because the DrawNode assumed our incorrect rendering of FBOs. This makes the blur direction clockwise once again as expected.
@bdach Please double check that this …

Fix blur direction changing between renderer surfaces

---

.github/workflows/deploy-pack.yml

In theory, this should deal with #5695.
Admittedly I haven't tested this end-to-end because it's a little tedious to do so (would have to change default branch on my fork to use these changes, add a secret to push to nuget, change the package IDs around, tag, trigger the workflow...) But, if the docs [from nuget](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#creating-a-symbol-package) and the [`upload-artifact` action](https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions) are to be trusted, this _should_ work? I can go and do the full flow test described above if that is considered a requirement.
Note that I haven't changed the final push command, because [docs claim the symbols package should be automatically …

Build debug symbol packages in deploy workflow

---

SampleGame.Android/AndroidManifest.xml
osu.Framework.Android/AndroidGameHost.cs
osu.Framework.Tests.Android/AndroidManifest.xml
osu.Framework.Tests/Visual/Platform/TestSceneExternalLinks.cs

- Closes https://github.com/ppy/osu/issues/22993
- Alternative to https://github.com/ppy/osu/pull/23005
- Somewhat reverts #5666 
This PR follows the [guidelines](https://developer.android.com/training/package-visibility/use-cases#open-urls-browser-or-other-app) for apps targeting Android 11+.
The links added in the tests only fail if they are opened in their respective app (not the default web browser).
- https://github.com/ppy/osu/pull/22790 should be reverted after this is merged

Fix opening external links on Android

---

osu.Framework.Android/AndroidGameWindow.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2Window.cs
osu.Framework/Platform/SDL2Window_Windowing.cs

The property being bindable had mostly no use, as generally the list of supported modes will not change while the game is running, so there is no benefit to having it bindable.
Consumers that are broken by this change (due to using the property in bindable flow) can safely enumerate `SupportedWindowModes` at initialisation time without having to worry about the returned set of modes ever changing during game operation.

Change `SupportedWindowModes` to non-bindable

---

osu.Framework.Tests/Primitives/QuadTest.cs
osu.Framework/Graphics/Primitives/Quad.cs

Closes https://github.com/ppy/osu/issues/23042
Hopefully the last one of these... I'll let the diff do most of the talking here, as I added a huge explanatory inline comment to attempt to explain what is going on in the new implementation. Scrutiny is however both warranted and welcome.
|   Method | NumPoints |        Mean |     Error |    StdDev | Allocated |
|--------- |---------- |------------:|----------:|----------:|----------:|
| Contains |        10 |    72.03 ns |  1.437 ns |  2.479 ns |         - |
| Contains |       100 |   661.56 ns |  9.191 ns |  8.147 ns |         - |
| Contains |      1000 | 6,723.38 ns | 33.804 ns | 28.228 ns |         - |
|   Method | NumPoints |        Mean |      Error |     StdDev | Allocated |
|--------- |---------- …

Fix `Quad.Contains()` not working with clockwise-oriented quads

---

osu.Framework/Platform/SDL2Window.cs

wl_shell_surface is a part of wl_shell, which is a deprecated protocol and isn't supported by the majority of compositors today
I'm not sure why commit 37a3331473d37c9c895df746d94f379b28f90008 made this mistake (maybe SDL2 documentation wasn't clear about wl_shell?)
This mistake wasn't really relevant until recently, when Veldrid renderer started using this variable for creating a Wayland surface on Vulkan (which was always empty and so ended up crashing Mesa's Wayland Vulkan WSI code when creating a swapchain)
This change fixes Vulkan renderer crashes when SDL is using the Wayland video driver (I personally tested this on a debug build of osu! and it works)

Fix Veldrid failing to initialise on Wayland

---

osu.Framework.iOS/GameApplication.cs

I'm 99.9% sure we don't need this anymore. Originally added in https://github.com/ppy/osu-framework/pull/1409.

Remove iOS imagesharp AOT workaround

---

osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Platform/GameHost.cs

- Closes https://github.com/ppy/osu/issues/22978
I didn't intend on spending much time on this one, but I realised the cause was too simple that it's better to fix as a fallback rather than leaving it broken for later.
Interestingly, the [`Path` rendering issue](https://github.com/ppy/osu/issues/23003) doesn't actually occur with Veldrid OpenGL, so the cause of that one may very well lie within the `GLRenderer` implementation (potentially a specific GL call that isn't supported on iOS).

Fix Veldrid OpenGL not working on iOS and bring back as valid

---

osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/osu.Framework.csproj

- Closes https://github.com/ppy/osu/issues/22959
As per the issue thread, this follows a simple approach of reading backbuffer pixels by copying the swapchain texture to a staging buffer and mapping it for CPU read.
Tested to work on OpenGL, D3D11, and Metal. Vulkan may require further changes against Veldrid according to [an old PR that's achieving similar to what my PRs above achieve](https://github.com/mellinoe/veldrid/pull/363).

Add Veldrid screenshot support

---

osu.Framework/osu.Framework.csproj

See https://github.com/ppy/veldrid/commit/0ec05acb9b7ed04649f57ef979548bcfb5797694 (diff applied from discord discussion).

Update veldrid again to fix direct x crash

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Should resolve https://github.com/ppy/osu/issues/23088, can't test it right now.
When `setSwapchainFramebuffer` is non-null, Veldrid will always use it without falling back to `glBindFramebuffer(0)`. Therefore we should fall back to binding to framebuffer 0 ourselves rather than returning without binding anything.

Fix non-legacy OpenGL sometimes flickering/freezing

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Fixes https://github.com/ppy/osu/issues/22970
It's not the most that can be done, because Veldrid doesn't expose interfaces to do this sort of alignment, and although it seems possible in at least D3D, it's something I don't want to do unless absolutely necessary. This is already between 1-2 magnitudes faster for me, just in this one block nevermind GL execution time which is hard to profile.
I want confirmation that this fixes the issue before merge, though.
Also would be good to test this on mobile platforms.

Improve performance of video texture uploads

---

osu.Framework/Resources/Shaders/sh_Masking.h

Computing the border colour is a bit of an expensive operation, and on vertices with a high number of fragments, could lead to a reduction in performance.
When the "colour weight" is equal to one, the border colour is completely ignored. So I've let it early-return with the texel colour before computing the border colour if so. I've also renamed the locals to better describe them rather than the generic `dest`/`src` names. 
Profiling on Metal with Xcode's instrument tools shows ~25% gain, as can be seen below:
|--------|-------|
| ![CleanShot 2023-04-08 at 08 58 46](https://user-images.githubusercontent.com/22781491/230706220-82d6b213-dddc-484e-a071-cf88448c0156.png) | ![CleanShot 2023-04-08 at 08 54 59](https://user-images.githubusercontent.com/22781491/230706229-82349d …

Improve texture shader performance on fragments away from corners

---

osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs

This only came up due to further performance investigations that attempt to fill VBOs instead, which requires non-zero `startIndex`. The value is pinned to zero in all current use cases, so this doesn't have any immediate effects.

Fix incorrect VBO start index

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Noticed on passing. Doesn't have any effect since such textures are uploaded on `BeginFrame` before any render passes begin, but it's still better to do this now in case the method is consumed in the middle of a render pass (potentially breaking rendering once we stick to one render pass per framebuffer in a single frame).

Use blit command queue for copying video textures on Veldrid

---

osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridVideoTexture.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Avoid enumerable/enumerator allocation when fetching texture resources on Veldrid

---

osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs

- Alternative to / closes #5740 
On Metal, encoding a buffer copy command comes with an overhead, and that overhead becomes noticeable on frequently updated buffers (aka "dynamic").
Since we update our vertex buffers pretty much every single frame, it's wiser to update them directly from the CPU rather than encoding a copy command every time.
In addition, since we're updating vertex buffers directly from the CPU, we must ensure it shouldn't be read from the GPU. Simple triple-buffering logic should help with that, but note that it increases the memory usage to triple times its original size in return (maybe double-buffering is better?).
If the memory usage here turns out to have taken a bad turn, then this PR can be ignored for the time being (potentially wait for …

Upload Veldrid VBOs directly rather than using a command list

---

osu.Framework/Graphics/BufferedDrawNode.cs
osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
osu.Framework/Graphics/DrawNode.cs
osu.Framework/Graphics/OpenGL/Buffers/GLFrameBuffer.cs
osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/Rendering/Dummy/DummyFrameBuffer.cs
osu.Framework/Graphics/Rendering/IFrameBuffer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Platform/GameHost.cs

I'll preface this by mentioning that I don't seem to notice that much of a gain on my phone, but I'm PR'ing this anyway as it saves GPU memory bandwidth according to Xcode.
Until now, we've always been switching between framebuffers in the middle of a render pass, which was pretty much fine with OpenGL. But with Metal, switching a framebuffer requires ending the current render pass and beginning a new one, therefore unnecessarily increasing the number of render passes in a frame, potentially along with the bandwidth of loading and storing framebuffer attachments from/to tile memory.
This PR moves away any logic that involves binding a framebuffer to a separate pass that occurs before the main render pass, and enables using ["memoryless" storage …

Move FBO content population to a separate pass and enable "memoryless" storage mode on Metal

---

osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
osu.Framework.Tests/Shaders/TestShaderLoading.cs
osu.Framework/Graphics/OpenGL/Shaders/GLShaderPart.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Shaders/IShaderStore.cs
osu.Framework/Graphics/Shaders/ShaderManager.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs

Alternative to https://github.com/ppy/osu-framework/pull/5739
This aims to resolve three issues:
1. Separation - when a ruleset only contains one part and references an o!f shader part lookup (e.g. the `Texture2D` vertex shader).
* This resolves the same issue as the PR above.
2. Fallback - If a ruleset doesn't contain the requested shader (e.g. every sprite requesting `Texture2D/Texture`).
* This removes the hack added in https://github.com/ppy/osu/pull/23111 .
3. Isolation - If two rulesets define and request shaders with the same name.
* This will both help out in the future with multi-spectator, and prevent rulesets polluting the global `ShaderManager` that could lead to weird behaviour. The above PR didn't achieve this.

Add multi-stage ShaderManager caching

---

osu.Framework.iOS/runtimes/ios/native/veldrid-spirv.xcframework/ios-arm64/veldrid-spirv.framework/Info.plist

- Resolves ppy/osu#23198
Recompiled on same branch but with a lower deployment target (13.4) in order to resolve https://github.com/ppy/osu/issues/23198. I've tried updating the simulator version as well but that didn't work for odd reason, so I've kept it as-is.

Update `veldrid-spirv` native library with lower iOS deployment target

---

osu.Framework/Platform/Windows/Native/Input.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

- Closes ppy/osu#23144
This PR simply disables touch feedback in the window using [`SetWindowFeedbackSetting`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowfeedbacksetting). This will disable feedback for touches that start in the window. Pen and gesture feedback is also disabled for good measure.
Since we draw our own cursor (and cursor trails in osu!), having this disabled (in all window modes and renderers) is desirable.
The [docs](https://learn.microsoft.com/en-us/windows/win32/input_feedback/input-feedback-configuration-portal) mention our use case:
> For example, default visual feedback settings might not be necessary, or desirable, in a game app because of interference or conflicts with the gameplay itself.

Fix touch feedback breaking Direct3D 11 exclusive/optimised fullscreen

---

osu.Framework/Graphics/Visualisation/Audio/AudioMixerVisualiser.cs

Noticed this in passing, seems to have been caused by the changes to `ToolWindow` in #5254.
Before:
After:
.

Fix broken `AudioMixerVisualiser` layout

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

- Closes https://github.com/ppy/osu/issues/23311
Similar to https://github.com/ppy/osu-framework/pull/5750, mipmap levels sizes are not up-rounded when divided by 2. Doing so results in the texture potentially accessing a non-existent mipmap level due to incorrect size calculations (say 11x11 for example, up-rounded division results in 5 mipmap levels, while normal divsion results in 4 levels).

Fix texture mipmap sizes not calculated correctly

---

osu.Framework/Utils/Interpolation.cs

This is only intended to remove the reflection from the ctor, both to reduce memory footprint but also to be more AOT-friendly. There appears to be no difference in performance.
Before:
|                   Method |      Mean |     Error |    StdDev | Allocated |
|------------------------- |----------:|----------:|----------:|----------:|
| InterpolateMarginPadding | 45.014 ns | 0.6000 ns | 0.5612 ns |         - |
|  InterpolateFloatGeneric |  8.282 ns | 0.1558 ns | 0.1382 ns |         - |
|         InterpolateFloat |  8.319 ns | 0.1909 ns | 0.2344 ns |         - |
After:
|                   Method |      Mean |     Error |    StdDev | Allocated |
|------------------------- |----------:|----------:|----------:|----------:|
| InterpolateMarginPadding | 45.721 ns | 0.3529 ns | 0.2947 ns | …

Remove reflection usage from `Interpolation` class

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Textures/TextureStore.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

- Temporarily fixes https://github.com/ppy/osu/issues/23249
- Temporarily fixes https://github.com/ppy/osu/issues/23240 (as tested by @Joehuu)
- Temporarily fixes https://github.com/ppy/osu/issues/23318 (as tested by @Joehuu)
- Could possibly end up temporarily fixing some of the following (can't tell since I can't reproduce in the first place):
- https://github.com/ppy/osu/issues/23285
As per [today's discussion in discord](https://discord.com/channels/188630481301012481/589331078574112768/1101851147570004030), this disables the meaningful changes made in #5508 to restore operation on configurations that have been negatively affected by the change (primarily appears to be mobile).
This is not a direct revert, and the goal was to keep the mipmap generation code in the tree, just in a …

Disable manual mipmap generation (and decrease atlas size again)

---

osu.Framework/Graphics/Cursor/CursorContainer.cs

See discussion at https://github.com/ppy/osu/pull/23394#issuecomment-1534999637

Move `ActiveCursor` initial population to ctor to allow safe non-null specification

---

osu.Framework/osu.Framework.csproj

Inclues https://github.com/ppy/veldrid-spirv/pull/1.

Update veldrid SPIRV with fix for older macOS versions

---

osu.Framework/Platform/Linux/LinuxGameHost.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs

There are still edge cases on Linux where relative-mode isn't working correctly. One example is my NoMachine setup, which grabs the cursor but pins it to `(windowWidth, windowHeight)`.
The change to `Default` is intentional (for macOS also), otherwise the in-game options will show a non-default setting for the default value on these platforms.

Disable relative-mode mouse by default on Linux

---

osu.Framework.Templates/README.md

for a pull request involving osu-framework and dotnet.
This is a very small tiny pull request. 
I ran the command as per the instruction to install the templates in the readme.md file and it gave me a warning because --install (which -i is the short for) is deprecated. 
[Learn more here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new#description)

updating the dotnet command because -i is deprecated.

---

osu.Framework/Threading/AudioThread.cs

It's not the end of the world, but we're definitely querying too often.

Reduce overhead induced by checking Bass CPU usage

---

osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs

As seen by @smoogipoo 
I can't repro on macOS but this should be a pretty low-risk change, and especially important since this is called at least once per frame for opengl renderers:
https://cdn.discordapp.com/attachments/589331078574112768/1106511624686288946/image.png

Cache value of `VerticalSync` to avoid overhead retrieving from SDL2 each time

---

osu.Framework/Graphics/Veldrid/Batches/VeldridLinearBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridQuadBatch.cs
osu.Framework/Graphics/Veldrid/Buffers/Staging/IStagingBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/Staging/ManagedStagingBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Resolves https://github.com/ppy/osu-framework/issues/5779
I've encapsulated the relevant logic in an `IStagingBuffer<T>`.
- Persistently-mapped buffers appear to work out-of-the-box on D3D11 and Vulkan, but not on OpenGL.
- Persistently-mapped buffers _may_ also work on MTL, either by grabbing the contained `IntPtr` of the device buffer and using the more optimal `renderer.Device.UpdateBuffer()`, _or_ by the way the class already works. This needs more testing, and I've chosen to not change MTL's behaviour here.
- Therefore, managed buffers are used for MTL, OpenGL, and OpenGL ES. There should be no behavioural changes on those platforms.
Tested:

Fix D3D11 losing performance by constantly mapping/unmapping buffers

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

- Closes https://github.com/ppy/osu/issues/23466
- Closes https://github.com/ppy/osu/issues/23491
- Fixes https://github.com/ppy/osu/discussions/23503
There's not going to be much of an explanation in this one. The goal is to revert to a known-working state. I don't know why the old code would fail in the ways it did.
Part of it seems to be that initialising mip levels via framebuffers was deeply wrong somehow. The `glClear()` calls could lead to mip levels getting nuked (as in, cleared to transparent black) at some indeterminate point. If all of them got cleared, then there is no visual output. If only some of them got cleared, minimising a texture causes it to disappear (hilarious). If the mip level got cleared *during an upload of the zero level of a mipped atlas*, then some characters …

Revert changes to texture upload from manual mipmap generation pull

---

osu.Framework/Input/Bindings/KeyBindingContainer.cs

See discussion at https://github.com/ppy/osu-framework/pull/5793.
Inline comment already mentioned this.
Looks like we can remove this after switching to .NET 7 (https://github.com/dotnet/roslyn/issues/5835#issuecomment-1055790728). Heap allocations viewer plugin doesn't show this as an allocation already, for best or worst.

Revert method group change in hot path

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs

This reverts changes from https://github.com/ppy/osu-framework/pull/5516, but also removed one extra `Scheduler.AddOnce` ensuring that `Items_Get` returns the same result as `Items_Set` in all cases.
Resolves performance concerns cited at https://github.com/ppy/osu-framework/pull/5516/files#r1042047938
Closes https://github.com/ppy/osu/issues/22573
Closes https://github.com/ppy/osu/issues/23537
I've tried to come up with a better approach but have not been able to yet. Let's restore sanity first and foremost.

Revert `Schedule` changes to `Dropdown`

---

osu.Framework.Tests/Bindables/BindableListTest.cs
osu.Framework/Bindables/BindableList.cs

`ReplaceRange(index, count, newItems)` equivalent to remove + insert but as an atomic operation.
- Together with an osu-side change, to be used instead of https://github.com/ppy/osu/pull/23572

Add `BindableList.ReplaceRange` as an atomic operation

---

osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
osu.Framework/Graphics/Performance/PerformanceOverlay.cs

A result of smoogi not being able to tell which frame limiter is applied on high refresh monitors (where they all become 1000 Hz). Obviously this is a fault of the frame limiters, but fixing that is for another day.
I've also unapplied fixed width font display on the fps details since roboto is already fixed width for numbers. This improves the kerning of the non-numeric text.
| -- | -- |
|![osu Framework Tests 2023-05-18 at 07 48 02](https://github.com/ppy/osu-framework/assets/191335/a488fed9-9af9-4d4b-85f3-8613cb32cc04)|![osu Framework Tests 2023-05-18 at 07 47 05](https://github.com/ppy/osu-framework/assets/191335/23d3ad5d-a974-4bbf-ba5e-5cc1575f8359)|

Show more information in frame statistic display

---

osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs

This fixes the graphical issues in https://github.com/ppy/osu/issues/23538
The conjecture here, going by documentation and testing, is that `Map()` blocks the GPU from accessing the resource, and `Unmap()` allows it to access it again.
Due to the undocumented nature of this entire endeavour, I'm going to spend the rest of this PR providing some documentation on my findings and testing.
A lot of this is diving into seemingly uncharted territory as I've been unable to find anyone else doing what we're doing here, and all suggestions lead to worse performance than these changes achieve. It seems like D3D is more tailored for 3D applications where VBOs are fully populated ahead of time and are very rarely if ever updated, or, when they are; users are okay with adding artificial delays in …

Unmap persistent buffers before uploading

---

osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/TemplateGame.Game.Tests.csproj
osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/FlappyDon.Game.Tests.csproj
osu.Framework.Tests/osu.Framework.Tests.csproj
osu.Framework/osu.Framework.csproj

Also bumps minor package versions because we can.
Incorporates https://github.com/libsdl-org/SDL/issues/6835, of note (but also thousands of other changes soo testing is probably best).
testing:

Update SDL native libraries

---

osu.Framework.Benchmarks/BenchmarkColourInfo.cs
osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
osu.Framework.Tests/Visual/Graphics/TestSceneColours.cs
osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs
osu.Framework/Graphics/Colour4.cs

During profiling of watching autoplay, `Color4Extensions.ToLinear` appears to be the hottest function, with above 2% sampled count:
When I first tried to use `MathF.Pow` instead of `Math.Pow`, the performance surprisingly regressed. Further investigation shows that when input `x` is 1, `Math.Pow` appears to use a shortcut while `MathF.Pow` doesn't. Breaking shows that about half of the calls are called with white color (R,G,B=1), it should be worth adding a short path for it.
I also added more colours to BenchmarkColourInfo to show the difference of colours.
<details>
|                    Method |  Runtime |               Colour |       Mean |     Error |    StdDev | Ratio | RatioSD | Allocated | Alloc Ratio |
|-------------------------- |--------- |--------------------- …

Use float for color space conversion

---

osu.Framework/Graphics/Performance/FrameTimeDisplay.cs

After https://github.com/ppy/osu-framework/pull/5801/commits/c0979e9331bb4ab28f9db1fff1f72b223b764bc8, osu!-side FPS display went all weird as it was preferring an osu-provided font which does not support fixed-width display:
We are already forcing the font choice almost everywhere else in this display, so let's call this an oversight.

Force `FrameTimeDisplay` font choice to framework font

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

This was triggering on every texture *bind* operation. Oops.
Loading song select (from an already warmed up glyph cache):
| -- | -- |
|![JetBrains Rider 2023-05-24 at 04 01 46](https://github.com/ppy/osu-framework/assets/191335/b0255f16-0d1f-48c5-bc5c-e0a1b006430a) |![JetBrains Rider 2023-05-24 at 04 03 47](https://github.com/ppy/osu-framework/assets/191335/babbffb5-2ce3-4948-b489-8e03f561dfd8)|

Avoid creating new `List<RectangleI>` when no texture uploads are required

---

osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Platform/HeadlessGameHost.cs

A significant amount of time is spent in tests on the `CompileGlslToSpirv()` method. It's quite hard to resolve because shaders are in stores, so it's not as simple as making things `static` unless by name-pairs which brings with it potential other side effects.
`HeadlessGameHost` does not draw anyway, so it doesn't sound like a stretch to use the `DummyRenderer`:
https://github.com/ppy/osu-framework/blob/5d72e48d64c98b483985f5b6a6888ad4c1dfbc33/osu.Framework/Platform/HeadlessGameHost.cs#L89-L92
(o!f UI tests) Before:
(o!f UI tests) After:
```
osu.Game.Tests `UserInterface` tests:
Before: 67s
After: 33.369s
```
```
osu.Game.Tests full:
Before: 14min
After: 8.5min
```

Use `DummyRenderer` in `HeadlessGameHost`

---

osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Resolves https://github.com/ppy/osu-framework/issues/5770 and hopefully makes this code a lot more readable as to why it's doing things the way it is.
UBOs no longer flush when data is set, and are now flushed as part of the draw call. Considering the sequence of events:
```
1. VBO.Add(...)
2. UBO.Data = ...
3. VBO.Add(...)
4. UBO.Data = ...
5. VBO.Draw()
```
- Previously: Vertex 1 uses data 2, vertex 3 uses data 4.
- Now: Both vertices use data 4.
The global uniform buffer, which persists through multiple `DrawNode`s and needs special flush handling, is already covered by flushes in the various Renderer state change methods.
As a bonus, this removes the equality comparer from `Data_set()` which could _slightly_ improve performance where it's called multiple times before actually being …

Simplify UBO uploads

---

osu-framework.sln.DotSettings
osu.Framework.Tests/Bindables/BindableEnumTest.cs
osu.Framework.Tests/Bindables/BindableTest.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/BindableBool.cs
osu.Framework/Bindables/BindableColour4.cs
osu.Framework/Bindables/BindableMarginPadding.cs
osu.Framework/Bindables/BindableSize.cs

Previously:
My particular use case is I want to set a realm setting to `null`, but we currently store and retrieve them from the database as non-nullable strings. Not that having them stored as `null` would help (see `TestParseNullIntoNullableValueType` failure above).
Store: https://github.com/ppy/osu/blob/ba5f76fcc8b7e926310f22a6c5fc63bae19897fb/osu.Game/Rulesets/Configuration/RulesetConfigManager.cs#L72 (i.e. `Bindable<T>.ToString()` which returns `string.Empty` for a `null` value).
Retrieve: https://github.com/ppy/osu/blob/ba5f76fcc8b7e926310f22a6c5fc63bae19897fb/osu.Game/Configuration/RealmRulesetSetting.cs#L20-L21.
In summary:
```
Bindable<int>.Parse(null)               => ArgumentNullException()
Bindable<int>.Parse(string.Empty)       => FormatException()
Bindable<int?>.Parse(null) …
```

Fix not being able to parse empty string into nullable bindable

---

osu.Framework/osu.Framework.csproj

No changes required from our end as we are already calling the relevant `Renderer.WaitUntilNextFrameReady()` function. Veldrid side, this is now supported on desktop metal platforms.
Closes https://github.com/ppy/osu-framework/pull/5803 (separate PR so we can keep that one around for potential reference – it contains iOS changes).
In the future, we can improve this further by implementing `CVDisplayLink` in `MacOSWindow`, in a very similar way to https://github.com/ppy/osu-framework/pull/5820. Once this is merged and all has settled, I'll open an issue to track that. The benefits would be that the timings are slightly more precise as we are not using a semaphore. Higher effort though, as we will need to figure a better solution for multi-threaded mode.

Update veldrid with macOS `CVDisplayLink` support

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/IOSWindow.cs
osu.Framework/Platform/SDL2Window.cs

Alternative to and closes https://github.com/ppy/osu-framework/pull/5803 (the iOS portion – the macOS part is still
valid but only requires a veldrid version bump).
Testing at 2x limiter, 120hz display (iPad Pro 2018), release build local framework
| Header      | menu (contracted) | menu (expanded) | song select |
|-------------|-------------------|-----------------|-------------|
| `master`    | 120fps                 | 70fps               | 28fps           |
| this PR     | 120fps            | 80fps           | 28fps       |
| `master` gl | 120fps                 | 70fps               | 27fps           | 
Not much difference, but that's because we're still doing way too much work in draw. The main thing I want to show is that nothing regressed. Once we have more overhead this is only …

Improve iOS/iPadOS frame timings by using `CADisplayLink`

---

osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
osu.Framework/Graphics/Containers/CompositeDrawable.cs

Although this should not have much of an effect on performance, it has behavioural effects with [`RequiresChildrenUpdate`](https://github.com/ppy/osu-framework/blob/4f51459744d1f2e97692696b4c38a557d7c6e827/osu.Framework/Graphics/Containers/CompositeDrawable.cs#LL903C59-L903C59), that could needlessly trigger `Update`s on children when their parents are masked away.

Reduce invalidations of `childrenSizeDependencies` in edge cases

---

osu.Framework/osu.Framework.csproj

- Addresses https://github.com/ppy/osu/discussions/23792#discussioncomment-6111778
```
2023-06-08 05:38:37 [verbose]: 🖼️ Initialising "Veldrid" renderer with "Metal" surface
2023-06-08 05:38:37 [verbose]: Updated display mode to desktop resolution: 844x390@60, SDL_PIXELFORMAT_ABGR8888
2023-06-08 05:38:37 [verbose]: 🖼️ Renderer initialisation failed with:
2023-06-08 05:38:37 [verbose]: System.EntryPointNotFoundException: createDisplayLinkProxy
2023-06-08 05:38:37 [verbose]: at Veldrid.MetalBindings.CADisplayLinkProxy.InitWithCallback(IntPtr callback)
2023-06-08 05:38:37 [verbose]: at Veldrid.MTL.MTLCADisplayLink..ctor()
2023-06-08 05:38:37 [verbose]: at Veldrid.MTL.MTLGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 swapchainDesc, MetalDeviceOptions metalOptions)
2023-06-08 …
```

Update Veldrid package to revert `CADisplayLink` implementation from veldrid-side

---

osu.Framework/Resources/Shaders/Internal/sh_Compatibility.h
osu.Framework/Resources/Shaders/Internal/sh_GlobalUniforms.h
osu.Framework/Resources/Shaders/Internal/sh_Vertex_Output.h
osu.Framework/Resources/Shaders/sh_Blur.fs
osu.Framework/Resources/Shaders/sh_Blur.vs
osu.Framework/Resources/Shaders/sh_CircularBlob.fs
osu.Framework/Resources/Shaders/sh_CircularBlobUtils.h
osu.Framework/Resources/Shaders/sh_CircularProgress.fs
osu.Framework/Resources/Shaders/sh_CircularProgressUtils.h
osu.Framework/Resources/Shaders/sh_HueSelectorBackground.fs
osu.Framework/Resources/Shaders/sh_Masking.h
osu.Framework/Resources/Shaders/sh_Particle.vs
osu.Framework/Resources/Shaders/sh_Position.vs
osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
osu.Framework/Resources/Shaders/sh_Texture.fs
osu.Framework/Resources/Shaders/sh_Texture2D.vs
osu.Framework/Resources/Shaders/sh_Texture3D.vs
osu.Framework/Resources/Shaders/sh_TextureWrapping.h
osu.Framework/Resources/Shaders/sh_Utils.h
osu.Framework/Resources/Shaders/sh_Video.fs
osu.Framework/Resources/Shaders/sh_mipmap.fs
osu.Framework/Resources/Shaders/sh_mipmap.vs
osu.Framework/Resources/Shaders/sh_yuv2rgb.h

This is [standard practice](https://en.wikipedia.org/wiki/Include_guard) in the C/C++ world.

Add include guards to all shaders

---

README.md

VS Code needs the C# plugin installed in-order to work with Dotnet projects. Additionally, the EditorConfig plugin needs to be installed to work on the project without 1000+ errors; Visual Studio 2019+ and Jetbrains Rider support EditorConfig by default, VS Code does not.

Update README.md to include VS Code plugin prerequisites

---

osu.Framework/Graphics/UserInterface/Dropdown.cs
osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
osu.Framework/Testing/TestBrowser.cs

This overload is hard to work with, as I would expect that calling `GenerateItemText()` on an existing dropdown item to be idempotent. (I've had this expectation in mind when trying to properly fix https://github.com/ppy/osu/pull/23858.)
Since this overload is `protected`, no one really used it (zero osu!-side usages). So I hope it would be fine to remove.
If you were using this, refactor your code to use `LocalisableString GenerateItemText(T value)` instead.
Easiest way is to add `LocalisableString? CustomDropdownText` to your `T`, or wrap `T` in a class that has one.
Then simply change `GenerateItemText()` to use that:
```cs
public partial class MyDropdown : Dropdown<T>
{
protected override LocalisableString GenerateItemText(T value)
=> value.CustomDropdownText ?? …
```

Remove `Dropdown.AddDropdownItem(text, value)` overload

---

UseLocalVeldrid.ps1
UseLocalVeldrid.sh

Add UseLocalVeldrid scripts

---

osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
osu.Framework.Tests/Shaders/TestShaderLoading.cs
osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
osu.Framework/Graphics/OpenGL/Shaders/GLShaderPart.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Shaders/ComputeProgramCompilation.cs
osu.Framework/Graphics/Shaders/ShaderCompilationStore.cs
osu.Framework/Graphics/Shaders/VertexFragmentShaderCompilation.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Platform/GameHost.cs

Shader compilation dominates our startup time, so they're now cached to disk (spirv + cross-compile + reflection) at `cache/shaders/`.
| Test | Before | After (cold) | After (hot) |
| --- | --- | --- | --- |
| framework | ![image](https://github.com/ppy/osu-framework/assets/1329837/56190029-52a1-4e33-bdd8-0f874289bd48) | ![image](https://github.com/ppy/osu-framework/assets/1329837/a5cf9d62-8223-40f1-a06d-be319481baa3) | ![image](https://github.com/ppy/osu-framework/assets/1329837/d2a15b93-b0d0-4e8f-90e8-5d6e23cdd6fe)
| osu | ![image](https://github.com/ppy/osu-framework/assets/1329837/7372ec28-8652-4c14-ae5f-aa60ecf26dc0) | ![image](https://github.com/ppy/osu-framework/assets/1329837/a4a87e2e-d973-427a-9802-cc54cf52e02f) | ![image](https://github.com/ppy/osu-framework/assets/1329837/28eb9c …

Add disk cache for shader compilations

---

osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
osu.Framework/Graphics/UserInterface/Popover.cs

Resolves https://github.com/ppy/osu-framework/issues/5621
Moves focus logic outside of `PopIn`/`PopOut` methods in `FocusedOverlayContainer`
Forces  non-abstract inheritors of `FocusedOverlayContainer` to correctly implement these methods.
Previously, subclasses of `FocusedOverlayContainer` were not forced to implement `Pop{In,Out}` themselves, despite actually needing to do so for the overlay to actually play transitions out correctly. This has now been changed and inheritors of the class must always implement `Pop{In,Out}`.
In practice this should not break any reasonable consumers of the class, except for the need to remove any `base.Pop{In,Out}()` calls in classes that directly inherit `FocusedOverlayContainer` and call base in `Pop{In,Out}()`.

Remove overrides of PopIn/PopOut in FocusedOverlayContainer

---

osu.Framework/FrameworkEnvironment.cs
osu.Framework/Graphics/Veldrid/Buffers/Staging/DeferredStagingBuffer.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

On occasion, I have noticed the new `PersistentStagingBuffer` causing graphics corruption. At least, I _think_ it's because of this type and its undefined nature (part of the reason why we now have an `Unmap()` inside the copy function).
As a result, I'm going back to buffers to figure out the most efficient update strategy. This implements a new `DeferredStagingBuffer`, which uses a managed CPU buffer and an intermediate driver-side `Staging` buffer, to do updates.
The new type is off by default, and is only accessible with an environment variable:
<table>
<tr>
<th>Name</th>
<th>Values</th>
</tr>
<tr>
<td>
`OSU_GRAPHICS_STAGING_BUFFER_TYPE`
</td>
<td>
`0` = `ManagedStagingBuffer`
`1` = `PersistentStagingBuffer`
`2` = `DeferredStagingBuffer`
</td>
<tr>
<table>
I'd like to test this new …

Add new `DeferredStagingBuffer` type

---

osu.Framework/Platform/GameHost.cs

Fix `WaitUntilNextFrameReady` not being accounted for as `Sleep` time

---

osu.Framework/Input/Handlers/Midi/MidiHandler.cs

MIDI is rarely used. On top of that, on macOS the overhead on first call to the `Devices` enum is very expensive (>1s). This shouldn't delay startup of the game.
Implementation is copied from `OpenTabletDriveHandler`, which should be quite reliable.

Move midi initialisation to a thread

---

osu.Framework.SourceGeneration/Analysers/DiagnosticRules.cs
osu.Framework.SourceGeneration/Analysers/DrawableAnalyser.cs

Current:
Expected:
No change in performance:
Before:
```sh
$ # Partial build
$ for i in {1..5}; do (touch osu.Framework/Game.cs && dotnet build osu-framework.Desktop.slnf -v:q) | tail -1; done
Time Elapsed 00:00:03.55
Time Elapsed 00:00:02.39
Time Elapsed 00:00:02.43
Time Elapsed 00:00:02.48
Time Elapsed 00:00:02.41
```
```sh
$ # Full rebuild
$ for i in {1..5}; do (dotnet clean osu-framework.Desktop.slnf -v:q && dotnet build osu-framework.Desktop.slnf -v:q) | tail -1; done
Time Elapsed 00:00:05.78
Time Elapsed 00:00:05.77
Time Elapsed 00:00:05.38
Time Elapsed 00:00:05.37
Time Elapsed 00:00:05.43
```
After:
```sh
$ # Partial build
$ for i in {1..5}; do (touch osu.Framework/Game.cs && dotnet build osu-framework.Desktop.slnf -v:q) | tail -1; done
Time Elapsed 00:00:03.29
Time Elapsed …
```

Fix nested DI candidates not analysed in non-candidate parent types

---

osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
osu.Framework/Graphics/Audio/WaveformGraph.cs

Closes https://github.com/ppy/osu/issues/23905
| -- | -- |
|![osu Framework Tests 2023-06-16 at 07 41 08](https://github.com/ppy/osu-framework/assets/191335/ca0a4310-a600-4e14-b55b-ded3a97841d6)|![osu Framework Tests 2023-06-16 at 07 40 21](https://github.com/ppy/osu-framework/assets/191335/acbb9fae-739f-4a27-bff5-fe1bdfa62d69)|

Fix performance when viewing the tail end of a long / zoomed-in waveform

---

osu.Framework/Platform/GameHost.cs

I noticed very long pauses when loading song select on my windows PC. Tracking this down, the game was getting stuck on the D3D11Swapchain [wait handle](https://github.com/ppy/veldrid/blob/d4340776eba0541aa3598856dafccf25633072f2/src/Veldrid/D3D11/D3D11Swapchain.cs#L303) until the full one second timeout.
It turns out that the wait handle will not be set unless a frame finishes rendering. The fail case is where the update thread takes over 100ms to prepare a frame, causing `TripleBuffer.GetForRead` to timeout and return `null`, which early exits the draw frame method.
This would happen anywhere the game takes slightly too long to render an update frame. I could reproduce:
- Entering song select
- Opening settings
- Opening beatmap listing
To confirm / reproduce this issue, remove the …

Ensure renderer-api-driven frame wait is only invoked when a frame is actually drawn

---

osu.Framework/Platform/GameHost.cs
osu.Framework/osu.Framework.csproj

Incorporating @ILW8's work (https://github.com/ppy/veldrid/pull/20) to more correctly provide hinting to metal as to where the window is running on the host, which allows better selection of refresh rates and display timings.
Tested on single display macbook and dual display mac pro (with two external displays). In these cases, I'm not noticing anything working better than before, but it runs fine without any signs of regression.
Closes #5828.

Improve metal frame rendering when more than one display is connected

---

osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs

Reduces the uploaded vertices when creating a new vertex buffer
Fixes the spikes I was seeing on entering song select where `VerticesUpl` goes way higher than `VerticesDraw`. Unfortunately this doesn't fix the whole performance issue, but seems like a sane improvement.
Change was implemented with oversight from smoogi.

Avoid initialising `VeldridVertexBuffer` immediately

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs

- Regressed in https://github.com/ppy/osu-framework/pull/5836
Originally reported in [Discord](https://discord.com/channels/188630481301012481/589331078574112768/1120261143819210855). This regression affected the (not really useful) assembly dropdown in visual tests, and also the duration dropdown in playlists screen osu!-side.

Fix item labels not generated while dropdown is in `Ready` state

---

osu.Framework/osu.Framework.csproj

- FlooGoo FMA100
- Gaomon GM156HD
- Gaomon PD2200
- Gaomon S830
- Genius i405x
- Huion G930L
- Huion H320M
- Huion H610 Pro V3
- Huion H690
- Huion Kamvas 12
- Huion Kamvas Pro 16 (2.5k)
- Huion RTM-500
- KENTING K5540
- Monoprice 10594
- UGEE S640
- UGTABLET M708 V2
- Veikk A15 V2
- Veikk A30 V2
- Veikk VK1060
- Veikk VK430
- Veikk Viola (VO1060)
- Wacom CTE-660
- Wacom CTH-301
- Wacom CTH-661-SE
- Wacom DTK-1300
- Wacom DTK-1660
- Wacom DTZ-1200W
- XP-PEN MT0960B (Deco Pro SW)
- XP-Pen Artist 10 (2nd Gen)
- XP-Pen Artist 13 (2nd Gen)
- XP-Pen Artist 13.3
- XP-Pen Artist 16 Pro
- XP-Pen Artist Pro 16TP
- Gaomon 1060 Pro
- Gaomon M6
- Gaomon S56K
- Gaomon S620
- Huion GC610
- Huion H1060P
- Huion H320M
- Huion H610 Pro V2
- Huion H610X
- Huion H640P
- Huion HC16
- Lifetec LT9570
- …

Bump OpenTabletDriver version to 0.6.1.0

---

osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
osu.Framework/Resources/Shaders/Internal/sh_Fragment_Output.h

Cleanup Veldrid shader resource layouts and add header guard

---

osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

I noticed this when opening texture visualiser (Ctrl+F3) and then the FPS display (Ctrl+F11). Likely what's happening here, though I haven't gone into it, is that the `TextureVisualiser` is attempting to display some textures from the FPS display that haven't been uploaded yet.
At the moment, I have no reason to believe this could occur in any other normal execution.

Fix possible nullref when binding textures under Veldrid

---

osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
osu.Framework/Testing/Drawables/Sections/ToolbarRunAllStepsSection.cs
osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
osu.Framework/Testing/TestBrowser.cs

Maintains support for multiple assemblies but removes the dropdown as proposed a while back on discord.
Open for feedback on this – if the assembly name being in the toolbar was seen as good hinting to have, we could choose to either leave this dropdown in place, or display it as text. Personally I think the window title is enough hinting for me, but let's see what people think.

Remove assembly dropdown from visual test browser

---

osu.Framework.Tests/Graphics/TripleBufferTest.cs
osu.Framework/Allocation/ObjectUsage.cs
osu.Framework/Allocation/TripleBuffer.cs
osu.Framework/Platform/GameHost.cs

As discussed in #osu-framework, this is probably a safer way of implementing the draw node triple buffer. It ensures that the last read buffer will never be written to. This may be helpful in scenarios where an external resource (ie. the GPU) is still interacting with the last read object's content.
This comes with no changes to lockability overheads, and only updates the naive approach previously used to find the next usable buffer.

Ensure triple buffer never uses the same buffer twice in a row

---

osu.Framework/Graphics/Sprites/SpriteText.cs

Fixes the other part of https://github.com/ppy/osu/issues/15135.

Exclude U+202F NARROW NO-BREAK SPACE from being treated as fixed-width

---

osu.Framework/Input/StateChanges/Events/InputStateChangeEvent.cs
osu.Framework/Platform/DesktopStorage.cs

The intention of this PR is to unblock https://github.com/ppy/osu/pull/24019, as CI detected a few more inspections there that in my judgement need to be fixed framework-side.
The nullability spec was carried over from R# annotations, but it really isn't clear _why_ it is there. None of the five subclasses of `InputStateChangeEvent` allow construction with a null input.
Spotted in https://github.com/ppy/osu/blob/511451770c98161daced844b082b4975c94f02dd/osu.Game/Rulesets/UI/RulesetInputManager.cs#L153.
The base `NativeStorage` is null-tolerant anyways.
This was relied on here: https://github.com/ppy/osu/blob/511451770c98161daced844b082b4975c94f02dd/osu.Game.Tournament/IPC/FileBasedIPC.cs#L67

Fix NRT-related issues found game-side

---

osu.Framework.Tests/Visual/Platform/TestSceneWindowModeResizedEvent.cs
osu.Framework/Platform/SDL2Window.cs
osu.Framework/Platform/SDL2Window_Windowing.cs

- Resolves #5879 
As seen in that issue, `Resized` would get invoked when the window was invalid / in the process of changing window modes. This is because we have a multi-step window mode change process _and_ we're fetching the window size with an event filter (SDL would usually coalesce those events to a single event with the last set, valid size).
Callstack from one `fetchWindowSize()` that would fetch the invalid size. Notice how `UpdateWindowStateAndSize()` is in progress.

Fix `IWindow.Resized` being invoked with invalid data during `WindowMode` switch

---

osu.Framework.Android/AndroidGameWindow.cs
osu.Framework.iOS/IOSWindow.cs
osu.Framework/Input/SDL2WindowTextInput.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/MacOS/MacOSWindow.cs
osu.Framework/Platform/OsuTKGraphicsSurface.cs
osu.Framework/Platform/OsuTKWindow.cs
osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
osu.Framework/Platform/SDL2DesktopWindow.cs
osu.Framework/Platform/SDL2Window.cs
osu.Framework/Platform/SDL2Window_Input.cs
osu.Framework/Platform/SDL2Window_Windowing.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

See https://github.com/ppy/osu-framework/pull/5880#discussion_r1248888299. Having these be public isn't doing any good.
Public members of `SDL2Window` that should have been exposed are now properly exposed in `IWindow`. Notably, `DragDrop` and `SetIconFromStream()` that were used in osu!.
Graphics surfaces are also changed to `internal` to make the compiler happy (using `internal` window in `public` ctor). If that is not desired, only the ctor can be made `internal`.
If you were using public members of `SDLWindow`/`OsuTKWindow`, change to use the appropriate `IWindow` member. If you find that you were using a member that is not available in `IWindow`, please open a discussion describing your use case.

Make `IWindow` and `IGraphicsSurface` implementations `internal`

---

osu.Framework/Platform/Windows/WindowsWindow.cs

osu! will use PerMonitor V2 in https://github.com/ppy/osu/pull/24092, so this PR changes framework to match.
The catch clauses could probably just catch [`EntryPointNotFoundException`](https://learn.microsoft.com/en-us/dotnet/api/system.entrypointnotfoundexception?view=net-7.0), but catching everything seems safer.

Set PerMonitor V2 DPI awareness on Windows

---

osu.Framework.iOS.props
osu.Framework.iOS/osu.Framework.iOS.Workarounds.targets

`ApplicationServices` is a macOS-only framework. I'm not sure where is it being referenced (probably a package we use), so let's just trim it away from here.

Work around iOS linker including `ApplicationServices` framework during compilation

---

osu.Framework.Benchmarks/BenchmarkSpriteText.cs
osu.Framework/Graphics/Sprites/SpriteText.cs
osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs

Of note, this doesn't show a huge improvement in benchmarks, but in an edge case noticed in osu!, the `AddRange` operation can add a perceivable overhead:
| ![JetBrains Rider 2023-07-03 at 08 16 07](https://github.com/ppy/osu-framework/assets/191335/c20539ce-9cab-43a4-8cbd-2ee16fcbfad2) | ![JetBrains Rider 2023-07-03 at 08 15 11](https://github.com/ppy/osu-framework/assets/191335/5213b2e7-a2a6-417c-b4d3-04102569b4fb) |
We believe this may be a dotnet runtime quirk.
Even though this change can't be shown in isolated benchmarks, I'd argue the code quality improvement is worth it.
Of note, the caching of the SSDQs at `SpriteText` was a bit redundant as it was being invalidated by basically everything. So it makes sense to just fetch it every time, …

Reduce complexity overhead (and avoid one copy) when obtaining character SSDQs in `SpriteTextDrawNode`

---

osu.Framework/FrameworkEnvironment.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs

As discussed in far too much length. We can test reducing this further at a later point. I've added an envvar to aid in this (`OSU_GRAPHICS_VBO_COUNT`).

Reduce VBO buffer count to 2

---

osu.Framework/Game.cs

Happens a lot with frame visualiser on iOS, part of it gets rendered within the phone's corner no matter the screen orientation.

Fix game tools being rendered outside safe area

---

osu.Framework/Platform/GameHost.cs
osu.Framework/osu.Framework.csproj

The game run loop is wrapped under `CADisplayLink`, therefore the time spent between two loop calls indicates `CADisplayLink` waiting for next V-Sync request.
Before:
After:

Fix frame statistics display showing `CADisplayLink` callback delays under "WndProc" time

---

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs

When running on mobile, we've seen gen 0 GCs almost every frame. I'm not sure if this is good or bad, but ignoring that for a moment, this would cause opening the frame statistics graphs to slowly grind the game to a halt as it tries to display this with box markers.
Pooling the boxes reduces the alloc overhead. Custom logic cleans up old squares to ensure things don't runaway in terms of performance.
https://github.com/ppy/osu-framework/assets/191335/bc2134c9-5715-4861-8861-1b790eabd1c0

Pool and limit how many GC boxes can be displayed on `FrameStatisticsDisplay` at once

---

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
osu.Framework/Graphics/Performance/PerformanceOverlay.cs

As mentioned in https://github.com/ppy/osu-framework/pull/5897/files/05a935442013cc2d07a0ac73e4edbd8887e2fd1c..4e4e4d6e3a2b39ec3cd9554650693a32e094414c#diff-21428f5fd4a0ed5b32fd7d887aaf536f1c93cbbdc973eaf94425abd346f2be52R78-R80.

Fix `PerformanceOverlay` autosize not working due to incorrect anchor

---

osu.Framework.iOS.props
osu.Framework.iOS/GameApplication.cs
osu.Framework.iOS/IOSWindow.cs
osu.Framework/Platform/SDL2Window.cs
osu.Framework/osu.Framework.csproj

First step towards #5902. After recent investigations, turns out Mono interpreter isn't as efficient as AOT is, and is the cause of many minor overheads that are affecting draw time negatively.
Switching osu! to use AOT compilation is going to be a considerable effort so I'll change this on o!f first and begin investigating iOS performance on a higher scale before moving into osu!.
Note that we're intentionally not using the `--interpreter=all` flag here (which allows the app to fall back to interpretation for dynamic code rather than throw exception), as we don't want to rely on interpretation at all until we come across a case where we can't help it.

Switch osu!framework iOS projects to use AOT compilation on release configurations

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework/Configuration/FrameworkDebugConfig.cs

When it works well, it works very well (ie. in isolated tests) but it's very rare for performance improvements to be seen as a result of front-to-back being enabled.
The reasoning for disabling by default is:
- It breaks on android when the render scale PR is applied (#5888). This could likely be resolved but as [pointed out](https://github.com/ppy/osu-framework/pull/5888#issuecomment-1622272437) by @bdach, the overall performance on android is considerably worse with front-to-back enabled – even in an optimal scenario where it should be helping.
- It's disabled on iOS as it doesn't work there
- It's showing worse performance on desktop in seemingly benign cases, as discovered on @frenzibyte's new performance tests in #5904:
https://github.com/ppy/osu-framework/assets/191335/c217f2b1-bd94- …

Disable front-to-back pass by default on all platforms

---

osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

It turns out we were initialising every mipmap level of every textures, while it is only actually required in scenarios we are not already replacing every pixel of the texture.
For framework usages, this is for atlases alone.
I've implemented this by changing the `initialisationColour` to be nullable. For native textures, it has a `null` default, which is perfect to cover all overrides (`VideoTexture` and `FrameBufferTexture`).
For the `IRenderer` exposed usage, the parameter was already required, so there is no default. This is good as it ensures a consume isn't going to see a change in behaviour out-of-the-blue.
---
At least on metal, this has *insane* performance effects across the whole game. Basically all my stutters are gone, including song select and player loading transition. …

Avoid initialising textures when unnecessary

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

Noticed while checking https://github.com/ppy/osu-framework/pull/5901.

Add back removed comment on creating texture images with no background specification

---

osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBufferStorage.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
osu.Framework/Graphics/Veldrid/VeldridStagingBufferPool.cs
osu.Framework/Graphics/Veldrid/VeldridStagingResourcePool.cs
osu.Framework/Graphics/Veldrid/VeldridStagingTexturePool.cs

Staging buffer cache has been removed from Metal in https://github.com/ppy/veldrid/pull/31, and needs to be brought back here to maintain performance. Needs testing on all platforms, especially D3D11 since it's the only backend that doesn't allocate a staging buffer in `CommandList.UpdateBuffer` (if there's any sign of performance degradation, I can easily revert back just for D3D11).

Add caching for Veldrid staging buffers in favour of `CommandList.UpdateBuffer`

---

osu.Framework.Android/AndroidClipboard.cs
osu.Framework.Android/AndroidGameHost.cs
osu.Framework.Tests/Visual/Platform/TestSceneClipboard.cs
osu.Framework/Graphics/UserInterface/TextBox.cs
osu.Framework/Platform/Clipboard.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/HeadlessClipboard.cs
osu.Framework/Platform/HeadlessGameHost.cs
osu.Framework/Platform/MacOS/MacOSClipboard.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs
osu.Framework/Platform/MacOS/Native/Cocoa.cs
osu.Framework/Platform/SDL2/SDL2Clipboard.cs
osu.Framework/Platform/SDL2GameHost.cs
osu.Framework/Platform/Windows/WindowsClipboard.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs

As noted in https://github.com/ppy/osu/pull/24171, clipboard can't be used in headless tests. This PR adds a virtual clipboard that can be used in test, and improves old clipboard code along the way.
Changes:
- `Clipboard` is now a cached dependency (instead of acquiring it from `GameHost.GetClipboard()`) this brings it in line with osu-framework best practises(maybe?) and allows overriding it for tests if necessary
- `HeadlessGameHost` now uses a `HeadlessClipboard` that stores the data in-memory and doesn't modify the host OS clipboard
- `AndroidClipboard` has been added, text only for now to keep it simple. [docs](https://developer.android.com/develop/ui/views/touch-and-input/copy-paste)
The new way to retrieve a `Clipboard` instance is to resolve it via dependency injection directly. …

Improve `Clipboard` class for use in tests and on Android

---

osu.Framework.Tests/Visual/Performance/TestSceneTexturePerformance.cs
osu.Framework.Tests/Visual/Performance/TestSceneTextureUploadPerformance.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs

This also makes the uploads happen every frame, as this is more useful for diagnosing contention edge cases.
Notes from testing:
- Metal can show signs of corruption with higher texture upload counts.
- D3D has very low performance compared to metal with similar texture upload counts.

Split texture upload performance test into own `TestScene`

---

osu.Framework.Tests/Visual/Sprites/TestSceneScreenshot.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

- Regressed in https://github.com/ppy/veldrid/pull/30
Initially I was looking into properly implementing a "wait for fence" logic over at Veldrid using [`notifyListener:atValue:block`](https://developer.apple.com/documentation/metal/mtlsharedevent/2966574-notifylistener?changes=_8&language=objc), but I've stumbled across issues with P/Invokes specific to that function, and tried going back and fourth on it for over an hour to no avail. For the time being, I'm working around this locally.

Fix screenshots not working on Metal

---

osu.Framework/Graphics/BufferedDrawNode.cs

Weird code was weird.
Note that this will result in `Nearest` scaling being applied. I think it's fine. Better than not working at all (it used to scale the content to be smaller on-screen).
https://github.com/ppy/osu-framework/assets/191335/74754480-0afb-4af8-9d88-a0f5fa0e9c16

Fix `FrameBufferScale` not working when `PixelSnapping` is enabled

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

- Closes #5923 
Please test thoroughly and check multiple times that this does fix the issue, I have no explanation for how this fixes the issue (I rather have suspicion it's hiding the issue instead), but I cannot reproduce this on my machine (M1 Pro) and there's not much to lose in flushing before drawcall so why not.

Fix texture uploads getting corrupted on Metal with non-Apple GPUs

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Ignoring the fact that these tracking fences are doing nothing in D3D (they are set immediately https://github.com/ppy/veldrid/blob/6a43198af1b069e56ac53770249a5424c1859500/src/Veldrid/D3D11/D3D11GraphicsDevice.cs#L229-L232):
This is a regression so let's fix it locally for the time being.
Time spent in `ManualResetEvent` construction:
Before this PR:
After this PR:

Add a fence pool for frame tracking fences

---

osu.Framework/Audio/Callbacks/BassCallback.cs
osu.Framework/Audio/Callbacks/FileCallbacks.cs
osu.Framework/Audio/Callbacks/SyncCallback.cs

`IsDynamicCodeSupported` returns true in iOS when building with interpreter mode on, so it's probably better to use that instead (kind of as a way of testing dynamic code on iOS). Note that I have kept the `TransformCustom` cases as they generate CIL instructions, which I'm not sure would outperform reflection in an interpretation environment (I have tested this and I didn't see any noticeable differences, but felt safer not to change it).

Replace most usages of `IsDynamicCodeCompiled` with `IsDynamicCodeSupported`

---

osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

Resolves noticeable texture corruption on osu!:
It's possible to have a draw frame which processes enqueued texture uploads but doesn't have any draw nodes to render to the screen (i.e. no calls to `DrawVertices`), therefore the texture upload commands continue to the next frame without being submitted and the staging resources incorrectly return back to the pool. This PR resolves the bug by ensuring texture upload commands are submitted before the end of the frame.
Reproducing this bug requires a fresh game state that has absolutely no draw node. Can be repro'd with this simple code in `SampleGameGame`:
```csharp
public partial class SampleGameGame : Game
{
protected override void LoadComplete()
{
base.LoadComplete();
Container<Drawable> test;
Add(test = new Container
{
Anchor = …
```

Fix potential texture corruption on Veldrid

---

osu.Framework/Platform/GameHost.cs

- Closes https://github.com/ppy/osu/issues/24242
In multi-threaded mode, `windowUpdate` will begin collecting "sleep" time as draw thread while in input thread, meanwhile `DrawFrame` will also begin collecting "sleep" time in the draw thread, therefore they collide together and produce 5 different exceptions.
Reverting for now as there's not a simple solution towards this.

Revert iOS frame-rate display fix to resolve issues with running multi-threaded mode

---

.github/workflows/ci.yml
osu-framework.sln.DotSettings
osu.Framework.SourceGeneration.Tests/Verifiers/CSharpMultiPhaseSourceGeneratorVerifier_Test.cs
osu.Framework.SourceGeneration.Tests/Verifiers/CSharpSourceGeneratorVerifier.cs
osu.Framework.SourceGeneration.Tests/Verifiers/CSharpSourceGeneratorVerifier_Test.cs
osu.Framework.SourceGeneration/Generators/AbstractIncrementalGenerator.cs
osu.Framework.SourceGeneration/Generators/GeneratorEventDriver.cs
osu.Framework.Tests/Dependencies/Reflection/CachedAttributeTest.cs
osu.Framework.Tests/Dependencies/SourceGeneration/CachedAttributeTest.cs
osu.Framework/Graphics/Drawable_HandleInputCache.cs
osu.Framework/Graphics/Drawable_IsLongRunning.cs
osu.Framework/osu.Framework.csproj

As we continue to add more source generators, we've seen increases in compile-time overheads, with local testing showing over 2x compile times with source generators turned on.
osu!framework source generators are made to optimise builds at runtime (mostly by removing reflection overhead). As such, it doesn't make sense to run these for debug releases as they are basically custom release-targeting optimisations.
This should not result in a noticeable change in runtime performance during debug, but will reduce compilation times by over 50% in most cases. This is valuable during debug as the most common case is frequently building / hot reloading for quick iteration.

Change source generators to only run for release builds

---

osu.Framework.iOS.props

`dotnet build` by default builds on the `AnyCPU` platform. Explicitly adding `-p:Platform=iPhone` doesn't work halfway through the build for reasons I don't think I want to know (it reverts back to `AnyCPU` platform). Fixed the workaround instead to copy to the correct directory if no custom `Platform` is specified (eventually the `Platform != AnyCPU` branch won't exist along with the entire `iPhone`/`iPhoneSimulator` configuration [once Rider becomes smart about choosing which RID to build with](https://youtrack.jetbrains.com/issue/RIDER-76794/Cannot-deploy-MAUI-project-to-physical-iOS-device)).

Fix building iOS projects in AOT mode via command line not working

---

osu.Framework/Allocation/TripleBuffer.cs

One of those things I see in passing and can't un-see. Call this a developer indulgence rather than an optimisation if you want.
|:------:|:-----:|
| ![JetBrains Rider 2021-09 at 07 04 10](https://github.com/ppy/osu-framework/assets/191335/aa75a5b6-7ab4-49c5-bdce-2839403675c0) | ![JetBrains Rider 2023-07-10 at 07 09 26](https://github.com/ppy/osu-framework/assets/191335/c2ad2897-dbe0-433f-a5e3-7fa71a3c7fb9) |
| ![JetBrains Rider 2021-09 at 07 03 40](https://github.com/ppy/osu-framework/assets/191335/4614c03f-cfae-4179-8fbd-189ff5fc95e7) | ![JetBrains Rider 2023-07-10 at 07 09 00](https://github.com/ppy/osu-framework/assets/191335/931f3fbd-27e8-42a9-af23-f74b7ef74d6a) |
The time profiling results should be taken with a grain of salt. Of note is the reduction in lock %, …

Remove most locking overhead in `TripleBuffer`

---

osu.Framework/Platform/MacOS/Native/Cocoa.cs

Originally reported in [discord](https://discord.com/channels/188630481301012481/589331078574112768/1133129653553463386). The new implementation mimicks Xamarin's implementation, see https://github.com/xamarin/xamarin-macios/blob/d1d3dcdf68928303f8a00719a26dc1844b8567d9/src/Foundation/NSString.cs#L183-L200:

Use better method for `NSString` conversion to avoid potentially pasting garbage content from clipboard

---

.github/workflows/report-nunit.yml

Example of it not working: https://github.com/ppy/osu-framework/actions/runs/5667046167.
Regressed with https://github.com/ppy/osu-framework/pull/5938/commits/d3ac44d45ac8a46c8f24ffda97673ba94d374fa0.

Fix CI test results not working

---

osu.Framework/Graphics/OpenGL/Buffers/GLVertexUtils.cs

This PR can be merged independently and should not result in breaking changes.
Ints passed through `glVertexAttribPointer` are converted to floats. This is documented as such in the description (https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glVertexAttribPointer.xhtml), and appears like this in RenderDoc:
(Notice `R32_SINT Cast to float`)
The result is that these attributes are not usable as ints in shaders.
The code in this PR is the same as what veldrid does: https://github.com/ppy/veldrid/blob/5ea442d15d3bead92c9d32a876bf3f8b8e453d95/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs#L338-L358

Fix integer vertex atributes being cast to floats

---

osu.Framework/Graphics/OpenGL/Batches/GLVertexBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs

This can be merged independently and will not cause a breaking change.
In upcoming changes, I'll have `VeldridRenderer.DrawVertices()` and the soon-to-be `GLRenderer.DrawVertices()` binding uniform and array buffers locally. Doing this will trigger a `FlushCurrentBatch()` that currently causes a stack overflow. This should be a no-op.

Prevent re-entrancy into `VertexBatch.Draw()`

---

osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs

Hit this a few times recently, and the fix actually looks quite simple?
Should close https://github.com/ppy/osu/issues/24013.

Fix `DrawableAudioWrapper` deadlock by moving unbind to `UnbindAllBindables`

---

osu.Framework.Tests/Bindables/BindableListTest.cs
osu.Framework/Bindables/BindableList.cs

- Closes https://github.com/ppy/osu-framework/issues/5953 (using solution 1).
- *Probably* also covers https://github.com/ppy/osu-framework/issues/5635 (see call stack, matches original investigation). I'm not listing this as closing the issue, because the threading concern is likely still real, but the specific stack in that issue suggests it will cover that case.
- Closes https://github.com/ppy/osu/issues/16026
- Closes https://github.com/ppy/osu/issues/24085
Given how egregious this issue is, I would argue we use this solution as it's very simple to implement and review. Performance overhead should be negligible, and either way shouldn't matter as primary goal should be to get this in a robust state.

Fix `BindableList` being unsafe for complex bind trees

---

osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs
osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithUnloading.cs
osu.Framework/Graphics/Containers/ModelBackedDrawable.cs

The test added should hopefully explain this one, but here's a text explanation:
`CreateDrawable()` is allowed to return `null`s. The case where it returns `null` on the first call was handled by `loadDrawable()` in the early exit, but the nested case (which is called after unload operations where the first invocation of `CreateDrawable` has already been consumed) was not covered.
To fix this without requiring changes in usages, I've made `ModelBackedDrawable` use an empty drawable in cases it would otherwise have crashed due to `null` (see c341a6365326ae9305f28e047b6d8d1b3761e1df).
I've also applied NRT with existing null expectation to make things clearer.
This fixes flaky tests in `TestSceneBeatmapSetOverlay` (see https://teamcity.ppy.sh/buildConfiguration/Osu_Build/40918?hideProblemsFr …

Fix `ModelBackedDrawable` potentially crashing on badly timed `null`

---

osu.Framework/Graphics/Drawable.cs

Example:
```
Unhandled exception. System.InvalidOperationException: Tried to load long-running drawable type MultiSpectatorLeaderboard in a non-direct async context. See https://git.io/Je1YF for more details.
```

Include type name in long-running exception output

---

osu.Framework/Platform/Storage.cs

RFC.
The core motivation for this change is several failing test runs on the osu! side such as:
- https://github.com/ppy/osu/actions/runs/5726098589/job/15515865792
- https://github.com/ppy/osu/actions/runs/5707825455/job/15464878786
- https://github.com/ppy/osu/actions/runs/5729725579/job/15527053558
in which `SafeWriteStream` appears to be in the process of being finalised and attempting to call `Dispose()`.
Finalisers are [notoriously](https://ericlippert.com/2015/05/18/when-everything-you-know-is-wrong-part-one/) [unreliable](https://ericlippert.com/2015/05/21/when-everything-you-know-is-wrong-part-two/), as they give no guarantees as to if they will be called, when they will be called, how many times they will be called, and so on, so I think having them doing anything in …

Disallow `SafeWriteStream` logic from running on finalisation

---

osu.Framework/Graphics/Shaders/ShaderCompilationStore.cs

Noticed this when testing multiplayer spectator, and more than one user had flashlight enabled.
See inline comment for a better description.
Relevant crash:
```
2023-08-03 10:47:32 [verbose]: Requesting any changes since last known queue id 7370295
2023-08-03 10:47:33 [error]: Failed to save shader to cache.
2023-08-03 10:47:33 [error]: System.IO.IOException: The file '/Users/dean/Library/Application Support/osu-development/cache/shaders/2ad9c747fce2b1e65f237d2355197306#abd6023987102484f5046ab5bd157cca#1' already exists.
2023-08-03 10:47:33 [error]: at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
2023-08-03 10:47:33 [error]: at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
2023-08-03 10:47:33 [error]: at …
```

Fix potential user-facing error when same shader is compiled in parallel

---

osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
osu.Framework/Input/ButtonEventManager.cs
osu.Framework/Input/UserInputManager.cs

RFC. Closes https://github.com/ppy/osu/issues/24463.
This was always a problem, but got much louder after https://github.com/ppy/osu-framework/pull/5557. Reproduction scenario for issue:
1. Start with game in windowed state
2. Enable tablet handler
3. Change active area to be smaller than available tablet area
4. Disable mouse confine
5. Move tablet stylus to inactive area (which will cause the mouse pointer to leave the game window bounds)
6. Touch tablet
https://github.com/ppy/osu-framework/assets/20418176/e8a7f31c-f479-446a-a5cd-9472b2785329
Part of the cause here is this:
https://github.com/ppy/osu-framework/blob/75ed421f60228920abd819cebc5982cb7799bbbb/osu.Framework/Input/UserInputManager.cs#L68-L72
which allows the button release event to reach the `ButtonEventManager` without a …

Fix crash on tablet stylus touch when stylus is over inactive area and mouse confine is off

---

osu.Framework.Tests/Audio/DrawableAudioWrapperTest.cs
osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs

Closes https://github.com/ppy/osu/issues/24519
An innocent change to `DrawableAudioWrapper` (https://github.com/ppy/osu-framework/pull/5956) caused a rather serious game-side regression (https://github.com/ppy/osu/issues/24519), wherein tracks would start playing on top of each other in song select.
The immediate cause of the failure was that tracks were faded out to zero volume via audio adjustments. When audio adjustments are unbound, `AggregateBindable` logic causes the aggregate volume to be recomputed, and if there are no sources in the aggregate left, it will revert to the default initial value of 1.
In normal usages this is perfectly fine and how the aggregate bindable system should work, but in rare cases where the async disposal thread was under pressure, such as with a weak …

Fix `DrawableAudioWrapper` unapplying adjustments between removal from hierarchy and disposal

---

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs
osu.Framework/Graphics/Cursor/PopoverContainer.cs
osu.Framework/Graphics/UserInterface/Popover.cs

This is intended to be used for https://github.com/ppy/osu/issues/12045.
The "hinting" in question is more specifically allowing popovers to specify on which sides of the target drawable they're allowed to display, which is achieved by setting the popover's `AllowableAnchors`. This comes in handy in cases like the above when sometimes you want to control the autolayout algorithm so that the popover can only be shown on the sides of a button.
https://github.com/ppy/osu-framework/assets/20418176/2eb4caf6-95ec-4e4d-9182-66a65dd4c3d0

Implement popover hinting

---

osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
osu.Framework/Input/Bindings/KeyBindingContainer.cs

RFC.
This change would allow to replace [this game-side workaround](https://github.com/ppy/osu/blob/34a519f80354d9de353b4feee85be15c221a2d97/osu.Game/Input/Bindings/GlobalActionContainer.cs#L166-L170) with usage of `KeyBindingContainer.IsPrioritised`. The workaround in question is a blocker in resolving a game-side p0 issue (https://github.com/ppy/osu/issues/24248#issuecomment-1652296315).
More specifically, this change ensures that the game-side workaround can be replaced with `IsPrioritised` without regressing issues like https://github.com/ppy/osu/issues/6026. The fail case is when a child of the `KeyBindingContainer` is handling a plain input handler method like `OnMouseDown()`, and handles the positional input before the `KeyBindingContainer` even has a chance to see it. This is …

Make `KeyBindingContainer.Prioritised` work for positional input too 

---

README.md

I'm not quite sure whether open-source is a requirement for being added to this list, there are plans on open-sourcing sometime in the future but for the early state it was deemed closed-source is better, although certain components like parsers and algorithms for the game will be provided as NuGet packages.

Add DeltaDash to the list of projects using the framework

---

osu.Framework.Tests/Visual/UserInterface/TestSceneRigidBody.cs
osu.Framework/Physics/RigidBodySimulation.cs

For context, I'm making a top-down game kinda like billiards where I need the gravity to be 0.

Allow gravity in RigidBodySimulation to be adjustable

---

osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
osu.Framework/Graphics/Rendering/MaskingInfo.cs
osu.Framework/Graphics/Rendering/Renderer.cs

Prereqs:
Fixes (at least some) 1px masking errors:
| --- | --- |
| ![osu_2023-08-03_16-05-01](https://github.com/ppy/osu-framework/assets/1329837/b4c5a91e-ad55-425f-ab2c-b0130e634696) | ![osu_2023-08-03_16-05-38](https://github.com/ppy/osu-framework/assets/1329837/f2c7a07d-5423-4350-8fea-f1ffd71f1edb) |

Use RectangleF for masking scissor

---

osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
osu.Framework/Input/Bindings/KeyBindingContainer.cs

Fix `KeyBindingContainer` propagating release events to removed drawables

---

osu.Framework/Graphics/Video/VideoDecoder.cs

Usually, the IO context would be closed and freed by `avformat_close_input`. But since we're using a custom IO context, this does not happen. So we need to free the IO buffer and context ourselves.
Note that there is no need to `avio_close` because it's never opened in the first place.

Free AVIOContext and IO buffer

---

osu.Framework/Platform/NativeStorage.cs
osu.Framework/Platform/Storage.cs

Coming from https://github.com/ppy/osu/actions/runs/5948760882/job/16133189924, the only way I can see this happening is if the underlying `File.Move` logic is less atomic than we expect it to be.
In the process of looking into this, I noticed there's an `overwrite` flag available for `File.Move` which tends to prefer a `rename` operation internally on unix, rather than `link`.
On windows (the failcase in question) it likely won't help at the end of the day.
Anyway, personally I think having it overwrite by default is what we prefer from our API. If that isn't agreed on then closing this without further consideration is fine.

Change behaviour of `Storage.Move` to overwrite existing by default

---

osu.Framework/Platform/SDL2Window_Windowing.cs

On a Windows PC, I noticed that running osu/osu-framework at non-native resolutions (1280x1024 on a 1920x1080 screen) would crash when minimising a fullscreen window, with:
```
2023-08-24 04:45:55 [error]: An unhandled error has occurred.
2023-08-24 04:45:55 [error]: NUnit.Framework.AssertionException: Stored Displays don't match actual displays: Stored displays:
2023-08-24 04:45:55 [error]: Name: Dell AW2521H, Bounds: {X=0,Y=0,Width=1280,Height=1024}, DisplayModes: 66, Index: 0
2023-08-24 04:45:55 [error]: 
2023-08-24 04:45:55 [error]: Actual displays:
2023-08-24 04:45:55 [error]: Name: Dell AW2521H, Bounds: {X=0,Y=0,Width=1920,Height=1080}, DisplayModes: 66, Index: 0
2023-08-24 04:45:55 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2) in …
```

Fix crash on minimising from non-native fullscreen resolutions

---

osu.Framework/Graphics/Lines/Path_DrawNode.cs
osu.Framework/Graphics/Rendering/Vertices/TexturedVertex3D.cs

Resolves https://github.com/ppy/osu/issues/24766
Resolves https://github.com/ppy/osu/issues/24769
Resolves https://github.com/ppy/osu/issues/24767

Fix masking broken with TexturedVertex3D

---

osu.Framework/IO/Network/JsonWebRequest.cs
osu.Framework/IO/Network/WebRequest.cs

One less potential web request exception = maybe a touch better debug performance? Not sure, but this throws on every timeout of requests [osu! side](https://github.com/ppy/osu/blob/9f842ccdc057e6c6ec60def1ac607f1ea00f02e1/osu.Game/Online/API/APIRequest.cs#L199) and can easily be avoided.

Avoid throwing exception when attempting to access `WebRequest` response in fail path

---

osu.Framework/osu.Framework.csproj

- Fixes https://github.com/ppy/osu/issues/23872
- Adesso Cybertablet K8
- Gaomon PD156 Pro
- Huion GT-221
- Huion H641P
- Huion Kamvas 24 Plus
- Huion Kamvas Pro 24 (4K)
- Huion Q630M
- Huion RDS-160
- Huion RTE-100
- Parblo Ninos N4
- Parblo Ninos N7
- UGEE U1200
- VEIKK VK430 V2
- Waltop Slim Tablet 5.8"
- XP-Pen Artist 16 (2nd Gen)
- XP-Pen Deco L
- Gaomon 1060 Pro
- Gaomon M106K Pro
- Gaomon M1230
- Huion H430P
- Huion H610 Pro V3
- Huion HS610
- Huion HS611
- Huion Kamvas Pro 16 (2.5k)
- Huion Kamvas Pro 16
- Huion RTM-500
- VEIKK VK430
- Wacom CTE-650
- Wacom ET-0405A-U
- XP-Pen Star 06C
- Fix barrel rotation reports causing broken pressure, tilt, and pen buttons on some wacom tablets.
This fixes issues related to osu! lazer's OTD implementation not working on some scenarios where …

Bump OpenTabletDriver to 0.6.3.0

---

osu.Framework/Graphics/UserInterface/TextBox.cs

Closes https://github.com/ppy/osu/issues/24867.
If this is seen as a bad direction, I can fix this locally at osu!'s end (using the `AllowClipboardExport` property).

Don't block cut/copy platform actions on empty textbox selection

---

osu.Framework/Input/Handlers/Tablet/TabletDriver.cs

See https://github.com/ppy/osu/discussions/24915. Maybe wait for a response before going ahead with this, but it doesn't seem worthwhile to log non-errors to the user.

Stop logging non-error output from OpenTabletDriver

---

osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/HeadlessGameHost.cs

Has been reported by multiple users, probably due to a once-off startup failure caused by external factors.
Can be tested with something like:
```diff
diff --git a/osu.Framework/Platform/MacOS/MacOSGameHost.cs b/osu.Framework/Platform/MacOS/MacOSGameHost.cs
index 1600b9af0..2cb5e4432 100644
--- a/osu.Framework/Platform/MacOS/MacOSGameHost.cs
+++ b/osu.Framework/Platform/MacOS/MacOSGameHost.cs
@@ -21,7 +21,7 @@ internal MacOSGameHost(string gameName, HostOptions options)
{
}
-        protected override IWindow CreateWindow(GraphicsSurfaceType preferredSurface) => new MacOSWindow(preferredSurface);
+        protected override IWindow CreateWindow(GraphicsSurfaceType preferredSurface) => null;
public override IEnumerable<string> UserStoragePaths
{
```
---
Closes …

Fix keyboard handler getting disabled on window creation failure

---

osu.Framework/Graphics/Audio/WaveformGraph.cs

The previous attempt to fix this (https://github.com/ppy/osu-framework/pull/5197) helped, but there were still some scenarios where invalidation would cause regeneration.
Let's just do our own invalidation for now.
One thing I'm not sure about is whether checking `DrawSize` here is enough (should I be using `ScreenSpaceDrawQuad.Size` instead?).
Closes https://github.com/ppy/osu/issues/24951
| ![osu! 2023-09-29 at 10 03 06](https://github.com/ppy/osu-framework/assets/191335/4186ff87-edb5-4491-9637-39ae4f7502b3) | ![osu! 2023-09-29 at 10 02 11](https://github.com/ppy/osu-framework/assets/191335/7caf213f-0642-42bc-9eb1-5593f485627e) |

Fix `WaveformGraph` overhead when `DrawPosition` is changed

---

osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs

They're starting to get a bit flaky, as seen in:
- https://github.com/ppy/osu-framework/pull/6009/checks?check_run_id=17249564046
- https://github.com/ppy/osu-framework/pull/6009/checks?check_run_id=17249563269
30ms of leeway is enough to cover these, and then some (biggest gap seen so far was ~21ms).

Increase tolerance in decoupling framed clock tests

---

osu.Framework.Tests/Threading/ThreadedTaskSchedulerTest.cs
osu.Framework/Threading/ThreadedTaskScheduler.cs

See: https://github.com/ppy/osu/runs/17361055215#r0s1

Fix race condition in ThreadedTaskScheduler when adding tasks

---

osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs

Hopefully should resolve https://github.com/ppy/osu/issues/24987, however this is based off of [my assumption](https://github.com/ppy/osu/issues/24987#issuecomment-1747750490).
Previously we were passing `hue` to the shader and computing hsv to rgb in there.
Now horizontal gradient (from white to colour) is being passed through the `Colour` property and vertical gradient (from colour to black) is being added on top in the shader.
Visuals/performance are the same.
| master | pr |
|---|---|
| ![master](https://github.com/ppy/osu-framework/assets/22874522/d4fd97e9-106a-4d03-8298-92724d08ed80) | ![pr](https://github.com/ppy/osu-framework/assets/22874522/1bbc03ac-8f8d-4963-8b72-f6562c7f30f0) |

Simplify `SaturationValueSelector`

---

osu.Framework.Tests/Audio/TrackVirtualTest.cs
osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
osu.Framework/Audio/Track/TrackVirtual.cs
osu.Framework/Timing/DecouplingFramedClock.cs

Noticed when going through osu! side test failures.
Also adds safeties and test coverage to `DecouplingFramedClock` against a source which may still start after a failed seek. Better safe than sorry I guess.
Note that the test doesn't fail even without the `TrackVirtual` fix, as it's not using a `TrackVirtual`.

Fix incorrect implementation of `TrackVirtual`

---

osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
osu.Framework.Tests/Clocks/InterpolatingFramedClockTest.cs
osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs
osu.Framework/Timing/InterpolatingFramedClock.cs

I'm crossing my fingers that at face value this one is understandable. I'll add inline review notes as to why the changes were made.

Fix `InterpolatingFramedClock` not correctly handling seeks when source clock is stopped

---

osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
osu.Framework/Testing/TestScene.cs

I got sick of doing this manually.
In the future I'd like to expand this to probably be able to persist across hot reloads of the same test scene.
https://github.com/ppy/osu-framework/assets/191335/560b8924-f5d5-4cc9-b3f1-1bc5e8dbb7b0

Add button to randomise test scene background colour

---

.github/workflows/build-ffmpeg.yml
osu.Framework.NativeLibs/scripts/ffmpeg/common.sh

Closes ppy/osu#25086.
[MPEG-4 Part 2](https://en.wikipedia.org/wiki/MPEG-4_Part_2) is a video coding standard that sits "between" H.262 and H.264. Xvid, DivX and some less known formats implement it.
FFmpeg supports these derivative codecs through the `mpeg4` decoder, so to support `xvid` and `divx` (which seems to have been used in some beatmaps), this PR enables it and the according parser.
Note that this does not depend on `libxvid`, which is GPL.

FFmpeg: Enable MPEG-4 parser and decoder

---

osu.Framework/Resources/Shaders/sh_Blur.fs

- Closes https://github.com/ppy/osu/issues/24960
- Reverts https://github.com/ppy/osu-framework/pull/5979
I could not investigate this as I failed to repro in local builds on neither my iPad nor my phone, but I have confirmed at least that the blur breakage only occurred on the next working release after the [workaround removal PR](https://github.com/ppy/osu-framework/pull/5979) was merged, so I'm going ahead with reverting that for now.
I've made sure at least that blurring still works on all of my devices regardless of its state previously.

Bring back shader workaround to fix blur on iOS

---

osu.Framework/Platform/Display.cs
osu.Framework/Platform/SDL2Window_Windowing.cs

Currently, SDL provides two display modes for an iPad, both of which resemble the same display's resolution, except that the second one is the portrait version of the first one.
For simplicity, let's not provide any display modes in such case.

Disable retrieval of SDL display modes on non-desktop platforms

---

osu.Framework/Platform/SDL2Window_Input.cs

- Closes https://github.com/ppy/osu-framework/issues/5788
I originally envisioned the fix to complicate the relative mouse logic further, capturing the cursor when at least one button is held down. That was too hard and not worth the effort. Instead, query the global mouse button state when it's outside the window and release any buttons that should not be held.
It's important that the buttons can only be _released_, not pressed when the cursor is outside the window. Also important (but not that much) is that the buttons are released after the move event is handled so the released events have the most up-to-date position.

Fix releasing mouse buttons outside of window not working in relative mode

---

osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs

Noticed when looking into https://github.com/ppy/osu/issues/5378#issuecomment-1780613477.
Since a single OTD `IDeviceReport` can implement [multiple report interfaces](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/b996c8feb0b3da53ff0599940af550118f6422ca/OpenTabletDriver.Configurations/Parsers/Wacom/Bamboo/BambooTabletReport.cs#L7), a `switch` would handle only one of the report types.

Correctly handle OTD "multi-reports"

---

osu.Framework/Audio/Track/TrackBass.cs
osu.Framework/Audio/Track/Waveform.cs

BASS uses 16-bit samples by default if neither BassFlags.Byte nor BassFlags.Float is specified. (https://www.un4seen.com/doc/#bass/BASS_StreamCreate.html)
You can find this out by applying the following diff:
```diff
--- a/osu.Framework/Audio/Track/TrackBass.cs
+++ b/osu.Framework/Audio/Track/TrackBass.cs
@@ -15,6 +15,7 @@
using osu.Framework.Extensions;
using osu.Framework.Extensions.ObjectExtensions;
using osu.Framework.Utils;
+using osu.Framework.Logging;
namespace osu.Framework.Audio.Track
{
@@ -106,6 +107,9 @@ internal TrackBass(Stream data, string name, bool quick = false)
bool success = seconds >= 0;
+                if (Bass.ChannelGetInfo(activeStream, out var info))
+                    Logger.Log($"Track Resolution: {info.Resolution}");
+
if (success)
{
Length = seconds * 1000; …
```

Fix wrong bytes per sample in TrackBass

---

osu.Framework/FrameworkEnvironment.cs
osu.Framework/Game.cs

https://github.com/ppy/osu-framework/wiki/Environment-variables#osu_frame_statistics_via_touch
I think it makes more sense to have it as described in the wiki. A hybrid solution would be to default to enabled on debug, and disabled on release (the envvar would always override the default in the case).
Currently there's no way to disable touch frame statistics in debug builds (one can only enable them in release builds).

Fix `FrameStatisticsViaTouch` to work as described in the wiki

---

osu.Framework.Tests/MathUtils/TestPathApproximator.cs
osu.Framework.Tests/Visual/Drawables/TestSceneCircularArcBoundingBox.cs
osu.Framework.Tests/Visual/Drawables/TestSceneCustomEasingCurve.cs
osu.Framework.Tests/Visual/Drawables/TestSceneInteractivePathDrawing.cs
osu.Framework.Tests/Visual/Drawables/TestScenePathApproximator.cs
osu.Framework.Tests/Visual/Graphics/TestSceneShaderStorageBufferObject.cs
osu.Framework/Graphics/Lines/Path.cs
osu.Framework/Utils/IncrementalBSplineBuilder.cs
osu.Framework/Utils/PathApproximator.cs

This adds the IncrementalBSplineBuilder class which can be used to build up a B-Spline from a series of linear points efficiently. The class takes special care to keep the number of control points.
This is a preparatory framework side change to implement free-hand drawing of sliders in the osu!lazer editor.
The following `PathApproximator` methods have been renamed:
| old | new |
| :- | :- |
| `ApproximateBezier` | `BezierToPiecewiseLinear` |
| `ApproximateBSpline` | `BSplineToPiecewiseLinear` |
| `ApproximateCatmull` | `CatmullToPiecewiseLinear` |
| `ApproximateCircularArc` | `CircularArcToPiecewiseLinear` |
| `ApproximateLinear` | `LinearToPiecewiseLinear` |
| `ApproximateLagrangePolynomial` | `LagrangePolynomialToPiecewiseLinear` |
Additionally, `ApproximateBSpline`'s polynomial order …

Add class for efficiently building B-Splines

---

osu.Framework/Utils/PathApproximator.cs

Previously, `PathApproximator.BSplineToPiecewiseLinear` was on one hand too permissive in its input handling (people knowing spline math would scratch their head) and, on the other hand, unintuitively returned an empty spline when given a single control point.
This PR addresses both concerns and adds explanatory comments to the function body.

PathApproximator: no BSpline degree <1 and better special case handling

---

osu.Framework.Tests/Visual/Sprites/TestSceneLargeStoreMipmaps.cs
osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
osu.Framework/Graphics/Textures/LargeTextureStore.cs

As [per discussion](https://discord.com/channels/188630481301012481/589331078574112768/1174532880408518838).

Allow enabling computed mipmaps in `LargeTextureStore`

---

osu-framework.sln.DotSettings
osu.Framework.Benchmarks/BenchmarkFontLoading.cs
osu.Framework.Tests/IO/FontStoreTest.cs
osu.Framework.Tests/Visual/Audio/TestSceneAudioMixer.cs
osu.Framework.Tests/Visual/Drawables/TestSceneDrawableScale.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/BindableDouble.cs
osu.Framework/Bindables/BindableFloat.cs
osu.Framework/Bindables/BindableList.cs
osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
osu.Framework/IO/Stores/FontStore.cs
osu.Framework/IO/Stores/StorageBackedResourceStore.cs
osu.Framework/Platform/GameHost.cs

- Rewrite veldrid extension logging code to avoid fixed-in-delegate inspection
- Fix multiple cases of using objects which may be disposed
- Add some missing nullability markers
- Add new migration flag
A couple of inspections are still flagging warning, but are r# bugs:
https://youtrack.jetbrains.com/issue/RSRP-494840/Incorrect-Conditional-access-qualifier-expression-is-known-to-be-not-null 
https://youtrack.jetbrains.com/issue/RSRP-494839/Resharper-asks-to-dispose-IEnumerator-which-does-not-implement-IDisposable

Update some inspections to (mostly) satisfy latest rider EAP

---

osu.Framework.Tests/MathUtils/TestPathApproximator.cs
osu.Framework.Tests/Visual/Drawables/TestSceneInteractivePathDrawing.cs
osu.Framework/Utils/IncrementalBSplineBuilder.cs
osu.Framework/Utils/PathApproximator.cs

- The BSpline builder now smoothens the input curve before processing it, making it more reliable.
- Corners are detected explicitly based on local maxima of winding rate. To be automatically converted to red control points on osu!'s end.
- The density of control points is also determined by winding rate.
Fixes https://github.com/ppy/osu-framework/issues/6046 and addresses comments in https://github.com/ppy/osu/pull/25409
https://github.com/ppy/osu-framework/assets/4923655/aa025169-8d57-4571-9d74-d6095d30f924

IncrementalBSplineBuilder: rewrite algorithm with many improvements 

---

osu.Framework.Tests/Audio/AudioCollectionManagerTest.cs
osu.Framework.Tests/Audio/AudioTestHelper.cs
osu.Framework.Tests/Audio/BassTestComponents.cs
osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs
osu.Framework.Tests/Audio/TrackVirtualTest.cs

Noticed the problem in https://discord.com/channels/188630481301012481/589331078574112768/1174627793221472276.
Updates all audio tests that start a new audio thread to use the `RunOnAudioThread()` logic from #5946.
Previously, some tests had custom logic that would silence exceptions.

Use better `RunOnAudioThread()` logic in audio tests

---

osu.Framework/Utils/Interpolation.cs

Currently we don't have out-of-the-box support for that and I would like to have it there rather than making a copy with `IInterpolable` (also including the fact that `Vector3` isn't something out of ordinary)

Add support for `Vector3` interpolation

---

osu.Framework/Platform/GameHost.cs

Original [discord thread](https://discord.com/channels/188630481301012481/589331078574112768/1175771698814013520) that sparked this change.
When the window is restored from minimised state, it'll show the old frame (with DX11) until a new frame is rendered.
This change visibly reduced the CPU and GPU usage (GPU goes to 0%) when the window is minimised, previously I'd only see a small reduction in GPU usage.

Don't draw when the window is minimised

---

.config/dotnet-tools.json

Not sure what broke this.
Failure: https://github.com/ppy/osu-framework/actions/runs/6924828290/job/18836758832
Fix reference: https://discord.com/channels/188630481301012481/589331078574112768/1176026954965729321
Testing: https://github.com/peppy/osu-framework/actions/runs/6926220112/job/18838045454

Fix android pack action failing due to missing OpenJDK

---

osu.Framework/Utils/PathApproximator.cs

Among other things, https://github.com/ppy/osu/pull/25409 permits sliders to contain segments which are B-splines of degree 3. To preserve the possibility of backporting such sliders to stable via the compatibility export function, expose a method to convert B-splines of arbitrary degree to piecewise Bezier curves.
The logic was already part of the `BSplineToPiecewiseLinear()` conversion method and has been largely unchanged.

Expose B-spline to Bezier conversion method

---

osu.Framework/Utils/IncrementalBSplineBuilder.cs

This PR makes the following improvements to the incremental BSpline builder:
1. the last vertex of the BSpline now follows the mouse perfectly without any jitter. Vertices are still inserted with `FD_EPSILON * 2` spacing to ensure derivatives are computed stably; only the currently last vertex is affected by this change.
2. the control point spacing algorithm has been tweaked to prevent global dependencies along the path. This gets rid of jittering that the previous batch of "improvements" introduced. See comparison videos below.
Before this PR:
https://github.com/ppy/osu-framework/assets/4923655/69f60092-f24f-4f62-a296-143a3058fe2c
After this PR:
https://github.com/ppy/osu-framework/assets/4923655/8d8c72d0-0822-4364-8929-1c2e9598c6d2

Improve incremental bspline builder

---

.config/dotnet-tools.json
.github/workflows/ci.yml
.github/workflows/deploy-pack.yml

The previous fix in reality did nothing because the [two](https://github.com/peppy/osu-framework/actions/runs/6926220112/job/18838045454) [runs](https://github.com/ppy/osu-framework/actions/runs/6927288952/job/18840885827) that passed happened to run on the version of the runner that was _not_ broken, namely 20231029.1.0. Today's run [ran on 20231115.2.0](https://github.com/ppy/osu-framework/actions/runs/6939325341/job/18876480850#step:1:9) and thus broke again.
[Attempt at evidence that this time it will be fixed.](https://github.com/bdach/osu-framework/actions/runs/6941641330/job/18882900940#step:1:9)
This will need to be done game-side too, but I will do that after the framework tag is fixed, because right now game-side builds are failing due to the nuget package not existing (which it …

Attempt to fix android compile failures due to invalid java version again

---

osu.Framework.Benchmarks/BenchmarkTextBuilder.cs
osu.Framework/IO/Stores/FontStore.cs
osu.Framework/IO/Stores/GlyphStore.cs
osu.Framework/Text/ITexturedGlyphLookupStore.cs

Offers a bit more flexibility for custom implementations of font lookups. To be used osu! side to allow lookups of raw sprites. I may consider bringing that functionality over to the framework side after it has been proved reliable.
Probably best to wait for the osu! side PR to see how this works.

Allow using custom `ITexturedGlyphLookupStore`s as texture sources

---

osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs
osu.Framework.Tests/Visual/Graphics/TestSceneShaderStorageBufferObject.cs
osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
osu.Framework.Tests/Visual/Graphics/TestSceneVertexBatching.cs
osu.Framework/Graphics/Audio/WaveformGraph.cs
osu.Framework/Graphics/BufferedDrawNode.cs
osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
osu.Framework/Graphics/DrawNode.cs
osu.Framework/Graphics/Drawable_ProxyDrawable.cs
osu.Framework/Graphics/Lines/Path_DrawNode.cs
osu.Framework/Graphics/Rendering/DepthValue.cs
osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
osu.Framework/Graphics/Rendering/IRenderer.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Rendering/Vertices/TexturedVertex2D.cs
osu.Framework/Graphics/Sprites/BufferedContainerView.cs
osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
osu.Framework/Platform/GameHost.cs

Curious what people's thoughts are on this.
Right now, we have a dichotomy between the implementations of `Draw()` and `DrawOpaqueInternal()` where one batches everything including children inside `Draw()` but the other exposes `DrawOpaqueInternalSubtree()` for this purpose. 
This results in other weirdness, like `Draw()` being `public` and `DrawOpaqueInternal()` being protected. As a consumer of the framework, there is no way to correctly implement `DrawOpaqueInternal()` if needing to draw a child, prior to this PR.
My eventual goal is to be able to wrap both of these draw functions in some way that indicates to the renderer what `DrawNode` is currently being drawn, for example something like...
```csharp
class DrawNode
{
protected internal static void DrawOther(DrawNode node, IRenderer …
```

Cleanup `DrawNode` drawing methods

---

osu.Framework.NativeLibs/scripts/ffmpeg/common.sh

As mentioned [here](https://github.com/ppy/osu/discussions/25604#discussioncomment-7740686), there are some beatmaps with WMV2 and VP6 video.
WMV2 is the shorthand (fourcc) for [Windows Media Video 8](https://en.wikipedia.org/wiki/Windows_Media_Video#Versions). [VP6](https://en.wikipedia.org/wiki/VP6) was often used in Flash. A new demuxer is also needed (`asf`) to decode .wmv files.
As per usual, build artifacts available on [my fork](https://github.com/FreezyLemon/osu-framework/actions/runs/7087395991).

FFmpeg: Add VP6 and WMV2 video formats

---

osu.Framework/Audio/AudioManager.cs

Without this, at least on my PC, the BASS device initialisation happens twice. The first time, device matching fails because the first run of `syncAudioDevices` has not occurred yet (scheduled and thread). This causes initialisation to fail matching by name:
https://github.com/ppy/osu-framework/blob/e5a0e4ec0e9a030dbc83ae3fb375a9ebd2e8963b/osu.Framework/Audio/AudioManager.cs#L303-L305
.. and initialise the BASS "no sound" or "default" device unnecessarily.
Then a second callback happens which brings the device into a good state.
Basically, this PR reduces the number of BASS device initialisations on startup from 2 to 1 in many cases.

Fix audio device names not being populated in time for bass device initialisation

---

osu.Framework/osu.Framework.csproj

- Gaomon GM116HD
- Huion Kamvas 22
- VEIKK VK1060PRO
- Wacom CTC-4110WL
- Wacom CTC-6110WL
- Wacom DTH-1320
- Wacom PTU-600U
- XP-Pen Deco M
- Artisul A1201
- Gaomon 1060 Pro 
- Huion H1060P
- Huion H420x
- Huion H950P
- Huion Kamvas 20
- Huion Kamvas Pro 24 (4K)
- Kamvas Pro 13 (2.5k)
- UGEE S640
- Huion Q11K: Fix digitizer specifications
- XP-Pen Star 05 V3: Fix digitizer specifications

Bump OpenTabletDriver to 0.6.4.0

---

osu.Framework/Audio/AudioManager.cs
osu.Framework/Audio/Mixing/AudioMixer.cs
osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs

Hopefully this makes immediate sense.
Splitting this out from WASAPI changes to allow me to use the term "global mixer" more correctly.

Rename concept of "global" mixer with "fallback"

---

osu.Framework.Tests/Audio/BassTestComponents.cs
osu.Framework/Audio/AudioManager.cs
osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
osu.Framework/Graphics/Visualisation/Audio/AudioChannelDisplay.cs
osu.Framework/Threading/AudioThread.cs
osu.Framework/osu.Framework.csproj

This reduces latency from perceivable (25-40ms) to non-perceivable (5-15ms). With this change, the latency on windows actually becomes limited by the update thread rate.
Pushing this as a draft for those interested in testing it ahead of time. I hope to clean up the single `static` usage.
If you wish to test in the mean time, please checkout this PR, build osu! after running `UseLocalFramework.ps1`.

Add low latency initialisation support on windows by directly interacting with WASAPI

---

osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
osu.Framework/Configuration/FrameworkConfigManager.cs
osu.Framework/Platform/SDL2Window.cs
osu.Framework/Platform/SDL2Window_Windowing.cs

- Resolves https://github.com/ppy/osu/discussions/17172
Uses `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS` on desktop (and iOS, but I'm not sure if it does anything).
Mobile isn't really a consideration here, as the OS has full control over "minimising a window".
Added tests that require manually alt-tabbing. Tested on windows 11 with DirectX (seamless transition) and OpenGL legacy (black screen flicker).

Add setting to control automatic minimising on focus loss in fullscreen mode

---

osu.Framework.Android/AndroidGameActivity.cs

As per https://github.com/dotnet/runtime/pull/76250 and https://github.com/dotnet/docs/issues/31423, `System.Environment.SpecialFolder.Profile` since .NET 8 points to `$HOME/Documents` instead of `$HOME`, causing
```
android.runtime.JavaProxyThrowable: [System.IO.DirectoryNotFoundException]: IO_PathNotFound_Path, /data/user/0/com.test.app/files/Documents
```
on startup.
This PR changes it to always target `$HOME`.
Similar change was previously done in https://github.com/ppy/osu-framework/pull/5909/commits/d7ff5d6478ada5017518aa19843f3fdca0d174cf, but android was skipped.

Fix android storage path on .NET 8

---

osu.Framework/Graphics/UserInterface/DropdownHeader.cs

- Addresses https://github.com/ppy/osu/discussions/26175
- Resolves https://github.com/ppy/osu/issues/26211
Regressed in https://github.com/ppy/osu-framework/commit/6d215cf9303c547f57056b69d7f6afcd12f0b66a. Not sure why the change was made in the first place, but it has been reverted here. No signs of breakage as far as I tried.
To briefly explain the issue in the linked thread above, disabled dropdowns handle any platform action received, regardless of whether the dropdown is hovered or not. When pressing left/right arrows anywhere, the actions `MoveBackwardChar`/`MoveForwardChar` are propagated first, and any disabled dropdown present in the scene will handle them, therefore blocking the slider from receiving the key event.

Fix dropdown header handling platform actions when not hovered

---

osu.Framework/Lists/SlimReadOnlyListWrapper.cs

Unsurprisingly no usages of the method anyways (checked only in framework), so shouldn't break anything.
Also replaced `NotImplementedException` with the more correct `NotSupportedException`.

Make `Insert` for `SlimReadOnlyListWrapper` unsupported

---

osu.Framework/Platform/DesktopGameHost.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs

This is something we do on osu!stable and has large gains (for some users) on desktop systems, especially when shared with other heavy applications.
Tested on windows and macOS. Windows works as expected, macOS fails due to lack of permissions. Would appreciate linux testing.
If deemed more appropriate, can be moved to `WindowsGameHost`.

Set process priority of framework window to high when focused

---

osu.Framework.Benchmarks/BenchmarkTransform.cs
osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs

Noticed that this has no reason to be a list. Changing to `HashSet` avoids overheads from list capacity resizing.

Use `HashSet` instead of `List` for temporary check in transform handling

---

osu.Framework.Benchmarks/BenchmarkBindableNumber.cs
osu.Framework/Bindables/BindableNumber.cs

BenchmarkDotNet isn't outputting a summary table, so I'll leave it up to @peppy to provide before/after tales. But the optimisation is pretty standard (see other cases of the same being done in this file).

Reduce allocs when setting value on `BindableNumber` with precision

---

osu.Framework/Input/InputResampler.cs

Benchmark is part of a larger operation and doesn't show the sheer scale of this as it's running in a test at lower input sampling rates. This gets very out of hand with high poll rate devices.
| ![2024-01-07 13 10 29@2x](https://github.com/ppy/osu/assets/191335/497dd07c-63fe-4a48-99f1-1b523c90f589) | ![2024-01-07 13 26 33@2x](https://github.com/ppy/osu/assets/191335/94b2b2f0-c50f-4496-a9c0-5458cc0d7222) |
Alternatives would be `ref List<>` as a parameter or just returning a single `Vector2?` always, but my proposal here offers future flexibility and should be safe based on the only true usage of this method being to immediately handle the returned value.

Remove per-call array allocations from `InputSampler`

---

osu.Framework/Graphics/Sprites/SpriteIcon.cs

Closes https://github.com/ppy/osu-framework/issues/6110
As far as I can tell, there's no visual difference (which is desired behaviour).
| | master | pr |
|---|---|---|
|tests|![test-scene-before](https://github.com/ppy/osu-framework/assets/22874522/97b7b6e4-0554-4733-ae08-15ccecffa0c4)|![test-scene-after](https://github.com/ppy/osu-framework/assets/22874522/6b746706-e073-43ec-9865-feb342315788)|
|test-rotated|![rotation-before](https://github.com/ppy/osu-framework/assets/22874522/8fe871c1-1644-43f6-b4ff-f7e359f7682b)|![rotation-after](https://github.com/ppy/osu-framework/assets/22874522/3306ca7c-7e71-467f-aa01-6be9c0511b08)|
|settings|![settings-before](https://github.com/ppy/osu-framework/assets/22874522/69a1e05a-bcaa-4d06-a859-0ead9f98674c)|![settings-after](https://github.com/ppy/osu-f …

Simplify `SpriteIcon`

---

osu.Framework/Bindables/RangeConstrainedBindable.cs
osu.Framework/Graphics/UserInterface/SliderBar.cs

Was ~200KB/s during gameplay.
Not even going to provide a benchmark, should be obvious.

Remove alloc overhead for `NormalizedValue`

---

osu.Framework.Tests/Visual/Testing/TestSceneNestedGame.cs
osu.Framework/Testing/TestScene.cs

This allows running tests from a headless/benchmark context much easier.
Used in https://github.com/ppy/osu/pull/26422

Expose `RunTestsFromNUnit` as `public`

---

osu.Framework/Input/PassThroughInputManager.cs
osu.Framework/Input/States/TouchState.cs

This one's a bit fiddly, but mostly copying existing examples.
41b7c32cc01fa3a3831e1333cbde3a313f9104c7
| ![2024-01-11 01 08 58@2x](https://github.com/ppy/osu-framework/assets/191335/c6972d7c-c240-48bc-b35b-81d5450b3df3) | ![2024-01-11 01 09 12@2x](https://github.com/ppy/osu-framework/assets/191335/6f25eea7-9b59-402c-94d5-5b547d6ab71d) |
de5ad34538620a8f1b671251295d6c192182ea0c
| ![2024-01-11 02 11 24@2x](https://github.com/ppy/osu-framework/assets/191335/afd87dc0-d7f9-4996-a867-7ceae6418d14) | ![2024-01-11 02 11 35@2x](https://github.com/ppy/osu-framework/assets/191335/2d98f13d-da7c-4eb4-a320-2b8da3b3050b) |
91185b1a504d8a93a5a7c1081e6ffb88deda3f4b
| ![2024-01-11 02 14 …

Reduce input processing overheads in `PassThroughInputManager`

---

osu.Framework/Graphics/Lines/SmoothPath.cs

| ![2024-01-11 00 29 16@2x](https://github.com/ppy/osu-framework/assets/191335/39bf2567-0e07-4243-8326-6ac5633e182b) | ![2024-01-11 00 29 24@2x](https://github.com/ppy/osu-framework/assets/191335/3e1cde0e-dd4c-4073-9f2d-dc0169f9ecfa) |
Could go further and reuse the `Image` but it may cause the unsafe read to get half of the new and old pixels, so I didn't go down that path.

Avoid creating a new texture in `SmoothPath` if the existing one is already the correct size

---

osu.Framework/Graphics/OpenGL/Shaders/GLShaderPart.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs

| ![2024-01-11 05 19 21@2x](https://github.com/ppy/osu-framework/assets/191335/4880d5bc-d609-4912-ac15-9a0cbb39299f) | ![2024-01-11 05 19 17@2x](https://github.com/ppy/osu-framework/assets/191335/fbec9b1c-11dd-4d42-a797-aa288f423f9e) |

Reduce string allocations during shader creation

---

osu.Framework/Timing/FramedClock.cs

| ![2024-01-11 05 33 07@2x](https://github.com/ppy/osu-framework/assets/191335/2397e34a-0222-459d-84a0-de4fa148f87b) | ![2024-01-11 05 40 58@2x](https://github.com/ppy/osu-framework/assets/191335/de51549d-f9ac-4537-848f-a14a41d68226) |

Remove delegate allocation in jitter calculation in `FramedClock`

---

osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

Unused (internal) method that does not need to exist.

Remove `VeldridTexture.Bind()`

---

osu.Framework.Tests/Audio/AudioManagerWithDeviceLoss.cs
osu.Framework/Audio/AudioManager.cs
osu.Framework/Input/Bindings/KeyCombination.cs
osu.Framework/Platform/SDL2Window_Windowing.cs

Minor gains because this is just a one second poll, but is what it is.
| ![CleanShot 2024-01-11 at 05 48 29](https://github.com/ppy/osu-framework/assets/191335/33cf934d-61b4-4e0d-9593-7a7788b575a3) | ![CleanShot 2024-01-11 at 05 47 48](https://github.com/ppy/osu-framework/assets/191335/72674e5d-f2c5-488d-ac02-29f52c5229f4) |
Also fixed a couple of incorrect calls on array building. Check underlying implementation for reasoning (one allocates, other doesn't).

Remove allocations during bass device sync polling operation

---

osu.Framework/Input/Bindings/KeyBindingContainer.cs
osu.Framework/Input/Bindings/KeyCombination.cs
osu.Framework/Input/ButtonEventManager.cs

Overall gains are pretty substantial. All testing done with 13 keystrokes. Ignore overall allocations as the runtime of tests was significantly different.
| ![CleanShot 2024-01-11 at 07 44 09](https://github.com/ppy/osu-framework/assets/191335/4862e994-fb54-44a1-91d6-5265bb541897) | ![CleanShot 2024-01-11 at 07 44 17](https://github.com/ppy/osu-framework/assets/191335/1574e0e3-1c05-490e-b167-db842dca03ed) |
---
94b4b2435aa692d79274fae680b31ceb1dfc8ecb Remove allocation overhead in button propagation flow
| ![CleanShot 2024-01-11 at 07 40 36](https://github.com/ppy/osu-framework/assets/191335/3d99afd4-a2aa-408e-87b7-c552205b4cdf) | ![CleanShot 2024-01-11 at 07 41 …

Reduce allocation overhead for keyboard / binding / button handling

---

osu.Framework.Tests/Input/KeyCombinationTest.cs
osu.Framework/Input/Bindings/KeyCombination.cs

This class may require some test coverage. Just pushing out for immediate visibility.

Fix `KeyCombination` throwing when duplicates are fed in

---

osu.Framework/Platform/OsuTKWindow.cs

Closes https://github.com/ppy/osu/issues/26506.
See https://github.com/dotnet/runtime/issues/26880 for description of why the previous reasonable-looking code was in fact a footgun.

Fix incorrect implementation of `OsuTKWindow.Displays`

---

osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

Closes https://github.com/ppy/osu-framework/issues/6131.
Tried to think of a way to avoid this at a higher level but not really sure we can.

Fix runaway texture uploads when window is minimised with frame statistics visible

---

osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
osu.Framework/Graphics/Pooling/DrawablePool.cs

This has caught me twice to date. It still works roughly correctly, but won't initialise the pool to the correct default size, taking away the startup performance benefits of pooling.
Previously the pool would return drawables correctly but it would not initialise the pool to correct default size, causing overheads on drawable retrieval (usually on update thread).

Guard against potential usage of `DrawablePool` without being added to hierarchy

---

osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
osu.Framework/Input/InputManager.cs

- Closes https://github.com/ppy/osu/issues/23555
`KeyBindingContainer` gets into a weird state when handling input while it's not loaded. Since it's not loaded, `KeyBindings` would be null since it only gets populated in `LoadComplete`, so no press/release events are propagated to children for the first key. However, the key gets stored in `pressedInputKeys`, and later on, when the next key is pressed, the old key incorrectly becomes processed as a new binding as well, causing the double-press issue.
`KeyBindingContainer` was not supposed to enter the input queue if it's not fully loaded in the first place, but turns out `InputManager` was incorrectly adding it (by bypassing `ShouldBeConsideredForInput`).

Fix `InputManager` including non-loaded direct children in input queue

---

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
osu.Framework.Tests/Platform/UserInputManagerTest.cs
osu.Framework/HostOptions.cs
osu.Framework/Platform/DesktopGameHost.cs

Resolves https://github.com/ppy/osu-framework/issues/6127
Previously, the IPC port used for multiple instances of a single osu!framework app was hardcoded in the IPC host itself, effectively making it so that _all osu!framework apps_ would share the same IPC port, which obviously cannot work.
To allow multiple osu!framework apps to utilise IPC concurrently, `BindIPC` has thus been replaced by `IPCPort`.
- Setting `IPCPort = null` is equivalent to `BindIPC = false`.
- Setting `IPCPort` to a non-null value is equivalent to `BindIPC = true` *and* will force the use the specific port provided.
Note that it is advised to use a "user port" (in the range of 1024-49151) as per RFC 6335.

Make IPC port configurable via `HostOptions`

---

.idea/.idea.osu-framework/.idea/vcs.xml
osu.Framework.Tests/Input/KeyboardInputTest.cs
osu.Framework.Tests/Input/MouseInputTest.cs
osu.Framework.Tests/Input/TouchInputTest.cs
osu.Framework/Input/KeyEventManager.cs
osu.Framework/Input/MouseButtonEventManager.cs
osu.Framework/Input/TouchEventManager.cs

Drawables in the `ButtonDownInputQueue` could become unrooted between the button down event and a drag start event or touch move event. 
If a parent of a drawable gets removed, the children will keep `IsAlive` true forever, so checking for `IsAlive` is not sufficient.
Failing tests included. The test for the key repeat input does not fail before my fixes, but I added it for good measure.

Fix DragStart and TouchMove input events possibly being handled by unrooted drawables

---

osu.Framework.Tests/Clocks/InterpolatingFramedClockTest.cs
osu.Framework.Tests/FlakyTestAttribute.cs

Been failing for quite some time now.

Add flaky test attribute and mark `CanSeekForwardOnInterpolationFail` as flaky

---

osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TemplateGameTestScene.cs
osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/FlappyDonTestScene.cs

Noticed after making a template. Same fix as https://github.com/ppy/osu-framework/commit/e08c8827ed6914ed0257c5af5f77eab443310fe3.

Fix `TemplateGameTestScene` showing up in test browser

---

osu.Framework.Android/AndroidGameView.cs

Android apparently has a [separate API for "window cutouts"](https://developer.android.com/develop/ui/views/layout/display-cutout), i.e. for cameras and the like, and a [separate API for "rounded corners"](https://developer.android.com/develop/ui/views/layout/insets/rounded-corners), i.e. devices where the rounded corners of the display will cause some areas of the theoretically-rectangular display to be obscured. Because there is no engineering like overengineering, right? Bonus points for them being usable at different API levels, too.
Disclaimer that this does absolutely nothing on my one test device that has a rounded display and a high enough API level, but honestly it may be a device issue since it's not even returning `true` for `WindowInsets.IsRound`. Maybe it'll help someone, no …

Include rounded corner radius in android safe area implementation

---

.gitignore

This file just shows the last selected android device:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
<component name="deploymentTargetDropDown">
<value>
<entry key="osu.Framework.Android">
<State />
</entry>
<entry key="osu.Framework.Tests.Android">
<State>
<runningDeviceTargetSelectedWithDropDown>
<Target>
<type value="RUNNING_DEVICE_TARGET" />
<deviceKey>
<Key>
<type value="SERIAL_NUMBER" />
<value value="***" />
</Key>
</deviceKey>
</Target>
</runningDeviceTargetSelectedWithDropDown>
<timeTargetWasSelectedWithDropDown value="2024-01-18T17:26:25.696017100Z" />
</State>
</entry>
</value>
</component>
</project>
```

Ignore autogenerated .idea android file

---

osu.Framework/Graphics/Containers/FlowContainer.cs

The issue was caused [by this](https://github.com/ppy/osu-framework/blob/f6feea4b08de3a5182fa15f6913edfcffeceb267/osu.Framework/Graphics/UserInterface/TabControl.cs#L503).
So as far as my understanding goes: `FlowContainer` was never expecting it's children to be invalidated during validation process and at the end it was validating every frame.
Timeline of events:
1. `FlowContainer.UpdateAfterChildren` checking if it needs validation
2. `childLayout` invalidated? validate it and invalidate `layout`
3. `layout` is invalidated - call `performLayout()`
4. `performLayout()` calls `ComputeLayoutPositions()` down the line
5. `ComputeLayoutPositions()` is overriden by `TabFillFlowContainer` and changes children Y, which triggers `childLayout` to be invalidated again (even if it was validated in …

Fix allocation overhead in `TabFillFlowContainer` when it can't fit all the items

---

osu.Framework/Logging/Logger.cs

The flow in `GameHost` ensures that the game/version identifiers are set before `Logger.Storage` is set. Unfortunately, until now any call to the static `Logger.Log` would immediately materialise the headers into their final string form. A stray log call before `GameHost.Run` could result in less-than-optimal headers.
This can be seen in osu!'s runtime log from an [early log call](https://github.com/ppy/osu/blob/1e3c332658a320fb2dbf49e4a97e2927cafc4dcc/osu.Desktop/Program.cs#L124).
Before:
```
2024-01-17 15:34:40 [verbose]: ----------------------------------------------------------
2024-01-17 15:34:40 [verbose]: runtime Log for dean (LogLevel: Debug)
2024-01-17 15:34:40 [verbose]: Running game unknown on .NET 6.0.25
2024-01-17 15:34:40 [verbose]: Environment: macOS (Unix 14.3.0), 8 cores …
```

Write log header later to ensure game identifiers are present

---

osu.Framework/Testing/SoloAttribute.cs
osu.Framework/Testing/TestBrowser.cs

I've been wanting this for years. Discussed implementation details recently with smoogi and agreed that getting something very simple implemented would be beneficial to test development efficiency.
Basically, rather than commenting out 100 tests in a method where you want to test one specific test repeatedly (commonly using hot reload), you can now add `[Solo]` to the test in question and the runner will ignore the rest.
This has no effect when tests are run from nunit, as you may expect.

Add the ability to solo a test in visual testing using `[Solo]` attribute

---

osu.Framework.Benchmarks/BenchmarkBindableList.cs
osu.Framework/Bindables/IBindableList.cs

Saw this one come up off-hand, and I think it's a pretty easy gun to shoot yourself in the foot given that we advise exposing as `IBindableList<T>` for read-only usages. It's simple enough to fix in this case since the hierarchy is pretty concrete.
Before:
|             Method |     Mean |     Error |    StdDev |   Gen0 | Allocated |
|------------------- |---------:|----------:|----------:|-------:|----------:|
|          Enumerate | 1.225 us | 0.0028 us | 0.0023 us |      - |         - |
| EnumerateInterface | 6.546 us | 0.0156 us | 0.0138 us | 1.9073 |    4000 B |
After:
|             Method |     Mean |     Error |    StdDev | Allocated |
|------------------- |---------:|----------:|----------:|----------:|
|          Enumerate | 1.241 us | 0.0107 us | 0.0089 us |         - |
| …

Fix `IBindableList.GetEnumerator()` boxing and allocating

---

osu.Framework/Statistics/DotNetRuntimeListener.cs

```
1>DotNetRuntimeListener.cs(137,32): Warning CS8500 : This takes the address of, gets the size of, or declares a pointer to a managed type ('TypedReference')
```
I'd use `Unsafe.Cast<>` but it can't be done because `TypedReference` contains a `ByReference<T>` where `T` is not marked as `unmanaged`, even though the specific usage in the class is a `byte` which is unmanaged.
`TypedReference.GetTargetType()` is equivalent to `__reftype` internally. Just cleaning this up to not use undocumented features.

Fix build warning

---

osu.Framework.Benchmarks/BenchmarkBindableList.cs
osu.Framework/Bindables/IBindableList.cs

- Closes https://github.com/ppy/osu/issues/26809
Android [decided it didn't like this optimisation](https://sentry.ppy.sh/organizations/ppy/issues/?end=2024-01-30T17%3A11%3A59&groupStatsPeriod=auto&project=2&query=firstRelease%3Aosu%402024.130.2+os.name%3AAndroid&referrer=issue-list&sort=freq&start=2024-01-30T11%3A10%3A00). Not exactly surprised given the track record we have with these sorts of tricky changes (something inside mono _reeeeeally_ doesn't like interface level trickery).

Revert "Fix `IBindableList.GetEnumerator()` boxing and allocating"

---

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
osu.Framework/Graphics/Containers/RearrangeableListContainer.cs

Fix rearrangeable lists don't react on collection `Move` events

---

osu.Framework.Benchmarks/BenchmarkSlimReadOnlyDictionary.cs
osu.Framework.Benchmarks/BenchmarkSlimReadOnlyList.cs
osu.Framework/Extensions/ListExtensions/ListExtensions.cs
osu.Framework/Lists/SlimReadOnlyDictionaryWrapper.cs

I find it pretty silly that this is still a thing even going into .NET 8. Hoping to use this for https://github.com/ppy/osu/pull/26863.
|                   Method |     Mean |    Error |   StdDev |    Gen0 | Allocated |
|------------------------- |---------:|---------:|---------:|--------:|----------:|
|               Dictionary | 35.05 us | 0.692 us | 1.035 us |       - |         - |
|     DictionaryAsReadOnly | 91.75 us | 1.833 us | 4.212 us | 22.9492 |   48000 B |
| DictionaryAsSlimReadOnly | 34.67 us | 0.690 us | 1.345 us |       - |         - |
|                     Keys | 28.73 us | 0.079 us | 0.074 us |       - |         - |
|           KeysAsReadOnly | 81.24 us | 0.101 us | 0.095 us | 19.0430 |   40000 B |
|       KeysAsSlimReadOnly | 28.75 us | 0.056 us | 0.052 us |       - | …

Add readonly dictionary wrapper that removes enumerator alloc

---

osu.Framework.Benchmarks/BenchmarkWaveform.cs
osu.Framework/Audio/Track/Waveform.cs

I found this issue a bit back while testing performance of Waveform implementation of #6002.
Having `data.Dispose()` in my code hindered the benchmarks from running, and it seemed that the benchmarks used a single stream through its entire session.
I assumed that the stream gets disposed somewhere else, but I couldn't find any code for that. This could be my oversight, but writing this PR didn't take much time anyway...

Fix Waveform not disposing Stream

---

osu.Framework/Platform/Windows/WindowsGameHost.cs

This is in a try/catch because it can fail, and is only set on windows because UTF-8 is not the default there. Emoji already works fine when running unit tests from Rider, so setting this in `DesktopGameHost` is not needed.
Before (Rider Run/Debug on Windows):
After:

Set UTF-8 console encoding on windows

---

osu.Framework.Android/Input/AndroidMouseHandler.cs
osu.Framework.Android/Input/AndroidTouchHandler.cs

Fixes some inspections from the .NET 8 upgrade as seen in https://github.com/ppy/osu-framework/actions/runs/7754422132.
Fixes warnings such as the following:
> This call site is reachable on: 'Android' 21.0 and later. 'MotionEventButtonState.StylusPrimary' is only supported on: 'android' 23.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
Those warnings are new in .NET 8 because enum values are now also annotated.

Fix some .NET 8 CA1416 android inspections

---

osu.Framework/Platform/Windows/Native/Input.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

This exists only on win8+: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowfeedbacksetting#requirements
Before:
[1707225741.runtime.log](https://github.com/ppy/osu-framework/files/14180973/1707225741.runtime.log)
After:

Ignore missing feedback api

---

osu.Framework.Android.props
osu.Framework.Android/AndroidExtensions.cs
osu.Framework.Android/AndroidGameView.cs
osu.Framework.Android/osu.Framework.Android.csproj

This replaces obsolete calls with AndroidX compat classes that allow using new-style APIs on older android platforms.
Eg. [Display.getRealSize()](https://developer.android.com/reference/android/view/Display#getRealSize(android.graphics.Point)) is deprecated on API 31+ and the suggested alternative is [WindowManager.getCurrentWindowMetrics()](https://developer.android.com/reference/android/view/WindowManager#getCurrentWindowMetrics()) (API 30+), so instead of having to call the old API on old platforms and the new API on new platforms, we use AndroidX [WindowMetricsCalculator](https://developer.android.com/reference/androidx/window/layout/WindowMetricsCalculator) which does that for us.
`Microsoft.Maui.Essentials` is using `Xamarin.AndroidX` libraries ([see …

Fix obsolete code in Android safe area handling by using AndroidX

---

osu.Framework/Extensions/ExtensionMethods.cs

Benchmark:
|        Method |     Mean |     Error |    StdDev |   Gen0 | Allocated |
|-------------- |---------:|----------:|----------:|-------:|----------:|
|     StreamMD5 | 2.645 μs | 0.0151 μs | 0.0134 μs | 0.0687 |     296 B |
| StreamMD5_New | 2.499 μs | 0.0105 μs | 0.0093 μs | 0.0381 |     160 B |
|     StreamSHA | 1.649 μs | 0.0132 μs | 0.0124 μs | 0.0935 |     392 B |
| StreamSHA_New | 1.568 μs | 0.0128 μs | 0.0114 μs | 0.0572 |     240 B |

Use new MD5/SHA.HashData(Stream) overload

---

osu.Framework/Graphics/Containers/GridContainer.cs

Recomputing `GridContainer`'s layout is pretty allocation-heavy, which is happening during `DrawInfo` invalidation (common case - position change such as scrolling through overlays, comments, etc.).
Changing invalidation from `DrawSize` to `Invalidation.DrawInfo | Invalidation.RequiredParentSizeToFit` was a deliberate choice in https://github.com/ppy/osu-framework/pull/1139/commits/b0f4473ad0acaaabb718a385a6be47f4b1d304ed since looks like at the time of it's implementation nested grids weren't working properly.
However currently it seems like everything works fine somehow: tests are passing and as far as I can tell everything is good osu-side.
Also [FlowContainer](https://github.com/ppy/osu-framework/blob/d1a15e402157fcf8703cfd048b872c0bb0c37ce4/osu.Framework/Graphics/Containers/FlowContai …

Invalidate `GridContainer` only on DrawSize change

---

osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownCodeBlock.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs

- Closes https://github.com/ppy/osu/issues/27194
We commonly use the fenced style for code blocks (the ` ``` ` symbol), but there exists another style for code blocks in markdown, known as [indented code blocks](https://www.jetbrains.com/help/hub/markdown-syntax.html#indented-code-blocks). 
Markdig already handles everything for us and outputs the above as `CodeBlock` objects, but our current implementation was handling `FencedCodeBlock` specifically. Both styles render similarly, so I generalised the implementation to read from `CodeBlock`s instead of `FencedCodeBlock`s.
`CodeBlock` is a superclass of `FencedCodeBlock`, so this PR doesn't have to do extra logic for `FencedCodeBlock` objects.

Generalise markdown code block implementation to support indented style

---

osu.Framework/Configuration/RendererType.cs
osu.Framework/Platform/GameHost.cs

Spurred by people using this renderer, likely because "legacy" has a bad connotation associated with it (e.g. https://discord.com/channels/188630481301012481/1097318920991559880/1209220240383418438).
This forces `GLRenderer` ("legacy") to be used even when the `OpenGL` renderer type is selected. We will never be using Veldrid-GL because it allocates a ton, and we can't really make it efficient due to the way o!f works (except until https://github.com/ppy/osu-framework/pull/6190, but even then I wouldn't use it).
There will be a second change osu! side to disable the renderer from being shown as an option.
This also disables Vulkan as a fallback option - it's unstable at least in the way implemented via `VeldridRenderer`. It'll perhaps return with …

Remove Veldrid-OpenGL renderer, always use GLRenderer

---

osu.Framework/Logging/Logger.cs
osu.Framework/Platform/GameHost.cs

Instead, `NewEntry` is cleared only when the `GameHost` is disposing.
This allows using `Logger.Flush()` when [exporting logs from osu!](https://github.com/ppy/osu/blob/d2990170d021f2caee2c6e66368f07792c7ac53c/osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs#L96), the specific use case is to log global statistics:
```cs
GlobalStatistics.OutputToLog();
Logger.Flush();
// create the compressed-logs.zip etc.
```
Clearing `NewEntry` when exporting logs is undesirable.

Don't clear `Logger.NewEntry` handlers when flushing

---

osu.Framework/Graphics/Performance/PerformanceOverlay.cs

|master|pr|
|---|---|
|![master](https://github.com/ppy/osu-framework/assets/22874522/251bbf86-1207-4ddc-be9a-116408af75b5)|![pr](https://github.com/ppy/osu-framework/assets/22874522/c6fff6d4-c335-4607-bcee-f6817a02cbe5)|

Reduce allocations in `PerformanceOverlay` while in expanded state

---

osu.Framework/Graphics/OpenGL/Batches/GLLinearBatch.cs
osu.Framework/Graphics/OpenGL/Buffers/GLLinearBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/GLQuadBuffer.cs
osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
osu.Framework/Graphics/OpenGL/GLRenderer.cs
osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
osu.Framework/Graphics/Rendering/Renderer.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridLinearBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridQuadBatch.cs
osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
osu.Framework/Graphics/Veldrid/Buffers/IVeldridVertexBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridMetalVertexBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
osu.Framework/Graphics/Veldrid/VeldridRenderer.cs

- Adds `Renderer.DrawVertices()`, which is the method that binds the global UBO.
- Makes `globalUniformBuffer` private.
- Adds `Renderer.BindUniformBuffer()`, which does the state tracking/de-duping of flushes around UBO bindings.
- A few other misc cleanups.

Cleanup common Renderer methods

---

osu.Framework.Benchmarks/BenchmarkAggregateBindable.cs
osu.Framework/Bindables/AggregateBindable.cs
osu.Framework/Bindables/Bindable.cs
osu.Framework/Bindables/IBindable.cs

The benchmarks are below, but only the 2nd result is the significant one to me because it removes a `WeakReference` alloc. It's still not zero, though, and the other alloc is very hard/impossible to remove with the current structure of things.
Master:
|          Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|---------------- |----------:|----------:|----------:|-------:|----------:|
| AddRemoveSource |  2.111 us | 0.0413 us | 0.0776 us | 0.2098 |   1.72 KB |
|        SetValue | 20.122 us | 0.2580 us | 0.2413 us | 0.5493 |   4.69 KB |
Without allocating weak references:
|          Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|---------------- |----------:|----------:|----------:|-------:|----------:|
| AddRemoveSource |  1.760 us | 0.0352 us | …

Reduce allocs in `AggregateBindable`

---

osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
osu.Framework.Tests/Visual/Performance/TestSceneVertexUploadPerformance.cs
osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs
osu.Framework/Graphics/Cursor/CursorContainer.cs
osu.Framework/Graphics/UserInterface/CircularProgress.cs

There's zero to no reason to have it `Bindable` imo.
Performance impact is tiny, though in cases such as `TestSceneVertexUploadPerformance` it's quite noticeable (which is unrealistic, but still).
|master|pr|
|---|---|
|![master](https://github.com/ppy/osu-framework/assets/22874522/c269595e-6c4e-4019-883f-cdd6c943ab9c)|![pr](https://github.com/ppy/osu-framework/assets/22874522/96ddfa2b-981e-4ba6-bafb-1e75f3812a42)|

Remove bindable from `CircularProgress`

---

osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
osu.Framework/Graphics/Rendering/Renderer.cs

Prereqs:
Since the pre-req PR adds a common `DrawVertices()` method, we can now update the global UBO as late as possible - right before vertices need to be drawn.
The easiest way to see the difference is by using the GL renderer and noticing the reduction in the `Draw.UniformUpl` statistic. In `TestSceneTextFlow` it reduces uploads from 54 -> 28. This may lead to a minor performance increase.  
The Veldrid implementation does its own similar late-upload, which _could_ be removed but isn't done in this PR.
_In general_ though, this should slightly increase performance (not benchmarked) just from reducing struct copies.

Reduce frequency of global UBO changes

---

osu.Framework/Logging/Logger.cs

In an edge case scenario, this could throw.
```
----------------------------------------------------------
runtime Log for dean (LogLevel: Debug)
Running osu-server-spectator unknown on .NET 8.0.2
Environment: macOS (Unix 14.3.0), 8 cores 
----------------------------------------------------------
2024-02-28 08:49:26 [verbose]: Cycling logs failed (System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/dean/Projects/osu-server-spectator/osu.Server.Spectator/Logs'.
2024-02-28 08:49:26 [verbose]: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
2024-02-28 08:49:26 [verbose]: at System.IO.Enumeration.FileSystemEnumerator`1.Init()
2024-02-28 08:49:26 [verbose]: at …
```

Fix first call to `cycleLogs` failing due to directory not existing

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Extensions/ExtensionMethods.cs
osu.Framework/Extensions/StreamExtensions.cs
osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
osu.Framework/Graphics/DrawInfo.cs
osu.Framework/Graphics/Textures/TextureUpload.cs
osu.Framework/IO/Stores/RawCachingGlyphStore.cs
osu.Framework/Physics/RigidBodyContainer.cs
osu.Framework/Statistics/DotNetRuntimeListener.cs
osu.Framework/Utils/MathUtils.cs

The BCL versions are generally safer and faster.

Use new BCL APIs from .NET 7/8

---

osu.Framework/Graphics/Veldrid/Pipelines/BasicPipeline.cs
osu.Framework/Graphics/Veldrid/Pipelines/GraphicsPipeline.cs
osu.Framework/Graphics/Veldrid/VeldridStagingResourcePool.cs
osu.Framework/osu.Framework.csproj

Prereqs:
The current logic makes this assumption:
```csharp
// Iterate backwards to find the last signalled fence, which can be considered the last completed execution.
```
This is not actually correct because command buffers/command lists aren't guaranteed to finish sequentially. In other words, suppose two command buffers `A` and `B` are submitted in turn, it is generally guaranteed for all graphics APIs that the execution of `A` **starts** before `B`, but it is _not_ guaranteed that `A` **finishes** before `B`.
So the most important parts of this change are:
- Calling `BasicPipeline.ExecutionFinished` with _only_ the specific execution that finished.
- Changing `VeldridStagingResourcePool` to only free resources with the specific execution index from above.
The rest is fluff - …

Track Veldrid staging resources per-frame

---

osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs

This could cause problems if the object is resurrected. It's not the proper disposal pattern.

Fix incorrect disposal pattern

---

osu.Framework/Graphics/Rendering/Deferred/DeferredUniformBuffer.cs

I happened upon this by total accident. I don't have a reliable way to reproduce this, so I hope the changes make sense on their own.
Because the list isn't cleared, it would keep increasing in size over time and eventually take down the game. For me, this happened abruptly. Also disposal wasn't implemented...
As a side note, I wish to implement this entire flow better in the future but I haven't found a way yet.

Fix over time degradation of deferred renderer performance

---

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs

- Closes https://github.com/ppy/osu-framework/issues/6202
I intend for this to be a somewhat temporary change because this entire thing needs to be rewritten... As far as I can tell we're not relying on effect priorities in osu! (cc @nekodex ).
We've had issues with `FXSetPriority` segfaulting the test runner in the past, but it has not been reported to be doing the same in-game: https://github.com/ppy/osu/discussions/27338
I haven't been able to repro this in osu!framework, but, under pipewire the game should segfault when entering `PlayerLoader` with the following diff applied:
```diff
diff --git a/osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs b/osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
index 2605a84008..1ff9a69fbc 100644
--- …
```

Remove effect prioritisation to fix segfaults

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTabControlEvents.cs
osu.Framework/Graphics/UserInterface/TabControl.cs

- See https://github.com/ppy/osu/pull/27448 for previous discussion
The abstraction may look a little bit too much, but I've been trying to find a middle-ground between code readability and simplicity of structure. 
The previously existing `SelectTab` method is supposed to do all that's necessary for the tab selection to be changed, without necessarily being related to user action, so I've renamed it to `UpdateTabSelection`.
I've also introduced two methods, `SelectTab` and `SelectItem`, the former is for internal use by `TabItem` click event to update tab selection and trigger user event, meanwhile the latter is for external use by calling it with the target item to update tab selection and trigger user event as well (e.g. osu! calling the method when changing editor screen mode, so that …

Add event handler for user change of `TabControl` tab selection

---

osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
osu.Framework/osu.Framework.csproj

- Includes fix for https://github.com/libsdl-org/SDL/issues/9283
- Adds + uses `SDL_GetWindowSizeInPixels` (https://github.com/ppy/SDL2-CS/issues/181).
- In SDL3, this function replaces the `GetDrawableSize()` methods (see: https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_metalh).
- Although the `GetDrawableSize()` methods use this as a fallback pathway, this should also be a stable API in SDL2.

Update SDL2 package + use `SDL_GetWindowSizeInPixels`

---

osu.Framework.NativeLibs/scripts/ffmpeg/build-linux.sh
osu.Framework.NativeLibs/scripts/ffmpeg/fix-binutils-2.41.patch

I explain the rationale behind this change in #6154.
The included patch is necessary for local builds on some distros, and it will become necessary on more distros (and CI) as binutils gets updated (ver 2.41 breaks the ffmpeg build).
Note that the new NativeLibs version will cause the current logic to not find the new libraries. See the linked PR for the required logic change.

FFmpeg Linux binaries: Include version in file name

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

In most common text input fields that I've tested (Chrome, Firefox, Word, etc.), a left/right cursor movement while text is selected will place the cursor on the left/right border of the selection.
https://github.com/ppy/osu-framework/assets/47010459/9f6ee6fd-e0b5-44e8-9449-a089ee73d585
Currently, o!f's `TextBox` treats these cursor movements as... just regular movements. This can lead to some weird/unexpected cursor placements when coming out of selections.
https://github.com/ppy/osu-framework/assets/47010459/65ab1d54-c72d-49ce-a2a4-044a764664b2
These changes bring the behavior closer to what is usually seen in other programs.
https://github.com/ppy/osu-framework/assets/47010459/5a0f22a7-9011-45cc-bf59-149182c1d01a
Behavior when moving along word borders is also changed. Different …

Tweak behavior of cursor movement while text is selected to better match expectations

---

osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
osu.Framework/Graphics/Containers/TextChunk.cs

- Closes https://github.com/ppy/osu/issues/10085
- Closes https://github.com/ppy/osu/issues/14837
I'm not really considering the performance implications of this, just looking to get a baseline more-correct behaviour in place.
The change is basically a best-effort heuristic, although I did use a slightly smarter split method for CJK to attempt to ensure no hanging punctuation.

Split words on more characters in text flow container

---

osu.Framework/Platform/SDL2/SDL2ControllerBindings.cs
osu.Framework/Platform/SDL2Window_Input.cs

In SDL3, controller bindings are handled differently so the existing `Get{Axis,Button}ForIndex()` can't be implemented (eg. a joystick button can map to a gamepad axis, but that method expects each axis to be bound to an axis; ditto for button).
Instead, the methods have been changed to `IsJoystick{Axis,Button}Bound()` which can work in SDL3, and doesn't change semantics for consumers, which were only checking if the axis/button was bound or not.
This PR also includes minor cleanup that just renames things.

Prepare `SDL2ControllerBindings` class for SDL3

---

osu.Framework/Input/Handlers/Tablet/TabletDriver.cs

Noticed when working on something tablet-related.
`Dispose` has a new keyword since the base class doesn't have it virtual and is from an external package (i.e. `OpenTabletDriver`).
Before:
After:

Fix tablet driver log output subscription not unsubscribing after disposing/disabling

---

osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs

No reason for this to be unused. Non-default values are never used right now.

Fix ChannelGetPosition param not being used

---

osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs
osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs

After a tablet is plugged in for the first time, "No tablet detected!" and the faq link would never show again when no tablet is connected.
`tablet.Value` is potentially null as said in the xmldoc so made it that way, probably regressed somewhere. `TabletInfo` and `ITabletHandler`'s xmldoc says:
https://github.com/ppy/osu-framework/blob/2ec0642943c077e8ebfb1aa58e4bb9971faee640/osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs#L11
but have no idea what the removal refactor would look like. Just to note because the changes are relevant to those classes/interfaces.
The gifs below show me plugging and unplugging two different tablets:
| --- | --- |
| ![C2GBCp91tT](https://github.com/ppy/osu-framework/assets/35318437/3fbda546-f86d-4e09-8bc1-e8f4a36fccbd) | …

Fix tablet info not clearing when unplugged

---

osu.Framework.Tests/Bindables/BindableNumberTest.cs
osu.Framework/Bindables/BindableNumber.cs

RFC. Closes https://github.com/ppy/osu/issues/27847.
Didn't really benchmark this as I consider it a basic correctness issue, but will do on request. Game-side units tests pass.

Perform rounding to `Precision` in `BindableNumber` on `decimal` to avoid rounding error accumulation

---

osu.Framework/Platform/Windows/WindowsClipboard.cs

The old code of `SetImage()` would:
1. Allocate the necessary memory with `MemoryStream`
2. Copy that to a temporary array
3. Skip some bytes with LINQ and copy that to a new array
4. Copy that array into unmanaged memory with `Marshal.AllocHGlobal()`
5. memcopy that memory in a new `GlobalAlloc()` array
The new code skips steps 2 and 3.

Fix unnecessary array copying in `WindowsClipboard.SetImage()`

---

osu.Framework.Tests/FlakyTestAttribute.cs
osu.Framework.Tests/Visual/Testing/TestSceneNestedGame.cs
osu.Framework.Tests/Visual/Testing/TestSceneTestRetry.cs
osu.Framework/FrameworkEnvironment.cs
osu.Framework/Testing/Drawables/Steps/AssertButton.cs
osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
osu.Framework/Testing/TestBrowser.cs
osu.Framework/Testing/TestScene.cs

There's a few issues here:
1. We were throwing arbitrary exceptions, not `AssertionException`s. The latter are handled specially by NUnit to allow retries.
2. If an assertion happens inside `[TearDown]`, it does not re-run the test at all.
Using `TestActionAttribute` allows us to do basically the same thing without running into the second issue. Note however that this does not do anything like trying to recover the `GameHost` after a non-assertion exception, so those will still fail immediately and not retry. I think that this is fine and "intentional".
Until steps now throw an `AssertionException` instead of a `TimeoutException`. I don't believe we rely on this anywhere. Messaging has also changed a bit:
```
Previous:
TearDown : System.TimeoutException : "aaaaa" timed out
--TearDown
at …
```

Fix flaky test attribute not working

---

osu.Framework/Graphics/UserInterface/TextBox.cs
osu.Framework/Input/TextInputSource.cs

Intended to fix on-screen keyboard overlapping text boxes on SDL3 Android (https://github.com/ppy/osu-framework/pull/6105#issuecomment-2066993789).
From [`SDL_SetTextInputRect`](https://wiki.libsdl.org/SDL3/SDL_SetTextInputRect) documentation:
> To start text input in a given location, this function is intended to be called before [SDL_StartTextInput](https://wiki.libsdl.org/SDL3/SDL_StartTextInput), although some platforms support moving the rectangle even while text input (and a composition) is active.
Both `TextInputSource.Activate()` and `EnsureActivated()` have the new IME rectangle parameter, but it's optional in `EnsureActivated()` as it's only intended to be set when changing focus to a new text box.
If a text box already has input focus, it's assumed that the last …

Set IME rectangle before starting text input

---

osu.Framework/Platform/SDL3Window.cs

- Causes issues in https://github.com/ppy/osu-framework/pull/6105#discussion_r1572622366
- Upstream bug: https://github.com/libsdl-org/SDL/issues/9592
Turns out that setting the event filter drops all events, so this PR moves the `SDL_SetEventFilter` call as close as possible to `SDL_Init`.
The filter isn't doing too much so this shouldn't cause any issues (it'll be doing more in #6235, but that could only cause some dropped events on startup).
I've tested this with #6105 and can confirm it fixes the issue so [this workaround](https://github.com/ppy/osu-framework/pull/6105/files#diff-1f9486dea90c3d24267f78ddcaaf9155ede2cfc612414bf25cfe5877d75fa9d4R25-R27) is no longer needed.

Set event filter early in the startup process to work around SDL issue

---

osu.Framework/Platform/SDL3Window_Input.cs

- First noticed in https://github.com/ppy/osu-framework/pull/6105#pullrequestreview-2011866789
Works around https://github.com/libsdl-org/SDL/issues/9591 by ignoring the broken touch down events.
Buggy finger up events shouldn't cause any issues as releasing an already pressed finger will be ignored at the [`TouchInput`](https://github.com/ppy/osu-framework/blob/75ed421f60228920abd819cebc5982cb7799bbbb/osu.Framework/Input/StateChanges/TouchInput.cs#L56) level.
Current behaviour on `Relase` (`Debug` fails an assert): The bug leads to phantom touches that stick around. In the second part of the video, I show that pressing 3+ fingers only shows two touch points as the other 8 are stuck.
https://github.com/ppy/osu-framework/assets/16479013/f78eb849-9c2f-4784-becd-3332c16161ca

Work around broken `SDL_EVENT_FINGER_DOWN` events that lead to stuck touches

---

osu.Framework/Platform/SDL3Window_Windowing.cs

- Closes #6262 
I'd have hoped this GameHost code would guard against unsupported window modes, but this runs before the window is created so it has no effect.
https://github.com/ppy/osu-framework/blob/79d8e449cfb88a32b125ae3530ae53aee96b3f80/osu.Framework/Platform/GameHost.cs#L1229-L1236

Guard against unsupported window mode on startup

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/IOSWindow.cs
osu.Framework/HostOptions.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/Linux/LinuxGameHost.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs
osu.Framework/Platform/MacOS/MacOSWindow.cs
osu.Framework/Platform/SDL3DesktopWindow.cs
osu.Framework/Platform/SDL3Window.cs
osu.Framework/Platform/Windows/WindowsGameHost.cs
osu.Framework/Platform/Windows/WindowsWindow.cs

Supersedes #5650. Closes ppy/osu#25783.
The [docs](https://wiki.libsdl.org/SDL3/SDL_HINT_APP_NAME) say that
> This hint should be set before SDL is initialized.
Since `SDL_Init` is called in the `SDL3Window` constructor, this means that the application name must be known at that point in time. So it's not possible to rely on the window title.
This appName value is then used to tell SDL the application name to show in OS windows, prompts, etc.:
The `appName` could arguably be used as the initial window title.

Set SDL_HINT_APP_NAME in SDL3GameHost constructor

---

osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/IWindow.cs

The switch in `GameHost` has irked me for some time. It was mostly there since osuTK provided the event with a different signature.

Add `Update` event to `IWindow`

---

osu.Framework.Android/AndroidGameActivity.cs
osu.Framework.iOS/IOSGameHost.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/SDL3Window.cs

This removes the custom Android and iOS implementations, and also adds support for desktop platforms.
[Android](https://github.com/Susko3/SDL/blob/dc61b4b2f81c72028d7114e8b914b044d46f94f0/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L903-L907) and [iOS](https://github.com/Susko3/SDL/blob/dc61b4b2f81c72028d7114e8b914b044d46f94f0/src/video/uikit/SDL_uikitvideo.m#L173-L176) implementation in SDL3 match our old custom code.

Use SDL3 screen saver functions to implement `AllowScreenSuspension`

---

osu.Framework/Graphics/Lines/Path.cs

Partially addresses https://github.com/ppy/osu/issues/21495
Helps in reducing lag on complex (aspire/generated) sliders during fadein/out by not redrawing the slider on colour/alpha change. Note that this won't improve things on position and other geometry changes.
This probably can be applied to all the buffered containers, but I could't think of a good way to generalize that without just copying the same code into `BufferedContainer`.
Map: https://osu.ppy.sh/beatmapsets/1746664#osu/3572698
master:
https://streamable.com/hhuou2
pr:
https://streamable.com/iv4k0o

Don't redraw `Path` on colour invalidation

---

.github/workflows/ci.yml

Looks like some update to the runner broke our CI workflow for a few days now, example: https://github.com/ppy/osu-framework/actions/runs/8930403598/job/24530431772?pr=6276
I'm hoping specifying the version directly fixes this. I've pinned it to the version of the last successful run (https://github.com/ppy/osu-framework/actions/runs/8838769431/job/24270660297).

Fix broken macOS CI build

---

osu.Framework.Android/osu.Framework.Android.csproj

This conflict was most noticeable when using `[NotNull]` in osu! https://github.com/ppy/osu/commit/9c22fa3a9fbae0fb568e5a7b36d4c688268add3a.
This doesn't fix the conflict in `osu.Framework.Android`, but it does fix it for downstream projects. If a fix is needed for o!f, [`PackageReference` `Aliases`](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases) can be used.
I've tested osu! with a local framework checkout and with a local package, and it works fine without the [workaround](https://github.com/ppy/osu/commit/9c22fa3a9fbae0fb568e5a7b36d4c688268add3a).
---
- Upstream issue (wontfix): https://github.com/xamarin/AndroidX/issues/885
The namespace conflict can be tested with this diff (compile error on `master`, works fine …

Fix `Xamarin.Jetbrains.Annotations` conflicting with `Jetbrains.Annotations`

---

osu.Framework.Tests/FlakyTestAttribute.cs
osu.Framework.Tests/IO/TestOnlineStore.cs
osu.Framework.Tests/IO/TestWebRequest.cs
osu.Framework/FrameworkEnvironment.cs
osu.Framework/IO/Network/WebRequest.cs
osu.Framework/IO/Stores/OnlineStore.cs

- Adds the environment variable (`OSU_INSECURE_REQUESTS`).
- `WebRequest.AllowInsecureRequests` updated to act as an override of the environment variable.
- Added validation to `OnlineStore.GetAsync()`. This existed originally but was removed and incorrectly reverted at some point. Can't seem to pinpoint the exact commit where this happened.
- Adjusted `OnlineStore` to check for either `http` or `http` schemes. Added tests.
WIki entry: https://github.com/ppy/osu-framework/wiki/Environment-variables#osu_insecure_requests

Allow insecure requests on debug builds via `OSU_INSECURE_REQUESTS` environment variable

---

osu.Framework.Benchmarks/BenchmarkSRGBColourMultiplication.cs
osu.Framework/Graphics/Colour/SRGBColour.cs

Part of https://github.com/ppy/osu-framework/pull/6284.
Useful when computing `ColourInfo` of drawables which have white colour while applying colour to the parent (or changing parent's alpha).
Example would be applying colour/alpha to the tree of nested containers. In master some time will be spent computing colour on each level, but since by default they have white colour, we will basically passing it down to the children without conversions.
master:
```
|                   Method |      Mean |    Error |   StdDev | Allocated |
|------------------------- |----------:|---------:|---------:|----------:|
|         MultiplyNonWhite | 140.09 ns | 0.385 ns | 0.341 ns |         - |
|            MultiplyWhite | 102.45 ns | 0.242 ns | 0.189 ns |         - |
| MultiplyWhiteWithOpacity | 102.51 ns …
```

Avoid colour space conversion when multiplying `SRGBColour` by white

---

osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
osu.Framework.Tests/Visual/Input/TestSceneHandleInput.cs
osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs
osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
osu.Framework/Graphics/Containers/TabbableContainer.cs
osu.Framework/Graphics/Drawable.cs
osu.Framework/Graphics/UserInterface/Dropdown.cs
osu.Framework/Graphics/UserInterface/DropdownHeader.cs
osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
osu.Framework/Graphics/UserInterface/IDropdown.cs
osu.Framework/Graphics/UserInterface/Menu.cs
osu.Framework/Graphics/UserInterface/TextBox.cs
osu.Framework/Input/IFocusManager.cs
osu.Framework/Input/InputManager.cs
osu.Framework/Testing/TestBrowser.cs

Fixes https://github.com/ppy/osu/issues/25769
Fixes https://github.com/ppy/osu/issues/26079 (likely)
Supersedes / closes https://github.com/ppy/osu-framework/pull/6095
Closes https://github.com/ppy/osu-framework/pull/6097 (note that https://github.com/ppy/osu/issues/25850 is likely not fixed by this and will need reimplementation)
By extracting focus-management logic out of `InputManager`, we can implement something akin to a focus trap. Components can trap the focus management (`ChangeFocus()`/`TriggerFocusContention()`) of their subcomponents to add supplementary logic.
This PR features a partial redesign of `Dropdown` making use of this. There are two components wanting to manage focus here - the `Menu` and the `TextBox`.
- The `Menu`'s focus is trapped by `Dropdown` and reduced to a …

Implement focus traps

---

osu.Framework/Graphics/UserInterface/TextBox.cs

I've had the following osu! side tests fail when using a local framework checkout:
```
TestConfineAlwaysInFullscreen
TestConfineAlwaysUserSetting
```
```
at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2) in /Users/smgi/Repos/osu-framework/osu.Framework/Logging/ThrowingTraceListener.cs:line 27
at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
at System.Diagnostics.Debug.Fail(String message, String detailMessage)
at osu.Framework.Graphics.UserInterface.TextBox.unbindInput(TextBox next) in /Users/smgi/Repos/osu-framework/osu.Framework/Graphics/UserInterface/TextBox.cs:line 1380
at osu.Framework.Graphics.UserInterface.TextBox.Dispose(Boolean isDisposing) in /Users/smgi/Repos/osu-framework/osu.Framework/Graphics/UserInterface/Text …
```

Fix incorrect assertion and possible nullref

---

osu.Framework/Graphics/Rendering/Deferred/DeferredFrameBuffer.cs
osu.Framework/Graphics/Veldrid/Buffers/VeldridFrameBuffer.cs
osu.Framework/Graphics/Veldrid/Pipelines/GraphicsPipeline.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
osu.Framework/Graphics/Veldrid/Textures/VeldridVideoTexture.cs
osu.Framework/Graphics/Veldrid/VeldridDevice.cs
osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
osu.Framework/osu.Framework.csproj

This reverts commit 812e5290b88142271040fb4114c7e0d5c4ac2975, reversing changes made to 9c6dee5e854d396f9c223ab9f722995d3fa7a193.
MacOS buffered containers broke in the latest Veldrid release, pushed in https://github.com/ppy/osu-framework/pull/6275

Rollback Veldrid to fix broken buffered containers

---

osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
osu.Framework/Graphics/Drawable.cs
osu.Framework/Input/MouseButtonEventManager.cs

RFC. This is useful in situations like the osu!-side collection dropdown, which expects to remain open when the add/remove button is pressed.
Master:
https://github.com/ppy/osu-framework/assets/1329837/a0fed169-b0d6-4876-afcb-f866b802239f
With this PR (+ diff below):
https://github.com/ppy/osu-framework/assets/1329837/87430d1f-755d-44b5-9287-205291470e1a
```diff
diff --git a/osu.Game/Collections/CollectionDropdown.cs b/osu.Game/Collections/CollectionDropdown.cs
index 15dd644073..c04689b097 100644
--- a/osu.Game/Collections/CollectionDropdown.cs
+++ b/osu.Game/Collections/CollectionDropdown.cs
@@ -202,7 +202,7 @@ public CollectionDropdownDrawableMenuItem(MenuItem item)
[BackgroundDependencyLoader]
private void load()
{
-                AddInternal(addOrRemoveButton = new IconButton
+ …
```

Add a way to make Drawable clicks not change focus

---

osu.Framework.Tests/IO/TestOnlineStore.cs

https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000
> osu-framework\osu.Framework.Tests\IO\TestOnlineStore.cs(102,35): warning IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
Likely to show on embedded mobile platforms like iOS and Android.

Fix IL3000 warning on Android

---

osu.Framework.Android/AndroidGameActivity.cs
osu.Framework.Android/osu.Framework.Android.csproj

Depends on (to have identical behaviour):
SDL sends us a `SDL_EVENT_LOW_MEMORY` when Android's `onLowMemory()` handler fires. o!f handles this event and calls `GameHost.Collect()`. We also have our own handling in `onTrimMemory()`. Depending on how android handles those two functions, we may collect memory twice.
I think it makes more sense to just have `SDL_EVENT_LOW_MEMORY` handling, and not have custom logic just for android.
This PR was originally meant to pick out the useful parts from https://github.com/ppy/osu-framework/pull/6269/files#r1584189904, but I've since realised SDL already sends us a low memory event that we handle.

Fix `GameHost.Collect()` being called twice on android

---

osu.Framework/Logging/Logger.cs

Discussed in [ppy/osu#28243](https://github.com/ppy/osu/discussions/28243#discussioncomment-9548742)
This PR removes the `UserIdentifier` from log headers, along with the field itself.
I also looked into the possibility of setting the `UserIdentifier` from game code. For osu!, this would be using the account username when logged in. I found this unpractical as it depends on the user being authenticated before the header (and subsequently, the first log line) is written.
To my knowledge, no consuming projects use this field to set a custom username.

Remove OS username from log headers

---

osu.Framework/Graphics/Sprites/Sprite.cs
osu.Framework/Graphics/Sprites/SpriteText.cs

Needed for my personal project.

Make shader setter in `SpriteText` protected

---

osu.Framework/Graphics/Video/FFmpegFuncs.cs
osu.Framework/Graphics/Video/VideoDecoder.cs

Closes https://github.com/ppy/osu/issues/13696.
The editlist would cause storyboard videos to not play back the same way stable (and most other video players) plays them back.
It took me about 2 hours to figure out how to call this, and only managed to do it thanks to github-wide search [returning something that looked like what I wanted](https://github.com/codec-foundation/adobe-cc/blob/302805206994c45675b77e4a8b137bdd487ae080/source/session/movie_reader.cpp#L63-L73) after a lot of time wasted staring at ffmpeg docs, and ffmpeg source, and debugging ffplay to figure out how the hell it was passing everything and not being able to tell. C is a hell of a drug.

Ignore editlist when decoding mp4/mov videos

---

osu.Framework/Graphics/Video/FFmpegFuncs.cs
osu.Framework/Graphics/Video/VideoDecoder.cs

Closes https://github.com/ppy/osu/issues/28578.
Apparently on Android (and maybe iOS?) these point to null. Probably related to the fact that we're not building our own for these platforms yet. Best-effort fix for now.

Fix video decoding failing on Android due to missing `av_dict_{set,free}`

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/DropdownHeader.cs
osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs

Fixes https://github.com/ppy/osu/issues/28594
In hindsight, it's probably not a good idea to handle click-to-open input in something like a "search bar".
In osu!, the search bar is padded to add space for the down-arrow icon: https://github.com/ppy/osu/blob/9039ec34bae03a9b20e43b2161cc5c9e767c3889/osu.Game/Graphics/UserInterface/OsuDropdown.cs#L405-L408
I also explored the option of moving the padding to the textbox proper, but textboxes don't seem to properly handle padding at all.

Fix clicking on padded dropdown search bars not opening the menu

---

osu-framework.sln.DotSettings
osu.Framework.Tests/Visual/Containers/TestSceneVirtualisedListContainer.cs
osu.Framework/Graphics/Containers/VirtualisedListContainer.cs

RFC.
Game-side, we have a few lists/tables which perform dreadfully when stressed by a large number of rows/columns. Two of them reside in the editor, namely: the timing table and the verify issue list table.
The primary overheads in both are:
- All of the rows' content is constructed, loaded, and placed in the hierarchy eagerly, which causes a long freeze on first show.
- Even though 99.999999% of the content is not visible, it is still present in various places where it is causing trouble. While masking does cull *some* of it, the big killer is input handling - if any ancestor of a table row _might_ handle e.g. mouse input because they are all alive, all of them get shoved into the input queue and then all need to be checked on every mouse movement. (See …

Add virtualised list container

---

osu.Framework.Tests/Visual/Containers/TestSceneVirtualisedListContainer.cs
osu.Framework/Graphics/Containers/VirtualisedListContainer.cs

`CompositeDrawable.Dispose()` doesn't do anything to its children except dispose them, which is problematic, since it leads to two things happening in the context of `VirtualisedListContainer`:
- The pooled child is never returned to pool (because returning happens automagically on parent change, which doesn't happen here)
- However, the pool continues to retain the reference to a disposed pooled drawable, which means that it (a) keeps drawables that will blow up if they were ever to be used, which isn't possible because (b) these drawables are never returned, which means that the pool will inevitably start overflowing.
Thus, aggressively remove the pooled child at the start of disposal to counteract this happening.
Can be semi-manually tested using …

Fix `VirtualisedListContainer` rows not returning child to pool on disposal

---

osu.Framework/Graphics/Containers/ScrollContainer.cs

- Closes https://github.com/ppy/osu-framework/issues/2697
Hit this multiple times while just wanting to scroll through a zoomed-in editor timeline in osu!. Discussed removing assertion in [discord](https://discord.com/channels/188630481301012481/589331078574112768/1255759444739096606).

Remove faulty assertion in scroll container

---

osu.Framework/Graphics/Drawable.cs

Fix typo in `Drawable` documentation

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

- Closes https://github.com/ppy/osu/issues/28713
Before:
https://github.com/ppy/osu-framework/assets/22781491/322a49e4-d18b-4670-a9ee-3ac6e9ff43fc
After:
https://github.com/ppy/osu-framework/assets/22781491/9eee646e-a8ab-4498-9191-d030de29a204

Ignore ongoing text drag selection when user writes to textbox

---

osu.Framework/Audio/Sample/SampleChannelBass.cs

un4seen thread: https://www.un4seen.com/forum/?topic=20453.0
This fixes the test failures in https://github.com/ppy/osu-framework/pull/6327. Why did they come up? In that PR, the update thread is running slower time-wise because the audio thread is lagging behind. This means that steps are updated later than they normally would and there's a greater chance that they trigger right when the audio thread processes a frame.  
The failures in that PR can be simulated by adding a `Thread.Sleep(200)` in the update thread.
Repro (not committed because this is untestable - the until-step should not pass):
```csharp
[HeadlessTest]
public partial class TestSceneScratch : FrameworkTestScene
{
private Sample? sample;
private SampleChannel? channel;
[Resolved]
private AudioManager audioManager { get; …
```

Fix intermittent `Playing` state on short looping samples

---

osu.Framework/Platform/HeadlessGameHost.cs
osu.Framework/Threading/GameThread.cs

RFC. Primarily, this should fix the osu!-side macOS test failures when running under MultiThread execution mode. This will also likely fix other unexplainable flaky tests.
Unfortunately, I don't _think_ this is or I can't reason as to why it would be related to the clock running backwards (https://github.com/ppy/osu/issues/26879), as I'd hoped to find :(
Local osu!-framework checkout with:
```diff
diff --git a/osu.Framework/Threading/AudioThread.cs b/osu.Framework/Threading/AudioThread.cs
index 171f43280..4debaad82 100644
--- a/osu.Framework/Threading/AudioThread.cs
+++ b/osu.Framework/Threading/AudioThread.cs
@@ -65,6 +65,8 @@ private void onNewFrame()
m.Update();
}
}
+
+            System.Threading.Thread.Sleep(200);
}
internal void RegisterManager(AudioManager manager)
```
Run test …

Make time move along at the same rate in all threads during headless execution

---

.github/workflows/ci.yml
build/vstestconfig.runsettings

I was looking into a test failure and noticed the macOS runner is specifically outputting every test result, which is totally unreadable: https://github.com/ppy/osu-framework/actions/runs/9970267947/job/27548828465?pr=6314
This doesn't happen osu!-side, which is drilled down to only failed tests, see: https://github.com/ppy/osu/actions/runs/9967138608/job/27540336842
I made two changes here:
1. o!f provides custom test runner settings, setting a 300s test runner timeout. osu! doesn't have this, so I've removed it.
2. o!f doesn't pass the `NUnit.ConsoleOut=0` argument. osu! does, so I've added it.
Result: https://github.com/smoogipoo/osu-framework/actions/runs/9970690756/job/27550138301 (or in this PR)

Reduce macOS CI test output

---

osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs
osu.Framework/Graphics/UserInterface/Popover.cs

Closes https://github.com/ppy/osu/issues/28865.
The issue is caused specifically by the "arrow" part of the popover. The feedback loop involved in this is as follows:
- A popover is added to the scene graph. The automatic anchor selection logic chooses an anchor and a position for it. For the arrow part specifically, this is compounded with a counteracting adjustment that ensures that the popover arrow continues to point at its target drawable:
https://github.com/ppy/osu-framework/blob/691d8671be5f65f76b4800e85141bb6fde67e139/osu.Framework/Graphics/Cursor/PopoverContainer.cs#L143-L147
- The base `Popover` class uses autosize on both axes of its `BoundingBoxContainer`, whose bounds are used to calculate the best anchor:
https://github.com/ppy/osu-framework/blob/691d8671be5f65f76b4800e85141b …

Fix popovers one-frame-twitching in specific circumstances

---

osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
osu.Framework/Input/PassThroughInputManager.cs

- Direct revert of https://github.com/ppy/osu-framework/pull/6225
Attached a vital failing test case that deems this to be an incorrect approach (coming from https://github.com/ppy/osu/issues/28931). When the `PassThroughInputManager` is hidden from the input queue, if there is a key pressed before parent input is enabled again, releasing the key after parent input is enabled does not trigger a `KeyUpEvent` on the PTIM, as demonstrated in the failing test case.
The purpose of hiding PTIM from the input queue in the first place is to prevent it from receiving a `KeyDownEvent` if parent input is enabled by another drawable that received the `KeyDownEvent` before the PTIM does (in osu! case, the PTIM is the gameplay input manager and the drawable is the osu! click-to-resume cursor; see …

Keep `PassThroughInputManager` in input queue even while parent input is disabled

---

osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
osu.Framework/Input/PassThroughInputManager.cs

In order for a `PassThroughInputManager` to receive the release event of any input at any time, it must've seen the corresponding press event, even if the press was performed while `UseParentInput` is turned off.
This behaviour doesn't really make sense, and is broken in osu! right now when there are drawables in front of gameplay that block input (e.g. pause overlay handling `Space` key as the select action while playing mania wherein `Space` corresponds to the special key action).
Before:
https://github.com/user-attachments/assets/b3d15938-5938-4b4e-998a-9315fa858010
After:
https://github.com/user-attachments/assets/ea6da4bb-6c64-4733-ae5d-1b0701ab0212
(key is stuck in "Before" because pause overlay handled the space key press to select the continue button, but it's fixed in "After")

Fix `PassThroughInputManager` not always releasing input

---

osu.Framework.Benchmarks/BenchmarkBindableList.cs
osu.Framework/Bindables/BindableList.cs

As mentioned in https://github.com/ppy/osu/pull/28779
```diff
| Method |     Mean |   Error |   StdDev |   Gen0 | Allocated |
|------- |---------:|--------:|---------:|-------:|----------:|
- |    Add | 374.9 ns | 7.48 ns | 11.19 ns | 0.4334 |   2.66 KB |
+ |    Add | 335.9 ns | 3.59 ns |  3.00 ns | 0.1526 |     960 B |
```
I'm not sure why `BindableList` is awarded this facility and no other implementation (`Bindable` or `BindableDictionary`) is, but it was done to fix bugs so I'm not going to question it too much.

Remove HashSet allocations during BindableList methods

---

osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
osu.Framework/Graphics/Drawable.cs
osu.Framework/Input/InputManager.cs
osu.Framework/Input/MouseButtonEventManager.cs

RFC.
I'm not happy with this because means that `FocusedDrawable` is `null` during `OnClick()` handling. What I'd really like to do is "snapshot" `FocusedDrawable`. I'm not sure/don't think anything expects `FocusedDrawable` to be correct during click handling, though.

Do not unfocus on click if the focused drawable changed during the click

---

osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
osu.Framework/Graphics/UserInterface/DropdownHeader.cs
osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs

As mentioned in https://github.com/ppy/osu-framework/pull/6346#issuecomment-2277354452
I might take a look at input in dropdown again at some point, I don't really like that it's scattered between `DropdownHeader` and `DropdownSearchBar`. Until then please live with it...
https://github.com/user-attachments/assets/ddc3ab8b-4f80-4a3e-bd09-3331caf9dfb0

Allow clicking on empty search header to close dropdown

---

osu.Framework/Audio/Track/TrackBass.cs

Fixes https://github.com/ppy/osu/issues/29332
It seems the tempo attributes were being applied to the wrong stream handle, so the attributes were ignored completely. With the fix, the audio seems to match osu! stable.
Something else that's interesting is that if you disable the quick algorithm, the audio becomes even better and I didn't notice an increase in CPU usage while using it. Maybe that's something that can be looked into later.

Fix tempo attributes being ignored

---

osu.Framework.Benchmarks/BenchmarkBindableList.cs
osu.Framework/Bindables/BindableList.cs

This reverts commit af4e54d7af31fadd43024dbf796f917f3d89dd52, reversing changes made to 4779e1b82e5b03daff7210786200d2c14e8deaee.
See test failures in https://github.com/ppy/osu/pull/29367 . I don't really want to bother with figuring out how to make this work nicely without developer overhead. Might take a different approach in the future - dunno.

Revert BindableList GC reduction change

---

osu.Framework/Graphics/BufferedDrawNode.cs

Profiling over around 10s in `TestSceneBufferingPerformance`:
| --- | --- |
| <img width="832" alt="image" src="https://github.com/user-attachments/assets/1a4931fc-f05d-4281-bc36-d03abf40aff4"> | <img width="834" alt="image" src="https://github.com/user-attachments/assets/362a189b-9015-4c82-873e-d897f658c793"> |
This is a bit of an edge case, but it is a potential source of per-frame allocations nonetheless.

Remove unnecessary boxing allocation

---

osu.Framework.Android/AndroidGameActivity.cs
osu.Framework.Android/AndroidGameSurface.cs

SDL3 started to provide safe area, and it uses [`setOnApplyWindowInsetsListener`](https://developer.android.com/reference/android/view/View#setOnApplyWindowInsetsListener(android.view.View.OnApplyWindowInsetsListener)) which overrides `View.onApplyWindowInsets` with `View.OnApplyWindowInsetsListener.onApplyWindowInsets`.
This PR makes AndroidGameSurface override `View.OnApplyWindowInsetsListener.onApplyWindowInsets` instead, and removes `LayoutInDisplayCutoutMode` as it is now set in SDL side.
I also tried using SDL-provided safe area, but it doesn't seem to work like our current implementation, so I think we can still keep ours for now.

Fix Android safe area

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/Containers/TabbableContainer.cs

Closes https://github.com/ppy/osu/issues/29501.

Fix tabbable container not checking if its next tab stop is focusable

---

osu.Framework.Tests/Visual/Platform/TestScenePresentFileExternally.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs
osu.Framework/Platform/MacOS/Native/Finder.cs
osu.Framework/Platform/MacOS/Native/NSWorkspace.cs

apple doc: https://developer.apple.com/documentation/appkit/nsworkspace/1524399-selectfile
This API only overrides PresentFileExternally as it can only highlight the incoming file in its parent directory. 
We check if the file exists first (see https://github.com/ppy/osu-framework/commit/c1fd9561adb518b3f3d8af119b1614433d5cc38d), because if the file doesn't exist, the API won't do anything so we will fall back to `OpenFileExternally`, which then uses `openUsingShellExecute`.

Implement native method for `PresentFileExternally` in MacOS

---

osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
osu.Framework/Graphics/DrawNode.cs

Consider the [following scenario](https://github.com/user-attachments/assets/2d8c5bc0-d2ca-47d6-ac2d-f0424ef3d9cb).
You may assume that these boxes will be batched and drawn in a single draw call, however this is not the case:
That's because each `DrawNode` sets its blending parameters [inside `Draw` method](https://github.com/ppy/osu-framework/blob/4e3ef471300c27e7d8da42682343bc85812df729/osu.Framework/Graphics/DrawNode.cs#L79) and the problem here is that `CompositeDrawNode` does the same. But this is not needed since each child will set their own blending later on (which is computed with `DrawColourInfo` and [inherited from the parent](https://github.com/ppy/osu-framework/blob/4e3ef471300c27e7d8da42682343bc85812df729/osu.Framework/Graphics/Drawable.cs#L1644)), thus making blending …

Fix renderers can't batch vertices with the same blending parameters in some cases

---

osu.Framework/Input/Bindings/KeyCombination.cs

Just a quick one I couldn't ignore.
| ![JetBrains Rider 2024-09-04 at 06 33 56](https://github.com/user-attachments/assets/a93d9723-9a4a-4929-96b9-02380c9e94ab) | ![JetBrains Rider 2024-09-04 at 06 34 56](https://github.com/user-attachments/assets/22e181e5-2d51-4db2-be43-3d3b46748610) |
Want to get this in the imminent framework release just to tidy up allocs.

Fix alloc overhead in hot path for keyboard checks

---

osu.Framework/Localisation/LocalisationManager.cs

The initial rationale for it being internal was likely that there was never going to be any meaningful external usage of it, but as it turns out, there are cases where you want this, one of them being https://github.com/ppy/osu/pull/29913 - without having the non-bindable variant exposed, weird games of taking out the bindable and then manually unbinding it immediately after use have to be played to avoid reference leaks.
The pre-existing xmldoc should do the job when it comes to warning users that the method will likely not do what they want it to in most cases.

Expose `LocalisationManager.GetLocalisedString()` as public

---

osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
osu.Framework/Timing/DecouplingFramedClock.cs

- Fixes https://github.com/ppy/osu/issues/29946
This PR fixes an issue where DecouplingFramedClock retains old lastSeekFailed after changing its source.
It only happens on Windows because it only has platform offset due to new BASS versions. Seeking to 0 in EditorClock is practically seeking to -15, so TrackVirtual fails to seek to negative position, which in turn sets lastSeekFailed to true, but DecouplingFramedClock doesn't reset the variable after changing the source, so it just keeps interpolating instead of actually playing the source.

Fix DecouplingFramedClock retaining old lastSeekFailed

---

.github/workflows/ci.yml
.github/workflows/deploy-pack.yml

Ref: https://github.com/ppy/osu/pull/30019

Fix iOS CI build

---

osu.Framework/Graphics/UserInterface/SliderBar.cs

For use with https://github.com/ppy/osu/issues/30112. Without this, it is difficult to tell when a slider is done applying its changes, as there are several pathways for this (drag operation / keyboard stepping / direct single click).

Expose slider bar commit method as virtual

---

osu.Framework.iOS/IOSWindow.cs

This broke when we moved over from osuTK in https://github.com/ppy/osu-framework/pull/5698.
See: https://wiki.libsdl.org/SDL3/SDL_HINT_IOS_HIDE_HOME_INDICATOR
Same as https://github.com/ppy/osu-framework/pull/5009.

Hide iOS home indicator by default

---

osu.Framework.Tests/Localisation/LocalisableStringTest.cs
osu.Framework/Localisation/LocalisableStringEqualityComparer.cs

Needed to do this after https://github.com/ppy/osu/pull/30199 (`default` -> `Data = null`).

Enable NRT in `LocalisableStringEqualityComparer`

---

osu.Framework/FrameworkEnvironment.cs

I'm not sure how we're ever going to test this without testing in production. Can still be switched off via `OSU_SDL3=0`.

Use SDL3 windowing by default

---

osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
osu.Framework/Graphics/UserInterface/BasicSliderBar.cs
osu.Framework/Graphics/UserInterface/SliderBar.cs

This change would allow you to click the slider bar, have it gain focus, and then adjust the slider bar with the keyboard while the cursor is not hovering the slider bar.
This matches the user expectation because you can do the same thing in osu! stable.
In current lazer the only way to do this is click away to unfocus everything, then hover the slider bar while using keyboard. This flow is apparently so confusing that someone in Discord thought it wasn't possible at all.
https://github.com/user-attachments/assets/19d901c3-4130-48f8-be75-bedc75a6676f

Allow slider bar to take focus and accept keyboard input while not hovered

---

osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
osu.Framework/Graphics/Visualisation/DrawVisualiserHiddenAttribute.cs

When trying to use the draw visualiser during gameplay, you can't target anything other than the cursor trail.
```diff
diff --git a/osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs b/osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
index a4bccb0aff..5132dc2859 100644
--- a/osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
+++ b/osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
@@ -14,6 +14,7 @@
using osu.Framework.Graphics.Shaders;
using osu.Framework.Graphics.Shaders.Types;
using osu.Framework.Graphics.Textures;
+using osu.Framework.Graphics.Visualisation;
using osu.Framework.Input;
using osu.Framework.Input.Events;
using osu.Framework.Timing;
@@ -23,6 +24,7 @@
namespace osu.Game.Rulesets.Osu.UI.Cursor
{
+    [DrawVisualiserHidden]
public partial class CursorTrail : Drawable, …
```

Add attribute to hide arbitrary drawables from draw visualiser

---

osu.Framework.Tests/Graphics/RendererTest.cs
osu.Framework/Graphics/Rendering/Renderer.cs

Fixes https://github.com/ppy/osu-framework/issues/6409

Fix texture wrapping not updating when atlas is already bound

---

osu.Framework/IO/Network/WebRequest.cs

Something I ended up needing in the course of BSS work.
The previous implementation would treat files as a straight dictionary, as in you could have only one file with a given parameter name in a request. This isn't how `multipart/form-data` really works; you're allowed to send multiple files in scope of a single parameter.
Additionally, the request did not permit specifying a filename, which is yet another thing I need for BSS purposes.
I don't believe this method has any real consumers, yet anyhow:
Breaking changes
----------------
`WebRequest.AddFile()` has been altered to provide an API closer to what the HTTP specs intended, and to allow sending multiple files for a given request parameter. To that end:
- The signature of the method has changed from
```csharp
public void …
```

Add better support for adding form file parameters to web requests

---

osu.Framework/Platform/SDL3/SDL3Window.cs

Is not necessary since we handle this ourselves. Additionally the Windows implementation of this looks abhorrent:

Fix SDL3 attempting to render IME composition text

---

osu.Framework/Graphics/Containers/ScrollContainer.cs

Allow customising `ScrollContainer`'s scrollbar mapping

---

osu.Framework/Graphics/Visualisation/DrawVisualiser.cs

Should fix targeting in osu!mania argon skin, where the background layer is placed at the front for input handling but proxied to the back for visual arrangement.

Make draw visualiser follow proxied drawables to their visual layer

---

osu.Framework/Testing/TestBrowser.cs
osu.Framework/Testing/TestScene.cs
osu.Framework/Testing/TestSceneTestRunner.cs

When executing a group of steps by clicking on the label, if a step fails, it does not get logged. Fix is pretty simple, don't need to waste my breath. I've also made the error message consistent with [this](https://github.com/ppy/osu-framework/blob/94bd9c2f73f0bb72af93ef175e4c169d1440c03b/osu.Framework/Testing/Drawables/Steps/StepButton.cs#L96-L95).

Fix error triggered in label step execution not being logged

---

.github/workflows/report-nunit.yml

Carbon copy of https://github.com/ppy/osu/pull/30543.
Example run: https://github.com/bdach/osu-framework/runs/32856932147

Fix CI test report workflow

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/IOSWindow.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/ISDLWindow.cs
osu.Framework/Platform/SDL2/SDL2Window.cs
osu.Framework/Platform/SDL3/SDL3Window.cs
osu.Framework/Platform/SDLGameHost.cs

Noticed while working on fixing iOS hardware keyboard issues. When a hardware keyboard is attached, the software keyboard no longer shows and "overlaps with the game window", so it's more ideal for the `OnScreenKeyboardOverlapsGameWindow` flag to remain false in that case, so that search text boxes on osu! still gain focus when they are present (i.e. when opening song select or opening settings overlay).
An Android companion to this should be in place if this change can be agreed upon. 
Also note that this implementation can be simply replaced with `!SDL_HasKeyboard()`, and we can also just replace these overrides with a single override at `SDLGameHost` that returns `!SDL_HasKeyboard()` (usually always false on desktop platforms, and true on mobile platforms if there are no hardware …

Disable `OnScreenKeyboardOverlapsGameWindow` on iOS when hardware keyboard is attached

---

osu.Framework/Platform/SDL3/SDL3Window.cs
osu.Framework/Platform/SDL3/SDL3Window_Input.cs
osu.Framework/Platform/Windows/SDL3WindowsWindow.cs

Previously, it would use a custom implementation. That implementation is still used for windows SDL2.
There is still some windows-specific code that handles `AllowIme` and cancelling the active composition.
The SDL3 text editing events work well (even better than the custom impl in some cases). The only issue I ran into when testing is that the caps lock key would sometimes gets stuck (<kbd>Ctrl</kbd>/<kbd>Alt</kbd> + <kbd>Caps Lock</kbd> is used to change kana mode on Japanese IME), but this also happened with the custom implementation so it's not a regression. (I use programs that change keyboard behaviour, so it might be a me problem.)

Use SDL3 text editing events on windows

---

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
osu.Framework/Graphics/Containers/RearrangeableListContainer.cs

When handling range replacements, it first does a remove, then a sort, then an add, then a sort. The sort is intended to operate on drawable objects, but these do not yet exist because they haven't been added yet. In other words, the sort in-between the add and remove is causing the crash.
I've gone with the likely least-regressing path of making the `sortItems()` handle this case. I'd considered moving the events to the callback and doing a sort of "transaction", but there's quite a bit involved due to the sometimes-asynchronous operation of this container.  
Maybe things could be better if we removed the asynchronous `Add`...

Fix `RearrangeableListContainer<>` crashing on replacement operations

---

osu.Framework/FrameworkEnvironment.cs

Reverts ppy/osu-framework#6396
Rationale:
- https://github.com/ppy/osu/issues/30641
- https://github.com/ppy/osu/issues/28222
- Apparent general unspecified severe issues with macOS windowing (https://discord.com/channels/188630481301012481/188630652340404224/1306507518134194176)
- https://github.com/ppy/osu/discussions/30647 (wayland issue, so weak reason)
None of this seems hotfixable and users are reporting mass breakage using several communication channels, most of which is a variation of any of the three points above. See
- https://osu.ppy.sh/community/forums/5
- https://osu.ppy.sh/home/changelog/lazer/2024.1115.1
I think this is the best move forward in terms of a hotfix, and we shouldn't attempt SDL3 again until these issues are fixed either by us or upstream (*or both...*)

Revert "Use SDL3 windowing by default"

---

osu.Framework/osu.Framework.csproj

This was only included for the old dynamic compiler, that doesn't exist anymore.

Remove `NuGet.ProjectModel` dependency

---

osu.Framework/osu.Framework.csproj

We've been seeing some hot reload failures of the form: `error ENC0003: Updating 'attribute' requires restarting the application`
This is caused by SourceLink, which wants to write the git hash to the `AssemblyInfo` obj file.
Trail starts here: https://github.com/dotnet/sourcelink/pull/1144
SourceLink is included starting with the .NET 8 SDK, and I've tested that SourceLink is still working - `dotnet pack` and check the `.nuspec` in the contained package:
```sh
$ cat ppy.osu.Framework.nuspec | grep rep
<repository type="git" url="https://github.com/ppy/osu-framework" commit="270b29d58b736deca2b6d76fe9907b2554d5979f" />
```

Remove SourceLink package reference

---

osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
osu.Framework/Graphics/Containers/RearrangeableListContainer.cs

When using `ReplaceRange()` it will no longer re-add items that were previously and still are in the list.

Make `RearrangeableListContainer<>` only replace differences

---

osu.Framework/Input/UserInputManager.cs

The mouse position is in pixel/client coordinates, while window and displays positions are in window coordinates.
Proof of coordinate spaces for display position (on a 3456x2234 macbook):
(Image taken from https://discord.com/channels/188630481301012481/188630652340404224/1308162379045011506)
---
We should probably have `IWindow.ClientToDisplay(Vector2)` that takes in a client (game screen space) vector and converts it to display coordinates. Would the need for `ISDLWindow` type checks from this code.

Factor window scale in `UserInputManager.mouseOutsideAllDisplays`

---

.github/workflows/ci.yml
.github/workflows/deploy-pack.yml

- Related: https://github.com/dotnet/sdk/issues/45204
Something extremely funny is happening straight from Windows Runner Image 20241113.3.0, where installing workloads without specifying a version installs ones from .NET 7(????)
[This part](https://github.com/frenzibyte/osu/actions/runs/12062014593/job/33635009500#step:7:10) should be enough to show how messed up the situation seems to be. The command execution shows that the used .NET SDK is correct, but the installed workloads point to .NET 7 versions. Moreover, the workload install output shows that it is installing both [.NET 6](https://github.com/frenzibyte/osu/actions/runs/12062014593/job/33635009500#step:5:32) and [.NET 7](https://github.com/frenzibyte/osu/actions/runs/12062014593/job/33635009500#step:5:52) versions of the …

Work around Android CI workflow errors

---

osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
osu.Framework.Tests/Visual/Platform/TestSceneWindowed.cs
osu.Framework.Tests/Visual/Platform/WindowDisplaysPreview.cs
osu.Framework/Input/UserInputManager.cs
osu.Framework/Platform/ISDLWindow.cs
osu.Framework/Platform/IWindow.cs
osu.Framework/Platform/Windows/WindowsGLRenderer.cs

`Focused`, `PointToClient()` and `PointToScreen()` in `IWindow` are made obsolete as they are not useful. See commits for more details.
Moves some members from `ISDLWindow` to `IWindow`. This makes it so platform-agnostic code no longer needs to cast to `ISDLWindow` (in `UserInputManager` and tests).

Clean up `IWindow` and remove platform-agnostic code probing `ISDLWindow`

---

osu.Framework/Graphics/UserInterface/Menu.cs

To be used by lazer for improved menu audio feedback (ppy/osu#30910)

Add callback for when a submenu is opened

---

CodeAnalysis/osu-framework.globalconfig
Directory.Build.props
osu-framework.sln

Rider doesn't recognize the implicitly named `.globalconfig` files. Reference it explicitly in msbuild props instead.

Fix Rider support of .globalconfig

---

osu-framework.sln.DotSettings
osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs
osu.Framework/Configuration/FrameSync.cs
osu.Framework/Configuration/RendererType.cs
osu.Framework/Graphics/Drawable.cs
osu.Framework/Graphics/Video/HardwareVideoDecoder.cs
osu.Framework/Input/Bindings/InputKey.cs
osu.Framework/Platform/Linux/Native/Library.cs
osu.Framework/Platform/MacOS/Native/NSStringEncoding.cs
osu.Framework/Platform/Windows/Native/Execution.cs
osu.Framework/Platform/Windows/Native/Imm.cs
osu.Framework/Platform/Windows/Native/Input.cs
osu.Framework/Platform/Windows/SDL2WindowsWindow.cs
osu.Framework/Platform/Windows/WindowsGLRenderer.cs
osu.Framework/RuntimeInfo.cs
osu.Framework/Statistics/DotNetRuntimeListener.cs

Not fully sure if this is caused by new Rider update or something else, I've navigated back to a point before https://github.com/ppy/osu-framework/pull/6434 was merged but it's not relevant, not to mention that the warnings fixed by this PR completely come from ReSharper, so they're not relevant to that PR anyway.
This one was actually seen in ppy/osu as well half a year ago: https://github.com/ppy/osu/pull/28051
It seems that it would be better to exclude enum members from naming rule inspections, but apparently that's not possible to do at all. Enum members are being treated the same as public fields/properties, and since we apply the pascal case rule to those, enum members are being affected as well.
This is an issue with Rider that was [reported a long while …

Fix recent warnings seen on Rider 2024.3

---

osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
osu.Framework.Tests/Platform/IPCTest.cs
osu.Framework.Tests/Platform/UserInputManagerTest.cs
osu.Framework/HostOptions.cs
osu.Framework/Platform/DesktopGameHost.cs
osu.Framework/Platform/GameHost.cs
osu.Framework/Platform/IIpcHost.cs
osu.Framework/Platform/IpcChannel.cs
osu.Framework/Platform/NamedPipeIpcProvider.cs

Resolves https://github.com/ppy/osu/discussions/30783.
Has come up a few times in recent months so worthwhile fixing.
I've used this opportunity to also make the API a touch more robust and lock in the bidirectional messaging API too.
This resolves cases where other applications may be reserving ranges of ports on localhost (as we found is common of WSL). Things should still work out-of-the-box if you are already using IPC, but you may want to update your usage as we've obsoleted the port specification:
```diff
diff --git a/osu.Desktop/Program.cs b/osu.Desktop/Program.cs
index 1a9aade377..bb9b0c30fa 100644
--- a/osu.Desktop/Program.cs
+++ b/osu.Desktop/Program.cs
@@ -99,7 +99,7 @@ public static void Main(string[] args)
var hostOptions = new HostOptions
{
-                IPCPort = 12345, …
```

Switch to using named pipes for IPC

---

osu.Framework/Platform/NamedPipeIpcProvider.cs

https://sentry.ppy.sh/organizations/ppy/issues/67405/?alert_rule_id=4&alert_timestamp=1733713067444&alert_type=email&environment=production&project=2&referrer=alert_email
Not hotfix worthy, but worth fixing.

Fix unobserved exceptions on named pipe shutdown

---

osu.Framework.Benchmarks/BenchmarkBindableList.cs
osu.Framework/Bindables/BindableList.cs

Extracted out from + excludes the controversial changes of https://github.com/ppy/osu-framework/pull/6405.
Before:
```
|    Method | NumBindings |        Mean | Error |     StdDev | Ratio | RatioSD |   Gen0 |   Gen1 | Allocated | Alloc Ratio |
|---------- |------------ |------------:|------:|-----------:|------:|--------:|-------:|-------:|----------:|------------:|
|    Create |           0 |    81.33 ns |    NA |   1.539 ns |  1.00 |    0.00 | 0.0930 |      - |     584 B |        1.00 |
|       Add |           0 |   135.18 ns |    NA |  21.728 ns |  1.66 |    0.24 | 0.1364 |      - |     856 B |        1.47 |
|    Remove |           0 |    96.40 ns |    NA |   1.789 ns |  1.19 |    0.04 | 0.1147 |      - |     720 B |        1.23 |
|     Clear |           0 |   106.17 ns |    NA | …
```

Improve `BindableList` performance + reduce allocations

---

osu.Framework.iOS/IOSFilePresenter.cs
osu.Framework.iOS/IOSGameHost.cs
osu.Framework.iOS/IOSWindow.cs

Allows exporting files in the game. Preview:
https://github.com/user-attachments/assets/f47a82d5-9eac-4363-a9e3-c4447658a986

Add support for presenting/opening files on iOS

---

osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs
osu.Framework/Platform/NamedPipeIpcProvider.cs

Regressed with https://github.com/ppy/osu-framework/pull/6442. Closes https://github.com/ppy/osu/issues/31072.
Was not visible in test coverage because as per the inline comment, this is an exceptional case where two different processes bind.
I'm not sure how to add test coverage for this, but I have tested manually on both windows and macOS.
Can test using this:
```diff
diff --git a/SampleGame.Desktop/Program.cs b/SampleGame.Desktop/Program.cs
index 4756edbaa..ae5075535 100644
--- a/SampleGame.Desktop/Program.cs
+++ b/SampleGame.Desktop/Program.cs
@@ -12,9 +12,17 @@ public static class Program
[STAThread]
public static void Main(string[] args)
{
-            using (GameHost host = Host.GetSuitableDesktopHost(@"sample-game"))
+            using (GameHost host = …
```

Fix multiple instances of a game being allowed to start concurrently

---

osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
osu.Framework/Input/InputManager.cs

Noticed in osu! gameplay, where if you press resume from the pause overlay, a right click is always triggered at the point where the button was clicked:
https://github.com/user-attachments/assets/52817b8b-b29a-4825-875d-27f09a54ae06

Fix disabling hold-to-right-click not cancelling in-progress actions

---

osu.Framework/osu.Framework.csproj

- Acepen AP906
- Artist 22
- Artisul D16 Pro
- Gaomon M8
- Huion 1060 Plus
- Huion Kamvas GT-156HD V2
- Huion Kamvas Pro 16
- Huion Kamvas Pro 16 Plus
- Huion Kamvas Pro 19
- Huion Kamvas Pro 22
- Huion RTP-700
- Parblo A610
- Parblo A640
- Trust Flex Design Tablet
- Turcom TS-6580
- UGEE M808
- UGEE M908
- Wacom CTH-300
- Wacom Cintiq 22HD 
- Wacom DTH-271
- XP-Pen Artist 16
- XP-Pen Artist 24 Pro
- XP-Pen Star 03 Pro
- XP-Pen Gen2 tablets
- Artist Pro 16 Gen 2
- Deco Pro LW Gen 2
- Deco Pro XLW Gen 2
- Artisul M0610 Pro
- Gaomon GM116HD
- Gaomon M10K Pro
- Huion H580X
- Huion H580x
- Huion H950P
- Huion HS64 variant
- Huion HS64
- Huion Kamvas Pro 12
- Huion WH1409 V2
- Kamvas 13
- Kamvas Pro 12
- VEIKK VK430
- Wacom PTH-460
- XP-Pen Deco mini4
- XP-Pen Star G430S
- XP-Pen Star G640
- …

Bump OpenTabletDriver to 0.6.5.0

---

osu.Framework.Tests/Bindables/BindableListTest.cs
osu.Framework/Bindables/BindableList.cs

Partial revert to `IList`, with casts to `IEnumerable<T>` instead that are internally optimised by `List<T>`.
While a bit ugly, it's still more performant than the original code that used a `.Cast<T>()` LINQ expression for similar reasons.

Fix `BindableList` methods crashing with non-`IList` collections

---

osu.Framework.Tests/Visual/Graphics/TestSceneTexturePremultiplication.cs
osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs

- Supersedes / closes https://github.com/ppy/osu-framework/pull/6454
- Closes ppy/osu#19957
Apple offers high-performance / SIMD-based image processing API under its Accelerate framework called `vImage`, suiting our needs perfectly as well as providing support for non-premultiplied image loading (I've only been aware of this as I was working towards changing the entire game to use premultiplied colours).
The benchmark methodology may be basic, but I've benchmarked this by measuring time spent on loading each texture while randomly browsing through osu!. Results show roughly close match between master and this PR.
To ensure the premultiplication issues are appropriately fixed, I've added a test scene for it.
The intro artifacts in https://github.com/ppy/osu/issues/9922 will not be fixed by …

Use Accelerate framework for texture image processing on iOS and fix premultiplication issues

---

osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs

Noticed while attempting to migrate this to macOS, the `Crop` part had allocation overhead with it (which...makes sense). Naive coding from my part.
In case it's not clear already, it's not possible to directly load the image off of the `vImage` pixel buffer as each row in the buffer has additional space at the end for performance reasons (memory alignment etc.). I've replaced the load-and-crop step with loading an empty image and copying row by row directly to memory.
Time measuring of the texture loading process shows nothing bad, maybe good even (left master, right this PR):

Shave allocation overheads in recent iOS texture loading code

---

.github/workflows/build-ffmpeg.yml

[Run on my fork](https://github.com/FreezyLemon/osu-framework/actions/runs/12517175492)
The `macos-12` image has been [deprecated and disabled](https://github.com/actions/runner-images/issues/10721) which means the macOS jobs don't even start anymore. I chose version 13 because I assume that the resulting binaries will have better compatibility with older macos versions than ones built on a newer OS version.

FFmpeg build: Use macos-13 CI image

---

osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs

Input in framework is absolutely frustrating to figure out when it goes wrong. This helps a bit.
Used to diagnose https://github.com/ppy/osu/issues/31262 (which should be a 5 minute fix at maximum):
https://github.com/user-attachments/assets/27c8fdc4-59ea-480b-9183-bb05d3fc73b6

Show whether drawable is receiving input in draw visualiser

---

osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs

Also noticed while testing iOS. Popping out the software keyboard on a dropdown always feels wrong, regardless of the `AlwaysDisplayOnFocus` toggle:
https://github.com/user-attachments/assets/d51b92e0-b0d8-4c59-8ac4-88a76fbe2f32

Disable dropdown searching on mobile when no hardware keyboard is attached

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

Fix crash when dragging in a text box while a key is held down

---

osu-framework.sln.DotSettings
osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
osu.Framework/Platform/Apple/AppleTextureLoaderStore.cs
osu.Framework/Platform/Apple/Native/Accelerate/vImage.cs
osu.Framework/Platform/Apple/Native/Accelerate/vImage_Buffer.cs
osu.Framework/Platform/Apple/Native/Accelerate/vImage_CGImageFormat.cs
osu.Framework/Platform/Apple/Native/Accelerate/vImage_Error.cs
osu.Framework/Platform/Apple/Native/Accelerate/vImage_Flags.cs
osu.Framework/Platform/Apple/Native/CGBitmapContext.cs
osu.Framework/Platform/Apple/Native/CGBitmapInfo.cs
osu.Framework/Platform/Apple/Native/CGColorRenderingIntent.cs
osu.Framework/Platform/Apple/Native/CGColorSpace.cs
osu.Framework/Platform/Apple/Native/CGImage.cs
osu.Framework/Platform/Apple/Native/CGImageAlphaInfo.cs
osu.Framework/Platform/Apple/Native/CGPoint.cs
osu.Framework/Platform/Apple/Native/CGRect.cs
osu.Framework/Platform/Apple/Native/CGSize.cs
osu.Framework/Platform/Apple/Native/Interop.cs
osu.Framework/Platform/Apple/Native/NSData.cs
osu.Framework/Platform/Apple/Native/NSMutableData.cs
osu.Framework/Platform/MacOS/MacOSGameHost.cs
osu.Framework/Platform/MacOS/MacOSTextureLoaderStore.cs
osu.Framework/Platform/MacOS/Native/NSImage.cs

Improves texture loading time by a magnitude. Shares most implementation with iOS.

Add native macOS image loading support

---

osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
osu.Framework.Tests/Visual/Containers/TestSceneScrollContainerDoublePrecision.cs
osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
osu.Framework/Graphics/Containers/ScrollContainer.cs

This is the first step towards supporting scrolling over very large amounts of content. With this along, the animation already becomes somewhat smoother (no longer "locking" into place too early) but scroll content will still look jagged when scrolled too far down.
Fixing actual content requires a small amount of extra implementation on top of this. To keep things simple this would be up to the consumer to implement and maintain.
Intended to help fix osu! song select from becoming weird when hundreds of thousands of beatmaps are loaded.
A sample implementation is provided in `TestSceneScrollContainerDoublePrecision`.
master with a `BasicScrollContainer`:
https://github.com/user-attachments/assets/30195f3d-df1d-436b-8350-b7307653d767
This PR with a `BasicScrollContainer`: …

Use `double` in `ScrollContainer` for scroll tracking

---

osu.Framework/Graphics/Containers/ScrollContainer.cs

In line with other changes, this should have been switched to `double`. Also making `virtual` for usage within the beatmap carousel (I need to extend what this function does for this usage).

Change `OffsetScrollPosition` to take a `double`

---

osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
osu.Framework/Platform/Apple/Native/Class.cs
osu.Framework/Platform/Apple/Native/NSArray.cs
osu.Framework/Platform/Apple/Native/NSAutoreleasePool.cs
osu.Framework/Platform/Apple/Native/NSData.cs
osu.Framework/Platform/Apple/Native/NSMutableData.cs
osu.Framework/Platform/Apple/Native/NSNotificationCenter.cs
osu.Framework/Platform/Apple/Native/NSString.cs
osu.Framework/Platform/Apple/Native/Selector.cs
osu.Framework/Platform/MacOS/MacOSClipboard.cs
osu.Framework/Platform/MacOS/MacOSTextureLoaderStore.cs
osu.Framework/Platform/MacOS/SDL2MacOSWindow.cs
osu.Framework/Platform/MacOS/SDL3MacOSWindow.cs

- Fixes recent segmentation fault on game exit since https://github.com/ppy/osu-framework/pull/6475
This is caused by the fact that the allocated `NSMutableData` object in the loading process is manually released whilst internally marked as auto-released (it is marked as auto-released because it is created using a convenience constructor, read https://stackoverflow.com/a/24807570 for more info (not owning the object essentially means the object itself is queued in the active auto-release pool).
To fix this in an obj-c friendly way, interop for `NSAutoreleasePool` is added and used in places where `NSData` is allocated, and the method to manually release `NSData` is removed as incorrect practice. I've also updated iOS code accordingly as it is generally better to have a local autorelease …

Fix incorrect release pattern in macOS/iOS texture loading code

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Input/TextInputProperties.cs
osu.Framework/Platform/SDL3/SDL3Window_Input.cs

Noticed while testing iOS. I cannot think of a single occurrence where we do want automatic capitalisation to be applied to user text input in osu!. One may say this should be disabled in `OsuTextBox` instead, I can move the default value there if that's preferred.

Disable auto-capitalisation in textboxes

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextInputProperties.cs

The added test scene is purely interactive, there are no automated tests.
Useful for checking how a OS platform shows the different text input types.

Add simple `InputProperties` / `TextInputType` test

---

osu.Framework/Graphics/DrawableExtensions.cs

I think it can be useful to be able to use this method outside the framework. For example, I need it for this : 
```
bool sliderDraggedInItself = inputManager.DraggedDrawable.IsRootedAt(this);
if (Expanded.Value || IsHovered || sliderDraggedInItself)
{
// Do things
}
```
Detailed example : https://github.com/ppy/osu/pull/31596

Change IsRootedAt method from internal to public in DrawableExtensions

---

osu.Framework.iOS/IOSFilePresenter.cs

- Closes https://github.com/ppy/osu-framework/issues/6487
Displays at the top-left corner for now, embedded with explanatory notes. Ensured iOS is still working fine.

Fix file presentation on iPadOS not working

---

osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneTemplateGameGame.cs
osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestSceneFlappyDonGame.cs
osu.Framework/Testing/TestScene.cs

See [test failures in relevant PR](https://github.com/ppy/osu/pull/31417).

Fix `SetupLogging` not being called in game test scenario

---

.github/workflows/ci.yml

See https://github.com/ppy/osu/pull/31633 for reasoning.

Roll back windows build image to 2019 on android build job

---

osu.Framework/Input/TextInputType.cs
osu.Framework/Platform/SDL3/SDL3Extensions.cs
osu.Framework/Platform/SDL3/SDL3Window_Input.cs

Very minor one, but also quite easy to implement so might as well. To be used for the two-factor authentication textbox in osu!, which I found quite weird to suddenly show a bar suggesting English words.

Add text input type for alphanumeric code

---

osu.Framework.iOS/IOSGameHost.cs
osu.Framework/Platform/GameHost.cs

- Reverts part of https://github.com/ppy/osu-framework/pull/6407
- Keeps the override in `SDLGameHost` as-is, as I think it's still good for any case of running the game on a 3-in-1 laptop with keyboard detached (assuming windows will slide up a software keyboard on any request of text input).
This introduced horrible UX in reality, contrary to what I thought and have seen when I added this. It seems I have not tested this enough back then.
While the on-sceren keyboard hides when a hardware keyboard is connected, it can be brought back, and once it's back, it does not hide again until the user explicitly hides it again. 
This introduces very weird / ugly behaviour when combined with a `FocusedTextBox` on osu!, e.g.:
https://github.com/user-attachments/assets/46dd8ea4-7abd-40ea-aae1-bf9839f …

Revert changes to `OnScreenKeyboardOverlapsGameWindow` on iOS

---

osu.Framework/FrameworkEnvironment.cs
osu.Framework/Platform/SDL3/SDL3Extensions.cs
osu.Framework/Platform/SDL3/SDL3Window.cs
osu.Framework/Platform/SDL3/SDL3Window_Input.cs
osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
osu.Framework/osu.Framework.csproj

- Supersedes #6484
- Closes https://github.com/ppy/osu/issues/28254
- Closes #6291
- Closes https://github.com/ppy/osu/issues/28223
- Closes https://github.com/ppy/osu/issues/30641
- Resolves the soft dependency for https://github.com/ppy/osu-framework/pull/6498#discussion_r1923227642
---
Depends on:
**This PR will make SDL3 the default option**, see https://github.com/ppy/osu/issues/30641#issuecomment-2581695099. `OSU_SDL3=0` can be set to use SDL2.
---
Issues to check after this SDL3 update propagates to osu!:
- https://github.com/ppy/osu/issues/28222
- https://github.com/ppy/osu/issues/28279
- https://github.com/ppy/osu/issues/28259

Update SDL3, bringing in support for Windows Ink pen input, and enable it on desktop platforms once again

---

osu.Framework/Graphics/UserInterface/TextBox.cs
osu.Framework/Input/TextInputType.cs
osu.Framework/Platform/SDL3/SDL3Extensions.cs

Required to (fix) https://github.com/ppy/osu/issues/31568.
Specifying a `Number` input type broke editor textboxes due to the type disallowing decimal characters from being entered. This disability is applied internally within `TextBox` and is not overridable with `CanAddCharacter` (rightly so).
As a proper fix for this, a specific input type for decimal numbers is added to support this. It has also came to my attention that displaying the software keyboard on iOS on a textbox that uses `TextInputType.Number` does not show a decimal button, which suggests that it is a good choice to add a different input type for decimal numbers. Unfortunately there's no corresponding SDL input type for decimal numbers, so this new input type is interpreted as "regular text" in SDL.
In other words, using …

Add input type for decimal numbers

---

osu.Framework/Graphics/Shaders/ShaderManager.cs

This should allow shader files to be loaded, regardless of filename extension, as long as it's specified when using dependency injection. Otherwise, default to vs and fs for vertex and fragment shader respectively. ("sh_" prefix is still required)
The exception message is updated as well.
This might be a small change that might not matter to a lot of people since they can just follow as instructed and use the hardcoded filename extension, but it doesn't feel right to force people to accept on someone else's preference on something subjective IMO

Don't force fs and vs shader file extension if shader load argument string already includes file extension

---

osu.Framework.iOS/IOSGameHost.cs

- Closes https://github.com/ppy/osu/issues/31727
Can be reproduced by changing threading mode to multi-threaded then export a file and click on it. Oversight from my end.

Fix iOS file presentation code not scheduled to main thread

---

osu.Framework/osu.Framework.csproj

- Huion H1061P
- Huion Kamvas 13 (Gen 3)
- Wacom DTH-135
- XP-Pen Artist 10S
- XP-Pen Artist 24
- XP-Pen Deco mini7 V2
- XP-Pen Deco 01 V3
- XP-Pen Star 02
- Add identifier and fix dimensions to Huion RTP-700
- Add support for new firmware of RTS-300
- Add support for 16k pressure variant of Gaomon M8
- Fix tilt for Huion H1061P
- add support of Huion 420 with null characters
- Add wireless support for Wacom CTC-6110WL
- Add linux support to Huion H610 Pro V3
- config/Huion Kamvas Pro 13: Add an additional device string
- Add identifier for Gaomon PD2200
- config/UGEE M708 V2: Fix dimensions and add new identifier
- Add support for variant of Huion Q630M
- Add string for kamvas pro 13
- Change H610 Pro V3 regex to support null character variants
- Add support for variant of XP-Pen Star …

Update OpenTabletDriver to 0.6.5.1

---

osu.Framework.Benchmarks/BenchmarkAsyncDisposal.cs
osu.Framework/Allocation/AsyncDisposalQueue.cs
osu.Framework/Statistics/GlobalStatistic.cs

I noticed that the majority of the time being spent in async disposal was actually on getting the readable type...
Before:
| Method |     Mean |     Error |    StdDev |     Gen0 |    Gen1 | Allocated |
|------- |---------:|----------:|----------:|---------:|--------:|----------:|
|    Run | 1.318 ms | 0.0263 ms | 0.0571 ms | 248.0469 | 11.7188 |   1.98 MB |
After:
| Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|------- |---------:|---------:|---------:|-------:|----------:|
|    Run | 547.0 us | 10.87 us | 15.24 us | 8.7891 |   78.7 KB |

Reduce overhead of async disposal

---

osu.Framework/Testing/TestScene.cs

See https://github.com/peppy/osu/commit/aa329f397e684f41e5ca040d4d33a13026d464a5
Arguably this impairs the ability to leave them specified locally while running headless tests, but I don't think this is a blocker.

Fix `[Solo]` attributes getting committed by blocking from NUnit runs

---

osu.Framework.iOS/GameApplicationDelegate.cs

- Probably closes https://github.com/ppy/osu/issues/31687
I'm surprised that .NET does not warn against this, but apparently I was overriding an older version of the method which was long deprecated since iOS 9. The functionality is still there and working except for that specific user, and I'm not sure why.
I'm not 100% sure that this would fix the issue above but it fulfills what the error message stated:
```
Application has LSSupportsOpeningDocumentsInPlace key, but doesn't implement application:openURL:options: on delegate <AppDelegate: 0x302991dc0>
```
Note that it's bizarre for the error message to include `LSSupportsOpeningDocumentsInPlace` since we actually have set that to false, but the error itself is surrounded in an exception typed `NSInternalInconsistencyException`, so maybe …

Fix iOS URL handling overriding deprecated method

---

osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs

- Closes https://github.com/ppy/osu-framework/issues/6525
For some reasons, the Input Device Tree's `Disconnected` event is being called, causing `Driver` to `Dispose()` of the Output Mode.
What comes with that is `entryElement` (The first element called in the tablet input pipeline), being nulled.
In this situation, `entryElement` is `AbsoluteOutputMode`'s `Consume()`.
So what happens if you null it but never set it back ?
Well, tablets inputs not going down the pipeline & position being set.
Normally, the a new output mode would be instanciated for each devices, but that's not the case in the integration.
Either you override `Dispose()` in `AbsoluteTabletMode` with nothing, OR you instanciate a new `AbsoluteTabletMode` object (as should be done), after the detection process.
1. …

Fix Tablet Inputs

---

osu.Framework.Tests/Clocks/InterpolatingFramedClockTest.cs
osu.Framework/Timing/InterpolatingFramedClock.cs

I forgot that this was the whole point of removing the obsoleted methods in #6528.
Of note, I've move the `Rate` calculation out to be local so that `AllowableErrorMilliseconds` can be a simple settable property.

Seal `InterpolatingFramedClock`

---

osu.Framework.Android/AndroidGameWindow.cs

This was a workaround for https://github.com/libsdl-org/SDL/issues/9592, which was fixed by https://github.com/libsdl-org/SDL/pull/9926.
Spotted this no-longer-necessary code in https://github.com/ppy/osu-framework/pull/6462#discussion_r1957322742. With this removal, https://github.com/ppy/osu-framework/pull/6462/commits/03934bcd19f541ba8d410919e023031aab34fa1f is no longer necessary.
Tested to work as expected on my phone.

Remove Android SDL3 workaround code 

---

osu.Framework/Platform/SDLGameHost.cs

Creating it in SDL2 (when `OSU_SDL3=0`) would [disable the handler](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/GameHost.cs#L1159-L1163) since it fails to initialise on SDL2. We don't want the handler disabled as that is stored to config, and osu! doesn't show it in settings (no way for users to enable it in the GUI).
The handler only works with SDL3.
Spotted by @Joehuu [on discord](https://discord.com/channels/188630481301012481/589331078574112768/1341901014755967079).

Only create `PenHandler` on SDL3

---

osu.Framework/FrameworkEnvironment.cs

Pending upstream fixes for external tablet driver support.

Disable SDL3 (windows) desktop default for now

---

osu.Framework/Platform/SDL2/SDL2Window.cs
osu.Framework/Platform/SDL3/SDL3Window.cs

Only really useful on Linux, to show if SDL is using `x11` or `wayland`.

Log SDL video driver

---

osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs
osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs

Adds a bindable to set a threshold for the minimum tablet pen pressure required to click for opentabletdriver.
Worth noting that, on my setup, there is some interference from the systemwide tablet drivers. Specifically, tapping produces a click for one frame, regardless of pen pressure, and I can confirm this comes from the outside drivers since disabling clicking there removes the issue. Though, I wouldn't be surprised if this is an issue with my Linux setup specifically.
Untested on Windows, MacOS, iOS, or Android.

Add tip pressure to click threshold to tablet handler configuration

---

osu.Framework.Benchmarks/BenchmarkTextFlowContainer.cs
osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
osu.Framework/Graphics/Containers/FlowContainer.cs
osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
osu.Framework/Graphics/Containers/TextFlowContainer.cs

- Closes https://github.com/ppy/osu-framework/issues/5084
- Closes https://github.com/ppy/osu-framework/issues/5499
- Closes https://github.com/ppy/osu-framework/issues/2073
- Closes https://github.com/ppy/osu/issues/8580
- Supersedes / closes https://github.com/ppy/osu-framework/pull/5507
You might ask why I'm bothering to try this now. Well, this came up when I wanted to use text flow for BSS purposes (and forced me to hack around it), and came up again in https://github.com/ppy/osu/pull/31970, and I'm sick of it.
The actual fix is taken verbatim from https://github.com/ppy/osu-framework/pull/5507, it's just restructured using the idea of a single nested flow taken from https://github.com/ppy/osu-framework/pull/5507#discussion_r1023426911.
Game side changes available for preview at …

Fix `TextFlowContainer` not laying text out properly on some `TextAnchor` settings

---

osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
osu.Framework/Graphics/UserInterface/TextBox.cs

Fixes #6483 
https://github.com/user-attachments/assets/53665dce-9788-4f94-9dd0-e3a4dc8ecb35

Adjust GetBackwardWordAmount and GetForwardWordAmount to take symbols into account

---

osu.Framework/Audio/BassRelativeFrequencyHandler.cs

Fixes https://github.com/ppy/osu/issues/32321
Well... It's not every day we encounter a bug with about 9 years of history. This goes all the way back to osu!framework's initial commit, but going further than that it was added in the transitional period here: https://github.com/peppy/osu-lazer-transitional/pull/168
It's a non-descript change that is probably hoping the inline documentation is enough. In this case it's not enough because we don't use (and have never used, even in the above commit) BASS.NET which is the alternative C# wrapper to ManagedBass.   
The official documentation (https://www.un4seen.com/doc/#bass/BASS_ATTRIB_FREQ.html) makes no mention of such limitation. [`osu-stable`](https://github.com/peppy/osu-stable-reference/blob/996648fba06baf4e7d2e0b248959399444017895/osu!/A …

Remove `TrackBass` frequency clamping

---

osu.Framework/Graphics/Containers/TextFlowContainer.cs

Fixes one part of https://github.com/ppy/osu/issues/32348.
The reason this is required is due to the game-side abuse done by `DrawableLinkCompiler` & co. See [this game-side crime](https://github.com/ppy/osu/blob/4633f635a4137d6af902187e12d6fc360bc3a50d/osu.Game/Graphics/Containers/LinkFlowContainer.cs#L141-L144).
`FillFlowContainer` performs layout computations on `FlowingChildren` specifically:
https://github.com/ppy/osu-framework/blob/1ccf0376c4306cb4077d0e3230f60efb92ea7803/osu.Framework/Graphics/Containers/FillFlowContainer.cs#L113
Because of this, if using `Flow.Children` in `TextFlowContainer`, the `DrawableLinkCompiler` - which was skipped by the inner fill flow - is now being considered for layout at the text flow level. Text flow sees that the X position of the compiler is 0 …

Only consider flowing children when performing layout of text flow

---

osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs

Closes https://github.com/ppy/osu/issues/32132.
Arguably we don't want to handle movement events as well in this scenario. Need someone to test with a tablet and see which feels more correct.

Fix tablet buttons being handled when window is not active

---

osu.Framework/Game.cs

It's disabled by default so it won't affect anyone, and I've just learned of a method where I can launch a release build of an iOS app with specific envvars:
```
mlaunch --devname "<device name>" --killdev sh.ppy.osulazer --launchdev ./osu.iOS.app --wait-for-unlock --argument=-connection-mode --argument=usb -sdk 13.4 --setenv:OSU_ENVVAR_GOES_HERE=1 --sdkroot /Applications/Xcode.app/Contents/Developer
```
It's dodgy but it works so I'll use it while I can.

Allow usage of "frame statistics via touch" envvar on release builds

---

osu.Framework/Platform/SDL3/SDL3Window.cs

- Closes https://github.com/ppy/osu-framework/issues/6489#issuecomment-2716480865
This PR changes the buggy workaround introduced in ff2ee9db1de3c44aa5b185477bd12e9a847bc5e0 to only apply when the user is not holding left click. I.e. if the user is holding left click (when resizing the window), windowed size will be stored to config.
https://github.com/ppy/osu-framework/pull/6264#issuecomment-2070857205 should not regress with this change. The user is unlikely to be holding left click when changing the window mode to borderless:
- <kbd>F11</kbd> and <kbd>Alt</kbd>+<kbd>Enter</kbd> don't work when holding left click
- if using the dropdown, the selected window mode is only applied after releasing left click.
Please test it with of! Tests → Platform → Borderless. If you hold left click, the …

SDL3: Add hack to make resizing store windowed size to config

---

osu.Framework/Graphics/Containers/FlowContainer.cs

This is one of two safeties to alleviate performance issues described in https://github.com/ppy/osu/issues/32474.
Hoping this can be considered acceptable to fix cases like this:
https://github.com/user-attachments/assets/005c53ce-4134-4fe6-bd61-457b6435c05f
I've done ~2 hours of due diligence investigation and don't see there being a better fix for this.
I will note that:
- It's not `ScrollContainer` related – in this case the `Current` and `Target` are in a stable state
- This cyclic case only happens when `Padding` [is non-zero](https://github.com/ppy/osu/blob/cca63b599eb3b0f57ef23abf582884003ae7d3af/osu.Game/Rulesets/Edit/ExpandingToolboxContainer.cs#L34). This is likely due to [this line](https://github.com/ppy/osu-framework/blob/024fd0b437c7c846d10eedd03db3f6122b49f0a1/osu.Framework/ …

Avoid fill flow layout flipping between floating point precisions

---

osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
osu.Framework/Graphics/Containers/FillFlowContainer.cs
osu.Framework/Graphics/Containers/FlowContainer.cs
osu.Framework/Graphics/Containers/TextFlowContainer.cs

RFC. This probably needs more testing but I want to see what the initial review reaction to this is going to be.
Fixes https://discord.com/channels/90072389919997952/1327149041511043134/1351809773510590494. Probably also the issue mentioned in https://github.com/ppy/osu/pull/32475#issue-2934297971, but I haven't checked.
Essentially what's happening here is that new lines have weird sizing rules wherein the height of the new line is relative to the height of the line preceding it. https://github.com/ppy/osu-framework/pull/6545 broke this because prior to it, the lines responsible for this, namely
https://github.com/ppy/osu-framework/blob/769a5d5803709a99ef92503d08c192f13e7d913e/osu.Framework/Graphics/Containers/TextFlowContainer.cs#L448-L452
ran in …

Fix text flow container layout changing after one frame in some cases

---

osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
osu.Framework/Graphics/UserInterface/SliderBar.cs

Fix second button click moving slider while dragging

---

osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
osu.Framework/Graphics/Containers/TextFlowContainer.cs

Closes https://github.com/ppy/osu/issues/32861.

Fix incorrect text flow layout with non-left anchors when line breaks at last word of paragraph

---

osu.Framework.Tests/Bindables/BindableBindingTest.cs
osu.Framework/Audio/AdjustableAudioComponent.cs
osu.Framework/Bindables/AggregateBindable.cs
osu.Framework/Bindables/ValueChangedEvent.cs

There's very little reason for this to be a class.
It is constructed by each bindable locally when it has listeners, and generally never modified or passed further. Changing to a struct reduces GC overhead.
(honestly we shouldn't be firing these enough for it to be an issue in the first place, but there's some egregious usage of bindables in the game which needs further consideration to fix, and this may alleviate things somewhat).
Not sure whether this needs profiling. A well structured benchmark may show lower GC counts, but allocations should not change.
osu!-side changes:
```diff
diff --git a/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs b/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
index 2cd8e45d28..d9c7ee3ffd 100644
--- …
```

Change `ValueChangedEvent` to a `struct`

---

osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
osu.Framework/Statistics/FrameStatistics.cs
osu.Framework/Statistics/PerformanceMonitor.cs

Could provide some insight into GC performance? Not sure about the colour (conflicts with `Scheduler`) - tried to make it visually distinct from `Work`...
https://github.com/user-attachments/assets/ce86c810-fd20-4705-81ff-4b3b453ffe2b
Satori GC for comparison:
https://github.com/user-attachments/assets/23078de2-e6d3-4d12-8ba4-2e74f37c1978

Show GC pause duration in frame statistics graphs

---

osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
osu.Framework.Tests/Visual/Testing/TestSceneManualInputManagerTestScene.cs
osu.Framework/Input/PassThroughInputManager.cs
osu.Framework/Testing/ManualInputManagerTestScene.cs

- Closes https://github.com/ppy/osu/issues/28384
Assume a parenting `InputManager` A and a child `PassThroughInputManager` B.
On the first frame where B is a child of A, the following sequence of events occurs:
1. `InputManager` is a `CompositeDrawable`. `CompositeDrawable`s update themselves before updating children. As such, A updates itself first.
2. As part of its update logic, A grabs all pending inputs to be processed.
3. The collected pending inputs are "applied to current state". The process of "applying to current state" is equivalent to passing the input to the appropriate input queue in order, until a drawable handles the input.
4. While B at this point is a child of A, it is not yet `LoadState.Loaded`, because `LoadComplete()` runs as part of the first `UpdateSubTree()` call …

Fix passthrough input manager mouse position being desynced from parent on first frame

---

osu.Framework/Audio/Track/Waveform.cs

Today I found some weird test failures on my machine to the tune of:
Failed TestMultipleAudioFiles [433 ms]
Error Message:
System.AggregateException : One or more errors occurred. (Index was outside the bounds of the array.)
----> System.IndexOutOfRangeException : Index was outside the bounds of the array.
Stack Trace:
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at osu.Framework.Extensions.TaskExtensions.WaitSafely(Task task) in /Users/bdach/Documents/Work/open-source/osu-framework/osu.Framework/Extensions/TaskExtensions.cs:line 22
at osu.Framework.Testing.TestScene.checkForErrors() in /Users/bdach/Documents/Work/open-source/osu-framework/osu.Framework/Testing/TestScene.cs:line 519
at …

Improve reliability of waveform disposal

---

osu.Framework.Tests/Audio/SampleBassInitTest.cs
osu.Framework/Audio/Sample/ISample.cs
osu.Framework/Audio/Sample/Sample.cs
osu.Framework/Audio/Sample/SampleBass.cs
osu.Framework/Audio/Sample/SampleBassFactory.cs
osu.Framework/Audio/Sample/SampleVirtual.cs

Closes #6399 
Exposes the length of the underlying `SampleBaseFactory` on `SampleBass`. 
The length may not be immediately available since initialization happens on the audio thread (brief discussion about that about that on [discord](https://discord.com/channels/188630481301012481/589331078574112768/1375503628126781642)).

Populate sample length in `SampleBass`

---

osu.Framework/Input/PassThroughInputManager.cs

You'll probably wisely ask "what is this title? isn't that the tail wagging the dog?" It is. `PassThroughInputManager` usage in `RulesetInputManager` sucks. It should not exist. https://github.com/ppy/osu-framework/pull/6579 broke game-side osu! touch input mapping (see [test failures](https://github.com/ppy/osu/actions/runs/15438536705/job/43453184186)) because the touch input mapping wants to do its bespoke mouse position logic on top of `PassThroughInputManager`.
It is my firm belief that `RulesetInputManager` should stop using `PassThroughInputManager` and instead roll its own bespoke logic. But I am not going to do that here, because I want to put a framework release out now rather than in a week, so this attempts to roll out the fix in https://github.com/ppy/osu-framework/pull/6579 …

Fix passthrough input manager so that it works again with game-side usages

---

osu.Framework.Tests/Visual/Testing/TestSceneTestWithSource.cs
osu.Framework/Testing/TestBrowser.cs

Breakage noticed in `TestSceneOsuTooltip` on test browser, specifically a test backed by a `TestCaseSource` attribute which points to an array of `string`s. Included similar test in `TestSceneTestWithSource`.
To explain briefly why that breaks with the current code: `string` implements `IEnumerable<char>`, and the logic we have treats types with `IEnumerable` specially and assumes it's an enumerable of multiple parameters per test case, meanwhile in this case the test only intends to accept a single `string` parameter.
Regardless, I've rewritten the entire logic to just rely completely on NUnit and not reinvent the wheel with parsing the attribute.

Rewrite `TestCaseSource` attribute implementation to fix edge cases

---

osu.Framework/osu.Framework.csproj

These are expected to be transitively provided by the `ppy.Veldrid.SPIRV` nuget package.

Remove `libveldrid-spirv` libs from Android package

---

osu.Framework/Development/DebugUtils.cs
osu.Framework/Platform/HeadlessGameHost.cs
osu.Framework/Timing/DecouplingFramedClock.cs

I don't know how to push this change in any reasonable fashion (please suggest alternatives), and I'm aware of concerns:
- Introduction of a static.
- I don't know how to get around this.
- Introduction of a reference (which potentially holds inner references to GameThread and the rest of everything)
- I figure this is fine because it's cleared on every `TestScene` init.
- Using a single reference clock or non-zeroed clock across all instances.
- I figure this to be fine because code is only relying on the elapsed time rather than using the reference clock's current time as-is.
Practically all current gameplay tests have a lead-in time of up to/usually ~2s, see: https://github.com/ppy/osu/blob/321707590ab51333ce86a0b1198592705603cdb4/osu.Game/Rulesets/UI/DrawableRuleset.cs#L64
During this …

Use test clock as reference for decoupling clock

---

osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
osu.Framework/Timing/DecouplingFramedClock.cs

Handles a scenario discovered with recent changes to make reference time run faster during headless testing. Here's two scenarios and how they handled with previous code (before this PR).
✅ working:
```
decoupled.CurrentTime = 1000
decoupled.seek(-15)
"can source run?" no
"okay we'll enter decoupled mode"
decoupled.processFrame();
"okay our exposed currenttime is now -15"
sleep(17);
decoupled.processFrame();
"moving from -15 to 2"
"time crossed 0, let's try starting the source"
```
❌ fail case:
```
decoupled.CurrentTime = 1000
decoupled.seek(-15)
"can source run?" no
"okay we'll enter decoupled mode"
// decoupled.processFrame(); <-- not called
"our exposed currenttime is still 1000"
sleep(17);
decoupled.processFrame();
"moving from 1000 to 2"
"no need to attempt starting the source track …
```

Fix `DecouplingFramedClock` not starting source in edge case scenario

---

osu.Framework/Audio/Sample/ISampleChannel.cs
osu.Framework/Audio/Sample/SampleChannel.cs
osu.Framework/Audio/Sample/SampleChannelBass.cs

This PR provides an option to change behavior of `IsAlive` in SampleChannel. To make auto-free work, https://github.com/ppy/osu-framework/pull/6397 is required.
If `ManualFree` is false (default), it works the same as before: `IsAlive` will be false after `Stop` or the end of playback.
If `ManualFree` is true, `IsAlive` will never be true until the user explicitly calls `Dispose`.
It also contains a fix for an issue where calling `Play` after disposal makes `Playing` true.

Add an option to change behavior of `IsAlive` in SampleChannel

---

osu.Framework/Audio/Track/TrackBass.cs

Fixes https://github.com/ppy/osu/issues/34307
Fixes https://github.com/ppy/osu/issues/34294
Should also fix https://github.com/ppy/osu/issues/34307#issuecomment-3094666882 (I spied this one happening to me out the corner of my eye)
Follow-up investigation to the issue above, the user claims this happens on any OGG output by this tool: https://github.com/Tyrrrz/YoutubeDownloader. I haven't verified that claim, though it should be a good repro for those wanting one, without me having to upload copyrighted content here.
I tested with the user's original track.
It looks like this is a mixer issue. I didn't manage to make a repro for it other than empirically testing in the editor. My test was:
1. Seek to 0.
2. Play and pause the track immediately.
3. Seek +30s.
4. Play ---> error should occur …

Gracefully handle errors when retrieving track position

---

osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
osu.Framework.Tests/Clocks/InterpolatingFramedClockTest.cs
osu.Framework/Timing/DecouplingFramedClock.cs

Likely not the main cause of clock drift that some users are reporting, but noticed this logic fallacy during testing.
When frames are run often enough, there is a compounding error caused by querying the source clock's time twice in the decoupled update method, losing a small amount of time each iteration. The test scene added shows a worst case scenario when `Thread.Sleep` is zero, resulting in 10%+ drift.
Luckily, the more important interpolating clock does not suffer from a similar issue.

Fix decoupling clock drifting during decoupled mode execution

---

osu.Framework/Timing/InterpolatingFramedClock.cs

This should largely alleviate any remaining concerns of stutters due to https://github.com/ppy/osu/issues/22488. It's not an absolute fix, but it's a no-brainer improvement which requires much less thought.
In testing, on both windows and macOS the delay for bass to start playback is around 10 ms. If there is no interpolation, this would cause a 10 ms stutter.
I've confirmed that interpolation *does* alleviate this already. The problem is that depending on the update frame rate, it doesn't do a great job.
With this change, the drift is spread out over multiple frames, which should make the issue much less visible to an end user (gameplay will run slightly slower for a brief period rather than outright stopping).
Spreadsheet which can be used to play with half time values: …

Fix interpolating clocks' drift recovery being frame rate dependent

---

osu.Framework/Graphics/Visualisation/ToolWindow.cs
osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs

Also adds a tooltip of the full class name when truncated.
| --- | --- |
| <img width="560" height="661" alt="Screenshot 2025-09-07 at 11 28 37 AM" src="https://github.com/user-attachments/assets/12d1591c-ac4f-4867-a34b-058e1a038b51" /> | <img width="1203" height="664" alt="Screenshot 2025-09-07 at 11 26 10 AM" src="https://github.com/user-attachments/assets/a0b9bb42-9311-4969-8421-6697ff1c50f6" /> |

Truncate drawable class names so that position and size are always visible in draw visualiser

---

osu.Framework/IO/Network/WebRequest.cs

By disabling IPv6 support and retrying the request.
Very targeted, but given the conversation in https://github.com/ppy/osu-framework/pull/6637 should be much safer and better to understand. Given what I've seen of this issue I'm betting this is 99% some apple weirdness.
- Supersedes / closes https://github.com/ppy/osu-framework/pull/6637
- Closes https://github.com/ppy/osu/issues/34654

Work around web request failures on macOS when on networks with no IPv6 support and content filters enabled

---

osu.Framework.Tests/Visual/Performance/TestSceneCircularProgressRingsPerformance.cs
osu.Framework/Graphics/UserInterface/CircularProgress.cs

Closes https://github.com/ppy/osu/issues/33360
In this scene GPU usage on my machine goes from 100% to 25-30% while also being more performant.
|master|pr|
|---|---|
|<img width="1920" height="1080" alt="master" src="https://github.com/user-attachments/assets/d977225d-5bc7-4aa0-be43-8a52a940ba6d" />|<img width="1920" height="1080" alt="osu_2025-10-05_03-46-05" src="https://github.com/user-attachments/assets/e3cfffd8-6eb4-44c1-8b8e-c9a32b08b553" />|
This is a preview of the resulting triangulation:
|||
|---|---|
|<img width="632" height="572" alt="Снимок экрана 2025-10-05 034113" src="https://github.com/user-attachments/assets/9fba8a0b-9113-4b49-87fe-1fba96ad6bf3" />|<img width="569" height="520" alt="Снимок экрана 2025-10-05 034139" …

Implement simple triangulation algorithm for `CircularProgress`
